### ISSUE TITLE
[Feature Request] Implement filter subscription by URL

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#1]
QMK-962-46146

**Comment by Hongbo-Miao** [comment]
Thank you!

**Comment by vbagirov** [comment]
Also mentioned here:
http://forum.adguard.com/showthread.php?10366

**Comment by JayBrown** [comment]
Have a couple of additional filters I'm using with uBlock, so it would be great to be able to subscribe by URL.

**Comment by evgeniy-ADG** [comment]
@Stillness-2 Hi! Do you know when this feature will be ready? We've had a bunch of related requests last week.

**Comment by Stillness-2** [comment]
I can't tell yet.
