### ISSUE TITLE
Supports redirection to the destination, without tracking services as middleman

### ISSUE THREAD

**Issue by imTHAI** [AdguardTeam/AdguardForMac#1001]
Hello,

I would like Adguard support the URL redirect with cleaning the tracking. Like ClearURLs add-on does. 
Indeed both Adguard (with $removeparam I believe ?) and ClearURLs can clean tracking code _after_ the URL 
For example:

`https://example.com?utm_source=newsletter1&utm_medium=email&utm_campaign=sale `
After the address is cleaned, it will look like this:
`https://www.amazon.com/dp/exampleProduct`

**But** clearURLs also cleans in case of redirection. That's the purpose of my request:
For example:
If I click on a link like this one:
`https://dealabs.digidip.net/visit?url=https%3A%2F%2Fwww.amazon.fr%2Fdp%2FB098K16RX5%3Fsmid%3DA1X6FK5RDHNB96&ppref=https%3A%2F%2Fwww.dealabs.com%2Fbons-plans%2Fasus-zenbook-um425qa-14-fhd-amd-ryzen-7-5800h-ram-16go-512-go-w10-azerty-2256311`

With ClearURLs it will be cleaned to:
`https://www.amazon.fr/dp/B098K16RX5?smid=A1X6FK5RDHNB96`

Another example:
`http://track.effiliation.com/servlet/effi.redir?id_compteur=12305754&effi_id=0k003mdl0mwv&url=https%3A%2F%2Ffr.shopping.rakuten.com%2Foffer%3Faction%3Ddesc%26aid%3D9027491774%26productid%3D6956351445`

With ClearURLs it will be cleaned to:
`https://fr.shopping.rakuten.com/offer?action=desc&aid=9027491774&productid=6956351445`

(with Safari/Adguard, it will give me an error page since track.effiliation.com is blocked by my AdguardHome dns server)

Some remarks:
- [Here](https://gitlab.com/anti-tracking/ClearURLs/rules/-/blob/master/data.min.json) is the filter list of ClearURLs that I wish we could adapt into Adguard 
- ClearURLS developers explained [here](https://github.com/ClearURLs/Addon/issues/92) that, other than the $99 for a Apple dev account, they wouldn't be able to port their extension to Safari for now, because of the lack of webRequestBlocking API. 
I imagine AdGuard could do that because it acts "outside" of Safari, doesn't it?
- Someone on Telegram says it would be possible to do the magic in AdGuard with something `#%#AG_onload!function(){window.location.href` but I means nothing to me :p
- I found something similar to my request [here](https://github.com/AdguardTeam/AdguardForWindows/issues/3529) in the Adguard/Windows GitHub. But I'm not sure it's exactly the same.

Thank you,
Best regards,

**Comment by Chinaski1** [comment]
Hello there!

As you correctly pointed out, you can use the `$removeparam` rule to remove tracking parameters.
We have also implemented a [URL Tracking filter](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt) that can be used for this purpose.

**Comment by imTHAI** [comment]
> Hello there!
> 
> As you correctly pointed out, you can use the `$removeparam` rule to remove tracking parameters. We have also implemented a [URL Tracking filter](https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_17_TrackParam/filter.txt) that can be used for this purpose.

Hello,
I'm not sure I understand you answer. You agree $removeparam cannot achieve my purpose right ?

**Comment by ameshkov** [comment]
Ah, I got it.

Well, we were thinking about some sort of a `$rewrite` parameter, but the problem with it is that it can be rather dangerous. We might consider it for trusted filters, though.

@Chinaski1 probably should be moved to the CoreLibs repo.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1557](https://github.com/AdguardTeam/CoreLibs/issues/1557) via [**ZenHub**](https://www.zenhub.com/)
