### ISSUE TITLE
unable use AirDrop

### ISSUE THREAD

**Issue by zqzess** [AdguardTeam/AdguardForMac#1002]
OS: MacOS Monterey 12.0.1

Adguard: 2.6.1.1051 release (CL-1.8.221, DNS-1.6.58)

CPU: M1 Max

bug:  If HTTPS filter is enabled，AirDrop can not use

**Comment by Chinaski1** [comment]
Hello there! @zqzess 

[Fixed](https://github.com/AdguardTeam/AdguardForMac/issues/973) in [beta](http://agrd.io/mac_beta), coming soon and in release.
Sorry for the temporary inconvenience

Stay tuned ;)
