### ISSUE TITLE
Breaks internet connection with Shadowrocket (iOS VPN app)

### ISSUE THREAD

**Issue by ViRb3** [AdguardTeam/AdguardForMac#1006]
### Steps to reproduce

1. Install [Shadowrocket](https://apps.apple.com/us/app/shadowrocket/id932747118) iOS app on a M1 Mac
2. Connect to a VPN server using the app

### Expected behavior
Internet works.

### Actual behavior
Internet does not work unless you disable AdGuard.

`ping` still works, but TCP seem to fail. For example, ssh errors, and HTTP requests result in:
```
$ curl -v google.com
*   Trying 240.0.0.9:80...
* Connected to google.com (240.0.0.9) port 80 (#0)
> GET / HTTP/1.1
> Host: google.com
> User-Agent: curl/7.77.0
> Accept: */*
>
* Empty reply from server
* Closing connection 0
curl: (52) Empty reply from server
```

I suspect this may be a more general issue with iOS VPN apps in general, but I have not found a good way to test that.

### Your environment
macOS 12.0.1
MacBook Pro M1 Max
AdGuard 2.6.1.1051
Shadowrocket  2.1.92 (1451)

**Comment by Chinaski1** [comment]
Sorry for the late reply.

The thing is that at the moment there is no support for compatibility with iOS VPN applications.
We will work in this direction in the near future.

As a workaround, you can try to configure `upstream proxy` in the AdGuard advanced settings section provided that the VPN can operate in proxy mode.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1570](https://github.com/AdguardTeam/CoreLibs/issues/1570) via [**ZenHub**](https://www.zenhub.com/)
