### ISSUE TITLE
Repeating permission requests to create a proxy

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#1007]
### Expected behavior

It is enough to give permission to start a proxy once before the first launch of an application.

### Actual behavior

[Permission](https://uploads.adguard.com/Chinaskinnx6t.png) is requested after each reboot of the operating system.

### Customer ID 
We have two complaints about this issue
`557980`
`550081`

### Your environment

* OS version: BigSur 11.6.1
* AdGuard version:  2.6.1.1051 release
* Logs are attached to the task

**Comment by cryptopatik22** [comment]
Hey guys.
It seems that the issue is back for the same customer, but now he has version 2.9.1 installed. Ticket 693550.
Please advise.

**Comment by cryptopatik22** [comment]
Here are the logs:
[adguard_logs_20221214013547 (1).zip](https://github.com/AdguardTeam/AdguardForMac/files/10254075/adguard_logs_20221214013547.1.zip)
