### ISSUE TITLE
setapp.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForMac#1012]
@adguard-bot commented on [Tue Nov 16 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100308)

### Issue URL (Annoyance)
 [https://setapp.com/ru/apps/openin?utm_campaign=openin_main_banner&utm_content=banner&utm_medium=vendor_program&utm_source=openin](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsetapp.com%2Fru%2Fapps%2Fopenin%3Futm_campaign%3Dopenin_main_banner%26utm_content%3Dbanner%26utm_medium%3Dvendor_program%26utm_source%3Dopenin)
### Comment
Username: `@rakleed`
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/FOwFFad.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.6.1.1051 release
Browser: | Safari
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Hide your Referrer from third-parties (), <br>Hide your User-Agent ()
DNS filtering: | server: `https://dns-unfiltered.adguard.com/dns-query`<br>
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Referrer: | [https://loshadki.app/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Floshadki.app%2F)

---

@zloyden commented on [Fri Nov 26 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100308#issuecomment-979484893)

Не повторяется, куки заблокированы фильтром раздражителей.

---

@rakleed commented on [Fri Dec 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100308#issuecomment-990985625)

@zloyden проверьте в Safari, так как в Chrome у меня также не воспроизводится.

P.S. Правило для блокировки `setapp.com##.cookie-banner` не работает в Safari.

---

@zloyden commented on [Fri Dec 10 2021](https://github.com/AdguardTeam/AdguardFilters/issues/100308#issuecomment-991029749)

@rakleed сейчас у меня тоже повторилось, но только на Маке и дело не в фильтрах. Наш сертификат в Сафари почему-то не применяется на этом сайте, перенесу в соответствующий репозиторий.

**Comment by Chinaski1** [comment]
@rakleed

Данный домен находится в списке специальных исключений `Network extension` режима.
Поэтому он не фильтруется.

**Comment by ameshkov** [comment]
Можно убрать в расширенных настройках. В списке исключений он из-за багов macOS Network extensions, также как и apple.com.
