### ISSUE TITLE
clicking on filtering log will cause AG to freeze

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1013]
### Steps to reproduce

1.open filtering log 
2. click on one of the generated links there

### Expected behavior
AG freezes and stops working
### Actual behavior
AG freezes and stops working

<details><summary>Screenshot:</summary>

https://user-images.githubusercontent.com/40741745/145714347-7a6279cf-454e-4d87-92cc-914a4aca04ab.mp4
</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Application version 2.7.0.1083 beta (CL-1.8.261, DNS-1.6.70) 
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
mac os monterey

here is the pure log of it:
_Logs link is hidden for privacy_

**Comment by sfionov** [comment]
@aliafshany This is probably caused by endless event cycling inside text wrapping code in Cocoa UI library, and we will report it to Apple.

Can you please tell, what monitor do you have?

Does resizing the "Filtering log" window help?

**Comment by aliafshany** [comment]
-it is a 13 inch macbook pro monitor
- yes,it does. it seems when you resize and enlarge it, everything works fine
