### ISSUE TITLE
Crashing on M1 Pro

### ISSUE THREAD

**Issue by LewisLebentz** [AdguardTeam/AdguardForMac#1015]
I've just got a new M1 Pro MacBook Pro, first ARM Mac I have used. I saw you do support Apple silicon, so assumed the M1 Pro would also work too.

I've downloaded the stable/beta/nightly and all of them install successfully but when I go to enable AdGuard it crashes and pops up with a box telling me to contact support, which I just filled in. This is a fresh machine, nothing else installed that might conflict with it.

### Steps to reproduce
1. Install AdGuard
2. Attempt to enable it

### Expected behavior
Ad Blocker enables

### Actual behavior
AdGuard crashes

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/5428939/146185536-b33033af-7e53-462f-aef9-28f30bdb994d.png)

</details>

### Customer ID 
561969

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Monterery 12.0, 14" 2021 MacBook Pro, M1 Pro
* Any specific potentially conflicting software installed: nothing, new machine

**Comment by Chinaski1** [comment]
Hello there!

There seem to be issues running the Network extension.

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

After sending the logs, it is advisable to try restarting the network extension manually:

1. Reboot Mac and enter `recovery mode`.
2. Disable SIP (Launch Terminal from the Utilities menu and type `csrutil disable`)
3. Reboot Mac
4. Close the AdGuard app and open Terminal and type `systemextensionsctl reset`
5. Reboot Mac and enter recovery mode.
6. Enable SIP (Launch Terminal from the Utilities menu and type `csrutil enable`)
6. Launch the AdGuard app and enable protection.​

**Comment by Chinaski1** [comment]
@LewisLebentz 

We checked received log files and information indicate that the system policy prohibits activating the system extension.
This is actually the reason why AdGuard has trouble starting protection since it uses a network extension.

If for some reason you are unable to grant such permissions, you can try running AdGuard in Autoproxy mode.
AdGuard settings -> Network -> Filering mode -> [Autoproxy](https://uploads.adguard.com/Chinaskibcd3q.png)

**Comment by LewisLebentz** [comment]
@Chinaski1 there shouldn't be any policy that blocks system extensions, and I haven't been prompted to allow one either (I would have permission).

I tried changing the mode from network extension to automatic proxy and back to see if anything showed up, but no sysext approvals pending. I'll try reinstalling and see if that makes a difference.

**Comment by Stillness-2** [comment]
@LewisLebentz May be your computer is managed by Jamf or something like that

**Comment by LewisLebentz** [comment]
@Chinaski1 tried a reinstall (deleted all the files [here](https://kb.adguard.com/en/macos/installation)), no luck.

Then turned off SIP and reset the sysext db like you said, still crashes when I attempt to enable it.

@Stillness-2 the device is Jamf managed, I was previously responsible for Jamf and am still an admin there, so know there's no policies blocking it. My previous intel Mac was also managed by Jamf, with no issues.

**Comment by planet0** [comment]
Hmm, how odd. New M1 here with no issues.

- By chance have you already installed Rosetta? `softwareupdate --install-rosetta`
- Is the user an Administrator account?
- Any way to temporarily remove your Profiles in System Preferences to try again?
- Tried to reinstall macOS in-place via `softwareupdate --fetch-full-installer --full-installer-version 12.1`?
- Advance uninstalled AdGuard via [this KB article](https://kb.adguard.com/en/macos/installation#uninstall) and reinstalled the stable version via adguard.com?

Throwing some ideas out.

**Comment by Chinaski1** [comment]
Returning to this issue, I want to reiterate that in the logs there is an error:

`OSSystemExtensionErrorDomain, 10 (forbiddenBySystemPolicy)`

Unfortunately, there is nothing we can do on the AdGuard side to solve it.

You can try to search for a solution by yourself.
