### ISSUE TITLE
AdGuard macOS affect Dropbox website working

### ISSUE THREAD

**Issue by nagahama-chris** [AdguardTeam/AdguardForMac#1018]
AdGuard macOS app affect Dropbox website working correctly
When AdGuard app running on my Mac, Dropbox Web page can not work fine, it will say "there was a problem loading your recommendations, please try again later." Only when I close AdGuard temporarily, Dropbox website can work correctly.
Hope your team could fix out, thx!

**Comment by nagahama-chris** [comment]
<img width="633" alt="error" src="https://user-images.githubusercontent.com/28833497/146768942-6a88747b-bdd9-4c5f-85b8-ea66af511c47.png">
Here on Safari to visit Dropbox Site > All Files, under the bottom of this page will show this. After closing AdGuard temporally, this will not show again.

**Comment by Chinaski1** [comment]
Still not reproduced.

Please, send the log files.

**Comment by Chinaski1** [comment]
@nagahama-chris Any news?
