### ISSUE TITLE
www.messenger.com

### ISSUE THREAD

**Issue by AdamWr** [AdguardTeam/AdguardForMac#1020]
@adguard-bot commented on [Wed Dec 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104095)

### Issue URL (Incorrect Blocking)
 [https://www.messenger.com/desktop](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.messenger.com%2Fdesktop)
### Comment
Username: @planet0
> Request URL
> https://graph.facebook.com/logging_client_events
> 
> Status
> Request blocked.
> 
> Application
> Messenger (com.facebook.archon.developerID)
> 
> Rules
> ||graph.facebook.com/logging_client_events (AdGuard Tracking Protection filter)
> 
> Data type
> Other

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/EQgDNgj.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/1IqBK2w.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)
Browser: | Messenger
Stealth mode options: | 
DNS filtering: | server: `AdGuard DNS`<br>filters: `AdGuard SDNS filter`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances
Userscripts: | disabled

---

@planet0 commented on [Wed Dec 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104095#issuecomment-999416489)

Looks like the Messenger app does not like to be filtered with AdGuard at all as even with `@@||graph.facebook.com/logging_client_events^$other,xmlhttprequest` which allows the connection, it still does not connect. This rule is not the cause of the issue, please ignore everything in the original post.

In Console logs, I see for AdGuard:

`Can't find log object in the pool of an active log objects:[info="tls://edge-mqtt.facebook.com:443", rule="" appName="Messenger"]`

---

@planet0 commented on [Wed Dec 22 2021](https://github.com/AdguardTeam/AdguardFilters/issues/104095#issuecomment-999419736)

Adding `edge-mqtt.facebook.com` to the HTTPS exclusions fixed it.
Is this something we could add by default to the list, or is the domain a privacy/tracking related one?

<img width="812" alt="image" src="https://user-images.githubusercontent.com/65204836/147069079-1367476f-0e18-4778-84e6-2aff01df1139.png">

**Comment by planet0** [comment]
From https://github.com/AdguardTeam/AdguardFilters/issues/104095
Summarised in https://github.com/AdguardTeam/HttpsExclusions/issues/448

> AdGuard cannot filter [Messenger for Desktop](http://messenger.com/desktop) unless `edge-mqtt.facebook.com` is added into HTTPS exclusions.
> 
> <img alt="Screen Shot 2021-12-22 at 8 00 17 pm" width="641" src="https://user-images.githubusercontent.com/65204836/147071055-d3a81b10-be8c-4ee7-bf09-55d5990e663e.png">
> 
>

**Comment by planet0** [comment]
Never mind, the app uses TLS to bypass filtering and so it also wants more domains to be excluded from AdGuard HTTPS filtering... I'll just remove Messenger from AdGuard filtering altogether.

`Can't find log object in the pool of an active log objects:[info="tls://graph.facebook.com:443", rule="" appName="Messenger"]`

`Can't find log object in the pool of an active log objects:[info="tls://web.facebook.com:443", rule="" appName="Messenger"]`
