### ISSUE TITLE
Browser assistant icon goes gray randomly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#1025]
Here's what happens:

1. The native host process notifies the extension that the app is not running anymore
2. The extension stops checking status and the icon goes gray

However, the app is actually running all the time.

![image](https://user-images.githubusercontent.com/5947035/147675991-75aa3d5a-2db2-486c-b229-791e1043895d.png)

**Comment by rakleed** [comment]
@Aydinv13 this problem is relevant again, although it happens much less often. Can you understand what is causing this problem? Since it is difficult to reproduce, and debug logs cannot be recorded.

**Comment by Aydinv13** [comment]
@rakleed 
Ok, we will check, thanks.

**Comment by Aydinv13** [comment]
@rakleed 

No such cases have been noticed on our part. As for the log file, could you please record a fresh one, since these are from version 2.8.1.

**Comment by rakleed** [comment]
If I see that the icon turns gray, should I turn on the debug log or will it not help?

**Comment by Aydinv13** [comment]
The debug log would be better. Thank you.

**Comment by rakleed** [comment]
@Aydinv13 was able to reproduce again, logs sent to devteam@adguard.com
