### ISSUE TITLE
Every time I login/restart, the Adguard window appears and needs to be dismissed. 

### ISSUE THREAD

**Issue by dtoub** [AdguardTeam/AdguardForMac#1026]
### Steps to reproduce

1.Logout or restart your mac
2.After restarting, the full Adguard window appears and needs me to dismiss it
3.
4.

### Expected behavior

What should happen is AdGuard should be enabled at login as desired (as per my preferences), but not open a window. That's distracting and a pain. 
### Actual behavior

Adguard window opens
<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Chinaski1** [comment]
Hello there!

Could you describe in more detail which AdGuard window is opening? Settings? Or a request to create a proxy?
It would be great if you could send a screenshot.

**Comment by dtoub** [comment]
Sure. Settings.

**Comment by Chinaski1** [comment]
Sounds really weird.
So maybe log files can shed some light on this situation.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Chinaski1** [comment]
Any news?

**Comment by Chinaski1** [comment]
Closed due not reply.

**Comment by dtoub** [comment]
Sorry to write but more detail would be helpful. Was this fixed? Is it not going to be fixed? Did it get reproduced?

**Comment by dtoub** [comment]
I did send logs

**Comment by dtoub** [comment]
Here they are again. I sent them to the email address you specified but now I’m sending them here. Frustrating.

**Comment by Chinaski1** [comment]
Unfortunately, I can't find your email with the logs.
Could you please resend it directly to k.gretskyi@adguard.com?

**Comment by dtoub** [comment]
done

**Comment by Chinaski1** [comment]
Got it, thank you.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #680](https://github.com/AdguardTeam/AdGuardForSafari/issues/680) via [**ZenHub**](https://www.zenhub.com/)
