### ISSUE TITLE
Facebook picture upload not working

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForMac#1029]
Uploading picture on facebook.com (messengers online, marketplace) is usually not working on Safari, rarely it works.
The photo never uploads, it just sits there with the progress dots cycling.

All filters, stealth mode, DNS and all extensions are disabled -> not working. 
When disabling HTTPS filtering upload works.

Happens on configs like:
MacOS 10.15.7 (19H1419)
Safari 15.0 (15612.1.29.41.4, 15612)
AdGuard 2.6.1.1051 release (CL-1.8.221, DNS-1.6.58)

Monterey 12.1
Safari 15.2 (17612.3.6.1.6)
AdGuard 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

Monterey 12.0.1
Safari 15.1 (17612.2.9.1.20)
Adguard version 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

Source:

https://forum.adguard.com/index.php?threads/cant-send-or-upload-pictures-on-facebook-safari.45236

I cannot reproduce it myself (also before I updated to nightly newer than stable build above).

**Comment by Chinaski1** [comment]
Also not reproduced on my side.

Thanks for the report, I am asking forum users for more information.

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/CoreLibs #1588](https://github.com/AdguardTeam/CoreLibs/issues/1588) via [**ZenHub**](https://www.zenhub.com/)
