### ISSUE TITLE
Unable to install AdGuard assistant extension

### ISSUE THREAD

**Issue by jimmysofat6864** [AdguardTeam/AdguardForMac#1035]
### Steps to reproduce

1. Install AdGuard 
2. Open Safari Preferences
3. Go to Extensions
4. AdGuard Assistant is not available

### Expected behavior

Switch to enable AdGuard assistant. 
### Actual behavior

AdGuard assistant switch is missing. 

<details><summary>Screenshot:</summary>

![Screen Shot 2022-02-03 at 8 26 00 PM](https://user-images.githubusercontent.com/69532417/152471946-a62c86b1-b075-40b4-9fdd-5ea6b4c1c733.png)
</details>

### Your environment

Safari 15.3
Mac OS Big Sur 11.6.3

**Comment by Chinaski1** [comment]
Hello there!

Looks really weird. Please specify which version of AdGuard you are using?
Have you tried reinstalling the application?

**Comment by jimmysofat6864** [comment]
@Chinaski1 I tried reinstalling and that didn’t work. It is version 2.5.3.955.

**Comment by Chinaski1** [comment]
You should update to the latest release and check again.

https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.7.0.1094

Or via [direct link](https://github.com/AdguardTeam/AdguardForMac/releases/download/v2.7.0.1094/AdGuard-2.7.0.1094-release.dmg).

**Comment by jimmysofat6864** [comment]
Latest version didn’t seem to work as well.

**Comment by Chinaski1** [comment]
Also, you should try сompletely close Safari and launch it again

**Comment by jimmysofat6864** [comment]
That didn’t work either.

**Comment by Chinaski1** [comment]
Sorry for the late reply

We tried to repeat your issue, but it stubbornly refuses to reproduce on dozens of MacBooks.


Please specify at what point the issue began to appear?
After a clean installation of AdGuard or after an update?
Was there an update of the operating system?

Does your legacy extension work as a temporary alternative?

**Comment by jimmysofat6864** [comment]
@Chinaski1 It started to happen after I upgraded Catalina or Big Sur and decided to reinstall AdGuard. It happened after an update but it doesn't work after a clean install either. The legacy extension works sometimes but doesn't always show up on some pages.

**Comment by jimmysofat6864** [comment]
@Chinaski1 is there a way to just force install the extension or install it manually without using the AdGuard Mac client like how on chrome I can download it from the chrome store?

**Comment by Stillness-2** [comment]
@jimmysofat6864 do extensions from other apps show up in safari?

**Comment by maxikuzmin** [comment]
@jimmysofat6864 question is still relevant?

**Comment by jimmysofat6864** [comment]
No new version solves this

**Comment by maxikuzmin** [comment]
@jimmysofat6864 update don't help to you?

**Comment by jimmysofat6864** [comment]
Yes that is right

**Comment by maxikuzmin** [comment]
@jimmysofat6864 what version of AdGuard are you currently using? What version of the OS? Check also Safari updates. 
We are still unable to reproduce your problem.
Could you please record a video describing the problem and attach a link? You can also email the video to devteam@adguard.com

**Comment by jimmysofat6864** [comment]
Alright new version seems to fix this this can be closed now

**Comment by maxikuzmin** [comment]
@jimmysofat6864 great news! Good luck!
