### ISSUE TITLE
scriptlet user rule not working

### ISSUE THREAD

**Issue by BottledSoda** [AdguardTeam/AdguardForMac#1036]
### Steps to reproduce

1. Add `powerclicks.xyz#%#//scriptlet("set-constant", "blurred", "false")
**(*##+js(set, ..., ....)* seemingly works as expected)**
2. Visit `https://powerclicks.xyz/P7w6J` and if possible, go to second page/step
3. When out-of-focus, seemingly, the countdown freezes

### Expected behavior

`blurred` should be set to `false` and thus the countdown shouldn't freeze on second page/step on given URL
### Actual behavior

The countdown is seemingly frozen when out-of-focus.

### Your environment

* Environment name and version: (e.g. Chrome 59): Google Chrome 97.0.4692.99 (arm64)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) AdGuard VPN - not sure if it could conflict.

**Comment by BottledSoda** [comment]
> ### Customer ID

I didn't get one after I seemingly sent a bug report via the Support thing.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/Scriptlets #191](https://github.com/AdguardTeam/Scriptlets/issues/191) via [**ZenHub**](https://www.zenhub.com/)

**Comment by stanislav-atr** [comment]
@ghost, hi! Can not reproduce the issue with the latest nightly version of AdGuard for Mac. Could you please try it?
