### ISSUE TITLE
Removing tracking parameters also removes anchor links as well

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#1038]
### Steps to reproduce

1. Enable stealth mode and enable Remove tracking parameters
2. Visit a link such as https://word.rodeo/?utm_source=share#LSXu4huq9DZNoWTuezpG1XmBM6qVSldng1NV56tpEU6Uib79ItmA+aFeJ87VfxVa6c0hD8B3

### Expected behavior
You visit [https://word.rodeo/#LSXu4huq9DZNoWTuezpG1XmBM6qVSldng1NV56tpEU6Uib79ItmA+aFeJ87VfxVa6c0hD8B3
](https://word.rodeo/#LSXu4huq9DZNoWTuezpG1XmBM6qVSldng1NV56tpEU6Uib79ItmA+aFeJ87VfxVa6c0hD8B3
)

### Actual behavior
Entire URL is stripped just to [https://word.rodeo/](https://word.rodeo/) which removes the main content anchor link

### Your environment

* AdGuard for Mac Application version 2.7.1.1108 nightly (CL-1.9.27, DNS-1.6.72)
* Safari Version 15.3 (17612.4.9.1.5)

**Comment by sfionov** [comment]
AG doesn't control anchor links, and browser doesn't remove anchor for redirects. Seems that it is removed by this websites's service worker.

You may add this rule:
```
||word.rodeo/sw.js^
```
And then remove service worker in developer tools console:
```
await navigator.serviceWorker.getRegistrations().then(rs => Promise.all(rs.map(r => r.unregister())))
```

**Comment by planet0** [comment]
That is odd, as when I uncheck 'Remove tracking perimeters' in AdGuard, then the URL works as `?utm_source=share#LSXu4huq9DZNoWTuezpG1XmBM6qVSldng1NV56tpEU6Uib79ItmA+aFeJ87VfxVa6c0hD8B3` isn't removed anymore.

**Comment by planet0** [comment]
That is odd, as when I uncheck 'Remove tracking parameters' in AdGuard then the URL works, as `?utm_source=share#LSXu4huq9DZNoWTuezpG1XmBM6qVSldng1NV56tpEU6Uib79ItmA+aFeJ87VfxVa6c0hD8B3` isn't removed anymore.

Does 'Remove tracking parameters' know to keep the content in the URL from **#**?

It seems to try to remove `?utm_source=share` which is a predefined parameter, but accidentally removes the **#** content as well.

**Comment by sfionov** [comment]
> Does 'Remove tracking parameters' know to keep the content in the URL from #?

AdGuard works at network level, and at network level there's no anchors in URLs.
Browser must restore original anchor after redirect.

But service workers may not do this.

You may check that anchor is not removed on website without service worker, e.g. https://example.org/?utm_source=something#someanchor

**Comment by planet0** [comment]
I understand now, thank you for explaining this @sfionov.
You are right, the example link does keep the anchor even after removing the tracking parameter.

Will we close this as it is not an issue with AdGuard?
