### ISSUE TITLE
Some website completely blocked by adguard

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardForMac#104]
The following website seems to be completely blocked by adguard, even if a whitelist is added:

http://www.osipres.be/

- Chrome + Adguard extension + Adguard Mac :  the website never displays, even when adguard is disabled.

- Safari + adguard extension + adguard Mac : the website is not displayed until adguard for mac is disabled.

**Comment by ameshkov** [comment]
Huh, cannot confirm this in Chrome configuration.

Which filters do you have enabled?

**Comment by ploum** [comment]
After investigation, it seems that it's not adguard fault but some crappy redirections. Sorry for the noise.
