### ISSUE TITLE
Some AG filters don't show any rules

### ISSUE THREAD

**Issue by Quorum75** [AdguardTeam/AdguardForMac#1040]
### Steps to reproduce

1. Open AG base filter 
2. Right window is empty there is no rule.
3.
4.

### Expected behavior
 AG filter should show rules like other filters

### Actual behavior
 Some AG filters are just empty.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49731083/153917164-774978cd-8b03-460a-a66d-f92a45e33e01.jpeg)

### Customer ID 
 578453

### Your environment

macOS 12.2.1 (21D62)
AG Desktop version 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

**Comment by Chinaski1** [comment]
Hello there!

Looks really weird, can you `Check the updates` from the main menu?

**Comment by Chinaski1** [comment]
@Quorum75 

Any updates?
