### ISSUE TITLE
DNS-запросы не доходят после выхода из сна🕵🏻‍♂️

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#1041]
Здравствуйте,

напишу на русском, чтобы быть уверенным, что меня поймут. Конфигурация:
1. MacBook Pro 13" 2017;
2. macOS 12.2.1;
3. AdGuard для Mac 2.7.0.1094;
4. AdGuard VPN 1.1.0.167;
5. DNS-сервер на внешнем VPS на базе AdGuard Home 0.107.3.

При полной разрядке батареи и последующем выходе из "сна" во время зарядки и после восстановления интернет-соединения DNS-запросы идут уже не через клиентский upstream-сервер (мой на базе AdGuard Home), а через DNS-серверы по умолчанию VPN подключения (нефильтрующие AdGuard):

![2022-02-19_00-11-58](https://user-images.githubusercontent.com/45385632/154762840-996cf359-65a5-4150-8f10-394064a4edcb.png)

При этом в логе AdGuard Home этот запрос я вижу, но по факту ответ клиенту не доходит👆🏼Расширенные логи обоих приложений (временная метка на скриншоте по МСК):

[adguard_logs_20220218091311.zip](https://github.com/AdguardTeam/AdguardForMac/files/8100475/adguard_logs_20220218091311.zip)
[adguard_logs_20220218091343.zip](https://github.com/AdguardTeam/AdguardForMac/files/8100476/adguard_logs_20220218091343.zip)

И нет, это не кэш - манипуляции с кэшем и его очисткой не помогают. Лечится перезагрузкой ОС. P.S.: не уверен, что отрепортил в подходящий репозиторий 🤷🏻‍♂️

Спасибо 🚀

**Comment by ameshkov** [comment]
@ammnt а какая версия макоси?

**Comment by ammnt** [comment]
@ameshkov, если не удается воспроизвести, то после разрядки батареи и отключения ноутбука нужно подождать минут 10-15, чтобы гарантированно все сетевые соединения умерли🙅🏻‍♂️

**Comment by ammnt** [comment]
@ameshkov, удалось понять в чём проблема?😒

**Comment by ngorskikh** [comment]
По неясной причине, в некоторый момент времени был заюзан фолбэк-апстрим. Ответ от фолбэк-апстрима попал в кэш, протух, однако в `00:10:21.082` протухший ответ вернулся из кэша, потому что включено оптимистичное кэширование. По той же причине параллельно пошел запрос на нормальный апстрим, чтобы обновить запись в кэше – отсюда запись в логе хомяка.

Вероятно, имеет смысл не кэшировать ответы от фолбэк-апстримов, но надо это обсудить @sfionov @ameshkov

**Comment by ammnt** [comment]
@ameshkov, в результате баг или нет? Удалось понять что-то из логов?

**Comment by ameshkov** [comment]
Да вот не пойму. Ну не баг это по идее то.

Но вообще ситуация с фолбэками странная, может вообще пересмотреть то, как мы с ними работаем? @ngorskikh @sfionov 

Изначально фолбэки были нужны, чтобы нам нормально работать в сетях с кэптив порталом. Но на новых макосах и иосах мы можем использовать (`NWPathMonitor`)[https://developer.apple.com/documentation/network/nwpathmonitor], чтобы отслеживать это и в случае наличия кэптив портала автоматически слать запросы к днс провайдера.

**Comment by ammnt** [comment]
@ameshkov, okay. Касательно алгоритма в целом меня смущает ситуация, когда мы имеем и фолбэки, и обычный кэш, и оптимистичный кэш... Как-то очень много и из этого всего управляется только обычный кэш. И всё это течёт...😅

Я и так выставил 0 TTL и задал IP SDNS-штамп и hosts🤷🏻‍♂️ Если есть возможность сделать это более надежным, то будет здорово.

Спасибо🚀

**Comment by sfionov** [comment]
Идея записана в DnsLibs репозитории, мы изучим, можно ли её реализовать.

Эту задачу закрываю

**Comment by sfionov** [comment]
Идея записана в DnsLibs репозитории, мы изучим, можно ли её реализовать.

Эту задачу закрываю
