### ISSUE TITLE
'install_cert' prompt when switching between user accounts

### ISSUE THREAD

**Issue by samwzlim** [AdguardTeam/AdguardForMac#1043]
### Steps to reproduce

1. Start with a clean installation of AdGuard 
2. Set up AdGuard in a similar way to mine
3. Set up AdGuard on another user with the same settings (create one if you don't already have another user) and enable fast user switching
4. Switch to the first user and notice the prompt appear
5. Switch back to the second user and notice the prompt appearing again

### Expected behavior
A prompt of any form shouldn't appear

### Actual behavior
'install_cert' prompt appears which asks for admin password

<details><summary>Screenshot:</summary>

![IMG_5002](https://user-images.githubusercontent.com/74489037/155251886-bc91396c-137b-4355-b605-3e4e0e71acf1.jpeg)

</details>

### Customer ID 

580500

### Your environment

* Environment name and version: macOS 12.2.1, M1 Pro
* Any specific potentially conflicting software installed: none

**Comment by jstaubr** [comment]
Same behaviour here on nightly. Maybe worse. Install cert prompt appears randomly multiple times a day. Asking for password twice every time. 2.7.1.1108 nightly (CL-1.9.27, DNS-1.6.72)

**Comment by Chinaski1** [comment]
Hello!

The issue is not reproduced on our side.

To troubleshoot this situation, we need to get the app logs.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by samwzlim** [comment]
> 

Done :) Hope I did it correctly.

**Comment by samwzlim** [comment]
> Hello!
> 
> The issue is not reproduced on our side.
> 
> To troubleshoot this situation, we need to get the app logs.
> 
> Here's what we need you to do:
> 
> 1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
> 2. Reproduce the issue and remember the exact time it happened;
> 3. Menu --> Advanced --> **Export Logs and System Info...**;
> 4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

Done :) Hope I did it correctly.

**Comment by ameshkov** [comment]
Just in time, we're reworking this functionality in v2.8.

@Stillness-2 please take a look, can we fix this in v2.8 as well?

**Comment by Chinaski1** [comment]
@samwzlim 

Hello!

I sent you an email yesterday and attached a link to download the raspy logging app.
If you have some free time, please send us the necessary data.

**Comment by samwzlim** [comment]
@Chinaski1 Unfortunately, I am no longer using multiple users on my mac. However, I tried creating a new user today and was unable to reproduce the issue. I suspect it might have been a user space issue.
