### ISSUE TITLE
Tor Browser support

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1045]
Please add Tor Browser support.

**Comment by Chinaski1** [comment]
Actually, I doubt that it is possible to filter tor browser traffic.
 But we will explore this possibility and add support for it if possible.

**Comment by rakleed** [comment]
.

**Comment by Aydinv13** [comment]
@rakleed we've implemented Tor Browser support and this feature is available in the [Nightly](https://agrd.io/mac_nightly) channel, please try it.

**Comment by rakleed** [comment]
@Aydinv13 filtering is now working, tests on https://adguard.com/en/test.html are being passed. Thank you!

But there are a couple of problems:
1. Why does the link to help information about why AdGuard needs permission to change Tor security settings lead to the [AdGuard Knowledgebase main page](https://kb.adguard.com/en)?
2. The [AdGuard Browser Assistant](https://addons.mozilla.org/en-US/firefox/addon/adguard-browser-assistant/) extension does not work, when you open it, the error “AdGuard is not installed or configured incorrectly” appears.

**Comment by Aydinv13** [comment]
@rakleed 
1. This is not the final appearance of the dialog box and will be improved.
2. As for Assistant, you are right, it shows an error but we'll see what we can do.

Thanks for your feedback.

**Comment by vozersky** [comment]
@rakleed

1. Well, this is a nightly channel, the article is not ready yet.
2. Assistant is a different thing, this is not a part of this task, we'll still have to figure it out.

Thanks
