### ISSUE TITLE
TikTok login and browse issue

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1047]
Well, there is a tiktok bug that occurred around a week ago.
TikTok login will not operate if DNS protection is enabled, and you will receive " Too many attemps error".
I tried switching from Adguard to another DNS provider, such as Cloudflare, but the problem persisted.
To login and work with that, the workaround is to disable DNS Protection. and quit completely.

However, this is not the case on my Android. I disabled Adguard and closed it entirely, but I was still unable to access my account. or even register.

Even if you sign up in both cases, you'll get the same issue.

also some people were discussing about this on Reddit and i found the solution there.
please search "Adguard" there
https://www.reddit.com/r/Tiktokhelp/comments/n22etx/i_keep_getting_too_many_attempts_try_again_later/

date and time is clear on the menue bar.
so you can investigate easily
15:08 - 15:10

https://user-images.githubusercontent.com/40741745/158360052-f94157d0-8d3e-45d6-ad8d-a80399df3763.mp4

[Uploading adguard_logs_20220313114111.zip…]()

**Comment by Chinaski1** [comment]
We found out that Ratelimit is triggered on the site side and, unfortunately, at this stage there is nothing we can do about it.
