### ISSUE TITLE
twitch.tv filtering issue

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#105]
please check 1067789 for logs and more details

"настройки=>сеть=>автоматически фильтровать трафик приложений - если галочка активирована то стримы на twitch.tv и сам safari начинают жутко тормозить, а если убрать галочку все работает, но с рекламой и т.п. Пробовал убрать галочку конкретно с приложения safari но результат тот же что и с ней, т.е жуткие лаги.
Еще необходимо отключить «блокировщик всплывающих окон», а то с ним видео начинает периодически виснуть на twitch.tv"

**Comment by Stillness-2** [comment]
commit 26140
