### ISSUE TITLE
AdGuard services were not started correctly

### ISSUE THREAD

**Issue by avatar-lavventura** [AdguardTeam/AdguardForMac#1053]
I am using macOS Monterey version 12.3. Safari Version 15.4. In this answer (https://apple.stackexchange.com/a/398362/209103) I am adviced to use [Adguard][1] to block ads in Safari. When I try to enable Adguard I am get getting the following error message:

`Some AdGuard services were not started correctly. Please contact the support team.`

How can I prevent this error from happening and how can I fit it?

  [1]: https://adguard.com/en/article/how-to-block-ads-on-youtube.html

Hope you all well in Ukraine.

Related: https://github.com/AdguardTeam/AdguardForMac/issues/718

**Comment by Chinaski1** [comment]
Hello there!

Try to use this instruction to reset the system extension.

1. Reboot Mac and enter [recovery mode](https://support.apple.com/en-us/HT201255).
2. `Disable SIP` (Launch Terminal from the Utilities menu and type csrutil disable)
3. Reboot Mac
4. Close the AdGuard app and open Terminal and type `systemextensionsctl reset`
5. Reboot Mac and enter recovery mode.
6. `Enable SIP` (Launch Terminal from the Utilities menu and type csrutil enable)
6. Launch the AdGuard app and enable protection.​

If it doesn't give a result, to troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by avatar-lavventura** [comment]
I have done steps from 1-5 but I still get the same error message
