### ISSUE TITLE
feature request: firewall for AdGuardForMac

### ISSUE THREAD

**Issue by mgntcm** [AdguardTeam/AdguardForMac#1062]
Hello,
can you pls. implement firewall with whitelist option to AdGuardForMac, so that I could only allow certain applications to use Internet/Network and block others?

Thanks

**Comment by Chinaski1** [comment]
Hello!

We do not plan to introduce this feature because it is available in the basic macOS tools.
Open `System preferences` -> `Security & Privacy` -> `Firewall`
