### ISSUE TITLE
Install Update Button

### ISSUE THREAD

**Issue by Mizzick** [AdguardTeam/AdguardForMac#1066]
I've been a little surprised when I saw a downloading window after I clicked `Install Update` button. 
So as `Install Update` button actually downloads and installs update, I suggest change it to `Download & Install`.

<details><summary>Screenshot:</summary>

<img width="644" alt="Screenshot 2022-05-06 at 12 57 39" src="https://user-images.githubusercontent.com/13855288/167120536-97f91f79-2d65-404c-ab2f-92fc984eb2bf.png">

</details>

**Comment by Stillness-2** [comment]
@Mizzick `npm install PACKAGE` and then why install, and not `download-and-install` :) Well, that is a matter of habit...
