### ISSUE TITLE
Adguard on Mac disable http2

### ISSUE THREAD

**Issue by voanhduy1512** [AdguardTeam/AdguardForMac#107]
Hi,

When i enable adguard on mac, Chrome stops using http2 and fallback to http1 (on Gmail or Facebook). I check with uBlock and don't see this problem.

Can you guys take a look on it?

**Comment by ameshkov** [comment]
We should add H2 support to AG first, currently it does not yet supports it.

**Comment by ameshkov** [comment]
Duplicate of #232
