### ISSUE TITLE
[DNS] Buffering on YouTube 4K videos

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#1072]
I can't watch YouTube videos in 4K anymore, the video buffers every few seconds since I connected to AdGuard DNS (DoH). 
My internet connection is fast enough (500mbps) and everything works fine with DNS disabled. 
Any idea?

MacBook Pro 14" macOS 12.4 Safari 15.5

Edit: It works fine on my iPhone with AdGuard DNS enabled.
Edit2: YouTube works fine again after restarting DNS on my Mac.

I'll keep an eye on the issue.

**Comment by maxikuzmin** [comment]
@iDjay which product are you talking about? AdGuard DNS or AdGuard?

**Comment by iDjay** [comment]
DNS. It's working fine now, but not as good as with my standard DNS settings.

**Comment by iDjay** [comment]
still randomly occurring... Speediest shows more than 500mbps
