### ISSUE TITLE
[BUG] DNS filtering does not work on iPhone hotspot via Wi-Fi

### ISSUE THREAD

**Issue by grovolis** [AdguardTeam/AdguardForMac#1073]
### Steps to reproduce

1. Enable DNS filtering in the app and select a DNS server (in my case AdGuard private DNS address)
2. Connect to iPhone wifi network (I just used my iPhone hotspot) 
3. Go on [ipleak.net](https://ipleak.net) and check DNS server IP
4. In my case I just see my mobile data ISP DNS

### Expected behavior

I should be able to use the selected DNS server even when connected via hotspot

### Actual behavior

In my case I just see my mobile data ISP DNS

PS. If I download the AdGuard profile for macOS, it works just fine even when connected to a hotspot.

**Comment by Chinaski1** [comment]
Hello there!

Please clarify, are you using your iPhone as a hotspot and connecting to it from your macOS? 
Did I understand you correctly?

**Comment by grovolis** [comment]
> Hello there!
> 
> 
> 
> Please clarify, are you using your iPhone as a hotspot and connecting to it from your macOS? 
> 
> Did I understand you correctly?

Hello, yes that is correct! Enable hotspot in iPhone settings, then connect my Mac to the iPhone hotspot via WiFi!

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardForiOS #1999](https://github.com/AdguardTeam/AdguardForiOS/issues/1999) via [**ZenHub**](https://www.zenhub.com/)
