### ISSUE TITLE
Ad blocking stops working when waking up

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#1083]
@adguard-bot commented on [Sun Jun 19 2022](https://github.com/AdguardTeam/AdguardFilters/issues/122245)

### Issue URL (Ads)
 [https://coins.lave.ru/forum/viewforum.php?f=44](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fcoins.lave.ru%2Fforum%2Fviewforum.php%3Ff%3D44)
### Comment
> На компьютере Mac при выходе из режима сна прекращается фильтрация рекламы

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/hOFZ18R.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.8.1.1140 release
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Language-specific:</b><br/>AdGuard Russian
Userscripts: | Adguard extra

**Comment by Aydinv13** [comment]
Can't be reproduced on our side. Needs more details about the OS and steps to reproduce.
