### ISSUE TITLE
Can't open google search results with AdGuard active.

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForMac#1087]
Discussion at: https://github.com/AdguardTeam/AdguardFilters/issues/122177#issuecomment-1166172857

### Environment
* Environment name and version: MacOS 12.4, Safari, AdGuard 2.8.1.1141 nightly

**Comment by Stillness-2** [comment]
@HaikuOezu now here.

Let's do an experiment.
Before you start, export your AdGuard settings for backup ( `AdGuard menu -> Advanced -> Export Settings...` )

1. Upgrade AdGuard for lastest nightly, or download it from http://agrd.io/mac_nightly
2. In Safari Settings disable all extensions if they exists
3. Import this settings in AdGuard: 
[AdGuard_20220712093951.adguardsettings.zip](https://github.com/AdguardTeam/AdguardForMac/files/9091676/AdGuard_20220712093951.adguardsettings.zip)
   (Unzip it, and then `AdGuard menu -> Advanced -> Import Settings...` )
4. Ensure that AdGuard turned on
5. In Safari open private window ( `Shift+Cmd+N` ), and go to `google.com`
6. Try search

If you still can't open search result:

**Comment by HaikuOezu** [comment]
@Stillness-2 
Success! I can click search results just fine after following your instructions

Should I send you the logs anyway or is that enough?

**Comment by Stillness-2** [comment]
@HaikuOezu good news :)
Now you can add your settings one by one and see when search results to break. So you can determine which your settings cause to problem :)

**Comment by Stillness-2** [comment]
@HaikuOezu If everything is fine, then you do not need to send logs :)

**Comment by HaikuOezu** [comment]
@Stillness-2 I feel like a total jackass... this whole time it wasn't AdGuard's fault at all 🤦‍♂️
Turns out the real culprit was Tampermonkey... or rather - the two of them working together as disabling one or the other will not cause the bug to show up

**Comment by sfionov** [comment]
Btw you may try Extensions in AdGuard settings instead of Tampermonkey
