### ISSUE TITLE
Explanation for the confirmation dialog box after update

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1093]
Why after each update of macOS you ask for a password to install it is not clear what? Why don't you describe in this window what it is and why you need it? And can't you do without installing this every time you update macOS?

![image](https://user-images.githubusercontent.com/19418601/180829689-30c56864-fb07-409d-a21b-0fe1bc544d69.png)

**Comment by Aydinv13** [comment]
First of all, this is the macOS system window, and it requires a password because it installs auxiliary utilities that require sudo rights. These utilities change from version to version, so they need to be reinstalled.

**Comment by rakleed** [comment]
@Aydinv13 so you can't add information to this window?

**Comment by Aydinv13** [comment]
As I wrote above, it's a system dialog window.
