### ISSUE TITLE
Remove Discord and Steam from default app list

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#1095]
I have noticed that the Discord app experiences issues with activity status and rich presence features when routed through AdGuard. Steam also experiences an odd visual bug in its embedded browser when routed through AdGuard as well.

As they are two apps that seem 'out of place' in the default app list, and they are beginning to cause some issues to occur, could Discord and Steam be removed from the default app list?

**Comment by Aydinv13** [comment]
Could you be more specific about the issues you faced using these apps along with AdGuard? Especially, how to reproduce them. As for removing Discord and Steam, it's not planned in near future.

**Comment by planet0** [comment]
Sure.

> I have noticed that the Discord app experiences issues with activity status and rich presence features when routed through AdGuard.

Ensure you have enabled all related Activity Privacy settings, and add Spotify in your Connections. Enable the ability to show what you are listening to. With AdGuard filtering Discord.app, your activity status will not work. Once AdGuard is removed from Discord.app and you relaunch it, your activity status is functional as intended.

> Steam also experiences an odd visual bug in its embedded browser when routed through AdGuard as well.

Have Steam set to open the Library tab on launch, then visit the Store tab. You will get a small scrollable and viewable section of the page instead of the full page, which is black.

<img width="1183" alt="Screen Shot 2022-08-12 at 1 21 34 pm" src="https://user-images.githubusercontent.com/65204836/184279263-6a03cd75-991c-49fc-9f0f-d4a22d241f37.png">

**Comment by Aydinv13** [comment]
@planet0  I'm sorry for a big delay, I wasn't able to reproduce your issue. 
Could you please provide the debug logs:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by planet0** [comment]
@Aydinv13 I've just sent that to you now.

**Comment by Aydinv13** [comment]
Could you check it with the latest [nightly](https://agrd.io/mac_nightly) build. If the problem appears again please tell me if there are any blocked requests in Filtering log (AdGuard icon-->Gear menu-->Advanced-->Filtering log) when you open Steam/Discord.

**Comment by Aydinv13** [comment]
@planet0 
Any news?

**Comment by Aydinv13** [comment]
Using `Block third-party Authorization header` feature can be risky because it itself can disrupt some websites, so in this case it doesn't have to do with incompatibility and it's not a reason to remove these programs from the list of filtered apps.
