### ISSUE TITLE
Remove the word `release` from the number of the stable (release) version of AdGuard

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1099]
No other app for its stable (release) version of the app adds the word `release` to the version number, as this information is meaningless. I understand when you add `beta` or `nightly`, but `release` is definitely not needed.

![image](https://user-images.githubusercontent.com/19418601/181388055-ccc1f0cc-f9eb-4983-948c-ce3d792240cc.png)

**Comment by Aydinv13** [comment]
This word will be removed, thank you.

**Comment by rakleed** [comment]
@Aydinv13 why did you leave `release` on the About screen?

<details><summary>Screenshot</summary>

![Screenshot 2022-10-29 at 04 10 11](https://user-images.githubusercontent.com/19418601/198755087-09594288-4324-4f90-88e2-f6ebb974390e.png)

</details>
