### ISSUE TITLE
Add Extensions (userscripts) support

### ISSUE THREAD

**Issue by BooBerry** [AdguardTeam/AdguardForMac#11]
Self-explanatory.

The Mac needs some love here.

**Comment by tomiams** [comment]
Perhaps it is about time this feature got into production. Maybe for 2.0?

**Comment by BooBerry** [comment]
They're already working on it in CoreLibs.. it's just not ready yet. :)

**Comment by ameshkov** [comment]
Under-the-hood extensions are already supported in v2.0 nightly.

However, adding nice UI and all this stuff is time-consuming and that's why we don't plan it on v2.0 release (but it will be assigned to the first update of it)

**Comment by ameshkov** [comment]
Assigning to v2.1.

We'll need @AlikhanAliev's help with the UI here.

**Comment by Jason4V** [comment]
Hi, May I ask why [v2.1 beta](https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.1.0-beta) still do not have this wonderful feature ?

**Comment by ameshkov** [comment]
@Jason4V not yet, we had to delay it. But worry not, it will definitely come in the v2.2 update.
