### ISSUE TITLE
Shortcuts for enabling and disabling DNS protection

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1108]
If you enable third-party DNS-over-HTTPS/TLS in AdGuard when you watch some streaming services (HBO Max, Disney+), they simply don't work when using a VPN. Streaming works correctly only with DNS, which sets the VPN service upon connection. Therefore, I would like to have shortcuts to enable and disable DNS protection and get the status of DNS protection so that I can disable/enable DNS protection when connecting to/disconnecting from a VPN service.

**Comment by planet0** [comment]
Perhaps a similar method to how it's being done on AdGuard for iOS, for uniformity and similarity with Apple users.


![IMG_C6EBCD821220-1](https://user-images.githubusercontent.com/65204836/183078935-0fbfceca-3722-4979-bb74-f31fe4727717.jpeg)

**Comment by Aydinv13** [comment]
This is already in progress and supposed to be done in one of the next major updates.

**Comment by rakleed** [comment]
@Aydinv13 I checked in the latest version 2.9.0.1167 nightly, and this feature is not implemented yet. Can you open this issue and add a "Status: In Progress" label? And when the feature is already available in the nightly version, then change the label to "Status: Resolved". And when this functionality appears in the release version, then close this issue.

**Comment by rakleed** [comment]
@Aydinv13 please take a look

**Comment by Aydinv13** [comment]
@rakleed 
>I checked in the latest version 2.9.0.1167 nightly, and this feature is not implemented yet.

because it's in progress as was said before.

**Comment by rakleed** [comment]
@Aydinv13 it's been 4 months already, any news? In what version do you at least plan to implement this feature?

**Comment by rakleed** [comment]
@Aydinv13 @ameshkov please take a look

**Comment by ameshkov** [comment]
We'll do that in the large v3.0 redesign, the UI tasks are mostly freezed in the v2.X branch.
