### ISSUE TITLE
Memory Leak 11.42 GB!!

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1109]
please have a look at this issue

https://github.com/AdguardTeam/AdguardForMac/issues/1092#issuecomment-1202275013

I am ready to send you any required logs.

**Comment by aliafshany** [comment]
update:
this is after leaving it for a night.
it was around 90 MB when I left it and now it is 400MB for no reason.
it's really consuming gmy memory which results in mac's low functionality due to lack of memory.

<img width="985" alt="image" src="https://user-images.githubusercontent.com/40741745/182526338-db5029ae-d438-40bc-9fa4-49245fd09fd0.png">

**Comment by Aydinv13** [comment]
It's better to write [here](https://github.com/AdguardTeam/AdguardForMac/issues/1092) all the information related to memory leak. Thank you!
