### ISSUE TITLE
Safari file download doesn't work with Network Extension mode

### ISSUE THREAD

**Issue by gtom84** [AdguardTeam/AdguardForMac#1110]
### Steps to reproduce

1. Install AdGuard for Mac on Mac OS 12.4
2. Set Automatically filter applications mode to Network Extension
3. Open Safari and download any file. 
4. If you switch to Proxy or disable Automatically filter application, the same download will work fine.

### Expected behavior
File download should work in Network Extension mode, I guess.

### Actual behavior
Download will not start and error message reads "Operation couldn't be completed. Operation not permitted."

<details><summary>Screenshot:</summary>

<img width="577" alt="image" src="https://user-images.githubusercontent.com/53334241/182455309-0ec5a475-02ee-46c2-984e-01236d62323f.png">

</details>

### Customer ID 
AdGuard Support Request #625473

### Your environment
MacOS 12.4
Safari Version 15.5 (17613.2.7.1.8)
No VPN or AV software was running.

**Comment by Aydinv13** [comment]
@gtom84 
- Is it reproducible with other Browsers/files?
- In which version of AdGuard did you encounter this problem first?
- Did you try the latest version of AdGuard
- Could you share you settings? Popup menu - Gear - Advanced - Export settings

**Comment by gtom84** [comment]
Other files - yes any file.
Version 2.8.1.1147.
Yes, I'm using the latest one.

**Comment by gtom84** [comment]
[AdGuard_20220811071643.adguardsettings.zip](https://github.com/AdguardTeam/AdguardForMac/files/9311466/AdGuard_20220811071643.adguardsettings.zip)


I had to compress it into ZIP file, Github didn't allow me to upload *.adguardsettings file directly.

**Comment by Aydinv13** [comment]
Thanks for all detailed information. Unfortunately, it cannot be reproduced on my side. Could you also check if [this article](https://www.makeuseof.com/tag/safari-downloads-not-working/) is helpful? If not, collect debug logs and send them to devteam@adguard.com, please. (AdGuard popup menu - Gear - Advanced - Logging level - debug)

**Comment by Aydinv13** [comment]
@gtom84  By the way, do you have Private Relay enabled?

**Comment by Aydinv13** [comment]
@gtom84  Any news?

**Comment by gtom84** [comment]
I’m not using private relay.

**Comment by Aydinv13** [comment]
@gtom84 any updates about [this](https://github.com/AdguardTeam/AdguardForMac/issues/1110#issuecomment-1212908248)?

**Comment by gtom84** [comment]
No. Please close it. It’s been working fine after several AdGuard settings
changes. Some settings were blocking it.

**Comment by Aydinv13** [comment]
If you don't mind telling me exactly what settings have been changed? 

Thank you!
