### ISSUE TITLE
AG doesn't block identical ads on this site

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1111]
### Steps to reproduce

1. do like the video at this site: https://wcity4.site/

https://user-images.githubusercontent.com/40741745/182652154-58b3ec98-d98c-41fb-9c81-531ff0bb8a29.mp4

- and if I try to choose "Block similar" on advanced, I would get this:

https://user-images.githubusercontent.com/40741745/182655246-c4ac1798-d92b-4401-bf57-ab1a9dc2f651.mp4

### Expected behavior
- not blocking similar ads on other pages.

</details>

### Your environment

* Environment name and version: chrome 103.0.5060.134

**Comment by Alex-302** [comment]
@aliafshany Please report us using reporting tool as described here: https://kb.adguard.com/en/technical-support/reporting-tool

**Comment by aliafshany** [comment]
i did exactly like it

<img width="996" alt="image" src="https://user-images.githubusercontent.com/40741745/184412225-a375ef06-8c3b-4af2-8f03-9587c294bd3b.png">
