### ISSUE TITLE
Fully disable statistics function

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#1112]
Hello,

please add a function to completely disable statistics🙏🏼

Thank you.
Best regards😙

**Comment by Aydinv13** [comment]
@ammnt I'm sorry, but what's the point of doing that? Could you explain in which case this is necessary?

**Comment by ammnt** [comment]
@Aydinv13, okay. This is not critical request actually, but sometimes I not sure that I really want to see some statistic or logs in app. Will be great if we can turn off this functions in future.

**Comment by Aydinv13** [comment]
@ammnt I'm afraid at this moment we can't say it's necessary, although the idea is quite interesting. Thank you for your request.
