### ISSUE TITLE
`browser` value is incorrectly passed to ReportsWebApp

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1114]
### Steps to reproduce

1. Click "Report an issue" In AdGuard Browser Assistant
2. Go to step 3/8

### Expected behavior

Browser information is filled in correctly.

### Actual behavior

The browser information is filled in as `undefined undefined`. The problem appeared in version 2.8.1, in the latest available 2.9.0.1167 nightly is also reproduced.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/19418601/183226512-3f791c38-5d1c-4729-913f-42f1c551c10b.png)

</details>

### Customer ID 

626476

### Your environment

* Environment name and version: Chrome 104/Safari 15.6
* Any specific potentially conflicting software installed:

**Comment by planet0** [comment]
Can confirm this is happening for me with Version 2.9.0.1167 nightly.

**Comment by cryptopatik22** [comment]
https://adguard.zendesk.com/agent/tickets/626476

customer sent us a [cloud link](https://www.icloud.com/iclouddrive/0bbRS97oIxaCNtXnvGfS8FFeQ#adguard_logs_20220806123927) with the logs

**Comment by Aydinv13** [comment]
We will investigate the problem, thank you.

**Comment by rakleed** [comment]
@Aydinv13 this problem appeared after updating to 2.8.1. In 2.8.0 and earlier, the value was passed correctly.
