### ISSUE TITLE
Add support for linux.

### ISSUE THREAD

**Issue by Abhirup-99** [AdguardTeam/AdguardForMac#1119]
### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by michael1900** [comment]
This will be STUNNING!

**Comment by Aydinv13** [comment]
We work on the concept of AdGuard on Linux so it's too early to tell when it will be released.
