### ISSUE TITLE
Browser Assistant doesn't sync if "Do not filter for 30 second" has been completed via Legacy Assistant

### ISSUE THREAD

**Issue by Oleg-Chashko** [AdguardTeam/AdguardForMac#1123]
It doesn't work as well as I'd like it to. 
I increased the video speed for convenience.

https://user-images.githubusercontent.com/62497891/186650871-ee036a26-864e-46ff-93c1-26732efeb835.mp4

**Comment by Aydinv13** [comment]
This happens when you disable filtering via Legacy Assistant (which is not supported anymore), but everything works well if you use Browser Assistant. By "works well" I mean appearing `Refresh page` button in Browser Assistant's popup. So you have to refresh the webpage anyway.

**Comment by Oleg-Chashko** [comment]
@Aydinv13 

- Is this also considered the norm of behavior?

<img width="466" alt="Bildschirmfoto 2022-08-29 um 14 14 04" src="https://user-images.githubusercontent.com/62497891/187199620-6fad3120-0437-47d4-a8f9-2c7bd10a00f7.png">

- It seems to me it should be like this, or not?

<img width="466" alt="Bildschirmfoto 2022-08-29 um 14 14 35" src="https://user-images.githubusercontent.com/62497891/187199904-1fc18f10-eebe-42da-8998-a23375970c1f.png">

**Comment by Aydinv13** [comment]
This also occurs when you turn off filtering via Legacy Assistant
