### ISSUE TITLE
Error with filtering initialization through Network Extension when network is off

### ISSUE THREAD

**Issue by cryptopatik22** [AdguardTeam/AdguardForMac#1124]
### Steps to reproduce

1. Launch AdGuard

### Expected behavior
All is well

### Actual behavior
AdGuard fails to get started. "Some AdGuard services were not started correctly. AdGuard won't work correctly." message appears.

### Tickets where the issue was reported
627834
620652
628388
628953
629526
629279
630402
630853
631019
631127
632063

**Comment by cryptopatik22** [comment]
[adguard_logs_20220822032536.zip](https://github.com/AdguardTeam/AdguardForMac/files/9439288/adguard_logs_20220822032536.zip)
[adguard_logs_20220825103654.zip](https://github.com/AdguardTeam/AdguardForMac/files/9439289/adguard_logs_20220825103654.zip)
[adguard_logs_20220821055524.zip](https://github.com/AdguardTeam/AdguardForMac/files/9439290/adguard_logs_20220821055524.zip)

**Comment by cryptopatik22** [comment]
https://jira.adguard.com/browse/AG-16171

**Comment by sfionov** [comment]
Reopened since not fully resolved.
