### ISSUE TITLE
Allow viewing original SSL certificate

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForMac#113]
SSL certificate pass-through When activating "Filter https protocol" in Adguard Preferences, a website's SSL certificate is replaced with an intermediate SSL certificate by the Adguard local
proxy/interceptor. It would be nice to be able to access the original SSL certificate as well, e.g. as an additional button in the Adguard Assistant browser module.

The intermediate Adguard cert should remain the only relevant one for the client application 
connection to the Adguard proxy. However, what I would like to do (sometimes) is take a look at the original SSL certificate, i.e. take a look at its contents, who the issuer (CA) is etc.

Original request - **1231958**

**Comment by ameshkov** [comment]
Huh, this in an interesting feature request. We'll think about it.

**Comment by ameshkov** [comment]
Moved to CoreLibs:
https://github.com/AdguardTeam/CoreLibs/issues/143
