### ISSUE TITLE
AdGuard can't be opened after clicking on Hide from menu bar icon

### ISSUE THREAD

**Issue by rpc31** [AdguardTeam/AdguardForMac#1140]
Devide MacOs Monterey

As per https://www.reddit.com/r/Adguard/comments/vdfal6/menu_bar_icon_macos_monterey/

When hiding AdGuard from the menu-bar, it becomes impossible later to access the preferences. Any clue of what’s wrong?

### Steps to reproduce

1. tick the option "hide from menubar"
2. try to access adguard again
3.
4.

**Comment by trenbe-gaemi** [comment]
me too.

**Comment by Aydinv13** [comment]
@rpc31 @trenbe-gaemi 
Could you record a short video with opening AdGuard via Applications folder or Launchpad?

**Comment by Aydinv13** [comment]
This issue has been closed due to no response. You can open it again anytime if needed.

**Comment by rpc31** [comment]
Here a video that shows it. As soon as I untick the preferences, the Adguard app disappears from the menubar and becomes unaccessible then. The only way for me to get it back is to uninstall and then re-install it.
I tried to reproduce the bug with Adguard being the only app launched on the computer too and the result is there same, so it doesn't seem to be a conflict with another app.

https://share.cleanshot.com/kKmNTz

**Comment by rpc31** [comment]
@Aydinv13 I do (for the video), but results are the same when I uninstall them all.

**Comment by Aydinv13** [comment]
I mean, it can be the same issue https://github.com/AdguardTeam/AdguardForMac/issues/1101

**Comment by Lilac-Orange** [comment]
I have the same issue
