### ISSUE TITLE
System Freezes in Mac Ventura 13.0

### ISSUE THREAD

**Issue by yakirbu** [AdguardTeam/AdguardForMac#1159]
Few people including myself experience system freeze with AdGuard in the latest Mac Ventura update:

https://www.reddit.com/r/MacOSBeta/comments/yk47z1/system_freezes_in_mac_ventura_130_public_version/

**Comment by Aydinv13** [comment]
@yakirbu 
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.
