### ISSUE TITLE
Move "check filter updates" to settings menu

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForMac#116]
In Windows we can right click the adguard icon and click on Update. We see a message for example: 3 filters updated / No updates found.

Can this be added to Adguard for Mac as well? Ofcourse there is no right click in menu bar. It would be when we just left click on adguard icon in menu bar and maybe there a refresh icon or update now? 

Now I am stuck, alex made a change and I want to see if it worked. How do I update the filterlist?

Thanks

**Comment by ameshkov** [comment]
It is there already: settings icon -> advanced -> check filter updates.

I guess we could move it to the settings menu instead.

**Comment by worldsdream** [comment]
Thanks for pointing it out. Really didn't see it.

That would be better for the eye and faster indeed.

**Comment by ameshkov** [comment]
Could you edit the issue then? I'll assign it to the closest milestone.

**Comment by worldsdream** [comment]
Done
