### ISSUE TITLE
adguard assistant malfunction 

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1163]
### Steps to reproduce

1. just try to open any site

### Actual behavior

on sime sites, the assistant won't pop-up and on some sites although it is on, but it shows off sign.

https://user-images.githubusercontent.com/40741745/203925077-ca0d682a-e31e-4d70-ae8c-23c081f1dd9f.mp4

</details>

### Customer ID 

685529

### Your environment

* Environment name and version: (e.g. Chrome 59): Adguard Version 2.9.1.1217 release & chrome 107.0.5304.110 - MacOS 13.0.1
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): shadowrocket

**Comment by aliafshany** [comment]
update:
I followed this instruction and it DIDN'T solve my issue.

https://kb.adguard.com/en/macos/solving-problems/launch-issues#launch-issues-on-macos-11-and-higher

**Comment by Aydinv13** [comment]
Unfortunately, Legacy assistant isn't supported anymore and will be removed in the near future. Please, use Browser assistant instead. Here is the link: https://adguard.com/en/adguard-assistant/overview.html
