### ISSUE TITLE
mbank.pl

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#1165]
@adguard-bot commented on [Thu Dec 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314)

### Issue URL (Incorrect Blocking)
 [https://mbank.pl](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fmbank.pl)
### Comment
Username: `@nikbyte`
> Случилось недавно, после обновления фильтров.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/ulATQFi.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/FmALmKl.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.9.1.1217
Browser: | Safari
Stealth mode options: | Hide your search queries, <br>Remove X-Client-Data header from HTTP requests, <br>Self-destructing third-party cookies (), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>AdGuard Mobile Ads<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><b>Other:</b><br/>Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/>AdGuard Russian, <br/>AdGuard German, <br/>AdBlockID, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard
Userscripts: | disabled

---

@Alex-302 commented on [Thu Dec 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1333806021)

@nikbyte Это сетевая ошибка, очень маловероятно, что связана с фильтрами.
Попробуйте экспортировать настройки и переустановить Адгард.
Если не поможет - напишите на support@adguard.com

---

@nikbyte commented on [Thu Dec 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1333811064)

@Alex-302 я не согласен. Проблема проявляется на двух разных устройствах сразу. При отключении adguard всё становится нормально. При этом ещё неделю назад всё работало как положено.

---

@Alex-302 commented on [Thu Dec 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1333919495)

@nikbyte От включенных фильтров зависит?

---

@nikbyte commented on [Thu Dec 01 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1334068152)

Отключение всех фильтров не помогает.

---

@Alex-302 commented on [Fri Dec 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1335152968)

@nikbyte А расширений Адгарда(в настройках программы) и Антитрекинга?

---

@nikbyte commented on [Fri Dec 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1335228796)

Я так и не понял зависимость, отключал расширения – не помогало. Отключал фильтрацию https, добавлял в список исключений – никакой реакции. Когда отключал антитрекинг – помогало, но найти конкретно настройку, с которой возникала проблема я не смог. Это произошло после недавнего обновления adguard на двух устройствах. В итоге, я экспортировал настройки, переустановил, импортировал настройки, и всё заработало.

---

@Alex-302 commented on [Fri Dec 02 2022](https://github.com/AdguardTeam/AdguardFilters/issues/136314#issuecomment-1335389502)

> Отключал фильтрацию https – никакой реакции.

это очень странно. Точно не фильтрами вызвано. Перенесу в репозиторий программы, там расскажут как логи получить и куда отправить.

**Comment by nikbyte** [comment]
К сожалению, я уже обновил приложение, и проблема не воспроизводится. Если повторится, я соберу логи и предоставлю в отдельном тикете. Спасибо.

**Comment by Aydinv13** [comment]
Если проблема повторится, вы можете открыть заново эту задачу и отправить логи по инструкции выше. На данный момент я ее закрываю.
Спасибо за обратную связь.
