### ISSUE TITLE
Shadowrocket on M2 MBP will make Adguard lose its functionality 

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1166]
### Steps to reproduce

1. turn on Adguard
2. turn on shadowrocket and connect to any server you want

<details><summary>Screenshot:</summary>

</details>
I'm using Shadowrocket ( an iOS app ) on my MBP M2 on Ventura 13.0.1. it seems that every time i use Adguard with Shadowrocket, AG would lose its functionality.
for example, if i connect to my servers via **Qv2ray** app I see these results on the page:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/40741745/206644834-fb034e46-5572-43ef-96b9-cec3363ee82c.png">

but if I use shadowrocket the results would be this: ( it literally means that AG is not running and you can see ads everywhere, especially in Youtube)

<img width="614" alt="image" src="https://user-images.githubusercontent.com/40741745/206645158-06d05fa7-f091-4c30-abbe-c7043bd0c7c2.png">

i tried a clean Uninstall on AG and reinstalled it with a new setting. i tried 3 versions ( stable, beta, and nightly ) all with the same results.

### Your environment

* Environment name and version: (e.g. Chrome 59): chrome 108.0.5359.98 
* Any specific potentially conflicting software installed: Adguard (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by aliafshany** [comment]
this issue is also related to Shadowrocket's behavior.

https://github.com/AdguardTeam/AdguardForMac/issues/1160

i have no problem using Qv2ray, but shadowrocket.

**Comment by Aydinv13** [comment]
@aliafshany 
To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by aliafshany** [comment]
@Aydinv13 
testing the latest shadowrocket shows that the issue has been solved.
but in case if it happens again, i will reopen this issue.

**Comment by Aydinv13** [comment]
Ok, please if it occurs again specify you steps and preconditions (e.g. the way you connect to server, version of AdGuard). I'm closing this issue.
