### ISSUE TITLE
Extension for Adguard Mac

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForMac#117]
I would love to know if you can add extensions to the Mac version? This is what I am missing right now.

**Comment by ameshkov** [comment]
It is possible, should be done in the next major release.

**Comment by worldsdream** [comment]
Can you make a 2.0 milestone and add this one into it?

**Comment by ameshkov** [comment]
It is a bit too early for this.

Let's just leave this issue open for now

**Comment by vozersky** [comment]
duplicates #11
