### ISSUE TITLE
AdGuard local ROOT certificate causes no HTTP/3 support

### ISSUE THREAD

**Issue by dalisoft** [AdguardTeam/AdguardForMac#1173]
### Steps to reproduce

1. Download, open, register and configure as you wish
2. Open browser and open url with any HTTP/3 support website (e.g. flightradar24.com)
3. Open **DevTools**, open **Network**
4. Check if it requests HTTP/3

### Expected behavior

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/3511344/209870155-b49de4a1-1f38-418f-84e8-beae1bc8d5da.png">

### Actual behavior

<img width="1261" alt="image" src="https://user-images.githubusercontent.com/3511344/209870001-591c3da8-c4ff-48eb-83cb-6e73cef47bfd.png">

<details><summary>Screenshot:</summary>

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/3511344/209870155-b49de4a1-1f38-418f-84e8-beae1bc8d5da.png">
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/3511344/209870001-591c3da8-c4ff-48eb-83cb-6e73cef47bfd.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): macOS Ventura; Any browser with HTTP/3 support
* Any specific potentially conflicting software installed: Adguard for macOS + Adguard DNS (**quic** used)

**Comment by Aydinv13** [comment]
Hi there!
This happens because AdGuard now doesn't support HTTP/3. Implementation of filtering HTTP/3 connections is planned in one of the next CoreLibs update.
