### ISSUE TITLE
Missing translations in Polish in Safari Browser Assistant

### ISSUE THREAD

**Issue by emikaadeo-git** [AdguardTeam/AdguardForMac#1174]
### Steps to reproduce

1. On macOS Ventura 13.1 go to System Settings -> General -> Language & Region -> Applications -> change AdGuard to English

### Expected behavior

Safari browser assistant should be fully displayed in selected language
### Actual behavior

Part of the Safari browser assistant is displayed in English and another part is displayed in Polish (my general macOS language)

<details><summary>Screenshot:</summary>

<
<img width="166" alt="ad" src="https://user-images.githubusercontent.com/56483380/209875715-3bf92ad8-9a40-458f-bc3f-817c6ce04488.png">
!--- drag and drop, upload or paste your screenshot to this area-->

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Aydinv13** [comment]
Missing translations will be added, thank you!
