### ISSUE TITLE
AdGuard causes network error for HTTP/3 connection in Safari

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#1176]
### Steps to reproduce

1. Create your AdGuard Home DNS server and use reverse-proxy from Cloudflare with HTTP/3 support;
2. Enable HTTP/3 experimental support in Safari:
![image](https://user-images.githubusercontent.com/45385632/210229182-a39c95b4-0e0d-4f0e-84cb-08d959cba6e5.png)
3. Add the domain of your server in filtering exclusions in AdGuard for Mac (as rule in "Filter" section and HTTPS-exclusion too);
4. Disable AdGuard VPN and clear all possible caches in Safari😀
5. Open AdGuard Home UI and go to rules section, then try to edit rules - you will get a network error:
![2023-01-02_14-47-09](https://user-images.githubusercontent.com/45385632/210229618-57124388-3109-4294-9462-e63e8b7560d6.png)
![2023-01-02_14-47-16](https://user-images.githubusercontent.com/45385632/210229628-8aa5fc99-70b0-4e3c-a884-929fb90cbf16.png)
![2023-01-02_14-47-41](https://user-images.githubusercontent.com/45385632/210229639-8d483f88-1441-48f6-9005-81a8d23288d2.png)
6. Try to disable AdGuard for Mac - everything will be work perfect😋

### Expected behavior
I expect that HTTP/3 will be work without limits when the domain in exclusion lists.

### Actual behavior
AdGuard for Mac causes network error for HTTP/3 connection in Safari. Works fine in Chromium-based browsers.

<summary>Verbose logs and additional information:</summary>

[adguard_logs_20230102115225.zip](https://github.com/AdguardTeam/AdguardForMac/files/10331477/adguard_logs_20230102115225.zip)

1. This issue is also discussed here before:
https://github.com/AdguardTeam/AdGuardHome/issues/4772
Also reproduced with NGINX HTTP/3 and Docker too - instead Cloudflare.
2. Maybe this task must be in Corelibs repo;
3. I'm ready to provide remote access for debugging.

### Your environment

* macOS Ventura 13.1 (22C65)
* AdGuard for Mac 2.9.1.1217
* AdGuard VPN 2.0.1.300 (Disabled)
* No antivirus, firewalls etc.

**Comment by sfionov** [comment]
https://github.com/AdguardTeam/AdguardForMac/issues/1173#issuecomment-1367423466

**Comment by ammnt** [comment]
@sfionov, wait a minute. Everything works fine, except this error. Another resources of GUI connected by h3. Also the domain is in exclusions lists🤷🏻‍♂️ Why the app breaks http/3 connection for the domain from exclusion lists?

**Comment by ammnt** [comment]
@sfionov, I suppose that fallback to HTTP/2 proto doesn't work properly in some cases. Can you check and confirm please? Thank you🙃

**Comment by ammnt** [comment]
@Aydinv13, please take a look this issue🙏🏼

**Comment by Aydinv13** [comment]
@ammnt 
> Why the app breaks http/3 connection for the domain from exclusion lists?

HTTP/3 will work if the entire application does not have HTTPS enabled. That's why h/3 connection is broken even for domain from the exclusions list. This is a disadvantage for now.
Let's see how the behavior with the h/3 implementation will change in the next version of CoreLibs.

**Comment by ammnt** [comment]
@Aydinv13, okay, thank you. Last question: do you have any information about when HTTP/3 filtration will be implemented and HTTP/2 fallback will be no need anymore?👀

**Comment by Aydinv13** [comment]
Supposed to be implemented in version 1.11 of CoreLibs.
