### ISSUE TITLE
Add Safari Technology Preview to the default list of filtered applications

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#118]
For the OS X app, could you add Safari Technology Preview to the default list of filtered applications? (Preferences > Network tab > Applications)
<img width="520" alt="screen shot 2016-08-16 at 01 34 38" src="https://cloud.githubusercontent.com/assets/15856304/17695587/f58674f8-63b1-11e6-91f9-6ea320600cc4.png">

https://developer.apple.com/safari/technology-preview/

This browser is akin to Chrome Canary, which was already on the list.

**Comment by ameshkov** [comment]
@Stillness-2 it would be great if we could turn filtering OFF for Safari and leave it enabled for Safari Technology Preview.

Is it possible?

**Comment by Stillness-2** [comment]
At the moment we can't separate `Safari` and `Safari Technology Preview` technically. The network connections performs the same process for both browsers. Thus it makes no sense to add Safari Technology Preview app in filtering list.
