### ISSUE TITLE
Repeating permission requests to create a proxy (again)

### ISSUE THREAD

**Issue by cryptopatik22** [AdguardTeam/AdguardForMac#1181]
### Expected behavior
It is enough to give permission to start a proxy once before the first launch of an application.

### Actual behavior
[Permission](https://uploads.adguard.com/Chinaskinnx6t.png) is requested after each reboot of the operating system.

### Ticket ID 
693550

### Your environment
AdGuard for macOS 2.9.1

**Comment by cryptopatik22** [comment]
[adguard_logs_20221214013547.1.zip](https://github.com/AdguardTeam/AdguardForMac/files/10465660/adguard_logs_20221214013547.1.zip)

**Comment by VladisLoveZh** [comment]
Same issue with ticket: **731916**  
 2.9.2.1234 release (CL-1.10.182, DNS-2.0.75)
