### ISSUE TITLE
Some of the content on facebook.com is blocked

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardForMac#1184]
@Alex-302 commented on [Wed Jan 25 2023](https://github.com/AdguardTeam/AdguardForWindows/issues/4577)

@adguard-bot commented on [Mon Jan 16 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256)

### Issue URL (Incorrect Blocking)
 [https://www.facebook.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.facebook.com%2F)
### Comment
Username: @codyghind
> Facebook posts disappear from feed right after opening a new Facebook page. Other elements on the page (e.g. stories) are unaffected. I have tried logging out/in, clearing Chrome cookies, disabling other extensions, none of which helped. The only way to load Facebook posts is to disable the AdGuard extension for facebook.com

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/iGRz5aI.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/4ggJ75M.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.9.1.1217+release
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Self-destructing third-party cookies (180), <br>Block Push API, <br>Block Location API, <br>Block Java
DNS filtering: | server: `https://dns.adguard-dns.com/dns-query`<br>filters: `https://filters.adtidy.org/mac_v2/filters/15.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances<br/><br/><details><summary><b>Language-specific:</b></summary>AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Japanese, <br/>AdGuard Dutch, <br/>AdGuard Spanish/Portuguese, <br/>AdGuard French, <br/>AdGuard Chinese, <br/>EasyList Italy, <br/>Hungarian, <br/>Official Polish filters for AdBlock, uBlock Origin & AdGuard, <br/>Dandelion Sprout's Nordic Filters</details>
Custom filters: | https://www.joinhoney.com/whitelist/honey-smart-shopping.txt
Userscripts: | Web+of+Trust+(url:+https://userscripts.adtidy.org/release/adguard-wot/1.0/wot.user.js),<br>AdGuard+Popup+Blocker+(url:+https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.user.js),<br>AdGuard+Extra+(url:+https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.user.js)
Other extensions used: | Privacy Badger, Decentraleyes, I don't care about cookies

---

---

@Alex-302 commented on [Mon Jan 23 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1400068494)

@codyghind Hi. I can't reproduce. Is the problem related to enabled filters, stealth mode or DNS filtering?

---

@codyghind commented on [Tue Jan 24 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1401832989)

> Alex-302

The issue is reproducible only when the "Automatically filter applications" option is enabled in Network tab. All applications are enabled in that list, as per default. Additionally, the Filtering mode is set as "Network extension".

I have tried adding the user rule suggested by @jellizaveta, but the issue persists. Also, disabling DNS, Stealth Mode and Security settings does not the resolve the issue either.

<img width="699" alt="Screenshot 2023-01-24 at 14 02 01" src="https://user-images.githubusercontent.com/25612801/214287763-be62b5ca-c970-4959-9f29-b6efac557ed9.png">

---

@Alex-302 commented on [Tue Jan 24 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1401922459)

@codyghind Perhaps your message was misunderstood.
Could you please check what breaks the site?
Disable one by one with check:
- all filters;
- stealth mode;
- dns filtering;
- extensions in AdGuard settings.

---

@codyghind commented on [Tue Jan 24 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1402266271)

> @codyghind Perhaps your message was misunderstood. Could you please check what breaks the site? Disable one by one with check:
> 
> * all filters;
> * stealth mode;
> * dns filtering;
> * extensions in AdGuard settings.

What I wanted to explain in my previous message is that I have done exactly that. Regardless of disabling either separately or all the above settings at once, the issue with facebook.com persists.

The only way to make posts appear on the page is to disable the "Automatically filter applications" option.

Do you need any logs?

---

@Alex-302 commented on [Tue Jan 24 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1402373016)

> What I wanted to explain in my previous message is that I have done exactly that.

Just for confirmation.

Could you please test these rules one by one in user filter?(when all filters and bodules are turned off)
* `@@||facebook.com^$urlblock`
* `@@||facebook.com^$stealth`
* `@@||facebook.com^$elemhide`
* `@@||facebook.com^$jsinject`
* `@@||facebook.com^$jsinject,extension`
* `@@||facebook.com^$extension`
* `@@||facebook.com^$content`

---

@codyghind commented on [Wed Jan 25 2023](https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1403295956)

I have tried the above rules one by one, with modules both disabled and enabled. Regardless of the other modules status, the following two rules indeed fix the issue:

- `@@||facebook.com^$jsinject`
- `@@||facebook.com^$jsinject,extension`

---

Original issue: https://github.com/AdguardTeam/AdguardFilters/issues/140256#issuecomment-1399288169

**Comment by Aydinv13** [comment]
@codyghind please grab the logs and send them to us:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Wait for ~15 seconds;
3. Reproduce the issue (without workaround rules) and remember the exact time it happened;
4. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
5. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Aydinv13** [comment]
@codyghind 

Any update?

**Comment by codyghind** [comment]
@Aydinv13 Unfortunately I cannot reproduce the issue anymore. I have removed the custom `@@||facebook.com^$jsinject` rule as requested and all other modules are enabled as per normal.

Regardless, I have exported and emailed the debug logs in case they are of any help.

**Comment by Aydinv13** [comment]
@codyghind 
could you please check the latest [nightly](https://agrd.io/mac_nightly)?
