### ISSUE TITLE
AdGuard's filtering stops working after enabling VPN

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1189]
Very rarely, but still, it happens that AdGuard stops working after enabling VPN (Proton VPN). For filtering to work, I had to restart apps (Google Chrome and Spotify). What is the reason for this and can you, for your part, make sure that this does not happen?

**Comment by rakleed** [comment]
I'll try to reproduce the problem too (and it seems to me that this applies to any VPN, actually), but it usually appeared when I turned the VPN on/off frequently.

**Comment by rakleed** [comment]
@Aydinv13 sent logs to apple@adguard.com.

Filtering did not work on the dtf.ru website in Safari when IVPN was enabled. When I turned off IVPN, filtering immediately started working.

**Comment by Aydinv13** [comment]
Got them, thank you

**Comment by Aydinv13** [comment]
@rakleed 

We seem to have been able reproduce this issue. Probably the trouble is in the dns libs. Anyway, let's wait for a fix. Thanks for the catch.

**Comment by Aydinv13** [comment]
@rakleed could you check if the problem no longer exists? He is the [link](https://agrd.io/mac_nightly).

**Comment by rakleed** [comment]
@Aydinv13 judging by the version number, the latest nightly corresponds to the release version (2.10.1.1277), and in this version the problem was reproduced.

**Comment by rakleed** [comment]
@sfionov are you even going to fix this problem?
