### ISSUE TITLE
User script doesn't work

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1196]
### AdGuard version

2.9.2

### Browser version

Safari 16.3/Chrome 110

### OS version

13.2.1 (22D68)

### Issue Details

Steps to reproduce:
1. Install user script from https://greasyfork.org/en/scripts/15222-imdb-tomatoes or https://github.com/chocolateboy/userscripts/blob/master/src/imdb-tomatoes.user.js
2. Go to https://www.imdb.com/title/tt7366338/

### Expected Behavior

The user script works correctly.

### Actual Behavior

The user script doesn't work. Log from browser console:

```
[Log] id: – "tt7366338"
[Log] cached error (expires: 17/02/2023, 15:36:42): – "error fetching API (420 Connection Error)"
```

### Additional Information

Before [updating to version 5](https://github.com/chocolateboy/userscripts/commit/1c654935833d28ba72c368cef942192c324d8add), the script worked correctly.

And in Chrome, through the Tampermonkey or Violentmonkey extension, the script works correctly.

**Comment by EldritchEevee** [comment]
**Addon requires a rewrite with MV3 compatibility. MV2 MUST be dropped.**

**Comment by Aydinv13** [comment]
Issue moved to [AdguardTeam/CoreLibs #1729](https://github.com/AdguardTeam/CoreLibs/issues/1729) via [**Zenhub**](https://www.zenhub.com/)
