### ISSUE TITLE
Add Stealth Mode functions

### ISSUE THREAD

**Issue by BooBerry** [AdguardTeam/AdguardForMac#12]
Self-explanatory.

The Mac needs the protection Stealth Mode provides from pesky spies and the dreaded WebRTC protocol leaking your IP when using a VPN (I know, there's a filter rule for this, hehe).

**Comment by Stillness-2** [comment]
It might need CR-AG-744

**Comment by ameshkov** [comment]
@Stillness-2 what do you mean?:)

**Comment by deLumren** [comment]
So is it technically impossible to implement VPN features in MAC ?
With changes to U.S. legislation, it might be a good selling point.

**Comment by ameshkov** [comment]
Technically it is possible, but we're not a VPN service, and we don't really want to become one (at least now).

**Comment by tomiams** [comment]
This is dearily needed and it's been 3 years!
It's even given low priority...
Devs.. please give this crucial feature more attention.

**Comment by ameshkov** [comment]
Yep, that's true, AG for Mac will receive stealth mode functions **after** CL is integrated to AG for Windows.

**Comment by ameshkov** [comment]
@Stillness-2 please make sure that the settings from "Misc" are passed to CoreLibs. Currently, it seems that they simply do not work:
https://uploads.adguard.com/up04_l80q2_AdGuard_Preferences_-_Privacy.png
