### ISSUE TITLE
www.icloud.com.cn cannot load

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#1200]
@adguard-bot commented on [Tue Feb 21 2023](https://github.com/AdguardTeam/AdguardFilters/issues/143546)

### Issue URL (Incorrect Blocking)
 [https://www.icloud.com.cn/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.icloud.com.cn%2F)
### Comment
> 当打开adguard总开关时，icloud.com.cn始终无法访问，即使将该域名添加到白名单也无法解决

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/3ig5TRn.png)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/k4iDN3g.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.9.2.1234+release
Browser: | Safari
Stealth mode: | disabled
DNS filtering: | server: `System`<br>filters: `https://filters.adtidy.org/mac_v2/filters/15.txt`
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection<br/><br/><b>Language-specific:</b><br/>AdGuard Japanese, <br/>AdGuard Chinese
Userscripts: | disabled

**Comment by Alex-302** [comment]
Reproduced even if all filters, extensions, stealth mode and DNS filtering are turned off.

**Comment by Aydinv13** [comment]
Issue moved to [AdguardTeam/CoreLibs #1728](https://github.com/AdguardTeam/CoreLibs/issues/1728) via [**Zenhub**](https://www.zenhub.com/)
