### ISSUE TITLE
Auto DNS protection based on network you're connected to

### ISSUE THREAD

**Issue by iUnstable0** [AdguardTeam/AdguardForMac#1202]
### Issue Details

I host adguard home on my local network and have adguard DNS.io DNS added to my DNS protection list on adguard for mac
when my mac is connected to my local network it will override and use adguard-dns.io on the adguard app for mac instead of the configured local adguard home

### Proposed solution

A feature to automatically enable/disable dns protection or set DNS provider based on the network you're connected to, so when I'm connected to my home network DNS protection on Adguard on my mac would be disabled and use the local adguard home instead

**Comment by Aydinv13** [comment]
@iUnstable0 Hello!

I guess it is related to this feature request, isn't it? https://github.com/AdguardTeam/AdguardForMac/issues/901

**Comment by iUnstable0** [comment]
yes!! sorry i didn't see that post

**Comment by Aydinv13** [comment]
@iUnstable0 it's okay, I'm gonna close the current issue as a duplicate. 

Thank you!
