### ISSUE TITLE
[Feature request] Consider adding black theme for Night Mode feature in OS X

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForMac#121]
id 621565
for example, it should look as in Punto Switcher
![screenshot_100](https://cloud.githubusercontent.com/assets/18548949/17745739/b0d2afc0-64b5-11e6-8a09-a8cd88b5e12c.jpg)
![screenshot_101](https://cloud.githubusercontent.com/assets/18548949/17745740/b0d31b36-64b5-11e6-8e0a-642059e90db1.jpg)

**Comment by Jax0rz** [comment]
That's the reason why I don't use this App until it support dark theme.

**Comment by ameshkov** [comment]
Are you talking about AG main menu?

![](https://uploads.adguard.com/up04_nkul8.png)

**Comment by Jax0rz** [comment]
In dark mode,The AG background color should like this 
<img width="609" alt="screen shot 2017-09-06 at 10 40 24" src="https://user-images.githubusercontent.com/7557357/30092172-0609da54-92f0-11e7-96a4-afeddb12d9c4.png">

**Comment by ameshkov** [comment]
@Jax0rz got it, thank you!

That's rather easy to do when one uses the default context menu as shown in a screenshot. With custom UI like ours, this is much more complicated.

Anyways, we'll find a way.

**Comment by eivindml** [comment]
👍 Personally I think default cocoa menu is prefered to custom UI when it comes to menu bar apps anyway.

**Comment by ameshkov** [comment]
Done a long time ago in the first v2.0 nightly version, closing this: https://adguard.com/en/blog/adguard-for-mac-gets-nightly/
