### ISSUE TITLE
We should consider encrypting our safebrowsing database URLs 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#122]
Some AV software detect our .dmg as a malware.

**id 360496**

"Webroot would not let me install adguard. I asked them why and this was the response:

https://www.webroot.com/

What we found is that Adguard has unencrypted strings of their adware URL database in the file /Adguard.release.dmg/Adguard/Contents/Resources/default.db. We are detecting the string mrlmedia.net, which is a malicious URL. We are only detecting this in the .dmg itself, but we do not detect the app itself once installed.

The ideal fix is for Adguard to encrypt their database file. A work around to get this installed on your machine would be to temporarily shut down WSA, install Adguard, delete the .dmg, then launch WSA again."

**Comment by ameshkov** [comment]
@Stillness-2 we should encrypt SQLite db.
