### ISSUE TITLE
Why AdGuard writing so much on disk?

### ISSUE THREAD

**Issue by dantecoding** [AdguardTeam/AdguardForMac#1220]
### AdGuard version

2.9.2.1234

### Browser version

Safari 16.4

### OS version

Mac OS 13.3

### Issue Details

Steps to reproduce:
1. Run AdGuard
2. After some time (1-2 days)
3. Check disk usage

### Actual Behavior

AdGuard using less 100Mb

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="1056" alt="image" src="https://user-images.githubusercontent.com/1853220/229313134-eca7f531-6ebb-4c37-84bb-1413219d868d.png">

</details>

**Comment by Aydinv13** [comment]
@dantecoding Hi there!

This is not uncommon behavior because a lot of data may be written to the disk, such as the cache of certificates of sites visited, filter updates and any operations on them, logs and other temporary files.
