### ISSUE TITLE
"Filters - User rules" does not work on music.apple.com

### ISSUE THREAD

**Issue by wzxu** [AdguardTeam/AdguardForMac#1223]
### AdGuard version

2.9.2.1234 release

### Browser version

Safari Version 16.4 (18615.1.26.11.23), Arc Version 0.97.0 (38146)

### OS version

macOS Ventura 13.3.1

### What filters do you have enabled?

AdGuard Base filter, AdGuard Chinese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Enhanced Tracking List, CJX's Annoyances List, NoCoin Filter List

### Issue Details

Steps to reproduce:
1. Add rule "music.apple.com##.logo-container" in "Filters - User rules"
2. Visit music.apple.com

### Expected Behavior

Element gets hidden.

### Actual Behavior

Element does not get hidden.

(Same with other elements; my full rule was "music.apple.com##.logo-container,.navigation__native-cta,#scrollable-page > footer,.web-navigation__header,.web-navigation__native-upsell,.dt-footer")

Filtering works normally with other websites.

### Screenshots

<details><summary>Screenshots:</summary>

<img width="1034" alt="SCR-20230409-ncri" src="https://user-images.githubusercontent.com/5619348/230758684-c41db1ae-ffb0-4133-8f77-9baaebff9de3.png">
<img width="1436" alt="SCR-20230409-mytx" src="https://user-images.githubusercontent.com/5619348/230758626-1afe9539-4766-4305-9a57-9d333bd8bd2b.png">

</details>

**Comment by Aydinv13** [comment]
@wzxu Hi there!

To filter music.apple.com, you have to remove the domain apple.com from these exclusions lists:
1) HTTPS exclusions (Gear -> Preferences -> Network -> Exclusions) 
2) Advanced settings (Gear -> Advanced -> Advanced Settings -> network.extension.exclusions.domains)
The domain was added there because of compatibility issues related to MacOS Big Sur.

**Comment by wzxu** [comment]
@Aydinv13 Thanks. Changing those works. 

Question: Will this cause said compatibility issue or other side effects if I'm on Ventura?

Also, since these only affect network filtering, it should make sense to keep cosmetic filters working, no? (But of course if they're somehow intertwined and cannot be separate settings you'd know better than me. Just feel like it should work.)

**Comment by wzxu** [comment]
> @wzxu
> 
> It's not supposed to affect the Ventura OS or have any side effects. For cosmetic rules to work, you need to inject scripts into the page, and that requires HTTPS filtering. But if you visit the HTTP site, while it is excluded by the HTTPS protocol then the cosmetic rules will work.

I see. Cheers!
