### ISSUE TITLE
ECH feature is not working with Kext & PAC Filtering mode

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardForMac#1226]
### AdGuard version

2.10

### OS version

10.15

### Issue Details

1. Install the latest release
2. Switch to Kext or Auto Proxy filtering mode
3. Go to https://crypto.cloudflare.com/cdn-cgi/trace/

### Expected Behavior

Sni = encrypted is displayed 

### Actual Behavior

Sni = plaintext is displayed 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by ameshkov** [comment]
Not sure if it's actually critical though.
