### ISSUE TITLE
Latest version preventing websites from loading on first visit 

### ISSUE THREAD

**Issue by nicholascarey** [AdguardTeam/AdguardForMac#1228]
### AdGuard version

2.10.0.1272

### Browser version

Safari 16.4, Firefox 112.0

### OS version

macOS 13.3.1

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Block Push API, Block Location API, Block Java, Remove X-client-Data header

### Issue Details

Since the latest update a couple of days ago AdGuard is blocking websites from loading on first visit. The sites never load - there is only a stuck progress bar.

It's not all websites, but seems to be related to the initial download of cookies being blocked. On a site with an issue, if i disable AdGuard and reload the website it will work fine once AdGuard is reactivated. Sometimes i have to deal with the cookies request prompt, but it is not limited to sites which have these. I only know this because in an attempt to get browsing working again I reset Safari to remove all cookies and website data. 

Even after this random sites often hang or fail to load and browsing in general feels broken in Safari. 

The issue occurs in both Safari and Firefox, but is MUCH worse in Firefox, which is essentially unusable if AdGuard is on. The above procedure does not help very much. 

Sites where i saw the most problems include all Google sites (incl. Mail), Github, and some commerce sites like https://www.gooutdoors.co.uk/ and https://www.cotswoldoutdoor.com/

### Expected Behavior

Being able to visit websites obviously

### Actual Behavior

Not being able to visit websites

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by nicholascarey** [comment]
I am also seeing issues in other apps, such as my mail app (Mimestream) where images fail to load, entire messages take 5-6 seconds to load, or never do and are completely blank.

**Comment by Aydinv13** [comment]
@nicholascarey Hello!

To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and **remember the exact time** it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by nicholascarey** [comment]
I sent a log, but the issue has improved somewhat (no idea why) so i haven't been able reproduce the worst issues. But i am still having occasional weird behaviours and some sites just feel a bit broken. E.g. eBay for a long time wouldn't load any product images, but this eventually fixed itself.

**Comment by nicholascarey** [comment]
Well of course as soon as i wrote that i reencountered the main issue! I sent a follow up email and log.

**Comment by nicholascarey** [comment]
I was premature in saying the issue had improved. If anything it got worse. Same issues - websites I hadn't visited before taking up to a minute or longer to first load, or not loading at all until i had disabled AdGuard. Other sites i had been using fine had issues - e.g. Ebay wouldn't work at all for around 15 minutes for no reason, then started working. Other sites were slow or partially broken. Email messages were missing images or completely blank. 

This all culminated in my WiFi completely stopping working for everything, even after i had quit AdGuard and until i restarted my machine.  Not saying AdGuard was definitely at fault for this but I have to suspect it was.  

I eventually couldn't take it any more and reinstalled the most recent version of AdGuard completely. Same issues. I then downgraded to v2.9.2.1234. Same issues again. 

I then downgraded to v2.9.1.1217 and now everything is working perfectly. The difference is like night and day, which made me realise how bad it had gotten - websites are responsive and load instantly and work fine, even ones i have never visited before!  It made me realise on the latest version virtually every site i had been visiting had a pause while it first loaded. 

I don't know what changes you have introduced that could be causing this, but I really hope you fix it because it's unusable for me in its current state.

**Comment by Aydinv13** [comment]
@nicholascarey 

Please send the debug logs as was explained [here](https://github.com/AdguardTeam/AdguardForMac/issues/1228#issuecomment-1508291108) because yours are not detailed.

Also, have you tried disabling and enabling DNS protection?

**Comment by Aydinv13** [comment]
The issue closed due no possibility to get detailed logs from the user.
