### ISSUE TITLE
WARP gets an error "unable to connect" if AdGuard is already running

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardForMac#1234]
### AdGuard version

2.10

### OS version

13.3.

### Issue Details

Steps to reproduce:
1. Install WARP
2. Run AdGuard
3. Try to to connect via WARP

### Expected Behavior

WARP successfully connected

### Actual Behavior

Unable to connect error

### Screenshots

<details><summary>Screenshot</summary>

![image001](https://user-images.githubusercontent.com/73467237/233303297-49622c8b-0b69-4f98-bd95-a9cff63f10cd.png)

</details>

**Comment by brknstrngz** [comment]
I ran into this as well. After digging through the debug logs of the Warp client, applying the following DNS rewrites (my only upstream DNS is a self-hosted instance of Adguard Home) solved this for me:

warp-svc to 127.0.2.2
warp-svc to 127.0.2.3
warp-svc to fd01:db8:1111::2
warp-svc to fd01:db8:1111::3

I wish I could remember why it was these particular 4 addresses, it has been a while back.
