### ISSUE TITLE
AdGuard won't start after `systemextensionsctl reset`

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardForMac#1238]
### AdGuard version

2.10

### OS version

11.7

### Issue Details

Steps to reproduce:
1. Disable SIP
2. Reset settings of AdGuard -> Close
3. Perform this command in terminal `systemextensionsctl reset`
4. Restart Mac
5. Launch AdGuard for Mac

### Expected Behavior

AdGuard started successfully. Filtering is working.

### Actual Behavior

AdGuard is not functioning.

### Screenshots

<details><summary>Screenshot:</summary>

<img width="500" alt="up85_yc7qq" src="https://user-images.githubusercontent.com/73467237/235712590-333d55a9-181b-4543-9f4d-573f2d4e64ea.png">
</details>

**Comment by Stillness-2** [comment]
If you restart the Mac after resetting system extensions, the problem does not occur
