### ISSUE TITLE
Incorrect status of HTTPS filtering in Assistant if site is in list of HTTPS exceptions

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1240]
### AdGuard version

2.10.0.1272 release

### Browser version

Google Chrome 113.0.5672.92 (arm64)

### OS version

macOS 13.3.1 (a) (22E772610a)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard Experimental filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties, Hide your User Agent, Remove X-client-Data header, Protect from DPI

### Support ticket ID

756372

### Issue Details

Steps to reproduce:
1. Enable `Filter HTTPS protocol` and `Filter websites with EV certificates` options in General Network settings
2. Make sure `proton.me` and `tinkoff.ru` are in the HTTPS exclusion list
3. Go to https://mail.proton.me or https://journal.tinkoff.ru/

### Expected Behavior

If the site is in the HTTPS exclusion list, then on macOS the HTTPS filtering status is listed as disabled in the Assistant, and you can enable it.

### Actual Behavior

If the site is in the HTTPS exclusion list, then on macOS the HTTPS filtering status is listed as enabled in the Assistant, although in fact it does not work and cannot be enabled, unlike on Windows.

### Screenshots

<details><summary>Screenshots from macOS:</summary>

![Screenshot 2023-05-10 at 01 45 48](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/d2cec2a4-7772-449c-94af-8e3cd3cbcd99)

![Screenshot 2023-05-10 at 01 44 34](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/f0e460df-16ce-40d1-b2ad-b5aeef78bdb8)

</details>

<details><summary>Screenshots from Windows:</summary>

![image](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/8f3d06e4-2c4d-4b69-807c-4ee775b35dbf)

![image](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/86739660-ad37-4c98-8a2d-5743890e6c77)

</details>

### Additional Information

There may be a problem with https://github.com/AdguardTeam/AdguardAssistant, but why then does it work correctly on Windows?

**Comment by cryptopatik22** [comment]
Hey guys, the user provided us with some debug logs in the ticket 756372.

**Comment by Aydinv13** [comment]
@rakleed Hello!

Your issue duplicates https://github.com/AdguardTeam/AdguardForMac/issues/1063, so I'm closing it.

**Comment by rakleed** [comment]
@Aydinv13 but in my case the problem is not with the www prefix, but with the subdomain. If you consider my issue to be a duplicate, then #1063 needs to be changed to the names suitable for my case as well.

**Comment by rakleed** [comment]
@Aydinv13

**Comment by Aydinv13** [comment]
The related issue was changed according to your case as well.
