### ISSUE TITLE
HTTPS filtering causes "Secure Connection Failed" error

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdguardForMac#1242]
### AdGuard version

2.10.0.1272 release

### Browser version

Firefox 113.0.1 (64-bit)

### OS version

macOS 13.3.1 (a)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Liste AR, EasyPrivacy, Web Annoyances Ultralist, Adblock Warning Removal List, Fanboy's Enhanced Tracking List, I don't care about cookies, NoCoin Filter List, Dandelion Sprout's Annoyances List

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Disable cache for third-party requests, Block the third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Block Java, Hide Referrer from third-parties, Hide your User Agent, Remove X-client-Data header

### Issue Details

Steps to reproduce:
1. Enable "Filter HTTPS Protocol"
2. Browser internet intermittently for 24 to 48 hours without restarting Mac

Disabling and enabling WiFi fixes this problem for about 1 minute. Restart fixes it for at least a couple of hours. Disabling HTTPS filtering fixes it permanently.

### Actual Behavior

Some websites (like, docs.google.com) fail to load and get a secure connection error (PR_END_OF_FILE_ERROR). Internet would stop functioning completely. Even ping in terminal would return only dropped pings.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="820" alt="Screenshot 2023-05-11 at 9 05 13 PM" src="https://github.com/AdguardTeam/AdguardForMac/assets/39851020/064b89c3-13c8-4951-b812-6437af380489">

</details>

<details><summary>Screenshot 2:</summary>

<img width="868" alt="Screenshot 2023-05-10 at 11 26 30 AM" src="https://github.com/AdguardTeam/AdguardForMac/assets/39851020/1ff8f55f-ed26-499a-9a91-69b179fd3077">

</details>

**Comment by Aydinv13** [comment]
@tomiams any news?

**Comment by Aydinv13** [comment]
1) Do you use any other software affecting network traffic?
2) What if you go to `about:config` via address bar-> Accept Risk and continue - > turn off/on toggle `security.enterprise_roots` in Mozilla?
3) Please grab debug logs if the [latest](https://github.com/AdguardTeam/AdguardForMac/releases/download/v2.11.0-beta/AdGuard-2.11.0.1290-beta.dmg) build did not bring results:
- Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
- Reproduce the issue and remember the exact time it happened;
- Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
- Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Aydinv13** [comment]
@tomiams take a look please.

**Comment by Aydinv13** [comment]
The issue has been closed because of no response. Can be opened again if relevant.
