### ISSUE TITLE
Browser Assistant icon goes gray randomly in v2.10.1

### ISSUE THREAD

**Issue by Aydinv13** [AdguardTeam/AdguardForMac#1247]
### AdGuard version

2.10.1

### Browser version

Chrome

### OS version

13.4

### Issue Details

The issue is again relevant

https://github.com/AdguardTeam/AdguardForMac/issues/1025#issuecomment-1569124502

### Actual Behavior

The color of the icon should match the current state of the application.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Stillness-2** [comment]
@rakleed Эта история с засериванием регулярно повторяется сейчас?

**Comment by rakleed** [comment]
Редко, наверное раз в несколько дней.
