### ISSUE TITLE
Clicking on notification doesn't remove it from Notification Center

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1252]
### AdGuard version

2.11.0.1289 nightly

### Browser version

Google Chrome 114.0.5735.133

### OS version

macOS Ventura 13.4.1 (22F82)

### Issue Details

Steps to reproduce:
1. Disable AdGuard on https://adguard.com via AdGuard Browser Assistant
2. Open Notification Center
3. Click on AdGuard Notification

### Expected Behavior

Clicking on a notification removes it from the Notification Center.

### Actual Behavior

Clicking on a notification doesn't remove it from the Notification Center.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Screenshot 2023-06-23 at 03 56 38](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/962cca63-19f0-480e-9a71-ac34b4d47f51)

</details>

**Comment by Aydinv13** [comment]
Hi @rakleed

It's hard to call it a bug and probably Apple has stopped supporting our API properly (there was no change in this part of the application). Nevertheless we will check it out, thank you.

**Comment by rakleed** [comment]
@Aydinv13 why is this not a bug? If Apple has deprecated some API in modern versions of macOS and you ignored it, then the problem is on your end.
