### ISSUE TITLE
Experimental HTTP/3 filtering support

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#1253]
AdGuard should start supporting HTTP/3 filtering in experimental mode. For now, the functionality will only be available through advanced settings.

**Comment by philrosenthal** [comment]
When I enable this feature, AdGuard keeps crashing within a few minutes. I allowed it to submit feedback when it crashed. Is there anything else I can do to help debug what's going on?

**Comment by Aydinv13** [comment]
@philrosenthal could you please collect the debug logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.
