### ISSUE TITLE
Parallel usage of AdGuard VPN and ZyWALL SecuExtender 

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdguardForMac#1255]
### AdGuard version

2.1.0.407 release

### OS version

13.4.0

### Support ticket ID

Issue description provided by the user: 

```
Для подключения к офисной сети используется app ZyWALL SecuExtender (приложение зикселей организовывает впн подключение на железяках zyxel).
И так же нужно подключить AdGuard vpn.
К примеру надо чтобы была доступна офисная база данных (за это отвечает ZyWALL SecuExtender подключаюсь к офисной сетке), а AdGuard vpn нужен чтобы был доступен GitHub copilot.
Вместе их не запустить, ZyWALL начинает с ума сходить, крутится вертится в итоге мак заводится как чёрт
Добавление ZyWALL в исключения не помогает.
Сейчас попробовал настроить только на определенных сайтах и в определенных программах.
Включил ZyWALL и adguard vpn,  то же самое, ZyWALL перестает работать, подвисает, по иконке кликаешь а он не реагирует, внутренний корпоративные сервисы перестают работать
```

### Issue Details

Steps to reproduce:
1. Connect to the internal office network through ZyWALL 
2. Activate the VPN connection in the AdGuard app

### Expected Behavior

The office databank is accessible through ZyWALL SecuExtender, while parallel access to external services (such as GitHub Copilot) can be achieved using AfGuard VPN.

### Actual Behavior

The ZyWALL SecuExtender fails to function when connected to the VPN. The internal office network is inaccessible.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment]
Issue moved to [AdguardTeam/AdGuardVPNForMac #226](https://github.com/AdguardTeam/AdGuardVPNForMac/issues/226) via [**Zenhub**](https://www.zenhub.com/)
