### ISSUE TITLE
AdGuard won't respond to any command when working with Shadowrocket

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1257]
### AdGuard version

Version 2.11.0.1289 nightly

### Browser version

Arc Version 0.109.1 (39787)

### OS version

ventura 13.4.1

### Issue Details

Steps to reproduce:
i still don't know why this happens. it seems when you try to change the wifi network while the VPN is on this happens

### Actual Behavior

it won't respond to any command

### Screenshots

https://github.com/AdguardTeam/AdguardForMac/assets/40741745/e550bef5-935e-4728-8e2e-7e8df278f7aa

</details>

**Comment by lucaszischka** [comment]
Same issue here, but I also have no internet connection as long as AdGuard is running and activated (and turning it off/quitting doesn't work). So I removed it from my autostart list and force quit it via the activity manager for now.
AdGuard Version: 2.11.0.1292
MacOS Version: 13.4.1 (22F82)

**Comment by Aydinv13** [comment]
@aliafshany @lucaszischka Hi there.

Could you please download the [**Nightly**](https://agrd.io/mac_nightly) build, turn on **Debug** logging level (Gear -> Advanced -> Logging -> Logging Level) and export the logs when the issue occurs (also remember the exact time of reproducing). 
Have been using Shadowrocket with AdGuard for some time and no problems on my side.

**Comment by aliafshany** [comment]
@Aydinv13 
I'm using the nightly version all the time.
Yeah, I've been using Shadowrocket with AdGuard simultaneously and I've seen some bugs here.
Sure, I will send you the logs as soon as this happens.

**Comment by Aydinv13** [comment]
@aliafshany 

any news here?

**Comment by aliafshany** [comment]
> @aliafshany
> 
> any news here?
@Aydinv13 
It happened again last night and unfortunately the log mode was on default so I couldn't send it. I'm on it though, and will send the requested logs as soon as possible. No worries. :)

**Comment by Aydinv13** [comment]
@aliafshany 

For now I'm closing the issue. As soon as you send the logs, I'll reopen it.
