### ISSUE TITLE
EXTREMELY BAD CUSTOMER SUPPORT

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/AdguardForMac#1262]
I have asked for technical support 6 long days ago and have recieved NO RESPONSE.
Adguard have acknowledged by support request, my support request number is:
AdGuard Support Request 774382
I have a fully paid Lifetime Personal License for your Adguard ad blocker.
Excessively long delays of 6 days are unacceptable.
As a paying customer I expect to recieve much better and much, much faster responses to support requests.
A fully paid customer of Adguard should NEVER, EVER HAVE TO WAIT 6 days and still NOT RECEIVE ANY SUPPORT AT ALL.
YOUR CUSTOMER SERVICE IS EXTREMELY BAD.
IF I HAD KNOWN HOW BAD YOUR CUSTOMER SUPPORT IS I WOULD NEVER HAD PAID MONEY FOR AN ADGUARD LIFTIME LICENSE.
THIS EXTREMELY SLOW CUSTOMER SUPPORT IS SIMPLY NOT GOOD ENOUGH.

I have repeatedly complained to Adguard about their extremely bad customer support multiple times via email and STILL NO RESPONSE AT ALL.

**Comment by Aydinv13** [comment]
@jputting Hello!

The information was passed on to support team. They will answer as soon as possible.

**Comment by jputting** [comment]
Hi, 
I have indeed repeatedly emailed their customer support and complained loud and strong about their lack of response.

But still after many, many, many attempts they DO NOT RESPOND AT ALL.

I have paid good money for a Personal Lifetime License for their Adguard app for macOS.

As a paying customer who is supporting their business it is only fair and reasonable to expect that they support customers and respond quickly to requests for support.

It is TOTALLY UNACCEPTABLE TO HAVE EXTREMELY LONG DELAYS FOR CUSTOMER SUPPORT AND AFTER 6 LONG DAYS, STILL NO RESPONSE.

If i had known in advance that Adguard's customer support is extremely  bad with very, very long delays in getting a response from them, I WOULD NEVER EVER HAVE PAID GOOD HARD EARNED MONEY TO A COMPANY WITH SUCH EXTREMELY POOR CUSTOMER SERVICE.

IT IS SHAMEFUL THAT ADGUARD ACCEPTS OUR MONEY FOR THEIR PRODUCTS AND THEN THEY TAKE FOREVER AND A DAY TO PROVIDE CUSTOMER SUPPPORT.

I will be warning all my friends and relatives to stay well away from Adguard as feel my purchase of a Lifetime Personal License has been a total waste of  my money.

Adguard is a total 100% SCAM, they rip people of by taking our hard earned money and they DO NOT PROVIDE CUSTOMER SUPPORT.

**Comment by Aydinv13** [comment]
@jputting 

Your ticket is already being dealt with by technical support specialists. I'm closing this issue for now.
