### ISSUE TITLE
Incorrect displaying in the Filtering Log

### ISSUE THREAD

**Issue by OlgaPetukhova** [AdguardTeam/AdguardForMac#1266]
### AdGuard version

2.11.0.1292

### OS version

MacOS Monterey 12.6.5

### What filters do you have enabled?

AdGuard Base filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Support ticket ID

#774382

### Issue Details

Steps to reproduce:
1. Open the website https://advocatechannel.com/oceans-exploration-why-so-risky
2. Thumbnails of articles from "Trending Stories From Equal Pride"  are blocked by AdGuard Social Media filter
3. Open AdGuard Filtering Log
4. There are no requests blocked by AdGuard Social Media filter, but the thumbnails are blocked by this specific filter

### Actual Behavior

When the AdGuard Social Media Filter is subscribed to and activated the thumbnail images are gone, but no request can be found in the Filtering Log.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment]
Closed as a duplicate https://github.com/AdguardTeam/CoreLibs/issues/180
