### ISSUE TITLE
cert Verified by: Adguard Personal gets replaced by website cert

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForMac#127]
When I am browsing the internet with my Firefox or Chrome browser, all of a sudden I see ads on a webpage, it can be a Google/Youtube or any other webpage.

When I click on the https green icon in FF or Chrome and see the cert, it is for example COMODO or any other secure cert of the website itself and it is NOT Adguard Personal cert, that is why I am starting to get ads. 

This is a bug and should be fixed. 

How to reproduce:
open FF or Chrome, go to:
https://onhax.me/
Click on one of the post
when the post opens, you see the ads
if you don't see it,
click back and select other posts,

within 3 retries you will see ads.

**Comment by ameshkov** [comment]
@Stillness-2 cannot reproduce it with v1.3.1 beta build you've sent me last time.


Could you please attach it here?

**Comment by worldsdream** [comment]
Just right now, youtube ads came through. Looking at the cert, it was of youtube. Not adguard.

**Comment by worldsdream** [comment]
Can you sent me the beta? I am still having this problem, every day...

**Comment by Stillness-2** [comment]
https://www.dropbox.com/s/ctig2ihmzqq8i94/Adguard.zip?dl=1

**Comment by worldsdream** [comment]
Thanks, installing now and I will report back.

**Comment by worldsdream** [comment]
Still happening with the beta version. I removed the app completely from the app with cleanmymac. installed it fresh.

**Comment by worldsdream** [comment]
I just updated to macOS Sierra, still having this problem.

**Comment by Stillness-2** [comment]
@worldsdream 
When you visit sites in **FF**, using `http`, filtering works?
Does the problem exist with `https` if you are using **Safari**?

**Comment by worldsdream** [comment]
@Stillness-2 

FF https: filtering not/sometimes working
FF http: filtering working
Chrome https: filtering not/sometimes working
Chrome http: filtering working
Safari https: Not tested, going to use it now and report back
Safari http: Not tested, going to use it now and report back

Sometimes the https is working and sometimes not, if I clear the cache, it works. But then after couple of minutes it's not working.

**Comment by ameshkov** [comment]
@Stillness-2 we need to record some sort of extended log in this case.

At least record certificates validation data there.

**Comment by worldsdream** [comment]
@ameshkov What should I do now so this can be fixed?

**Comment by ameshkov** [comment]
@worldsdream waiting for @Stillness-2 to provide another build with better logging.

We suspect that the issue is caused by the fact that Adguard considers remote server certificate invalid and stops https filtering for the domain.

**Comment by Stillness-2** [comment]
https://www.dropbox.com/s/ctig2ihmzqq8i94/Adguard.zip?dl=1 - this is version with extended logs.
@worldsdream Use this app version, and when problem is occurred, send support request from Adguard app.

**Comment by worldsdream** [comment]
@Stillness-2 Ok I installed it and cleared the cache of the browser. Within couple of minutes I encountered this problem and I did sent the bug through the support button. I did add the link of this github into it, so you can find it easily.

I used the Firefox browser, stable release.

**Comment by worldsdream** [comment]
@Stillness-2 any ETA when you have a new build available to test on my machine?

**Comment by ameshkov** [comment]
@worldsdream we are planning to release next beta tomorrow, and right after that @Stillness-2 promised us a new build specially for this issue.

**Comment by worldsdream** [comment]
I am using Adguard Mac 1.3.1 beta for the last 4 hours, I have not encountered this problem so far, I hope this is fixed with the 1.3.1 release. Let me check for the coming days and I will report back.

**Comment by ameshkov** [comment]
We've been discussing this issue with @Stillness-2 lately, the test build will be ready next week.

It seems that the issue is caused by the way we use to test remote address availability. For some reason address is considered unavailable and socket control is passed back to the browser. We may need some time to add the proper logging.

**Comment by Stillness-2** [comment]
@worldsdream contact me in Skype please. :)

**Comment by worldsdream** [comment]
Contacted and explained that I dont have my mac at the moment. Will contact @stillness-2 when I have it back.

**Comment by ameshkov** [comment]
It seems that this issue is solved by #263
