### ISSUE TITLE
AdGuard crashes on Wi-Fi switching

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1270]
### AdGuard version

Version 2.12.0.1350 nightly

### Browser version

arc Version 1.0.1 (40233)

### OS version

ventura 13.4.1

### Issue Details

Steps to reproduce:
1. switch to another wifi while shadowrocker is on
2.
3.

### Expected Behavior

Adguard would crash and you have to turn it on manually

### Actual Behavior

adguard crashes and pops up "support" "close" buttons. 

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by aliafshany** [comment]
@Aydinv13  logs have been sent already.

**Comment by Aydinv13** [comment]
@aliafshany Hi there!

Will be fixed in the upcoming nightly version. Thanks for reporting.

**Comment by Aydinv13** [comment]
New nightly version has been published, so there shouldn't be any crashes now. Please let us know if something goes wrong. I'm closing this issue.
