### ISSUE TITLE
ECH feature interferes with DNS when using VPNs

### ISSUE THREAD

**Issue by eccgecko** [AdguardTeam/AdguardForMac#1278]
### AdGuard version

2.11.0.1292 release

### Browser version

Safari 16.6 (18615.3.12.11.2)

### OS version

macOS Ventura 13.5

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, AdGuard Annoyances filter, Peter Lowe's Blocklist, Online Malicious URL Blocklist, Fanboy's Enhanced Tracking List, NoCoin Filter List

### What Stealth Mode options do you have enabled?

Hide your search queries, Self-destruction of third-party cookies, Block Push API, Block Location API, Block Java, Hide Referrer from third-parties, Remove X-client-Data header

### Issue Details

Steps to reproduce:
1. Enable ECH in Advanced Settings (network.https.ech.enabled true) and enable DNS Protection in AdGuard Desktop.
2. Connect to a remote VPN server that also sets local DNS server to use remote VPN server.
3. Browse web

### Expected Behavior

When connecting to a remote VPN that sets the DNS server, web browsing should not be broken by AdGuard's DNS protection or ECH. 

### Actual Behavior

I have the latest AdGuard Desktop release version installed (2.11.0.1292 release), and after setting up an OpenVPN server on my home router, I noticed some issues with my connection when surfing the web remotely using a VPN to tunnel back home. Many web pages would take a long time to resolve, or else the server could not be found on first attempt, but would be found upon a refresh.

After much troubleshooting for many hours, where I was sure that the issue was due to incorrect MTU size on the openVPN tunnel, I finally realised it wasn't that at all, because the issue was only present in Safari, and not Microsoft Edge. This led me to believe the issue may actually be with the computer and not the VPN, and finally going down the troubleshooting rabbit hole further I finally narrowed down the issue to it being to do with AdGuard DNS protection being switched on within AdGuard Desktop. Further investigation and I narrowed the cause down even further to ECH being switched on.

So there is some kind of incompatibility between ECH in AdGuard Desktop whilst using a VPN. I believe it may be down to a conflict between different systems trying to take control of setting the DNS server. The OpenVPN tunnel is setting the DNS server to be the remote server (what I want, as I can then have domain-name resolution for my LAN devices back home). But AdGuard Desktop, specifically ECH, is somehow interfering with that. When I browse to ipleak.net on the VPN, the DNS servers are the ones provided by my home LAN router (the VPN server). This is the case with AdGuard DNS switched on or off. However, as soon as I switch ECH off from within AdGuard Desktop, all the browsing issues go away instantly, and browsing and name resolution is fast via the VPN.

I'm not sure what exactly the process is behind the scenes that causes this issue, but I thought I should report it. I believe that AdGuard should either detect a local DNS server change due to VPN connection initiation and gracefully hand-off DNS to VPN until disconnect, or else AdGuard should maintain DNS protection and tunnel DNS through VPN, but without errors. Ideally there would be the possibility of automating AdGuard DNS switching itself off when using a VPN that sets the DNS server, or at least switching off ECH, but I don't know how feasible that is.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment]
@eccgecko Hello!

To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and **remember the exact time it happened**;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.
