### ISSUE TITLE
`adguard.com` doesn't open in Russia with `Protect from DPI` enabled

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1288]
### AdGuard version

2.11.0.1292 release

### Browser version

Google Chrome 116.0.5845.110

### OS version

macOS Ventura 13.5 (22G74)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties, Hide your User Agent, Remove X-client-Data header, Protect from DPI

### Support ticket ID

796257

### Issue Details

Steps to reproduce:
1. Make sure `Protect from DPI` option is enabled.
2. Open `adguard.com` from Russia

### Expected Behavior

The site is up and running.

### Actual Behavior

The site does not open with the error "ERR_TIMED_OUT".

### Screenshots

<details><summary>Screenshot:</summary>

![Screenshot 2023-08-24 at 16 04 57](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/f63978de-284d-4a4d-baae-8f1a08723358)

</details>

**Comment by sfionov** [comment]
@rakleed Yes, it's IP is blocked in non-DPI way

**Comment by sfionov** [comment]
You need to use VPN for that, Protect from DPI is not universal spell against censorship.

As of adguard.com, it is still unclear why it is blocked. Russian censorship authority probably assumes that this site may be used to download AdGuard VPN but this is not true.

However, you may use [official mirror](//adguard.app)

**Comment by rakleed** [comment]
@sfionov @Aydinv13 can you develop a workaround to these new blocks so I don't have to use a VPN?

**Comment by rakleed** [comment]
@sfionov ping

**Comment by sfionov** [comment]
@sfionov I can't add anything to my previous message. Not every type of block can be bypassed without VPN.
