### ISSUE TITLE
AdGuard Causes Bluetooth Interference in Sonoma

### ISSUE THREAD

**Issue by validatedev** [AdguardTeam/AdguardForMac#1296]
### AdGuard version

2.11.0.1292

### Browser version

Arc Browser 1.7.0

### OS version

macOS Sonoma Developer Beta 7 (Version 14.0 Beta (23A5337a))

### What filters do you have enabled?

AdGuard Base filter, AdGuard Turkish filter, AdGuard Annoyances filter, Adblock Warning Removal List, Others

### Support ticket ID

805835 (I don't think the diagnostic is populated, as I reinstalled AdGuard)

### Issue Details

In macOS Sonoma, I had a strange bug via the AdGuard app. If both Ethernet and Wi-Fi are enabled (connected), and if I want to use the computer for a while in clamshell mode, eventually Wi-Fi flickers and after that Bluetooth sound stutter. The stutter does not happen with the integrated speaker or wired earphones. And I am sure the cause is AdGuard because if I uninstall it completely, I don't have such an issue. Furthermore, in macOS Ventura, it is flawless. So no actual interference in my environment. Such a strange bug, but yeah, it happens. Reboot (or switching Wi-Fi off-on) fixes it for a while, but it happens again. I've tried Nightly and Beta builds as well, but no luck. Disabled all components such as DNS, Advanced Tracking Protection, Userscript Manager, etc., but no luck either. Thanks in advance.

Steps to reproduce:
1. Use the computer for a while (1-2 hours) with Bluetooth output enabled and Ethernet and Wi-Fi are also enabled.
2. You can see that the sound is stuttering.

### Expected Behavior

The sound coming from Bluetooth device is smooth.

### Actual Behavior

The sound coming from Bluetooth device stutters.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

I think it triggers something inside the Wi-Fi, which causing 2.4 GHz interference from Wi-Fi to Bluetooth. Just guessing. By the way, I am using MacBook Pro 13" M2.

**Comment by validatedev** [comment]
I have shared logs to the support with same support ticket ID.

**Comment by Aydinv13** [comment]
@validatedev Hi!

We've received the data, thank you. We'll get back to you once we've analyzed them.

**Comment by validatedev** [comment]
@Aydinv13 Thank you! I'm ready for providing further debug info whenever you want 😁

**Comment by Aydinv13** [comment]
@validatedev please check the behaviour with the latest [build](https://agrd.io/mac).

**Comment by validatedev** [comment]
I had same problem without AdGuard also. Thus, I reverted to Ventura. I am not sure the cause is just AdGuard, so I'm closing the issue. Thanks for the advice though.
