### ISSUE TITLE
[Feature request] Add more Chinese filters

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForMac#13]
1. ChinaList+EasyList: http://sub.adtchrome.com/adt-chinalist-easylist.txt
2. CJX's Annoyance List: https://raw.githubusercontent.com/cjx82630/cjxlist/master/cjx-annoyance.txt

Original requester:
XQI-204-82994

**Comment by Hongbo-Miao** [comment]
Cool, by the way, 修正 here means "revisions".

**Comment by ameshkov** [comment]
Removed:)

**Comment by Hongbo-Miao** [comment]
Hi @ameshkov these two filters if can be added in OS X version, that will be great too! :)

**Comment by ameshkov** [comment]
Yep, we'll do it soon. Just check the filters list after this issue is closed.

**Comment by Hongbo-Miao** [comment]
Thanks!

**Comment by ameshkov** [comment]
@mmigi, add these filters to group "Other"
Don't forget to set proper display_number field.

**Comment by ameshkov** [comment]
Done

**Comment by Hongbo-Miao** [comment]
I saw, works perfect!
