### ISSUE TITLE
Adguard compatibility with Opera built-in VPN 

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#130]
Adguard's HTTPS filtering breaks VPN connection for SurfEasy VPN (Opera built-in)

**Comment by vozersky** [comment]
same with [Adguard for Windows](https://github.com/AdguardTeam/AdguardForWindows/issues/1174)

**Comment by ameshkov** [comment]
The issue is resolved in Opera Dev.

**Comment by ameshkov** [comment]
Ah, I am wrong, the issue is still here.

**Comment by ameshkov** [comment]
@Stillness-2 contact me when you are ready to work on this issue.

**Comment by Stillness-2** [comment]
#123
