### ISSUE TITLE
Unable to apply any of the DNS servers

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1300]
### AdGuard version

Version 2.12.0.1380 nightly

### Browser version

Arc Version 1.8.1 (41651)

### OS version

Ventura 13.5

### Issue Details

Steps to reproduce:
1. just set your Adguard DNS Settings to cloudflare doH

### Actual Behavior

When you open https://one.one.one.one/help/, even though you have set your settings to Cloudflare DoH, the site indicates "NO!"

### Screenshots

![CleanShot 2023-09-19 at 20 21 28](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/79a5a1df-f498-40b1-86ec-0566f4a57fed)
![CleanShot 2023-09-19 at 20 22 08](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/e1880edf-32c3-4b73-860c-576707a05482)

**Comment by Aydinv13** [comment]
@aliafshany hi there.

Is it only happening on this server/protocol? Does your computer have a VPN or software that affects network traffic? Do you see DNS requests in Filtering log (request details)?
Could you try the command `sudo dscacheutil -flushcache` then check again please. You may reboot just in case.

**Comment by aliafshany** [comment]
@Aydinv13 
- i've not checked the other servers. idk how can i verify the other ones if i'm using DoH.
- i got a vpn but its DNS has been set to DoH.
- i see DNS requests in Filtering log. here is a screenshot of the details at then end of this comment.
![CleanShot 2023-09-20 at 12 20 48](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/e882f72a-b962-4657-9205-22a92ef88d8a)
- i did ```sudo dscacheutil -flushcache``` but no luck!
- i have this issue on my adnroid too

**Comment by aliafshany** [comment]
when i run this command i get these results:

```scutil --dns | grep 'nameserver\[[0-9]*\]'
  nameserver[0] : 8.8.8.8
  nameserver[0] : 1.1.1.1
  nameserver[1] : 1.0.0.1
  nameserver[0] : 8.8.8.8```

is this normal?
and i have  only this line on my mac.
```nameserver 1.1.1.1``` in ```/etc/resolv.conf```

**Comment by aliafshany** [comment]
I encountered this issue on my Android device as well. Even though I have configured my DNS settings to AdGuard-QUIC, it is still malfunctioning. Please take a look at this demo: 


https://github.com/AdguardTeam/AdguardForMac/assets/40741745/f374fcc3-438f-4417-8bd6-f0d8b5d59849

**Comment by Aydinv13** [comment]
Please grab the debug logs and send to apple@adguard.com 
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by aliafshany** [comment]
just sent the logs!

**Comment by Aydinv13** [comment]
@aliafshany if you turn off VPN is everything ok? Has it started with the latest build?

**Comment by aliafshany** [comment]
@Aydinv13 
I recorded another video with different settings here. I'm using AdGuard DoH in the settings, and when I visit https://adguard.com/en/test.html, I see AdGuard DNS as "Not Running."

![CleanShot 2023-09-20 at 15 27 20](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/dee3609d-18d0-4a25-8344-b1bda84c40b7)

And this is the new video, without using any VPNs here.
https://github.com/AdguardTeam/AdguardForMac/assets/40741745/4c71e04f-f483-4c3b-b0b6-90819bed54a2

just sent another log for this video.
you can see timestamps in this video

**Comment by aliafshany** [comment]
>
@aliafshany if you turn off VPN is everything ok? Has it started with the latest build?


@Aydinv13  It was going on as far as I can remember. Turning off the VPN would not help here.

P.S. https://one.one.one.one/help/ is blocked here, and I can't access it without a VPN. Instead, I tried it on the Adguard test page.

**Comment by aliafshany** [comment]
@Aydinv13  It seems that AdGuard and Cloudflare DNS over HTTPS (DoH) are blocked here. That's why you can't reproduce this issue.
Is there any way I can confirm that these DoH services are blocked? I want to be sure.
