### ISSUE TITLE
Twitter Ads

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1303]
### AdGuard version

Version 2.12.0.1380 nightly

### Browser version

Arc Version 1.8.1 (41651)

### OS version

Ventura 13.5

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter

### Issue Details

Steps to reproduce:
1. just visit x.com
2.
3.

### Expected Behavior

you would see ads there
![CleanShot 2023-09-21 at 12 51 15](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/bcaad779-bb57-469e-a14a-683026e3ed35)

### Actual Behavior

Ads are in timeline

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information
I guess this started when I **changed** all of my **DNS** to AdGuard **IPv6** ones. These were the major settings I changed.

My AdGuard DNS settings are:

![CleanShot 2023-09-21 at 12 52 07](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/f876c721-cdca-425c-bb58-a7d51f810bd8)

My Wi-Fi and /etc/resolv.conf DNS settings are configured for AdGuard.

![CleanShot 2023-09-21 at 12 52 31](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/8d813016-fde1-488e-9b88-b096529de179)

**Comment by aliafshany** [comment]
I guess this is not a good place to open an issue. If you believe this is inappropriate, then you may close it. Thanks.

**Comment by aliafshany** [comment]
The number of ads I'm seeing is excessive.

**Comment by aliafshany** [comment]
Yes, I can confirm that when I changed my `/etc/resolv.conf` and DNS settings in Wi-Fi, all of the ads went away.

So, I don't know if IPv6 DNS is the cause or AdGuard DNS itself.

**Comment by aliafshany** [comment]
Another update: I changed the DNS in `/etc/resolv.conf` to AdGuard's IPv6, but I still don't see any ads. It appears that the only problematic area is in the `Wi-Fi settings under Details > DNS section`. I'll leave the DNS servers there as `1.1.1.1` and `1.0.0.1`.

![image](https://github.com/AdguardTeam/AdguardForMac/assets/40741745/a536cb83-9758-423e-ac92-d38ed9d279ef)

**Comment by Alex-302** [comment]
@aliafshany > just visit x.com

Is it a site?

What I see

<details>
<summary>Details</summary>

![image](https://github.com/AdguardTeam/AdguardForMac/assets/8361299/36072d62-5195-4d15-9dcd-5fd7929bcaa3)


</details>

**Comment by aliafshany** [comment]
> @aliafshany > just visit x.com
> 
> Is it a site?
> 
> What I see
> 
> Details

yes it is ex-Twitter! :|

**Comment by Aydinv13** [comment]
@aliafshany this issue duplicates https://github.com/AdguardTeam/AdguardForMac/issues/1300 as I can see, so lets discuss it there. I'm closing the current one.
