### ISSUE TITLE
Adguard 2.0 breaks Proton Bridge and Proton VPN

### ISSUE THREAD

**Issue by jfeuillet** [AdguardTeam/AdguardForMac#1304]
### AdGuard version

Version 2.12.0.1385 release

### Browser version

Safari Version 17.0 (19616.1.27.211.1)

### OS version

Sonoma 14.0

### What filters do you have enabled?

AdGuard Base filter

### Issue Details

Steps to reproduce:
1. Proton VPN 3.3.3
2. Proton Mail Bridge 3.5.0 
3. Latest release of Adguard for MacOS
4. 

### Expected Behavior

VPN opens first then mail bridge then adguard. I expected all to work transparently. 

### Actual Behavior

As soon as Adguard loads, Proton Mail Bridge breaks and claims no connectivity. Then Proton VPN breaks with no connection.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by alexx7311** [comment]
@jfeuillet Please go to AdGuard 'Preferences' >'Network' > 'Filtering mode' and change the mode to 'Automatic Proxy'. Did that help?

**Comment by jfeuillet** [comment]
That helped. Thanks.
