### ISSUE TITLE
AdGuard for Mac is not working on Safari in MacOS Sonoma

### ISSUE THREAD

**Issue by JTMG314** [AdguardTeam/AdguardForMac#1309]
### AdGuard version

AdGuard 2.12.0.1385 (newest)

### Browser version

Safari Version 17.0

### OS version

MacOS Sonoma 14.0 

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Block WebRTC, Block Push API, Block Location API, Hide Referrer from third-parties, Hide your User Agent, Mask your IP address, Remove X-client-Data header, Protect from DPI

### Issue Details

Steps to reproduce:
1. Install MacOS Sonoma
2. Open Safari
3. Getting the message: You Are Not Connected to the Internet
This page can't be displayed because your computer is currently offline.

### Expected Behavior

That Safari is still working as Intended.

### Actual Behavior

Safari has no Connection to the internet.
It is not because of some settings outside of Safari. The Tor Browser and every other app that needs internet to work, was normally working. But Safari was not.
When I disabled adblocking for the website nothing changed

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment]
@JTMG314 Hi there!

To troubleshoot this issue, we need to get the app logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Aydinv13** [comment]
@JTMG314 do you have Screen Time enabled on your device?

**Comment by JTMG314** [comment]
Yes but on Content & Privacy in Restriction

**Comment by enakr** [comment]
+ CRM 817461 with logs, start.log file and video

**Comment by JTMG314** [comment]
What is CRM 817461?
And how do I get the file start.log 
And what video?
I do not understand

**Comment by JTMG314** [comment]
I restarted my mac. Now everything is fine. Dont know what was the problem. I uninstalled one VPN and DNS program but that didnt do a thing. But now after the restart I dont know what was the solver for the problem. Because I changed to much.

**Comment by Aydinv13** [comment]
This is a known issue with Screen Time. In some cases only a reboot helps. Here is a [link](https://github.com/AdguardTeam/CoreLibs/issues/1790) to the initial task. This task was closed as a duplicate.
