### ISSUE TITLE
Adguard Breaks The Wi-Fi Connection

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1315]
### AdGuard version

Version 2.12.1.1391 nightly

### Browser version

Arc Version 1.10.1 (42026)

### OS version

Ventura 13.6

### Issue Details

Steps to reproduce:
1. Launch AdGuard.
2. Do your work.
3. It will happen on its own.

### Actual Behavior

Breaks the internet, and you have to turn off the Wi-Fi or turn off and on AdGuard itself.

### Screenshots

https://github.com/AdguardTeam/AdguardForMac/assets/40741745/b988ddfe-1420-411f-b83b-8a5372afa907

### Additional Information

It happened today. I didn't make any changes, and I was working as usual. Today, I had a lot of issues with my laptop. I want to tell you that there is nothing wrong with my VPN. It was working fine all this time.
and of course you can see that some times i can't turn AG off for some reasons

i have set the logging mode to Debug mode.
i will send you right away!

as of writing this issue. it happend again and i get DNS issues :/ (this is not on the logs)

**Comment by alexx7311** [comment]
@aliafshany Hello! Please go to AdGuard 'Preferences' >'Network' > 'Filtering mode' and change the mode to 'Automatic Proxy'. Did that help?

**Comment by alexx7311** [comment]
@aliafshany You can also try updating to the latest nightly version at https://agrd.io/mac_nightly
Does the problem still persist?

**Comment by aliafshany** [comment]
> @aliafshany You can also try updating to the latest nightly version at https://agrd.io/mac_nightly Does the problem still persist?

@alexx7311 
i'm always using the latest nightly version. just updated again.
i'll let you know the results.
so fdar so good, no issues

**Comment by alexx7311** [comment]
@aliafshany We'll close this issue for now, you can reopen it at any time if the problem recurs.
