### ISSUE TITLE
AdGuard Window Will Not Open

### ISSUE THREAD

**Issue by thomasholte** [AdguardTeam/AdguardForMac#1319]
### AdGuard version

2.12.1.1398 release

### Browser version

Safari 17.0 (19616.1.27.211.1)

### OS version

macOS Sonoma 14.0

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Hide menu bar icon in settings dialogue
2. Click on program icon
3. AdGuard program window will not open

### Expected Behavior

After clicking on the program icon, AdGuard should always open its program window, regardless of whether AdGuard's menu bar icon is hidden or not.

### Actual Behavior

After hiding AdGuard's menu bar icon clicking on AdGuard's program icon will not open AdGuard's program window.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by Aydinv13** [comment]
@thomasholte Hi there!

Could you please attach a short video of this problem? Have you encountered this issue before the latest version?

**Comment by thomasholte** [comment]
This version of AdGuard is the first version I installed.

Video showing error:
https://github.com/AdguardTeam/AdguardForMac/assets/15850560/5f663f6f-3403-46b1-a9a1-20f33295e1b6

**Comment by thomasholte** [comment]
I will close this issue as the error is caused by the menu bar manager "Bartender". After quitting "Bartender" clicking on AdGuard's program icon will show a window below the menu bar icon.

Video showing correct behavior:
https://github.com/AdguardTeam/AdguardForMac/assets/15850560/7935082b-cd8e-4ab2-aebc-0dc19124bc2d
