### ISSUE TITLE
Adguard Causes Microsoft Azure Portal to think logged-in user has wrong license type

### ISSUE THREAD

**Issue by GeordieGuy** [AdguardTeam/AdguardForMac#1322]
### AdGuard version

2.12.1398 release

### Browser version

Safari, Firefox and Chrome

### OS version

macOS Sonoma 14.0

### What filters do you have enabled?

AdGuard Base filter, AdGuard German filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Disable cache for third-party requests

### Issue Details

Steps to reproduce:
1. Enable AdGuard
2. Log in to portal.azure.com
3. Navigate to Microsoft Entra ID
4. Regardless of your actual license to use Azure, the License field in Overview will say Microsoft Entra ID Free
5. Disable AdGuard
6. Log out and back in to portal.azure.com
7. Navigate to Microsoft Entra ID to view the License field again, your license will show as what it actually is e.g. Microsoft Entra ID P2

### Expected Behavior

AdGuard should not make Azure think you are unlicensed

### Actual Behavior

AdGuard makes Azure think you are unlicensed

**Comment by AlexandrPkhm** [comment]
Hi @GeordieGuy 

We apologize for the delayed response. Could you please try disabling Stealth mode and see if the problem persists? Also, please try changing the DNS server or disabling DNS protection altogether. Please let us know the results.

**Comment by AlexandrPkhm** [comment]
@GeordieGuy 

Could you please let us know if there is any news on this issue?

**Comment by GeordieGuy** [comment]
Heya. Disabling Stealth mode clears the issue, but of course now I don't have Stealth mode.

**Comment by AlexandrPkhm** [comment]
@GeordieGuy 

If you would like to retain functionality of Stealth mode, we recommend adding `*.azure.com` to the list of _HTTPS Exclusions_. To do this, please open _AdGuard → Settings → Network → scroll down to HTTPS Filtering → press the Exclusions button → press + and enter the specified domain_. Unfortunately, Microsoft may use some other domains for the authorization process, so this may not be useful.

As an alternative, we recommend that you disable 'Self-destruct third-party cookies' and 'Disable cache for third-party requests' one by one to determine which of the settings is causing the problem in this particular case.

Please let us know of the results.

**Comment by AlexandrPkhm** [comment]
Hi @GeordieGuy 

Please let us know if you have any news on the issue.

**Comment by AlexandrPkhm** [comment]
Hi @GeordieGuy 

We will close this issue as there have been no recent responses. If you encounter this issue again, please reopen the issue and we will continue our investigation.
