### ISSUE TITLE
adguard for macOS doesn't filter Vmware Fusion VMs , windows gets ads through

### ISSUE THREAD

**Issue by avichou** [AdguardTeam/AdguardForMac#1329]
### AdGuard version

Version 2.12.2.1415 release

### Browser version

edge 118

### OS version

macOS sonoma 14

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard French filter, Filter unblocking search ads and self-promotion, EasyList, Others

### Issue Details

Steps to reproduce:
1.install vmware fusion 
2.create windows 11 VM 
3.go in adguard filtering settings and enable traffic filtering for Vmware fusion
4.open windows through vm and browse on chrome, edge 

ads get through and the network isnt filtered 

<img width="381" alt="image" src="https://github.com/AdguardTeam/AdguardForMac/assets/86660671/fdc5951b-93d5-4307-9b21-a508fde1471d">

<img width="848" alt="image" src="https://github.com/AdguardTeam/AdguardForMac/assets/86660671/0719ba9f-bedb-4657-b36b-a2a7e943a691">

### Expected Behavior

ads and trackers should ge blocked since they're filtered by adguard 

### Actual Behavior

no filtering at all 

### Screenshots

<img width="848" alt="image" src="https://github.com/AdguardTeam/AdguardForMac/assets/86660671/92810b2e-668d-41c3-b53c-2cb6f7105d4d">

<img width="381" alt="image" src="https://github.com/AdguardTeam/AdguardForMac/assets/86660671/1db12c3e-51d7-4b4f-baf3-b4a56e345425">

**Comment by Aydinv13** [comment]
@avichou Hi there!

Unfortunately, we can't guarantee that the filtering will work through the VM except for DNS filtering. For example, Parallels acts as a DNS proxy for virtual machines, so we filter all DNS traffic in this case. You might want to consider installing [desktop app](https://adguard.com/en/adguard-windows/overview.html) for your VM.

**Comment by avichou** [comment]
> @avichou Hi there!
> 
> Unfortunately, we can't guarantee that the filtering will work through the VM except for DNS filtering. For example, Parallels acts as a DNS proxy for virtual machines, so we filter all DNS traffic in this case. You might want to consider installing [desktop app](https://adguard.com/en/adguard-windows/overview.html) for your VM. 

Thank you, I'm installing Adguard on windows , I have a license for it 

I must ask, is there no ARM64 version of Adguard for windows ?

**Comment by Aydinv13** [comment]
@avichou AdGuard for Windows supports ARM (64) starting with [v7.11](https://github.com/AdguardTeam/AdguardForWindows/releases/tag/v7.11.0)
