### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by aliafshany** [AdguardTeam/AdguardForMac#1334]
### AdGuard version

Version 2.13.3.1512 nightly

### Browser version

Version 1.15.1 (43023)

### OS version

Sonoma 14.0

### Issue Details

Steps to reproduce:
It happened on its own, and I have no idea how to reproduce it.

### Actual Behavior

High CPU Usage caued my MBP M2 to turn on the fan

### Screenshots

https://github.com/AdguardTeam/AdguardForMac/assets/40741745/e1bff888-f254-4224-8fa6-d92d9d9494c9

### Additional Information

First of all, I noticed the fan spinning, and then I observed that there was high CPU usage related to AdGuard. I attempted to update the app to the latest nightly version. However, after downloading it, I didn't see any dialogues prompting me to enter the password, and the app didn't close either.

Therefore, as you can see in the video, I terminated it from the Activity Monitor, and then the "Install the Update" window appeared.
The logging mode was on Debug mode but after the Update it switched back to the default one.
i will send the logs right away.

**Comment by KolbasovAnton** [comment]
@aliafshany Thank You for the report! The problem will be fixed with next version DNSLibs, hopefully it will be updated with the next nightly version.
