### ISSUE TITLE
AdGuard incorrectly considers that LE certificate has expired and doesn't filter sites

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1352]
### AdGuard version

Version 2.12.2.1415 release

### Browser version

Chrome 120.0.6099.71 

### OS version

14.2 (23C64)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Russian filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### What Stealth Mode options do you have enabled?

Hide your search queries, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide Referrer from third-parties, Hide your User Agent, Remove X-client-Data header, Protect from DPI

### Support ticket ID

Sent debug logs to apple@adguard.com

### Issue Details

Steps to reproduce:
1. Go to https://id.embark.games/ or https://online-fix.me/games/rpg/16492-baldurs-gate-3-po-seti.html
2. Open AdGuard Browser Assistant popup in Chrome

### Expected Behavior

AdGuard correctly checks the validity of Let's Encrypt certificates and filters sites.

### Actual Behavior

AdGuard incorrectly considers that the Let's Encrypt certificates have expired and does not filter the sites

### Screenshots

<details><summary>Screenshots:</summary>

![CleanShot 2023-12-12 at 18 30 53](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/edb6ea28-d955-47c8-9198-f55e35c6c5cd)

![CleanShot 2023-12-12 at 18 31 27](https://github.com/AdguardTeam/AdguardForMac/assets/19418601/5e564028-18c1-46c0-bee4-628f541a65f5)

</details>

### Additional Information

Same problem in Safari

**Comment by rakleed** [comment]
https://github.com/AdguardTeam/AdguardFilters/issues/167485#issuecomment-1841075006

**Comment by jellizaveta** [comment]
Looks like this bug https://github.com/AdguardTeam/CoreLibs/issues/1833

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

It seems that this issue has already been fixed in the recently released AdGuard for Mac 2.13 beta and therefore will not be present in the 2.13 release. Could you please download the beta from the following link and let us know if the problem persists for you?

**Comment by rakleed** [comment]
@AlexandrPkhm yes, this problem is not reproduced in 2.13 beta.

**Comment by AlexandrPkhm** [comment]
@rakleed 

Thank you for your confirmation. We will close the issue as it can be considered fixed.
