### ISSUE TITLE
ERR_INTERNET_ DISCONNECTED randomly

### ISSUE THREAD

**Issue by omata** [AdguardTeam/AdguardForMac#1358]
### AdGuard version

2.12.2.1415

### Browser version

Brave v1.61.104 and Safari 17.2

### OS version

mcOS Sonoma 14.2

### What filters do you have enabled?

AdGuard Base filter, AdGuard Mobile Ads filter, AdGuard Spanish/Portuguese filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter, AdGuard DNS filter, Fanboy's Anti-Facebook List, NoCoin Filter List, Legitimate URL Shortener, Others

### What Stealth Mode options do you have enabled?

Hide your search queries, Send Do-Not-Track signals, Strip URLs of tracking parameters, Self-destruction of third-party cookies, Disable cache for third-party requests, Block the third-party Authorization header, Block Java, Hide Referrer from third-parties, Remove X-client-Data header, Protect from DPI

### Support ticket ID

No ticket ID.

### Issue Details

Steps to reproduce:
1. Start the computer
2. Open Web Browser
3. Enter a web site like https://www.lidl.es/ but it does it randomly with several of sites.
4. It shows the error then auto refresh and show the page correctly.

### Expected Behavior

Just open the webpage with out an initial error.

### Actual Behavior

Shows an initial error, then refresh automatically and show the page just fine.

### Screenshots

<details><summary>Screenshot 1:</summary>

![Xnip2023-12-16_01-40-15](https://github.com/AdguardTeam/AdguardForMac/assets/792294/af520507-51bc-4afe-8dfa-205f862fcb4b)

</details>

### Additional Information

It says that my internet is faulty, but I have a broadband internet service @ 10Gbps and not issues with it. When I close AdGuard this issue just disappear.

**Comment by AlexandrPkhm** [comment]
Hi @omata 

Unfortunately, we have not been able to reproduce this issue. Could you please try to check if it persists on our recently released AdGuard for Mac 2.13 beta, which is available via this [link](https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.13.0-beta-2)?
If the issue persists on the beta version, please record the application logs. Here's what you need to do:

1. Click **AdGuard icon** in the menu bar → Gear → Advanced  → Logging → Logging level → **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu → Advanced → Logging → **Export Logs and System Info…**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

You can also send us an export of your application settings. To do this, please click **AdGuard icon** in the menu bar → Gear → Advanced → **Export settings**. And attach the generated file to an email with logs.

**Comment by omata** [comment]
Hi @AlexandrPkhm 

I did what you requested, I installed the BETA version and it seems to fix the issue. I will keep using to do further tests, but initially looks like it solve the problem.

I have a question for you: When will be available the stable release? I don't want to use a BETA version.

Thank you and best regards.

**Comment by AlexandrPkhm** [comment]
@omata 

We are glad to hear that this issue has been resolved with this update. The stable release of AdGuard for Mac 2.13 is scheduled for the end of this week.

We will close this issue as it is effectively fixed. If you encounter similar behavior again, please reopen the issue and we'll continue our investigation.
