### ISSUE TITLE
http://affiliatelanding.superbahis8.com/ - dangerous requests counter issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#137]
User goes to affiliatelanding.superbahis8.com, Adguard shows the Access Denied page, but the Threats counter won't increase.

Works fine on my side.
Adguard 1.3.0, macOS 10.11.6

Logs: 461686

**Comment by Fridrix** [comment]
Send to us debug and state files)
https://github.com/AdguardTeam/AdguardForMac/issues/137

**Comment by ameshkov** [comment]
@Fridrix @evgeniy-ADG 

Just in case, do you see this behaviour with any other blocked websites? 
Test website: `wmconvirus.narod.ru`

**Comment by evgeniy-ADG** [comment]
Can't reproduce on both sites.

**Comment by Stillness-2** [comment]
I have already described, when this behavior occurs if there is a blocking rule, which for example blocks the root of the site - `wmconvirus.*.ru^`. In this case  Adguard increases counter - "ads blocked".

**Comment by Stillness-2** [comment]
I suppose it is no issue :)
