### ISSUE TITLE
Add Orion support for AdGuard Assistant

### ISSUE THREAD

**Issue by azdanov** [AdguardTeam/AdguardForMac#1370]
### Issue Details

Please consider adding support for [Orion](https://kagi.com/orion) WebKit based browser.
<img width="812" alt="Screenshot 2023-12-26 at 13 35 28" src="https://github.com/AdguardTeam/AdguardForMac/assets/6123841/1b2c9869-60d0-483e-aa3b-626b308e64db">

**Comment by KolbasovAnton** [comment]
@azdanov Hello! I doubt, that this browser will be fully supported in the near future, but it has a possibility to use some extensions from Firefox and Chrome stores - AdGuard is on the list.

Run browser, then click "Orion" in system tray -> Popular Extensions -> Ads & Tracking -> choose "Get" button on AdGuard AdBlocker bar. You will install fully functional browser extension.

**Comment by azdanov** [comment]
Hey, thanks for quick answer. I did try the extensions for Chrome and Firefox, but they seem to do nothing. I tested against https://adblock-tester.com.

Oh well..
