### ISSUE TITLE
Issues while playing YouTube's videos

### ISSUE THREAD

**Issue by nysqually** [AdguardTeam/AdguardForMac#1371]
### Issue Details

When playing most - if not all - Youtube's or Audio/Visual Social Media,
the player initially does not start, instead a yellow line briefly darts across the timeline,
next the screen goes blank for several seconds, and then an AD (audio only or sometimes video)
starts to play. THEN, I have discovered, that if 'I click to refresh' then, the screen refreshes and the media (I selected) play.. THIS, scenario (of the chosen media cutting out ... to be replaced by the yellow line darting across, a blank screen and the attempts of yet another AD) usually continues incrementally two or more times throughout the course of my attempting to enjoy AD Free service.

### Proposed solution

I'd like THIS (as described above) to STOP Happening, 
as it appears that AD Guard has an issue that has not yet been resolved, 
i.e.,bto free 'your paying customers' from the intrusion of ADs

I'm not AD Guard, I have no idea how you  are going to resolves this problem.

### Alternative solution

I'm not AD Guard, I have no idea how you  are going to resolves this problem.

**Comment by KolbasovAnton** [comment]
@nysqually Greetings! Please, specify your MacOS, AdGuard version and browser, where these problems appear.

Also, can You record a screencast/video of this bug's manifestation, for clarity?
