### ISSUE TITLE
AdGuard for Mac Advanced Setting/Low Level Setting To Disable Password Authorization 

### ISSUE THREAD

**Issue by SocietasEvanescentes** [AdguardTeam/AdguardForMac#1374]
### Issue Details

Previously, AdGuard for macOS could be updated and wouldn't ask for a password. AdGuard devs removed this citing that this is how malware can behave. 

As I have AdGuard installed on family devices, they freak out every time any app asks to update and asks for a password.

### Proposed solution

Add a low level setting (can only be accessed in a specific menu when someone specifically looks for it) to update the app without requiring a password upon each new version.

By default, this would be disabled and **would** require a password _unless_ a user has changed the low level setting.

### Alternative solution

n/a

**Comment by AlexandrPkhm** [comment]
@SocietasEvanescentes Hi!

The password authorization that occurs each time you update AdGuard on your devices is required by Apple's System Integrity Protection. Unfortunately, we cannot dictate whether the password authorization is displayed or not, as it is displayed by macOS when the installer needs additional permissions.
