### ISSUE TITLE
Adguard doesn't work if Web protection in Sophos antivirus is enabled

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#138]
Tested with Sophos 9.5.2
Adguard 1.3.0 beta
OS X 10.12

<details>

![image](https://cloud.githubusercontent.com/assets/15856304/19637778/6dd1fa2e-99d9-11e6-95e2-1be030e62d31.png)

![image](https://cloud.githubusercontent.com/assets/15856304/19637790/76afc41e-99d9-11e6-9b43-c98f0ff6298a.png)

</details>

and when you enabled it
<details>

![image](https://cloud.githubusercontent.com/assets/15856304/19637819/8d055f30-99d9-11e6-97ac-fffc139f472b.png)

![image](https://cloud.githubusercontent.com/assets/15856304/19637830/95c77054-99d9-11e6-8c30-d105259046db.png)

**Comment by ameshkov** [comment]
I suppose it depends on the startup order. It will be either Adguard or Sophos.

Try adding Sophos to the list of the filtered apps, does it change anything?

**Comment by evgeniy-ADG** [comment]
>Try adding Sophos to the list of the filtered apps

Nope, doesn't work.

<details>
![image](https://cloud.githubusercontent.com/assets/15856304/19646539/88a72abc-9a02-11e6-98f9-3c16371fab74.png)
</details>

>I suppose it depends on the startup order. It will be either Adguard or Sophos.

I can't find a way to unload Sophos, neither I can simply quit it.

**Comment by evgeniy-ADG** [comment]
Hi! Any updates?

**Comment by ameshkov** [comment]
Not yet, we'll return to this issue after v1.3.2 release.

**Comment by evgeniy-ADG** [comment]
Hi, we keep receiving similar questions and are not quite sure what to tell, do we have any timeframes or the only solution is to choose between adguard and sophos web shield?

**Comment by ameshkov** [comment]
@evgeniy-ADG frankly, I thought it was resolved already.

Anyways, temporary solution: uncheck "Use localhost for injections" in AG advanced settings.
Please report if it helps.

**Comment by ameshkov** [comment]
Ops, sorry, I thought it was about Windows verion

**Comment by planet0** [comment]
Any updates on if Adguard and Sophos Web Protection can work well together on macOS, @ameshkov?

**Comment by vozersky** [comment]
@zebrum test it please

**Comment by planet0** [comment]
Thanks — from my previous experience, Adguard would not filter browsers/apps sometimes, the Adguard Assistant would never load (no icon), or it would ‘reset’ with a ‘Welcome to Adguard Assistant!’ dialogue box often appearing (lose settings often).

I will mention that restarting macOS after Sophos or Adguard is installed makes a difference in seeing results, could be the way Sophos & Adguard loads on startup and which one can overlap the other.

Removing Sophos Home entirely helps, turning off Web Protection only can help, but I was still getting Adguard Assistant issues so I just uninstalled Sophos completely for the time being.

**Comment by zebrum** [comment]
@evgeniy-ADG @planet0 guys, is there any chance you have standalone Sophos 9.x installer? 
they don't let me download it. only new one cloud based v. 1.2.4 from official website.

**Comment by planet0** [comment]
@zebrum I found a way to download the classic older version of Sophos Anti-Virus for Mac Home Edition (9.x) via [this Sophos Community topic](https://community.sophos.com/products/free-antivirus-tools-for-desktops/f/sophos-anti-virus-for-mac-home-edition/80025/where-to-download-sophos-anti-virus-sav-home-edition-9-5-2-reffered-to-as-classic-now-that-there-also-is-a-cloud-edition/305296#305296) but they now prefer users to use Sophos Home.

I was personally referring to Sophos Home in my case, it seems that it occurs on both variants.

**Comment by zebrum** [comment]
Adguard 1.4.1 works as it should with Sophos 1.2.4 - no ads, assistant is on.
There is something with our test page I guess.

**Comment by planet0** [comment]
I'm still experiencing compatibility issues with Sophos Home 1.2.4 and Adguard 1.4.1.

I had Sophos Home installed first, everything was fine.
I then install Adguard 1.4.1, and both Sophos & Adguard function fine.
I then restarted macOS, and now Adguard assistant disappears from Safari entirely. Sophos Web Protection still works fine as per the [Sophos Malware test page](http://sophostest.com/malware/).

**Comment by planet0** [comment]
If I disable Web Protection from the Sophos Home dashboard for the Mac and wait for the Off indicator to appear nex to Web Protection in the Sophos Home app, the Adguard Assistant is back in Safari with no issue.

Upon further inspection, it seems that Web Protection in Sophos prevents Adguard from injecting the DIV code into pages, even though Safari extensions are still able to do so (eg. Grammarly).

Once again I'll mention this issue starts to occur once macOS has been restarted after Adguard is installed.

<img width="927" alt="screen shot 2017-07-27 at 10 12 31 am" src="https://user-images.githubusercontent.com/29296810/28648900-8787c642-72b4-11e7-95c7-0bb95c7b3729.png">

<img width="928" alt="screen shot 2017-07-27 at 10 11 55 am" src="https://user-images.githubusercontent.com/29296810/28648901-87b87454-72b4-11e7-9db3-f991c3ea301c.png">

**Comment by ameshkov** [comment]
@zebrum please re-test it

**Comment by zebrum** [comment]
@planet0 what is your OS X and Safari version?

Adguard 1.4.1, Sophos 1.2.4
since you've mentioned Sophos test page it seems that on my side Adguard interferes with Sophos app in opposite way - Adguard works perfectly well.

<details>

![screenshot 2017-07-31 14 18 40](https://user-images.githubusercontent.com/23637588/28775529-2e063442-75fb-11e7-808e-aa284fa62992.png)



</details>

but Sophos doesn't - current behavior [Sophos test page](http://sophostest.com/malware/) (Adguard is on):
<details>

![screenshot 2017-07-31 14 23 20](https://user-images.githubusercontent.com/23637588/28775670-ea0c1e2c-75fb-11e7-9c74-e3481bf66c4e.png)


</details>

expected behavior [Sophos test page](http://sophostest.com/malware/) (Adguard is on): 

<details>


![screenshot 2017-07-31 14 22 57](https://user-images.githubusercontent.com/23637588/28775691-fee6f9ac-75fb-11e7-88c2-146022766e84.png)


</details>

the problem is you can't just quit Sophos app on Mac.

**Comment by planet0** [comment]
@zebrum It is macOS Version 10.12.6 (16G29) and Safari Version 10.1.2 (12603.3.8)

This may not be true or possible -- but since you experienced opposite results, do you think only one of either Sophos or Adguard is able to successfully load fully in a random chance? (Eg. In my case Sophos overrode Adguard, and in your case Adguard overrode Sophos)

**Comment by ameshkov** [comment]
Guys, I suppose that it depends on the execution order. Who's the last register a kernel extension - wins:)

**Comment by zebrum** [comment]
@planet0 

as Andrey said who's the last register a kernel extension - wins, so in this case we kindly ask you to send the same report to Sophos developers. The same request to you @evgeniy-ADG 

We had similar incompatibility problems with other antivirus apps previously, so our developers found a solution, developers from other companies embeded some libraries to their code and all works well know. 

If Sophos will be receive more complaints about the issue, the chance that they will make some little changes in their product is increasing.

**Comment by zebrum** [comment]
closed for now until any update will shows up.

**Comment by evilvibes** [comment]
Just a little update to this I'm in the process of trying to get to sophos to have look at this issue.

https://community.sophos.com/products/sophos-home/f/sophos-home-for-mac/99608/sophos-and-adguard
