### ISSUE TITLE
Subtitle Issues for Hulu

### ISSUE THREAD

**Issue by ag202421** [AdguardTeam/AdguardForMac#1383]
### AdGuard version

2.13.0.1558

### Browser version

Chrome  121.0.6167.184

### OS version

macOS Sonoma 14.3.1

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard Social Media filter, Others

### Issue Details

Steps to reproduce:
1. Turn On AdGuard
2. Turn on Hulu subtitles
3. You can turn off adguard to see that the subtitles are in sync when Adguard is off
Adguard

### Expected Behavior

Synced subtitles

### Actual Behavior

Subtitles are not matching dialogue

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by AlexandrPkhm** [comment]
Hi @ag202421 

We have not been able to reproduce this issue. Could you please let us know if this is only happening with a specific Hulu show, or if this issue affects every show on the service? Also, please let us know if you are using any network related software in addition to AdGuard. 

To reproduce this issue, we might need the app logs and settings export. To get the app logs, please:

1. Click **AdGuard icon** in the menu bar → Gear → Advanced  → Logging → Logging level → **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu → Advanced → Logging → **Export Logs and System Info…**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

Also, please open AdGuard → Gear → Advanced → Export settings and send the exported file along with the logs.

**Comment by AlexandrPkhm** [comment]
@ag202421 

Could you please check and let us know if the problem still persists with the latest nightly release? This version can be downloaded via the following [link](https://agrd.io/mac_nightly).

**Comment by ag202421** [comment]
Hello,
I installed it but the issue is still there. There is still a delay between the audio and subtitles. Could it maybe be an issue with how Hulu subtitles work? I wish I could provide a video of the issue but sadly Hulu doesn’t allow that. 
Thanks,
Alexis Goldberg

**Comment by ag202421** [comment]
I disabled both DNS and HTTPS filtering. It worked after disabling HTTPS filtering but there were ads. Here is my filter log. 
￼

**Comment by AlexandrPkhm** [comment]
@ag202421 

Unfortunately, we are unable to view the filter log. Could you please resend this file to apple@adguard.com? Don't forget to include this issue number in the subject line.

**Comment by AlexandrPkhm** [comment]
@ag202421 

Thank you for the filtering log you provided. We were able to reproduce the problem, and it seems to be related to the way Hulu's subtitles work with any type of filtering. Their captions have hardcoded time intervals specifically for the ads, and we are unable to get around that.
