### ISSUE TITLE
AdGuard blocks access to iPhone Widgets settings on Desktop

### ISSUE THREAD

**Issue by PavelParkhomenko** [AdguardTeam/AdguardForMac#1389]
### AdGuard version

2.13.0.1558

### OS version

14.2.1 (Build 23C71)

### Support ticket ID

863663

### Issue Details

Steps to reproduce:
1. Download and install the [Weathergraph](https://apps.apple.com/app/id1501958576) widget for both iOS and macOS.
2. Open the Weathergraph widget on your Mac.
3. Within the widget settings, select the option "from iOS" 
4. Double-click the widget and choose "Edit Weathergraph"

### Expected Behavior

refer to Screenshot 1 (AdGuard disabled)

### Actual Behavior

refer to Screenshot 2 (AdGuard enabled)

### Screenshots

<details><summary>Screenshots:</summary>

<img width="482" alt="Quit AdGuard (1)" src="https://github.com/AdguardTeam/AdguardForMac/assets/104919935/7cf93e3e-87dc-40a9-aedc-02d7fae1c9cc">

<img width="499" alt="AdGuard On (2)" src="https://github.com/AdguardTeam/AdguardForMac/assets/104919935/a8a8f8a6-44a1-419f-a7e6-ba121f81248e">

<img width="524" alt="Edit (1)" src="https://github.com/AdguardTeam/AdguardForMac/assets/104919935/e0395ab5-6bdc-4219-908b-64f4c914e33c">

### Additional Information

AdGuard is blocking access to widget settings on macOS Sonoma, specifically affecting widgets from iPhones displayed on the desktop. This problem occurs consistently with the Readdle Calendars 5 and Weathergraph widgets (when using the iPhone version).

Despite attempting to resolve the issue by disabling various options such as HTTPS filtering, extensions, phishing and malware protection, advanced tracking protection, DNS protection, and all filters, the problem persists. Interestingly, there are no entries in the filtering log related to this issue, suggesting that whatever is blocked doesn't show up there. The widget settings only load when AdGuard is completely turned off.

**Comment by Arnoud-B** [comment]
It should not have the Resolution: Done, as the issue is still there in AdGuard 2.14.1.1603.

**Comment by Hessenpower01** [comment]
This is not fixed, still an issue in 2.15.1.1731 

see also: https://github.com/AdguardTeam/AdguardFilters/issues/186976#issuecomment-2321250472

**Comment by rakleed** [comment]
@sfionov @zzebrum @AlexandrPkhm @Aydinv13 please take a look

**Comment by sfionov** [comment]
@Arnoud-B @Hessenpower01 

Can you please try to enable `network.extension.monterey.force.split.tunnel` advanced setting?

This advanced option improves compatibility with connected devices, but can cause problems when iCloud Private Relay is on. If it works for you, it is recommended to disable iCloud Private Relay in iCloud settings.

**Comment by Hessenpower01** [comment]
> Can you please try to enable `network.extension.monterey.force.split.tunnel` advanced setting?

works for me, but have to think about what to do private relay

**Comment by Arnoud-B** [comment]
I did not have iCloud Private Relay turned on, but setting `network.extension.monterey.force.split.tunnel` to true, solved it for me as well 👍

**Comment by rakleed** [comment]
@sfionov can you make this option enabled by default? Before this, I thought that this was a problem with macOS or because of the developers of these apps.

**Comment by sfionov** [comment]
@rakleed No we can't since this will break internet for iCloud Private Relay users.

**Comment by rakleed** [comment]
@sfionov in the article https://adguard.com/kb/adguard-for-mac/solving-problems/icloud-private-relay/ you say that AdGuard disables iCloud Private Relay by default because they are incompatible, so I don't understand what you're talking about.
