### ISSUE TITLE
AdGuard breaks Earthlink SMTP on Mac

### ISSUE THREAD

**Issue by abromber** [AdguardTeam/AdguardForMac#1391]
### AdGuard version

10.8.0

### Browser version

Safari 17.3.1

### OS version

Sonoma 14.3.1

### What filters do you have enabled?

AdGuard Base filter

### What Stealth Mode options do you have enabled?

Send Do-Not-Track signals

### Issue Details

Steps to reproduce:
1. Launch AdGuard
2. Launch email client
3. Attemp to connect to smtp.earthlink.net server
4.  Connection will fail.

### Expected Behavior

Connection to smtp.earthlink.net should succeed. 

### Actual Behavior

Connection to smtp.earthlink.net fails.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

### Additional Information

This occurs with any Mac email client - none will connect.
This does not occur with other smtp servers. No problems connecting.
This does not occur with TailScale VPN. No problems connecting.

**Comment by AlexandrPkhm** [comment]
Hi @abromber 

Could you please let us know if you are using the `Protect Mail Activity` feature in the built-in macOS Mail client or any of the `Apple Private Relay` related features in other email clients?

**Comment by abromber** [comment]
"Protect Mail Activity”was on. Turning it off solved the problem. Thank 
you.

Allen Bromberger
***@***.***


------ Original Message ------
From "Alexandr" ***@***.***>
To "AdguardTeam/AdguardForMac" ***@***.***>
Cc "abromber" ***@***.***>; "Mention" 
***@***.***>
Date 3/4/24, 9:34:51 AM
Subject Re: [AdguardTeam/AdguardForMac] AdGuard breaks Earthlink SMTP on 
Mac (Issue #1391)

**Comment by AlexandrPkhm** [comment]
@abromber 

Thank you for letting us know! We are glad to hear that the issue was resolved.
