### ISSUE TITLE
iTunes Store shows blank screen after installing Adguard

### ISSUE THREAD

**Issue by legoninja** [AdguardTeam/AdguardForMac#140]
Hi,

After installing Adguad 1.3.0 on my MacBook Pro, I have been unable to access the iTunes store. If I click on Store, it just shows a blank screen. I have noticed that every time I click on the iTunes store, Adguard seems to be blocking some sort of a tracker since the count of trackers blocked gets incremented by one or two.

It is one of the strangest problems since it only started happening after I installed Adguard for Mac and disabling or quiting Adguard doesn't seem to solve the problem.

I am able to access the iTunes store on my other devices such as iPhone and iPad.

Can you please advise how this issue can be resolved?

Thanks,
Sam

<img width="1010" alt="blank1" src="https://cloud.githubusercontent.com/assets/20718473/19833083/7f3ba5d2-9e7d-11e6-8b55-4fead7f44d59.png">

**Comment by Alex-302** [comment]
Hi
Which filters are enabled? Try to temporary disable them and check again.

**Comment by legoninja** [comment]
> Hi
> Which filters are enabled? Try to temporary disable them and check again.

Hi,

I have the following filters enabled : User (which just disables adguard on some sites), Spyware filter, Easylist, EasyPrivacy, Fanboy's Social Blocking List.

I tried disabling all filters and that didn't help, also tried quitting adguard and also same issue, also quit adguard restarted my machine and it was still disabled and still the same issue - just a black itunes store page.

I have itunes 12.5.2.35 and MacOS Serria (10.12.1).

<img width="922" alt="filters" src="https://cloud.githubusercontent.com/assets/20718473/19833134/0f6c2982-9e7f-11e6-829d-3979a085a9c2.png">

**Comment by Alex-302** [comment]
I can't reproduce this, but I have only El Capitan.
@vozersky Could you please check it?

**Comment by Alex-302** [comment]
@gshumihin Could you please check it?

**Comment by gshumihin** [comment]
Cannot reproduce this too.

**Comment by ameshkov** [comment]
@Stillness-2 how's that possible? As I recall AG shouldn't filter iTunes traffic.

**Comment by Stillness-2** [comment]
@ameshkov It is possible. This is old problem. iTunes store works as integrated in system `com.apple.Webkit` process. The same for Safari and Mail. At this moment we can't separate those apps for filtering.

**Comment by ameshkov** [comment]
@legoninja we finally got what's happening.

There're two ways of fixing this issue:

1. Enable Adguard's `English filter`. In this case you'd better also disable EasyList as english filter already includes it.

2. Or add an exception for itunes: `@@||itunes.apple.com^$document`

**Comment by Stillness-2** [comment]
@legoninja 
To restore the iTunes Store (in iTunes), after the procedure, which is described @ameshkov , do the following steps:

- Quit iTunes
- Delete the folder `~/Library/Caches/com.apple.iTunes` (Run the command in Terminal.app `rm -R ~/Library/Caches/com.apple.iTunes`)
- Open iTunes

**Comment by legoninja** [comment]
> @legoninja 
> To restore the iTunes Store (in iTunes), after the procedure, which is described @ameshkov , do the following steps:
> 
> Quit iTunes
> Delete the folder ~/Library/Caches/com.apple.iTunes (Run the command in Terminal.app rm -R ~/Library/Caches/com.apple.iTunes)
> Open iTunes

Thanks @Stillness-2 and @ameshkov 

I tried the procedure you both described and now it is working. I think like you said there seems to be an issue with the EasyList filter (because even using <code>@@||itunes.apple.com^$document</code> with the EasyList filter didn't work; so I used the **English filter** instead.

Then I ran the command <code>rm -R ~/Library/Caches/com.apple.iTunes</code> and voila iTunes Store started working again. Thanks a lot everyone for your help.

<img width="1166" alt="itunes_store" src="https://cloud.githubusercontent.com/assets/20718473/19850301/b2efa326-9fa7-11e6-82a9-db3a56f5cdda.png">

**Comment by JML54** [comment]
Just had the same problem with Mojave and AdGuard.  Fix noted above worked!
