### ISSUE TITLE
Safari Cannot Load Webpages when AdGuard and Screen Time are Enabled

### ISSUE THREAD

**Issue by deanocko** [AdguardTeam/AdguardForMac#1401]
### AdGuard version

2.13.0.1558 release

### Browser version

Version 17.4.1 (19618.1.15.11.14

### OS version

14.4.1 (23E224)

### Support ticket ID

https://adguard.zendesk.com/tickets/871938

### Issue Details

Steps to reproduce:
1. Turn on Adguard Protection
2. Make sure the "Automatically filter applications" setting is enabled. (If disabled all adblocking in Safari will not work)
3. Enable any native MacOS screen time setting
4. No pages in safari will load, other browsers are not affected

### Expected Behavior

Websites should load normally.

### Actual Behavior

Websites on Safari will not load as if you are not connected to the internet. Other browsers are not affected.

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by deanocko** [comment]
I've tried resetting everything and changing all settings. I've also tried re-installs. This is a bug in AdGuard. Only remedied by disabling Screen Time and restarting computer or disabling AdGuard or the "Automatically Filter Applications" setting.

**Comment by Aydinv13** [comment]
@deanocko Unfortunately you need to disable Content&Privacy in Screen Time and reboot your system for AdGuard to work properly https://github.com/AdguardTeam/CoreLibs/issues/1790#issuecomment-1752447526

**Comment by deanocko** [comment]
This is not closed nor complete having to disable a native feature of MacOS to use AdGuard is not acceptable.
