### ISSUE TITLE
Improve user rules editor

### ISSUE THREAD

**Issue by jellizaveta** [AdguardTeam/AdguardForMac#1402]
### Issue Details

1. Add the ability to start writing a rule inline.
2. Avoid deleting text when cmd+z is pressed while editing a rule in grid mode. How to repeat:
- click on the plus sign, add rule
- press cmd+z without leaving the rule editor 

https://github.com/AdguardTeam/AdguardForMac/assets/91964807/3262a1e3-9d2b-4d95-a65a-6761462df0f5

3. Add cmd+z support in the rules editor as it is done in other products (e.g. extension, windows)

https://github.com/AdguardTeam/AdguardForMac/assets/91964807/045773b7-9c17-4921-ae7d-cfd7f232b05e

### Proposed solution

Do not erase rules when pressing cmd+z

**Comment by Stillness-2** [comment]
@jellizaveta

**Comment by Alex-302** [comment]
@Stillness-2 Why not by double-click on empty line like in Windows?
![image](https://github.com/AdguardTeam/AdguardForMac/assets/8361299/5ae19d20-93c1-4cdd-9c23-605bd0b23ae3)
