### ISSUE TITLE
High CPU usage 

### ISSUE THREAD

**Issue by nikkikom** [AdguardTeam/AdguardForMac#1407]
### AdGuard version

2.13.0.1558

### OS version

14.4.1

### Issue Details

I updated and started new version of AdGuard

### Actual Behavior

AdGuard worked few days, then I noticed that it consumes 100% of one CPU core without any noticeable network traffic. 
Attaching two screenshots with CPU and open files information and with call stacks from profiler.

### Screenshots

<details>
<summary>CPU usage and opened files:</summary>
<img width="1083" alt="Screenshot 2024-04-17 at 20 28 14" src="https://github.com/AdguardTeam/AdguardForMac/assets/3433005/0e1db82f-631c-4d9e-a885-f45e386291f8">
</details>

<details>
<summary>Profiler:</summary>
<img width="1607" alt="Screenshot 2024-04-17 at 20 27 09" src="https://github.com/AdguardTeam/AdguardForMac/assets/3433005/01feff9f-9de1-4ab3-a67e-64e172526ce6">
</details>

**Comment by Aydinv13** [comment]
@nikkikom Hi!
Could you update to the new release version and check if it still persists?

**Comment by nikkikom** [comment]
> @nikkikom Hi! Could you update to the new release version and check if it still persists?

The issue is intermittent. Hard to reproduce. Only saw it twice.
To the record I am using a number of vpns: Cisco secure client, wireguard, outline. I also use Little snitch.

**Comment by eshack94** [comment]
I am experiencing the same thing. Even after the latest upgrade, I am still seeing this. It started a couple releases ago. It's most noticeable while on YouTube.

This is AdGuard Pro on Mac, specifically it's the `com.adguard.mac.adguard.network-extension` network extension that has been intermittently causing very high CPU usage.

I think this should be higher priority.

**Comment by rebreatherccr** [comment]
High CPU 110% Usage is a real problem for me too happens all day long.
Restart Adguard doesn't help.  Reboot Mac doesn't help.
High fan noise is another indicator.
Can only remember this starting in the last few days perhaps.
MacBook Pro 2014
MacOS Montery 12.7.4
Adguard Latest Version 2.14.0.1592 release

**Comment by hsbugss** [comment]
![image](https://github.com/AdguardTeam/AdguardForMac/assets/157443721/a983e6ac-9a75-4ba6-bffb-9043a64ce87c)

The problem arises indirectly and irregularly

**Comment by eshack94** [comment]
@Aydinv13 Is this something you all are looking into? Can we raise the priority on this? The problem has been consistently recurring and has caused me to need to disable AdGuard entirely. It seems to occur several times a day and happens with some irregularity, but when it happens, CPU rises to 150-200+%. It causes battery to drain quickly.

The issue started maybe 1 or 2 releases ago. I did not notice the issue before then.

Let me know if there's additional info that might be useful for debugging.

**Comment by Aydinv13** [comment]
To troubleshoot this issue, we need to get the logs.
Here's what we need you to do:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

In addition, we need you to get the sample of `com.adguard.mac.adguard.network-extension` process when it reaches high levels. 

<details><summary>Example</summary>

<img width="945" alt="sample_example" src="https://github.com/AdguardTeam/AdguardForMac/assets/73467237/946eaacd-7aaa-4969-9cde-c2648eba0ac2">
</details>

**Comment by Aydinv13** [comment]
Some improvements have been made in CPU consumption, try the new [Nightly](https://agrd.io/mac_nightly) please.

**Comment by jtaylor-software** [comment]
So far the linked Nightly seems to have solved it on my M1 Ultra Mac Studio running 14.4.1. Normally I would see high CPU percentage minutes after launching and that didn't happen this time.

**Comment by rebreatherccr** [comment]
Working so far so good 2.14.0.1599 nightly,  no more high cpu.  Will send debug log from previous problem to support anyway.
Thanks.

**Comment by Aydinv13** [comment]
@eshack94 @nikkikom any news from your end? If it persists please collect data as described [here](https://github.com/AdguardTeam/AdguardForMac/issues/1407#issuecomment-2090114801)

**Comment by eshack94** [comment]
> @eshack94 @nikkikom any news from your end? If it persists please collect data as described [here](https://github.com/AdguardTeam/AdguardForMac/issues/1407#issuecomment-2090114801)

Sorry for the delay, I just saw this message. I will install the new Nightly build now and I'll let you know in a day or so whether the issue persists.

**Comment by nikkikom** [comment]
> @eshack94 @nikkikom any news from your end? If it persists please collect data as described [here](https://github.com/AdguardTeam/AdguardForMac/issues/1407#issuecomment-2090114801)

No, did not see it again. 
I am on 2.14.0.1592 now.

**Comment by eshack94** [comment]
@Aydinv13 The latest "Nightly" build seems to have fixed the issue for me. I haven't seen the problem happen again. Thank you!
