### ISSUE TITLE
rootElement.removeChild(currentScript)  rootElement is null 

### ISSUE THREAD

**Issue by captain-xu** [AdguardTeam/AdguardForMac#1411]
### AdGuard version

2.14.0.1588 release

### OS version

macOS 14.3 (23D56)

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

page crash

### Screenshots

<details><summary>Screenshot 1:</summary>

</details>

**Comment by captain-xu** [comment]
![image](https://github.com/AdguardTeam/AdguardForMac/assets/20409806/9b12ffa3-5b2f-4bbf-8e0d-61ef1323ad86)

**Comment by captain-xu** [comment]
![image](https://github.com/AdguardTeam/AdguardForMac/assets/20409806/14980f5c-d760-44fb-99c9-7627364fd539)

**Comment by captain-xu** [comment]
@Aydinv13 where is the code location，I can contribute a PR

**Comment by PavelParkhomenko** [comment]
Hello! Could you kindly provide a more detailed description of the issue and include steps to reproduce it? Specifically, what is not working or behaving differently than expected?

**Comment by captain-xu** [comment]
@PavelParkhomenko hello，when I render a child app in micro-frontend app with html entry，adguard will insert javascript to my html file like this
![image](https://github.com/AdguardTeam/AdguardForMac/assets/20409806/1d9e73ed-780a-43f6-9671-4acbc57983f9)
and then this inserted js run with this error
![image](https://github.com/AdguardTeam/AdguardForMac/assets/20409806/a2a4a89c-3b8c-4274-9418-52b6c5a6df95)
this will cause my page crash

> Hello! Could you kindly provide a more detailed description of the issue and include steps to reproduce it? Specifically, what is not working or behaving differently than expected?

**Comment by captain-xu** [comment]
@PavelParkhomenko Is it necessary to judge whether the rootElement is null before rootElement.removeChild?

**Comment by PavelParkhomenko** [comment]
Thank you for clarifying! We've already addressed the issue and a fix will be included in the upcoming CoreLibs 1.15 update, which will be released shortly.
