### ISSUE TITLE
Login item "Adguard Software Limited" not capitalised correctly

### ISSUE THREAD

**Issue by jslawler-gh** [AdguardTeam/AdguardForMac#1413]
### AdGuard version

2.14.0.1591 nightly (CL-1.14.53, DNS-2.5.19)

### Browser version

Version 17.5 (19618.2.10.11.4)

### OS version

14.5 Beta (23F5064f)

### What filters do you have enabled?

AdGuard Base filter, AdGuard Tracking Protection filter, AdGuard URL Tracking filter, AdGuard Social Media filter, AdGuard Annoyances filter

### Issue Details

Steps to reproduce:
1. Install AdGuard for Mac

### Expected Behavior

Login item "AdGuard Software Limited" added.

### Actual Behavior

Login item "Adguard Software Limited" added.

### Screenshots

<details><summary>Screenshot 1:</summary>

<img width="471" alt="Screenshot 2024-04-24 at 7 32 19 PM" src="https://github.com/AdguardTeam/AdguardForMac/assets/149243371/b58d8013-cb78-4357-a777-f9ea856ebbdd">

</details>

**Comment by PavelParkhomenko** [comment]
Issue closed. In future please follow the status of the request here https://github.com/AdguardTeam/AdguardForMac/issues/1414
