### ISSUE TITLE
Can loading https://www.ettoday.net/ in Safari with Cellular network

### ISSUE THREAD

**Issue by ryanwuson** [AdguardTeam/AdguardForMac#1420]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.14.0.1592

### Browser version

Safari 17.4.1

### OS version

macOS Sonoma 14.4.1

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard Chinese filter, AdGuard French filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.connect to wifi
2.open https://www.ettoday.net/ in safari and enable adguard for mac.
3.web loading correct.
4. disconnect to wifi and connect to hotspot from iPhone.
5. web can not loading

### Actual Behavior

web can not loading.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by AlexandrPkhm** [comment]
@ryanwuson Hi,

Unfortunately, we have not been able to reproduce the problem on our end. In this case, we need to get the app logs to diagnose and troubleshoot this issue.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar → Gear → Advanced  → Logging → Logging level → **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu → Advanced → Logging → **Export Logs and System Info…**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by AlexandrPkhm** [comment]
@ryanwuson 

Could you please let us know if there are any news on the issue?
