### ISSUE TITLE
Installer bug on 2.14.1(1601)b

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdguardForMac#1424]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.14.1(1601)b

### Browser version

Safari 17.4.1 (19618.1.15.11.14)

### OS version

macOS Sonoma.4.1（23E224）

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Installer cannot detect the termination of AdGuard and Safari, and the dialog asking for permission to terminate these will be displayed forever.

### Actual Behavior

Installer properly detects the termination of AdGuard and Safari.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@Chamiu Hi there,

could you share a screenshot of the dialog box when it occurs?

**Comment by Aydinv13** [comment]
A video would also be helpful.

**Comment by Chamiu** [comment]
It is not reproduced in ver.2.14.1 (1603) on macOS Sonoma.5 (23F79).

**Comment by Aydinv13** [comment]
@Chamiu I'm closing the issue then. Feel free to reopen if the problem occurs again.
