### ISSUE TITLE
block an element - doesn‘t work for reddit.com

### ISSUE THREAD

**Issue by 1bulf** [AdguardTeam/AdguardForMac#1427]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

1.11.18 (build 332, CT 2.0.44)

### Browser version

Safari 17.5 (19618.2.12.11.6)

### OS version

macOS 14.5 (23F79)

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter

### Language-specific

EasyList Czech and Slovak

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. open https://www.reddit.com
2. click on the adguard icon in safari toolbar
3. click on block an element

### Expected Behavior

i would expect the standard window to show up in the right corner as it always does when i want to block an element

### Actual Behavior

nothing happens. not even the standard window in the right corner doesn‘t show.
when i click on the choose button in block an element, it darkens upon clicking, but nothing happens.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

i have only experienced this on reddit webpage. it works properly on all other websites.

**Comment by KolbasovAnton** [comment]
https://github.com/AdguardTeam/AdguardAssistant/issues/419
