### ISSUE TITLE
Extensions Function does not work at all.

### ISSUE THREAD

**Issue by woofingcough** [AdguardTeam/AdguardForMac#1431]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.14.1.1603

### Browser version

Firefox 126.0.1

### OS version

macOS Sonoma 14.5

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Legitimate URL Shortener, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist

### Other

Fanboy's Anti-thirdparty Fonts

### Language-specific

List-KR, YousList

### Which DNS server do you use?

Custom DNS

### DNS protocol

DNS-over-HTTPS

### Custom DNS

I use NextDNS, but since this link is connected to my account, I am afraid I can't post it here.

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send Do-Not-Track signals, Block the third-party Authorization header, Block Push API, Block Location API, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Install Return Youtube Comment Username here: https://greasyfork.org/ja/scripts/460361-return-youtube-comment-username
2. Go to any Youtube video that has some comments
3. The script does not work

### Expected Behavior

The script working

### Actual Behavior

Not working at all. This applies to other userscripts as well. None of them works.

### Screenshots

<details><summary>Screenshot 1</summary>

![20240607000206](https://github.com/AdguardTeam/AdguardForMac/assets/68966952/05b9af6d-67b9-4b5c-9083-dec289dd9551)

</details>

### Additional Information

I am not sure if this problem is specific to me, but it hasn't been working for quite some time. I'd appreciate any help.

**Comment by woofingcough** [comment]
Oh, and I forgot to mention DPI protection does not work as well. There must be something going on in this neighbourhood.

**Comment by KelixAU** [comment]
can confirm Andti DPI isnt working for me either.

**Comment by AlexandrPkhm** [comment]
Hi @woofingcough 

Unfortunately, we were unable to reproduce the issue you have encountered. Could you please try to install the latest Nightly version of AdGuard for Mac and check if the issue persists there? This version can be downloaded via the following [link](https://agrd.io/mac_nightly).

If the issue still persists, we would need to get the app logs to troubleshoot it. Here's what we need you to do in this case:

1. Click **AdGuard icon** in the menu bar → Gear → Advanced  → Logging → Logging level → **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu → Advanced → Logging → **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by AlexandrPkhm** [comment]
@woofingcough 

Could you please let us know if there is any news on this issue? 

Regarding the Anti-DPI feature, unfortunately we do not guarantee 100% success in its operation. How exactly did you test Anti-DPI to make sure it didn't work?
