### ISSUE TITLE
Incorrect `Network Extension` permission path in macOS Sequoia

### ISSUE THREAD

**Issue by Lukaszpl666** [AdguardTeam/AdguardForMac#1434]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 2.14.1.1603 beta

### OS version

Mac OS Sequoia 15.0 beta

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. install adguard 
2. first run and setup works ok
3. when you try to turn on adguard filtering it shows a screen to allow Adguard system extension in macOS setting menu
4. with new MacOS the "allow" part in system privacy submenu is not showing up so the extension can't be probably installed
5. I tried to enable all apps with "sudo spctl --master-disable" and set in allow apps from anywhere but it still is not helping
6. It is probably a new way macOS is handling things
7. For now can't make Adguard run properly

### Expected Behavior

it should push macOS setting menu to allow Adguard install extension

### Actual Behavior

no way to "allow" installing extension

### Screenshots

<details><summary>Screenshot 1</summary>
<img width="861" alt="Screenshot 2024-06-11 at 19 54 01" src="https://github.com/AdguardTeam/AdguardForMac/assets/89794994/fb46ca44-e3db-487d-81f7-5a4b258f2067">
<img width="529" alt="Screenshot 2024-06-11 at 19 54 10" src="https://github.com/AdguardTeam/AdguardForMac/assets/89794994/38e866ee-58e5-4a26-b314-b78e552779bb">

</details>

**Comment by aschiletus** [comment]
I have the same problem and it seems that everyone who installs the beta will have this problem. I would expect a quick update.

**Comment by Lukaszpl666** [comment]
there is a problem (new way of handling extension) with new macOS. You can probably make it work when just upgrading your macOS with Adguard already being installed (with the extension) but if you try to install the extension on a fresh instance of a macOS it will not let you install the extension (there is no reaction from the macOS system and no way to allow the installation)
automatic proxy works without any problems so the app is fully functional just the extension is the problem 
ps. looking at macrumors forums, all apps using extensions (little snitch etc.)  have similar problem with newest macOS.

**Comment by Aydinv13** [comment]
@Lukaszpl666 @aschiletus Hi there,

due to the peculiarities of the new operating system you need to scroll to the end of the _Login items&Extensions_ page and click on "i" icon next to AdGuard after that turn the switch on.

<details><summary>Screenshot</summary>


![](https://uploads.adguard.org/mariehn99s.png)
</details>

**Comment by aschiletus** [comment]
> @Lukaszpl666 @aschiletus Hi there,
> 
> due to the peculiarities of the new operating system you need to scroll to the end of the _Login items&Extensions_ page and click on "i" icon next to AdGuard after that turn the switch on.
> 
> Screenshot

Yeah, that worked. Thank you.

**Comment by Lukaszpl666** [comment]
Amazing find!
ofc it works like a charm now
big thanks!

**Comment by zzebrum** [comment]
I'd rather leave it open for other people to notice until we fix it

**Comment by davitlee88** [comment]
@Aydinv13 thanks a lot for your finding

**Comment by xJustxMegx** [comment]
Hi, is there any news regarding this? It's pretty annoying my personal DNS doesn't work with the MacOS beta.

**Comment by IrishMan19** [comment]
Thank you for, it worked for me

**Comment by giovanninibarbosa** [comment]
> ew operating system you need to scroll to the end of the _Login items&Extensions_ page and click on "i" icon next to AdGuard after that turn the switch on.



> > @Lukaszpl666 @aschiletus Hi there,
> > due to the peculiarities of the new operating system you need to scroll to the end of the _Login items&Extensions_ page and click on "i" icon next to AdGuard after that turn the switch on.
> > Screenshot
> 
> Yeah, that worked. Thank you.

Tks a lot!! 🚀

**Comment by giovanninibarbosa** [comment]
> > @Lukaszpl666 @aschiletus Hi there,
> > due to the peculiarities of the new operating system you need to scroll to the end of the _Login items&Extensions_ page and click on "i" icon next to AdGuard after that turn the switch on.
> > Screenshot
> 
> Yeah, that worked. Thank you.

Tks a lot @aschiletus 🚀
