### ISSUE TITLE
"AdGuard is not installed or configured incorrectly" vivaldi adguard assistant extension message even though adguard is running and on

### ISSUE THREAD

**Issue by comfortablemilk4454** [AdguardTeam/AdguardForMac#1439]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.14.1.1603 release CoreLibs version 1.14.57 DNSLibs version 2.5.25

### Browser version

vivaldi 6.8.3381.44 (Stable channel) (arm64) 

### OS version

macOS 14.5 (23F79)

### Ad Blocking

AdGuard Base filter

### Annoyances

AdGuard Cookie Notices filter, Adblock Warning Removal List, EasyList Cookie List

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. add [AdGuard Browser Assistant extension](https://chromewebstore.google.com/detail/adguard-browser-assistant/fbohpolgemkbfphodcfgnpjcmedcjhpn) to vivaldi
2. click on its icon
3.see "AdGuard is not installed or configured incorrectly" message

### Expected Behavior

looks like this
<img width="345" alt="image" src="https://github.com/AdguardTeam/AdguardForMac/assets/43555540/c4728da0-6482-4ded-a45d-cbd1c99a7b6f">

### Actual Behavior

looks like this
<img width="338" alt="image" src="https://github.com/AdguardTeam/AdguardForMac/assets/43555540/78207579-6c21-45f7-b806-2597c0bc4244">

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@ComfortableMilk4454 Hi,

there is already such an issue, please take a look https://github.com/AdguardTeam/AdguardForMac/issues/1152. 
Closed this one as a duplicate.
