### ISSUE TITLE
Allowlist for AdGuard DNS Does Not Work

### ISSUE THREAD

**Issue by sanssecours** [AdguardTeam/AdguardForMac#1441]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.14.1

### Browser version

Safari 17.5, Orion 0.99.127.3

### OS version

macOS 14.5

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, Adblock Warning Removal List, Fanboy's Annoyances

### Security

Online Malicious URL Blocklist

### Language-specific

AdGuard Dutch filter, AdGuard German filter, AdGuard Japanese filter, AdGuard Russian filter, AdGuard Spanish/Portuguese filter, Dandelion Sprout's Nordic Filters, EasyList Germany, EasyList Italy, Liste AR, Official Polish filters for AdBlock, uBlock Origin & AdGuard

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNSCrypt

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send Do-Not-Track signals, Block Push API, Block Java, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1. Open the settings window of AdGuard (<kbd>⌘</kbd> + <kbd>;</kbd>)
2. Click on “DNS”
3. Enable “DNS Protection”
4. Click on “AdGuard DNS”
5. Click on “Allowlist”
6. Click on “+”
7. Add the domain `adtraction.com`
8. Close the settings window (<kbd>⌘</kbd> + <kbd>W</kbd>)
9. Open a browser e.g. Safari
10. Visit the page `https://track.adtraction.com/t/t?a=1578845458&as=1636858786&t=2&tk=1&url=https://www.gog.com:80/game/death_trash`

### Expected Behavior

The web browser open the URL and redirects to the page `https://www.gog.com:80/game/death_trash`

### Actual Behavior

The browser shows the error message “You are Not Connected to the Internet”

### Screenshots

<details><summary>You are Not Connected to the Internet</summary>

<img width="785" alt="No Internet Connection" src="https://github.com/AdguardTeam/AdguardForMac/assets/691989/616c7f46-81cc-4904-89f1-1e5c08924667">
</details>

### Additional Information

After I restart the computer the message changes to “This connection is not private”:

<img width="1015" alt="Connection Not Private" src="https://github.com/AdguardTeam/AdguardForMac/assets/691989/bce339c0-3cb0-4ac6-91d1-6a4937645193">

or “Access Blocked by AdGuard DNS”:

<img width="1296" alt="Access Blocked" src="https://github.com/AdguardTeam/AdguardForMac/assets/691989/2f9d7784-1464-4cc5-8fbe-1fc8c3b15a3b">

[Issue AdguardTeam/CoreLibs#1909](https://github.com/AdguardTeam/CoreLibs/issues/1909) seems to be about a similar bug.

**Comment by KolbasovAnton** [comment]
@sanssecours Greetings! Extensions in Allowlist applying only to local rules, so, to allow this domain You'll have to perform actions as described on the final screen in "How to unblock this website?" section.

![image](https://github.com/user-attachments/assets/9cb77495-a0d2-447e-bdae-81c17466232b)

**Comment by sfionov** [comment]
@sanssecours Alternatively, you can use "AdGuard DNS Non-filtering" in AdGuard app. In this case, DNS filter rules are applied only by AdGuard app.
