### ISSUE TITLE
Can't remove Network Extension

### ISSUE THREAD

**Issue by Tonton6217** [AdguardTeam/AdguardForMac#1448]
### Issue Details
Hello,
I have to sell my computer and there is a file that cannot be deleted.
Can you tell me if it is possible to delete it and how?
Thank you for your answer.
Best regards.
Copy of the file:
<details><summary>Original text</summary>
Bonjour, 
Je dois vendre mon ordinateur et constate qu'il reste un fichier qu'il est impossible de supprimer.
 Pouvez-vous me dire s'il est possible de le supprimer et comment faire ? 
Merci pour votre réponse. 
Cordialement. 
Copie du fichier:
</details>
 <img width="520" alt="Capture d'écran" src="https://github.com/user-attachments/assets/6cd3a015-1063-440e-a998-a6e265c18a56">

**Comment by Aydinv13** [comment]
@Tonton6217 Hello!

If you want to remove the app completely follow the instruction:
1) Close the app using the AdGuard icon - Gear - Quit AdGuard. 
2) Go to Applications folder and remove AdGuard from the list.
3) Perform this command in Terminal: `rm $HOME/Library/Preferences/com.adguard.mac.adguard.plist`
4) Quit all "cfprefsd" processes from Activity Monitor

Let us know if you have any other questions.

**Comment by Tonton6217** [comment]
Bonjour,Merci pour votre message.Problème résolu.Cordialement.envoyé : 17 juillet 2024 à 12:25de : Aydin Baydarov ***@***.***>à : AdguardTeam/AdguardForMac ***@***.***>cc : Tonton6217 ***@***.***>, Mention ***@***.***>objet : Re: [AdguardTeam/AdguardForMac] Can't remove Network Extension (Issue ***@***.*** Hello!If you want to remove the app completely follow the instruction:Close the app using the AdGuard icon - Gear - Quit AdGuard.Go to Applications folder and remove AdGuard from the list.Perform this command in Terminal: rm $HOME/Library/Preferences/com.adguard.mac.adguard.plistQuit all "cfprefsd" processes from Activity MonitorLet us know if you have any other questions.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
