### ISSUE TITLE
Add userstyles support

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#1451]
Add native support for installing Userstyles

**Comment by Caliintz** [comment]
So this was added. Sadly I’m getting: ANUserscriptParserErrorDomain error 1, whenever I try to install one. Either by the URL or by copying the CSS. 
![CleanShot 2024-12-18 at 00 04 47@2x](https://github.com/user-attachments/assets/dc82928f-310e-452e-b60c-9f1421dbcada)

**Comment by kikker902** [comment]
I have the same problem. Even with the most simple styles.
