### ISSUE TITLE
Question about macOS descriptor file DNS compatibility with AdGuard DNS, AdGuard Software and AdGuard VPN

### ISSUE THREAD

**Issue by linuxtechnology** [AdguardTeam/AdguardForMac#1455]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.14.1.1603

### OS version

14.5（23F79）

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### Issue Details

Dear AdGuard Support Team,

Hello!

I have encountered some issues while using AdGuard DNS, AdGuard software, and AdGuard VPN, and I hope to get your assistance.

Here is my current configuration:

- I have enabled AdGuard DNS and set it up using a configuration profile on macOS.
- I am also connected to AdGuard VPN.
- I have not manually set the DNS server in the AdGuard ad blocker.

### Actual Behavior

The problem I am facing is that when I enable AdGuard DNS (using the configuration profile) and connect to AdGuard VPN while the AdGuard ad blocker is on, the private DNS server gets switched to a public DNS server. This causes the private DNS configuration to fail, resulting in the use of public DNS servers.

This issue presents an inconvenience for users who wish to maintain their private DNS server configuration while using the VPN. I hope the AdGuard team can investigate this issue and provide a solution to ensure that AdGuard DNS, AdGuard software, and AdGuard VPN can work seamlessly together.

Thank you very much for your attention and assistance with this matter. If more detailed information is needed, please feel free to contact me.

Best regards,

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by AlexandrPkhm** [comment]
Hi @linuxtechnology 

AdGuard VPN applications overrides your system DNS server. To avoid using public AdGuard DNS servers, we recommend that you set up your private AdGuard DNS server in your AdGuard applications along with the configuration profile you have already installed. 

Could you please let us know which DNS server is selected in `AdGuard VPN → Settings → App settings → DNS servers` and in `AdGuard → Settings → DNS → Providers`?

**Comment by AlexandrPkhm** [comment]
@linuxtechnology Any news on this issue?
