### ISSUE TITLE
Feature Request: Lite AdGuard for Mac App Store Application with Native DNS Support for iCloud Private Relay Compatibility

### ISSUE THREAD

**Issue by bigplayer-ai** [AdguardTeam/AdguardForMac#1458]
## Feature Request: Lite AdGuard for Mac with Native DNS Support for iCloud Private Relay Compatibility

**Description:**

Currently, AdGuard for Safari lacks native DNS support, and AdGuard for macOS is incompatible with iCloud Private Relay. This limitation prevents users like myself from utilizing both AdGuard for macOS and iCloud Private Relay simultaneously.

**Proposed Solution:**

Develop a "Lite" version of AdGuard for Mac on app store that specifically incorporates native DNS support with safari ad blocking similar to iOS counterpart. This would ensure compatibility with iCloud Private Relay and provide users with a streamlined ad-blocking experience while maintaining privacy.

**Reasoning:**

A Lite version with native DNS support mirrors the functionality of AdGuard for iOS, which successfully integrates with iCloud Private Relay. This approach offers a user-friendly solution without compromising on core features.

**Alternatives:**

Downloading and installing custom DNS profile with Adguard For Safari Extension, this is not ideal because changing dns settings gets very complicated when wanting to exclude network or include network, I prefer native implementation of Adguard DNS inside an application...

**Additional Context:**

This feature request aims to address the growing need for privacy-focused ad-blocking solutions that seamlessly integrate with existing Apple features like iCloud Private Relay.

**Comment by AlexandrPkhm** [comment]
Hi @bigplayer-ai 

Currently, we are already in the process of adapting the standalone AdGuard app to Mac App Store specifications. However, at this time we are unable to specify the timeframe for it's release.

The app in its current configuration should be compatible with iCloud Private Relay, but to allow the compatibility you need to enable HTTP/3 filtering in Advanced settings. We would also like to assure you are continuously working on iCloud Private Relay compatibility.

**Comment by bigplayer-ai** [comment]
> Hi @bigplayer-ai
> 
> Currently, we are already in the process of adapting the standalone AdGuard app to Mac App Store specifications. However, at this time we are unable to specify the timeframe for it's release.
> 
> The app in its current configuration should be compatible with iCloud Private Relay, but to allow the compatibility you need to enable HTTP/3 filtering in Advanced settings. We would also like to assure you are continuously working on iCloud Private Relay compatibility.

I hope it is same subscription model as adguard for mac

**Comment by AlexandrPkhm** [comment]
@bigplayer-ai Yes, your existing AdGuard subscription should apply.
