### ISSUE TITLE
Add support of FreeBrowser

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1459]
### Issue Details

I would like to be able to manage AdGuard using the Assistant in FreeBrowser.

### Proposed solution

Add support of FreeBrowser: https://freebrowser.org/. It’s Chromium based browser.

**Comment by Aydinv13** [comment]
Duplicates https://github.com/AdguardTeam/AdguardForWindows/issues/5209

**Comment by rakleed** [comment]
@Aydinv13 starting from which version will you add filtering for all applications?

**Comment by Aydinv13** [comment]
@rakleed 

Starting from v3.0.
