### ISSUE TITLE
Option to choose filters update check period

### ISSUE THREAD

**Issue by worldsdream** [AdguardTeam/AdguardForMac#146]
Windows got it implented, would love to see this for Adguard Mac.

Can this be assigned to a Milestone?

**Comment by ameshkov** [comment]
We'll assign after we finish with the new release (when we'll be planning new milestones).

**Comment by ameshkov** [comment]
The same feature on Windows (has been implemented a long time ago): 
https://github.com/AdguardTeam/AdguardForWindows/issues/941

**Comment by planet0** [comment]
This would be very useful, it's wonderful on Windows and Android. On this Mac, I keep occasionally manually update filters and somehow always manage to get AdGuard to update at least one filter. Wish I could set it hourly like the other devices and let AdGuard do it automatically more often.

**Comment by tomiams** [comment]
When can we get this feature?

**Comment by danidoedel** [comment]
Any actual plans for this one?

**Comment by nohli** [comment]
What is the interval now?

I came here wondering if the filters get auto-updated at all - because, when starting `Check for Filter Updates`, it usually finds a lot of updates.
Sometimes, I see ads despite AdGuard being enabled, then update the filters and the ads are gone.
An ad-blocker should catch up with ads adapting to filters.

**Comment by danidoedel** [comment]
> What is the interval now?
> 
> I came here wondering if the filters get auto-updated at all - because, when starting `Check for Filter Updates`, it usually finds a lot of updates.
> Sometimes, I see ads despite AdGuard being enabled, then update the filters and the ads are gone.
> An ad-blocker should catch up with ads adapting to filters.

Base filter update interval is set to 4 days I believe. You can see it in the top of the filter somewhere.

**Comment by nohli** [comment]
@danidoedel thanks!
So this can't be changed, only with workarounds, right?

**Comment by Chinaski1** [comment]
@nohli 

Yes, at the moment you can only speed up this process by using a manual update.
We will try to add the ability to change the interval in version 2.7

**Comment by nohli** [comment]
Is there a command-line option to update the filters, so we could update via script?

**Comment by Chinaski1** [comment]
Unfortunately, no.

**Comment by planet0** [comment]
> This would be very useful, it's wonderful on Windows and Android.

Even after three years later and I'm still looking forward to having this on macOS 🙏🏼

**Comment by nohli** [comment]
The new beta finally has this feature:
https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.7.0.1073
