### ISSUE TITLE
Network Service Does Not Start Correctly, Login Item Removed

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#1462]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

17.6

### OS version

14.6.1

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

Regular

### Issue Details

Sporadic. Simply start up machine after shutdown.

### Expected Behavior

AdGuard starts without complaint.

### Actual Behavior

Sometimes, AdGuard does not start, and gives no indication. Sometimes, it complains the network filtering service does not start correctly. Either way, when I check in Login Items, I find it has been removed, for no reason.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

This only happens _sometimes_.

**Comment by AlexandrPkhm** [comment]
Hi @i-am-linja 

We apologise for the delayed response.  To diagnose this issue, we need to get the application logs.
Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar → Gear → Advanced  → Logging → Logging level → **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu → Advanced → Logging → **Export Logs and System Info…**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by ghost** [comment]
@AlexandrPkhm Got it. Sent just now.

**Comment by AlexandrPkhm** [comment]
@i-am-linja Please accept our apologies for the delayed response. Our development team will investigate the issue with network service not being able to start correctly.

Regarding the issue with AdGuard login item being removed. Could you please let us know if you are using any system cleaning application that might affect the login items by performing any kind of optimization? Could you also try to record the debug logs of the disappearing login item and send the archive to `apple@adguard.com`?

**Comment by ghost** [comment]
I have PearCleaner installed, but I don’t run it as a service. The only other service I run is Swish, which does have wide permissions but it shouldn’t touch other login items.

I don’t think I’ll be able to capture a log, given that the issue happens when AdGuard is not running. I don’t think a full system log will be of much use to you.
