### ISSUE TITLE
Permanently disable "Software Update" pop-up window

### ISSUE THREAD

**Issue by dgrinin** [AdguardTeam/AdguardForMac#1463]
### Issue Details

AdGuard for Mac utilizes a specific pop-up window to alert users about software updates, which operates independently of the macOS notification system settings. Even with AdGuard notifications disabled within macOS, this update prompt persists. Additionally, the "Skip This Version" button does not offer a lasting solution, as it only suppresses the pop-up until the next version is released, leading to repeated interruptions.

### Proposed solution

Introduce an option in AdGuard's settings that allows users to permanently disable the update pop-up window, enabling users to opt out of receiving these specific update prompts completely.

### Alternative solution

Adopt the macOS native notification system for delivering software update notifications. This would allow users to manage these alerts directly through macOS notification settings, ensuring a consistent and user-controlled experience.

**Comment by dgrinin** [comment]
Here is the pop-up window I'm referring to
<img width="732" alt="Screenshot 2024-08-03 at 21 59 42" src="https://github.com/user-attachments/assets/f3243122-ecad-4246-b90a-b9608ca5c324">

**Comment by AlexandrPkhm** [comment]
Hi @dgrinin 

Could you please clarify what are you trying to achieve by disabling updater pop-up? 
This pop up should be a rare occurrence if you are on *release* update channel. Besides, generally updates contain bugfixes and other improvement which in turn are aimed at making user experience better.

**Comment by AlexandrPkhm** [comment]
@dgrinin Please let us know if there are any news on the issue?
