### ISSUE TITLE
Trusted scriptlets not working

### ISSUE THREAD

**Issue by billkewl** [AdguardTeam/AdguardForMac#1465]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731 release

### OS version

macOS Sonoma

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. add user rule `ok.ru#%#//scriptlet('trusted-click-element', '.vid_play', '5000')`
2. open https://9tsu.cc/push240714
3. Adjust delay to 5000

Another example 
1. user rule `nogizaka46.com#%#//scriptlet('trusted-click-element', '.js-lang-wp>p.ja', '3000')`
2. Open https://www.nogizaka46.com/s/n46/

### Expected Behavior

play button clicked automatically / language set to Japanese

### Actual Behavior

play button not clicked / language not set to Japanese

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

### Additional Information

Is this scriptlet expected to work or there's anything wrong with my rules?

I reported this issue last month via app report and email but they told me they can't solve it and I have to open an issue here. Plus I was somehow assigned to Japanese support.

**Comment by AdamWr** [comment]
Probably wrong syntax - https://github.com/AdguardTeam/Scriptlets/blob/master/wiki/about-trusted-scriptlets.md#-%EF%B8%8F-trusted-click-element
```
example.com#%#//scriptlet('trusted-click-element', selectors[, extraMatch[, delay]])
```
`delay` should be after `extraMatch` argument.

Please try to use these rules:
```adblock
ok.ru#%#//scriptlet('trusted-click-element', '.vid_play', '', '5000')
nogizaka46.com#%#//scriptlet('trusted-click-element', '.js-lang-wp>p.ja', '', '3000')
```

**Comment by billkewl** [comment]
Thank you. These rules indeed work. 
Isn't extraMatch optional? Why it has to be added to the rules?

**Comment by AdamWr** [comment]
>Isn't extraMatch optional?

It is, the same like a `delay`.

>Why it has to be added to the rules?

Arguments passed to scriptlets must be in strict order to works correctly.
If  `delay` is passed in the place of `extraMatch` then it will not works.

**Comment by billkewl** [comment]
Thanks for clarification.

Another unrelated question, is it possible to only apply stealth mode to certain websites? 
Hide referer and UA, mask IP options break a lot of websites that making exceptions with `@@||example.com$stealth` isn't really feasible. 
Is it possbile to enable stealth mode on websites that I don't trust only? like `[$domain=example.com]` but this modifier is only for non-basic type of rules.

**Comment by AdamWr** [comment]
>is it possible to only apply stealth mode to certain websites?

As far as I know, there is no such option but maybe something similar can achieved by rule like this:
```adblock
@@$stealth,domain=~domain1.com|~domain2.com|~domain3.com|~example.org
```
It should disable Stealth mode on all websites except `domain1.com`, `domain2.com`, `domain3.com`, `example.org`.

<hr>

>Is it possbile to enable stealth mode on websites that I don't trust only?

If I understand correctly, it's opposite of the previous question, so maybe something like this:
```adblock
@@$stealth,domain=trustedDomain1.com|trustedDomain2.com|trustedDomain3.com
```
It should disable Stealth mode only on `trustedDomain1.com`, `trustedDomain2.com`, `trustedDomain3.com`.

**Comment by billkewl** [comment]
Sorry I didn't make it quite clear.

`@@$stealth,domain=~domain1.com|~domain2.com|~domain3.com|~example.org` 
This rule is what I wanted. 
Adguard's official filters have some stealth mode disable rules. Would they conflict with the rule above?

**Comment by AdamWr** [comment]
>Adguard's official filters have some stealth mode disable rules. Would they conflict with the rule above?

Rather not.

These rules in AdGuard's filters are exceptions, so should still be applied.
But for example, if you would like to use rule like this:
```adblock
@@$stealth,domain=~domain1.com|~domain2.com|~domain3.com|~example.org
```
and in AdGuard's filters there would be a rule like:
```adblock
@@||example.org^$stealth
``` 
then Stealth mode should be disabled (by this rule `@@||example.org^$stealth`) on `example.org`, even though `example.org` is excluded in the first rule.

**Comment by billkewl** [comment]
Thank you. For the time being I'll just spoof websites that I don't trust.
Hopefully there'll be an option to switch blacklist/whitelist for domains in the future version of CoreLibs.
