### ISSUE TITLE
adguard-tcpkill crashes on macOS login

### ISSUE THREAD

**Issue by mjgardner** [AdguardTeam/AdguardForMac#1466]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731 release

### Browser version

Safari 17.6 (19618.3.11.11.5)

### OS version

macOS Sonoma 14.6.1 (23G93)

### Ad Blocking

AdGuard Base filter, AdGuard Mobile Ads filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, Legitimate URL Shortener

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, Adblock Warning Removal List, EasyList Cookie List

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks

### Other

Filter unblocking search ads and self-promotion

### Language-specific

AdGuard Dutch filter, AdGuard French filter, AdGuard German filter

### Which DNS server do you use?

Cloudflare for Families - Malware Blocking

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block Java, Hide your Referrer from third-parties, Hide your User Agent, Mask your IP address, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Log in to macOS on my MacBook Pro (16-inch, 2021, Apple M1 Max, 64 GB)

### Expected Behavior

Login confinues uninterrupted

### Actual Behavior

Just as in #530, “Problem Report for adguard-tcpkill” window opens and reports, “adguard-tcpkill quit unexpectedly. This report will be sent automatically to Apple.”

### Screenshots

<details><summary>Screenshot 1</summary>

<img width="469" alt="image" src="https://github.com/user-attachments/assets/7604b521-d0d9-40da-ae45-915d2d9c59bb">

</details>

### Additional Information

See attached for Problem Details and System Configuration: [adguard-tcpkill-2024-08-22-104311.ips.zip](https://github.com/user-attachments/files/16714512/adguard-tcpkill-2024-08-22-104311.ips.zip)

**Comment by ihurin** [comment]
+1 ZenDesk 939910

**Comment by sfionov** [comment]
@mjgardner Hello! In the latest nightly, we added extra debugging for this problem. Can you please install the latest nightly, reproduce problem, and send us updated .ips file?

**Comment by mjgardner** [comment]
> @mjgardner Hello! In the latest nightly, we added extra debugging for this problem. Can you please install the latest nightly, reproduce problem, and send us updated .ips file?

I'm still using AdGuard for Mac version 2.15.1.1731, but it's no longer happening after upgrading to macOS Sequoia 15.0 (24A335) with Safari version 18.0 (20619.1.26.31.6). Do you still need me to reproduce?
