### ISSUE TITLE
`Protect from DPI` doesn't work when AdGuard VPN is enabled

### ISSUE THREAD

**Issue by rakleed** [AdguardTeam/AdguardForMac#1469]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

Chrome 128.0.6613.85 or Safari 17.6

### OS version

14.6.1 (23G93)

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Annoyances

AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter

### Language-specific

AdGuard Russian filter

### Which DNS server do you use?

Google DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Self-destruction of third-party cookies, Disable cache for third-party requests, Hide your Referrer from third-parties, Hide your User Agent, Remove X-client-Data header from HTTP request, Protect from DPI

### Issue Details

Steps to reproduce:
1. Enable `Protect from DPI` in Stealth Mode options
2. Enable AdGuard VPN with selected mode for sites and apps, then add Chrome and Safari to app list
3. Try to open https://zona.media or any other blocked site from Russia

### Expected Behavior

Sites are opening.

### Actual Behavior

Sites don't open.

### Additional Information

Logs sent to apple@adguard.com. Related issue: https://github.com/AdguardTeam/AdGuardVPNForMac/issues/348

**Comment by AlexandrPkhm** [comment]
Hi @rakleed 

This is expected behavior and no changes are planned at this time.

**Comment by rakleed** [comment]
@AlexandrPkhm could you please mention it in https://adguard.com/kb/general/stealth-mode/#dpi?
