### ISSUE TITLE
Adguard Legacy Assistant seems not working well in Brave Browser

### ISSUE THREAD

**Issue by chigarow** [AdguardTeam/AdguardForMac#1475]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

Version 2.15.1.1731 release

### Browser version

Brave is up to date Version 1.69.162 Chromium: 128.0.6613.120 (Official Build) (arm64)

### OS version

macOS Sonoma Version 14.5 (23F79)

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Annoyances

AdGuard Annoyances filter

### Language-specific

ABPindo, AdBlockID

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

Regular

### Issue Details

Steps to reproduce:
1. Somehow the toggle is not working on every website on Brave Browser

<img width="1512" alt="Brave Browser 2024-09-09 16 08 53" src="https://github.com/user-attachments/assets/68e8567e-2840-4930-9762-1741efbac05b">

### Expected Behavior

It should show the status of Enabled or Disabled

### Actual Behavior

Currently is always Disabled but it still blocking

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by KolbasovAnton** [comment]
@chigarow Greetings! Please, try latest [nightly](https://agrd.io/mac_nightly) or [beta](https://agrd.io/mac_beta) versions. Also, haven't You updated to the Sequoia OS from Sonoma?

**Comment by chigarow** [comment]
Let me try with Beta version, because it happens also in Opera
