### ISSUE TITLE
AdGuard crashing

### ISSUE THREAD

**Issue by saputnik** [AdguardTeam/AdguardForMac#1478]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

The last one, I can't check because the app is crashing on start

### Browser version

Safari 17

### OS version

Sonoma 14.6.1

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Support ticket ID

951694

### Issue Details

Steps to reproduce:
1. Reinstall MacOS
2. Install Adguard for Mac
3. And the app keeps crashing...

### Actual Behavior

After installing the apps keeps crashing 
[AdGuard Support Request 951694.pdf](https://github.com/user-attachments/files/16992921/AdGuard.Support.Request.951694.pdf)

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by saputnik** [comment]
With Version 2.15.1.1731 release

**Comment by Aydinv13** [comment]
@saputnik Hi there!

Do you have any software that affect network traffic?
Can you try the latest [Nightly](https://agrd.io/mac_nightly) version, please?
If the problem persists share the debug logs with us, please:
1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `qa@adguard.com` and mention this issue number in the subject.

Also, send the crash report via the window in AdGuard app if it appears.
