### ISSUE TITLE
Can't grant Adguard Mac permission on sequoia macOS 15

### ISSUE THREAD

**Issue by mazzelman** [AdguardTeam/AdguardForMac#1483]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

Safari 18

### OS version

macOS Sequoia (Version 15)

### Ad Blocking

AdGuard Base filter

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Install macOS 15
2. Download Adguard for Mac from the website
3. Install Adguard
4. Switch it on
5. A window comes up that says i have to give permission
6. Permission Option is missing in the settings (See screenshot)

![Bildschirmfoto 2024-09-19 um 12 56 25](https://github.com/user-attachments/assets/66500010-a307-404b-80e6-24f3abee1d67)

### Expected Behavior

In the settings aguard is listed under the security and i can give permission.

### Actual Behavior

Adguard is missing, i can't give permission to run.

### Screenshots

<details><summary>Screenshot 1</summary>

![Bildschirmfoto 2024-09-19 um 12 56 25](https://github.com/user-attachments/assets/623abed3-ac5d-4da4-bf95-35920fb08a06)

</details>

**Comment by Aydinv13** [comment]
@mazzelman Hello!

Please, take a look https://github.com/AdguardTeam/AdguardForMac/issues/1434#issuecomment-2167670352

I am closing this one as a duplicate.

**Comment by mazzelman** [comment]
Thank you!

This solves the problem!

Greetings

Marcel
