### ISSUE TITLE
Not Able To Activate Safari Extension - Sequoia

### ISSUE THREAD

**Issue by IrishMan19** [AdguardTeam/AdguardForMac#1484]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

Safari 18.0

### OS version

macOS Sequoia 15.0

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Social

AdGuard Social Media filter

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist

### Other

Filter unblocking search ads and self-promotion

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block Push API, Block Location API, Block Java, Remove X-client-Data header from HTTP request

### Issue Details

Steps to reproduce:
1. Fresh install Adguard
2. Try to enable"Allow Adguard system extension"
3. The option to allow the extension it doesn't shows in Settings/Privacy & Security

### Expected Behavior

Expected to be able to activate  Safari AdGuard Extension from the Safari icon after I hit "Enable"

### Actual Behavior

It's not possible to activate it from the Safari Icon or to "Allow" it from System Preferences because the option to "Allow" doesn't exist inside Privacy & Security.

### Screenshots

<details><summary>Screenshot 1</summary>

![Screenshot 2024-09-19 at 11 55 51 AM](https://github.com/user-attachments/assets/ca253e88-fc26-4b53-bfc7-edd92ed69883)
</details>

### Additional Information

Not able to activate AdGuard Safari extension. Inside the Adguard Preferences-Assistant, it says that extension is activated but the icon in Safari shows that it's not. Clicking on icon in Safari, click on "Enable" opens "Allow AdGuard System Extension" window. Clicking on "Open system Preferences" it opens System Preferences but it doesn't show that AdGuard is blocked.

**Comment by IrishMan19** [comment]
Actually, I just noticed that I can't activate AdGuard at all, not just an extension. It keep asking to "Allow" it from System Preferences but whatever I do, the option to "Allow" it doesn't show up under Security & Privacy and Adguard stays deactivated.

**Comment by Aydinv13** [comment]
@IrishMan19 Hello,

it will be fixed in an upcoming release, here is a [temporary](https://github.com/AdguardTeam/AdguardForMac/issues/1434#issuecomment-2167670352) solution. Closing this issue as a duplicate

**Comment by IrishMan19** [comment]
Thank you very much
