### ISSUE TITLE
The issue of Safari browser freezing when blocking video ads on macOS 15.

### ISSUE THREAD

**Issue by gaomengzhou** [AdguardTeam/AdguardForMac#1485]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed
- [X] macOS Sequoia 15.0 (24A335)    
- [X] Safari version 18.0 (20619.1.26.31.6)

### Ask a question

After enabling the AdGuard For Mac, Safari on macOS 15 experiences issues blocking video ads, causing the browser to freeze and display the error message: “The media could not be loaded, either because the server or network failed or because the format is not supported. (The probability of occurrence is high; refreshing the page multiple times will reproduce it.)” 
This issue does not occur in other browsers, such as Chrome.

_The logs were removed due to privacy reasons_

**Comment by gaomengzhou** [comment]
By the way, this issue doesn’t occur when using the “AdGuard For Safari” browser extension. It only happens with “AdGuard For Mac”.

**Comment by Aydinv13** [comment]
@gaomengzhou Hello!

Could you try the latest [Nightly](https://agrd.io/mac_nightly) version and if the problem still persists send the debug logs to us please:
<details><summary>Instruction:</summary>

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `qa@adguard.com` and mention this issue number in the subject.
</details>

**Comment by gaomengzhou** [comment]
> @gaomengzhou哈罗！
> 
> 您能尝试最新的[Nightly](https://agrd.io/mac_nightly)版本吗？如果问题仍然存在，请将调试日志发送给我们：
> 
> 指示：
> 1. 单击菜单栏中的**AdGuard图标**-->齿轮-->高级-->日志记录-->日志记录级别-->**调试**；
> 2. 重复问题，并记住它发生的确切时间；
> 3. 菜单-->高级-->日志-->**导出日志和系统信息...**；
> 4. 将档案发送至`qa@adguard.com`，并在主题中提及此问题编号。

I tried the latest Nightly version, but the issue still persists. The logs have been sent to qa@adguard.com as requested.

**Comment by gaomengzhou** [comment]
> @gaomengzhou Hello!
> 
> Could you try the latest [Nightly](https://agrd.io/mac_nightly) version and if the problem still persists send the debug logs to us please:
> 
> Instruction:
> 1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
> 2. Reproduce the issue and remember the exact time it happened;
> 3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
> 4. Send the archive to `qa@adguard.com` and mention this issue number in the subject.

I tried the latest Nightly version, but the issue still persists. The logs have been sent to qa@adguard.com as requested.

**Comment by Aydinv13** [comment]
@gaomengzhou seems that the issue you faced is related to incorrect ad blocking which is fixed by filter maintainers.

To resolve the issue you need to go to the troubled site, open [Safari Assistant](https://uploads.adguard.org/up85_420hi.png) and click on [Report this website](https://uploads.adguard.org/up85_yd8nf.png), then complete a short survey.
I'm closing this issue.
