### ISSUE TITLE
App's GUI is inaccessible after installation

### ISSUE THREAD

**Issue by BrainRTP** [AdguardTeam/AdguardForMac#1490]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### OS version

MacOS Sequoia 15.0

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Install latest version
2. Try to open

### Actual Behavior

Do not open a GUI

### Screenshots

<details>
I cut video to make <10mb size.
But. when i open nothing opened (i mean GUI). After i open adguard and try to open settings from upside bar - it close automatically (i do not push any button)

https://github.com/user-attachments/assets/6ca7a57b-269d-4df3-95a8-eb70beedb66d

</details>

### Additional Information

I try to reinstall by delete from system adguard and download from site again - nothing happens :(

And before i catch this bug i has adguard installed.

**Comment by AlexandrPkhm** [comment]
@BrainRTP Hello!

Could you please try to completely remove AdGuard from your device and then install the latest AdGuard for Mac Nightly version which is available via the following link https://agrd.io/mac_nightly. 

Please let us know if the issue persists on the Nightly version.

**Comment by BrainRTP** [comment]
> https://agrd.io/mac_nightly.

@AlexandrPkhm hi!
Reinstalled. The problem persisted.
The GUI appeared when the initial setup was taking place (system access), but after that the window closed and does not open anymore

**Comment by AlexandrPkhm** [comment]
@BrainRTP In this particular case, we will need the application logs in order to diagnose and troubleshoot the issue. Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar *→ Gear → Advanced  → Logging → Logging level → Debug*.
2. Reproduce the problem (try opening Settings or any other menu option in the aforementioned Gear menu), then remember the exact time it happened.
3. *Menu → Advanced → Logging → Export Logs and System Info.…*.
4. Send this file to [qa@adguard.com](mailto:qa@adguard.com):
    - include `[mac]` keyword and `ISSUE_NUMBER` in the subject of your email
    - specify the exact time when the issue occurred

**Comment by AlexandrPkhm** [comment]
@BrainRTP Could you please let us know if you were able to record the application logs of the issue?

**Comment by BrainRTP** [comment]
@AlexandrPkhm how to reopen this?) 
The problem is still relevant today. I sent the data to the post office, but never received a reply.
