### ISSUE TITLE
Adguard breaks latest Safari setting to open tabs from last session

### ISSUE THREAD

**Issue by bluelephant825** [AdguardTeam/AdguardForMac#1493]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 2.15.1.1731

### Browser version

Safari 18.0.1

### OS version

macOS Ventura 13.7

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter

### Social

AdGuard Social Media filter

### Other

AdGuard DNS filter

### Language-specific

AdGuard French filter, AdGuard German filter, Dandelion Sprout's Nordic Filters

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies

### Issue Details

Steps to reproduce:
1. Open the following 2 tabs in Safari: mail.google.com and chatgpt.com (make sure you're logged in)
2. In Safari Settings, under the General tab, ensure that the option "Safari opens with:" is set to "All windows from last session"
3. Close Safari
4. Re-open Safari

### Expected Behavior

The 2 tabs opened previously should re-appear in the browser window.

### Actual Behavior

The 2 tabs are missing. They have been closed.

### Screenshots

<details><summary>Screenshot 1</summary>

![CleanShot 2024-10-05 at 18 08 16@2x](https://github.com/user-attachments/assets/9f16a0d4-999f-44d0-bc2c-d4ca59f09b53)

</details>

### Additional Information

[Video demo](https://imgur.com/a/6J1AnkL)

**Comment by AlexandrPkhm** [comment]
Hi @odebroqueville, 

From the description of the problem, it does not seem to be related to AdGuard. Could you please do the following: 
1. Open **System preferences** and navigate to **Desktop & dock** section.
2. Make sure that the **Close windows when quitting an application** option is turned off.
<img width="716" alt="Screenshot 2024-10-04 at 15 53 01" src="https://github.com/user-attachments/assets/93136c9b-d1fd-4efc-868d-72a9dbf32f9f">

If this option is enabled, it closes all the opened widows of the closed app. Therefore, Safari is unable to open any windows upon next launch.

Please let us know if the issue still persists after this.

**Comment by bluelephant825** [comment]
Changing the above setting doesn't resolve the issue. However, after investigating further, I believe that I have found the app causing trouble: Cookie, not Adguard.
