### ISSUE TITLE
Installed AdGuard - no option to allow system access to enable AdGuard

### ISSUE THREAD

**Issue by gundam101cyber** [AdguardTeam/AdguardForMac#1496]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

Safari Version 18.0.1 (20619.1.26.31.7)

### OS version

macOS 15.0.1 (24A348)

### Ad Blocking

AdGuard Base filter

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.Installed AdGuard for the first time.
2.It then asked me to open system preferences to allow AdGuard to access my system.
3.However there is no option to allow it so I am stuck at this point.

![Greenshot 2024-10-12 16 17 51](https://github.com/user-attachments/assets/b5299da9-d24c-470a-8f71-c67e48299fab)
![Greenshot 2024-10-12 16 17 39](https://github.com/user-attachments/assets/199e56b3-a906-4be3-9a40-a5f0c25aa57c)

### Actual Behavior

No option to allow AdGuard access.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@gundam101cyber Hi!

Here is a short [instruction](https://github.com/AdguardTeam/AdguardForMac/issues/1434#issuecomment-2167670352) how to enable it.
The issue will be fixed in the next release version. Closing this one as a duplicate.
