### ISSUE TITLE
Can't find this permits setting anywhere. Could you be more clear please?

### ISSUE THREAD

**Issue by ilMagnifico** [AdguardTeam/AdguardForMac#1498]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question
<img width="780" alt="Screenshot 2024-10-14 alle 14 31 51" src="https://github.com/user-attachments/assets/5038e2e9-7d81-4344-9280-a65ff3fd8962">
<img width="544" alt="Screenshot 2024-10-14 alle 14 41 34" src="https://github.com/user-attachments/assets/d69f63a4-9738-49f9-bb81-368f2d1d64e9">

<img width="915" alt="Screenshot 2024-10-14 alle 14 35 21" src="https://github.com/user-attachments/assets/88cf2cde-94c6-4ebd-9a91-797cf495557e">

Restart doesn't work.

**Comment by ilMagnifico** [comment]
Solved:

You need to enable this:
<img width="565" alt="Screenshot 2024-10-14 alle 14 43 05" src="https://github.com/user-attachments/assets/1ca9627e-2498-4288-80d4-ea7e23797775">

**Feedback: make the AdGuard instructions clearer.**

**Comment by Aydinv13** [comment]
@ilMagnifico 

We're already working on it https://github.com/AdguardTeam/AdguardForMac/issues/1434
