### ISSUE TITLE
your network preferences prevent content from loading privately

### ISSUE THREAD

**Issue by ilMagnifico** [AdguardTeam/AdguardForMac#1499]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

Safari latest

### OS version

macOS 15.0.1

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Just open an email.

### Actual Behavior

<img width="1062" alt="Screenshot 2024-10-15 alle 15 20 59" src="https://github.com/user-attachments/assets/2a0fa762-bb67-4dce-8a06-1ed036aa79c1">
<img width="1063" alt="Screenshot 2024-10-15 alle 15 21 09" src="https://github.com/user-attachments/assets/12733f47-7672-4efd-9c42-280213b80ded">

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@ilMagnifico Hello!

Please follow the steps [here](https://adguard.com/kb/guides/report-website/#mac) to report the problem. I'm closing this issue.
