### ISSUE TITLE
Ads not blocked in Safari on macOS Sequoia with iCloud Private Relay enabled

### ISSUE THREAD

**Issue by siddiqq** [AdguardTeam/AdguardForMac#1500]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

AdGuard 2.15.1.1731

### Browser version

18.1

### OS version

15.1 Beta (24B5077a)

### Ad Blocking

AdGuard Base filter

### Privacy

AdGuard Tracking Protection filter

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

This was reported before, and the issue was closed and deemed fixed for some reason. But it is still not fixed. When Private Relay is Off, no ads come through. Then when I switch it back on , nothing seems to change for maybe 10-15 minutes, which is why the previous report was probably deemed fix, but then sure enough the ads start coming through. This issue is definitely not fixed.

### Expected Behavior

Ads blocked

### Actual Behavior

Ads are not blocked

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@siddiqq 

We've reopened the previous issue which was closed by mistake. Thank you
