### ISSUE TITLE
"Learn more" link in Extensions is out of date

### ISSUE THREAD

**Issue by ColeFrench** [AdguardTeam/AdguardForMac#1501]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731 release

### OS version

macOS Sonoma 14.5

### Which DNS server do you use?

DNS protection disabled

### DNS protocol

None

### Issue Details

Steps to reproduce:
1. Open AdGuard Settings
2. Go to the Extensions tab
3. Click on the `Learn more` link in the description of the `Extensions` checkbox

### Expected Behavior

The link takes you to https://adguard.com/kb/general/extensions/.

### Actual Behavior

The link takes you to https://adguard.com/kb/general/userscripts/, which no longer exists.

**Comment by Aydinv13** [comment]
@ColeFrench Hi,

thanks for the report, will be fixed.
