### ISSUE TITLE
Apple Pay not working

### ISSUE THREAD

**Issue by bidea117** [AdguardTeam/AdguardForMac#1506]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15.1.1731

### Browser version

Safari 18.1

### OS version

MacOS Sonoma 15.1

### Ad Blocking

AdGuard Base filter, EasyList

### Privacy

AdGuard Tracking Protection filter, AdGuard URL Tracking filter, EasyPrivacy, Legitimate URL Shortener, Peter Lowe's Blocklist, Fanboy's Anti-Facebook List

### Social

AdGuard Social Media filter, Fanboy's Social Blocking List

### Annoyances

AdGuard Annoyances filter, AdGuard Cookie Notices filter, AdGuard Popups filter, AdGuard Mobile App Banners filter, AdGuard Other Annoyances filter, AdGuard Widgets filter, Adblock Warning Removal List, Fanboy's Annoyances, EasyList Cookie List, Dandelion Sprout's Annoyances List

### Security

Online Malicious URL Blocklist, Phishing URL Blocklist, Scam Blocklist by DurableNapkin, uBlock Origin – Badware risks, NoCoin Filter List

### Other

Filter unblocking search ads and self-promotion, AdGuard DNS filter, AdGuard Experimental filter, Fanboy's Anti-thirdparty Fonts

### Which DNS server do you use?

Quad9

### DNS protocol

DNS-over-HTTPS

### What Stealth Mode options do you have enabled?

Block trackers, Remove tracking parameters, Hide your search queries, Send Do-Not-Track signals, Self-destruction of third-party cookies, Block WebRTC, Block Push API, Block Location API, Block Java

### Issue Details

Steps to reproduce:
1. Launch any site that support Apple Pay
2. Try to buy something with Apple Pay
3. Will not prompt for 'Pay with Touch ID'

### Expected Behavior

Apple Pay in Safari should prompt with 'Pay with TouchID'

### Actual Behavior

Apple pay prompts but no 'Pay with TouchID' prompt.

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by bidea117** [comment]
_logs were removed from public access_

**Comment by ameshkov** [comment]
Cannot reproduce this on adguard.com on AG for Mac v2.16 nightly version.

**Comment by Aydinv13** [comment]
@bidea117 Hi there!

Could you name the website where you encountered this problem? Have you tried to change the DNS server? 
Also, your logs are not detailed, could you please grab the debug ones.
<details><summary>Here's what we need you to do:</summary>

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Send the archive to `qa@adguard.com` and mention this issue number (1506) in the subject.
</details>

**Comment by bidea117** [comment]
Logs have been sent.

> @bidea117 Hi there!
> 
> Could you name the website where you encountered this problem? Have you tried to change the DNS server? Also, your logs are not detailed, could you please grab the debug ones.
> 
> Here's what we need you to do:
> 1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
> 2. Reproduce the issue and remember the exact time it happened;
> 3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
> 4. Send the archive to `qa@adguard.com` and mention this issue number (1506) in the subject.

Logs have been sent.

**Comment by bidea117** [comment]
> @bidea117 Hi there!
> 
> Could you name the website where you encountered this problem? Have you tried to change the DNS server? 
> Also, your logs are not detailed, could you please grab the debug ones.
> <details><summary>Here's what we need you to do:</summary>
> 
> 1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
> 2. Reproduce the issue and remember the exact time it happened;
> 3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
> 4. Send the archive to `qa@adguard.com` and mention this issue number (1506) in the subject.
> </details>

To answer your questions here

Sites used:

Apple com and campfireaudio.com

DNS change:

No I haven't tried changing the DNS server.

**Comment by Aydinv13** [comment]
@bidea117 as I can see, the logs were not recorded completely, the last time is 05:04, could you grab them again, please. Also, try to:
- change DNS server or to turn off the DNS Module
- disable Stealth mode
- update to the latest release

**Comment by bidea117** [comment]
> @bidea117 as I can see, the logs were not recorded completely, the last time is 05:04, could you grab them again, please. Also, try to:
> 
> * change DNS server or to turn off the DNS Module
> * disable Stealth mode
> * update to the latest release

I have updated to the latest version this morning before reattempting to recreate the issue and have:

- change the DNS to AdGuard DNS
- Turned off the DNS module
- disabled Stealth mode

Does not  fix the issue. I have attached additional logs which will hopefully capture the chain of events.

Sites used:

- Apple.com (attempting to purchase something with Apple Pay)
[adguard_logs_20241108162749.zip](https://github.com/user-attachments/files/17681482/adguard_logs_20241108162749.zip)

- AdGuard.com (attempting to purchase a license with Apple Pay)

**Comment by bidea117** [comment]
Good morning,

I would like to report that I have found the isssue, it was the AdGuard Assistant Safari browser extention that was causing the issue. Still nott sure why but disabling it fixed the issue.

**Comment by bidea117** [comment]
I would like to figure out the underlying issue however. Please let me know if you need further logs.

**Comment by ihurin** [comment]
@Aydinv13 let customer know if further assistance in debugging is needed. Thank you!
@bidea117 we are grateful for cooperation.

**Comment by Aydinv13** [comment]
@bidea117 do you mean "AdGuard Assistant" and you disable it by clicking here?
<img width="450" alt="up85_pfe8r" src="https://github.com/user-attachments/assets/0aa7adb0-6b16-4a3d-9018-7661c6ae0e6d">

**Comment by bidea117** [comment]
> @bidea117 do you mean "AdGuard Assistant" and you disable it by clicking here? <img alt="up85_pfe8r" width="450" src="https://private-user-images.githubusercontent.com/73467237/385304376-0aa7adb0-6b16-4a3d-9018-7661c6ae0e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0MjA1NDEsIm5iZiI6MTczMTQyMDI0MSwicGF0aCI6Ii83MzQ2NzIzNy8zODUzMDQzNzYtMGFhN2FkYjAtNmIxNi00YTNkLTkwMTgtNzY2MWM2YWUwZTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEyVDE0MDQwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5NzIyYzhiNDViNzNlNTEzNGViMWRmYzg4OTkzMmRlMGUyOWFlYjFjYjllYmJmYTIwNzc4OGRmZmY4NmZkODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HpDpnveW2gToRD1rXtjoLUxougKyTVF2H5sHcsrVG8Q">

That's the one!

**Comment by bidea117** [comment]
The issue returned so I tried removing Adguard all together (removing login items, daemons, launch agents) and the issue was fixed. Something within Adguard was preventing Apple Pay in Safari from successfully working.

**Comment by Aydinv13** [comment]
@bidea117 unfortunately, I can't see the screen

>That's the one!

Could you open Filtering log (Gear - Advanced - Filtering log), uncheck Regular requests and reproduce the issue. Is there any blocked requests?
