### ISSUE TITLE
[Question] Cannot Completely Uninstall

### ISSUE THREAD

**Issue by kands-code** [AdguardTeam/AdguardForMac#1507]
### Please answer the following questions for yourself before submitting a question.

- [X] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

For some reason, I need to uninstall Adguard for Mac, but when I check the system, I find that the `com.adguard.mac.adguard` entry in the local network settings cannot be deleted at all. What should I do to completely remove this?

**Comment by kands-code** [comment]
![5bb269dadc637b5b0dc8e68a4677a807](https://github.com/user-attachments/assets/376ecc20-705b-4124-9c42-3357cd1f813f)

System Settings > Privacy & Security > Privacy.

**Comment by Aydinv13** [comment]
@kands-code Hi,

which macOs version do you have?
Have you tried this [instruction](https://adguard.com/kb/adguard-for-mac/installation/#uninstall)?

**Comment by kands-code** [comment]
@Aydinv13 Thank you very much for your reply. My macOS version is 15.1, and I have already tried the methods mentioned in the link you provided. Everything else is fine, but the `com.adguard.mac.adguard` entry in the settings cannot be deleted. I believe that a plist file for some macOS setting has recorded this entry, but it has not been updated after the software was uninstalled.

**Comment by Aydinv13** [comment]
@kands-code oh sorry, I got what your problem is, it's a known issue and will be fixed [here](https://github.com/AdguardTeam/AdguardForMac/issues/1477).

**Comment by Aydinv13** [comment]
I'm closing this one as a duplicate.

**Comment by unknownsolo** [comment]
Issue is still not fixed!
