### ISSUE TITLE
Question about sciter and go bindings

### ISSUE THREAD

**Issue by whisperecean** [AdguardTeam/AdguardForMac#1510]
### Please answer the following questions for yourself before submitting a question.

- [x] I am running the latest version
- [X] I checked to make sure that this issue has not already been filed

### Ask a question

Hi adguard team. I was told to ask here.
I would like to develop a menubar app for Mac using sciter and go and as you seem to be the only prominent user of those Id like to ask if it is still somehow possible.

i have been told you only use the go bindings for “testing” whatever that means. ( just as a runner for the UI part?)

i am running into the crash issue with go routines but that is because i wanted to use systray go package. Was curious if i dont use that and stick to Go code and the rest objc or native if I am fine.

Many thanks for any help❤️

**Comment by KolbasovAnton** [comment]
@whisperecean Greetings! The easiest way to ask technical questions is on the Sciter's forum - https://sciter.com/forums/.
