### ISSUE TITLE
Can not enalbe AdGuard 2.16.0 (1856)b on macOS Sequoia.1.1

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdguardForMac#1511]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.16.0 (1856)b

### OS version

macOS Sequoia.1.1

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

DNS-over-QUIC

### Issue Details

Steps to reproduce:
1. upgrade to AdGuard 2.16.0 (1856)b
2. Launch AdGuard 2.16.0 (1856)b
3. Open Adguard main window
4. can not enable toggle switch

### Actual Behavior

can not enable

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by Aydinv13** [comment]
@Chamiu Hi there

To troubleshoot this issue, we need to get the app logs and settings.
<details><summary>Here's what we need you to do:</summary>

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> Logging --> **Export Logs and System Info...**;
4. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Export Settings
5. Send the archives to `qa@adguard.com` and mention this issue number in the subject.
</details>

**Comment by Aydinv13** [comment]
@Chamiu Is the issue still relevant?

**Comment by Chamiu** [comment]
> @Chamiu Hi there
> 
> To troubleshoot this issue, we need to get the app logs and settings.
> 
> Here's what we need you to do:

Again, "Can not enalbe AdGuard 2.16.0 on macOS Sequoia.2"
I send log and settings.
But
1. set debug mode
2. quit
3. launch
4. normal mode <- auto change

**Comment by Chamiu** [comment]
1. launch
2. debug mode
3. quit.
4. launch
5. auto change to normal

When should I export log?

I understand that you want to see operation log from launch, but 5. Since log mode becomes normal,
Since you can't keep log acquisition mode, it's logically self-evident that you can't get the log, right?
it's a bug that it doesn't keep log mode, right?

Isn't it wrong to ask users to do what they can't do in app's specifications?

**Comment by Chamiu** [comment]
It's solved in v2.16.1 for macOS.
