### ISSUE TITLE
Failed to start AdGuard after updating to 2.16.0.1857

### ISSUE THREAD

**Issue by ernestyao** [AdguardTeam/AdguardForMac#1515]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.16.0.1857

### Browser version

Arc, Safari

### OS version

macOS 15.2

### Which DNS server do you use?

System default DNS

### DNS protocol

None

### Issue Details

Steps to reproduce:
1.
2.
3.

### Actual Behavior

After updating to 2.16.0.1857, Adguard cannot be activated. The app start but I can't turn it on. Restarting the whole macOS does not solve.

[Uploading adguard_logs_20241218133613.zip…]()

### Screenshots

<details><summary>Screenshot 1</summary>

</details>

**Comment by ernestyao** [comment]
I reinstalled 2.15.2.1734, everything works fine now. Nothing else changed. So I suppose it's all about v2.16.

**Comment by AlexandrPkhm** [comment]
@ernestyao Hello!

The issue is related to third-party custom filters with checksums. We are working on a fix. To monitor the status of the resolution, we recommend that you track the issue at https://github.com/AdguardTeam/AdguardForMac/issues/1514

**Comment by Chamiu** [comment]
Perhaps, this issue equal  #1511 ?

**Comment by AlexandrPkhm** [comment]
@Chamiu Hello! 

We have released [AdGuard for Mac 2.16.1](https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.16.1) version which contains a fix for this issue. Please try updating and let us know if the issue still persists.

**Comment by ernestyao** [comment]
It's solved in v2.16.1 for macOS.
