### ISSUE TITLE
Apple News ads 

### ISSUE THREAD

**Issue by ihurin** [AdguardTeam/AdguardForMac#1517]
### Please answer the following questions for yourself before submitting an issue

- [X] Filters were updated before reproducing an issue
- [X] I checked the [knowledge base](https://adguard.com/kb/) and found no answer
- [X] I checked to make sure that this issue has not already been filed

### AdGuard version

2.15

### OS version

15.1

### Which DNS server do you use?

AdGuard DNS

### DNS protocol

None

### Support ticket ID

998480

### Issue Details

Open Apple News app -- see ads 

### Expected Behavior

No ads 

### Actual Behavior

There are ads.

### Screenshots

<img width="1137" alt="PastedGraphic-4" src="https://github.com/user-attachments/assets/5601d0c0-b868-4b5f-b26e-10297bb6c185" />
<img width="1148" alt="PastedGraphic-2" src="https://github.com/user-attachments/assets/8a034f90-0f03-4cc3-b119-a17caba108ba" />

**Comment by AlexandrPkhm** [comment]
Unfortunately, those ads can't be blocked https://github.com/AdguardTeam/AdguardFilters/issues/177309
