### ISSUE TITLE
User Style Feature Not Working for Some Userstyles

### ISSUE THREAD

**Issue by jiywww** [AdguardTeam/AdguardForMac#1520]
The new feature of adding user styles doesn’t work for some user styles, such as https://userstyles.world/style/12670/modern-hacker-news (and many others from userstyle.world). When creating a new user style, a pop-up error appears stating, “Failed to save extension: The operation couldn’t be completed. (ANUserscriptParserErrorDomain error 5.)”

**App version**: Version 2.16.1.1860 release
**OS version**: macOS Sequoia 15.2

**When you noticed the problem?**
Since the new adding Userstyle released.

**What you were doing or what happened to the app before you noticed the problem. Steps to reproduce it.**
Open an Adguard window -> Extensions Tab -> Click on the ➕ icon -> Install from File or URL or Create Userstyle -> fill in the URL or Userstyle content -> Click on the next button.

**Whether it recurred and with what frequency?**
Everytime

**Whether you have a VPN or an antivirus software?**
No

![CleanShot 2024-12-23 at 13 29 22@2x](https://github.com/user-attachments/assets/fbd34cbc-7fa1-47a5-bfac-a4bab37e06d3)

**Comment by Aydinv13** [comment]
@jiywww Hi there!

It seems that the userstyle you are trying to install contains unsupported metadata, see our [Knowledge Base](https://adguard.com/kb/general/extensions/#how-to-set-up-a-userstyle-in-adguard).
