### ISSUE TITLE
Error while updating user preferences

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#153]
STR:

You should have Adguard 1.3.2 beta installed.

1. Uninstall 1.3.2 beta
2. Install Adguard 1.3.0.
3. Run it.

You are supposed to get an error message and Adguard will not start until you reset the preferences

[debug.txt](https://github.com/AdguardTeam/AdguardForMac/files/631080/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForMac/files/631081/state.txt)

`2016/12/05 13:52:53:102  Error unloading kext. See system log.
2016/12/05 13:52:53:102  Error trace - AASNetwork[0x60000022de40]: callUnloadKext:
2016/12/05 13:59:35:467  Application Started! Version: 1.3.0.309
2016/12/05 13:59:35:500  (AADefaultsUpdater) Error occured when updating user defaults from version: 7.
2016/12/05 13:59:35:500  Error trace - AADefaultsUpdater[0x10cb30cd8]: updateDefaults
2016/12/05 13:59:35:508  (AAAppDelegate) User Defaults failed on updating.`

![screenshot 2016-12-05 13 59 50](https://cloud.githubusercontent.com/assets/17472907/20885492/19cba818-bb02-11e6-9572-eb159709a15d.png)

**Comment by Stillness-2** [comment]
It is normal behaviour
