### ISSUE TITLE
Unable to add rules for oregonlive.com

### ISSUE THREAD

**Issue by Darina655** [AdguardTeam/AdguardForMac#158]
Comments and social media widgets are blocked in Adguard for Mac 1.3.0 and can not be blocked in  Adguard for Mac 1.4.0 on the web page when we create the following rules in user filter:

oregonlive.com###rtb-comments > DIV.fyre.fyre-width-medium > DIV.fyre-widget (for the comments block)
oregonlive.com###footer-col-3 > DIV.cluster.clearfix (for the social media widgets at the bottom of the page)
oregonlive.com###adv_network

The direct link to the page:
http://www.oregonlive.com/opinion/index.ssf/2016/12/the_cabinet_as_a_ruling_oligar.html?
This issue is possible to reproduce.

user ID 536831

**Comment by ameshkov** [comment]
Hm, it seems there is some kind of an anti-adblocking script on this website.

So, instead of the old rules I suggest trying extended CSS rules, which will be more reliable in this case.

```
oregonlive.com###adv_network:has(div)
oregonlive.com###footer-col-3 > DIV.cluster.clearfix:has(.full-width)
oregonlive.com##.fyre-width-medium > .fyre-widget:has(div)
```

**Comment by stevewi** [comment]
Hi...

All these rules started working with no changes to my rules setup a few days ago.  Did oregonlive.com change something (let up on their offense) or did you improve your defense.  I notice that you have removed this fix from a future release.

Thanks in advance for the Info...

Steve Witten (user ID 536831)

**Comment by ameshkov** [comment]
@stevewi it's just anti-adblock script was handled by Adguard's English filter.
