### ISSUE TITLE
Mail.app cannot authorize in Gmail

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#159]
Source:
https://forum.adguard.com/index.php?threads/adblock-proxy-blocs-gmail-in-mail.18047/

@Stillness-2 I guess there should be a temporary solution for this issue, like disabling https filtering for a certain domain. Could you please check it?

**Comment by Stillness-2** [comment]
We need to add `gil.apple.com` in ssl exception list

**Comment by ameshkov** [comment]
Updated default https exceptions lists:
https://github.com/AdguardTeam/AdguardForWindows/issues/911

**Comment by oprotsyk** [comment]
Adding to the whitelist didn't help.
What to ask the user? 
Thank you.

**Comment by Stillness-2** [comment]
@oprotsyk 
Did you add domain `gil.apple.com` into exclusions list?
It is button `Exclusions...` on this screen.
![temp](https://cloud.githubusercontent.com/assets/12689/22549260/8559c07e-e95b-11e6-98d4-c68558757c18.png)

**Comment by zebrum** [comment]
@oprotsyk it's not the same problem, so send me vendor request again please.
