### ISSUE TITLE
MacOS X parental control function vs. Adguard possible issue

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#161]
Adguard works well under my regular login in which I initiated the purchase. I set Adguard up into the two logins of my child's (same device Macbook) and the client shows me, that's all is properly configured, enabled and it is linked to my license as well. But it won't work in their logins.

If you set up the Mac OS X build in parental control as I do/did for my child's account Adguard won't work properly. In this case, ads won't be filtered or in some cases (www.golem.de) the site even won't load at all.

My parental control was not even configured to filter the web traffic. It was just used to limit the usage time and the time frame for logins. But I guess the build in protocol function collides in some way with Adguard.

Ticket: 1475078 (waiting for logs)

**Comment by zebrum** [comment]
right now we have this log:

[debug (2).txt](https://github.com/AdguardTeam/AdguardForMac/files/678779/debug.2.txt)
Could it be some kind of compatibility conflict?

**Comment by ameshkov** [comment]
@Stillness-2 any idea?

**Comment by zebrum** [comment]
unfortunately Adguard is not supposed to work with parental control on Mac.
