### ISSUE TITLE
eu.battle.net - site is broken by Adguard injection

### ISSUE THREAD

**Issue by vgavrish** [AdguardTeam/AdguardForMac#162]
1477880
http://eu.battle.net/ru/
This page contains the following errors: error on line 10 at column 122: EntityRef: expecting ';' Below is a rendering of the page up to the first error.

<details>

![image](https://cloud.githubusercontent.com/assets/18548949/21561479/aac11c64-ce75-11e6-8459-04c5aeded55f.png)

**Comment by Stillness-2** [comment]
https://www.w3.org/TR/xhtml1/#C_12

**Comment by Stillness-2** [comment]
@vgavrish Ask the user to update the app
