### ISSUE TITLE
electricquilt.com - Chrome is attempting to download GZ file

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#166]
http://electricquilt.com/online-shop/jelly-roll-quilt-magic/
Chrome is attempting to download GZ file when you try to add something to cart
Response header is absent.

In Windows repository:
https://github.com/AdguardTeam/AdguardForWindows/issues/1498

**Comment by vozersky** [comment]
reproduced
check:
https://github.com/AdguardTeam/AdguardForWindows/issues/1452

**Comment by planet0** [comment]
Not happening with 1.2.4 beta, I can add to cart fine with Chrome Version 65.0.3325.181 (Official Build) (64-bit). Resolved?

**Comment by ameshkov** [comment]
Yeah, duplicate of #172
