### ISSUE TITLE
High CPU load while downloading a file

### ISSUE THREAD

**Issue by simonrosted** [AdguardTeam/AdguardForMac#168]
_macOS: 10.12.2
AdGuard: 1.4.0
Filters: English, Spyware, Social Media, Annoyances, Adblock Removal Warning List, Schacks Adblock Plus.
Browser: Chrome 57.0.2979.0 dev
Antivirus: Sophos Home 1.2.2_

While downloading a file using Chrome (i've only tested Chrome so far) i always get an abnormally high CPU load.
![screen shot 2017-01-10 at 11 18 34](https://cloud.githubusercontent.com/assets/8746591/22108211/4168abe6-de52-11e6-9727-1c131e81f585.png)

**Comment by zebrum** [comment]
@simonrosted it is absolutely normal behavior because all traffic goes through Adguard.

**Comment by Stillness-2** [comment]
All browser traffic. :)

**Comment by simonrosted** [comment]
Surely that's normal behavior. However, i'm wondering if it'd be possible to come up with a solution that differentiate between a website being downloaded and any other kind of file being downloaded - thereby allowing that 'other kind of file' to bypass the filtering process?

And thank you in advance, for coping with this likely silly question :)

**Comment by ameshkov** [comment]
Guys, I'd just like to point out, that this CPU usage will be mitigated in the future versions, when we finally start using async IO instead of the current approach.
