### ISSUE TITLE
Adding websites to exclusions doesn't work as intended

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#174]
Neither adding a website to whitelist nor adding an exception via User filter helps - Assistant disappears but ads are not shown or shown only partially.

Was tested in Safari on websites like tweakers.net and lenta.ru

Original thread:
https://forum.adguard.com/index.php?threads/whitelist-doesnt-work-in-mac-desktop-app.19358/

**Comment by ameshkov** [comment]
Check the filtering log.

**Comment by ameshkov** [comment]
It's a known issue with requests being blocked in the frames. Happens with Google ads often.
