### ISSUE TITLE
Add "Reset settings..." option

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#180]
Menu -> Advanced -> Reset settings...

Show confirmation dialog before doing the actual reset.
You might need to restart the app to apply new settings properly.

**Comment by Stillness-2** [comment]
ADMC-CR-30

**Comment by vozersky** [comment]
![image](https://user-images.githubusercontent.com/17472907/29666552-66b5fedc-88e1-11e7-99c4-b600a5b91c20.png)

"S" in "Reset settings" looks out of place, it should be capital, like in the other lines. 

The better option is to deal with our capitalization overuse and change everything to lowercase

@vbagirov

**Comment by Stillness-2** [comment]
fixed
