### ISSUE TITLE
Avast Mac Security 2016 compatibility

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#181]
Adguard seems to be blocked by the antivirus, it doesn't work unless you disable the Web shield. The same as with the Sophos software https://github.com/AdguardTeam/AdguardForMac/issues/138

![image](https://cloud.githubusercontent.com/assets/15856304/23456949/41d84a54-fe7e-11e6-9da3-24d05d1aefeb.png)

![image](https://cloud.githubusercontent.com/assets/15856304/23456961/4eb9f592-fe7e-11e6-9f4a-78811fe223c0.png)

Reproduced on MacOS X 10.11.6, Adguard 1.4, the most recent version of Avast for Mac.
Ticket: 1480897 1610420

**Comment by TheHasagi** [comment]
Unable to reproduce it anymore.
