### ISSUE TITLE
Adguard Assistant Causes Youtube Player to not resize

### ISSUE THREAD

**Issue by AtomicCoding** [AdguardTeam/AdguardForMac#182]
**Description**
Hello, there, I am using Adguard for Mac (Obviously) along with its built-in Adguard Assistant. However, recently on youtube, whenever playing a video and switching to theater mode or fullscreen or any mode that requires resizing of the play/pause/skip/settings element, it will cause that resizing to not occur. 
**Image**
http://i.imgur.com/E9RVg7M.png
**Some Debug in Inspect**
Uncaught TypeError: Cannot read property 'g' of null
    at E4 (annotations_module.js:3)
    at L6.g.h.Wr (annotations_module.js:542)
    at g.Jf.g.h.V (base.js:4239)
    at im.g.h.V (base.js:4480)
    at k2.g.h.zO (base.js:7048)
    at g.Jf.g.h.V (base.js:4239)
    at g.dl.V (base.js:4325)
    at nZ.g.qv.V (base.js:4811)
    at nZ.g.h.ah (base.js:6624)
    at e3 (base.js:4067)
E4 @ annotations_module.js:3
g.h.Wr @ annotations_module.js:542
g.h.V @ base.js:4239
g.h.V @ base.js:4480
g.h.zO @ base.js:7048
g.h.V @ base.js:4239
g.dl.V @ base.js:4325
g.qv.V @ base.js:4811
g.h.ah @ base.js:6624
e3 @ base.js:4067
g.h.tL @ base.js:7049
0.js:102 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined
    at 0.js:102
    at dispatch (0.js:11)
    at g.handle (0.js:11)
(anonymous) @ 0.js:102
dispatch @ 0.js:11
g.handle @ 0.js:11
annotations_module.js:3 Uncaught TypeError: Cannot read property 'g' of null
    at E4 (annotations_module.js:3)
    at L6.g.h.Wr (annotations_module.js:542)
    at g.Jf.g.h.V (base.js:4239)
    at im.g.h.V (base.js:4480)
    at k2.g.h.zO (base.js:7048)
    at g.Jf.g.h.V (base.js:4239)
    at g.dl.V (base.js:4325)
    at nZ.g.qv.V (base.js:4811)
    at nZ.g.h.ah (base.js:6624)
    at k (base.js:512)
E4 @ annotations_module.js:3
g.h.Wr @ annotations_module.js:542
g.h.V @ base.js:4239
g.h.V @ base.js:4480
g.h.zO @ base.js:7048
g.h.V @ base.js:4239
g.dl.V @ base.js:4325
g.qv.V @ base.js:4811
g.h.ah @ base.js:6624
k @ base.js:512

**Comment by ameshkov** [comment]
Assistant can be updated on its own, so we'll try to solve the issue asap.

**Comment by ameshkov** [comment]
@AtomicCoders do you have this issue in some specific browser only?

**Comment by AtomicCoders** [comment]
I tested it in Safari, everything seemed fine. But, it's probably because Safari uses some alternate video player that includes airplay and picture-in-picture. But this does still occur in Chrome and most likely other browsers.

**Comment by ameshkov** [comment]
@AtomicCoding sorry for the late reply, what's the exact Chrome version and what extension do you have installed?

For some reason, I cannot reproduce it in any Chrome version (beta/stable/canary)

**Comment by AtomicCoding** [comment]
For some reason, this no longer occurs in the latest version of Google Chrome. Or really at all, I don't know what happened. Sorry for opening this only to close it! ):

**Comment by ameshkov** [comment]
No worries, feel free to contact us:)
