### ISSUE TITLE
Calendar application - can't add account

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForMac#185]
Can't add an account to Calendar application when Adguard is running. Everything is fine after disabling Adguard.

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/24065458/d2191894-0b73-11e7-91b7-d85b84bf2b9b.png)

</details>

Ticket ID: 1208287

**Comment by Alex-302** [comment]
Not reproduced. Is it caused by filters?

**Comment by vozersky** [comment]
reproduced

**Comment by Stillness-2** [comment]
May be related issue #159

**Comment by vozersky** [comment]
@KozelElena 

For now, please go ahead and add domain `gil.apple.com` into HTTPS filtering exclusions list:
Press`Exclusions...` here:
![temp](https://cloud.githubusercontent.com/assets/12689/22549260/8559c07e-e95b-11e6-98d4-c68558757c18.png)

It will be added for everyone in the next build.
