### ISSUE TITLE
Rename "allow useful ads" to "Allow search ads and websites' self-promotion"

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#187]
Just like here:
https://github.com/AdguardTeam/AdguardForWindows/issues/1620

**Comment by vozersky** [comment]
it's still called "useful ads" in 1.5.0 

![image](https://user-images.githubusercontent.com/17472907/29666435-f6738f68-88e0-11e7-8685-48bad0302dc8.png)

**Comment by Stillness-2** [comment]
At this moment i can't update Russian localization. Onesky returns to me not translated values for those fields. :(

**Comment by vbagirov** [comment]
I have fixed both EN and RU versions of these phrases in OneSky.

**Comment by Stillness-2** [comment]
fixed
