### ISSUE TITLE
Enhance idea

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdguardForMac#192]
Add ability search engine result block .

**Comment by vozersky** [comment]
@Chamiu what kind of results? like not safe for kids?

**Comment by Chamiu** [comment]
@vozersky SEO poisoning and not usefull domains.

**Comment by ameshkov** [comment]
@Chamiu could you please explain it in detail? It's just currently it sounds like you want us to moderate search engine results.

**Comment by vozersky** [comment]
obsolete
