### ISSUE TITLE
Increase range of the $$ rules

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#196]
https://github.com/AdguardTeam/AdguardForWindows/issues/1464

**Comment by Stillness-2** [comment]
ADMC-CR-27

**Comment by ameshkov** [comment]
Does not work on 
```
view-source:https://web.archive.org/web/20170716104950/http://www.mathwarehouse.com/
```

Trying this rule:
`web.archive.org$$script[tag-content="admrlPreviewEngage"][max-length="60000"]`

Trying to edit this rule afterward breaks the filters editor.
