### ISSUE TITLE
Trouble connecting to Google Docs, Sheets, Presentations

### ISSUE THREAD

**Issue by Rediwed** [AdguardTeam/AdguardForMac#197]
Hi!

I noticed that, while running Adguard 1.4.1 (beta) there's a lot of issues when trying to edit a Google document, sheet or presentation. The website often get's stuck on 'Reconnecting' (initial page load works perfectly, and I can't make any changes until i've reloaded the page a couple (usually 6-8 does the trick) of times.

Disabling adguard makes all the problems go away.

I tried to exclude the google domains, but that doesn't work (probably, the webapp connects to other domain/ip's that I don't know off).

Thank in forward,

Rediwed.

**Comment by Alex-302** [comment]
@Rediwed are they work when you disable all filters?

**Comment by Rediwed** [comment]
@Alex-302 Yeah, when i disable filters everything works normally again!

**Comment by Alex-302** [comment]
@Rediwed which filters are you using?

**Comment by Rediwed** [comment]
@Alex-302 all of them 😂
http://i.imgur.com/nxNyhAC.png
http://i.imgur.com/74Zb44Y.png

**Comment by Alex-302** [comment]
@Rediwed 

please, disable these filters and check again
<details>

![image](http://i.imgur.com/nxNyhAC.png)
</details>
It the problem will gone, enable filters one by one with checking, and write the filter(s), which breaks editing.

**Comment by vozersky** [comment]
Can't reproduce :( 
Anything in UserFilter?

**Comment by DenLeo** [comment]
UserFilter: @@//www.google.ru^$document     ?

**Comment by DenLeo** [comment]
I have the same problem. If you restart the browser Chrome and open Google documents, the problem appears again. I think the problem with the filter Tracking filter rules statistics.I reinstalled Adguard. Left only the filter Tracking filter rules statistics.

**Comment by vozersky** [comment]
obsolete
