### ISSUE TITLE
Can't log into internet accounts - connection insecure issue.

### ISSUE THREAD

**Issue by KozelElena** [AdguardTeam/AdguardForMac#199]
Something similar to #185 
Caused not by filters and works only after disabling Ad Blocker, Privacy Protection, and Browsing Security. Leaving even one of them disabled fails the try.

Screenshots:

<details>

![image](https://cloud.githubusercontent.com/assets/17320558/25660277/3211e176-3014-11e7-95dc-4123acc0532c.png)

</details>

Ticket ID:1175327

**Comment by KozelElena** [comment]
Our customer commented additionally:

"Further problems with AdGuard which are probably related.
After refreshing Firefox, I can’t log into www.google.com <http://www.google.com/> or yahoo to use search engine and get the following screen.

If I turn AdGuard Off, I can log in just fine. 
After turning AdGuard back on, I next time I try to log into www.google.com <http://www.google.com/> ,I can. This also seems to apply to at least yahoo and probably to other search engines under firefox as well.
Note that I still can’t use google to search other locations using google search engine.
This problem does not appear to occur using Safari. I have iMac i3 using latest operating system (Sierra)."

**Comment by ameshkov** [comment]
@KozelElena something is wrong with AG certificate, don't you have an instruction on how to reinstall it in case of Mac?

**Comment by vozersky** [comment]
can't rep
@zebrum please assist with the certificate reinstall

**Comment by vozersky** [comment]
reproduced

**Comment by zebrum** [comment]
Sent an instruction how to reinstall the certificate to user.

**Comment by vozersky** [comment]
@zebrum why not to post it here as well?

**Comment by zebrum** [comment]
@vozersky sure!

For Keychain Access :
Please, in Items search for Adguard Personal CA - do the right click - Delete Adguard Personal CA.

For Firefox:
Open Settings - Preferences - Advanced - Certificates - Authorities - Adguard Personal CA - Delete.

And then reboot your Mac, please.

In case the certificate won't work after that - you can also import it manually.
Open Finder, press CMD+Shift+G and put /Library/Application Support/com.adguard.Adguard/NfApiConfiguration/SSL
Then double-click on Adguard Personal CA.cer and it will prompt to install it manually.

**Comment by vozersky** [comment]
Certificate reinstall doesn't help.
If you disable https filtering in Adguard, it works just fine.

**Comment by Stillness-2** [comment]
May be related issue #159

**Comment by vozersky** [comment]
Same as #185 

@KozelElena 

For now, please go ahead and add domain `gil.apple.com` into HTTPS filtering exclusions list:
Press`Exclusions...` here:
![temp](https://cloud.githubusercontent.com/assets/12689/22549260/8559c07e-e95b-11e6-98d4-c68558757c18.png)

It will be added for everyone in the next build.

**Comment by zebrum** [comment]
wrote to users from this issue and #185
