### ISSUE TITLE
Handle "strict-dynamic" CSP properly

### ISSUE THREAD

**Issue by AtomicCoding** [AdguardTeam/AdguardForMac#203]
Randomly, when opening up the console on google.com, I get this error message:
notifications.google.com/u/0/widget?sourceid=1&hl=en&origin=https%3A%2F%2Fw…6115396128&parent=https%3A%2F%2Fwww.google.com&pfname=&rpctoken=37866424:1 Refused to load the script 'https://local.adguard.com/adguard-ajax-api/injections/userscripts/Web%20of%20Trust?ts=1496016297.791549' because it violates the following Content Security Policy directive: "script-src https: 'unsafe-eval' 'strict-dynamic' 'unsafe-inline' http: 'nonce-+v6/DBYFgJ4dsYxUMUgvkpkT7PE' 'nonce-43AF551226E445EE90F9F44FC7AFFE41' local.adguard.com". 'strict-dynamic' is present, so host-based whitelisting is disabled.
And quick recommendation: Avoid using document.write()
(This is in Adguard 1.4.1)

**Comment by ameshkov** [comment]
This reminds me of another issue, which should be fixed in the Mac version:
https://github.com/AdguardTeam/AdguardForWindows/issues/1678

**Comment by ameshkov** [comment]
@Stillness-2 regarding Dropbox, please note that they send **TWO** CSP headers in the response.

**Comment by Stillness-2** [comment]
ADMC-CR-18
