### ISSUE TITLE
https filtering & Adguard Assistant: show original TLS certificate

### ISSUE THREAD

**Issue by JayBrown** [AdguardTeam/AdguardForMac#204]
I know you're still working on https filtering, so maybe you might be willing to extend the Adguard Assistant, namely add a field "Show original TLS certificate". With TLS connections, if you click on the lock sign in the browser URL field, it only shows you the local Adguard certificate, the one sitting between your browser and the website the user is visiting, but I assume that some users (like me) would sometimes like to have a look at a website's original TLS certificate. Currently that's only possible by disabling Adguard altogether (or at least by disabling Adguard's https filtering), so an option to inspect the original certificate with Adguard enabled would be really nice.

**Comment by vozersky** [comment]
https://github.com/AdguardTeam/AdguardForMac/issues/113

**Comment by ameshkov** [comment]
Closed as dup of #113 

The proposed feature makes perfect sense, we'd better take this into account while working on the new network library.
