### ISSUE TITLE
Wrong date of establishment in "About Adguard" section

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForMac#205]
Should be 2009. 2008 at the moment.

<details><summary>Screenshot:</summary>

![screen shot 2017-05-31 at 19 30 48](https://cloud.githubusercontent.com/assets/28726429/26642837/f2dbd39c-4637-11e7-9c3c-54a8718aa461.png)

</details>

**Comment by ameshkov** [comment]
Don't forget to update ALL the languages
