### ISSUE TITLE
Visual Bug with Adguard Assistant

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#207]
Discovered this by accident when I changed my mind to create an exception.

macOS Version 10.12.5 (16F73)
Safari Version 10.1.1 (12603.2.4)
Adguard Version 1.4.1 Beta

**Steps to Reproduce:**
1. Visit a webpage with Adguard Assistant visible
2. Click the Adguard Assistant icon in Safari
3. Click 'Add Exception'
4. Click 'Advanced Settings...'
5. Click on the X on the top right
6. Click 'Add Exception' again
7. Click 'Advanced Settings...' again

**Excpected Behaviour:**
You can see the Exception rule properties and the Add exception button.
<img width="578" alt="adguard-assistant-expected" src="https://user-images.githubusercontent.com/29296810/26960921-3a7a68de-4d1e-11e7-9ee7-e50b2cb10d6a.png">

**Actual Behaviour:**
The properties and button are cut off from view.
<img width="576" alt="adguard-assistant-actual" src="https://user-images.githubusercontent.com/29296810/26960920-39f04cf8-4d1e-11e7-86c6-e8726a69b4d4.png">

**Comment by vozersky** [comment]
Hi! Thank you for reporting it.

There is a new version of [Adguard Assistant](https://github.com/AdguardTeam/AdguardAssistant) coming soon. It has been completely reworked, so this bug will not be releveant anymore: 

![image](https://user-images.githubusercontent.com/17472907/27138224-afa2ab7c-5128-11e7-8268-ee3518d5e5da.png)

Unfortunately it is only available in Windows app beta at the moment

**Comment by planet0** [comment]
@vozersky Thanks for letting me know, I'm looking forward to seeing the new version on macOS soon.

**Comment by planet0** [comment]
@vozersky This bug is still present as of 1.5.4 beta. Any chances of seeing the new AdGuard Assistant on macOS?

**Comment by vozersky** [comment]
@planet0 yeah, sadly, it takes much more time then I expected to introduce new Assistant to Mac version, but it will get there
