### ISSUE TITLE
Ads disappears only after several seconds after the page is loaded

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForMac#208]
Ads disappears only after several seconds after the page is loaded
The issue persists only in Google Chrome, also on some other site. The most visible on Yandex weather

here is the video: https://www.dropbox.com/s/xdpw21j6yag3at5/adguard_pogoda_yandex_ru.mov?dl=0%20%3Chttps://www.dropbox.com/s/xdpw21j6yag3at5/adguard_pogoda_yandex_ru.mov?dl=0%3E

[debug (38).txt](https://github.com/AdguardTeam/AdguardForMac/files/1066602/debug.38.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForMac/files/1066603/state.txt)
Customer ID: 188003

**Comment by vozersky** [comment]
@Michael23456 filtering related -> always goes to Adguard Filters first

**Comment by Juev** [comment]
Hello, what does it mean?

**Comment by vozersky** [comment]
@Juev Денис, здравствуйте! К сожалению, на этой странице по-другому заблокировать не получится :(

**Comment by Juev** [comment]
Владимир, мне несколько не понятно, что вообще происходит?
Если правильно понимаю, блокировка должна проходить на этапе прохождения страницы через вашу программу, и уже результат обработки отображается браузером. 
Из-за чего происходит мигание на странице уже после ее отображения? 
И подобное поведение фиксируется только в Хроме, в Сафари, к примеру, подобной проблемы нет.

И да, такое же мигание фиксируется и на других страницах.

**Comment by Alex-302** [comment]
Яндекс использует способ восстановления рекламы.
Проверьте такие правила в пользовательском фильтре:
```
yandex.ru$$div[wildcard="*//clck.yandex.*redir*data-bem*"][parent-elements="div"][parent-search-level="2"][max-length="20000"]
://yandex.ru/pogoda/cry/*^|$replace=/detectContext/detectContext__/,important
```

**Comment by Juev** [comment]
Добрый вечер.

Добавил в пользовательский фильтр, не помогло.

Thanks,
Denis

**Comment by Alex-302** [comment]
@Juev 
давайте переместимся в более подходящий репозиторий:
https://github.com/AdguardTeam/AdguardFilters/issues/5332

**Comment by Stillness-2** [comment]
Это относится вот к этому #203
