### ISSUE TITLE
Allow to launch Adguard from external drive

### ISSUE THREAD

**Issue by Michael23456** [AdguardTeam/AdguardForMac#210]
error while launching Adguard
The customer has Mac OS installed on an external drive(HDD is not working) when launching the Adguard app the following error is shown:
<details>

![image](https://user-images.githubusercontent.com/25711093/27263061-90a7ae0c-546b-11e7-88a8-a41a346d656c.png)

</details>
But the app is already installed to the "Applications" folder.

Mac OS 10.12.5

CustomerID:1576791

**Comment by vozersky** [comment]
one tiny detail: "У меня MacOS установлена на карту памяти (жёсткий диск неисправен)."

**Comment by ameshkov** [comment]
@Stillness-2 can we fix it or is it by design?

**Comment by vozersky** [comment]
@Michael23456 Not going to work from sd card at the moment, it's by design we check the location for "removable" and "read only."

we might change this behaviour in future, let's keep it as a feature request

**Comment by Stillness-2** [comment]
Check this build https://www.dropbox.com/s/l71rtrxvdw0r223/Adguard-1.4.1.release.dmg?dl=1

**Comment by evgeniy-ADG** [comment]
Sent to the customer.

**Comment by Stillness-2** [comment]
@evgeniy-ADG We need confirmation from user, that test build works correctly.

**Comment by Stillness-2** [comment]
works
