### ISSUE TITLE
www.imore.com - some elements are not working with Adguard on

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardForMac#212]
https://www.imore.com 
issues working with Adguard: some essential elements can’t be
clicked. Examples are the Menu on the top left
corner & at the bottom of the page the “Show Me More” button.
It’s worth mentioning that this goes for Adguard on iOS as well.

Screen recording of the issue: https://www.dropbox.com/s/2v5bn3kz0ynipxi/Screen_recording_imore.mov?dl=0

Ticket ID: 1010685

**Comment by vozersky** [comment]
@kbahlyk filtering issues are reported here: https://github.com/AdguardTeam/AdguardFilters/issues

some rule in English filter breaks it
