### ISSUE TITLE
"System Extension Blocked" issue on macOS 10.13 (High Sierra)

### ISSUE THREAD

**Issue by kbahlyk** [AdguardTeam/AdguardForMac#217]
What should we do:
https://github.com/AdguardTeam/AdguardForMac/issues/217#issuecomment-322421670

Original text:
<details>
"Service for filtering network traffic" issue on macOS 10.13 (High Sierra)
Reinstallation doesn't help.
Log files in the ticket.
Ticket ID: 1572788
</detail>

**Comment by vozersky** [comment]
[Archive.zip](https://github.com/AdguardTeam/AdguardForMac/files/1135253/Archive.zip)

**Comment by veronikasav** [comment]
Another log file below:

[state.txt](https://github.com/AdguardTeam/AdguardForMac/files/1179606/state.txt)
[debug .txt](https://github.com/AdguardTeam/AdguardForMac/files/1179607/debug.txt)


Ticket ID: 1600180

**Comment by veronikasav** [comment]
One more log file:

[debug.txt](https://github.com/AdguardTeam/AdguardForMac/files/1215225/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForMac/files/1215226/state.txt)

Ticket ID: 1610450

**Comment by vozersky** [comment]
@veronikasav 

New OS blocks kernel extensions by default.
On the first launch you are getting a dialogue window about it.

Please tell users to try starting Adguard and then open "Security and Privacy" ->"General" tab. There should be a notification about Adguard app, you can unlock the page and click "allow".

pls let me no if that was actually the issue

**Comment by ameshkov** [comment]
Guys, this is actually a major issue, AG should make this process easier for users instead of this:

![screen shot 2017-08-10 at 18 29 51](https://user-images.githubusercontent.com/5947035/29181005-4188645e-7e02-11e7-844a-44ef4ef12484.png)
![screen shot 2017-08-10 at 18 30 10](https://user-images.githubusercontent.com/5947035/29181004-4186836e-7e02-11e7-9091-1b8eafda855d.png)

**Comment by ameshkov** [comment]
Detailed howtos:
http://support.eset.com/kb6512/
https://www.obdev.at/products/littlesnitch/high-sierra-notes.html

Important note:
> It's only possible to enable the system extension in the 30 minutes following the installation. A new installation can be run to reset this timer.

**Comment by ameshkov** [comment]
Mockups (just mock-ups, not a design, screenshots should be replaced there):
https://app.moqups.com/ameshkov/6JGYGKjD5J/view/page/aa9df7b72

### Step 1: After the initial installation wizard we should show a warning screen
![adguard for mac - system extension blocked moqups 2017-08-15 12-19-57](https://user-images.githubusercontent.com/5947035/29309860-2019cd7a-81b4-11e7-80d6-a08eed9aaac4.png)

When a user clicks "Continue", we should install the system extension.

### Step 2: After macOS indicates, that user should allow system extension
![adguard for mac - system extension blocked moqups 2017-08-15 12-20-11](https://user-images.githubusercontent.com/5947035/29309866-239b8d08-81b4-11e7-9790-f8e11dd8814f.png)

**Comment by Stillness-2** [comment]
ADMC-CR-32

**Comment by wd** [comment]
Any one meet this problem, if you found the  'allow' button is useless, check this issue  https://github.com/tekezo/Karabiner-Elements/issues/1017 , for me, I need to quite karabiner to click that button..
