### ISSUE TITLE
Adguard Crashes Due to Uncaught Exception `NSUnknownKeyException`

### ISSUE THREAD

**Issue by sanssecours** [AdguardTeam/AdguardForMac#219]
# Steps to Reproduce

1. Open Adguard
2. Adguard Crashes

The application worked well before, but since I decided to deactivate and activate Adguard – via the menu bar item – about one hour ago, it crashes constantly.

# Expected Behavior

Adguard works :o)

# Actual Behavior

The program crashes every time I open it. I already tried removing Adguard’s configuration files, which unfortunately did not help.

# Customer ID 

My purchase ID is 1005484.

# Environment

OS: macOS 10.12.6
Adguard Version: 1.4.1

# Crash Reports

- [Adguard_2017-07-21-182545_Apfelmus.crash.txt](https://github.com/AdguardTeam/AdguardForMac/files/1166172/Adguard_2017-07-21-182545_Apfelmus.crash.txt)
- [Adguard_2017-07-21-182723_Apfelmus.crash.txt](https://github.com/AdguardTeam/AdguardForMac/files/1166171/Adguard_2017-07-21-182723_Apfelmus.crash.txt)
- [Adguard_2017-07-21-183749_Apfelmus.crash.txt](https://github.com/AdguardTeam/AdguardForMac/files/1166170/Adguard_2017-07-21-183749_Apfelmus.crash.txt)
- [Adguard_2017-07-21-183816_Apfelmus.crash.txt](https://github.com/AdguardTeam/AdguardForMac/files/1166168/Adguard_2017-07-21-183816_Apfelmus.crash.txt)
- [Adguard_2017-07-21-183818_Apfelmus.crash.txt](https://github.com/AdguardTeam/AdguardForMac/files/1166169/Adguard_2017-07-21-183818_Apfelmus.crash.txt)

**Comment by vozersky** [comment]
@sanssecours Thanks for the report! We are fixing the issue atm.

**Comment by vozersky** [comment]
Solved
