### ISSUE TITLE
Adguard Crashes when receives new metadata from backend

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForMac#220]
Details in #219

**Comment by ameshkov** [comment]
You should also change the filters URL (they are moved to another location -- `mac_v2`

**Comment by Stillness-2** [comment]
ADMC-CR-31

**Comment by ameshkov** [comment]
Let's close it once pull request is merged

**Comment by Stillness-2** [comment]
This issue was merged with master before bt :)
