### ISSUE TITLE
Failed to verify server certificate when adding google account to mail.app

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/AdguardForMac#221]
### Steps to reproduce

1. Have adguard.app running
2. Remove any google accounts if you have from System Preferences -> Internet Accounts
3. Open mail.app, preferences, add new google account
4. Window slides in to load OAuth page to enter Google username and password.

### Expected behavior

OAuth page should load

### Actual behavior

Error appears that server certificate is invalid.

<details><summary>Screenshot:</summary>

![2017-07-31_15-46-37](https://user-images.githubusercontent.com/739119/28778356-90d2266a-7607-11e7-9130-4d67d9c3afdb.png)
![2017-07-31_15-46-27](https://user-images.githubusercontent.com/739119/28778360-93972abc-7607-11e7-967c-6c9424d903ee.png)
![2017-07-31_15-43-30](https://user-images.githubusercontent.com/739119/28778361-954fca4e-7607-11e7-9d60-805bf80fe596.png)

</details>

### Customer ID 

1501720

### Your environment

* Environment name and version: OSX 10.12.6
* Any specific potentially conflicting software installed: None.

**Comment by Stillness-2** [comment]
What happen if you add `gil.apple.com` in ssl exception list? (#159)

**Comment by Stillness-2** [comment]
>Why was #159 closed anyway?

Because this is issue for next milestone (next update) and it is solved.

**Comment by hmage** [comment]
Alright. Though default search on github is for open issues. Maybe it's better to close issues after next release is out? Could be useful to avoid duplicate issues since I've searched for it before opening this issue.
