### ISSUE TITLE
Adguard prevents the loading of embedded block at wunderground.com

### ISSUE THREAD

**Issue by altokarev** [AdguardTeam/AdguardForMac#222]
### Steps to reproduce

1. Proceed to https://www.wunderground.com
2. Follow the `Full Forecast` button
3. Look at `10-Day Weather Forecast` block

### Expected behavior
`10-Day Weather Forecast` should load [well](https://user-images.githubusercontent.com/28726429/28833725-e19193ce-76e8-11e7-8941-1b7da242f922.png)

### Actual behavior
Adguard with `Browsing Security` option `ON` prevents the loading of embedded block at wunderground.com

<details><summary>Screenshot:</summary>

![screen shot 2017-08-01 at 18 38 59](https://user-images.githubusercontent.com/28726429/28833751-f96aa03a-76e8-11e7-80f5-0e90b878c7c3.png)

</details>

### Your environment

* macOS: 10.12.6
* Adguard: 1.4.1
* Environment name and version:  Chrome 59.0.3071.115 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: nothing

**Comment by Stillness-2** [comment]
pull-requests/16

**Comment by BioBoostedOne** [comment]
I have been having this same problem and behavior for awhile on Safari as well.

**Comment by altokarev** [comment]
@BioBoostedOne Seems it's OK for me on Safari 11 with AdGuard for Mac 1.5.0.

Which filters do you use?

**Comment by BioBoostedOne** [comment]
@altokarev 
Okay, I should've double checked before posting.  It seems within the last few weeks they completely revamped their website.  I don't see the problem anymore.
