### ISSUE TITLE
Unusual delayed boot with Adguard and macOS 10.13 Beta

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#229]
Reporting this as this issue isn't present with Adguard and macOS Sierra, and is only introduced when installing with macOS High Sierra.

### Steps to reproduce

1. Note the time it takes to boot into macOS usually.
2. Install Adguard on macOS High Sierra beta.
3. Allow the extension in System Preferences
4. Reboot macOS
5. Notice the progress bar stall for 10 seconds or so

### Expected behavior
macOS boots without a large delay, as with Adguard and macOS Sierra 10.12.

### Actual behavior
macOS stalls for 10 seconds or so about 70% of the way when looking at the progress bar, with Adguard and macOS High Sierra 10.13 Beta.

### Customer ID 
1552859

### Your environment
* Environment name and version:
macOS High Sierra 10.13 Beta (17A358a)
Adguard for Mac 1.5.0 beta

* Any specific potentially conflicting software installed:
None

**Comment by planet0** [comment]
I noticed this continuing to occur after quitting and deleting the Adguard app — It seems that the kext is still loaded into macOS and System Integrity Protection prevents the user from being able to delete it.

Is there a way to remove the Adguard kext from the system once Adguard.app is deleted or moved to trash?

**Comment by ameshkov** [comment]
Let's wait for @Stillness-2 to comment on this. Might be caused by this new Kext validation process.

**Comment by planet0** [comment]
Not a problem, will wait. Was able to remove the kext in Sierra and below, seems to be related to what you mention. It is possible to disable SIP and then delete the kext, but the whitelist for validation still keeps the allowed decision permanently anyway, so it isn’t an ideal workaround.

**Comment by ameshkov** [comment]
> but the whitelist for validation still keeps the allowed decision permanently anyway

Oh, reverting this is really tiresome. 

Copy/pasted, seem to be working:
<details>

```
I want to revert the kext loading system policy state in order to test my application behavior when my kext is blocked.
I succeed to remove my identifier from the allowed kext list by the following procedure.
 
 
1. The system policy is saved into /private/var/db/SystemPolicyConfiguration/KextPolicy (sqlite3 file)
  To modify the file, boot macOS in Recovery Mode.
 
 
2. Open Terminal in Recovery Mode, then open the file by this command.
 
 
    sqlite3 /Volumes/<YOUR VOLUME NAME>/private/var/db/SystemPolicyConfiguration/KextPolicy
 
 
3. Confirm contents by these queries.
 
 
    sqlite> .tables
    sqlite> SELECT * FROM kext_policy;
    sqlite> SELECT * FROM kext_load_history_v3;
 
 
4. Delete policies by these queries. (Replace 'G43BCU2T37' with your team_id)
 
 
    sqlite> DELETE FROM kext_policy WHERE team_id = 'G43BCU2T37';
    sqlite> DELETE FROM kext_load_history_v3 WHERE team_id = 'G43BCU2T37';
 
5. Exit sqlite by control+D. Then restart macOS.
```
<details>

**Comment by planet0** [comment]
I hope there will be an easier method in future in regards to the whitelist in High Sierra (like a terminal command without recovery mode) since it’s very easy to press a button to add it to the list itself. Also for removing the kext, without having to disable SIP, like Apple providing the ability for the developer to use something to remove it just the same as adding it during install.

**Comment by ameshkov** [comment]
> since it’s very easy to press a button to add it to the list itself

It'd disagree here, you should do quite a lot to approve a kext: open settings, unlock settings and only then you can approve it.

**Comment by planet0** [comment]
That’s true @ameshkov, my mistake. Perhaps there could be a similar system like in Privacy settings (eg. apps that can use privacy, accessibility, etc.) that can show a list of approved kexts that has been allowed and the ability to remove it inside System Preferences once unlocked.

**Comment by vozersky** [comment]
Could not really see the difference, with kext or without
