### ISSUE TITLE
Changing name Adguard to AdGuard

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForMac#231]

**Comment by planet0** [comment]
@Stillness-2, 'Adguard' is still visible in a few places as of 1.5.0 RC in case you weren't aware (aside from the DMG name), see screenshots below.

<img width="358" alt="screen shot 2017-09-20 at 6 18 31 am" src="https://user-images.githubusercontent.com/29296810/30613587-f9d6b126-9dcb-11e7-908c-6f0f83acce08.png">

<img width="555" alt="screen shot 2017-09-20 at 6 19 35 am" src="https://user-images.githubusercontent.com/29296810/30613588-f9e0b054-9dcb-11e7-94b0-bf082d226c1f.png">

**Comment by ameshkov** [comment]
Changing certificate name would be too painful
