### ISSUE TITLE
Integrate with the CoreLibs

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#232]
Ask @sfionov for instructions.

**Comment by tomiams** [comment]
Is there a due date for this crucial task?

**Comment by ameshkov** [comment]
October is the current due date. The task is almost done, but thanks to Mojave release we had to shift focus a bit and spend extra weeks on it.

**Comment by Stillness-2** [comment]
We continue work on this in separated issues.
