### ISSUE TITLE
"Shadowsocks-R" and AdGuard

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForMac#240]
In China, we must use Google, Twitter with proxy. The software which named
"shadowsocks-R" can help us to realize this function. Network traffic will
be controlled by this software. When the software starts
running, AdGuard(1.5.0(402)) is efficient, but the other version of
the AdGuard
can't do.

### Steps to reproduce
This is the software:ShadowsocksX-NG-R8.dmg (8,763 K)

<https://mail.google.com/mail/u/0/?ui=2&ik=dac3b9406f&view=att&th=15eb9a3f884ded5e&attid=0.1&disp=safe&realattid=f_j80bq23f0&zw>

1. Install and open it.
2. Then do it.
3. import config with this export.json (2 K)

<https://mail.google.com/mail/u/0/?ui=2&ik=dac3b9406f&view=att&th=15eb9bce4cb83c54&attid=0.1&disp=safe&realattid=f_j80cp8rm0&zw>
​
4. update list

Then, you can try to visit Google, and check adguard is efficient or not in
different versions.

<details><summary>Screenshot:</summary>

<img width="452" alt="screen shot 2017-09-29 at 9 58 28 am" src="https://user-images.githubusercontent.com/27292111/31004462-3516d2f6-a4fd-11e7-88a8-a7f9a1e09266.png">
<img width="494" alt="screen shot 2017-09-29 at 9 58 46 am" src="https://user-images.githubusercontent.com/27292111/31004458-34fd4f0c-a4fd-11e7-97c2-fa63f34484dc.png">
<img width="1109" alt="screen shot 2017-09-29 at 9 58 56 am" src="https://user-images.githubusercontent.com/27292111/31004459-34ff543c-a4fd-11e7-8afe-8daa71e32a42.png">
<img width="690" alt="screen shot 2017-09-29 at 9 59 07 am" src="https://user-images.githubusercontent.com/27292111/31004460-34ff8312-a4fd-11e7-9b2e-644f55c283e5.png">
<img width="1102" alt="screen shot 2017-09-29 at 9 59 16 am" src="https://user-images.githubusercontent.com/27292111/31004461-3504a504-a4fd-11e7-9ca3-770d64beea6b.png">

</details>

### Your environment

[ShadowsocksX-NG-R8.dmg.zip](https://github.com/AdguardTeam/AdguardForMac/files/1343358/ShadowsocksX-NG-R8.dmg.zip)
[export.json.zip](https://github.com/AdguardTeam/AdguardForMac/files/1343357/export.json.zip)

[debug.txt](https://github.com/AdguardTeam/AdguardForMac/files/1343355/debug.txt)
[state.txt](https://github.com/AdguardTeam/AdguardForMac/files/1343354/state.txt)

**Comment by ameshkov** [comment]
So, in v402 we were filtering local connections and that's why it worked okay.
