### ISSUE TITLE
Add Mozilla Developer Edition to the list of filtered apps

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForMac#241]
### Steps to reproduce

1. Download it here: https://www.mozilla.org/en-US/firefox/developer/
2. Install and run Adguard at the same time

### Expected behavior

Ads are blocked.

### Actual behavior

Ads are not blocked. HTTPS certificate is not installed into FF storage.

### Your environment

* Environment name and version: Firefox 57.0b3, Adguard 1.5.0
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by zebrum** [comment]
@Bohdan-SUP check FF is added to filtered apps.

![screenshot 2017-09-29 15 46 39](https://user-images.githubusercontent.com/23637588/31016478-8cc81dea-a52d-11e7-85ac-5acce8076fb5.png)

**Comment by Bohdan-SUP** [comment]
Yup, that fixed it, thanks!
Why wasn't it there automatically, though? We should add it to a default list then.

**Comment by ameshkov** [comment]
It should be in the default list indeed
