### ISSUE TITLE
Can't log in to icloud.com

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForMac#242]
### Steps to reproduce

Try to log in to your account on icloud.com 

### Actual behavior

<details><summary>Screenshot:</summary>

![mqxf03](https://user-images.githubusercontent.com/23637588/31183002-09cebb56-a92e-11e7-8489-e2c425014b7d.png)

</details>

There is no blocked domains in filtering log. Disabling all filters doesn't help.

forum [thread](https://forum.adguard.com/index.php?threads/problems-getting-icloud-com-to-load.24321)
### Your environment

* Environment name and version: Safari 11, High Sierra, AdGuard 1.5.0

**Comment by zebrum** [comment]
17.16 [debug (3).txt.zip](https://github.com/AdguardTeam/AdguardForMac/files/1356322/debug.3.txt.zip)

**Comment by vozersky** [comment]
Can't reproduce on my machine :/

**Comment by zebrum** [comment]
@vozersky have you been updated you mac to high sierra? it's reproducible there.

**Comment by Bohdan-SUP** [comment]
I've got High Sierra and can't reproduce either.

**Comment by Bubu92** [comment]
I spent an hour with Apple support on this matter before figuring out that Adguard was blocking the login access.

In a guest environment iCloud login works perfectly. With Adguard it does not. If Adguard is disabled then the login is possible.

Also, one strange thing. With Apple we also tried to login to iCloud.com on  iPad and iPhone with Adguard iOS app enabled. No issue at all.

It seems the concern is only with Adguard desktop version only.

**Comment by BooBerry** [comment]
Are you still using these filter lists?

English, Spyware, French, Experimental, Safari, EasyPrivacy, Fanboy's Annoyances, Icelandic ABP, Adblock Warning Removal, Anti-Adblock Killer | Reek, I don't care about cookies, Malware domains, Peter Lowe's list, Prebake, Spam 404, BarbBlock.

**Comment by Bubu92** [comment]
Yes, I keep my signature updated to make sure you guys get the right info.

**Comment by ameshkov** [comment]
Just in case, does it help to add `icloud.com` to the HTTPS exclusions list?

**Comment by Bubu92** [comment]
@ameshkov You made my day! Simple, obvious and effective solution! 👍
