### ISSUE TITLE
YouTube ads are not blocked

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForMac#248]
### Steps to reproduce

1. open any browser
2. go to YouTube.com

Can't reproduce steadily, but @zebrum was able to with a VPN.

### Expected behavior

Ads should be blocked

### Actual behavior

Pre-video ads are shown :(

### Customer ID 
1643078, will add more

### Your environment

* Environment name and version: Adguard 1.5.0; HTTPS filtering enabled, ofc

**Comment by evgeniy-ADG** [comment]
@ameshkov @Stillness-2 do you have any updates on this?
There's a couple of other reports on youtube on macOS in the Filters repo.

**Comment by veronikasav** [comment]
Logs
[state.txt](https://github.com/AdguardTeam/AdguardForMac/files/1443910/state.txt)
[debug.txt](https://github.com/AdguardTeam/AdguardForMac/files/1443911/debug.txt)

Ticket ID: 1654912

**Comment by vozersky** [comment]
i doubt this is a macos app issue though, should we move it to filters?

**Comment by Alex-302** [comment]
Check on your end before it(with UK VPN)

**Comment by ameshkov** [comment]
Will be solved by #263

**Comment by evgeniy-ADG** [comment]
We've gotten several (2 actually, 1713960 is one of them) complaints that the 1.5.3 version does not block ads. I can confirm there's something not right but I can't reproduce it at will.

**Comment by ameshkov** [comment]
Opened a new one:
https://github.com/AdguardTeam/AdguardForMac/issues/270
