### ISSUE TITLE
Consider moving Assistant translucent icon to bottom left window corner instead of bottom right

### ISSUE THREAD

**Issue by GermarisTwo** [AdguardTeam/AdguardForMac#250]
### Steps to reproduce

1. Using Safari 11.0.1 with AdGuard installed
2. In the bottom right corner the translucent AdGuard Assistant Icon appears
3. If a video is playing, this icon interfere wth the full screen button located at the far right end of the video commands bar.
This is very annoying...

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
 Mac OS X El Capitan 10.11.6 - Safari 11.0.1
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
No antiviruses - No firewall

**Comment by Stillness-2** [comment]
@GermarisTwo What if... https://uploads.adguard.com/screencast_2017-11-03_09-57-08.mp4 ?
This is not enough? :)

**Comment by GermarisTwo** [comment]
Yes it is. Thank you very much.
But it was not so easy to find as I used to modify settings by clicking on the AdGuard Icon in the Menu Bar and choose Settings and then Preferences
