### ISSUE TITLE
Update AdGuard for Mac with New AdGuard Features

### ISSUE THREAD

**Issue by AtomicCoding** [AdguardTeam/AdguardForMac#253]
Adguard for Windows just received an update with browser cryptocurrency mining protection and a new AdGuard Assistant. However, these updates are not reflected on Adguard for Mac.

**Comment by vozersky** [comment]
hi
mining protection works on mac version as well, you can check here https://coinhive.com/ (press "start mining")

new assistant is coming to mac as well, unfortunately I can't say when exactly

**Comment by ameshkov** [comment]
@AtomicCoding let me please elaborate a bit on what's going on.

Currently, we are working on a cross-platform single filtering engine (codename [CoreLibs](https://github.com/AdguardTeam/CoreLibs)). We're slowly starting to use it (AG for Android already uses part of it). Once we start using the single engine on all the platforms, it'd be much easier to have the same functionality everywhere.
