### ISSUE TITLE
AdGuard blocks notifications on Yandex mail in a browser tab

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForMac#256]
New mail notifications are blocked in tabs with Yandex mail.

### Steps to reproduce

1. Go to https://mail.yandex.ru
2. Send yourself an email from another account

Video: https://yadi.sk/i/ZN7rkaA53PQkKJ

### Customer ID
1656180 

### Your environment

* Adguard version: AdGuard for Mac 1.5.0
* OS: 1012
* Browser: FF
* Subscriptions: English, Russian, Spyware, Filter unblocking search ads and self-promotion
* DNS: Off

**Comment by zebrum** [comment]
reproduced
originally from here: https://github.com/AdguardTeam/AdguardFilters/issues/7486

**Comment by Stillness-2** [comment]
@zebrum did you test only on Mac?

**Comment by zebrum** [comment]
@Alex-302 said that it's ok on windows.
I turned off all filters and extensions on my side and checked on mac.
