### ISSUE TITLE
AdGuard blocks WebSockets in Firefox on slack.com

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#259]
AdGuard on macOS interferes with Slack WebSockets when using Firefox but not when using Chrome or Safari. This prevents Slack from being usable on Firefox.

### Steps to reproduce

1. Open Firefox
2. Head to slack.com and log in
3. Wait
4. See what's on the screenshot

### Expected behavior

You successfully log in and slack.com is fully operable

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/33113312-7646d8d8-cf60-11e7-9770-9480f5b32ea7.png)

</details>

### Your environment

* Adguard version: AdGuard for Mac 1.5.0, default settings
* Subscriptions: English, Russian, Social media, Annoyances, Safari, Spyware, German
* DNS: Off
* HTTPS: On
* FF Quantum, v 57.0

**Comment by ameshkov** [comment]
There were some general issues with Slack yesterday, I cannot reproduce the issue today

**Comment by evgeniy-ADG** [comment]
I can.

![image](https://user-images.githubusercontent.com/15856304/33128623-bf4d0e5a-cf95-11e7-8706-f6df082cc416.png)

**Comment by ameshkov** [comment]
@zebrum could you please check it?

**Comment by vozersky** [comment]
Yeah, can reproduce even without any filters enabled.

**Comment by ameshkov** [comment]
Weird, I can't, have you tried 1.5.1?

**Comment by vozersky** [comment]
Hmm, I did just now, and it works fine with 1.5.1 beta for me as well.
@evgeniy-ADG could you please confirm? https://uploads.adguard.com/up05_m706r.dmg

**Comment by evgeniy-ADG** [comment]
Works with the beta.

**Comment by Stillness-2** [comment]
related to #256
