### ISSUE TITLE
Notify users when they disable Base filter

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#260]
Some users don't realize how important is English filter for proper filtering. We should immediately show a warning-like red text when a user disables English filter in "Filters" settings tab. It should say "English filter is necessary for quality filtering!" right under the "English filter" heading.

**Comment by ameshkov** [comment]
Wait-wait-wait.

Wouldn't it be better to rename it to something like "Base filter"?

**Comment by vbagirov** [comment]
Weren't we supposed to do the `English filter` --> `Base filter` transition at once everywhere? Or do you think this "rebranding" will be enough to stop users from disabling it?

**Comment by ameshkov** [comment]
Yeah, I am quite sure people disable English filter because they think it is for english websites only.

**Comment by TPS** [comment]
Now that the name is changed to "AdGuard Base filter," could this issue title be updated?  TIA! 🙇🏾‍♂️

**Comment by TPS** [comment]
@zzebrum _IfF_ you're interested, https://github.com/AdguardTeam/AdguardForWindows/issues/2029, https://github.com/AdguardTeam/AdguardForAndroid/issues/1617, https://github.com/AdguardTeam/AdguardBrowserExtension/issues/904, & https://github.com/AdguardTeam/ReportsWebApp/issues/82 need the same renaming. 🙇🏾‍♂️
