### ISSUE TITLE
https://www.finam.ru/ - graph is broken

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#264]
All filters and extensions are disabled. Filter exclusions does not help. It works only when domain is added to HTTPS exclusions.
Originsl issue
https://github.com/AdguardTeam/AdguardFilters/issues/8189
https://www.finam.ru/profile/tovary/brent
User can provide remote access.

**Comment by vozersky** [comment]
reproduced

**Comment by altokarev** [comment]
There is a related report that http://common.ru is broken too.

<summary>Screenshot:</summary>
<details>

![image](https://user-images.githubusercontent.com/28726429/34006247-b3152c78-e10e-11e7-9d79-ca45c6209e92.png)

</details>

**Comment by ameshkov** [comment]
Moved to CoreLibs:
https://github.com/AdguardTeam/CoreLibs/issues/150
