### ISSUE TITLE
Hide the AdGuard icon from menu bar

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#265]
> For something that simply always runs in the background, there’s no need for it to take up valuable space in the taskbar or in the dock. This is pretty expected behavior for third-party apps these days. As a suggestion, and Similar to BetterTouchTool, any user that needs to retrieve AdGuard settings should be able to relaunch the app by opening it from Applications.

**Comment by Evertt** [comment]
Yes please, +1

**Comment by iDjay** [comment]
+2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by akmLaVx** [comment]
Got another feature request from user 2234677. @TheHasagi ?

> Добавить чекбокс «Показывать AdGuard в
> строке меню». Если снять галочку с
> чекбокса, то иконка Adguard пропадает из
> строки меню. Чтобы снова открыть
> главное окно программы (которое
> появляется по клику на иконку в меню)
> нужно будет запустить программу из
> Launchpad’a. По сути, пользователю может
> понадобиться открыть AdGuard только для
> полного отключения защиты, внесения
> правок в правила фильтрации,
> изменения каких-то настроек, или
> просто для просмотра статистики, что
> не является таким уж частым действием
> и не требует постоянного нахождения в
> строке меню. Также, такая настройка
> есть, например, у 1password и великого
> множества других программ для Mac, а
> аналогичное, предложенному мной,
> поведение, с запуском настроек из
> Launchpad’a если убрать иконку из меню,
> есть, например, у Little Snitch. Спасибо за
> внимание.

**Comment by MazterQyou** [comment]
+1, please add this, it's the only thing stopping me from using AdGuard 🙏

**Comment by ameshkov** [comment]
Sorry that it takes so long. I've assigned it to v2.3 and increased priority to High.

**Comment by iDjay** [comment]
any news on this?

**Comment by zzebrum** [comment]
Currently, this issue assigned to 2.4 milestone :) maybe we can ask @ameshkov to reassign the issue.

**Comment by chenjau** [comment]
still no hiding setting(2.4.1.708 nightly), any news on this?

**Comment by zzebrum** [comment]
@chenjau well, it was the very first nightly version 2.4 :)

**Comment by dasnorsep** [comment]
I like my menu bar clean and this issue is a major dealbreaker. I'll going to have to stick with your DNS service for now.

**Comment by chenjau** [comment]
working now(2.4.9.802 nightly)!🚀

**Comment by Lilac-Orange** [comment]
Once an icon has been hidden, access to Adguard settings becomes unavailable.

**Comment by Evertt** [comment]
> Once an icon has been hidden, access to Adguard settings becomes unavailable.

I haven't used the app in a while, so I'm not sure if you've observed a new bug.
But normally, when an app is running but has no dock icon nor a menu icon then accessing its settings should be possible by simply "launching" the app again. You're not really launching a new instance of the app, but it should notify the app that you're wanting to see some kind of window and then usually it would show you the settings window.

Have you tried that?

**Comment by Lilac-Orange** [comment]
> Have you tried that?

— Yes, I have been using Adguard for many years now.

# Solution

I just discovered a workaround for this issue today. I thought I'd share it 
with you all in case anyone else is searching for the same answers I was. 
Hope it helps!

Upon investigating the Adgurad files on my Mac OS, I came to the realization 
that I don't actually need an icon in the menubar.
You have the ability to make edits directly where they are needed.

## To Add/Remove/Modify Adguard filtering rules:

> SQLite DB: I use TablePlus for this purpose

```
/Users/lilac/Library/Group Containers/TC3Q7MAJXF.com.adguard.mac/Library/Application Support/com.adguard.mac.adguard/adguard.db
```


## Menu bar icon settings and other settings as well:

> plist: I use BBEdit for this purpose

```
/Users/lilac/Library/Preferences/com.adguard.mac.adguard.plist
```

To hide the menu bar icon:

```
    <key>HideMenubarIcon</key>
    <true/>
```

To unhide the menu bar icon:

```
    <key>HideMenubarIcon</key>
    <false/>
```
