### ISSUE TITLE
Auto-updating filters feature and advanced stealth features

### ISSUE THREAD

**Issue by veronikasav** [AdguardTeam/AdguardForMac#267]
After purchasing the Windows version am noticing it's much more super to
the MacOS version. Please add reliable auto-updating filters feature for
MacOS version (every 60 minutes, etc), as well as similar advanced stealth
features like the Windows version.

**Comment by vozersky** [comment]
@veronikasav please elaborate a little, what exactly is wrong with filters auto-updates? 

stealth mode request here: https://github.com/AdguardTeam/AdguardForMac/issues/12
