### ISSUE TITLE
Connections can rarely slip through AdGuard filtering

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#270]
This problem appears to be not fully resolved.

We need to improve the "detector" extension. Instead of checking just the main frames, it should also check some popular third-party domains (google analytics, doubleclick, etc).

**Comment by ameshkov** [comment]
Domains it should react on:

`*.doubleclick.net`
`adservice.google.*`
`google-analytics.com`
`*.google-analytics.com`
`googlesyndication.com`
`*.googlesyndication.com`

**Comment by Stillness-2** [comment]
"Detector" for Google Chrome 
[AdgFailAlert.zip](https://github.com/AdguardTeam/AdguardForMac/files/1622380/AdgFailAlert.zip)

**Comment by Stillness-2** [comment]
It is the same #285. 
Closed this issue.
