### ISSUE TITLE
Add Cliqz browser to the default filtered applications list

### ISSUE THREAD

**Issue by BooBerry** [AdguardTeam/AdguardForMac#275]
Like Opera Neon, the same user also reported that Cliqz browser for Mac also isn't included in AG for Mac's default filtered applications list and currently needs to be manually added.

Download Cliqz here: https://cliqz.com/en/

Forum topic regarding this: https://forum.adguard.com/index.php?threads/adguard-app-and-cliqz-browser.27857/

**Comment by BooBerry** [comment]
Might want to also check installing the certificate for the browser, according to the user after adding Cliqz to the filtered applications list (and rebooting the Mac) the browser gives off certificate warnings on HTTPS sites.

**Comment by ameshkov** [comment]
Yeah, this is a fork so it makes sense
