### ISSUE TITLE
Feature Request - Adding DNSCrypt In macOS client

### ISSUE THREAD

**Issue by zznosar** [AdguardTeam/AdguardForMac#277]
Not sure if there is an existing feature request for this, but can we integrate DNSCrypt in the macos client?

Probably default the DNS to AdGuard DNS.

Users can enable or disable this feature.

I think it’s good to have that so that we have consistency between the system. The android version has it, the ios pro version will have it, how about adding this feature in macos as well?

**Comment by evilvibes** [comment]
I would love to see AdGuard as my default DNSCrypt client for mac. This would be awesome on Windows aswell.

**Comment by willfarrell** [comment]
Jumping straight to v2 would be ideal. [dnscrypt-proxy 2](https://github.com/jedisct1/dnscrypt-proxy)
- https://github.com/jedisct1/dnscrypt-proxy/issues/47
- https://github.com/AdguardTeam/AdguardForiOS/issues/585

Some verbiage on your website about the DNSSec features would be great.

**Comment by planet0** [comment]
Adding a +1 for this, as the [DNSCrypt OS X Client](https://github.com/alterstep/dnscrypt-osxclient) hasn't been active.

**Comment by ameshkov** [comment]
dup of #685
