### ISSUE TITLE
Feature Request- Change frequency of auto-update of filters

### ISSUE THREAD

**Issue by xlumin8** [AdguardTeam/AdguardForMac#278]
Currently the filters auto-update. However, the frequency at which they check for updates and apply them is information that is completely in the dark. There should be a setting in the preferences that allow us to adjust the frequency at which the app checks the filters for updates such as every 1 day, 7 days, 30 days, etc. Or disable auto-updates of filters altogether.

**Comment by ameshkov** [comment]
It appears that we have an open feature request about that:
https://github.com/AdguardTeam/AdguardForMac/issues/146

Marking this as a duplicate then.

Thank you!
