### ISSUE TITLE
IpVanish VPN compatibility

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#28]
http://www.ipvanish.com/software/

If 'automatically filter applications' option is checked in ADguard, IpVansih VPN does not connect, even though IPVanish is not listed in the filtered apps section. It connects fine if this option is disabled.

OS X El Capitan

RKL-474-61259

**Comment by vozersky** [comment]
@zebrum need to test this one

**Comment by zebrum** [comment]
with Adguard 1.4.1 and EL Capitan 10.11.6, 'automatically filter applications' option is enabled and IpVanish is in filtered apps - **IpVanish** v3.0.7 is able to connect.
