### ISSUE TITLE
AdGuard suddenly stops working in Google Chrome until quit and relaunch

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#285]
At unpredictable moments, AdGuard stops working in Google Chrome and I need to quit Google Chrome and relaunch it if I want AdGuard to continue functioning.

Only occurs with AdGuard for macOS, not the browser extension.
Provided logs and screenshots in support emails already.

### Steps to reproduce

1. Continuously watch a number of YouTube videos
2. Whilst watching, do a Google search or visit reddit in a new tab

### Expected behavior

Ads in YouTube videos continue to be blocked, and AdGuard continues filtering on webpages in other tabs. AdGuard assistant remains visible in all tabs.

### Actual behavior

All ads in YouTube videos are being seen, and all ads on other tabs are suddenly shows. AdGuard assistant disappears from all tabs.

<details><summary>Screenshot:</summary>

<img width="1552" alt="3-google-search-ads" src="https://user-images.githubusercontent.com/36845626/36667577-667e5204-1b42-11e8-9353-08782a204d86.png">

</details>

### Customer ID 

1655879

### Your environment

* Environment name and version: (e.g. Chrome 59): Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): None installed

**Comment by ameshkov** [comment]
Could you please check `chrome://net-internals` next time that happens?

I'm interested in what you'll see on `chrome://net-internals/#quic` and `chrome://net-internals/#http2`

**Comment by planet0** [comment]
So I realised it happened again, this time just general browsing in multiple tabs, no YouTube videos.

Webpage in particular was: http://www.onlinemediamasters.com/why-is-wordpress-so-slow/
I've checked `chrome://net-internals` for you, couldn't see anything out of the ordinary.

Screenshots of the two sections you mentioned are below.

<details><summary>QUIC</summary>
<img width="440" alt="screen shot 2018-02-27 at 2 48 48 pm" src="https://user-images.githubusercontent.com/36845626/36709732-82f1ad38-1bcd-11e8-8131-de7fa9866962.png">
</details>

<details><summary>HTTP/2</summary>
<img width="211" alt="screen shot 2018-02-27 at 2 48 41 pm" src="https://user-images.githubusercontent.com/36845626/36709739-937cb648-1bcd-11e8-981b-d6e1e1b55e0d.png">
</details>

**Comment by planet0** [comment]
Yes, visiting this website and clicking through a few pages, then opening a new tab and doing a Google Search replicates this issue pretty much every time. Now I can close tabs, open new tabs, and all Google Searches have ads with no AdGuard assistant visible.

<img width="675" alt="screen shot 2018-02-27 at 3 27 37 pm" src="https://user-images.githubusercontent.com/36845626/36710552-d62a2ef8-1bd2-11e8-98bc-d4e807e435a5.png">

<img width="800" alt="screen shot 2018-02-27 at 3 27 55 pm" src="https://user-images.githubusercontent.com/36845626/36710568-eef16f32-1bd2-11e8-8d46-017f9f049d5b.png">

**Comment by ameshkov** [comment]
@planet0 could you please also record a HAR file next time it happens?

https://support.zendesk.com/hc/en-us/articles/204410413-Generating-a-HAR-file-for-troubleshooting

One more question -- do you first open google.com.au and then enter a search term, or do you enter it right away to the address bar?

**Comment by planet0** [comment]
@ameshkov Sure, what's the best way to get this file privately over to you?

I enter it right away in the address bar. I will perform both methods whilst recording for you.

**Comment by ameshkov** [comment]
`devteam at adguard.com`

**Comment by planet0** [comment]
@ameshkov I'm trying to record the HAR, but when I go ahead and right click to save it with contents, it seems to be stuck on 'Collecting content...' and the HAR file it has created is stuck on zero bytes. Google search doesn't seem to help. Any ideas?

<img width="1110" alt="screen shot 2018-03-04 at 9 27 44 am" src="https://user-images.githubusercontent.com/36845626/36939987-fb170d20-1f8e-11e8-9b0b-ba1b7ce68011.png">

**Comment by ameshkov** [comment]
Hm, no ideas, it's usually going smoothly for me

**Comment by planet0** [comment]
Figured it out -- the issue is when trying to save the HAR after visiting any page on onlinemediamasters.com -- I wanted to give you a recording of this domain since it seems to be one of the easiest ways to break AdGuard and google.com.au.

I do have HAR recordings of searching on google.com.au via the Chrome address bar and via the website, sending them over now.

**Comment by ameshkov** [comment]
Hm, I can see that `www.google.com.au` is not filtered indeed as if HTTPS filtering could not kick in for it.

Does it help to stop for a few seconds and then start AdGuard protection back?

**Comment by planet0** [comment]
>Does it help to stop for a few seconds and then start AdGuard protection back?

It doesn't make a difference for me, the ads still show on refresh after reenabling protection.


However, I found something in particular.
When the issue appears in Google:

In the same window...
-refreshing the affected tab, or
-opening a new tab and pasting the URL
still displays ads in Google search and AdGuard assistant is gone.

In a new window, pasting the url or typing a new search still displays ads in Google search and AdGuard assistant is gone.

However, if I...
- Select a different Google Chrome profile, such as Guest, or
- I open an Incognito window
The ads disappear with the same url or with any google search, and the assistant is visible again.

After reproducing the issue (by visiting pages in onlinemediamasters.com and performing various searches in Google), the Incognito session started showing Ads again in search results, and the AdGuard assistant once again disappears.

--

From what I am taking from these experiences, it could be session related. AdGuard is okay for a while in a users session, until something for that session interferes. That's why it can still work with a new profile or new session until I reproduce it inside that one session.

**Comment by ameshkov** [comment]
I suppose this is the same issue as #270 but for some reason, it is not as rare in your case.

To prove it we can try another thing. Next time it happens, open `chrome://net-internals/#sockets`, then click "Close idle sockets", "Flush idle sockets", and refresh google.com

**Comment by planet0** [comment]
> To prove it we can try another thing. Next time it happens, open chrome://net-internals/#sockets, then click "Close idle sockets", "Flush idle sockets", and refresh google.com

You were correct, performing these steps immediately and refreshing made the ads disappear and AdGuard assistant show again.

**Comment by ameshkov** [comment]
That's it then. @Stillness-2 plz take a look.

**Comment by Stillness-2** [comment]
@planet0 Can you test this debug version please? 
https://uploads.adguard.com/AdGuard.app.zip

**Comment by planet0** [comment]
@Stillness-2 I've tried reproducing the issue in the debug version for over 15 minutes, and I couldn't recreate it. Is there something with this version that fixes the issue?

**Comment by Stillness-2** [comment]
@planet0  Yes, I hope so. :)

**Comment by planet0** [comment]
@Stillness-2 Well, I just tried in again in another session and I still cannot replicate it. It seems like this is fixed in the version you provided. :)

I cannot continue using my license with this version claiming the key is invalid (only 14 day trial), do I need to downgrade back to the stable app?

**Comment by Stillness-2** [comment]
@planet0 "do I need to downgrade back to the stable app?" 
Yes, on stable version your key will be accepted again. 
Also debug version contains many debug output, which slow down performance.

If all will be ok we plan to release hotfix version.

**Comment by planet0** [comment]
@Stillness-2 No problem, I'm convinced that the issue is resolved on my end so I'll go ahead and get back onto the stable version.

**Comment by planet0** [comment]
Still good with 1.5.4 beta. 👍
