### ISSUE TITLE
AdGuard Assistant randomly disappears from all browsers on AdGuard for Mac

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#287]
### Steps to reproduce
1. Just have AdGuard for Mac ready
2. Assistant will disappear randomly. All browsers and websites are affected.
3. Reinstalling Assistant via AdGuard's settings fix the issue temporarily, but it repeats after a random period of time

### Expected behavior
AdGuard Assistant should be available where applicable

### Actual behavior
It randomly disappears from everywhere

### Customer ID and debug logs
1435611

**Comment by ameshkov** [comment]
@Stillness-2 could you please take a look at the log?

**Comment by evgeniy-ADG** [comment]
USER ID: 819154
Logs regarding the same problem: https://uploads.adguard.com/nwinr.txt

> Пользуюсь вашими услугами уже давно,претензий не возникало никогда,но последнее время периодически стала исчезать иконка а правом нижнем углу Яндекс браузера,и соответственно сразу появляется реклама.Исправить это перезагрузкой браузера или программы не получается, проблема может исчезнуть сама собой без всякой привязки к чему либо.Может через час или через полдня.Скажите это почему так? Вот и сейчас его нет и соответственно реклама присутствует.

**Comment by ameshkov** [comment]
Guys, I am pretty sure this is a duplicate of #270 . Will be resolved in the next update
