### ISSUE TITLE
Inconsistent checksums

### ISSUE THREAD

**Issue by designorant** [AdguardTeam/AdguardForMac#288]
I wanted to try AdGuard for Mac today, but the binaries out there were different to the ones provided a while ago.

I have downloaded the file from three different locations, and only the one sitting on GitHub appears to match what was available at static.adguard.com [a while ago](https://github.com/caskroom/homebrew-cask/commit/c2697e338fdb1f146b1df585c0d235f68f3cd47d#diff-9115dabb9db95662ebeee2a6e52d8d89). Digging a bit further, it turned out that the original checksum was [even different](https://github.com/caskroom/homebrew-cask/commit/81b76e2b5b2f4d2e43ae2bf66896fadb10c324ee#diff-9115dabb9db95662ebeee2a6e52d8d89).

Have you been modifying your binaries since the release?

**Source**: 
https://static.adguard.com/mac/Adguard-1.5.3.release.dmg
**Checksum**: 
de1dc6e957094c9d05a935cb3896273bd8c8379c62e74c19922984d8f5c05a3d

**Source**: 
https://download.adguard.com/d/18673/Adguard.release.dmg via https://adguard.com/en/download.html?os=mac
**Checksum**: 
364f67cd1de7d4caa240983bebfcc7d83dfb98897abe22064f7cef1932792292

**Source**: 
https://github.com/AdguardTeam/AdguardForMac/releases/download/v1.5.3/Adguard-1.5.3.release.dmg
**Checksum**: 
02d40d8f039459515e8e596edbe591cec1c77703fe49797c9215b0e7363781b8

<img width="945" alt="adguard" src="https://user-images.githubusercontent.com/87477/37105416-07011956-2227-11e8-9d31-0a8f9473a229.png">

**Comment by ameshkov** [comment]
Yep, we've released a hotfix yesterday (handling content-md5 header in the case if AG has modified response content with a $replace rule or HTML filtering rules), but haven't yet published it here. We'll fix it, thank you for alerting us!

**Comment by ameshkov** [comment]
Uh, missed the brew cask screenshot, @Stillness-2 let's create a PR there
