### ISSUE TITLE
[Feature request] Distribute the "stripped-down" (extension + assistant only) macOS version via App Store

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#289]
As requested by user #1581065, a macOS 3rd-party developer:

You can distribute app with only Safari Extension and iCloud sync, etc.
For additional money users can extend app abilities installing “helper" app. And in this case users can get system level proxy/adblocker.
A lot other app implement additional unsandboxes functionality.
Examples:
https://pasteapp.me <https://pasteapp.me/>
https://itunes.apple.com/us/app/paste-clipboard-history-manager/id967805235?mt=12 <https://itunes.apple.com/us/app/paste-clipboard-history-manager/id967805235?mt=12&ign-mpt=uo=6>
Direct paste in any app can be enabled with helper app download automatically from developer website.

Same about
https://copiedapp.com <https://copiedapp.com/>
https://itunes.apple.com/us/app/copied/id1026349850?mt=12 <https://itunes.apple.com/us/app/copied/id1026349850?mt=12>

Much more complicated example with system level functionality
https://wifispoof.com <https://wifispoof.com/>
https://itunes.apple.com/us/app/wifispoof/id1192126677?mt=12 <https://itunes.apple.com/us/app/wifispoof/id1192126677?mt=12>

This is just recommendations how-to improve product and get better sales.

Thanks,
Myroslav

**Comment by ameshkov** [comment]
Eventually, we'll have to do it as Apple is going to deprecate the old extensions SDK..
