### ISSUE TITLE
HTML filtering rules - void elements are never removed

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#29]
The problem is in the wrong order of checks in ContentFilterRule.

Current implementation:
1. Attributes check
2. Check if content is empty (return NO if empty)
3. Check tag-content and wildcard

Proper implementation:
1. Attributes check
2. Check if tag-content and wildcard are empty. If so - return YES
3. Check if content is empty
4. Check tag-content and wildcard

**Comment by Stillness-2** [comment]
CR-AG-710

#20, #25, #26, #29
