### ISSUE TITLE
Device Count for 'Number of Devices' in License Status

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#291]
AdGuard for Mac seems to not understand using licenses that include mobile devices.

On the AdGuard website, my license states: "Premium license for 3 computers and 3 mobile devices", but on AdGuard for Mac, it says "Number of devices: 3 (used on 5)".

Suggesting to either:

1. Recount license to include mobile devices, so AdGuard for Mac says "Number of devices: 6 (used on 5)"; or
2. Introduce more details in the license window, "Number of devices: 3 computers and 3 mobile devices (used on 3 computers and 2 mobile devices)".

<img width="584" alt="screen shot 2018-03-18 at 7 16 34 am" src="https://user-images.githubusercontent.com/36845626/37559565-87e3160c-2a7c-11e8-8b51-a81ff727d783.png">

**Comment by planet0** [comment]
@ameshkov Any chance this will be resolved in the upcoming new UI for 2.0? Still visible as is in the Nightly builds.

**Comment by Stillness-2** [comment]
Not applicable for new UI
