### ISSUE TITLE
Receiving slower internet speeds with AdGuard activated on Mac

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#299]
> Recently, I've noticed activating AG on my Mac has provided slower internet speeds vs. not having it activated and also compared to AGP on my iOS devices. I deactivated AG for Mac and am using AG DNS on my Mac for now. My internet speeds have improved greatly. No other apps/services are running on the network or local level. I only have 4 filters enabled (English, Spyware, Russian and Adblock Warning removal). I first noticed that it was slow when loading NYTimes.com and a few other sites. Then I performed a speedtest using fast.com, speedtest.net and speedtest.xfinity.com
> 
> It isn’t necessarily a browser issue as I’ve noticed it’s slow in apps like Reeder. But I’m using the latest stable versions of Safari and Chrome 65.0.3325.184 (Platform version: 10323.62.0/1)

<details><summary>Logs:</summary>

Are available here: 1809476

</details>

### Customer ID 
1809476

### Your environment

* Environment name and version: (e.g. Chrome 59): Safari, Chrome 65.0.3325.184, other apps
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) none

**Comment by zzebrum** [comment]
I suppose the whole issue is outdated now. @Eugene-Savenko you guys can suggest the user try the new nightly version with CL. If the problem will persist, collect new log and reopen the issue.

**Comment by TheHasagi** [comment]
#### Customer ID: 2061703

Reopened. Need testing results.

**Comment by TheHasagi** [comment]
#### Customer ID: 381904

**Comment by Eugene-Savenko** [comment]
@zebrum @ameshkov 

Can someone please look into it once again? The 2061703 user reports that it got even worse since the 2.0.0.500 release; the upload has dropped from 100 to 15-40 Mbps, and the upload speed remains the same - ~ 170 out of 250. Please let us what information do you need to troubleshoot the issue.

**Comment by TheHasagi** [comment]
No internet speed slowdown detected. Closed.

<details> Screenshot:

![img](https://uploads.adguard.com/TheHasagi3o3zm.jpg)

</details>
