### ISSUE TITLE
cloudflare dns's website fails to open in safari

### ISSUE THREAD

**Issue by hmage** [AdguardTeam/AdguardForMac#301]
### Steps to reproduce

1. Enable adguard
2. Open safari
3. Navigate to https://1.1.1.1/

### Expected behavior

The site should open, all elements should be rendered correctly and embedded video manual should play.

### Actual behavior

Safari shows "Connection is not private" warning.

<details><summary>Screenshot:</summary>

![mbithtdpg3](https://user-images.githubusercontent.com/739119/38207510-c9995b74-36b6-11e8-825c-155242a033d1.png)
![iws317rpxc](https://user-images.githubusercontent.com/739119/38207524-db8a15f8-36b6-11e8-85e9-008bfd3ad1f2.png)

</details>

### Customer ID 

1501720

### Your environment

* Environment name and version: (e.g. Chrome 59): Safari 11.0.3 (13604.5.6)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by planet0** [comment]
Can confirm.

In Safari, the AdGuard Certificate points to 127.0.0.1, Not Private warning and blocked.
In Chrome, the AdGuard Certificate points to *.cloudflare-dns.com, no issues.


<details><summary>Screenshots:</summary>

<img width="701" alt="screen shot 2018-04-03 at 11 30 37 am" src="https://user-images.githubusercontent.com/36845626/38224278-b2033936-3732-11e8-9c84-e910a77899a2.png">

<img width="504" alt="screen shot 2018-04-03 at 11 30 47 am" src="https://user-images.githubusercontent.com/36845626/38224279-b546750e-3732-11e8-924e-09e2cce06c73.png">

</details>
