### ISSUE TITLE
Browser connections are blocked in certain circumstances

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#306]
### Description

We received 3 complaints so far, also I had a similar case on my machine

> После загрузки системы через непродолжительное время (и каждый раз через разное) делает недоступными соединения по http и https,то есть, сайты не грузятся, хотя почта и другие сервисы работают. При отключении защиты, работа браузера восстанавливается. Это касается Safari и точно Chrome

### Customer ID 
1405612 (debug log: )
1847467 (waiting for logs)
1488350 (waiting for logs)
1851155  (waiting for logs)
1558433 (logs: )

### Your environment

* Environment name and version: (e.g. Chrome 59): Safari, Chrome
* macOS: 1013
* AdGuard: 1.5.6 release
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) n/a

**Comment by ameshkov** [comment]
Какой провайдер у пользователей?

**Comment by Lemierre** [comment]
It seems that this beta solved the problem. Thank's!

**Comment by ameshkov** [comment]
@Lemierre thank you!

@Stillness-2 let's publish a hotfix.

**Comment by veronikasav** [comment]
The test build didn't help.
Ticket ID: 404405
[debug (3).txt](https://github.com/AdguardTeam/AdguardForMac/files/1986384/debug.3.txt)

**Comment by Eugene-Savenko** [comment]
Could someone please examine the logs sent by 404405? He still has the issue despite updating to this test build.

**Comment by ameshkov** [comment]
@Eugene-Savenko it must be something new, let's create a separate issue

**Comment by Stillness-2** [comment]
@Eugene-Savenko About 404405, the user should install the latest beta, and if the problem is repeated, then he should write new logs and send us.
