### ISSUE TITLE
Localization fix for the Japanese translation

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForMac#308]
To change "Statistics since" to "Statistics since %@"

**Comment by aalpatkina** [comment]
Please add an appropriate placeholder to the following phrases:

1. starting at -  String Key: starting at 
(Main Panel - Renew Button (AAStatusBarMenuController))
2. used on - String key: used on
3. trackers blocked - String Key: %d tracker blocked>trackers
4. ads blocked - String key: %d ad blocked>ads
5. dangerous requests blocked - String key: %d dangerous request blocked>requests

Maybe to these strings as well:

1. banners - SK: %d banner>banner
2. threats - SK: %d threat>threat
3. trackers - SK: %d tracker>tracker

It is also not clear how the dates will be reflected in the Japanese app. For example, this format "day/month/year" is not acceptable in the Japanese language. They use "year/month/day" date format.

**Comment by Dariamag** [comment]
Example of the date string: 
String Key: Statistics since %@
https://adguard.oneskyapp.com/collaboration/translate/project/project/125821/language/4#/
