### ISSUE TITLE
TCP FastOpen incompatibility

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#309]
### Description

Unable to reach HTTPs websites, importing the certificate manually doesn't help.

### Steps to reproduce

1. Install Firefox 61.0b2 
2. Go to an HTTPs website, the https://facebook.com for instance
3. Import the cert from /Library/Application Support/com.adguard.Adguard/NfApiConfiguration/SSL
4. Repeat step 2, still can't access

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/39745288-7f8c1480-52af-11e8-8e0d-37f85fdd6b80.png)

![image](https://user-images.githubusercontent.com/15856304/39745297-8586332a-52af-11e8-9e1d-3babbdb0e9fc.png)

![image](https://user-images.githubusercontent.com/15856304/39745306-8ada6c1a-52af-11e8-8e5f-f5ecb827751d.png)

</details>

### Customer ID 
Originally reported here - 1858581, UPD: we were unable to reproduce

### Your environment

* Environment name and version: (e.g. Chrome 59): Firefox 61.0b2 
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) none
* macOS 10.13.3
* AdGuard 1.5.6

**Comment by Eugene-Savenko** [comment]
Q: Could you confirm that you have checked these boxes when importing?
A: I originally only checked the first of the two, but trying again with both did not make any difference.

Q: Also, the problem might be in the Firefox Sync feature, are you using it?
A: I am not using Firefox Sync.

Q: Does the issue persist in the stable version of the browser?
A: Just tried now, and no it does not. Seems to be something that’s changed in Firefox 61. Interesting that it doesn’t seem to happen on your end though. Even though the issue is intermittent, it usually surfaces after navigating a couple pages or a couple of unique Google searches. I could try on another machine, but I can only get access to one in a week or so.

**Comment by Bo98** [comment]
A subtle note, but on HSTS websites it doesn't mention anything about HSTS like your screenshot.

So instead of [this](https://i.imgur.com/Yrr7oJy.png) without any certificate imported, the error with the certificate imported is the same as non-HSTS websites as seen [here](https://i.imgur.com/xr6TSer.png).

The next Firefox Developer Edition update is 61.0b7 in two weeks time, but I could opt into the beta channel and keep an eye on b3-b6 in the meantime.

**Comment by ameshkov** [comment]
I've failed to reproduce this issue in both FF Dev and nightly.

Could you please try it with a new FF profile?

**Comment by ameshkov** [comment]
> A subtle note, but on HSTS websites it doesn't mention anything about HSTS like your screenshot.

Hm, one moment, so you see the "secure connection failed" everywhere? It means that the problem might be not in the certificate -- something else is wrong.

**Comment by Bo98** [comment]
> Could you please try it with a new FF profile?

I've tried that and it did not make a difference.

> Hm, one moment, so you see the "secure connection failed" everywhere?

Well, only on HTTPS sites of course. But it doesn't go as far as detecting HSTS is seems, or at least the error doesn't indicate HSTS.

What's interesting is how it's intermittent. I can consistently reproduce it, but not on every page load. I don't think it was mentioned here but I mentioned it via email.

**Comment by Bo98** [comment]
The issue still persists unfortunately, but I've sent the archive regardless.

**Comment by ameshkov** [comment]
@Stillness-2 plz prepare a debug build, we need network logs in order to troubleshoot this

**Comment by Stillness-2** [comment]
Because we can't reproduce this issue we ask to collect logs to you. :)
This is debug version for collecting network log: https://uploads.adguard.com/AdGuard.app.zip
Please run it and reproduce issue. 
After that send as all files from `~/Library/Logs/Adguard` and time when issue occured.

**Comment by Bo98** [comment]
Sent to devteam email.

**Comment by ameshkov** [comment]
@Bo98 could it be that you have another network-level filtering software?

**Comment by Bo98** [comment]
> could it be that you have another network-level filtering software?

The closest I can think of is VPN, but that was definitely not running at the time.

> and one more idea: go to about:config and try disabling network.tcp.tcp_fastopen_enable there

Yep, that seems to stop the issue from happening.

**Comment by ameshkov** [comment]
Awesome, thank you very much for confirming it!

**Comment by Bo98** [comment]
That also explains why it worked in Firefox 60: it was disabled by default and now it's enabled by default as of 61.

**Comment by ameshkov** [comment]
It does not explain why it works on our side, though.

**Comment by ameshkov** [comment]
Anyway, the fix will arrive soon and I'd be grateful if you check it as you're the only one I know who experiences this issue :)

**Comment by Bo98** [comment]
I can do that. Let me know when it's ready and I'll give it a try.

**Comment by Stillness-2** [comment]
@Bo98 This is debug build with fix (may be): https://uploads.adguard.com/AdGuard-ffd.app.zip
Please check it.

**Comment by Bo98** [comment]
The fix seems to be working from my testing. Thanks!

**Comment by ameshkov** [comment]
Yay, thank you for testing it!
