### ISSUE TITLE
Compatibility with Boxcryptor

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#310]
### Descryption

AdGuard is currently affecting [boxcryptor](https://www.boxcryptor.com/en/) (security software to encrypt files to the cloud) - not during ongoing usage but definitely during set up phase. The workaround is to temporarily disable AG, install boxcryptor then re-enable AG

### Steps to reproduce

1. Install Boxcryptor
2. Launch it
3. See the error message

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/39968108-857af594-56d0-11e8-8918-6bbfd60d7eef.png)

</details>

### Customer ID 
1726771

### Your environment

* Environment name and version: macOS 10.13.4, AdGuard 1.5.6, Boxcryptor 2.22.933
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) none

**Comment by stephantual** [comment]
thanks yes - that's indeed an issue - would appreciate if it was resolved as boxcryptor is enough fun as it is to setup correctly 👍

**Comment by ameshkov** [comment]
@vozersky plz try reproducing this issue. I suppose we just need to figure out what domain needs to be placed to the https exclusions list.

**Comment by vozersky** [comment]
reproduced, but I don't see any requests in the filtering log

**Comment by vozersky** [comment]
![screen shot 2018-05-14 at 17 06 42](https://user-images.githubusercontent.com/17472907/40002363-337cd0ae-5799-11e8-8b39-548947b1e193.png)



Looks like we have to exclude` boxcryptor.com`
It helps.
