### ISSUE TITLE
Adguard Blocking Webpack's HMR (Hot Module Reload)

### ISSUE THREAD

**Issue by williamli** [AdguardTeam/AdguardForMac#311]
I am a web developer and use something called HMR to reload part of a website when a file is updated. (https://webpack.js.org/concepts/hot-module-replacement/)

The reloading feature seems to be blocked by Adguard app on MacOS.
Changes made on the server is no longer hot reloaded.
The issue is fixed once protection is turned off on the Adguard app.
Disabling production on Firefox / Chrome's extension is not enough to restore this feature.

**Comment by vozersky** [comment]
@williamli hi
what if you try not to just disable protection for the affected domain, but add it to HTTPS filtering exclusions here: https://uploads.adguard.com/up05_gbzve.png ?
does it help?

**Comment by williamli** [comment]
@vozersky please give me some time to work on your suggestion and find a easy way to reproduce the problem

**Comment by ameshkov** [comment]
Please reopen if there's new info
