### ISSUE TITLE
Adguard (Mac) Breaks Google Docs on Safari

### ISSUE THREAD

**Issue by williamli** [AdguardTeam/AdguardForMac#312]
Adguard (Mac) is killing Google Docs on Safari, works fine Chrome.

PS: use using the Adguard Mac OS app, with Safari browser extension disabled in settings.

![screen shot 2018-05-16 at 17 44 52](https://user-images.githubusercontent.com/179761/40109899-23aea2d0-5931-11e8-874f-e505d3684542.png)

**Comment by ameshkov** [comment]
Does it help to add `docs.google.com` to the whitelist?

**Comment by vozersky** [comment]
can't reproduce 
what filters do you use?

**Comment by williamli** [comment]
@vozersky English, Filter unlocking search ads and self-promotions, French filter, Safari filter

**Comment by williamli** [comment]
@vozersky @ameshkov I just disabled the French filter and everything is working now.

**Comment by ameshkov** [comment]
Got it, thank you!

Passed it to the filters maintainers team
