### ISSUE TITLE
Please update Traditional Chinese translations for filters.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#318]
I don't have a macOS PC.
I'm unable to check filters' translations in AG for macOS.
But I guess that Simplified Chinese is used in Traditional Chinese language file for filters, such like AG for Windows.
https://github.com/AdguardTeam/AdguardForWindows/issues/2245

1. Only use Traditional Chinese translations for filters in Traditional Chinese language file.

2. "English filter (英文過濾器)" was renamed to "AdGuard Base filter (AdGuard 基本過濾器)".
You should also update the translations of filters from oneskyapp.

Please fix them.

Thanks.

**Comment by ameshkov** [comment]
@Stillness-2 could you please verify that the exact locale (`zh-tw` in this case) is used to get the filters translation?

**Comment by Stillness-2** [comment]
@ameshkov, I checked. All ok.

**Comment by lancelot-moon** [comment]
Hi, may you change to use Traditional Chinese (正體中文) in AG for macOS and then make a screenshot of filters?

Please upload that screenshot here.

I want to check its translations for filters.
Sorry that I don't have Mac.

**Comment by Stillness-2** [comment]
@lancelot-moon 
![2018-06-13 14 08 44](https://user-images.githubusercontent.com/12689/41347846-93fce7a2-6f13-11e8-8634-e6a093c5e3c0.png)

**Comment by lancelot-moon** [comment]
Hi,
Those translations of filters are Simplified Chinese, **not Traditional Chinese.**
You have to apply my Traditional Chinese translations for filters.
You need to reopen the topic until you solve the issue.
AG for Android & iOS already fixed the mistake.

Maybe other AdGuard team members know how to do.

Thanks a lot!

**Comment by Stillness-2** [comment]
```
			"zh": {
				"name": "英语过滤器",
				"description": "基于 EasyList 开发的过滤器。过滤器可以移除以英语内容为主网站上的广告。"
			},
			"zh_TW": {
				"name": "英文過濾器",
				"description": "EasyList + AdGuard 英文過濾器。該過濾器對於優質的廣告封鎖是必要的。"
			}
```

**Comment by lancelot-moon** [comment]
Yes, you got it.
You should **use "zh_TW" in the client side**, not "zh".

**Comment by Stillness-2** [comment]
@lancelot-moon First screenshot was made from wrong version (1.5.6). The current version of the app (1.5.8) contains correct processing for zh_TW.

**Comment by lancelot-moon** [comment]
Hi,
May you show the screenshot about the translation of Traditional Chinese title?
In the past, AdGuard for Windows used "China tradition" as "Traditional Chinese", which is wrong.
https://github.com/AdguardTeam/AdguardForWindows/issues/2190

I am not sure if AG for macOS has the same mistake.

Thanks.

**Comment by Stillness-2** [comment]
Adguard for Mac do not have language switcher, it is done from system preferences.
![2018-06-14 11 54 47](https://user-images.githubusercontent.com/12689/41401971-cf1b3972-6fc9-11e8-83ae-f2608d82b3f0.png)
