### ISSUE TITLE
We need more detailed approach when find localisation for filters description in UI

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForMac#319]
We need to use components for searching, which is returned by `[NSLocale componentsFromLocaleIdentifier:]`, in this sequence:

- `NSLocaleLanguageCode`-`NSLocaleScriptCode`-`NSLocaleCountryCode`
- `NSLocaleLanguageCode`-`NSLocaleScriptCode`
- `NSLocaleLanguageCode`
- 'en'

#318

**Comment by ameshkov** [comment]
It seems your change has broken filters translations: https://github.com/AdguardTeam/AdguardForMac/issues/510

**Comment by lancelot-moon** [comment]
It's `zh-hant-tw`, not `zh-hans-tw`.

https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
Type: redundant
Tag: zh-Hant-TW
Description: Taiwan Chinese in traditional script

https://www.w3.org/International/articles/bcp47/
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/qCNGNLO.png)
</details><br/>

**Comment by lancelot-moon** [comment]
@Stillness-2 

Why is the issue fixed in nightly but NOT fixed in v2.0.4 Release?

The same wrong things as v2.0.3 beta.
Filters become Simplified Chinese.
