### ISSUE TITLE
Adguard interferes with Android Messages for Web

### ISSUE THREAD

**Issue by NathanTheGr8** [AdguardTeam/AdguardForMac#320]
### Steps to reproduce
1. Open https://messages.android.com/ and scan the QR code on the phone
2. Wait and page should refresh to messages for web, but it never loads
3. Disabling chrome adgurad extension doesn't help
4. Turning Of AdGuard for Mac imminently lets the page load

### Expected behavior
After scanning the QR code the page should refresh in a few seconds and load my messages

### Actual behavior
Page never refreshes and my sms messages never load

I never got an auto-reply with customer ID but I included the issue name in the submission.

MacOS 10.13.5 (17F77)
Adguard 1.5.8
Chrome 67.0.3396.87

**Comment by ameshkov** [comment]
Add `instantmessaging-pa.googleapis.com` to the HTTPS exclusions list.

**Comment by NathanTheGr8** [comment]
Could you elaborate on this? I don't see what issue I was a duplicate of and I have tried adding both
````
@@//messages.android.com^$document
@@//instantmessaging-pa.googleapis.com^$document
````
to my user filter list and it doesn't help.

**Comment by ameshkov** [comment]
It's just it was discussed in the Windows repo.

The only solution is to add `instantmessaging-pa.googleapis.com` to HTTPS exclusions (settings -> network -> exclusions...). It will be added to the defaults in the next AG for Mac build automatically (it syncs with https://github.com/AdguardTeam/HttpsExclusions)
