### ISSUE TITLE
How to prevent ads in <p> blocks? 

### ISSUE THREAD

**Issue by KandidatOne** [AdguardTeam/AdguardForMac#321]
Здравствуйте,
Позвольте поблагодарить Вас за столь добротный продукт. Все нравится. Благодарю Вас. 
Столкнулся с такой вот проблемой - при посещении сайта macdigger.ru на страницах с новостями взяли за правило добавлять блок `<p></p>` в случайном месте, с рекламой своего магазина. Можно посмотреть [здесь](http://www.macdigger.ru/macall/macnews/pochti-vse-iphone-2018-goda-budet-sobirat-foxconn.html). 
Подскажите пожалуйста, как мне убрать этот блок с рекламой? Правило добавлял, однако, на конкретной странице срабатывает, на другой нет. А вот при просмотре в Safari режиме Reader - это вообще ни как не победить.
Надеюсь на Вашу помощь.

----------------------
I am sure that Your product is capable of this, but I do not have enough knowledge to do it myself. Faced such here a problem-when visiting the  macdigger.ru site on pages with news made a rule to add the casual blog `<p></p>` advertizing about the shop. Can be watch [here](http://www.macdigger.ru/macall/macnews/pochti-vse-iphone-2018-goda-budet-sobirat-foxconn.html). 
Please tell me how I can prevent this? The rule added, however, on a particular page it works, on the other one does not. 
I hope you can help me.

**Comment by ameshkov** [comment]
Добрый день!

Ну вот как-то так можно:
`macdigger.ru$$p[tag-content="https://mdlavka.ru"][max-length="600"]`
