### ISSUE TITLE
AdGuard и ESET Cyber Security Pro

### ISSUE THREAD

**Issue by Healler3108** [AdguardTeam/AdguardForMac#324]
Невозможна одновременная работа AdGuard и ESET Cyber Security Pro - одна из них перестает обрабатывать соединения в зависимости от последовательности запуска. Например, если первой запустилась Cyber Security, а AdGuard второй, то AdGuard исправно блокирует рекламу, но интернет-защита Cyber Security не обрабатывает соединения. И наоборот, если первой запустилась AdGuard, а Cyber Security второй, то AdGuard перестает блокировать рекламу, а интернет-защита Cyber Securit работает нормально.

macOS 10.13.6
Safari 11.1.2
AdGuard for Mac 1.5.8
ESET Cyber Security Pro 6.6.300.1

**Comment by ameshkov** [comment]
К сожалению, это стандартная проблема на маках с антивирусами.

Условно, кто первый начал фильтровать соединения, тот и "победил".

В качестве альтернативного решения, можно попробовать настроить их в "цепочку".
Сделать чтобы ESET не фильтровал браузер, но фильтровал исходящий трафик самого AdGuard.
