### ISSUE TITLE
HTTPS website XHR requests loading temp webpage

### ISSUE THREAD

**Issue by choco** [AdguardTeam/AdguardForMac#327]
When loading an https url Adguard seem to provide a waiting page (with the content "Loading site please wait...") before loading the website.
First of all, why is it needed?? Why isn't the filtered page loaded instead of this intermediate page
This also breaks a website for me https://fibra.click (and I wonder why it doesn't break more?)
When entering some text in the textbox and searching it sends a XHR request to https://api.fibra.click/municipalities/?name=string_entered which loads the same exact waiting page instead of the result and breaks the site.

AdGuard 1.5.8 beta, macOS High Sierra 10.13.6, any browser I tried.

**Comment by choco** [comment]
It works now, no idea why, nothing should have changed. But i would be cool if you could answer the question above about the temp page.

**Comment by zebrum** [comment]
@choco AdGuard doesn't do such things. More likely it was cloudflare ddos protection.
