### ISSUE TITLE
That special Safari Filter 

### ISSUE THREAD

**Issue by sh2sg** [AdguardTeam/AdguardForMac#328]
I am cross-checking all the filters to reduce rules overlap in order to get better performance, hopefully..

I noticed this special Safari Filter, it is enabled by default after installation, the description is a bit unclear but I think this filter is only needed for iOS and AdGuard Safari extension (to convert some unsupported AdBlock syntax to Safari Content Block syntax), the standalone version of AG does not need this special filter? 

If my understanding is correct, maybe you should remove it from installation default, or make it clear in its description header.

**Comment by ameshkov** [comment]
@sh2sg sorry for the late reply!

> the standalone version of AG does not need this special filter?

You are right, it does not need it indeed.

@Stillness-2 could you please check why do we have it enabled in the Mac app?

**Comment by Stillness-2** [comment]
https://uploads.adguard.com/screencast_2018-09-14_22-19-54.mp4
I do not understand what you mean

**Comment by zebrum** [comment]
Safari filter is turned off by default.
