### ISSUE TITLE
Broken FTP protocol support in Safari

### ISSUE THREAD

**Issue by vit9696** [AdguardTeam/AdguardForMac#332]
### Steps to reproduce

Visit `ftp://ftp.cis.upenn.edu/pub/papers/lee/Paper/Full_Postscript/proceedingsRV.pdf` by clicking on [the URL](ftp://ftp.cis.upenn.edu/pub/papers/lee/Paper/Full_Postscript/proceedingsRV.pdf) or by pasting the link into the search field in Safari.

### Expected behavior
The document should open.

### Actual behavior
NSURLErrorDomain:-1 error is shown. The document opens and the error is not shown when AdGuard is turned off or other software like `curl` is used.

<details><summary>Screenshot:</summary>
https://user-images.githubusercontent.com/4348897/45762200-83c85400-bc36-11e8-967c-e0538d01bf78.png
</details>

### Your environment
* Environment name and version: macOS High Sierra 10.13.6 (17G65), AdGuard 1.5.8 (455), Safari 12 (13606.2.11).
* Any specific potentially conflicting software installed: nothing.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #494](https://github.com/AdguardTeam/CoreLibs/issues/494) via [**ZenHub**](https://www.zenhub.com/)
