### ISSUE TITLE
Statistics is not counted properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#334]
Currently, the stats aren't counted properly:
https://uploads.adguard.com/up04_aa824_Monosnap.png

Here's what needs to be done:

1. Parse the filters tags in the `filters.json`: https://filters.adtidy.org/mac_v2/filters.json
2. If the filter has a `purpose:privacy` tag, increment the "blocked trackers" counter
3. If the filter has a `purpose:security` tag, increment the "blocked dangerous requests" counter
4. In ALL other cases, increment the "blocked ads" counter

**Comment by Stillness-2** [comment]
PR110
