### ISSUE TITLE
Please use Traditional Chinese translations for Web of Trust, AdGuard Assistant and Popup blocker when choosing Traditional Chinese interface in the system preferences of macOS.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#336]
I don't have Mac, but I saw another Taiwanese user shared screenshots about AdGuard for Mac.
It seems that you used wrong language (Simplified Chinese) in Traditional Chinese interface.
The Chinese characters in the screenshot are Simplified Chinese, not Traditional Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hw0FntT.png)
</details><br/>

This can be for your reference.
https://github.com/AdguardTeam/AdguardForWindows/issues/2302#issuecomment-416605008

zh-CN is Simplified Chinese for China.
zh-TW is Traditional Chinese for Taiwan.
On oneskyapp, Traditional Chinese in MISCELLANEOUS were all done long time ago.

Please check that you should use zh-TW for Web of Trust, AdGuard Assistant and Popup blocker when choosing Traditional Chinese interface in the system preferences of macOS.
https://github.com/AdguardTeam/AdguardForMac/issues/318#issuecomment-397222633

Thanks.

**Comment by ameshkov** [comment]
@zebrum could you please check it in the nightly version?

**Comment by zzebrum** [comment]
reproduced.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #264](https://github.com/AdguardTeam/AdguardAssistant/issues/264) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lancelot-moon** [comment]
@ameshkov 
@sfionov

This bug isn't fixed in v2.0.2 Beta.
AG Assistant is Simplified Chinese (zh-CN) interface while system language is Traditional Chinese (zh-TW).
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/FX1uIwo.png)

![image](https://i.imgur.com/HyWgeRN.png)
</details><br/>

Are you using the latest extensions in AG for Mac v2?
May you really check if Traditional Chinese normally represent for Web of Trust, AG Assistant, AG Extra and Popup blocker while system language is Traditional Chinese (zh-TW)?

Thanks.
