### ISSUE TITLE
Handle multiple $replace rules properly

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#338]
CoreLibs allows applying multiple $replace rules to a single request.

Here's how we should handle it in the filtering log:

1. Highlight the request with yellow (instead of current "red")
2. Print `Modified (3 rules)` in the "Rule" cell
3. Print all three rules in the item details

One more important thing about that. Yellow rows must be shown when I choose to check "Blocked" checkbox (including filtered HTML pages, etc).

**Comment by Stillness-2** [comment]
PR112
