### ISSUE TITLE
Assistant is missing in Outlook website on macOS

### ISSUE THREAD

**Issue by karina-archazh** [AdguardTeam/AdguardForMac#344]
@Eugene-Savenko commented on [Thu Oct 11 2018](https://github.com/AdguardTeam/AdguardAssistant/issues/260)

AdGuard Assistant from AdGuard 1.5.8 for Mac does not show up at https://outlook.live.com/mail/inbox
Works on Windows.

### STR:

- Make sure there's HTTPS exceptions
- Log in

### Expected result:

AdGuard Assistant shows up in the default location

### Actual result

It's missing

<details> <summary> screenshot </summary>

![image](https://user-images.githubusercontent.com/15856304/46790014-9c63ef80-cd46-11e8-82d2-427fa9ab4b50.png)

</details>

### Environment

AdGuard 1.5.8
macOS 10.14
Firefox 64.0a1
Chrome 69.0.3497.

---

@karina-archazh commented on [Thu Oct 11 2018](https://github.com/AdguardTeam/AdguardAssistant/issues/260#issuecomment-428968130)

Issue moved to [AdguardTeam/AdguardForMac #343](https://github.com/AdguardTeam/AdguardForMac/issues/343) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
Duplicate
