### ISSUE TITLE
Certificate issue when visiting 1.1.1.1 in Safari

### ISSUE THREAD

**Issue by choco** [AdguardTeam/AdguardForMac#345]
### Steps to reproduce
1. Visit https://1.1.1.1
2. Safari prompts that the connection is not private

### Expected behavior
Site is loaded correctly
### Actual behavior
Safari doesn't load the website, even trusting the certificate doesn't let me load the website

Screenshot:
<img width="1672" alt="screen shot 2018-10-12 at 01 33 00" src="https://user-images.githubusercontent.com/85527/46839677-5bf48800-cdbf-11e8-8704-6e3027579cd5.png">

### Your environment
* macOS 10.14 Mojave
* Safari 12.0
* Adguard For Mac 1.5.8

**Comment by ameshkov** [comment]
Thank you! This issue will be resolved in the next update of AG for Mac.

**Comment by choco** [comment]
I'm using the Adguard nightly, and I can still reproduce this issue.

**Comment by ameshkov** [comment]
Yep, but it will be resolved in the next nightly update.
