### ISSUE TITLE
New UI for AdGuard 2.0

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#346]
UI sketches are shared in the Abstract.

* [x] Main menu
    * [x] Light theme
    * [x] Dark theme
* [x] Settings screens rework
    * [x] Introduce "Security" settings section

**Security** settings section:

* Phishing and malware protection
    **[Learn more about it.](https://kb.adguard.com/en/general/how-malware-protection-works)**
* Help us in Browsing security filters development
    **Submit anonymous security-related information.**

Phishing and malware protection -- enabled by default
Help us in Browsing security filters development -- disabled by default

**Comment by Jax0rz** [comment]
When will the dark mode come

**Comment by Jax0rz** [comment]
Could you release a beta version to test the Mojave dark mode

**Comment by ameshkov** [comment]
> Could you release a beta version to test the Mojave dark mode

Wait a bit, it'll soon arrive to the nightly channel.

**Comment by Jax0rz** [comment]
> > Could you release a beta version to test the Mojave dark mode
> 
> Wait a bit, it'll soon arrive to the nightly channel.

I can't wait ,because you app is the only app works in safari 12 with fully function( ublock is dead)
