### ISSUE TITLE
AdGuard does not filter Chrome Canary v72

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#349]
Version 72.0.3586.0 (Official Build) canary (64-bit), it's added to the Filterd apps list, however it's not filtered; ads are missed, the filtering log is empty.

### Steps to reproduce

1. Install Chrome Canary 72 or update from an older vrsion
2. Launch AdGuard
3. Open a website and check the log

### Expected behavior

Log is getting populated with requests, ads are blocked

### Actual behavior

The log is empty, ads are missed

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/47259847-ce98ee00-d4b8-11e8-97ed-491740e80885.png)

</details>

### Your environment

* Environment name and version: Chrome 72.0.3586.0 (Official Build) canary (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) none

**Comment by bondarev** [comment]
I have the same problem after Chrome Canary is updated.

**Comment by Eugene-Savenko** [comment]
Another report from https://qcrm.supportyourapp.com/#/customer/1435921:

> AdGuard does not work on Chrome 69 70 Chrome Beta Chrome Canary. I tried reinstalling. I can see the AdGuard Assistant icon on the left corner but after quitting Chrome and reopening, AdGuard is gone and ads are back. I’m using MacOS 10.14 Adguard 1.5.8

**Comment by ameshkov** [comment]
The hotfix is coming, guys.

**Comment by Stillness-2** [comment]
@Eugene-Savenko @bondarev please check this binary:
https://uploads.adguard.com/Adguard-1.5.9.beta.dmg

**Comment by dimanesterchuk** [comment]
1.5.9 бета — фильтрация восстановилась.

**Comment by bondarev** [comment]
@Stillness-2 1.5.9 beta works fine!

**Comment by ameshkov** [comment]
Awesome, thank you for testing it, guys!

@Stillness-2 @zebrum let's not wait for too long and publish the hotfix.
