### ISSUE TITLE
Get AdGuard for Mac kext notarized

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#350]
Check the details here:
https://help.apple.com/xcode/mac/current/#/dev88332a81e

and here:
https://developer.apple.com/developer-id/

**Comment by ameshkov** [comment]
Useful links:

* [Notarizing kexts](https://forums.developer.apple.com/thread/112135)
* [Customizing notarization](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/customizing_the_notarization_workflow?language=objc)
* [Apple: Common issues](https://developer.apple.com/documentation/security/notarizing_your_app_before_distribution/resolving_common_notarization_issues)

**Comment by Jax0rz** [comment]
When is the release date of the new nightly,I can't wait.I'm a life time license user of your app.

**Comment by ameshkov** [comment]
> When is the release date of the new nightly,I can't wait.I'm a life time license user of your app.

It's hard to say anything when we're talking about Apple :(

They didn't even care to notify developers about this new requirement, I received the official notification a few hours ago (2 days after Mac OS beta was released!).

We are working hard on getting the app notarized, I'll keep you posted.

**Comment by ameshkov** [comment]
@Jax0rz please try the new nightly version, kext is now notarized and it works on the new MacOS.

**Comment by rotu** [comment]
Can confirm the new nightly build resolves the issue on my system (10.14.5 Beta (18F108f))

**Comment by ezrazw** [comment]
The new nightly version works fine in 10.14.5 Beta 2 now.

**Comment by Jax0rz** [comment]
Thank you AdGuard team for the awesome support, it works fine in the latest nightly build.

**Comment by ameshkov** [comment]
Great, thank you for checking it guys!

The new beta is coming next week.
