### ISSUE TITLE
AdGuard does not filter Brave Browser 0.55

### ISSUE THREAD

**Issue by zebrum** [AdguardTeam/AdguardForMac#351]
### Steps to reproduce

1. Setup Brave browser (v0.55) and check if it is added to filtering apps list
2. go to any website

### Actual behavior
Filtering log is empty, no assistant icon, ads are not blocked

**Comment by zebrum** [comment]
related to #349

**Comment by zebrum** [comment]
quic are not being blocked on Mojave in brave v0.55.
AG v1.5.10

**Comment by ameshkov** [comment]
It's not too long till v2.0 so let's just reassign it
