### ISSUE TITLE
Welcoming UI and app menu in AdGuard Nightly have some issues (screenshots provided)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#359]
MacOS Mojave 10.14.1 Beta
AdGuard Nightly 2.0.0.481

![captura de pantalla 2018-11-03 a la s 14 30 25](https://user-images.githubusercontent.com/44731792/47955388-56313300-df76-11e8-8a8e-281d42a7df08.png)
![captura de pantalla 2018-11-03 a la s 14 30 36](https://user-images.githubusercontent.com/44731792/47955389-57626000-df76-11e8-808b-793485ff152f.png)
![captura de pantalla 2018-11-03 a la s 14 30 40](https://user-images.githubusercontent.com/44731792/47955390-57faf680-df76-11e8-944b-1bab2a59be75.png)
![captura de pantalla 2018-11-03 a la s 14 30 44](https://user-images.githubusercontent.com/44731792/47955391-59c4ba00-df76-11e8-8898-8e830bd953c2.png)
![captura de pantalla 2018-11-03 a la s 14 30 48](https://user-images.githubusercontent.com/44731792/47955392-5a5d5080-df76-11e8-88e6-0b5932ec26e0.png)
![captura de pantalla 2018-11-03 a la s 14 40 32](https://user-images.githubusercontent.com/44731792/47955404-73660180-df76-11e8-809b-ada97476fd65.png)

**Comment by LucasDiTomase** [comment]
In the welcoming UI, as you can see, some elements are missing. In the app menu, the part that reads "¡Tu equipo está protegido!" (your device is protected), is barely visible (don't know if its a bug or just a redesign )

**Comment by ameshkov** [comment]
Hm, could it be that you're on Mojave dark theme?

**Comment by LucasDiTomase** [comment]
Thats right! Is it a known bug?

**Comment by ameshkov** [comment]
@LucasDiTomase yeah, the UI is not yet Mojave-ready, we were focused on the filtering engine mostly. Now it's time to polish the UI :)

**Comment by LucasDiTomase** [comment]
Great! Thanks for replying. Awesome tool BTW
