### ISSUE TITLE
Handle complaint on a website reported from the Assistant

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#361]
Once this is implemented on CoreLibs side:
https://github.com/AdguardTeam/CoreLibs/issues/595

Just like Win and Android version, you should build a link to `reports.adguard.com/new_issue` with parameters filled with the current app configuration.

**Comment by sfionov** [comment]
CoreLibs sends onBrowserApiRequest for "send-abuse" command.
