### ISSUE TITLE
Issues with Privacy Settings UI

### ISSUE THREAD

**Issue by BeQ** [AdguardTeam/AdguardForMac#362]
### Steps to reproduce

1. open preferences -> privacy
2. click "configure" button close to "strip tracking parameters"

### Expected behavior
"close" button should close panel

### Actual behavior
nothing happens

### Your environment
macos 10.12.3
adguard 2.0.0.481

**Comment by zzebrum** [comment]
not reproduced on 10.13 so far, will check on Sierra.

**Comment by zzebrum** [comment]
reproduced on 10.12 and 10.11

**Comment by zzebrum** [comment]
@BeQ do have a problem to close settings window after you stuck on it?  I can't quit AG regular way and have to use Activity Monitor to force quit.

**Comment by BeQ** [comment]
yes, force quit is the only option to close this panel.

**Comment by Stillness-2** [comment]
#411 related
