### ISSUE TITLE
[Feature Request] Self-Destructing First-Party Cookies Exceptions

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdguardForMac#370]
Regarding Self-Destructing First-Party Cookies, there should be a whitelist with its own Time to Live.

Example use cases:
I want my Amazon cookies to be remembered so I don't get signed out. (Whitelist)
I don't want every news website I visit to set cookies.

**Comment by ameshkov** [comment]
Nice feature request btw.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #613](https://github.com/AdguardTeam/CoreLibs/issues/613) via [**ZenHub**](https://www.zenhub.com/)
