### ISSUE TITLE
Adguard Assistant Not Showing

### ISSUE THREAD

**Issue by JonoHaysom** [AdguardTeam/AdguardForMac#372]
Issue with the Adguard assistant not showing on certain websites.

Steps to reproduce
1. head to MacRumors.com (or apple.com)
2. the Adguard Assistant is now available (ads are being correctly blocked however)
3. head to other websites and its showing

Expected behaviour
Adguard Assistant should show

Actual behavior
Adguard assistant is not visible or able to be summoned

Your environment
Using Safari 12.0.2 and AdGuard 2.0.0.484 Nightly
basic filters are enabled.

**Comment by JonoHaysom** [comment]
Another option would be to have AdGuard show as a contextual menu item rather than a overlay button.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #263](https://github.com/AdguardTeam/AdguardAssistant/issues/263) via [**ZenHub**](https://www.zenhub.com/)
