### ISSUE TITLE
Upload interrupted in Safari but keeps going in Adguard

### ISSUE THREAD

**Issue by choco** [AdguardTeam/AdguardForMac#374]
This is a really strange issue, when I try to do a speedtest on http://www.dslreports.com/speedtest (I select gigabit as connection type) when the test starts the upload part, after a couple of seconds the upload speed goes to 0 and the test reports the error. But with LittleSnitch I can see that the connection is actually still active, and Adguard is still uploading data.

This is the first time I can actually reproduce it reliably, but it has already happened that a connection is still active in Adguard (whether in up or download)  while the browser is already closed or reporting it as disconnected.

macOS 10.14.1 
Aguard Nightly 2.0.0.484
(but I can reproduce it even with the current stable release)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #615](https://github.com/AdguardTeam/CoreLibs/issues/615) via [**ZenHub**](https://www.zenhub.com/)
