### ISSUE TITLE
Bug: Adguard for Mac won't work with non-system proxy in Google Chrome

### ISSUE THREAD

**Issue by Jason4V** [AdguardTeam/AdguardForMac#377]
### Steps to reproduce
I have taken a video record to demo how to reproduce this bug: https://youtu.be/SpYCv8rXW7Q

### Expected behavior

It should block ads with proxy ( actually it really works with system-wide proxy)

### Customer ID 
**User ID**: 2037941

### Your environment
Adguard 1.5.10
macOS 10.13.6
Chrome Version 70.0.3538.102 (Official Build) (64-bit)

Thank you!

**Comment by ameshkov** [comment]
Hi! It works okay in the latest nightly build:
https://adguard.com/en/blog/adguard-for-mac-gets-nightly/

**Comment by ImHUan** [comment]
@ameshkov   
Hi, I have installed the[ nightly build ](http://static.adguard.com/mac/Adguard.nightly.dmg) you gave me then find it won't work as before. See the snap:

![wx20181119-085014](https://user-images.githubusercontent.com/385914/48680661-3c2f5b80-ebd8-11e8-8d7f-65544b700a4c.png)

**Comment by ameshkov** [comment]
Hm, weird, I use switchy omega as well and have no issues with that.

What type of proxy do you use? HTTP/SOCKS/anything else?

**Comment by ImHUan** [comment]
I am using socks5, 127.0.0.1:1081 @ameshkov

**Comment by ameshkov** [comment]
Ah, so it's a local proxy. It explains why it does not work:)

You should add the proxy app to the list of filtered apps in AdGuard (settings -> network -> filtered apps).

**Comment by ImHUan** [comment]
Thank you @ameshkov  I will try your fix later ;)

**Comment by ImHUan** [comment]
Hi @ameshkov I have add my proxy app [V2RayX](https://github.com/Cenmrev/V2RayX), which is a GUI of [v2ray-core ](https://github.com/v2ray/v2ray-core), to AdGuard filter app list but do NOT work :(

Check out my screen:
![screen shot 2018-11-20 at 08 35 41](https://user-images.githubusercontent.com/385914/48743733-4bc5a780-ec9f-11e8-9093-356c63faec9c.png)

**Comment by ameshkov** [comment]
@ImHUan and this one most likely is a bug:) filed a new one:
https://github.com/AdguardTeam/AdguardForMac/issues/378

**Comment by ImHUan** [comment]
OK, I'm glad to find a new bug for you and looking forward to the later fix!

Btw, you are the best ad blocker I ve used and new anti-tracker features in 2.0 are fantastic!

**Comment by ameshkov** [comment]
Thank you:) Please note that v2 nightly is a tad unstable, we have a lot to do before it's ready to become a beta or stable version.

**Comment by ImHUan** [comment]
Got it. I will back to 1.5 and wait your stable version :)

**Comment by ameshkov** [comment]
@ImHUan downgrade is a bit complicated.

1. Run AG v2.0
2. Menu -> Advanced -> Reset Settings...
3. Click Quit after that (do not restart it back)
4. Replace AG v2.0 with 1.5

**Comment by Jason4Van** [comment]
Hi @ameshkov I have upgrade to v2.0.4 but this issue happened again.  eg [this page](https://greasyfork.org/en/scripts/14178-ac-baidu-%E9%87%8D%E5%AE%9A%E5%90%91%E4%BC%98%E5%8C%96%E7%99%BE%E5%BA%A6%E6%90%9C%E7%8B%97%E8%B0%B7%E6%AD%8C%E6%90%9C%E7%B4%A2-%E5%8E%BB%E5%B9%BF%E5%91%8A-favicon-%E5%8F%8C%E5%88%97) and see this snap: 
<img width="1113" alt="1" src="https://user-images.githubusercontent.com/385914/58881620-19483d00-870d-11e9-90ce-fafff45f6be6.png">

**Comment by ameshkov** [comment]
@Jason4Van could you please check if V2RayX is still in the list of filtered apps?

**Comment by Jason4Van** [comment]
wow, you are right @ameshkov I add it to filter list then it works fine. Thanks!

**Comment by Jason4Van** [comment]
@ameshkov  
 Excuse me for telling this bug happened again today, I have add the v2ray app to the list of filtered apps which appears in the filter log:
<img width="1616" alt="Screen Shot 2019-06-07 at 21 44 15" src="https://user-images.githubusercontent.com/385914/59108588-d76a0180-896d-11e9-99e0-93b0592aab51.png">

It seems adguard can not check the encrypted websocket protocol?

**Comment by ameshkov** [comment]
@Jason4Van does it help to restart AG

**Comment by Jason4Van** [comment]
<img width="1236" alt="Screen Shot 2019-06-08 at 09 38 58" src="https://user-images.githubusercontent.com/385914/59140524-4298ef80-89d1-11e9-994c-50519e4cd567.png">

No good news. Even I restarted macOS.

**Comment by Jason4Van** [comment]
No good news. Even I restarted macOS. @ameshkov

![](https://user-images.githubusercontent.com/385914/59140524-4298ef80-89d1-11e9-994c-50519e4cd567.png)

**Comment by ameshkov** [comment]
@Jason4Van could you please record debug log for us?

1. Switch logging level to "Debug" (menu -> advanced -> logging level -> debug)
2. Restart AdGuard protection
3. Reproduce the issue
4. Export logs via the menu
5. Send them to `devteam@adguard.com` and comment here

**Comment by Jason4Van** [comment]
I followed your method exactly and tried 3 times. Logs have been sent by email to devteam@adguard.com. Thank you  @ameshkov

**Comment by ameshkov** [comment]
@Jason4Van hmm, I've not received anything. Could you please also send it to `am at adguard.com`?

**Comment by Jason4Van** [comment]
Sent you by account is jason4van A me.com.  Check the spam box? here is the last sent mail
![a](https://user-images.githubusercontent.com/385914/59182092-70ca2b00-8b9b-11e9-987e-f0d7e25e420e.jpg)

**Comment by ameshkov** [comment]
@Stillness-2 logs are moved to the private NextCloud, could you please take a look?

**Comment by Stillness-2** [comment]
@Jason4Van 
It does not make sense to add V2Ray to the list of apps for filtering, since outgoing traffic may be over a protocol that is not processed by AdGuard. However, AdGuard must filter outgoing browser connections, that is, be built between Chrome and V2Ray. But by default, outgoing traffic from the filtered application on the localhost and local network is not filtered! 
AdGuard automatically adds system proxy addresses to the exception from this rule. Therefore, when V2Ray is configured to replace the system proxy, the filtering works, regardless of the fact that the proxy is on a localhost.
 
AdGuard has a hidden configuration parameter that allows you to enable filtering for connections on a localhost/local network. You may use this commands in Terminal.app:

`defaults write com.adguard.mac.adguard FilteringLocalNetworkEnabled YES` - turn on filtering local traffic

`defaults write com.adguard.mac.adguard FilteringLocalNetworkEnabled NO` - turn off

**Comment by Jason4Van** [comment]
Hi @Stillness-2  I followed and used your commands to turn on filtering local traffic. Now Chrome starts to work well! Thank you :) 
 I think the reason is that because I used [this chrome extension ](https://chrome.google.com/webstore/detail/padekgcemlokbadohgkifijomclgjgif) to set proxy port only for chrome rathe than setting system proxy port for all apps.
