### ISSUE TITLE
Adguard filtering broken after sleep

### ISSUE THREAD

**Issue by choco** [AdguardTeam/AdguardForMac#380]
This started with the nightlies, or at least I was never affected before.

Sometimes after I reopen the lid on my Macbook, Adguard filtering is broken.
Broken in the sense that all connections are stuck, i.e. any application filtered by Adguard acts like there's no internet connection (more specifically like the servers don't respond).
Enabling and disabling Adguard from the menubar doesn't fix the issue, I need to force quit Adguard (if I try to quit it, it stops responding).

macOS Mojave 10.14.1
Adguard Nightly 2.0.487

**Comment by zzebrum** [comment]
@choco can you collect logs, please? Go to AdGuard icon - settings - support, check that 'Attach the diagnostic report' is on and send a message to the support team. After that, you will receive an autoreply email with your user_id - post it here so we could find your logs.

**Comment by choco** [comment]
@zzebrum here's the user_id: 559578

**Comment by choco** [comment]
This bug got even worse since I reported it, not sure if because of newer nightlies or 10.14.2 macOS update. Or maybe it's another bug I really don't know, I had to stop using the nightly because it made my Mac unusable...

It happens even without going to sleep, sometime all networking stops working, even local sockets!!! This basically makes the entire system come to a halt; I have to force restart it in these situations....

**Comment by ameshkov** [comment]
It sounds like some kind of a compatibility issue, and you're the only one reporting it.

Do you have any other network-filtering software installed? A Firewall, Antivirus, or anything like that?

**Comment by choco** [comment]
I have Little Snitch installed, latest version. I never experienced this specific issue with pre-2.0 versions.

**Comment by zzebrum** [comment]
@choco can you disable Little Snitch for a while. I'll try to reproduce the issue on my side too.

**Comment by ameshkov** [comment]
> I have Little Snitch installed

What exact version of it?

**Comment by choco** [comment]
> > I have Little Snitch installed
> 
> What exact version of it?

4.2.4

**Comment by zzebrum** [comment]
@choco any update? Have you updated AG nightly version to v2.0.0(500)?

**Comment by choco** [comment]
Haven't been able to reproduce it with latest AG nightly, will report back if it happens again
