### ISSUE TITLE
Adguard icon is blocking us from the clicking the street view icon in google maps

### ISSUE THREAD

**Issue by tk120404** [AdguardTeam/AdguardForMac#382]
### Steps to reproduce

1. Goto https://www.google.com/maps/@25.2531793,55.3634841,17z
2. Adguard icon is blocking us from the clicking the street view icon in google maps

If we can move the icon, then it will be great

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by ameshkov** [comment]
> If we can move the icon, then it will be great

You actually can (in AG v2.0 nightly)
