### ISSUE TITLE
Add Spotify to the default filtered applications list

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#383]
Noticed AdGuard for macOS doesn't include Spotify by default like Windows does. Adding Spotify to the filtered applications list does work well, so could it be included by default?

**Comment by ameshkov** [comment]
Yeah, why not

**Comment by planet0** [comment]
Could we also add Steam to the list by default? Also noticed it already in the Windows version, but not the Mac version.

**Comment by ameshkov** [comment]
Huh, here is why not:
https://www.theverge.com/2019/2/7/18215845/spotify-ad-blockers-terms-of-service
