### ISSUE TITLE
Indicate what cookies were modified in the filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#386]
Currently, it is not shown in the filtering log

here's how cookie modification looks like in the new browser extension version:

* https://uploads.adguard.com/up04_79yg6_Filtering_log.png
* https://uploads.adguard.com/up04_3ud0c_Filtering_log.png

https://github.com/AdguardTeam/AdguardBrowserExtension/issues/961

**Comment by Stillness-2** [comment]
Also we work here on tasks from 
https://github.com/AdguardTeam/AdguardForWindows/issues/2427

1. [ ] It reports that HTML elements are removed from jpg, CSS, JS files, that cannot be so: https://uploads.adguard.com/up04_1qrhx_Windows_7_Enterprise_1.png

-----

1. [ ] We should use the same statuses we get from CoreLibs:
2. [ ] Color indication
    * Blocked - red
    * Modified - yellow
    * Whitelisted - green
    * Bypassed - no color
3. [ ] Show the full list of rules applied to the request in the log item details (including whitelist, cookie, csp, whatever).
4. [ ] Additionally, show the stealth mode actions applied (if any)
5. [ ] Exceptions: removed cookies and removed HTML elements should be separate items in the filtering log (just like we do now).
6. [ ] "Size" value should be replaced with `↑3.0 KB ↓15.0 KB`. That's important to understand what's the size of uploaded data.
7. [ ] Rule column value:
    * Do not print `$$`, `$cookie`, and `$stealth` rules there;
    * In the case of a single rule, just print it there;
    * In the case of multiple rules applied, print "5 rules";
    * If no rules were applied, but status is modified:
        * If there are any stealth mode actions applied, print "Stealth mode"
        * If this is a "Document", print "Cosmetic rules"
        * In any other case this might be a bug of CoreLibs:)
8. [ ] Print `Connection ID` for processed requests as well
