### ISSUE TITLE
macOS Crash with AdGuard 2.0.0.491 nightly

### ISSUE THREAD

**Issue by cvandray** [AdguardTeam/AdguardForMac#391]
macOS crash using AdGuard 2.0.0.491 nightly.

Please see following kernel panic report:

Anonymous UUID:       F70FE6EB-503E-07B1-D336-C140B724DF39

Fri Dec 14 11:20:55 2018

*** Panic Report ***
panic(cpu 0 caller 0xffffff800d7ab905): "tcp_lock: so=0xffffff804661b600 NO PCB! lr=0xffffff7f94211150 lrh= 0xffffff800d92ca7b:0xffffff800d9478ac 0xffffff7f8e0899d8:0xffffff800d949cdc 0xffffff800d91c379:0xffffff800d9478ac 0xffffff7f8e0899d8:0xffffff800d949cdc \n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-4903.231.4/bsd/netinet/tcp_subr.c:3125
Backtrace (CPU 0), Frame : Return Address
0xffffff9201d83a20 : 0xffffff800d3aeafd 
0xffffff9201d83a70 : 0xffffff800d4e85a3 
0xffffff9201d83ab0 : 0xffffff800d4d9fca 
0xffffff9201d83b20 : 0xffffff800d35bca0 
0xffffff9201d83b40 : 0xffffff800d3ae517 
0xffffff9201d83c60 : 0xffffff800d3ae363 
0xffffff9201d83cd0 : 0xffffff800d7ab905 
0xffffff9201d83d10 : 0xffffff800d91f308 
0xffffff9201d83d30 : 0xffffff7f94211150 
0xffffff9201d83d80 : 0xffffff800d949b5f 
0xffffff9201d83dc0 : 0xffffff800d91c54d 
0xffffff9201d83de0 : 0xffffff800d7ad3ab 
0xffffff9201d83e50 : 0xffffff800d7ad0d3 
0xffffff9201d83e70 : 0xffffff800d773c51 
0xffffff9201d83ec0 : 0xffffff800d3eaf65 
0xffffff9201d83f40 : 0xffffff800d3eab15 
0xffffff9201d83fa0 : 0xffffff800d35b0ce 
      **Kernel Extensions in backtrace:
         com.adguard.nfext(19.0)[90B6D809-0CD6-3561-AD80-F48266F9BE85]@0xffffff7f9420f000->0xffffff7f9423afff**

BSD process name corresponding to current thread: kernel_task

Mac OS version:
18C54

Kernel version:
Darwin Kernel Version 18.2.0: Mon Nov 12 20:24:46 PST 2018; root:xnu-4903.231.4~2/RELEASE_X86_64
Kernel UUID: 56B30885-F9BA-30E8-AD1C-5D59EC243BA9
Kernel slide:     0x000000000d000000
Kernel text base: 0xffffff800d200000
__HIB  text base: 0xffffff800d100000
System model name: MacBookPro13,3 (Mac-A5C67F76ED83108C)

System uptime in nanoseconds: 41067836298210
last loaded kext at 26576184779682: com.apple.driver.usb.cdc.acm	5.0.0 (addr 0xffffff7f94251000, size 32768)
loaded kexts:
fi.dungeon.driver.SATSMARTDriver	0.10
com.adguard.nfext	19
com.sophos.kext.oas	9.7.4
com.sophos.nke.swi	9.7.4
com.sophos.kext.sfm	9.7.4
com.paragon-software.filesystems.ntfs	11.4.15
com.paragon-software.kext.VDMounter	1370.2
com.apple.iokit.SCSITaskUserClient	408.200.1
com.apple.driver.AppleAHCIPort	329.200.2
com.apple.filesystems.msdosfs	1.10
com.apple.driver.AppleBluetoothMultitouch	96
com.apple.driver.AudioAUUC	1.70
com.apple.fileutil	18.306.12
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.23.46
com.apple.driver.ApplePlatformEnabler	2.7.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleUpstreamUserClient	3.6.5
com.apple.driver.AppleHDAHardwareConfigDriver	282.10
com.apple.kext.AMDFramebuffer	2.0.4
com.apple.driver.AppleHIDALSService	1
com.apple.driver.AppleHDA	282.10
com.apple.kext.AMDRadeonX4000	2.0.4
com.apple.driver.AppleGraphicsDevicePolicy	3.28.4
com.apple.AGDCPluginDisplayMetrics	3.28.4
com.apple.driver.AppleHV	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	6.0.9f2
com.apple.driver.pmtelemetry	1
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleIntelSKLGraphics	12.0.4
com.apple.driver.AppleIntelPCHPMC	2.0.1
com.apple.kext.AMD9500Controller	2.0.4
com.apple.driver.AGDCBacklightControl	3.28.4
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.SMCMotionSensor	3.0.4d1
com.apple.driver.eficheck	1
com.apple.driver.AppleGFXHDA	100.1.40
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleMuxControl	3.28.4
com.apple.driver.AppleBacklight	170.12.11
com.apple.driver.AppleMCCSControl	1.5.6
com.apple.driver.AppleEmbeddedOSSupportHost	1
com.apple.driver.ACPI_SMC_PlatformPlugin	1.0.0
com.apple.driver.AppleIntelSKLGraphicsFramebuffer	12.0.4
com.apple.driver.AppleFIVRDriver	4.1.0
com.apple.driver.AppleThunderboltIP	3.1.2
com.apple.driver.AppleFileSystemDriver	3.0.1
com.apple.driver.AppleVirtIO	2.1.2
com.apple.filesystems.hfs.kext	407.200.4
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.BootCache	40
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.AppleSystemPolicy	1.0
com.apple.driver.AppleTopCaseHIDEventDriver	138.2
com.apple.filesystems.apfs	945.230.6
com.apple.driver.AirPort.BrcmNIC	1400.1.1
com.apple.private.KextAudit	1.0
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleACPIButtons	6.1
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	6.1
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	190
com.apple.security.TMSafetyNet	8
com.apple.driver.usb.cdc.acm	5.0.0
com.apple.driver.usb.serial	6.0.0
com.apple.iokit.IOAHCIBlockStorage	301.200.2
com.apple.iokit.IOAHCIFamily	288
com.apple.driver.AppleThunderboltPCIUpAdapter	2.1.4
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	282.10
com.apple.kext.OSvKernDSPLib	527
com.apple.kext.AMDRadeonX4100HWLibs	1.0
com.apple.kext.AMDRadeonX4000HWServices	2.0.4
com.apple.iokit.IOAVBFamily	710.1
com.apple.plugin.IOgPTPPlugin	700.7
com.apple.iokit.IOEthernetAVBController	1.1.0
com.apple.driver.AppleSSE	1.0
com.apple.iokit.IOBluetoothHostControllerUARTTransport	6.0.9f2
com.apple.iokit.IOBluetoothHostControllerTransport	6.0.9f2
com.apple.AppleGPUWrangler	3.28.4
com.apple.driver.AppleHDAController	282.10
com.apple.iokit.IOHDAFamily	282.10
com.apple.kext.AMDSupport	2.0.4
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleSMBusPCI	1.0.14d1
com.apple.driver.AppleGraphicsControl	3.28.4
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.iokit.IONDRVSupport	530
com.apple.driver.AppleSMBusController	1.0.18d1
com.apple.driver.IOPlatformPluginLegacy	1.0.0
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.IOPlatformPluginFamily	6.0.0d8
com.apple.AppleGraphicsDeviceControl	3.28.4
com.apple.iokit.IOAcceleratorFamily2	404.2.2
com.apple.iokit.IOGraphicsFamily	530.14
com.apple.iokit.IOSurface	255.1
com.apple.driver.AppleIntelLpssUARTv1	3.0.60
com.apple.driver.AppleIntelLpssUARTCommon	3.0.60
com.apple.driver.AppleOnboardSerial	1.0
com.apple.iokit.IOSkywalkFamily	1
com.apple.driver.AppleThunderboltEDMSink	4.2.0
com.apple.driver.AppleThunderboltDPOutAdapter	5.5.8
com.apple.driver.usb.cdc.ecm	5.0.0
com.apple.driver.usb.cdc.ncm	5.0.0
com.apple.driver.AppleUSBAudio	315.6
com.apple.driver.usb.IOUSBHostHIDDevice	1.2
com.apple.iokit.IOAudioFamily	206.5
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.AppleUSBiBridge	1.0
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.2
com.apple.driver.AppleUSBHostMergeProperties	1.2
com.apple.iokit.IOSerialFamily	11
com.apple.filesystems.hfs.encodings.kext	1
com.apple.driver.AppleActuatorDriver	2410.5
com.apple.driver.AppleHIDKeyboard	208
com.apple.driver.AppleHSBluetoothDriver	138.2
com.apple.driver.IOBluetoothHIDDriver	6.0.9f2
com.apple.iokit.IOBluetoothFamily	6.0.9f2
com.apple.driver.AppleMultitouchDriver	2410.5
com.apple.driver.AppleInputDeviceSupport	2410.2
com.apple.driver.AppleHSSPIHIDDriver	55
com.apple.driver.AppleThunderboltDPInAdapter	5.5.8
com.apple.driver.AppleThunderboltDPAdapterFamily	5.5.8
com.apple.driver.AppleThunderboltPCIDownAdapter	2.1.4
com.apple.driver.AppleXsanScheme	3
com.apple.driver.AppleHSSPISupport	55
com.apple.driver.AppleIntelLpssSpiController	3.0.60
com.apple.iokit.IO80211Family	1200.12.2
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.driver.corecapture	1.0.4
com.apple.iokit.IONVMeFamily	2.1.0
com.apple.driver.AppleThunderboltNHI	4.7.6
com.apple.driver.AppleHPM	3.3.0
com.apple.iokit.IOThunderboltFamily	6.8.1
com.apple.driver.AppleIntelLpssI2CController	3.0.60
com.apple.driver.AppleIntelLpssDmac	3.0.60
com.apple.driver.AppleIntelLpssI2C	3.0.60
com.apple.driver.AppleIntelLpssGspi	3.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.2
com.apple.driver.usb.AppleUSBXHCI	1.2
com.apple.driver.usb.AppleUSBHostPacketFilter	1.0
com.apple.iokit.IOUSBFamily	900.4.2
com.apple.driver.AppleEFINVRAM	2.1
com.apple.driver.AppleEFIRuntime	2.1
com.apple.iokit.IOSMBusFamily	1.1
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.security.quarantine	3
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.DiskImages	493.0.0
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleEffaceableStorage	1.0
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleUSBTDM	456.230.1
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.kext.CoreTrust	1
com.apple.iokit.IOUSBMassStorageDriver	145.200.2
com.apple.iokit.IOSCSIBlockCommandsDevice	408.200.1
com.apple.iokit.IOSCSIArchitectureModelFamily	408.200.1
com.apple.iokit.IOStorageFamily	2.1
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.KernelRelayHost	1
com.apple.iokit.IOUSBHostFamily	1.2
com.apple.driver.usb.AppleUSBCommon	1.0
com.apple.driver.AppleBusPowerController	1.0
com.apple.driver.AppleSEPManager	1.0.1
com.apple.driver.IOSlaveProcessor	1
com.apple.iokit.IOReportFamily	47
com.apple.iokit.IOTimeSyncFamily	700.7
com.apple.iokit.IONetworkingFamily	3.4
com.apple.driver.AppleACPIPlatform	6.1
com.apple.driver.AppleSMC	3.1.9
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.pthread	1
com.apple.kec.Libm	1
com.apple.kec.corecrypto	1.0

EOF

**Comment by cvandray** [comment]
No it is not easy to reproduce and in fact, I have just upgraded to 2.0.0.493 nightly.
My only indication that my macOS kernel panic was likely caused by the AdGuard beta release was that the log pointed in that direction from the back trace information.

I will report back if it happens again.

Thanks.

**Comment by zzebrum** [comment]
@cvandray hello! any update on this? Have you tried v2.0.0.(500)?

**Comment by DasBlatz** [comment]
please reopen v2.0.0.(504) start crashing again and also slow down video conference connection on appear.in

**Comment by zzebrum** [comment]
@DasBlatz please, after a crash happens, run AG and send a crash report.

**Comment by DasBlatz** [comment]
already done 5 times @zzebrum 

fixed my problem by reseting Adguard completely und start fresh.

**Comment by cvandray** [comment]
Just installed v2.0.0.50 nightly and will report any issues.
So far so good!

**Comment by cvandray** [comment]
Running smoothly on v2.0.0.511 nightly and no crashing in the last 30 days.
Smooth going from now on!

**Comment by SHuang-Broad** [comment]
I am seeing this again

```

panic(cpu 6 caller 0xffffff8007b4aa1a): "tcp_lock: so=0xffffff807cead3c0 NO PCB! lr=0xffffff7f8ea95fcf lrh= 0xffffff8007cdf81b:0xffffff8007cfe4f6 0xffffff8007cce27d:0xffffff8007cfe4f6 0xffffff8007cde1bd:0xffffff8007cfe4f6 0xffffff8007cde1bd:0xffffff8007b3b352 \n"@/AppleInternal/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.141.1/bsd/netinet/tcp_subr.c:3309
Backtrace (CPU 6), Frame : Return Address
0xffffffa3ee2eba10 : 0xffffff800771a65d 
0xffffffa3ee2eba60 : 0xffffff8007854a75 
0xffffffa3ee2ebaa0 : 0xffffff80078465fe 
0xffffffa3ee2ebaf0 : 0xffffff80076c0a40 
0xffffffa3ee2ebb10 : 0xffffff8007719d27 
0xffffffa3ee2ebc10 : 0xffffff800771a117 
0xffffffa3ee2ebc60 : 0xffffff8007ec1abc 
0xffffffa3ee2ebcd0 : 0xffffff8007b4aa1a 
0xffffffa3ee2ebd00 : 0xffffff8007cd1208 
0xffffffa3ee2ebd20 : 0xffffff7f8ea95fcf 
0xffffffa3ee2ebd70 : 0xffffff8007cfe352 
0xffffffa3ee2ebda0 : 0xffffff8007cce43d 
0xffffffa3ee2ebdc0 : 0xffffff8007b4c988 
0xffffffa3ee2ebe30 : 0xffffff8007b4c5de 
0xffffffa3ee2ebe50 : 0xffffff8007b0a971 
0xffffffa3ee2ebec0 : 0xffffff800775c605 
0xffffffa3ee2ebf40 : 0xffffff800775c131 
0xffffffa3ee2ebfa0 : 0xffffff80076c013e 
      Kernel Extensions in backtrace:
         com.adguard.nfext(27.0)[4AF16C66-CBFC-369B-8F0A-6FB96F1D536E]@0xffffff7f8ea94000->0xffffff7f8eabffff

BSD process name corresponding to current thread: kernel_task
Boot args: chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
19G2021

Kernel version:
Darwin Kernel Version 19.6.0: Thu Jun 18 20:49:00 PDT 2020; root:xnu-6153.141.1~1/RELEASE_X86_64
Kernel UUID: 1D3A0F3D-D908-397B-BD16-8F48C0823A2E
Kernel slide:     0x0000000007400000
Kernel text base: 0xffffff8007600000
__HIB  text base: 0xffffff8007500000
System model name: MacBookPro16,1 (Mac-E1008331FDC96864)
System shutdown begun: NO

System uptime in nanoseconds: 159130987423231
last loaded kext at 143464699886931: >!AXsanScheme	3 (addr 0xffffff7f8bec5000, size 32768)
last unloaded kext at 140878599093529: >!UAudio	323.4 (addr 0xffffff7f8eac0000, size 434176)
loaded kexts:
com.adguard.nfext	27
com.sentinelone.sentinel-kext	2982
>AudioAUUC	1.70
@kext.AMDRadeonX6000	3.1.0
@kext.AMDRadeonServiceManager	3.1.0
>!AGraphicsDevicePolicy	5.2.6
@fileutil	20.036.15
@AGDCPluginDisplayMetrics	5.2.6
>!AHV	1
|IOUserEthernet	1.0.1
|IO!BSerialManager	7.0.6f7
>AGPM	111.4.4
>!APlatformEnabler	2.7.0d0
>X86PlatformShim	1.0.0
>pmtelemetry	1
>!AUpstreamUserClient	3.6.8
@Dont_Steal_Mac_OS_X	7.0.0
>!A!IKBLGraphics	14.0.7
>AGDCBacklightControl	5.2.6
>BridgeAudioCommunication	6.70.7
>!ATopCaseHIDEventDriver	3430.1
>!AHIDALSService	1
>!AThunderboltIP	3.1.4
>!A!ISlowAdaptiveClocking	4.0.0
>!AAVEBridge	6.1
>!A!IPCHPMC	2.0.1
>!AMuxControl2	5.2.6
>!ABridgeAudio!C	6.70.7
>!AGFXHDA	100.1.429
>!A!ICFLGraphicsFramebuffer	14.0.7
>!AMCCSControl	1.14
@filesystems.autofs	3.0
>BCMWLANFirmware4355.Hashstore	1
>BCMWLANFirmware4364.Hashstore	1
>BCMWLANFirmware4377.Hashstore	1
>!ABCMWLANBusInterfacePCIe	1
@filesystems.hfs.kext	522.100.5
@BootCache	40
@!AFSCompression.!AFSCompressionTypeDataless	1.0.0d1
@!AFSCompression.!AFSCompressionTypeZlib	1.0.0
>!AVirtIO	1.0
@filesystems.apfs	1412.141.1
@private.KextAudit	1.0
>!ASmartBatteryManager	161.0.0
>!AACPIButtons	6.1
>!ASMBIOS	2.1
>!AACPIEC	6.1
>!AAPIC	1.7
$!AImage4	1
@nke.applicationfirewall	303
$TMSafetyNet	8
@!ASystemPolicy	2.0.0
|EndpointSecurity	1
>!AXsanScheme	3
>usb.IOUSBHostHIDDevice	1.2
>!UAudio	323.4
@kext.AMDRadeonX6100HWLibs	1.0
@kext.AMDRadeonX6000HWServices	3.1.0
|IOAVB!F	850.1
@!AGPUWrangler	5.2.6
>!AHIDKeyboard	209
>!AActuatorDriver	3440.1
>!AHS!BDriver	3430.1
>IO!BHIDDriver	7.0.6f7
>!AMultitouchDriver	3440.1
>!AInputDeviceSupport	3440.8
@kext.AMDRadeonX6000Framebuffer	3.1.0
>!ABacklightExpert	1.1.0
|IO!BHost!CUARTTransport	7.0.6f7
|IO!BHost!CTransport	7.0.6f7
>!A!ILpssUARTv1	3.0.60
>!A!ILpssUARTCommon	3.0.60
>!AOnboardSerial	1.0
>X86PlatformPlugin	1.0.0
|IOSlowAdaptiveClocking!F	1.0.0
>IOPlatformPlugin!F	6.0.0d8
>!AGraphicsControl	5.2.6
@plugin.IOgPTPPlugin	840.3
|IOEthernetAVB!C	1.1.0
|IONDRVSupport	576.1
@kext.AMDSupport	3.1.0
@!AGraphicsDeviceControl	5.2.6
|IOAccelerator!F2	438.7.3
>!ASMBus!C	1.0.18d1
|IOGraphics!F	576.1
@kext.triggers	1.0
>usb.cdc.ncm	5.0.0
>usb.cdc	5.0.0
>usb.networking	5.0.0
>usb.!UHostCompositeDevice	1.2
>!ABCMWLANCore	1.0.0
>mDNSOffloadUserClient	1.0.1b8
>IOImageLoader	1.0.0
|IO80211!FV2	1200.12.2b1
>corecapture	1.0.4
|IOSkywalk!F	1
|IOSurface	269.11
@filesystems.hfs.encodings.kext	1
|IOAudio!F	300.2
@vecLib.kext	1.2.0
|IOSerial!F	11
>usb.!UVHCIBCE	1.2
>usb.!UVHCI	1.2
>usb.!UVHCICommonBCE	1.0
>usb.!UVHCICommon	1.0
>!AEffaceableNOR	1.0
|IOBufferCopy!C	1.1.0
|IOBufferCopyEngine!F	1
|IONVMe!F	2.1.0
>!AThunderboltPCIDownAdapter	2.5.4
>!AThunderboltDPInAdapter	6.2.6
>!AThunderboltDPAdapter!F	6.2.6
>!AHPM	3.4.4
>!A!ILpssI2C!C	3.0.60
>!A!ILpssDmac	3.0.60
>!A!ILpssI2C	3.0.60
>!AThunderboltNHI	5.8.6
|IOThunderbolt!F	7.6.1
|IOUSB!F	900.4.2
>usb.!UXHCIPCI	1.2
>usb.!UXHCI	1.2
>!AEFINVRAM	2.1
>!AEFIRuntime	2.1
>!ASMCRTC	1.0
|IOSMBus!F	1.1
|IOHID!F	2.0.0
$quarantine	4
$sandbox	300.0
@kext.!AMatch	1.0.0d1
>!AKeyStore	2
>!UTDM	489.120.1
|IOSCSIBlockCommandsDevice	422.120.3
>!ACredentialManager	1.0
>!AFDEKeyStore	28.30
>!AEffaceable!S	1.0
>!AMobileFileIntegrity	1.0.5
@kext.CoreTrust	1
|CoreAnalytics!F	1
|IOTimeSync!F	840.3
|IONetworking!F	3.4
>DiskImages	493.0.0
|IO!B!F	7.0.6f7
|IO!BPacketLogger	7.0.6f7
>!ASSE	1.0
>KernelRelayHost	1
>!ASEPManager	1.0.1
>IOSlaveProcessor	1
|IOUSBMass!SDriver	157.140.1
|IOSCSIArchitectureModel!F	422.120.3
|IO!S!F	2.1
|IOUSBHost!F	1.2
>usb.!UCommon	1.0
>!UHostMergeProperties	1.2
>!ABusPower!C	1.0
|IOReport!F	47
>!AACPIPlatform	6.1
>!ASMC	3.1.9
>watchdog	1
|IOPCI!F	2.9
|IOACPI!F	1.4
@kec.pthread	1
@kec.corecrypto	1.0
@kec.Libm	1
```

**Comment by zzebrum** [comment]
@SHuang-Broad report all crashes using the form, we will fix them soon.
