### ISSUE TITLE
[UI] Menu Bar Icon & AdGuard Menu mismatch (Nightly 2.0.0.493)

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#392]
Something has gone wrong when I used the built in updater and relaunched, the position of the app is not in the right spot anymore.

<img width="426" alt="screen shot 2018-12-15 at 6 35 18 pm" src="https://user-images.githubusercontent.com/42660125/50040494-84874f80-0098-11e9-8235-5cd3f78cf6c8.png">

**Comment by planet0** [comment]
It has done it again, this time on a fresh install.

<img width="408" alt="screen shot 2019-01-05 at 10 17 07 am" src="https://user-images.githubusercontent.com/46271764/50715878-2e279280-10d3-11e9-969c-f16453801dc3.png">

**Comment by planet0** [comment]
Hi @zzebrum, was this issue resolved?
