### ISSUE TITLE
Open Wi-Fi Captive Network Pop-Up window "The Page Cannot Be Loaded"

### ISSUE THREAD

**Issue by seanob86** [AdguardTeam/AdguardForMac#394]
### Steps to reproduce

1. Connect to Public Open Wi-Fi that launches pop-up window to accept T&C's to obtain an active Internet Connection. For my example I am connecting to Starbucks Open Wi-Fi that launches a Captive Network Window and is supposed to load the Starbucks T&C's page.

2. The Captive Network Pop-Up Window launches with a blank white page with an error dialog "A Problem Occurred. The page cannot be loaded.

3. To overcome the issue I have found that either of the following will allow loading the content within the pop up captive network window.

a) Disable AdGuard completely in the menu bar
b) Disable "Automatically filter application"
c) In the list of Applications under the option above b) deselect "Safari"

I am currently using Firefox as my default browser so deselecting Safari (option c) is the workaround I am currently using.

Alternatively, if I do not utilize the workaround above, I can load safari or any other browser for that matter, and browse to captive.apple.com and that will load the web content normally for the open wi-fi network to accept T&C's - even if filtering is enabled for Safari under "Automatically filter application" option.

<img width="612" alt="screen shot 2018-12-19 at 14 44 21" src="https://user-images.githubusercontent.com/45988261/50202273-68640680-0355-11e9-8f0e-295b047f1626.png">

Other Troubleshooting steps I have tried with no success
1. Re-Install AdGuard
2. Disable all Filters
3. Disable each of the options individually (Ad Blocker, Privacy Protection, Browsing Security)
4. Enable debug filtering logging and clear the log - reproduce the issue. Filtering log does not populate any events whilst the issue is observed.

I have also found another user on Reddit who has also reported this:
https://www.reddit.com/r/Adguard/comments/9t3r09/hello_darlings_internet_connection_issues/

### Expected behavior
The Captive Network Window appears and loads web content for the user to accept T&C's to obtain an active Internet connection.

### Actual behavior
Captive Network Window appears. A URL is briefly observed at the bottom for captive.apple.com (but then disappears). Then the error (mentioned above) is displayed on top of a white blank screen.

<img width="1012" alt="screen shot 2018-12-19 at 11 23 43" src="https://user-images.githubusercontent.com/45988261/50201943-18d10b00-0354-11e9-9d80-92c76eb68d3d.png">

### Customer ID 
543636

### Your environment
* Environment name and version: macOS 10.14.2 / Safari 12.0.2 / AdGuard 1.5.14
* Any specific potentially conflicting software installed: Little Snitch - Although have allowed all outgoing connections for AdGuard. Was able to overcome the issue by either disabling Adguard in the menu bar or by unchecking "Automatically filter application" or unchecking Safari in the list of Applications under "Automatically filter application".

**Comment by sfionov** [comment]
Hello! Thank you for reporting.
We already have an issue about this in CoreLibs: https://github.com/AdguardTeam/CoreLibs/issues/612

Can you please see what domain appears at the bottom of Wi-Fi login window when AG is disabled?
Especially interesting, is it IP or domain.

More helpful would be debug logs if you used the latest AG v2.0 nightly, as mentioned in this comment: https://github.com/AdguardTeam/CoreLibs/issues/612#issuecomment-445750228

**Comment by seanob86** [comment]
> Hello! Thank you for reporting.
> We already have an issue about this in CoreLibs: [AdguardTeam/CoreLibs#612](https://github.com/AdguardTeam/CoreLibs/issues/612)
> 
> Can you please see what domain appears at the bottom of Wi-Fi login window when AG is disabled?
> Especially interesting, is it IP or domain.
> 
> More helpful would be debug logs if you used the latest AG v2.0 nightly, as mentioned in this comment: [AdguardTeam/CoreLibs#612 (comment)](https://github.com/AdguardTeam/CoreLibs/issues/612#issuecomment-445750228)

It's definitely domain not IP that appears at the bottom of the window.
There are two URL's that appear at the bottom.
The first is captive.apple.com. This is where the process breaks and can't load the Wi-Fi login page. As you can see in the screenshot in my first report the bottom of the window does not show the URL but definitely shows captive.apple.com briefly before presenting the error.

Utilizing the workaround the second URL is loaded which is for the Open WiFi login page. I'll screenshot below

I'll give the Nightly a go and report back. But give me a bit of time to get back onto an open Wi-Fi. 

<img width="1012" alt="screen shot 2018-12-19 at 15 48 28" src="https://user-images.githubusercontent.com/45988261/50203888-dced7400-035a-11e9-8cd7-81fd1ba84def.png">

**Comment by seanob86** [comment]
Hi,

I have tested with the Nightly version 2.0.0.493 (CL-1.2.150) and can confirm the login page still fails to load. Same behavior is observed when compared from stable to nightly versions.

Unfortunately I can not send any logs because no logs were created. Here is what I did:
- Enable debug logs within AG app settings.
- Reproduced the issue. Confirmed the captive login page still fails to load (nightly)
- launched console app.
- in the side menu within console app I'm assuming logs are found under ~/Library/Logs/Adguard. 
- Found no logs that were created whilst I reproduced the issue.
- However I did have logs in there from previous days. Cleared these logs and re-produced the issue. No logs created.

<img width="173" alt="screen shot 2018-12-20 at 12 58 22" src="https://user-images.githubusercontent.com/45988261/50262976-85f3a780-040b-11e9-8229-8142e048d7dd.png">

<img width="499" alt="screen shot 2018-12-20 at 12 57 16" src="https://user-images.githubusercontent.com/45988261/50262930-62306180-040b-11e9-8b99-db278485c012.png">

Are the logs in another location?

**Comment by ameshkov** [comment]
@seanob86 in the nightly build the logs are in ~/Library/Logs/com.adguard.Adguard

**Comment by seanob86** [comment]
Unfortunately, nothing is logged! I have attempted 3-4 times and no logs are created during re-producing the issue whilst debug logging is enabled. 
    	
    	

    	Thanks,Sean
Sent from my iPhone
    
  




On Thu, Dec 20, 2018 at 5:01 PM +0900, "Andrey Meshkov" <notifications@github.com> wrote:












@seanob86 in the nightly build the logs are in ~/Library/Logs/com.adguard.Adguard

**Comment by ameshkov** [comment]
@sfionov @Stillness-2 guys, I guess we should provide a debug build with kernel extension logging enabled.

**Comment by Stillness-2** [comment]
@seanob86 try this debug build
https://uploads.adguard.com/up10_1porb_AdGuard.app4701.zip

**Comment by seanob86** [comment]
I installed the build you provided earlier - version 2.0.0.493.DEBUG (CL-1.2.150).
Noticed that some extensions had to be allowed under system preferences > Security & Privacy > General. Allowed all extensions and rebooted.

Unfortunately, under DEBUG logging I still can't get any logs produced whilst re-producing the issue.

I screen captured (video) the process just in-case I am doing something wrong. I will email to devteam@adguard.com - hopefully you receive it (12MB in size). "Captive Network Login Error.mov"

**Comment by ameshkov** [comment]
@seanob86 we haven't received it:( Could you please upload it somewhere?

@Stillness-2 let's add the "Export logs" option, it'd make things easier for everyone:  https://github.com/AdguardTeam/AdguardForMac/issues/395

**Comment by seanob86** [comment]
try this. hope it works! 
https://share.icloud.com/photos/0bDqXdRGBIWn_4YPvKvn4oepw

**Comment by seanob86** [comment]
Thanks for that 👍 
I have emailed  devteam@adguard.com with the logs as requested. Issue encountered a couple of times at 09:39AM 25th of December.

**Comment by ameshkov** [comment]
Merged to https://github.com/AdguardTeam/CoreLibs/issues/612
