### ISSUE TITLE
Adguard for Mac

### ISSUE THREAD

**Issue by asianid** [AdguardTeam/AdguardForMac#396]
### Steps to reproduce

1.Turning MacBook into sleep mode
2.Reopening the MacBook
3.Pop-up stating AdGuard wants to make some changes

### Expected behavior

There shouldn't be a pop-up, or at least it should not happen every time these steps are repeated.
### Actual behavior

Pop-up (AdGuard wants to make some changes) 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/46177041/50484628-59cabe80-09e9-11e9-82d4-74a65a99f762.png)

</details>

### Customer ID 
2074698
### Your environment

* Safari
* Both the AdGuard Beta and AdGuard versions are installed and running.

**Comment by zzebrum** [comment]
@asianid did you allow those changes at the first time?

**Comment by asianid** [comment]
@zzebrum You're right, thanks. I allowed for the changes but then locked it again. However doesn't this leave the laptop exposed to changes made by other apps if left unlocked?

> @asianid did you allow those changes at the first time?

**Comment by asianid** [comment]
@zzebrum I guess I don't need both of them running.

**Comment by zzebrum** [comment]
@asianid I guess the fact that you locked it should not affect AG work. Did this happen with release AG version?

**Comment by zzebrum** [comment]
@asianid any update on this issue? Did you try AG v2.0 beta?

**Comment by zzebrum** [comment]
reopen if needed.
