### ISSUE TITLE
Tracking parameters are not removed sometimes

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#397]
### Steps to reproduce

1. Add `__tn__` to stripped parameters
2. Visit facebook.com
3. Click on a name in the News Feed that contains `__tn__` in the URL

### Expected behaviour
The `__tn__` parameter is removed from the URL

### Actual behaviour
It remains in the URL unless you manually refresh afterwards

### Your environment

* AdGuard for Mac 2.0.0.493 Nightly (CL-1.2.150)
* Chrome Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by ameshkov** [comment]
Do you actually leave Facebook when clicking on a name? The tracking parameters will only be removed when you're leaving the website (otherwise it does not make much sense).

**Comment by planet0** [comment]
I don't leave Facebook, but all of these extra parameters are uncomfortable enough for Facebook to track every click on the website. Surely there is some benefit of removing them so it's a raw link?

They do get removed if I refresh, so I think Facebook uses the same behaviour as YouTube and uses AJAX loading to prevent the browser from loading as a page. 

So I guess the broader question is: Is AdGuard able to use stealth mode features with AJAX loading present?
