### ISSUE TITLE
Please update translations of the Adguard for Mac and Installer.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#399]
@ameshkov
@aalpatkina

I anew translated and just finished all Traditional Chinese translations in the projects of Adguard for Mac and Installer.

May you update their translations in the next version?
Please correctly use Traditional Chinese (**zh-TW**) for the app, Installer and **extensions (AdGuard Assistant, Popup Blocker & Web of Trust)**.

Remember **NOT** to use Simplified Chinese (zh or zh-CN) in Traditional Chinese interface.
I'm afraid that your engineers often forget about this.
Check for not only the app but also its installer and extensions (AdGuard Assistant, Popup Blocker & Web of Trust).
Ex:
https://github.com/AdguardTeam/AdguardAssistant/issues/264
https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1218#issuecomment-450478312

You should **ONLY** use Traditional Chinese (zh-TW) or English (if having no translation) in Traditional Chinese interface.
Taiwanese people dislike to see Simplified Chinese characters because they're not our words and culture.

Thanks.

**Comment by Stillness-2** [comment]
#502, #503
