### ISSUE TITLE
Add description page to kb.adguard.com

### ISSUE THREAD

**Issue by Stillness-2** [AdguardTeam/AdguardForMac#402]
It is necessary to make an analogue of that page in our KB : https://www.obdev.at/products/littlesnitch/high-sierra-notes.html
for `macOS High Sierra or above`

**Comment by ameshkov** [comment]
@aalpatkina plz assist

**Comment by vbagirov** [comment]
https://github.com/AdguardTeam/AdguardKnowledgeBase/pull/295

**Comment by vbagirov** [comment]
https://kb.adguard.com/macos/solving-problems/high-sierra-compatibility
