### ISSUE TITLE
"Report the website" doesn't work in Assistant

### ISSUE THREAD

**Issue by aspasskaya** [AdguardTeam/AdguardForMac#408]
### Steps to reproduce
1. Go to Assistant
2. Tap on "Report the website" 

### Expected behavior
https://reports.adguard.com/ru/new_issue.html?product_type=Mac ...

### Actual behavior
Nothing happens

---
* AdGuard nightly 2.0.0.500
* Chrome 71.0.3578.80
* Mac Mojave

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #680](https://github.com/AdguardTeam/CoreLibs/issues/680) via [**ZenHub**](https://www.zenhub.com/)

**Comment by sfionov** [comment]
Duplicate of #361
