### ISSUE TITLE
Huge CPU usage

### ISSUE THREAD

**Issue by choco** [AdguardTeam/AdguardForMac#416]
Adguard seems to use a lot of CPU for its filtering. When opening a website it jumps to 75% to 100% CPU usage like nothing.
Take a look at the CPU usage time
<img width="593" alt="screen shot 2019-02-09 at 16 11 19" src="https://user-images.githubusercontent.com/85527/52522437-b4f8fd80-2c85-11e9-91b9-a3d4dcf5f82f.png">
Is this normal?

Environment
--- 
macOS 10.14.3
Adguard Nightly 2.0.0.504 (CL-1.3.113)

**Comment by ameshkov** [comment]
Well, filtering takes some CPU time, especially when you open a website for the first time (additional CPU time is required when the HTTPS filtering kicks in). The following web pages of that website will take considerably less CPU.

Also, if you have the filtering log open, the usage would be noticeably higher as every modified/removed HTML element is reported to the filtering log with its full content.

Anyways, we haven't yet conducted the proper performance testing of v2.0 so I can't say if the current values are optimal. This is on our TODO list for the v2.0 release.
