### ISSUE TITLE
AdGuard ignoring the Priority Tasks app

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#425]
### Steps to reproduce
1. Install the following app: https://itunes.apple.com/ua/app//id1119079160?l=ru&mt=12&ls=1>
2. Ads will not be blocked by AdGuard, even if the app is already in filtered apps list

### Expected behavior
Ads should be blocked

### Actual behavior
Ads aren't blocked

### Screenshots & Logs
Available under customer id 2090812

**Comment by Stillness-2** [comment]
@Alex-302 technically AdGuard intercepts connections of this application (the last beta at least). It may be possible to create a set of rules for filtering this app.

**Comment by Stillness-2** [comment]
May be like this:

```
||trenshot.com
||stat.analytiall.com
||itunes.apple.com$app=Priority Tasks
```

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/AdguardFilters #44420](https://github.com/AdguardTeam/AdguardFilters/issues/44420) via [**ZenHub**](https://www.zenhub.com/)
