### ISSUE TITLE
Running Adguard in proxy mode does not update statistics in UI

### ISSUE THREAD

**Issue by TheWojtek** [AdguardTeam/AdguardForMac#43]
If Adguard is set to proxy mode and does the filtering, the statistics in main UI are not updated. Count of blocked ads and trackers does not change.

**Comment by TheWojtek** [comment]
Update: actually, it does update, but with a significant delay (more than 5 minutes).

**Comment by Stillness-2** [comment]
I can't reproduce these issues

**Comment by Stillness-2** [comment]
@TheWojtek Can you please make screencast with this issue?

**Comment by vozersky** [comment]
can't reproduce, outdated issue
