### ISSUE TITLE
Filtering log issues

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#430]
1. [X] No cookie rules info: #386 
2. [X] Connections from non-filtered applications are still in the log: https://uploads.adguard.com/up04_du5ud_Monosnap.png
3. [X] `null` in the log details: https://uploads.adguard.com/up04_3p76s_Monosnap.png
4. [ ] Strange errors in the log:
    ```
    2019/03/01 10:24:38:299  Can't find log object in the pool of an active log objects: [(0x0x600000c7b580) ID=1000043, reqID=200118, info="", rule="" appName="Google Chrome"]
    2019/03/01 10:24:38:300  Can't find log object in the pool of an active log objects:[(0x0x600000db8600) ID=1000043, reqID=200119, info="", rule="" appName="Google Chrome"]
    2019/03/01 10:24:39:199  Can't find log object in the pool of an active log objects:[(0x0x600000d80900) ID=1000020, reqID=200038, info="", rule="" appName="Google Chrome"]
    ```
5. [X] No hostname in the https tunnel requests: https://uploads.adguard.com/up04_tt30z_Monosnap.png

**Comment by ameshkov** [comment]
See the issues here and do the same:
https://github.com/AdguardTeam/AdguardForWindows/issues/2427

**Comment by Stillness-2** [comment]
from 
https://github.com/AdguardTeam/AdguardForWindows/issues/2427

1. [ ] It reports that HTML elements are removed from jpg, CSS, JS files, that cannot be so: https://uploads.adguard.com/up04_1qrhx_Windows_7_Enterprise_1.png

-----

1. [ ] We should use the same statuses we get from CoreLibs:
2. [ ] Color indication
    * Blocked - red
    * Modified - yellow
    * Whitelisted - green
    * Bypassed - no color
3. [ ] Show the full list of rules applied to the request in the log item details (including whitelist, cookie, csp, whatever).
4. [ ] Additionally, show the stealth mode actions applied (if any)
5. [ ] Exceptions: removed cookies and removed HTML elements should be separate items in the filtering log (just like we do now).
6. [ ] "Size" value should be replaced with `↑3.0 KB ↓15.0 KB`. That's important to understand what's the size of uploaded data.
7. [ ] Rule column value:
    * Do not print `$$`, `$cookie`, and `$stealth` rules there;
    * In the case of a single rule, just print it there;
    * In the case of multiple rules applied, print "5 rules";
    * If no rules were applied, but status is modified:
        * If there are any stealth mode actions applied, print "Stealth mode"
        * If this is a "Document", print "Cosmetic rules"
        * In any other case this might be a bug of CoreLibs:)
8. [ ] Print `Connection ID` for processed requests as well

**Comment by Stillness-2** [comment]
https://github.com/AdguardTeam/AdguardForWindows/issues/2427 -> #386

**Comment by Stillness-2** [comment]
`Strange errors in the log` I can't reproduce on last CL
