### ISSUE TITLE
Advanced tracking features logs out of Twitch.tv

### ISSUE THREAD

**Issue by choco** [AdguardTeam/AdguardForMac#431]
### Steps to reproduce
Have the following settings enabled:
<img width="710" alt="screen shot 2019-03-01 at 16 14 33" src="https://user-images.githubusercontent.com/85527/53647331-97dc9c80-3c3d-11e9-9c8e-f60bdab0f7d0.png">
<img width="714" alt="screen shot 2019-03-01 at 16 14 38" src="https://user-images.githubusercontent.com/85527/53647338-9a3ef680-3c3d-11e9-94fd-71c4c1625a5b.png">
Log on twitch.tv
After the third party time is elapsed I'm logged out.
Can reproduce it more easily by setting the third party cookie setting to 0
It doesn't seem to that it's a third party cookie but maybe I'm wrong. In that case a way to configure a whitelist would be highly appreciated

### Expected behavior

Does not get logged out of Twitch

### Actual behavior

Get logged out of Twitch

### Your environment

* Safari 12
* macOS 10.14.3
* Adguard 2.0.0.516 CL-1.3.179

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #803](https://github.com/AdguardTeam/CoreLibs/issues/803) via [**ZenHub**](https://www.zenhub.com/)
