### ISSUE TITLE
AdGaurd 2.0.0.516 is incompatible with the Windscribe extensions for Chrome

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#433]
### Steps to reproduce

1. Install the extension: https://chrome.google.com/webstore/detail/windscribe-free-vpn-and-a/hnmpcagpplmpfojmgmnngilcnanddlhb 
2. Register and log in
3. Turn it on 
4. Try visiting any website
5. Disable the AdGuard protection or the extension 
6.  Try visiting any website

### Expected behavior

Websites are accessible on steps 4 and 6

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/53692249-15ff8700-3d95-11e9-86ad-092876fe705c.png)

</details>

### Actual behavior

Unable to access any website on step 4, works on step 6

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/53692236-ff593000-3d94-11e9-899f-ff85e6598a15.png)

</details>

### Customer ID 

[Forum thread](https://forum.adguard.com/index.php?threads/%D0%9D%D0%B5-%D0%BE%D1%82%D0%BA%D1%80%D1%8B%D0%B2%D0%B0%D1%8E%D1%82%D1%81%D1%8F-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%B5%D1%81%D0%BB%D0%B8-%D0%B2%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD-adguard-%D0%B8-windscribe.31015/)

### Your environment

* AdGaurd 2.0.0.516 (CL 1.3.79)
* Windscribe 2.4.1
* Chrome 72.0.3626.119

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #785](https://github.com/AdguardTeam/CoreLibs/issues/785) via [**ZenHub**](https://www.zenhub.com/)
