### ISSUE TITLE
Use localized date format

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#439]
Suggest to use Chinese date format for date in the main screen and filters' update time in Chinese interface.
Use 24-hour clock.
Don't need AM or PM.
ex: March 08, 2019 19:23:56
Chinese date format: 2019年3月8日 19:23:56

This is for your reference.
https://github.com/AdguardTeam/AdguardForWindows/issues/2400#issuecomment-470779013

Because I don't have Mac, I can't check its Chinese date format.
Please note it.
If you already did it, please ignore this request.
Thanks.

**Comment by ameshkov** [comment]
We use the same format as configured in MacOS settings.
