### ISSUE TITLE
Message box is unresponsive in "Support.." dialog

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#44]
**Source complaint:**
http://forums.macrumors.com/threads/the-el-capitan-safari-9-content-blocker-thread.1924936/page-7#post-22431199

**Video:**
https://www.youtube.com/watch?v=x2b0hi5vZK8

**Comment by Stillness-2** [comment]
It happens because this field must be filled correct email address. We lost placeholder in this field. :)

**Comment by ameshkov** [comment]
@TheWojtek seems that this is intended.

**Comment by ameshkov** [comment]
@Stillness-2 let's fix the missing placeholder then, I'll leave this issue open then.

**Comment by Stillness-2** [comment]
commit 23427
