### ISSUE TITLE
Ads not filtered in Kiwi for Gmail / G Suite

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#443]
https://www.kiwiforgmail.com/

### Steps to reproduce
1. Install the app, make sure it's included in AdGuard's filtering list
2. Launch the app
3. Enjoy the ads!

### Expected behavior
AdGuard should be able to filter out ads in this application

### Actual behavior
You get ads

<details><summary>Screenshot:</summary>

![img](https://uploads.adguard.com/TheHasagi7nep7.png)

</details>

### Customer ID 
399703

### Your environment
Application ver 1.5.14 (464) on macOS 10.14

**Comment by jbryant705** [comment]
This seems like a bug related to Chromium, not specifically Kiwi. Kiwi is based on Chromium and I'm seeing ads on gmail.com in Chrome 73.0.3683.75 beta as well.

**Comment by ameshkov** [comment]
Most likely it was not added to the filtered apps in AdGuard network settings
