### ISSUE TITLE
Redirect has been blocked by CORS policy issue 

### ISSUE THREAD

**Issue by TheHasagi** [AdguardTeam/AdguardForMac#454]
Customer facing an issue "redirect has been blocked by CORS policy issue" in dev-tools - console.

<details><summary>Short clip:</summary>

[link](https://cl.ly/669db8)

</details>

### Customer ID 1817719

Logs will be provided upon request.

**Comment by ameshkov** [comment]
When AG blocks a request, it responds with a fake error response (status=500) that does not have an `Access-Control-Allow-Origin` header (which seems to be required by the CORS policy of the website).

To solve this, we'll need to add `Access-Control-Allow-Origin` header with smth like `https://origin-domain` to these "blocked" responses.

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #851](https://github.com/AdguardTeam/CoreLibs/issues/851) via [**ZenHub**](https://www.zenhub.com/)
