### ISSUE TITLE
Beta 2 not filtering properly on Chromium based browsers (Chrome, vivaldi)

### ISSUE THREAD

**Issue by PTR-inc** [AdguardTeam/AdguardForMac#458]
### Steps to reproduce

1. Open 'telegraaf.nl'

### Expected behavior
No ads

### Actual behavior
Most ads are still there

In Safari it all works properly

### Customer ID 
2159042

### Your environment
Macos Mojave 10.14.4, Vivaldi 2.4 stable, vivaldi 2.5 beta, chrome v73
Avast for mac, webshield disabled, tried with avast off

Adgaurd for mac beta 2.0.522 & also tried nightly 2.0.1.531

**Comment by ameshkov** [comment]
@PTR-inc is it specific to this website only?

**Comment by PTR-inc** [comment]
No, on all sites. A few things are filtered, but most not. Also the integration with the adguard extension is spotty, sometimes it's blue, most of the times not. And tried it with and without the extension.

**Comment by ameshkov** [comment]
@sfionov could you please take a look?

I moved the logs to our private nextcloud.

**Comment by ameshkov** [comment]
@PTR-inc you should try the new nightly (in a day or two). The issue that I see in your logs should be resolved there.

**Comment by PTR-inc** [comment]
Allright, will try and keep you posted. Thanks for the quick reply!

**Comment by PTR-inc** [comment]
nightly 2.0.1.535 seems to have solved the issue, thanks!

**Comment by ameshkov** [comment]
Awesome, thank you for checking it!
