### ISSUE TITLE
Switch to the new Developer ID

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#460]
It is time to switch to `Adguard Software Ltd`.

Here is what needs to be done:

1. [x] Start using the new Developer ID for the app and kext
2. [x] Start using the new Developer ID for the installer app
3. [x] Handle the app update (it might be complicated if bundle ID change is necessary)
4. [x] Notarize new kext
5. [x] Notarize the app
6. [x] Notarize the installer app
7. [x] Change the "security preferences" warning screen

**Comment by ameshkov** [comment]
Here are some issues with the current version:

![image](https://user-images.githubusercontent.com/5947035/56813752-48ce7480-6846-11e9-9e97-84d0194eca16.png)

![image](https://user-images.githubusercontent.com/5947035/56813760-4e2bbf00-6846-11e9-80f4-a8a6d42a2648.png)

**Comment by planet0** [comment]
Any way to notify users who are updating to have a short explanation, such as:

> From version 2.0, AdGuard has now retitled its developer name from "Performiks OOO" to "AdGuard Software Ltd". You need to open System Preferences and re-allow AdGuard for application loading in order for AdGuard to function properly.

**Comment by ameshkov** [comment]
@planet0 it will be written in **HUGE BOLD** in the release notes of the final version.
