### ISSUE TITLE
[Nightly] ERR_SPDY_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by BlazDT** [AdguardTeam/AdguardForMac#465]
https://github.com/AdguardTeam/AdguardFilters/issues/32620

Web pages in www.persol.com (and related subpages) refuse to load or refuse to load completely with AdGuard on.
Browser Chrome

Screenshot: https://camo.githubusercontent.com/4e291fe6da247cb5eaf5429e5ff4812a6fc771b9/68747470733a2f2f7265706f7274732d696d672e616467756172642e636f6d2f3675764d4444722e706e67

Looks like some error with SSL/TLS on 2.0.1.535 nightly. Please check.

**Comment by ameshkov** [comment]
Hm I, I cannot reproduce this

**Comment by BlazDT** [comment]
@giodeluigi
Is your Chrome up2date and did you try to clean browser cache?

**Comment by zzebrum** [comment]
reproducible on my side, but @sfionov suggests to check with the next nightly - the problem maybe fixed there.

**Comment by zzebrum** [comment]
It's not reproducible on my side anymore with the latest nightly. @BlazDT can you confirm?

**Comment by BlazDT** [comment]
As I never experienced it, only @giodeluigi reported it. But when it is working for you and before not with latest nightly, let's close it.
