### ISSUE TITLE
Slightly incorrect translation in menu bar widget

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#467]
As reported by user 461686.

Both current and correct translations are on the screenshot:
<img width="428" alt="Ekran Resmi 2019-04-17 12 26 37" src="https://user-images.githubusercontent.com/33634917/56380818-d6450f80-621b-11e9-9f1b-227f1d5f6922.png">

**Comment by zzebrum** [comment]
@aalpatkina please, take a look.

**Comment by aalpatkina** [comment]
corrected on OneSky
