### ISSUE TITLE
Minor typo in UI (2.0.0.522 beta)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#470]
Under Stealth Mode > Miscellaneous:
"Hide **Referer** from third-parties" should be "Hide **Referrer** from third-parties"

<img width="442" alt="Screen Shot 2019-04-26 at 8 09 14 am" src="https://user-images.githubusercontent.com/46271764/56771661-a046f300-67fa-11e9-93a7-285aa3a1e1ca.png">

**Comment by aalpatkina** [comment]
corrected on OneSky
