### ISSUE TITLE
Automatically filter application

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForMac#473]
I recently updated Adguard beta from 2.0.0 to 2.0.1.

In ideal scenario, the settings within "automatically filter application” should be retained on update. However, they reverted back to default state after update.

**Comment by zzebrum** [comment]
@specter78 please, give more details. the problem is only in `Automatically filter applications` option? 
What exact changes have you made with the list of filtered apps before the update?

**Comment by specter78** [comment]
> the problem is only in Automatically filter applications option?

I haven’t noticed such issue elsewhere.

> What exact changes have you made with the list of filtered apps before the update?

I removed all the applications and kept only Chrome, Safari and Opera. On update, all the default applications re-appeared.

**Comment by specter78** [comment]
I updated Adguard from 2.0.1 to 2.0.2 and the filtered apps again reset. This shouldn’t have happened since the issue is supposed to be fixed in 2.0.2.
