### ISSUE TITLE
Not working in Opera

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForMac#474]
Adguard beta 2.0.1 is not working with Opera (v60.0.3255.70).

PS: It was not working in 2.0.0 either.

**Comment by zzebrum** [comment]
@specter78 Is VPN enabled?

**Comment by specter78** [comment]
> Is VPN in Opera enabled?

Yes.

When you mention it, on disabling VPN, Adguard works perfectly.

**Comment by zzebrum** [comment]
yeap, that is the trick - Opera does not let AdGuard the access to traffic if VPN is enabled. Unfortunately,  nothing to be done here.
