### ISSUE TITLE
Vivaldi not being filtered

### ISSUE THREAD

**Issue by PTR-inc** [AdguardTeam/AdguardForMac#475]
Only vivaldi is not being filtered, as if not recognised. Chrome, safari & firefox do get filtered.
When I load the adguard extension in vivaldi, it is green, not blue. Also no adguard assistent in vivaldi.

Mojave 10.14.4
Adguard 2.0.1.539 (CL-1.3.304)
Chrome 74.0.3729.108 (Official Build) (64-bit)
Vivaldi 2.5.1525.4 (Official Build) (64-bit)
Firefox 66.0.3 (64-bit)

**Comment by zzebrum** [comment]
@PTR-inc the problem came out after the update to AdGuard v2.0.1beta?

**Comment by PTR-inc** [comment]
Looks like it. The last update made me notice it.

**Comment by ameshkov** [comment]
@Stillness-2 plz take a look
