### ISSUE TITLE
#%#AG_setConstant('navigator.javaEnabled', 'false'); fails to block Java on some websites when using Safari

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#477]
### Steps to reproduce
1. Add the following filter rule:
```
#%#AG_setConstant('navigator.javaEnabled',
'false');
```
2. Try to open some websites containing Java elements (not JS)
3. In some instances, Java won't be blocked

### Expected behavior
Rule should block Java content on Safari 

### Actual behavior
Cannot block Java in some instances

<details><summary>Screenshot:</summary>

Available in ticket
</details>

### Customer ID 
1402125

### Your environment
Not applicable

**Comment by ameshkov** [comment]
It should be this:
`#%#AG_setConstant('navigator.javaEnabled', 'falseFunc');`

**Comment by akmLaVx** [comment]
`#%#AG_setConstant('navigator.javaEnabled', 'falseFunc');` isn't working as well.
<img width="1534" alt="adguard_setConstant" src="https://user-images.githubusercontent.com/33634917/57319764-050d2200-7106-11e9-87e8-ac3ccf95f9f4.png">

**Comment by ameshkov** [comment]
The problem is that on [that page](https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_javaenabled) the iframe is created dynamically, and JS rules can't simply be injected there.
