### ISSUE TITLE
Adguard disappearing from "Login Items"

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForMac#480]
I am using Adguard beta 2.0.1.

For some unknown reason, whenever I restart or shutdown Mac, Adguard disappears from `Users & Groups > Login Items`.

I do not know whether this is related to Adguard or macOS, but I haven’t had this issue with any other app.

Mojave 10.14.4

**Comment by planet0** [comment]
Also experienced this, AdGuard suddenly stopped launching on startup.

After the 2.0.1 beta update, I noticed the 'Launch AdGuard on Login' option was unchecked in the AdGuard app, and now that I ticked it again, it is launching on start-up.

Now, there is no login item in System Preferences, and 'AdGuardLoginHelper' is set to launch on start up.

<img width="1095" alt="Screen Shot 2019-05-03 at 6 18 36 pm" src="https://user-images.githubusercontent.com/46271764/57126310-e9d1a800-6dcf-11e9-9d7e-88080e6f28a3.png">


Seems to be a new mechanic for start up, but upgrading/updating to 2.0.1 beta from a previous version isn't migrating the startup option over to the new method.

Could this be fixed?

**Comment by planet0** [comment]
Oops, seems to have already been noticed. #417

**Comment by ameshkov** [comment]
The update issue seems to be a bug

I am not so sure about login items, though. @Stillness-2  plz remind me is it a bug or is it intended?

**Comment by Stillness-2** [comment]
@ameshkov  "Adguard disappears from Users & Groups > Login Items" - it was planned :)
