### ISSUE TITLE
[Question] Malware Protection

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForMac#481]
Adguard provides `Phishing and Malware Protection` within preferences.

So will enabling `Malware Domains`, `Spam404` and `NoCoin`  filters make any difference?

Also, I’ve noted that the performance of Adguard has slightly worsen after enabling `Malware Domains` filter. This is especially notable when updating filters manually. (Maybe because of the sheer size of the list)

Adguard beta 2.0.1
macOS 10.14.4

**Comment by zzebrum** [comment]
AdGuard has [its own filters](https://kb.adguard.com/en/general/how-malware-protection-works#adguard-filters) for phishing and malware protection. So it's up to you which one do you prefer.

Performance issue needs to be checked.
