### ISSUE TITLE
Stealth Mode & GitHub Logged In

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#485]
I've noticed with AdGuard 2.0.1.539 beta that if I stay logged into GitHub on Google Chrome, my Stealth Mode settings seem to be removing my session for GitHub daily, so I need to login again and also complete two-factor authentication.

I use the same settings as the Windows version and don't experience this issue, so I'm trying to figure out which particular stealth setting is doing this.

My best guess is the "Self-destruction of third-party cookies", but I'm not sure why or how to allow GitHub to have an exception.

See below, same device, new session daily.

<img width="765" alt="sessions" src="https://user-images.githubusercontent.com/46271764/57189436-1dd4d680-6f52-11e9-861d-a511c7667a2a.png">

**Comment by ameshkov** [comment]
> My best guess is the "Self-destruction of third-party cookies", but I'm not sure why or how to allow GitHub to have an exception.

Add `@@||github.com^$stealth` to the user filter

**Comment by planet0** [comment]
Is there any reason why this is only happening on the macOS version and not the Windows version of AdGuard? Wouldn't the Stealth features behave similarly?

**Comment by ameshkov** [comment]
> Wouldn't the Stealth features behave similarly?

The same version of CoreLibs is under the hood so yeah, they must behave similarly.
