### ISSUE TITLE
AdGuard appears twice in Notification Centre settings

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#486]
I've noticed that AdGuard has two entries in System Preferences > Notifications as of 2.0.1.529 beta. Before, there was just one entry.

I like to use custom settings for Notifications (such as unchecking 'Show in Notification Centre'), so if there is a way to get it back to one entry, or have a way to identify which is the 'correct' one to change settings for, that would help the user.

Otherwise I'll just apply the same settings to both. Still worth mentioning this issue though.

<img width="780" alt="Screen Shot 2019-05-09 at 6 42 35 am" src="https://user-images.githubusercontent.com/46271764/57407263-1c433100-7226-11e9-8cc9-f1d0f7cdc0d2.png">

**Comment by iDjay** [comment]
It‘s a MacOS issue and not AdGuard. Just hit backspace on one of them 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by planet0** [comment]
> Just hit backspace on one of them

Thanks @iDjay, I had no idea that was possible. I restarted after removing both and only one has come back.
