### ISSUE TITLE
Start supporting the Microsoft Edge browser

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#487]
Version 76.0.151.0 (Official build) Canary (64-bit). It currently cannot be filtered even though it's added to the list in AdGuard > ... > Network > Applications.

<details> <summary > Screenshots </summary>

![image](https://user-images.githubusercontent.com/15856304/57442796-65f74000-7255-11e9-9ba8-868ede7dde33.png)

![image](https://user-images.githubusercontent.com/15856304/57442865-8921ef80-7255-11e9-9ff3-706293ed73c2.png)

</details>

**Comment by smlombardi** [comment]
FWIW, I installed the Chrome extension into Edge, and it works perfectly.
