### ISSUE TITLE
Connections slip through AdGuard when resumed from Sleep

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#489]
I have AdGuard filtering Spotify. I know it isn't officially supported since Spotify has updated their ToS, however it is working perfectly and I haven't received any warning or anything from them.

Regardless, I notice when I put macOS to sleep and then resume it (open the lid), Spotify ads start to play and it is no longer being filtered through AdGuard. If I quit Spotify and relaunch it, everything is okay again.

This could be happening to other apps in general, which is why I'm raising this on GitHub.

### Steps to reproduce

1. Add Spotify to list of filtered apps
2. Open Spotify and play a few songs with a free account
3. Put macOS to sleep
4. Resume from sleep and keep playing music

### Expected behavior

Spotify continues to filter through AdGuard
### Actual behavior

Spotify starts playing ads between music, it has somehow connected through even though filters should continue blocking it.

### Your environment

* Environment name and version: macOS 10.14.4 (18E227), AdGuard 2.0.1.539 beta, Spotify 1.1.6.113.gb388fe17
* Any specific potentially conflicting software installed: LuLu, BlockBlock

**Comment by zzebrum** [comment]
hey @planet0! sorry for the late reply
can you reproduce the issue and collect logs?

**Comment by planet0** [comment]
Hi @zzebrum, sure, I recreated the issue and exported logs. Resumed from sleep 11:22am, ads starting leaking through around 11:22:50am. I sent it to apple@adguard.com, hope that's okay (re: @ameshkov?).

**Comment by ameshkov** [comment]
Thank you for the logs!

@Stillness-2 logs are in the private next cloud.

I've assigned this issue to v3.1.

**Comment by ameshkov** [comment]
@planet0 do you have this issue with Spotify only or other apps are also affected?

**Comment by planet0** [comment]
All apps/connections are affected it seems.

I was able to easily reproduce via this method:

1. Visit blockme.com in a browser, view the website.
2. Add `||blockme.com^` to the User filter, enable and turn on.
3. Visit blockme.com in a browser, connection blocked.
4. Put macOS to sleep.
5. Wait enough time for hardware to sleep too. I waited about 10 minutes.
6. Resume from sleep and immediately log back in.
7. Revisit blockme.com

Website goes through.

Actually, it seems like something isn't right the more I continue trying. Even though I see the 'Access denied' title for a short moment, Safari and Google Chrome keep loading the page and it's just a white screen. Restarting isn't fixing this.

Are you able to replicate blocking a domain in the User filter and seeing it not blocked correctly?

**Comment by ameshkov** [comment]
@planet0 you should add `||blockme.com^$empty` in order to force blocking a main frame request

**Comment by planet0** [comment]
Oops, my bad @ameshkov. That does work with Chrome and Safari. To answer your question then, it has only happened with the Spotify desktop app.

**Comment by planet0** [comment]
Seems like others are reporting this #540 #567
