### ISSUE TITLE
Add a background service/daemon for filtering traffic when the app is closed

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#490]
As reported by user 2187248,

> I have installed Adguard on my server (Mac Mini, MacOS Server X.12.6). I have configured Adguard to be used as a proxy (3128) by the clients. It works when the session is opened because the App is loaded. But if i close the session, it stops. There is no daemon working as an headless task. Should it be possible to add this function for future release ?

**Comment by ameshkov** [comment]
Well, this is too much for our type of software.

On the other hand, we are going to add MITM proxy functionality to [AdGuard Home](https://github.com/AdguardTeam/AdguardHome) eventually.
