### ISSUE TITLE
Beta to Nightly no auto launch after upgrade

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#493]
From latest beta to nightly, the installer closes AdGuard for the upgrade, but never opens it again. User remains unprotected, user must manually launch AdGuard with no instruction.

### Steps to reproduce

1. Get latest Nightly .dmg
2. Run installer
3. Allow installer to close running instances of AdGuard
4. Complete install

### Expected behavior

Since AdGuard was closed and it was an upgrade, AdGuard relaunches once install is complete

### Actual behavior

AdGuard remains closed and nothing happens after installer finishes

**Comment by ameshkov** [comment]
Well, this is not how it works when we do the normal auto-update.

In this particular case (running the nightly installer and overwriting another version) this is just a standard behavior of the installer package.

**Comment by planet0** [comment]
Oh I see, didn't realise it was expected. Just reported it as AdGuard macOS full installers are the only ones that don't auto-launch, the Windows full and web installers do and so does the macOS Web Installer from memory.
