### ISSUE TITLE
AG Missing Some Queries with AGSDNS

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForMac#495]
### Steps to reproduce

1. Install AdGuard Home
2. Install AdGuard for Mac
3. Apply AdGuard Simplified DNS to both products
4. Observe AdGuard Home query log watching for DNS blocking that should be caught on AdGuard for Mac.

### Expected behavior
Filter list should block everything it says it's going to block on AdGuard Home.

### Actual behavior
AdGuard for Mac is not filtering everything, with some data being caught by AdGuard Home.

<details><summary>Screenshot:</summary>

<img width="867" alt="Screen Shot 2019-05-18 at 13 14 26" src="https://user-images.githubusercontent.com/6005161/57963928-b9375580-791b-11e9-8fc9-6f11c7d8ed48.png">
<img width="899" alt="Screen Shot 2019-05-18 at 13 14 56" src="https://user-images.githubusercontent.com/6005161/57963929-ba688280-791b-11e9-90f7-4dd09df5ecbf.png">
</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Latest AdGuard Home/AdGuard for Mac/AdGuard SDNS
* Any specific potentially conflicting software installed: Little Snitch

**Comment by sfionov** [comment]
DNS filtering presents in Adguard Home and Adguard for Android only. But in AG for Android it is completely optional.

In general, AG apps doesn't need to do less accurate filtering before performing more accurate.

**Comment by jslawler** [comment]
Either I completely misunderstood what you're saying, or I'm stupid.

If DNS level blocking doesn't exist on AG Mac (keep in mind that my DNS is set to AG on the wifi on my Mac, then why would the SDNS be an option in the filter settings?

Keeping in mind that I have my DNS set to AGDNS I would have presumed I should not be seeing AG Home catching data that AGDNS should be catching before reaching the AG Home.

I may also be entirely wrong. By all means, correct me.

**Comment by sfionov** [comment]
AG Simplified domain names filter is simplified version of AG filter designed for DNS blocking. It has the same syntax as other filters but contains rules only for domain names.

However, it is just another AdGuard filter, thats why it is in the list of filters.

**Comment by jslawler** [comment]
So, this leads to my next question then.
If AdGuard DNS uses the SDNS filter, my MacBook is using AdGuard DNS and my AdGuard Home is catching data that should have been caught by AdGuard DNS - would this not indicate an issue?

**Comment by ameshkov** [comment]
@jslawler my bet is that these requests are made by apps which are not filtered by AdGuard for Mac. You can control what's filtered in AG for Mac settings: Network -> Filtered Applications
