### ISSUE TITLE
Update CoreLibs 1.3.344

### ISSUE THREAD

**Issue by sfionov** [AdguardTeam/AdguardForMac#499]
### V1.3.344
* [Fix] PCRE updated to 8.43
* [Fix] Fix crash in HTTP/1.1 module
#### Android specific
* [Fix] Server is not started when safebrowing is disabled
#### Windows specific
* [Fix(regression)] forum.ru-board.com - net::ERR_INCOMPLETE_CHUNKED_ENCODING: AdguardTeam/CoreLibs#849

### V1.3.340
* [Fix] Deny duplicate attributes in HTML rules
* [Fix] Small Content-Security-Policy fix
#### Windows specific
* [Fix] forum.ru-board.com - net::ERR_INCOMPLETE_CHUNKED_ENCODING: AdguardTeam/CoreLibs#849

**Comment by Stillness-2** [comment]
#506
