### ISSUE TITLE
Show extensions' version and update date on the screen.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#501]
This is the screenshot of extensions in AG for Mac v2.0.2 beta.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/vLDHpGP.png)
</details><br/>

This is the screenshot of extensions in AG for Windows v7 nightly.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/R1vQ6yN.png)
</details><br/>

May you show extensions' version and update date in AG for Mac v2 such like AG for Windows v7?

**Comment by ameshkov** [comment]
> May you show extensions' version and update date in AG for Mac v2 such like AG for Windows v7?

This will only be done when we add full userscripts support to AG for Mac.
