### ISSUE TITLE
The blocking page of AG for Mac is English while system language is Chinese (or Portuguese) locale.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#502]
@sfionov

May be related to these bugs.
https://github.com/AdguardTeam/AdguardForAndroid/issues/2651
https://github.com/AdguardTeam/CoreLibs/issues/805
I guess maybe it's the same situation in Portuguese.

But I found that the 2 phrases are also in Adguard for Mac / AdGuard for Mac 2.0 on onesky.
#48597459
This web page at <strong>(var.Host)</strong> has been reported as a malware page and has been blocked based on your security preferences.

#48597461
This web page at <strong>(var.Host)</strong> has been reported as a phishing page and has been blocked based on your security preferences.

Does AG for Mac not use the phrases about blocking pages in Misc / Misc on onesky?

Test the domain:
https://ilo134ulih.com/
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/0IBgNPh.png)
</details><br/>

Hope the blocking page can be Traditional Chinese (zh-TW) while system language is Traditional Chinese.
Thanks.

**Comment by ameshkov** [comment]
Blocking pages are managed by CoreLibs, and AG for Mac the previous version of CoreLibs where these issues aren't solved yet. You should simply wait a little bit until the newer version of CoreLibs is shipped.

**Comment by lancelot-moon** [comment]
I supposed that this should be solved in
https://github.com/AdguardTeam/AdguardForMac/issues/491.

The issue was fixed in AG for Windows/Android.

But the CoreLibs is v1.3.335 in AG for Mac v2.0.2 beta.
It's still English.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/ckMziRu.png)
</details><br/>

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #917](https://github.com/AdguardTeam/CoreLibs/issues/917) via [**ZenHub**](https://www.zenhub.com/)

**Comment by ameshkov** [comment]
@maximtop might be the same issue as https://github.com/AdguardTeam/AdguardForMac/issues/503#issuecomment-496028881

**Comment by lancelot-moon** [comment]
In v2.0.3 beta, the blocking page is still an English page.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/jXTv9nk.png)
</details><br/>

You didn't check by yourself.

**Comment by lancelot-moon** [comment]
@Stillness-2 

Why is the issue fixed in nightly but NOT fixed in v2.0.4 Release?

The same wrong things as v2.0.3 beta.
The blocking page is English.
