### ISSUE TITLE
Please use Traditional Chinese translations for Web of Trust, AdGuard Assistant and Popup blocker when choosing Traditional Chinese interface in the system preferences of macOS.

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#503]
@zzebrum commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardAssistant/issues/264)

@lancelot-moon commented on [Sat Sep 29 2018](https://github.com/AdguardTeam/AdguardForMac/issues/336)

I don't have Mac, but I saw another Taiwanese user shared screenshots about AdGuard for Mac.
It seems that you used wrong language (Simplified Chinese) in Traditional Chinese interface.
The Chinese characters in the screenshot are Simplified Chinese, not Traditional Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/hw0FntT.png)
</details><br/>

This can be for your reference.
https://github.com/AdguardTeam/AdguardForWindows/issues/2302#issuecomment-416605008

zh-CN is Simplified Chinese for China.
zh-TW is Traditional Chinese for Taiwan.
On oneskyapp, Traditional Chinese in MISCELLANEOUS were all done long time ago.

Please check that you should use zh-TW for Web of Trust, AdGuard Assistant and Popup blocker when choosing Traditional Chinese interface in the system preferences of macOS.
https://github.com/AdguardTeam/AdguardForMac/issues/318#issuecomment-397222633

Thanks.

---

@ameshkov commented on [Tue Nov 06 2018](https://github.com/AdguardTeam/AdguardForMac/issues/336#issuecomment-436164506)

@zebrum could you please check it in the nightly version?

---

@zzebrum commented on [Tue Nov 13 2018](https://github.com/AdguardTeam/AdguardForMac/issues/336#issuecomment-438186820)

reproduced.

---

@lancelot-moon commented on [Sat May 25 2019](https://github.com/AdguardTeam/AdguardAssistant/issues/264#issuecomment-495828802)

This bug isn't fixed in AG for Mac v2.0.2 Beta.
@ameshkov 
1. May you assign someone to early fix the bug **before AG for Mac v2 Release**?

AG Assistant is Simplified Chinese (zh-CN) interface while system language is Traditional Chinese (zh-TW).
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/FX1uIwo.png)

![image](https://i.imgur.com/HyWgeRN.png)
</details><br/>

**Are you using the latest extensions in AG for Mac v2?
May you really check if Traditional Chinese normally represent for Web of Trust, AG Assistant, AG Extra and Popup blocker while system language is Traditional Chinese (zh-TW)?**

2. How about AG Assistant in AG for Safari?
The same bug?

3. Simplified Chinese are outmoded translations in AG Assistant.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/zPH6ixV.png)
</details><br/>

You can see WoT isn't correctly shown in the below.
Lack placeholders in Simplified Chinese translations.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/FX1uIwo.png)
</details><br/>

This is the correct Traditional Chinese interface of AG Assistant in AG for Windows v7 for your reference.
You can see the placeholder of WoT.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/fjuXQta.png)
</details><br/>

Thanks.

**Comment by ameshkov** [comment]
Moved to AG for Mac repo so that I could assign release v2 to it. I'd like this to be fixed asap.

@maximtop we need to test this.

I suppose the issue is caused by different locales naming on Mac and other platforms. It is `zh-tw` on Win and Android, but it is `zh-hans-tw` on Mac.

**Comment by lancelot-moon** [comment]
You use a wrong locale in v2.0.3 beta.
No, it's zh-hant-tw, not zh-hans-tw.
In v2.0.3 beta, AG Assistant is still Simplified Chinese.
It should be Traditional Chinese in Traditional Chinese interface.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/Y5IZqFM.png)
</details><br/>

**Comment by Stillness-2** [comment]
@lancelot-moon check latest nightly build please

**Comment by lancelot-moon** [comment]
Fixed, thanks.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/6bt3cpC.png)

![image](https://i.imgur.com/kaCRa7N.png)

![image](https://i.imgur.com/1YisbVv.png)
</details><br/>

**Comment by lancelot-moon** [comment]
@Stillness-2 

Why is the issue fixed in nightly but NOT fixed in v2.0.4 Release?

The same wrong things as v2.0.3 beta.

**Comment by Stillness-2** [comment]
![螢幕快照 2019-05-31 上午9 37 20](https://user-images.githubusercontent.com/12689/58686545-c9254f80-8387-11e9-88d9-77ff597e9beb.png)
@lancelot-moon Is this traditional?

**Comment by lancelot-moon** [comment]
Your screenshots are Traditional Chinese.
But I don't know why the netfriend gets the same wrong things as v2.0.3 beta when he use v2.0.4 beta.
https://imgur.com/a/0S2TQlt

**Comment by lancelot-moon** [comment]
The more information:
https://imgur.com/a/JZ7tSNP

**Comment by lancelot-moon** [comment]
He said the wrong issues happen in v2.0.4 Release.

But everything is ok in v2.0.4 nightly.

https://imgur.com/a/PEaS6sO

**Comment by lancelot-moon** [comment]
He said most apps use zh_TW for Traditional Chinese (Taiwan).

But AdGuard for Mac use zh-Hant.
https://imgur.com/a/21NMIZN

**Comment by Stillness-2** [comment]
@lancelot-moon Run this utility in the terminal (`Terminal.app`). And give us what this program will print.
[test-locale.zip](https://github.com/AdguardTeam/AdguardForMac/files/3240273/test-locale.zip)

**Comment by lancelot-moon** [comment]
https://i.imgur.com/9Ou2JmZ.jpg

**Comment by lancelot-moon** [comment]
Do you remember this?
https://github.com/AdguardTeam/AdguardForMac/issues/319#issuecomment-496845681

I guess the locale of Traditional Chinese (Taiwan) in macOS is zh_TW, not zh-Hant-TW...

zh_TW matches zh_TW but doesn't match zh-Hant-TW.

zh-Hant matches zh-Hant-TW and zh-Hant-HK but doesn't match zh_TW.

**Comment by Stillness-2** [comment]
"BTW, everything is correct in nightly version but is failed in release version.
Strange."
`nightly` and `release` - the same build. I do not rebuilt app for release, only name changed!
Very strange

**Comment by lancelot-moon** [comment]
Try use zh_TW as the locale of Traditional Chinese.

Well, let Hong Kong go. XD
(Traditional Chinese is used in Taiwan and Hong Kong.)

**Comment by lancelot-moon** [comment]
Hi, I get some information.
1. If updating app from old version, it's Traditional Chinese.

2. If first installing AG v2 nightly and then also installing AG v2 release, it's Traditional Chinese.

3. If cleanly installing AG v2 release (no any AG for Mac installed), it's Simplified Chinese.

**Comment by Stillness-2** [comment]
"If cleanly installing AG v2 release (no any AG for Mac installed), it's Simplified Chinese."

**Comment by Stillness-2** [comment]
"If cleanly installing AG v2 release (no any AG for Mac installed), it's Simplified Chinese."
installed using `AdGuard installer`, which downloaded from `adguard.com` (pressing "DOWNLOAD")?

**Comment by lancelot-moon** [comment]
Remove AG for Mac if ever installing it.
Download AG for Mac v2 release installer from GitHub and cleanly install it.

The issue should be reproduced.

**Comment by Stillness-2** [comment]
@lancelot-moon Thank you. On GitHub was wrong build. :) Check now please.

**Comment by lancelot-moon** [comment]
Good!
The installer on GitHub is fixed.
You can close the related issues.
https://i.imgur.com/yKOE2yJ.png

Thanks!
