### ISSUE TITLE
Stealth mode isn't enabled according to the protection level in the configuration (setup wizard).

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#504]
If we choose any privacy protection level (ex: comfortable level) in the configuration, stealth mode is disabled by default.
<details><summary>Screenshots:</summary>

![image](https://i.imgur.com/YwZOf5q.jpg)

![image](https://i.imgur.com/HTLIkXj.jpg)
</details><br/>

I supposed stealth mode should be enabled and set according to the privacy protection level since users didn't choose "protection disabled" in the configuration from the beginning.

The selection of privacy protection level in the configuration works in AG for Android v3 but is failed in AG for Mac v2 beta.

**Comment by zzebrum** [comment]
@lancelot-moon comfortable level includes Advanced tracking protection filter only here.

**Comment by lancelot-moon** [comment]
Advanced tracking protection filter??
Do you mean AG tracking protection filter?

No, privacy protection level is for stealth mode.
4 options:
Protection disabled
Comfortable protection level
High protection level
Paranoid protection level

Do you not know stealth mode pre-configuration in the setup wizard of AG for Android?

@ameshkov
It's very strange to select comfortable protection level, but stealth mode is disabled.
