### ISSUE TITLE
Support dark mode.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#508]
Please give the option of light/dark mode.
Thanks.

**Comment by iDjay** [comment]
It supports dark mode on 2.0 beta

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lancelot-moon** [comment]
I don't have Mac.
Simply, I don't find the phrases about light/dark mode on onesky.
So I supposed that AG for Mac doesn't have dark mode.
Please close the issue if I misunderstood.
Sorry & thanks.
