### ISSUE TITLE
Using Adguard 2 on a mac with more than one account

### ISSUE THREAD

**Issue by zuzung** [AdguardTeam/AdguardForMac#509]
### Steps to reproduce

1.  Using Adguard 2.x beta on a mac with two accounts, both with admin rights
2. Once i log into the other account (not logging out of the first one) webpages using https don't load, or about 90% don't load at all.
3. They only load if https filtering is switched off (which isn't an acceptabe solution, obviously)
4. Once i reset all settings to default, and then switch on https filtering, pages again load as they normally should. 
5. BUT after switching to the other account (without logging out from previous one), the same problems occurs again - pages not loading with https filtering on, only after a settings reset.

### Expected behavior

Didn't have these issues with Adguard 1.x. Adguard 2 should handle macs with multiple account correctly.

### Actual behavior
Pages don't load - tested only in Safari - because the server was not found.

<details><summary>Screenshot:</summary>

</details>

### Your environment

Mojave 10.14.5, Safari 12.1.1.

**Comment by Stillness-2** [comment]
transfered to CL https://github.com/AdguardTeam/CoreLibs/issues/953
