### ISSUE TITLE
Filters become Simplified Chinese in Traditional Chinese interface.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#510]
@ameshkov 
@Stillness-2 

In v2.0.3 beta, you don't solve my issues, and it gets the worst.
https://github.com/AdguardTeam/AdguardForMac/issues/502
https://github.com/AdguardTeam/AdguardForMac/issues/503

You use a wrong locale.
No, it's `zh-hant-tw`, not `zh-hans-tw`.
Sorry, I didn't early remind you at that time, which is my fault.
https://github.com/AdguardTeam/AdguardForMac/issues/503#issuecomment-496028881
The "t" in hant means Traditional Chinese.
The "s" in hans means Simplified Chinese.

BTW, my Traditional Chinese translations are in `zh-TW` locale on onesky.

Filters become Simplified Chinese in Traditional Chinese interface.
In v2.0.2 beta, filters were correctly shown as Traditional Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/WB65tN3.png)
</details><br/>

In v2.0.3 beta, filters wrongly become Simplified Chinese.
<details><summary>Screenshot:</summary>

![image](https://i.imgur.com/9Vk272q.png)
</details><br/>

**Comment by ameshkov** [comment]
@lancelot-moon when you open an issue on Github, this is **completely unnecessary** to mention people.

**Comment by ameshkov** [comment]
dup of https://github.com/AdguardTeam/AdguardForMac/issues/510
