### ISSUE TITLE
Remove „release“ from version number

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#512]
![GitHawk Upload by iDjay](https://i.imgur.com/94IE8c9.jpg)

It‘s not really an issue / bug, but I would prefer a cleaner version number without the „release“ text 😊

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
This actually would be quite hard to change - we use this version postfix in our automation tools
