### ISSUE TITLE
AdguardForMac 2.0.4  wrecking Chrome Remote Desktop

### ISSUE THREAD

**Issue by gitguys** [AdguardTeam/AdguardForMac#515]
Upgraded from 1.x to 2.0.4 and now Chrome Remote Desktop is broken.

### Expected behavior

Be able to connect to Chrome Remote Desktop Hosts

### Actual behavior

Times out.

I turned off Adguard and still couldn't connect until I restarted my Mac.  Then CRD worked perfectly until I turned Adguard back on again.

Reverting back to 1.x version fixes the trouble.  Using latest version of Chrome on macOS Sierra.

**Comment by zzebrum** [comment]
@gitguys so far can not reproduce the issue.
can you reproduce the problem and send it to support with a diagnostic report attached to the email?
also what filters and Stealth mode options are enabled in settings?

**Comment by gitguys** [comment]
@zzebrum unfortunately I'm in the middle of time sensitive projects involving CRD and can't afford to risk losing access right now.  However, it may help to know I had turned on most the the privacy settings that were available. It could be that's where the trouble started with one or more of those settings being turned on.  Perhaps turn on all the settings until you lose access.  Also, I was using macOS Sierra 10.12.6 so it may be specific to that version.

**Comment by ameshkov** [comment]
Yeah, it might be one of the stealth mode features breaking it. @zzebrum could you please check?

**Comment by Stillness-2** [comment]
@gitguys Check please with last nightly version http://agrd.io/mac_nightly

**Comment by zzebrum** [comment]
that's because of WerRTC. I'll upload logs in nextcloud

**Comment by planet0** [comment]
Another user having trouble with Chrome Remote Desktop, perhaps on PC though: https://www.reddit.com/r/Adguard/comments/cmfjgo/chrome_remote_desktop_wont_connect/

**Comment by ameshkov** [comment]
This is "blocking webrtc" working as expected. Temp fix: do not block webrtc.

Meanwhile, we'll think about how to work with webrtc more carefully

**Comment by ameshkov** [comment]
After all, it seems there is no "fix" for this. If AdGuard is told to block WebRTC, it should block it, otherwise, the real IP can leak. We cannot make an exclusion for some software that supposedly does not use/record it.
