### ISSUE TITLE
assistant settings  problem

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#516]
macOS Mojave  version 10.14.5
AdGuard version 2.04.552

assistant settings on safari/firefox/chrome   cann't save changes

![image](https://user-images.githubusercontent.com/3109626/58751763-b4ef6880-84d5-11e9-98f6-d4469903970b.jpeg)

**Comment by PMheart** [comment]
Can be reproduced here. Identical AdGuard version and macOS build.

**Comment by zzebrum** [comment]
guys, if the issue still reproducible, enable debug lo (AG - settings - advanced - logging level), reproduce the problem, export log file (AG - settings - advanced - export logs and system info) and send it to mg[at]adguard[dot]com

**Comment by PMheart** [comment]
@zzebrum Sent. Thanks!

**Comment by zzebrum** [comment]
@PMheart haven't received your message :(

**Comment by PMheart** [comment]
@zzebrum That's weird, anyway, sent again with another address.

**Comment by Eugene-Savenko** [comment]
@zebrum we have logs provided by another customer here: 2228241

**Comment by zzebrum** [comment]
@spacexnasa @PMheart guys, if the issue still reproducible, please, save your User filter if needed by using import/export in Filters: https://uploads.adguard.com/AdGuard_Preferences_-_Filters_2019-06-25_12-36-52.png
then reset program settings (AdGuard - Advanced - Reset Settings) and check if it helps.

**Comment by zzebrum** [comment]
funny thing, Reset settings option is kinda broken #543 in the latest builds, use force quit in Activity monitor then :(

**Comment by PMheart** [comment]
Unfortunately not. Tried a fresh install on a VM, no luck. :(

**Comment by zzebrum** [comment]
@spacexnasa @PMheart how the issue goes on the latest release version? still reproducible?

**Comment by PMheart** [comment]
Hello,

What I am currently using is `2.1.5.626 nightly`, with this issue RESOLVED!
However, I have no idea whether it gets fixed in the release version. Sorry about that.

Thanks for your efforts!

PMheart

**Comment by zzebrum** [comment]
@spacexnasa any update on this?
