### ISSUE TITLE
Major battery resourse consumption on Mac

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#52]
When Adguard is enabled, user Mac's battery discharges extremely fast. He has sent SIGABRT dump around January, 13th.

You can find more details in the ticket: RIP-854-27792

**Comment by Bohdan-SUP** [comment]
Please check crash report here - RIP-854-27792

**Comment by ameshkov** [comment]
@Stillness-2 could you please take a look?

**Comment by Stillness-2** [comment]
We have two problems.
1. Hang app when open Preferences, at the same time Mac have mounted network drives, but they are not available. "Launch at login" component affects on it.
2. Permanently loads CPU about 100%

**Comment by Stillness-2** [comment]
@gshumihin We will need testing "Launch at Login" on 10.7

**Comment by Stillness-2** [comment]
commit 25015
