### ISSUE TITLE
Use of wildcards (*) and domain signs (@) for complex rules under the Strip tracking parameters section under the Stealth Mode partition

### ISSUE THREAD

**Issue by arturbikbaev** [AdguardTeam/AdguardForMac#525]
**Feature request for the AdGuard desktop app (macOS and Windows)**

Please consider adding the following features to the **Strip tracking parameters** section under the **Stealth Mode** partition in the AdGuard desktop app (macOS and Windows):

1. Ability to use wildcards in rules, i.e. `pd_rd_*`
2. Ability to set rules for specific domains, i.e. `*@amazon.com`

**As a result** we will be able to use complex rules like `pd_rd_*@amazon.*` in the **Strip tracking parameters** section under the **Stealth Mode** partition in the AdGuard desktop app

**My environment**

- macOS Mojave 10.14.5
- Safari 12.1.1 (14607.2.6.1.1)
- AdGuard 2.0.4.552
- macOS Mojave's built-in Firewall
- No antivirus

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #958](https://github.com/AdguardTeam/CoreLibs/issues/958) via [**ZenHub**](https://www.zenhub.com/)
