### ISSUE TITLE
[10.15] AdGuard icon is invisible

### ISSUE THREAD

**Issue by GauthierPLM** [AdguardTeam/AdguardForMac#527]
### Steps to reproduce
1. Install AdGuard on MacOS 10.15 Catalina.
2. Select "Automatic" theme for the system.
3. AdGuard icon in the menu bar becomes invisible.

### Expected behavior
The icon should be dark during day and black during night according to system theme.

### Actual behavior
The icon is invisible.

### Your environment

* Environment name and version: (e.g. Chrome 59): MacOS 10.15 Beta 1, AdGuard Stable (2.0.4)

**Comment by iDjay** [comment]
Is this fixed already in the nightly version?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@iDjay not yet

**Comment by GauthierPLM** [comment]
For me it's fixed with the latest version of MacOS (10.15 (19A583)) and AdGuard 2.1.3.611.

Can other confirm if they still have the issue or not?

**Comment by iDjay** [comment]
> For me it's fixed with the latest version of MacOS (10.15 (19A583)) and AdGuard 2.1.3.611.
> 
> Can other confirm if they still have the issue or not?

Not fixed, still having the issue.

**Comment by iDjay** [comment]
but maybe it's an macOS issue, f.e. weTransfer is invisible too.

**Comment by zzebrum** [comment]
looks like the macOS issue, seems to be working now on my side.

**Comment by iDjay** [comment]
@zzebrum how did you fix it?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@iDjay we didn't do anything in AdGuard. I'm on Catalina 10.15 beta 19a578c - I've checked the issue with the latest beta and now it is working ok.

**Comment by iDjay** [comment]
@zzebrum you‘re using an old version. Catalina got released on Monday. The current build is 19A583.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
Maybe here‘s the solution? https://github.com/electron/electron/pull/18666

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
Now it‘s working here too after the appearance switched to dark. Maybe it‘s just an issue during the day?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
It‘s not fixed with 2.1.3 @zzebrum 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sysfu** [comment]
I'm having the same problem with 2.1.3.600 on macOS 10.15. Works fine in night mode, but invisible during day mode. I would also prefer an option to choose a green icon for day mode.

**Comment by ameshkov** [comment]
Reopened and reassigned to v2.2, we'll check it

**Comment by iDjay** [comment]
It's definitely an AdGuard issue. I have the same issue with "Splice" but they fixed it. with an update today.

**Comment by iDjay** [comment]
Seems to be fixed after Mac turns dark and to light ones. Can anyone confirm?

**Comment by zzebrum** [comment]
the latest beta and nightly versions are ok on our side.

**Comment by iDjay** [comment]
Yes, talking about the 2.2 beta

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
It‘s not fixed lol. After two days of working fine, it doesn’t work now. Maybe this issue is only happening when the system appearance change? So maybe shutting down the Mac with auto appearance dark and booting with light is causing the issue because AdGuard doesn’t understand it has to switch the icon? 
AdGuard 2.2.0.643 Beta

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
fixed in 2.2.3
