### ISSUE TITLE
adguard-tcpkill process constantly crashes on MacOS Catalina

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#530]

**Comment by akmLaVx** [comment]
It started crashing again.
AdGuard 2.1/release,  OS X 10.15 (19A602)
Crash logs in helpdesk ticket **2361381**.

**Comment by Stillness-2** [comment]
@akmLaVx I can't repeat, suggest the user to upgrade to the latest version and check again...
also, based on the ticket text, it is not visible which version of the application is used by the user
