### ISSUE TITLE
AdGuard prevents the encrypt.me app from establishing a secure connection

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#533]
It starts establishing a connection but never finishes, and the filtering log is getting populated with the below requests

![image](https://user-images.githubusercontent.com/15856304/59548937-607ccc00-8f5e-11e9-8ff1-a71d99999d36.png)

### Steps to reproduce

1. Install the encrypt.me app and log in with a valid trial account
2. Go to encrypt.me > Secure my connection

### Expected behavior

The connection is established

### Actual behavior

It keeps connecting but never connects. **Whitelisting the blocked IP with the $network rule didn't work for me**; quitting AdGuard helps

<details><summary>Screenshot:</summary>

![Screen Shot 2019-06-15 at 11 05 28](https://user-images.githubusercontent.com/15856304/59548949-9326c480-8f5e-11e9-9d3d-e139b74c14a6.png)

</details>

### Your environment

* Environment name and version: macOS 10.14.5 (18F132)
* AdGuard 2.0.6 / the latest nightly
* Any specific potentially conflicting software installed: none

**Comment by ameshkov** [comment]
Temporary solution: add `@@185.210.218.205$network` to the user filter.

**Comment by Eugene-Savenko** [comment]
I've tried that before reporting the issue here and it didn't work for me. It's stuck connecting (screenshot 1) despite the rule is added to the UF (screenshot 2).

<details> <summary> screnshot 1 </summary>

![image](https://user-images.githubusercontent.com/15856304/59624385-4cdc8b80-913f-11e9-9385-ebbedb000d38.png)

</details> 

<details> <summary> screnshot 2 </summary>

![image](https://user-images.githubusercontent.com/15856304/59624428-667dd300-913f-11e9-8be0-dea63c1c7e29.png)

</details>

**Comment by ameshkov** [comment]
My bad, the temp solution won't work. Please wait till the next nightly update.

**Comment by Stillness-2** [comment]
#528, #535

**Comment by Stillness-2** [comment]
@Eugene-Savenko Check please last nightly version http://agrd.io/mac_nightly

**Comment by Eugene-Savenko** [comment]
@Stillness-2 works fine now, thank you!
