### ISSUE TITLE
IPVanish connection issue

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#535]
### Steps to reproduce

1. Launch the IPVanish application and try to connect to the server.
2. Within a few minutes, the application tries to connect to the server (without result)
3. If you remove the application from "Filtered apps'. Then the application can connect to servers.

### Customer ID 

554246

### Your environment

* Environment name and version: AdGuard (2.0.5.555 nightly)

**Comment by sfionov** [comment]
Kext issue :(

**Comment by Stillness-2** [comment]
@Chinaski1 Check please last nightly version http://agrd.io/mac_nightly

**Comment by Chinaski1** [comment]
@Stillness-2 
Works well now.
