### ISSUE TITLE
AirVPN(Eddie) compatibility

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#536]
### Steps to reproduce

1.  Start AdGuard protection
2. Then Start VPN (AirVPN) with the app Eddie
3. Eddie can't get the connection until reboot.
4. If you start AirVPN first and after you turn on the protection then problems do not arise

### Customer ID 

[AdGuardForum](https://forum.adguard.com/index.php?threads/since-ag-mac-2-0-4-ag-dont-work-with-my-vpn-airvpn.33041/#post-183776)
### Your environment

* Environment name and version: AdGuard (2.0.4/2.0.6)

**Comment by Chinaski1** [comment]
Same problem with 
VPN client – Tunnelblick
[Logs](https://ncloud.adguard.com/apps/files/?dir=/Support/Issues/Mac/github_536&fileid=34604)

**Comment by Eugene-Savenko** [comment]
More logs here: 2235577

**Comment by Stillness-2** [comment]
Check please last nightly version http://agrd.io/mac_nightly

**Comment by Chinaski1** [comment]
@Stillness-2 
Says it works well now

**Comment by ThomasPzzz** [comment]
Yes, it seems to work on my side too.
Cheers!

**Comment by DPRReborn** [comment]
I seem to be having the same issue but with ExpressVPN :( no connection at all especially if AdGuard is started first and then turning on the VPN results in it saying no connection detected.

**Comment by ThomasPzzz** [comment]
Did you try the nightly build:  http://agrd.io/mac_nightly <http://agrd.io/mac_nightly> ?
It works for me.

**Comment by DPRReborn** [comment]
Awesome! okay so it seems to be working now with the nightly build also turned off 'stealth mode' everything seems to be in order now. :) ty!
