### ISSUE TITLE
The application does not start (2.0.4/2.0.6)

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#537]
### Steps to reproduce

1. Update or install 2.0.4/2.0.6
2. The application does not start

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/59841466-0e241c80-935d-11e9-9cf7-dfccd4925765.png)

</details>

### Customer ID

2223438
### Your environment

* Environment name and version: Mac OS X 10.12.6
* [Logs](https://ncloud.adguard.com/index.php/apps/files?dir=/Support/Issues/Mac/github_)

**Comment by zzebrum** [comment]
the user is suggested to do advanced uninstall. the issue may be related to attempting to downgrade from v2.x to 1.x
