### ISSUE TITLE
Little Snitch incompatibility

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#538]
### Steps to reproduce

1. Launch Adguard and Little Snitch 
2. Does not open any site from any browser. Safari Error - "... because I can not safely connect to ...", 
Chrome - "ERR_CONNECTION_RESET"
3. If you disable protection or Little Snitch  everything works correctly

### Customer ID 

1150941
### Your environment

* Environment name and version: Little Snitch 4.3.2 / ADGuard 2.0.5.558

**Comment by zzebrum** [comment]
the issue seems to be resolved with Little Snitch v4.4 update
