### ISSUE TITLE
AdGuard keeps spamming "Cannot install root certificate when Firefox is running"

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#539]
### Steps to reproduce
1. Install AdGuard, launch Firefox
2. You'll receive a "Cannot install root certificate when Firefox is running message"
3. Close the browser
4. Same as 2
5. Install certificate manually
6. Same as 2

### Expected behavior
AdGuard shouldn't constantly display "Cannot install root certificate when Firefox is running message", especially if said cert is already installed

### Actual behavior
AdGuard keeps spamming the user with  "Cannot install root certificate when Firefox is running message" error

<details><summary>Screenshot:</summary>

N/A
</details>

### Customer ID & Logs
2229512

### Your environment
* Environment name and version: (e.g. Chrome 59): OS X 10.14.5, AdGuard 2.0.4.552 release
* Any specific potentially conflicting software installed: None found

**Comment by TheHasagi** [comment]
Customer is using 2.0.4.552, so [release](https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.0.6) version is 2.06. He should try to reproduce this issue with the release and check again.

**Comment by akmLaVx** [comment]
Moving to 2.0.6 did not resolve the issue.

**Comment by ameshkov** [comment]
Confirmed

**Comment by ameshkov** [comment]
This was caused by #596
