### ISSUE TITLE
Installation stucks at "Need your permission" screen

### ISSUE THREAD

**Issue by alwynpan** [AdguardTeam/AdguardForMac#545]
### Steps to reproduce

1. Install AdGuard and go through the setup wizard.
2. Click "Open System Preferences" when prompted, and allow AdGuard
3. Close System Preferences window
4. "Need your permission" window won't close and AdGuard cannot be enabled.

### Expected behavior

"Need your permission" windows goes away and AdGuard should be enabled.

### Actual behavior

"Need your permission" stucks and AdGuard cannot be enabled.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/9387800/60161937-d117c880-983b-11e9-9d4b-b27415fd317b.png)

</details>

### Customer ID 

Cannot get ID, got this "Error occurred when sending message" when I tried to send the report.

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

macOS: 10.14.5
AdGuard: 2.0.6.559 (CL-1.4.13)

**Comment by alwynpan** [comment]
**Workaround:** Uninstall AdGurad and reinstall.

**Comment by ameshkov** [comment]
Most likely this is a macOS glitch.

Please reopen if this happens ever again.
