### ISSUE TITLE
Wrong web page encoding or Automatic download page files 

### ISSUE THREAD

**Issue by Chandler-Lu** [AdguardTeam/AdguardForMac#546]
When I visit a page without HTTPS, just like http://bbs.pcbeta.com/forum-win10-1.html, the web page may display garbled characters or Automatic download page file (forum-win10-1.html). Then I need to refresh some times, the page can display normally.

### Expected behavior

display normally

### Actual behavior

garbled characters, lose css style, automatic download page file

### Your environment

* Environment name and version: (e.g. Chrome 59): safari 12.1.1 (14607.2.6.1.1)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): [ClashX](https://github.com/yichengchen/clashX)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #986](https://github.com/AdguardTeam/CoreLibs/issues/986) via [**ZenHub**](https://www.zenhub.com/)
