### ISSUE TITLE
AdGuard Assistant is missing in Safari 9

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#547]
The assistant does not appear in any browser.
Advanced reinstall, clean cache, etc not bring any effect.

### Customer ID 

[Forum](https://forum.adguard.com/index.php?threads/no-shield-in-the-browser.32883/#post-183386)

Logs in NCloud

### Your environment

* Environment name and version: OSX 10.11.6 /AG 2.0.6.560N/SAFARI (9.1.3 )/FIREFOX(62.0.3) 
* Any specific potentially conflicting software installed: only the system Firewall

**Comment by ameshkov** [comment]
Safari 9??

**Comment by akmLaVx** [comment]
Got a pretty similar case here: 2243289

Assistant just disappeared from Safari. The only option that helped the user was to disable "Automatically filter applications" and refresh the browser.

**Comment by Chinaski1** [comment]
After update to 11 version issue is resolved

**Comment by Stillness-2** [comment]
Assistant does not support old Safari...
