### ISSUE TITLE
iTunes Store access issue

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#552]
iTunes Store simply shows a blank page.

### Customer ID 

[2249546](https://qcrm.supportyourapp.com/#/customer/2249546)
[2249545](https://qcrm.supportyourapp.com/#/customer/2249545)
[2247111](https://qcrm.supportyourapp.com/#/customer/2247111)
[2244975](https://qcrm.supportyourapp.com/#/customer/2244975)
[2248023](https://qcrm.supportyourapp.com/#/customer/2248023)
[1115806](https://qcrm.supportyourapp.com/#/customer/1115806)
[2238029](https://qcrm.supportyourapp.com/#/customer/2238029)
[2235591](https://qcrm.supportyourapp.com/#/customer/2235591)

2135992

**Logs in NCloud**

**Comment by zer212112** [comment]
также столкнулся с подобной проблемой

macOS 10.11.6

adguard 2.0.6 stab

ьазовый фильтр
фильтр счётчиков
фильтр раздрожажителей
русский фильтр

настройки программы стандартные
отключение фильтров не помогает

**Comment by planet0** [comment]
Yes, also experienced that in stable up to date iTunes and macOS.
Now in Catalina, the Music app still has trouble accessing the iTunes Store fully.

**Comment by planet0** [comment]
Okay, definitely related to how AdGuard uses HTTPS. When turned off, and the cache is reset, and you quit the app and relaunch it, the iTunes Store loads perfect.

<img width="1212" alt="Screen Shot 2019-07-14 at 1 25 15 pm" src="https://user-images.githubusercontent.com/46271764/61178896-d433f680-a63a-11e9-9f07-819a86acd956.png">

Do the same thing but with AdGuard HTTPS Filtering enabled, and it is a mess. However interestingly, if you force refresh it a second time, it can sometimes fix itself (Press command + R).

<img width="1212" alt="Screen Shot 2019-07-14 at 1 23 05 pm" src="https://user-images.githubusercontent.com/46271764/61178898-d6965080-a63a-11e9-8c90-d053191e96cd.png">

Resetting Cache each time for testing is essential, for some reason the cache will keep the failed page. Button is located in Advanced settings.

<img width="497" alt="Screen Shot 2019-07-14 at 1 22 12 pm" src="https://user-images.githubusercontent.com/46271764/61178922-4ad0f400-a63b-11e9-90b3-3ffe3522b578.png">

I also tried adding all the domains that the iTunes Store uses (captured via Pi-hole) to both the AdGuard Whitelist and HTTPS Exclusions... but that doesn't seem to work.

Perhaps this is a more deeper issue, within CoreLibs perhaps? @ameshkov

**Comment by gilby101** [comment]
As @planet0 says, definitely related to https.  I get exactly that behaviour.

One thing that confuses me, is that AG log refers to the iTunes (and Books) as being from the Safari app.

**Comment by zzebrum** [comment]
guys, there is [new nightly available](https://static.adguard.com/mac/Adguard-2.1.0.571.nightly.dmg)
try it! seems to be working due to #556? I've reset cache though.

**Comment by planet0** [comment]
@zzebrum Unfortunately on macOS Mojave the iTunes Store is still blank with 'Filter HTTPS protocol' enabled, I couldn't get it working on 2.1.0.571 nightly.

Unchecking that still fixed the issue.

(I needed to go back to Mojave from Catalina, so I am back to stable macOS and iTunes Version 12.9.5.5).

**Comment by mtkushner** [comment]
Please keep in mind as in my original bug report, that the Books store has the same problem - blank page when entering, blank page when searching. The only way to restore the iTunes Store and Book store is to completely purge Adguard, and clear out caches. Obviously not desirable behaviour.

**Comment by planet0** [comment]
So far we are able to narrow it down to the 'Filter HTTPS protocol' setting, and setting exclusions does not work.

**Comment by mtkushner** [comment]
Agreed planet0 on both counts about the nightly build and setting exclusions.

**Comment by planet0** [comment]
@mtkushner @zzebrum @ameshkov @TheHasagi 

And just for the sake of consistency, here is the same behaviour on current stable macOS Mojave with AdGuard 2.1.0.571 nightly.

**With 'Filter HTTPS protocol' enabled** (on by default)
<img width="1254" alt="Screen Shot 2019-07-18 at 9 28 09 pm" src="https://user-images.githubusercontent.com/46271764/61454093-3d04d100-a9a3-11e9-898a-a4c741af5408.png">


**With 'Filter HTTPS protocol' disabled**
<img width="1250" alt="Screen Shot 2019-07-18 at 9 28 52 pm" src="https://user-images.githubusercontent.com/46271764/61454098-4130ee80-a9a3-11e9-8154-b979c5c2ed74.png">

**Comment by mtkushner** [comment]
Not only is the iTunes Store page blank, it reports No items in the status bar. In my case, it is irrelevant whether or not the Filter HTTPS protocol is on or off.

**Comment by planet0** [comment]
> In my case, it is irrelevant whether or not the Filter HTTPS protocol is on or off.

What if you follow the previous steps I mentioned?
> 1. Turn AdGuard HTTPS Filtering off, and
> 2. the iTunes Store cache **must** be reset, and
> 3. you **must** quit the app and relaunch it to the iTunes Store

**Comment by planet0** [comment]
Guys, I figured it out.
You need to have **mzstatic.com** as an exclusion for the 'Filter HTTPS protocol'.

@ameshkov @mtkushner @zzebrum @TheHasagi @gilby101

**Comment by mtkushner** [comment]
> > In my case, it is irrelevant whether or not the Filter HTTPS protocol is on or off.
> 
> What if you follow the previous steps I mentioned?
> 
> > 1. Turn AdGuard HTTPS Filtering off, and
> > 2. the iTunes Store cache **must** be reset, and
> > 3. you **must** quit the app and relaunch it to the iTunes Store

No, planet0. It makes no difference. iTunes Store and Books Store are both blank.

**Comment by planet0** [comment]
> No, planet0. It makes no difference. iTunes Store and Books Store are both blank.

@mtkushner, I'm able to reproduce the issue and resolve the issue over and over again. We'll need to record each other's procedures to figure out why you still are having issues.

Here is what is happening on a fresh macOS system (only 2 days old) - from AdGuard's default setting, to adding mzstatic.com to exclusions to work again.

[itunes480p.mov.zip](https://github.com/AdguardTeam/AdguardForMac/files/3408780/itunes480p.mov.zip)

**Comment by ameshkov** [comment]
@mtkushner could you please try this build and see if it helps?
https://uploads.adguard.com/up04_i3itc_Adguard-2.1.0.573.nightly.dmg

**Comment by mtkushner** [comment]
I completely purged Adguard, and removed caches for iTunes and the Books Store. I then installed the 2.10.572 nightly build. Without adding the mzstatic.com address, both stores appear to work. Also, I didn't clear the iTunes cache. I tried it a second time, and all seemed well.

UNTIL I searched for a matched song in my iTunes Library by right-clicking and choosing Show in iTunes Store. BLANK results. Quit iTunes (no need to clear the cache). Restart iTunes and go to the iTunes Store; it's okay when browsing. Search and get blank results. Browse and the iTunes Store is restored.

The Books Store shows much the same behaviour. Browse is fine. Search shows results. Click on a specific book in either browse or search mode. Blank results. Browse by clicking on Featured, Top Charts, Categories, Top Authors; Books Store shows results. Click on a specific book. Blank.

So, top level appears okay, but anything past that level results in blank pages.

**Comment by planet0** [comment]
@mtkushner Have you added mzstatic.com and then tried to visit a specific album or book?
Could you try the build that @ameshkov provided?

**Comment by planet0** [comment]
@mtkushner It's still working here even viewing single items in the iTunes Store and Book Store.

Could you try the build that @ameshkov provided?
> https://uploads.adguard.com/up04_i3itc_Adguard-2.1.0.573.nightly.dmg

After installing the build, relaunch iTunes and Books, and try visiting both stores. Also viewing single items.

**Comment by mtkushner** [comment]
Yes. I just tried that build. I note that apple.com and mzstatic.com are included in that build. I get the same results as I reported: top level okay, drilling down in both stores results in blank pages. I'm going to have to pause now (work).

**Comment by mtkushner** [comment]
Okay one more report. I completely deleted com.apple.iTunes from Library. I quit Adguard. I ran iTunes. Normal behaviour. I restarted Adguard 2.1.0.573 nightly. iTunes Store works fine now at both top level and detail level. EXCELLENT. Unfortunately, Books Store is not working even with Adguard not running. There is no cache at the moment to delete, so I can't seem to restore functionality. I'll try a restart later and experiment then. Thanks.

**Comment by planet0** [comment]
Try running in Terminal with Books not running:
`sudo rm -rf ~/Library/Containers/com.apple.iBooksX`

And relaunch Books.

**Comment by mtkushner** [comment]
Everything seems to be working right now. Congratulations to all involved in finding the issue and devising a fix.

**Comment by ameshkov** [comment]
@Chinaski1 we need to make an instruction for the customers who are suffering from this issue. It seems that these apps cache is corrupted and needs to be removed.

1. Add `apple.com` and `mzstatic.com` to the HTTPS exclusions list;
2. Clear iTunes and Books cache: see [here](https://user-images.githubusercontent.com/46271764/61178922-4ad0f400-a63b-11e9-90b3-3ffe3522b578.png) and [here](https://github.com/AdguardTeam/AdguardForMac/issues/552#issuecomment-513211092)
3. Restart the apps

**Comment by Chinaski1** [comment]
I mailed to specified users.
Now waiting for feedback

**Comment by pradorocchi** [comment]
Hello all, 
I just posted this information on AdGuard forum, but then I noticed there is here a better place for this technical info, so I'm putting it here.

A full listing of DNS queries, collected from the **new App Music** v1.0.0.317 from the latest MacOS Catalina Developer Beta [19A512f]


**[CNAME]s DNS Queries:** 

1. **ax.itunes.apple.com** -> ax.itunes.apple.com.edgesuite.net 

2. **init.itunes.apple.com** -> init-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

3. **p16-buy.itunes.apple.com**

4. **s.mzstatic.com** -> s.mzstatic.itunes-apple.com.akadns.net -> s-mzstatic-applak.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

5. **upp.itunes.apple.com** -> upp-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

6. **ld-1.itunes.apple.com** -> ld-1.itunes-apple.com.akadns.net

7. **se2.itunes.apple.com** -> se2-cdn.itunes-apple.com.akadns.net -> se2.itunes.apple.com.edgekey.net

8. **sync.itunes.apple.com** -> sync-cdn.itunes-apple.com.akadns.net ->  itunes.apple.com.edgekey.net

9. **gsp-ssl.ls.apple.com** -> gsp-ssl.ls-apple.com.akadns.net -> gsp-ssl-geomap.ls-apple.com.akadns.net -> gsp-ssl-gspxramp.ls-apple.com.akadns.net -> gsp-ssl-frontend.ls-apple.com.akadns.net -> gsp-ssl-v2.ls3-apple.com.akadns.net

10. **itunes.apple.com** -> itunes-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net 

11. **gateway.icloud.com** -> gateway.fe.apple-dns.net

12. **music.apple.com** -> itunes-cdn.itunes-apple.com.akadns.net ->  itunes.apple.com.edgekey.net

13. **xp.apple.com** -> xp.itunes-apple.com.akadns.net

_ 
**additional DNS queries for Authentication:** [ Login / Buy / Coupon-Gift verification ]

14. **p16-buy.itunes.apple.co**m -> p16-buy.itunes-apple.com.akadns.net
15. **gsa.apple.com** -> gsa.apple.com.akadns.net
16. **gsas.apple.com** -> gsas.apple.com.akadns.net
17. **init.itunes.apple.com** -> init-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

_
**DNS queries for Audio/Play** [stream samples/music]

18. **audio-ssl.itunes.apple.com** -> itunes.assets.itunes.com.edgekey.net




_
==============================================================
**[A] records**: This is the A name, which is last DNS name returned after each CNAME pointer query (listed above), and it contains the final DNS name for each initial CNAME query + the IPv4 destination of it, respectively numbered, below:


1)  from ax.itunes.apple.com.edgesuite.net: reply a1108.gi3.akamai.net is 66.201.185.203
2)  from itunes.apple.com.edgekey.net: reply e673.dsce9.akamaiedge.net is 23.41.194.217
3)  from p16-buy.itunes.apple.com: reply p16-buy.itunes-apple.com.akadns.net is 17.154.66.79
4)  from mzstatic.com.edgekey.net: reply e673.dsce9.akamaiedge.net is 23.41.194.217
5)  reply e673.dsce9.akamaiedge.net is 23.41.194.217
6)  reply ld-1.itunes-apple.com.akadns.net is 17.56.138.29
7)  reply e673.dsce9.akamaiedge.net is 23.41.194.217
8)  reply e673.dsce9.akamaiedge.net is 23.41.194.217
9)  reply gsp-ssl-v2.ls3-apple.com.akadns.net is 17.249.146.18
10) reply e673.dsce9.akamaiedge.net is 23.41.194.217
11) reply gateway.fe.apple-dns.net: 
gateway.fe.apple-dns.net is 17.248.176.177
gateway.fe.apple-dns.net is 17.248.177.8
gateway.fe.apple-dns.net is 17.248.177.10
gateway.fe.apple-dns.net is 17.248.177.12
gateway.fe.apple-dns.net is 17.248.177.15
gateway.fe.apple-dns.net is 17.248.177.40
gateway.fe.apple-dns.net is 17.248.177.51
gateway.fe.apple-dns.net is 17.248.177.56
12) reply e673.dsce9.akamaiedge.net is 23.41.194.217
13) reply e17437.dscb.akamaiedge.net is 184.51.133.200
14) reply p16-buy.itunes-apple.com.akadns.net is 17.154.66.79
15) reply gsa.apple.com.akadns.net is 17.151.240.36
16) reply gsas.apple.com.akadns.net is 17.137.166.35
17) reply e673.dsce9.akamaiedge.net is 23.41.194.217
18) reply e12984.dsce1.akamaiedge.net is 23.41.194.86

**Comment by pradorocchi** [comment]
**TV App** [CNAME]s DNS Queries: 

- **sb.tv.apple.com** ->  itunes.apple.com.edgekey.net

- **init.itunes.apple.com** ->  init-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

- **pd.itunes.apple.com** -> pd-cdn.itunes-apple.com.akadns.net ->  itunes.apple.com.edgekey.net

- **uts-api.itunes.apple.com** ->  itunes.apple.com.edgekey.net

- **gateway.icloud.com** -> gateway.fe.apple-dns.net

- **is1-ssl.mzstatic.com** ->  is-ssl.mzstatic.com.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

- **is2-ssl.mzstatic.com** ->  is-ssl.mzstatic.com.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

- **is3-ssl.mzstatic.com** ->  is-ssl.mzstatic.com.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

- **is4-ssl.mzstatic.com** ->  is-ssl.mzstatic.com.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

- **is5-ssl.mzstatic.com** ->  is-ssl.mzstatic.com.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

- **e673.dsce9.akamaiedge.net**

- **valid.apple.com** -> valid.origin-apple.com.akadns.net -> valid-apple.g.aaplimg.com -> valid.apple.com.edgekey.net

- world-gen.g.**aaplimg.com**

- **itunes.apple.com** -> itunes-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

- **s.mzstatic.com** -> s.mzstatic.itunes-apple.com.akadns.net -> s-mzstatic-applak.itunes-apple.com.akadns.net -> mzstatic.com.edgekey.net

- **client-api.itunes.apple.com** -> client-api-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

- **se.itunes.apple.com** -> se-cdn.itunes-apple.com.akadns.net -> se-applak.itunes-apple.com.akadns.net -> se.itunes.apple.com.edgekey.net

- **play.itunes.apple.com** -> play-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

- **upp.itunes.apple.com** -> upp-cdn.itunes-apple.com.akadns.net -> itunes.apple.com.edgekey.net

- **hls.itunes.apple.com** -> hls.itunes.g.aaplimg.com

___

I was curious about [ **world-gen.g.aaplimg.com** ] domain, so I verified it more deep, 
and it is used by TV App when browsing "Watch now" or when browsing movies for rent/buy.
Deducing by its name, "aapl" means "Apple", also AAPL is the name for Apple Inc on Nasdaq, 
and "img" may be "images", so this looks like is the TV App content server. 

While playing movies on TV App, there are DNS query for "**hls.itunes.apple.com**" which 
points to "hls.itunes.g.**aaplimg.com**" (another subdomain on "aaplimg.com" domain)

hls.itunes.apple.com -> hls.itunes.g.aaplimg.com -> 17.253.33.203


I verified the full domain **aaplimg.com** : it is registered by Apple Inc. 

__
My conclusion is that "**aaplimg.com**" domain (and all of it subdomains) can be a candidate for whitelist, and may be used for troubleshooting users with blank pages or content/images problems, by temporary whitelisting it and testing.

**Comment by iDjay** [comment]
iTunes Store works again with 2.1.1 beta :)
