### ISSUE TITLE
Add apple.com and mzstatic.com to HTTPS exclusions due to changes in iTunes and macOS Catalina

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#556]
Apple seems to be moving away from using itunes.apple.com for links, and redirecting links to new ones based on the type of media to match the new apps available in macOS Catalina.

As the new links are not included in HTTPS exclusions, Certificate errors appear as Apple does not like using the AdGuard certificate for those links (See #555 for what I saw in Safari 13.0).

Could these domains be added by default, these are what I see so far.

- **apps.apple.com** (Apps [macOS, iOS, tvOS])
- **music.apple.com** (Music, Apple Music, iTunes Music)
- **books.apple.com** (Books, Audiobooks)
- **podcasts.apple.com** (Podcasts)

At the moment, TV Shows and Movies still use the **itunes.apple.com** domain for now.

You can see all the links that Apple use via their tool: https://linkmaker.itunes.apple.com/en-us

Ideally, this would be done before the public stable release of macOS Catalina.

**Comment by ameshkov** [comment]
@Stillness-2 what do you think about simply adding the whole `apple.com` to the HTTPS exclusions?

**Comment by Stillness-2** [comment]
@ameshkov I think we can add whole domain

**Comment by gilby101** [comment]
Ideally this should be in the release version as soon as possible as it can effect all users of Apple apps, books, music, etc. whatever version of macOS is used - not just those with Catalina.

**Comment by planet0** [comment]
There should also be an exclusion for **mzstatic.com** to resolve Store content in apps like iTunes, Music, Books, etc. (Re: #552)
