### ISSUE TITLE
Crash of the application

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#557]
Hello, i have regular crashes of the application. My configuration:
- macOS 10.14.5 Mojave
- Safari 12.1.1
- Adguard for Mac 2.0.6

Filters:
Базовый фильтр + Фильтр счетчиков и аналитики + Фильтр виджетов социальных сетей + Фильтр раздражителей + Русский фильтр + Упрощенный фильтр доменов + Adblock Warning Removal List + Facebook annoyances blocker

Of course, i sent the reports of these errors many times, specifying my mailbox. There are no concrete steps for a reproduce of this error. But I suspect that there is a problem of incompatibility with a VPN-application from Windscribe (1.83 build 22). I prepared the logs from two last incidents:
- the first time was in 13/07/2019 23:59-14/07/2019 00:00 MSK. The log in the "normal" mode - adguard_logs_20190713090046.zip.
- the second time was 14/07/2019 15:21-15:22 MSK. The log in the "detailed" mode - adguard_logs_20190714122245.zip.

The both logs is attached. Please, take a look and try to fix it ASAP. Thank you.
`file links removed`

**Comment by Stillness-2** [comment]
@ammnt Можете позапускать и посмотреть как работает тестовая сборка?
https://uploads.adguard.com/up15_8EB82427-B94F-408A-A343-7BB5B5A192E8_AdGuard.app.zip

Как только закрашится, перезапустите и отправьте отчет с комментарием `issue-557`, а так же сформируйте zip с логами. отправить логи (или ссылку на них) можно на `dev<собака>adguard.com`

Если не работает VPN клиент, то AdGuard не крашится?

**Comment by Stillness-2** [comment]
@ammnt новая ссылка на тестовую сборку
https://uploads.adguard.com/up15_4E1967B2-1994-408B-A467-BB57BA915CAA_Adguard.app.zip

**Comment by ammnt** [comment]
@Stillness-2, этот крэш довольно сложно поймать, поэтому это займет время. Насчет VPN-клиента вообще не уверен, так как точно крашилось и без него раньше, но причина могла быть вообще иной.

**Comment by ameshkov** [comment]
@ammnt вообще в той версии что @Stillness-2 сбросил исправлено несколько популярных крашей, вполне может быть что и ваш уже исправлен.

**Comment by ammnt** [comment]
@Stillness-2 & @ameshkov, после почти трех дней тестирования могу сказать, что проблема не воспроизводится на этом билде. Надеюсь, что она устранена. С нетерпение жду стабильную версию 2.1. Спасибо!

**Comment by ammnt** [comment]
@Stillness-2 & @ameshkov, похоже мне всё же удалось поймать этот крэш ещё раз с детальным логированием. Отчет отправлен только что и продублирован в приложении:
[adguard_logs_20190731040659.zip](https://github.com/AdguardTeam/AdguardForMac/files/3452881/adguard_logs_20190731040659.zip)

Текущая конфигурация системы:
macOS 10.14.6 Mojave
Safari 12.1.2
Adguard for Mac 2.1.0.572 beta.

Конкретных шагов для воспроизведения нет. Пожалуйста, постарайтесь отловить этот баг и попытаться устранить к релизу. Спасибо.

P.S.: на dev(at)adguard.com письмо не ушло - сервер возвращает ошибку 554 5.1.1 Unknown user.

**Comment by ammnt** [comment]
@ameshkov & @Stillness-2, ещё раз сегодня в 18:21 МСК зафиксировал падение, по всей видимости, при открытии URL:
https://www.reg.ru/user/account/#/

Отчет о падении отправлен только что и продублирован в приложении:
[adguard_logs_20190801032233.zip](https://github.com/AdguardTeam/AdguardForMac/files/3457443/adguard_logs_20190801032233.zip)

**Comment by ameshkov** [comment]
@ammnt вчера новая найтли кстати вышла, по ней пока не вижу ничего похожего.

Утащил логи к нам nextcloud, стер в комментариях.

@sfionov ивенты в sentry:
* https://sentry.adguard.com/adg/adguard-mac/issues/16111/events/1082494/
* https://sentry.adguard.com/adg/adguard-mac/issues/27322/events/1094439/

**Comment by ammnt** [comment]
@ameshkov, есть подозрение, что проблема в совместимости с этим фильтром:
https://easylist-downloads.adblockplus.org/fb_annoyances_full.txt
Удалил его. Проверяю стабильность работы без него на этой nightly-версии и дальнейшую целесообразность его использования. Спасибо.

**Comment by ameshkov** [comment]
Да не, вряд ли в фильтрах дело, там ошибка где-то глубже зарыта

**Comment by ammnt** [comment]
@ameshkov & @Stillness-2, только что получил краш на последней nightly-версии 2.1.1.588. Репорт отправил с пометкой, логи в приложении:
[adguard_logs_20190809061439.zip](https://github.com/AdguardTeam/AdguardForMac/files/3484999/adguard_logs_20190809061439.zip)

**Comment by ammnt** [comment]
@ameshkov & @Stillness-2, ещё раз с уже выключенным пользовательским фильтром и удаленным facebook annoyances blocker фильтром. Логи в приложении:
[adguard_logs_20190809094922.zip](https://github.com/AdguardTeam/AdguardForMac/files/3488123/adguard_logs_20190809094922.zip)

**Comment by iDjay** [comment]
AdGuard 2.1.1 Beta randomly crashed for me, crash logs sent.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ammnt** [comment]
@ameshkov & @Stillness-2, ещё раз на последней beta-версии. Логи с пометкой "issue-557" отправлены пять минут назад. Прикрепить сюда не удается.

**Comment by ammnt** [comment]
@ameshkov & @Stillness-2, и ещё разок перед сном:
[adguard_logs_20190815090036.zip](https://github.com/AdguardTeam/AdguardForMac/files/3507166/adguard_logs_20190815090036.zip)

**Comment by ammnt** [comment]
@iDjay, can you please tell me if you're using anything else to further block the ads? Pi-Hole, Diversion, pixelserv-tls, pfBlockerNG, AdGuard Home or probably AdGuard DNS, Cloudflare DNS? And do you also probably use your own self-generated CA certificate? I suspect there is a conflict between AdGuard's CA certificate and pixelserv-tls CA certificate. Thank you.

@ameshkov & @Stillness-2, i'm trying to understand what difference between my configuration and configuration of most users of AdGuard for Mac...

**Comment by iDjay** [comment]
@ammnt nope, nothing. It just happens once a week

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ammnt** [comment]
@iDjay, you don't use antivirus, either?

**Comment by iDjay** [comment]
Nope, no antivirus 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ammnt** [comment]
@iDjay, please answer for three more questions:
1. Do you use any VPN clients like Windscribe or something like that?
2. Do you clean folders ~ / Library/Caches and / Library/Caches sometimes manually or by programs like CCleaner, Onix, CleanMyMac etc.?
3. Do you clean sometimes Safari cache with the CMD+Option+E keyboard shortcut?
Thank you.

**Comment by iDjay** [comment]
No.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ameshkov** [comment]
All logs are moved to the private nextcloud.

> @ameshkov & @Stillness-2, i'm trying to understand what difference between my configuration and configuration of most users of AdGuard for Mac...

Well, I think that a VPN might be the catalyst, but I doubt that it's the real reason. There must be something we're missing.

Meanwhile, I've opened a new issue in CoreLibs, let's continue there:
https://github.com/AdguardTeam/CoreLibs/issues/1086
