### ISSUE TITLE
Filter editor rework

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#56]
It will be nice to be able to sort alphabetically the user filters list. I have now a long list and it is not easy to mange anymore.

AMR-567-98185

**Comment by Stillness-2** [comment]
@evgeniy-ADG I don't understand. Does user want sort list of the rules in user filter?

**Comment by worldsdream** [comment]
Yes, I think that is what he means. It would be nice if we could sort the filters that we have added. For example:

English
Dutch
Spyware
Annoyance

I would have done that order myself.

**Comment by Bubu92** [comment]
What I mean was to sort the "User Filter" window.

The work around I found was to export the list. To open it in Excel, to sort it out, save it. Paste in a txt editor and then import it again. A complicated process IMHO.
![screen shot 2017-01-10 at 14 08 08](https://cloud.githubusercontent.com/assets/23118229/21807372/adf88e40-d73e-11e6-95a7-66c998e3d27c.jpg)

**Comment by ameshkov** [comment]
Actually, I suppose we should use the same approach as in Windows version:
https://github.com/AdguardTeam/AdguardForWindows/issues/1293#issuecomment-265460286

@Stillness-2 please take a look, it should be relatively easy to implement. We should only find a proper editor component.
