### ISSUE TITLE
Match AdGuardLoginHelper.app Icon to new main AdGuard.app Icon (AppIcon.icns)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#561]
As done in #450, I noticed AdGuardLoginHelper.app doesn't use the new icon and still uses the old one.

It's minor, but it would be good to see the new icon copied over to AdGuardLoginHelper.app as well.

**Comment by ameshkov** [comment]
Done in `mac/pull-requests/259`

**Comment by planet0** [comment]
Can see the change in 2.1.0.578 nightly. Thank you!
