### ISSUE TITLE
blocked_page.html is not showing, blank

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#562]
I noticed when AdGuard tries to load blocked_page.html, the output for <body> is simply blank.

error_page.html, parental.html and safebrowsing.html within FilterLibResources seem to load fine.

Is there a reason why I'm only seeing a blank white page for when blocked_page.html tries to display?

Viewing blocked_page.html manually does work, just not when AdGuard tries to show it for a blocked page.

**Comment by ameshkov** [comment]
The logic is to bypass this page when the request is opened in the browser's tab.

Only subrequests are strictly blocked at the moment (unless https://github.com/AdguardTeam/CoreLibs/issues/152 is implemented)
