### ISSUE TITLE
UI problems with the menu bar icon in MacOS Catalina

### ISSUE THREAD

**Issue by LucasDiTomase** [AdguardTeam/AdguardForMac#563]
I attach screenshots and video recording showing how the icon in the menu bar in the latest Nightly version is not showing up properly (at all) in light mode in MacOS Catalina

![Captura de Pantalla 2019-07-23 a la(s) 10 33 39](https://user-images.githubusercontent.com/46760897/61716459-b65b4580-ad4e-11e9-812d-17b060e587b8.png)
![Captura de Pantalla 2019-07-23 a la(s) 10 33 26](https://user-images.githubusercontent.com/46760897/61716461-b78c7280-ad4e-11e9-9921-7b5203860cd7.png)

Link to video: https://we.tl/t-StekwuKFFl

**Comment by zzebrum** [comment]
It's ok on my side with the same AG and Catalina versions.

**Comment by zzebrum** [comment]
Yeap, I was thinking this is somehow may be related to automatic mode, but my mac at that time was slow down by downloading an update which turned out was not update, lol. So I can reproduce it now.

@ameshkov is it a Catalina problem, or we can do something to fix it?

**Comment by planet0** [comment]
Same issue as #527?

**Comment by zzebrum** [comment]
Huh, yep! closed as a dup then.
