### ISSUE TITLE
[2.0.6] AdGuard not running when MacBook wakes up from sleep mode

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#567]
- put MacBook into sleep mode (close the lid)
- wake it up after a few minutes (open the lid)
- ADGuard SOMETIMES doesn‘t run in the background anymore or runs in the background but is not filtering anything.
-> restart AdGuard and everything’s fine again

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@iDjay can you collect logs, please?

**Comment by iDjay** [comment]
@zzebrum check: https://we.tl/t-6E17WGOoyy this time (10 minutes ago) it was just not doing anything, but still visible in my menu bar. There's no crash log available when it crashs, it just "disappears".

**Comment by iDjay** [comment]
oh it's a duplicate #540

**Comment by zzebrum** [comment]
got your logs, thanks. yep, it's a dup :)
