### ISSUE TITLE
AdGuard 2.10b inoperable after user logoff/login

### ISSUE THREAD

**Issue by tomads** [AdguardTeam/AdguardForMac#573]
### Steps to reproduce

1. logoff user
2. login again
3.
4.

### Expected behavior

Adguard should be active

### Actual behavior

Adguard is inactive and can't be activated.
Activation is only possible after restarting Adguard

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): macOS 10.14.6
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): LittleSnitch

**Comment by michael1900** [comment]
I tried and it seems work well, weird.

**Comment by iDjay** [comment]
Same issue as #540?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by tomads** [comment]
No.

No problem after sleep here ...

**Comment by zzebrum** [comment]
@tomads 

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject

**Comment by tomads** [comment]
Hi.

The issue is gone after installing new Adguard v2.1.1b.
SFT

Tom
