### ISSUE TITLE
Use custom adguard: scheme for adding userscripts

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#578]
@ameshkov commented on [Thu Jul 11 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2838)

1. Update CoreLibs to convert userscript links to use `adguard:` scheme
2. Intercept these links and offer to install a userscript
3. No more intercept `.user.js` on the network level

---

@optomux commented on [Fri Jul 12 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/2838#issuecomment-510957373)

What does this mean?

**Comment by adbuker** [comment]
Please note, that the new proxy-server conguration's property have appeared - `clickedLinksInterception` . It is responsible for allowing to intercept request to subscription, userscripts (a list can be extended further). See more in `core/pull-requests/1576`

**Comment by Stillness-2** [comment]
done in #636
