### ISSUE TITLE
Update installer icon to match the app

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#584]

**Comment by chernikova-yana** [comment]
Installer icons 
https://share.goabstract.com/fc2d6c54-e876-48e0-ae8d-3e6b609954e6?sha=0dc6b953869d97f4e5140c4b20ce556258868792

Installer icons Safari
https://share.goabstract.com/f0e5ab2f-fc76-4dcc-ae59-095fd0695855?sha=0dc6b953869d97f4e5140c4b20ce556258868792
