### ISSUE TITLE
Page rendering issues on macOS Catalina

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#585]
### Steps to reproduce
1. Install macOS Catalina
2. Try to open some sites like https://idnes.cz
3. First, AdGuard will force Safari to display a "Cannot open this page" error
4. Refreshing the page afterwards causes an incomplete page load

### Expected behavior
Shouldn't affect page rendering

### Actual behavior
Some pages are broken

<details><summary>Screenshot & logs:</summary>
Ticket 2286505
</details>

### Customer ID 
2286505

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Catalina (10.15 build 19A526h), AdGuard 2.0.6.559
* Any specific potentially conflicting software installed: none found

**Comment by ameshkov** [comment]
@akmLaVx I cannot reproduce this issue on AdGuard v2.1
