### ISSUE TITLE
speedtest.net: it takes time to start a test

### ISSUE THREAD

**Issue by sh2sg** [AdguardTeam/AdguardForMac#586]
### Steps to reproduce
1. go to https://www.speedtest.net/
2. click the big "Go" button
3. it starts preparing for the test with message "connecting..."

### Expected behavior
with AdGuard disabled, test starts in 2 seconds

### Actual behavior
with AdGuard enabled, it takes 15 seconds to start the test

### Your environment
- MacOS Mojave 10.14.6
- AdGuard 2.1.2.595
- Safari 12.1.2

**Comment by zzebrum** [comment]
No significant difference on my side. Is Stealth mode enabled?

**Comment by sh2sg** [comment]
> No significant difference on my side. Is Stealth mode enabled?

No.

**Comment by ameshkov** [comment]
Actually, I've been able to reproduce it in Safari

**Comment by ameshkov** [comment]
But only once 😢
