### ISSUE TITLE
Microsoft Edge Canary issue

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#589]
### Steps to reproduce

1. Download or Update to the latest version of [IE Canary](https://go.microsoft.com/fwlink/?linkid=2069147&clcid=0x409&Consent=1&IID=ce941349-10ba-5a96-960c-a1093bcf5e2d)
2. Add the app to Filtered apps
3. The application is not filtered 

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/64181438-1fb29600-ce6f-11e9-88d7-b1f6a435daf2.png)

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Version 78.0.262.0 (Official build) Canary (64-bit) | High Sierra 10.13.6

**Comment by smlombardi** [comment]
Is it worth me switching to the nightly build?  Does it work there?

**Comment by ameshkov** [comment]
@smlombardi not yet, but it will first appear there
