### ISSUE TITLE
Compatibility issues with Remotix

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#592]
### Steps to reproduce
1. Install & launch the latest Remotix beta
2. AG is causing the hub window of the new version 6 to throw a JavaScript error

### Expected behavior
Shouldn't cause any compatibility issues

### Actual behavior
AdGuard makes the app throw a JS exception

<details><summary>Screenshot:</summary>

<img width="1770" alt="Screen Shot 2019-09-05 at 8 26 27 AM" src="https://user-images.githubusercontent.com/33634917/64492875-bae9a800-d281-11e9-95fb-02ad2aa64c48.png">

</details>

### Customer ID & Logs
See helpdesk ID 551934.

### Your environment
* Environment name and version: (e.g. Chrome 59): Remotix 6.0 Beta, AdGuard 2.1.2.595
* Any specific potentially conflicting software installed: None

**Comment by TheJTizzle** [comment]
Any update on this?

**Comment by Stillness-2** [comment]
@TheJTizzle `AdGuard` identifies `Remotix` web view for login page as `Safari`, we will investigate why this happen. At this point you can try add `remotixcloud.com` domain in SSL Exceptions list. 
![image](https://user-images.githubusercontent.com/12689/66311977-67b65400-e918-11e9-9e9a-237955cf74a6.png)

**Comment by TheJTizzle** [comment]
Worked like a charm! Thanks so much!

JT

**Comment by akmLaVx** [comment]
Remotix developers have contacted us and requested to whitelist both `remotix.com` and `remotixcloud.com` on our end.
