### ISSUE TITLE
Websites/IP Addresses can't be whitelisted

### ISSUE THREAD

**Issue by sudoankit** [AdguardTeam/AdguardForMac#597]
I live inside a campus and we got a firewall ( Fortinet ) for which I need to login every 40 mins. AdGuard Mac is blocking the firewall authentication page. I tried adding the URL/IP address to the whitelist but it's not working as intended.

### Steps to reproduce

1. Go to Settings -> General -> Edit Whitelist
2. Add the Authentication IP Address 
3. Click Close
4. Open Edit Whitelist Again

### Expected behavior

It should allow the Auth page to load.

### Actual behavior

It's blocking the webpage even if it's in the whitelist. I have attached screenshots below to make it clear.

<details><summary>Screenshot:</summary>

<img width="429" alt="Screen Shot 2019-09-21 at 2 19 22 PM" src="https://user-images.githubusercontent.com/8577076/65370892-6419a080-dc7b-11e9-888c-3dccef2961b8.png">

<img width="434" alt="Screen Shot 2019-09-21 at 2 20 17 PM" src="https://user-images.githubusercontent.com/8577076/65370896-6b40ae80-dc7b-11e9-8446-ae7de04ed032.png">

After closing and opening it again:

<img width="432" alt="Screen Shot 2019-09-21 at 2 20 25 PM" src="https://user-images.githubusercontent.com/8577076/65370897-6f6ccc00-dc7b-11e9-930c-1f6bdec3fcf7.png">

</details>

### Customer ID 

I am using the beta key. 

### Your environment

* Environment name and version: MacOS Mojave 10.14.6, MacBookPro Early 2015 13"
* I use MalwareBytes (Free), Little Snitch but they didn't interfere or block the auth page. uBlock Origin too allowed it.

**Comment by Alex-302** [comment]
> AdGuard Mac is blocking the firewall authentication page

please make screenshot of this. Page can be broken by the filters, stealth mode or HTTPS filtering.

**Comment by sudoankit** [comment]
With AdGuard:
<img width="1280" alt="Screen Shot 2019-09-21 at 3 46 05 PM" src="https://user-images.githubusercontent.com/8577076/65371951-f2475400-dc86-11e9-8c68-65b26f944445.png">

Without: 
<img width="1280" alt="Screen Shot 2019-09-21 at 3 44 07 PM" src="https://user-images.githubusercontent.com/8577076/65371936-c1671f00-dc86-11e9-917c-e5cad2e48736.png">

**Comment by Alex-302** [comment]
Got it. Please try to add `192.168.173.1` to HTTPS exclusions.
Not sure if it a bug...
Please show SSL certificate details for both cases. How to do it(described for few browsers):
https://www.globalsign.com/en/blog/how-to-view-ssl-certificate-details/

**Comment by sudoankit** [comment]
I'm not sure if it is safe to share SSL certificates on a public discussion board. I guess I can share what is mentioned in this [answer](https://security.stackexchange.com/a/165028). Will that be alright?

**Comment by ameshkov** [comment]
Here's another option you can use: `@@192.168.173.1^$network`
This rule will completely disable filtering for the specified IP.

> Also unrelated to this question, AdGuard Mac is using ~300MB RAM, is this alright? Is AdGuard Mac made using Electron?

No, it's native. An Electron would've used a gigabyte at least:)

**Comment by sudoankit** [comment]
@ameshkov Yes, this works perfect! Thank you. I'm closing the issue now.
