### ISSUE TITLE
Higher Priority to User Filters

### ISSUE THREAD

**Issue by specter78** [AdguardTeam/AdguardForMac#598]
I want to block Facebook comments on this website --> http://www.commitstrip.com/en/2014/02/04/mes-collegues-mes-bugs-et-moi/

So I added this as user filter --> `||facebook.com^$domain=commitstrip.com`

However, Adguard social media filter unblocks Facebook comments. There is no option other than finding that filter and disabling it. But this then affects other sites too.

So User filters should get highest priority among all filters.

**Comment by TheHasagi** [comment]
@specter78 

Can't see the conflict between Social media filter and your rule. Also, there are no fields of facebook comments. Can you share a screenshot?

**Comment by specter78** [comment]
![webpage](https://user-images.githubusercontent.com/40606342/65422990-91a24d80-de25-11e9-9161-ed52ef64ae75.jpg) - webpage with facebook comments

<img width="1208" alt="Screenshot - log" src="https://user-images.githubusercontent.com/40606342/65423024-a8e13b00-de25-11e9-833d-537d0f023368.png"> - log showing comments being unblocked

**Comment by zzebrum** [comment]
@specter78 try this rule instead

`commitstrip.com##.fbCommentsBlock`

**Comment by specter78** [comment]
That works. But I think it only hides comments and not block them.

**Comment by specter78** [comment]
> @specter78 you can use `$important` modifier to block any whitelisted request:
> `||facebook.com^$domain=commitstrip.com,important`
> or just
> `||connect.facebook.net^$domain=commitstrip.com`

Thank you. That works perfectly.
