### ISSUE TITLE
Incorrect filtering of third-party request

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#6]
http://forum.adguard.com/showthread.php?7528

Third-party request was blocked by rule
```
||traq.li^$third-party
```
https://ci3.googleusercontent.com/proxy/xInq9zlHUkhfo-01ET8UE7ihcifdb-iu0DRyXY4ZJWpuctOjhKX7neci2D5g0KSCz4WyN1Lp5QrftN6Qu8U5S-rw-Jc9j0x2aK8EB7TJIMGh87SN83ODi23M8FHfcyFOexkSCf1qYHujR6U7SNHIzSZUaJQ=s0-d-e1-ft#http://api.traq.li/url/image?url=http://go.publisher-news.com/AVDNinRDp3bAwNgUCMPL&w=500&h=300

**Comment by ameshkov** [comment]
@Stillness-2 look at regexp we use for "||" symbol.

Now it's something like ```https:?//```
Should be ```^https://```

**Comment by Stillness-2** [comment]
Now it's:
@"^https?://([a-z0-9-_.]+\\.)?"

**Comment by ameshkov** [comment]
In current beta?

**Comment by Stillness-2** [comment]
I think in release version too

**Comment by ameshkov** [comment]
Ops, false alarm, it is for browser extension:)
