### ISSUE TITLE
No Assistant at icefilms.info

### ISSUE THREAD

**Issue by Bohdan-SUP** [AdguardTeam/AdguardForMac#60]
http://www.icefilms.info
![screen shot 2016-02-14 at 5 09 14 pm](https://cloud.githubusercontent.com/assets/14153331/13034724/af34e8d8-d345-11e5-90eb-78ca16e756c4.png)
NTU-239-51806

**Comment by Stillness-2** [comment]
@ameshkov In requests from site root no "Referer" header field

**Comment by ameshkov** [comment]
How is that possible?

**Comment by Stillness-2** [comment]
Header of the main HTML page on this site contains `<meta name="referrer" content="no-referrer"/>` directive, which prevents adding `Referer` header field in  HTTP requests, which sent from this page.

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta charset="ISO-8859-1"/>
<meta name="referrer" content="no-referrer"/>
```

**Comment by ameshkov** [comment]
Frankly I don't know what to do:)

What if we remove it with a rule like that?
```icefilms.info$$meta[name="referrer"]```

**Comment by vozersky** [comment]
Resolved
