### ISSUE TITLE
AdGuard blocking/preventing delivery of outgoing email

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#600]
The messages from hosted server IMAP accounts appear to be going out but they are never delivered.
Full disabling filters, stealth-mode, and extensions do not solve the problem.

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/65679185-45d9e900-e05d-11e9-9d2f-f2def4dd8aca.png)

</details>

### Customer ID 

2306648

### Your environment

* AdGuard version: 2.1.2.595 nightly
* Any specific potentially conflicting software installed: Bitdefender AV

### Additional INFO
Bunch of Log files in **NCloud**

**Comment by zzebrum** [comment]
@Chinaski1 what about disabling Bitdefender?
@Stillness-2 please, take a look

**Comment by Chinaski1** [comment]
@zzebrum 
Look at the screenshot pls, user try to different combinations.
AdguardON/BitdefenderOFF
Both off and etc.

**Comment by ameshkov** [comment]
@Chinaski1 I'd suggest adding a `$network` rule that excludes the IMAP server's IP address.

Smth like '@@1.1.1.1$network', you just need to figure out what the IP address is
