### ISSUE TITLE
NSPOSIXErrorDomain: 1

### ISSUE THREAD

**Issue by ao-ku** [AdguardTeam/AdguardForMac#602]
ADGUARD 2.1.2.595 (CL-1.4.138)
MACOS MOJAVE 10.14.6
SAFARI 12.1.2 (14607.3.9)

When trying to access some websites (mostly e-commerce) I get "The operation could not be completed. Operation not permitted" (NSPOSIXErrorDomain: 1). When Adguard disabled the website loads normally.
Thanks.

**Comment by zzebrum** [comment]
@ao-ku please, provide a couple of examples of websites.

**Comment by zzebrum** [comment]
reopen if needed.
