### ISSUE TITLE
Vivaldi browser doesn't offer to remember username and password on websites.

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#603]
### Steps to reproduce

1. Install the [Vivaldi](vivaldi.com) browser or completely clear browser cache.
2. For example, try to authorize on [vk.com](vk.com)
3. A popup window should offer to save your username and password.
4. This is not happening. Regardless of filter combinations, stealth mode and extension settings.

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/66045787-14fe2600-e52d-11e9-980d-01a24ed22991.png)
</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/49645813/66046808-352ee480-e52f-11e9-8196-ca9124a2244a.png)

</details>

### Customer ID 
[AdGuard Forum](https://forum.adguard.com/index.php?threads/%D0%92-%D0%B1%D1%80%D0%B0%D1%83%D0%B7%D0%B5%D1%80%D0%B5-vivaldi-%D0%BF%D1%80%D0%B5%D0%BF%D1%8F%D1%82%D1%81%D1%82%D0%B2%D1%83%D0%B5%D1%82-%D1%81%D0%BE%D1%85%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D1%8E-%D0%B8-%D0%B0%D0%B2%D1%82%D0%BE%D0%B7%D0%B0%D0%BF%D0%BE%D0%BB%D0%BD%D0%B5%D0%BD%D0%B8%D1%8E-%D0%BB%D0%BE%D0%B3%D0%B8%D0%BD%D0%BE%D0%B2-%D0%B8-%D0%BF%D0%B0%D1%80%D0%BE%D0%BB%D0%B5%D0%B9.34305/#post-189466)

**Comment by zzebrum** [comment]
can not reproduce anymore
