### ISSUE TITLE
AdGuard for Mac does not work on Safari 13

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#609]
# Steps to reproduce
1. Update Safari to version 13
2. AdGuard for Mac will no longer be able to work in this browser

### Expected behavior
AdGuard for Mac should be able to filter this browser

### Actual behavior
AdGuard for Mac becomes absolutely unable to filter this browser

### Customer ID & debug logs
2322481

### Your environment
* Environment name and version: (e.g. Chrome 59): AdGuard 2.1.2.595, macOS 10.13.6, Safari 13
* Any specific potentially conflicting software installed: None detected

**Comment by zzebrum** [comment]
It seems that user confusing AG form Mac and Safari extension
