### ISSUE TITLE
[Catalina] AdGuard Icon not visible

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#611]
AdGuard Icon is not visible in macOS Catalina.
Video attached.

[Bildschirmvideo aufnehmen 2019-10-08 um 10.12.08.mov.zip](https://github.com/AdguardTeam/AdguardForMac/files/3701384/Bildschirmvideo.aufnehmen.2019-10-08.um.10.12.08.mov.zip)

**Comment by zzebrum** [comment]
closed as a duplicate of #527
