### ISSUE TITLE
Userscript incompatibility

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#617]
### Steps to reproduce
1. Install userscript: https://raw.githubusercontent.com/solymosi/npu/master/npu.user.js
2. GM_getValue GM_setValue don't work.

### Expected behavior
Userscript should work well with AdGuard

### Actual behavior
Userscript doesn't work with AdGuard

<details><summary>Screenshot:</summary>

Not provided by user.

</details>

### Customer ID 
406307

### Your environment
* AdGuard version: 2.1.3.611 nightly
* Conflicting software: Not found

**Comment by zzebrum** [comment]
the script for specific university sites https://github.com/solymosi/npu
user asked for additional info and screenshots.

**Comment by ameshkov** [comment]
@zzebrum there's a CoreLibs issue about userscripts incompatibilities, please merge it there

**Comment by zzebrum** [comment]
the issue moved here: https://github.com/AdguardTeam/CoreLibs/issues/204
