### ISSUE TITLE
AdGuard does not filter Opera browser v. 64.0.3417.54

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#619]
The browser is added to the filtered apps list, no Turbo, no VPN, no other network monitoring apps and extensions. It's not filtered and the filtering log is empty.

![image](https://user-images.githubusercontent.com/15856304/66712721-a2513e00-eda9-11e9-8598-4b0b8b8c9ffa.png)

OS: 10.15 (19A583)
AdGuard: 2.1.3.611
Opera: 64.0.3417.54

**Comment by ameshkov** [comment]
We should publish a hotfix tomorrow

**Comment by ammnt** [comment]
@ameshkov, I have the exactly same issue with macOS 10.15, AdGuard 2.1.2.595 and Yandex.Browser 19.9.0.1768 - this will be also corrected, I hope? Thank you.

**Comment by Eugene-Savenko** [comment]
https://github.com/AdguardTeam/AdguardForMac/issues/612

**Comment by crestadellonda** [comment]
Thanks a lot ;)

**Comment by crestadellonda** [comment]
It Rocks again...Thanks so much!!

**Comment by XonicTWD** [comment]
Yes it does! Thank You!

🤟😎
