### ISSUE TITLE
Sometimes AdGuard interrupts file downloading

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#625]
macOS 10.15 Catalina/Safari 13.0.2/AdGuard for Mac 2.1.3

Sometimes AdGuard interrupts file downloading. The screenshot and detailed log is attached:
https://yadi.sk/i/8MW8399KaMSTug
This isn 't about network connectivity because there 's no problem if you turn application off.

Thank you.

**Comment by zzebrum** [comment]
Log file moved to ncloud.
@ammnt was the problem reproducible on AG v2.1.2 too?  And is it only in Safari?

**Comment by ammnt** [comment]
@zzebrum, yes the same issue was on 2.1.2 version. But I can't reproduce it with Chrome 77 and Firefox 69 (last stable versions). Thank you.

**Comment by ammnt** [comment]
@zzebrum, anything clear from the logs? Thank you.

**Comment by ameshkov** [comment]
@ammnt could you please check this with the current AG for Mac nightly version?

Here's the link:
https://agrd.io/mac_nigthly

**Comment by ammnt** [comment]
@ameshkov, sure. This version already have extended logging?

**Comment by ameshkov** [comment]
@ammnt no, but it brings improved HTTP/2 flow control, and I think that this might fix the issue.

**Comment by ammnt** [comment]
@ameshkov, works really better with the last nightly build. Nice work! I will wait for release. Thank you.

**Comment by zzebrum** [comment]
@ammnt please, reopen the issue if needed then.
