### ISSUE TITLE
Send 'filters=' in the query string while reporting if all filters are disabled

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForMac#627]
for now there is no such parameter as `filters` if all filters are disable

#### Expected behavior
`filters=` should be sent in the query string

**Comment by ameshkov** [comment]
@slavaleleka are you sure? Why do you need it?

**Comment by slavaleleka** [comment]
@ameshkov for now there are not many query-string parameters which is common for all AG products. and some of our products get rid of empty parameters via reporting the issue. 

so I thought sending `filters=` would be nice and useful (for example, for detection if reports tool got enough parameters for [showing the message that most of fields are auto-filled](https://github.com/AdguardTeam/ReportsWebApp/issues/222))
