### ISSUE TITLE
AdGuard reinstalls certificates upon each reboot

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#628]
### Steps to reproduce
1. Reboot the device (must have HTTPS protection enabled beforehand)
2. AdGuard cert will be reinstalled

### Expected behavior
AdGuard uses the same SSL certs until they are expired

### Actual behavior
AdGuard reinstalls SSL certs upon each reboots

### Customer ID 
2348539

### Your environment
* Environment name and version: AdGuard 2.1.2.595 release + unspecified iOS devices proxied through AdGuard
* Any specific potentially conflicting software installed: none found

### Logs & terminal output
[adguard terminal output.log](https://github.com/AdguardTeam/AdguardForMac/files/3748203/adguard.terminal.output.log)
[adguard_logs_20191019021753.zip](https://github.com/AdguardTeam/AdguardForMac/files/3748204/adguard_logs_20191019021753.zip)

**Comment by zzebrum** [comment]
reproduced.
the AdGuard Personal CA in Keychain Access is not changed after Mac reboot but filtering through proxy stopped on a mobile device.

**Comment by zzebrum** [comment]
will be fixed in https://github.com/AdguardTeam/CoreLibs/issues/1203

**Comment by TheHasagi** [comment]
@akmLaVx Ask a customer to update to the latest release version. This issue is no more relevant.
