### ISSUE TITLE
Add Finnish language 

### ISSUE THREAD

**Issue by TommiHynynen** [AdguardTeam/AdguardForMac#63]
Finnish translation has been completed.

**Comment by ameshkov** [comment]
@Stillness-2 could you please make a new build so @TommiHynynen could check it?

**Comment by Stillness-2** [comment]
@TommiHynynen: Check this: 
https://www.dropbox.com/s/ctig2ihmzqq8i94/Adguard.zip?dl=1

**Comment by TommiHynynen** [comment]
Thanks @Stillness-2 ! There were some odd translations here and there but everything should be fine now.

"Misc" section is also translated. That might be useful for Adguard for Mac.

I'll try to translate and proofread Adguard Browser extension and Adroid 6 in
the near future. 

Cheers!

**Comment by ameshkov** [comment]
Great, thank you!

**Comment by Stillness-2** [comment]
commit 25066
