### ISSUE TITLE
[Request] Better way to report websites

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#632]
I really don't like the current way to report websites. The only way to do it is to use "AdGuard Assistent" which is permanently in the bottom right corner and I think it is disturbing. 
For that reason, I disabled "AdGuard Assistent" which means I have to enable it, reload the page, then report the page and after submitting the issue, disable "AdGuard Assistent" again just to report an overseen cookie banner f.e.
I think we need a way better solution for this without the Assistent being permanently visible.

**Comment by iDjay** [comment]
@zzebrum which one? I use Safari but not AdGuard for Safari.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@iDjay got it. 
We are open for suggestions :)
we have a link to report tool on contact support window https://uploads.adguard.com/Support_2019-10-31_13-20-37.png - in the current implementation, it's just a link and no settings params are passing from the app to the reporting web-page.

**Comment by iDjay** [comment]
Is it possible to auto hide the „AdGuard Assistant“ Module on websites? F.e. Make it only visible when you move the cursor to the bottom right corner of Safari. Not sure if this is technically possible.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zzebrum** [comment]
@iDjay since you can change the size and position for different websites I don't think it would be very convenient.

**Comment by iDjay** [comment]
>@iDjay since you can change the size and position for different websites I don't think it would be very convenient. 

@zzebrum is there one option to save the settings for every website? That would be very convenient :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iDjay** [comment]
I‘m just blind.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
