### ISSUE TITLE
Assistant missing at fastcompany.com

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#633]
![image](https://user-images.githubusercontent.com/15856304/67664695-c481b900-f970-11e9-9665-9d09edd1efdd.png)

macOS: 10.15 (19A602)
AdGuard: 2.1.6.630
Assistant: 4.3.18
Safari 13.0.2 (15608.2.30.1.1), Chrome 77.0.3865.120

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdguardAssistant #314](https://github.com/AdguardTeam/AdguardAssistant/issues/314) via [**ZenHub**](https://www.zenhub.com/)
