### ISSUE TITLE
[2.2 Beta] Missing Translations (German)

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#638]
Almost every translation is missing here
<img width="642" alt="Bildschirmfoto 2019-11-07 um 16 43 45" src="https://user-images.githubusercontent.com/4127356/68403864-f1f31180-017d-11ea-8faa-f18f870b430b.png">

It's "Benutzerfilter" not "user rules"
<img width="1034" alt="Bildschirmfoto 2019-11-07 um 16 44 05" src="https://user-images.githubusercontent.com/4127356/68403899-059e7800-017e-11ea-8a3b-f813231fb855.png">

"Allgemein" not "Allgemeine"
<img width="709" alt="Bildschirmfoto 2019-11-07 um 16 44 24" src="https://user-images.githubusercontent.com/4127356/68403944-12bb6700-017e-11ea-9523-7f23a5b631c4.png">

"extensions" + Description not translated
<img width="665" alt="Bildschirmfoto 2019-11-07 um 16 44 40" src="https://user-images.githubusercontent.com/4127356/68404032-35e61680-017e-11ea-920b-ae87b090f087.png">

**Comment by aalpatkina** [comment]
The translations into German have been completed on Crowdin.

**Comment by iDjay** [comment]
you forgot to change "Allgemeine" to "Allgemein" here.
<img width="680" alt="Bildschirmfoto 2020-02-04 um 17 08 19" src="https://user-images.githubusercontent.com/4127356/73762865-f628ce00-4770-11ea-8af6-01ad7d71f89f.png">

**Comment by aalpatkina** [comment]
@iDjay sorry, fixed now :)
Thanks!
