### ISSUE TITLE
AdGuard broken in Safari 10.15.2 beta

### ISSUE THREAD

**Issue by neilio** [AdguardTeam/AdguardForMac#639]
### Steps to reproduce

1. Upgrade to the latest 10.15.2 developer preview or beta
2. Try to load a page in Safari that normally should have ads stripped out

### Expected behavior
Ads should not appear

### Actual behavior

Ads appear

<details><summary>Screenshot:</summary>

</details>

### Customer ID 
1589258

### Your environment
macOS 10.15.2 build 19C32e
Safari Version 13.0.4 (15608.4.4.1)
Adguard 2.2.0.643 nightly
Macbook Pro 13" 2019

**Comment by zzebrum** [comment]
@neilio hi! I'm on v10.15.2 Beta (19C32e) and Safari v13.0.4 (15608.4.4.1), AdGuard v 2.2.0.643n - everything workink as expected. 

Load the problematic site in New Private window and check its certificate please:  https://uploads.adguard.com/macOS_Catalina_10.15_2019-11-11_20-16-23.png

**Comment by neilio** [comment]
This is what I see.

https://d.pr/i/scnv1Z

**Comment by zzebrum** [comment]
@neilio then it should be ok. Check that recommended filters are enabled - at least Base, Tracking protection. Social media, annoyances, and language-specific filters are optional. Also, make sure that User Rules filter is empty https://uploads.adguard.com/AdGuard_Preferences_-_Filters_2019-11-11_20-34-10.png

**Comment by zzebrum** [comment]
@neilio any news on this?

**Comment by neilio** [comment]
I reinstalled from the latest nightly and things seem to be okay now. Thanks!
