### ISSUE TITLE
Adguard Blocking My Login To Banking Website

### ISSUE THREAD

**Issue by jputting** [AdguardTeam/AdguardForMac#646]
Adguard 2.1.3.600 for mac is currently blocking all my attempts to login into my banking website at https://www.anz.com.au/personal/

I click the log in link which takes me to another page to enter my login details https://www.anz.com/INETBANK/bankmain.asp?adobe_mc=MCMID%3D46391347343968571254407049070114815049%7CMCAID%3D2EE992D685158BD1-400008FA6295ACE7%7CMCORGID%3D67A216D751E567B20A490D4C%2540AdobeOrg%7CTS%3D1574119731

I always ensure my Customer Registration Number and password  details are 100%accurate.

However when I am using Adgaurd for mac I can no longer login to my account.

I get this error message "Secure Connection Failed" An error occurred during a connection to banking4.anz.com.

 "The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
 Please contact the website owners to inform them of this problem."

When Adguard for mac is deactivated I can login as usual.

I am using macOS Catalina 10.15.1 I am using Firefox 70.0.1 with the Adguard2.1.3.600 add-on installed using the Integration mode, the Firefox Adguard add-on has never blocked me from entering my banking website.

To try and resolve this myself I have done the following:

Disabled ALL Adguard Filters for blocking ads

In the "General Settings" I have  whitelisted the following anz.com, anz.com.au, banking3.anz.com, banking4.anz.com

Disabled Adguard "Stealth Mode" completely.

Disabled all Adguard Extensions

Disabled Phishing and Malware Protection

I tried disabling both HTTPS Filtering and Do Not Filter Websites with EV Certificates.

When both of the above are active I have:

In the Network Settings I have added HTTPS Filtering Exlusions for anz.com, anz.com.au, banking3.anz.com, banking4.anz.com

In the Do Not Filter Websites with EV  Certificates I added Exclusions for anz.com, anz.com.au, banking3.anz.com, banking4.anz.com

I am NOT using Adguard as a HTTP Proxy.

Th only thing which resolves my banking login issue is "Automatically Filter Applications" when this is not activated I can log into my banking website as usual.

However disabling "Automatically Filter Applications" renders Adguard for mac impotent and  it is then useless to me.

Please advise on what i can do to login to my banking website while using Adguard and it's full protection capabilities.

**Comment by zzebrum** [comment]
@jputting first of all, please, update the app to the latest [beta](https://github.com/AdguardTeam/AdguardForMac/releases/download/v2.2.3/AdGuard-2.2.3.beta.dmg) version - this is a Release candidate and it's working quite good.

Also, when did this situation start? After a browser update or AdGuard update or something else?

**Comment by jputting** [comment]
Hi,
I have fully uninstalled the previously installed stable release version of Adguard 2.1.3.600

I then downloaded and installed the BETA version .

But I am very dismayed to report that Adguard is still blocking me from entering my anz.com banking website.

I would like to have this issue resolved urgently as I need to do some basic banking monitor my financial investments.

**Comment by jputting** [comment]
This been going on for well over 48 hours an still it is not fixed.

Adguard are quite simply not upholding their advertised claim of MOST TECHNICAL ISSUES ARE DEALT WITH IN A 24 HOUR TIMEFRAME.

**Comment by Stillness-2** [comment]
@jputting 
I can not repeat your problem on my computer. However, I don’t have an account in this bank, so I can’t go further than entering a dummy login and password. In my case, I do not observe any connection errors at all pages, where the site allows me to navigate.
There are a few questions:
1. Is the error repeated in another browser (Safari or Chrome)?
2. Other sites work fine via the HTTPS protocol, as well as the site `https://www.anz.com.au/`, but the problem arise after logging into your account. Is this true?

**Comment by jputting** [comment]
I can not test this on other browsers as I truly hate both Chrome and Safari and have a loyal long term user of Firefox.

The problem is that with Aduard activated I can not gain any form of access to my bank accounts at all.

Adguard is blocking my access to my bank accounts completely.

I believe that you are unable to replicate this issue because you do not have an account with anz.com.au and simply do not have a valid account number and password.

Not having valid login details prevents you from proceeding to the stage after having your credentials verified and then blocks access to any banking accoun
t.

There is only one quite specific factor that I can assuredly pin this problem upon.

When I ENABLE the option "AUTOMATICALLY FILTER ALL APPPLICATIONS"
I am blocked from entering my banking website.

When I DISABLE the option "AUTOMATICALLY FILTER ALL APPLICATIONS"
I can enter my banking website and access my bank account with no problems.

I have tried disabing every filter and every possible Adguard option one at a time this is how I am absolutely certain this "AUTOMATICALLY FILTER ALL APPLICATIONS" is the culprit responsible for this serious issue.

However disabling "AUTOMATICALLY FILTER ALL APPLICATIONS" effectively cripples Adguards capabiities and it becomes useless to me.

**Comment by jputting** [comment]
Hi,

I have further information on this issue of Adguard blocking access to my banking website.

As previously mentioned adding the anz.com.au to the HTTPS Filtering Exclusions DID NOT FIX THIS ISSUE.

There is only one quite specific factor that I can assuredly pin this problem upon.

When I ENABLE the option "AUTOMATICALLY FILTER ALL APPPLICATIONS"
I am blocked from entering my banking website.

When I DISABLE the option "AUTOMATICALLY FILTER ALL APPLICATIONS"
I can enter my banking website and access my bank account with no problems.

I have tried disabing every filter and every possible Adguard option one at a time this is how I am absolutely certain this "AUTOMATICALLY FILTER ALL APPLICATIONS" is the culprit responsible for this serious issue.

However disabling "AUTOMATICALLY FILTER ALL APPLICATIONS" effectively cripples Adguards capabiities and it becomes useless to me.

This what needs to be investigated THIS IS THE ONE AND ONLY FACTOR WHICH CAUSES THIS ISSUE TO ARISE.

Many Thanks

jputting

________________________________

**Comment by jputting** [comment]
Adguards technical support is extremely poor and almost nonexistant.

This issue has been rated as a "CRITICAL ISSUE".

Over 5 days have elapsed since reporting this and still no technical fix for this.

Banking services are an essential and vitally important part of our lives and yet Adguard is extremely slow in responding and taking forever and ever to deal with this "CRITICAL ISSUE".

THIS IS SIMPLY NOT GOOD ENOUGH.

Offering apologies about late replies is not in any way helpful in getting this resolved.

How much longer are technical support people at Adguard going take before they finally get this resolved and I can once again access to my banking website?

**Comment by Chinaski1** [comment]
As we mentioned earlier, we are unable to reproduce the problem on our side. 
It would be great if we could agree on a remote session. I have been writing to you on the forum but my post has not been replied to yet.
You can answer here or in the PM on the forum.
Let's agree on a time and date when you feel comfortable?
 We will connect and try to solve the problem.

**Comment by planet0** [comment]
@Chinaski1 @Stillness-2 Just realised I have the same issue and reported it:

https://github.com/AdguardTeam/AdguardFilters/issues/45707
https://github.com/AdguardTeam/CoreLibs/issues/1216

**Comment by ameshkov** [comment]
@sfionov could it be the same issue as with digid.nl? We should push the updated CL version to nightly and see if i thelps

**Comment by planet0** [comment]
@sfionov as discussed in https://github.com/AdguardTeam/CoreLibs/issues/1216: Removing `anz.com`, `anz.com.au`, and `anz.co.nz` from the default HTTPS exclusion list works. @ameshkov mentions it is most likely related to the same issue
