### ISSUE TITLE
Menubar icon became semi-transparent

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#650]
### Steps to reproduce
1. Update to 2.2

### Actual behavior
AdGuard menu bar icon becomes semi-transparent

<details><summary>Screenshot:</summary>

<img width="147" alt="PastedGraphic-1" src="https://user-images.githubusercontent.com/33634917/69899919-93ccdf00-1375-11ea-9b9e-5d60f1abff09.png">

</details>

### Customer ID 
2068738

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Catalina
* Any specific potentially conflicting software installed: None

**Comment by akmLaVx** [comment]
User 2293069 has the same issue.

**Comment by zzebrum** [comment]
reproducible on old MacOS: 10.13, 10.12 with a custom color scheme for the menu bar
