### ISSUE TITLE
AdGuard is not functioning after pressing Ignore button while reseting settings

### ISSUE THREAD

**Issue by adgkart** [AdguardTeam/AdguardForMac#651]
### Preconditions
1. AdGuard installed and active
2. Firefox installed and open

### Steps to reproduce
1. Go to AdGuard -> Menu -> Advanced -> Reset Settings...
2. Notification appeared: "Reset AdGuard settings. Are you sure?"
3. Press Reset
4. Notification appeared: "AdGuard can't remove AdGuard CA certificate from Firefox!"
5. Press Ignore

### Expected behaviour
AdGuard ask us to reload application and after action will be approved AdGuard will be reloaded with default setting

### Actual behaviour
AdGuard stoped working only Quit option is available

**Comment by Stillness-2** [comment]
I will remove `Ignore` button from `Alerts of the Removing Certificate `
