### ISSUE TITLE
Next button unavailable during extension reinstallation

### ISSUE THREAD

**Issue by adgkart** [AdguardTeam/AdguardForMac#652]
### Steps to reproduce
1. Go to AdGuard -> Menu -> Preferences... -> Extensions
2. Choose any extension, press gear, press Reinstall
3. Extension installation window appeared
4. Press Back

### Expected behaviour
Next button enabled without any additional action

### Actual behaviour
Next button disabled and become enabled only if some action made in editor area

**Comment by Stillness-2** [comment]
fixed in #651
