### ISSUE TITLE
Hide previously selected filters while adding new ones by search 

### ISSUE THREAD

**Issue by slavaleleka** [AdguardTeam/AdguardForMac#655]
#### Steps to reproduce
1. Open window for adding new filters by search.
2. Select one or few of them.
3. Search some particular filter.
4. For some reason there are previously selected filters search results

[▶️ **Expected behavior**](https://uploads.adguard.com/Screencast_15-10_11-12-2019.mp4)

[ ▶️ **Actual behavior** ](https://uploads.adguard.com/slbdzd8l83qf8.mp4)

#### Your environment
* AdGuard 2.4.0.693
* macOS 10.15.1

**Comment by zzebrum** [comment]
@slavaleleka technically it's not a bug. we made it on purpose - to show what filters already chosen. 
we can wait for feedback from users :)

**Comment by zzebrum** [comment]
Well, since there are no complaints about that, I still think that it is a good implementation - after choosing items from a list user can observe all changes and apply them. Though we can hide checked items while searching.
