### ISSUE TITLE
Adguard for Mac - Beachball/Freezes when opening Safari

### ISSUE THREAD

**Issue by budista379** [AdguardTeam/AdguardForMac#657]
### Steps to reproduce

1. Open Safari 
2. Ads should be blocked
3. Adguard opens in background and there's a beachball and Adguard is frozen
4.

### Expected behavior

Adguard should open and work 
### Actual behavior

Adguard opens and freezes (beachball appears) when I open Safari

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

I am using latest Mac OS 10.15.2 with Adguard for Mac 1.5.4 and 4 filters turned on.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #303](https://github.com/AdguardTeam/AdGuardForSafari/issues/303) via [**ZenHub**](https://www.zenhub.com/)
