### ISSUE TITLE
Add HTTPS filtering step to the initial wizard

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#659]
@ameshkov commented on [Sat Dec 14 2019](https://github.com/AdguardTeam/AdguardForWindows/issues/3125)

We should add a step that allows configuring HTTPS filtering

Here's what should be configurable:
1. Enable or disable HTTPS filtering in general
2. Filtering of the websites with EV certificates
3. If the user opts to disable HTTPS filtering, we should enable AdGuard SDNS filter automatically

What's important is that we should not start protection until the initial wizard is completed.

**Comment by northis** [comment]
https://app.goabstract.com/projects/21f05c20-c733-11e8-a52a-07ba12563bc0/branches/fee1bdba-63d6-4bd0-8f39-571f13c321ba/commits/848e49b9c637d8c9efd4881ebe8d453f9b5c4fcf/files/62DEA713-3892-4591-879F-67912D3EA2D0/layers/718FA0C3-7021-45D1-9CEC-22A242268A15?mode=design
