### ISSUE TITLE
Filtering in Microsoft Edge Beta browser doesn't turn off when removing the browser from filtered applications

### ISSUE THREAD

**Issue by SoLenny** [AdguardTeam/AdguardForMac#663]
Steps to reproduce:

1.Open AdGuard settings.
2.Open Network tab.
3.Disable Microsoft Edge Beta in automatically filtered applications.
4.Open browser and check console on any site with ads.

Expected behaviour: Filtering disabled, ads aren't blocked.

Actual behaviour: The browser is still filtered.

**Comment by Stillness-2** [comment]
In the described scenario, the issue does not reproduced.
BUT if you use filtering the list of apps on that screen, and then if you make any changes to the filtered list, they are not applied and are not saved after the application is restarted!
