### ISSUE TITLE
BZGApps Unite-powered web apps are not filtered

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#665]
### Steps to reproduce
1. Install https://www.bzgapps.com/unite
2. Create a YouTube webapp
3. It won't be detected or filtered by AdGuard

<details><summary>Screenshot:</summary>

![2019-12-29_17-45-11](https://user-images.githubusercontent.com/33634917/71622910-b145d080-2be1-11ea-8b87-279cafd22a40.png)

</details>

### Customer ID 
1428745

### Your environment
macOS Catalina + BZGApps Unite 3

**Comment by valch85** [comment]
MacOS version 10.15.2 (19C57)
AdGuard version 2.3.2.710 release (CL-1.5.163)
Unite version 2.2.3

**Comment by Stillness-2** [comment]
@akmLaVx @valch85 Did you add this webapp into application filtration list (AdGuard Preferences -> Network Tab)?

**Comment by valch85** [comment]
Thx. It's seems working now.

**Comment by zzebrum** [comment]
reopen if needed.
