### ISSUE TITLE
Deezer app filtering issues

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#666]
### Steps to reproduce
1. Download Deezer (https://www.deezer.com/en/download) for macOS;
2. When protection is enabled, Deezer does not work correctly: it displays the user as offline, and it prevents the app from playing the next song in user's playlist once the current song has ended.

### Suggested solutions
**Disable HTTPS Filtering**: Resolves the issue, but the app starts playing audio ads.

### Actual behavior
When protection is enabled, Deezer does not work correctly: it displays the user as offline, and it prevents the app from playing the next song in user's playlist once the current song has ended.

<details><summary>Filtering log screenshot:</summary>

<img width="1097" alt="Schermata 2020-12-30 alle 18 24 18" src="https://user-images.githubusercontent.com/33634917/71674052-f3f2de80-2d82-11ea-9dfe-89fe2724ebef.png">

</details>

### Customer ID 
2148650

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS 10.12.6, AdGuard for Mac 2.4.2.712n, Deezer 4.18.11
* Any specific potentially conflicting software installed: Not reported

**Comment by giodeluigi** [comment]
Hi to all and thanks for opening this task.
I am here to help, feel free to tell me what can I do to be more useful.

**Comment by giodeluigi** [comment]
The "offline message error" only occured one time.
The persisting bug consist in tracks hanging at the very end and the music stops and so the playlist.
Music starts to play again by itself after some minutes and also the "back" and "fast forward" keys get un-responding.

**Comment by giodeluigi** [comment]
Neither disabling HTTPS nor removing Deezer from the filtered programs list helped because the app turned to work properly but I get tons of visual and especially audio ads between tracks.

**Comment by giodeluigi** [comment]
Any kind news, please?
Thank you

**Comment by akmLaVx** [comment]
The devs are on a small break due to winter holidays. Please give them a few days, and they will definitely get back to you.

Thank you for your patience.

**Comment by giodeluigi** [comment]
> The devs are on a small break due to winter holidays. Please give them a few days, and they will definitely get back to you.
> 
> Thank you for your patience.

<3

**Comment by zzebrum** [comment]
@giodeluigi you don't use Deezer paid subscription, right?

**Comment by giodeluigi** [comment]
Correct. Free version.
Never had ads on it previously.


Il gio 9 gen 2020, 10:41 zzebrum <notifications@github.com> ha scritto:

**Comment by zzebrum** [comment]
@giodeluigi was issue reproducible on previous versions of AdGuard\Deezer?

**Comment by giodeluigi** [comment]
Never had these issues before.

Il gio 9 gen 2020, 16:44 zzebrum <notifications@github.com> ha scritto:

**Comment by ameshkov** [comment]
> The persisting bug consist in tracks hanging at the very end and the music stops and so the playlist.
> Music starts to play again by itself after some minutes and also the "back" and "fast forward" keys get un-responding.

Isn't it the moment when the app tries to play the ad?

**Comment by giodeluigi** [comment]
> > The persisting bug consist in tracks hanging at the very end and the music stops and so the playlist.
> > Music starts to play again by itself after some minutes and also the "back" and "fast forward" keys get un-responding.
> 
> Isn't it the moment when the app tries to play the ad?

Most probably it is.
The hangs occur only if you play the full song.

**Comment by zzebrum** [comment]
yes, it may be filters problem. checking now.

**Comment by giodeluigi** [comment]
> yes, it may be filters problem. checking now.

Thank you mate!
Waiting for updates to test this again

**Comment by giodeluigi** [comment]
UP

**Comment by zzebrum** [comment]
"you seem to be offline" problem is reproducible even if all filters disabled. 

STR:
1.  log out from the profile, close the app or do a clean install
2. run the app

Expected behavior: login screen.

Actual behavior:  "you seem to be offline" message appears on the first screen. Also, there are no requests in the AG request log.

**Comment by zzebrum** [comment]
On the other hand, the is no problem if you have a paid subscription.

**Comment by giodeluigi** [comment]
For login, I often need to disable Adguard, then login OK but Deezer still hangs at the end of a song.
Never had these issues on Deezer free version and Adguard before so I believe the ads protection scheme has changed.

**Comment by giodeluigi** [comment]
[SELF SOLVED]
I made an Adguard reset, deleted all user filter (really a few indeed) and Deezer back to work correctly.
Neither visual nor audio ads and even login was ok.
Also the freeze problems at the end of the song seem to be gone.
I'll try it for some more days but everything appears to be fine.
Thanks to everyone participated to this thread or at least tried to give some help.

**Comment by zzebrum** [comment]
well, I can confirm that everything is working now. But we haven't changed a thing on our side neither Deezer app hasn't got an update past few days. 

@giodeluigi please, reopen if the problem appears again.

**Comment by giodeluigi** [comment]
> well, I can confirm that everything is working now. But we haven't changed a thing on our side neither Deezer app hasn't got an update past few days.
> 
> @giodeluigi please, reopen if the problem appears again.

zzebrum I think you miss my edit for 4 minutes! ;)
Issue is not solved yet.
How can I reopen this?
Thank you

**Comment by giodeluigi** [comment]
I believe this is definitely a filter issue because if I turn off any Adguard default filter and I put "Energized Blu" as a personal host filter, Deezer seems to run smooth again without hangs at the end of the tracks, unresponsive buttons or offline-login problem.

**Comment by ameshkov** [comment]
@giodeluigi could you please do the following:

open preferences -> network -> open the list of HTTPS filtering exclusions -> add `deezer.com` there. does it help?

**Comment by akmLaVx** [comment]
User reports that the issue still persists. Reopening.

**Comment by zzebrum** [comment]
disabling https filtering for the app seems to cause audio ads

**Comment by ameshkov** [comment]
@Stillness-2 could you pleas check?

**Comment by giodeluigi** [comment]
disabling general https filtering from the app seems to cause audio ads but Deezer seems not to reproduce audio ads if disabling https filtering for deezer.com only.
Still testing but yesterday afternoon no audio ads were reproduced within half an hour.
Atm these filters are enabled:
English base filter, Tracking protection filter, Social media filter, Annoyances filter, Adblock warning removal filter, Adguard simplified domains name filter, Easylist Italy.
Still testing.

**Comment by giodeluigi** [comment]
Thanks for reopening this.

**Comment by giodeluigi** [comment]
Hi to all,
keep testing on new Deezer 4.18.30 (4.18.30.45) version.

**Comment by giodeluigi** [comment]
Ads are currently gone so I think this can be safely close.
Thank you.
