### ISSUE TITLE
Spontaneous reboots 

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#668]
### Steps to reproduce
From time to time the system is accidental reboots. 
MAC hangs up for a second and reboots.
Safari/AdGuard/Kaspersky

###  Here's the report of the issue:
panic(cpu 2 caller 0xffffff8009f6208d): "tcp_lock: so=0xffffff807db3b9c8 NO
PCB! lr=0xffffff7f8fdf1fcf lrh= 0xffffff800a0f596b:0xffffff800a114685
0xffffff800a0e461d:0xffffff800a114685 0xffffff800a0f452d:0xffffff800a114685
0xffffff800a0f452d:0xffffff8009f4d8c2
\n"@/BuildRoot/Library/Caches/com.apple.xbs/Sources/xnu/xnu-6153.61.1/bsd/netinet/tcp_subr.c:3309
Backtrace (CPU 2), Frame : Return Address
0xffffff83b6f2ba30 : 0xffffff8009b3bb1b
0xffffff83b6f2ba80 : 0xffffff8009c733e5
0xffffff83b6f2bac0 : 0xffffff8009c64e5e
0xffffff83b6f2bb10 : 0xffffff8009ae2a40
0xffffff83b6f2bb30 : 0xffffff8009b3b207
0xffffff83b6f2bc30 : 0xffffff8009b3b5eb
0xffffff83b6f2bc80 : 0xffffff800a2d24f9
0xffffff83b6f2bcf0 : 0xffffff8009f6208d
0xffffff83b6f2bd20 : 0xffffff800a0e7558
0xffffff83b6f2bd40 : 0xffffff7f8fdf1fcf
0xffffff83b6f2bd90 : 0xffffff800a114522
0xffffff83b6f2bdc0 : 0xffffff800a0e47dd
0xffffff83b6f2bde0 : 0xffffff8009f63fd8
0xffffff83b6f2be50 : 0xffffff8009f63c43
0xffffff83b6f2be70 : 0xffffff8009f22471
0xffffff83b6f2bec0 : 0xffffff8009b7d765
0xffffff83b6f2bf40 : 0xffffff8009b7d291
0xffffff83b6f2bfa0 : 0xffffff8009ae213e
Kernel Extensions in backtrace:

com.adguard.nfext(27.0)[4AF16C66-CBFC-369B-8F0A-6FB96F1D536E]@0xffffff7f8fdf0000->0xffffff7f8fe1bfff

BSD process name corresponding to current thread: kernel_task

Mac OS version:
19C57

Kernel version:
Darwin Kernel Version 19.2.0: Sat Nov 9 03:47:04 PST 2019;
root:xnu-6153.61.1~20/RELEASE_X86_64
Kernel UUID: C3E7E405-C692-356B-88D3-C30041FD1E72
Kernel slide: 0x0000000009800000
Kernel text base: 0xffffff8009a00000
__HIB text base: 0xffffff8009900000
System model name: MacBookPro15,3 (Mac-1E7E29AD0135F9BC)
System shutdown begun: NO

System uptime in nanoseconds: 308850148538087
last loaded kext at 272119365738362: >!AXsanScheme 3 (addr
0xffffff7f8fdcb000, size 32768)
last unloaded kext at 272191171730163: >!AXsanScheme 3 (addr
0xffffff7f8fdcb000, size 32768)
loaded kexts:
com.adguard.nfext 27
com.parallels.kext.netbridge 15.1.2 47123
com.parallels.kext.hypervisor 15.1.2 47123
com.parallels.kext.vnic 15.1.2 47123
com.paragon-software.filesystems.ntfs 71.5.15
com.kaspersky.nke 2.4.7a10
com.kaspersky.kext.klif 3.6.15a14
@filesystems.smbfs 3.4

### Customer ID 

2275900

### Your environment

* Environment name and version: OS 10.15.2 (Build 19C57)/AG 2.3.2.710 release
* Any specific potentially conflicting software installed: Kaspersky AV

**Comment by Eugene-Savenko** [comment]
For more information on the KAV configuration, please check 2496506 in CRM.

**Comment by adgkart** [comment]
Cannot be reproduced so far
