### ISSUE TITLE
[Feature Request] UI tweaks to Assistant?

### ISSUE THREAD

**Issue by geoff-nixon** [AdguardTeam/AdguardForMac#673]
Hi Guys! I'm a big fan—for years I held out on buying your products, but it's really made my life so much easier. Between myself, family and friend we've probably purchased thirty-odd licenses.

Anyway:
I have one or two of UI-related feature requests (suggestions) regarding the Assistant which I thought I'd reach out in the chance you'd consider entertaining them.

I'm one of those who (while I understand why it needs to be this way) do miss my nondescript black and white toolbar item, and even in its "small" incarnation, find it distracting, particularly when working on design stuff. If I'm showing someone a mockup, something like this is a little distracting:
<img width="616" alt="Screen Shot 2020-01-21 at 8 39 45 AM" src="https://user-images.githubusercontent.com/3162811/72825363-be2b7200-3c2b-11ea-9cf7-e78caee2c78d.png">

So for some concrete examples of what I'd *love* to see:
1. An option under "Assistant Settings", instead of just size options: the ability to choose another color scheme, something like a low opacity gray?
2. Also, I'd really love it if there were an option (or default behavior) where the Assistant icon disappeared when the cursor stops moving (the way the mouse pointer does).
3. This one's less an aesthetic gripe, but I thought I'd throw it in anyway: 98% of the time, the only thing I use the Assistant for is to temporarily toggle it off and on again, and it can get a little irksome having to find the Assistant, have it come up, find the toggle, etc. I'd love it if, say, a double or triple click on the Assistant did this, and then maybe turned red while disabled, to remind me I have it off. Then same procedure in reverse.

Well, there's my $0.02. Thank you for making such a great product, and thank you entertaining my rambling suggestions. :)

**Comment by zzebrum** [comment]
@geoff-nixon hi there and thanks a lot!
We actually are going to replace it with a native Safari Assistant extension: #670
