### ISSUE TITLE
AdGuard does not preserve the Whitelist

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#674]
What you have added disappears as soon as you close the Whitelist editor

### Steps to reproduce

1. Go to AdGuard > gear > Preferences... > Edit Whitelist
2. Click on the + item and type in the domain
3. Close
4. Reopen

### Expected behavior

The domain is added to the list 

### Actual behavior

The Whitelist is empty

<details><summary>Screenshot:</summary>

https://imgur.com/a/IAjRQeP

</details>

### Customer ID 
1262024

### Your environment

* 2.3.2.710 release
* OS: Version 10.15.3 (Build 19D76)

**Comment by antonreshetov** [comment]
Why is it closed? The bug is still there.

**Comment by zzebrum** [comment]
@antonreshetov sorry, we closed the issue due to changes in our processes. It has been fixed in the latest nightly so far.

**Comment by antonreshetov** [comment]
When will this fix be available in the new version? It seems to me that it's been a long time since this problem was solved. And this is not an open source project.
