### ISSUE TITLE
Fast user switching might corrupt certificate database

### ISSUE THREAD

**Issue by nexttoyou** [AdguardTeam/AdguardForMac#675]
Problem:
It isn’t currently reproducible but already happened twice. After switching from one user account to another on the same machine (by using fast user switching) the cert database in _/Library/Application Support/com.adguard.mac.adguard/AdguardCore/CertCache/SSL/_ is suddenly corrupted and renders impossible to open any ssl connection except those that are excluded in AdGuard. Apparently both instances of AdGuard from both user accounts are writing at the same time to the same file.

Workaround:
Quitting AdGuard, replacing the files _cert.db_, _cert.db-shm_ and _cert.db-wal_ (all of them situated in _/Library/Application Support/com.adguard.mac.adguard/AdguardCore/CertCache/SSL/_) from a backup and restarting AdGuard again resolves the expected functionality.

Environment:
iMac (Retina 5K, 27-inch, 2017) on macOS Mojave (10.14.6, build 18G3020), 40 GB RAM.

**Comment by zzebrum** [comment]
@nexttoyou can you check your permissions for all files in the directory, please?
`ls -la "/Library/Application Support/com.adguard.mac.adguard/AdguardCore/CertCache/SSL/"`

**Comment by nexttoyou** [comment]
Sure:
```
# ls -la "/Library/Application Support/com.adguard.mac.adguard/AdguardCore/CertCache/SSL/"
drwxrwxrwx  7 you     admin      224  3 Feb 18:00 .
drwxrwxrwx  4 root    admin      128  2 Feb 17:46 ..
-rw-r--r--@ 1 me      admin     6148 17 Jan 18:36 .DS_Store
-rw-r--r--  1 you     admin      812 21 Nov 17:44 Adguard Personal CA.cer
-rw-rw-rw-  1 you     admin  1675264  3 Feb 15:59 cert.db
-rw-rw-rw-  1 me      admin    32768  3 Feb 18:00 cert.db-shm
-rw-rw-rw-  1 me      admin   848752  3 Feb 20:04 cert.db-wal

```
**Addendum**: "me" is myself while "you" is the other user. Both are admins. This is _after_ I replaced the files in question of course. Besides this I have never touched the directory before the problem appeared.

**Comment by zzebrum** [comment]
@nexttoyou thanks! everything is ok here. 
Anyway, we will change the approach a little bit to avoid such situations.
