### ISSUE TITLE
Any plans to add AdGuard Home and the soon to be released AdGuard VPN to AdGuard for Mac?

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [AdguardTeam/AdguardForMac#677]
FEATURE REQUEST:

Any plans to add AdGuard Home and the soon to be released AdGuard VPN to AdGuard for Mac?

I would love to have every AdGuard program in one product

- Ad / tracker blocker
- DNS protection 
- VPN

Also, this would make the setup for AdGuard Home easier

Thanks

**Comment by adgkart** [comment]
We defenetly have plans to integrate AdGuard VPN, but for AdGuard Home no plans so far
