### ISSUE TITLE
Just received this notification from Apple on my Mac

### ISSUE THREAD

**Issue by Lucas-Di-Tomase** [AdguardTeam/AdguardForMac#680]
I just updated to the most recent beta version of macOS. I currently have the latest version of AdGuard Nightly. The popup says that the AdGuard extension is old and won't work on a newer macOS release. Are you aware of this?

![Captura de Pantalla 2020-02-21 a la(s) 17 57 27](https://user-images.githubusercontent.com/57176665/75071244-bf261c80-54d3-11ea-8f31-6687be8bd0cf.png)

![Captura de Pantalla 2020-02-21 a la(s) 17 56 34](https://user-images.githubusercontent.com/57176665/75071265-c4836700-54d3-11ea-9fd3-7438a6d65129.png)

**Comment by zzebrum** [comment]
@Lucas-Di-Tomase  yes, we aware of the situation! Nothing to worry about. We will change the approach.
Thank you for your attention!
