### ISSUE TITLE
Set a user rule to UNHIDE user-agent for a spefic app?

### ISSUE THREAD

**Issue by Jason4V** [AdguardTeam/AdguardForMac#681]
As mention above, recently I found one of my mac apps won't display comments because enable "hide you user-agent" feature in Stealth Mode. So, is there any way to set a user rule to unhide user-agent for a spefic app? 

Thanks! @zzebrum @ameshkov

**Comment by slavaleleka** [comment]
@Jason4V could you please report about this issue via AdGuard Assistant? we need to know what app is broken and how + all AdGuard settings (which will be automatically transferred to report tool by Assistant)

**Comment by Jason4V** [comment]
@slavaleleka it's [this app](https://apps.apple.com/us/app/wechat/id836500024?mt=12) and there is no  AdGuard Assistant button there like web brower. 

May I have your favor to know "how to unhide user-agent via user rule" first? Thank you :)

**Comment by ameshkov** [comment]
You can do something like this:
`@@||example.org^$stealth,app=binary_name`

This way you'll disable stealth mode for a particular app

**Comment by Jason4V** [comment]
I solved this problem with method that disabling "Hide-User Agent" feature. So, any way to disable this feature for a particular app?

**Comment by ameshkov** [comment]
Just like I said, you should specify the app binary (or bundle ID) and the URL where you want to disable stealth mode features, for instance:
`@@||example.org^$stealth,app=com.google.Chrome`

You can completely disable stealth mode for a particular app with a rule like this:
`@@http*^$stealth,app=com.google.Chrome`

**Comment by Jason4V** [comment]
Thanks @ameshkov. However I just wanna disable "Hide user agent" not Stealth mode for a particular app. Is there a way?

**Comment by slavaleleka** [comment]
@Jason4V no, there is no way to disable Stealth options selectively

**Comment by Jason4V** [comment]
@slavaleleka Thank you. Wish it will be implemented in future
