### ISSUE TITLE
AdGuard crashes on macOS 10.9

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#682]
### Steps to reproduce
1. Must run macOS 10.9. Not tested on older releases
2. Attempt to run or install AdGuard
3. Either AdGuard or its installer will crash

### Actual behavior
Crash upon launch.

<details><summary>Crash reports:</summary>

[report.docx](https://github.com/AdguardTeam/AdguardForMac/files/4246353/report.docx)
[Adguard crash report (1).pdf](https://github.com/AdguardTeam/AdguardForMac/files/4246359/Adguard.crash.report.1.pdf)

</details>

### Customer ID 
2554475, also 2564544 and 2555526

### Your environment
* Environment name and version: (e.g. Chrome 59): AdGuard 1.4.1 on macOS 10.9.5

**Comment by zzebrum** [comment]
fixed already
