### ISSUE TITLE
Allow user to turn off js script redirect

### ISSUE THREAD

**Issue by Chandler-Lu** [AdguardTeam/AdguardForMac#686]
Now, all js script url, like `https://example.com/file.js` will be redirect to `adguard:userscript?location=https://example.com/file.js`, it's inconvenient.

When I want to read a [code](https://github.com/burlesco/userscript/tree/master/src), Adguard will pop up.
![截屏2020-03-0419 42 17](https://user-images.githubusercontent.com/18322610/75876250-436f8c80-5e50-11ea-944a-8fc87572e1e4.png)

**Comment by Stillness-2** [comment]
@Chandler-Lu try this:

1. in terminal run command: 
`defaults write com.adguard.mac.adguard UserscriptSubscriptionLinkEnabled false`
1. disable/enable AdGuard
1. reload https://github.com/burlesco/userscript/tree/master/src page


for returning to default: 
`defaults write com.adguard.mac.adguard UserscriptSubscriptionLinkEnabled true`

**Comment by Chandler-Lu** [comment]
> @Chandler-Lu try this:
> 
> 1. in terminal run command:
>    `defaults write com.adguard.mac.adguard UserscriptSubscriptionLinkEnabled false`
> 2. disable/enable AdGuard
> 3. reload https://github.com/burlesco/userscript/tree/master/src page
> 
> for returning to default:
> `defaults write com.adguard.mac.adguard UserscriptSubscriptionLinkEnabled true`

Thanks! It's solved!
