### ISSUE TITLE
Support for Extension Storage (stats.storage_checked_on)

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#687]
Some userscripts are displaying an error regarding storage support not being present with AdGuard for Mac. These do work with extensions such as Tampermonkey, for example.

**stats.storage_checked_on doesn't exist**

### Steps to reproduce

1. Install Social Fixer via ([link](https://socialfixer.com/socialfixer.user.js))
2. Add to AdGuard
3. Go to Facebook

### Expected behavior

Extension will work

### Actual behavior

Error warns regarding Extension Storage support. Extension will not function and lose changes upon refresh

<details><summary>Screenshot:</summary>

<img width="329" alt="Screen Shot 2020-03-10 at 12 37 38 pm" src="https://user-images.githubusercontent.com/46271764/76271647-4560a200-62cd-11ea-912e-8a6eb1a3dd7d.png">

<img width="329" alt="Screen Shot 2020-03-10 at 12 41 12 pm" src="https://user-images.githubusercontent.com/46271764/76271389-79879300-62cc-11ea-9328-3e23db3ead62.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Safari Version 13.0.5 (15608.5.11), Chrome Version 80.0.3987.132 (Official Build) (64-bit)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) No

**Comment by adgkart** [comment]
Issue moved to [AdguardTeam/CoreLibs #1278](https://github.com/AdguardTeam/CoreLibs/issues/1278) via [**ZenHub**](https://www.zenhub.com/)
