### ISSUE TITLE
AdGuard doesn't work in Brave Beta 1.7.64

### ISSUE THREAD

**Issue by sophisticated-zero** [AdguardTeam/AdguardForMac#689]
It works in a regular version but doesn't work in Beta. 

<details><summary>Screenshot of the regular version:</summary>

![Screenshot 2020-03-19 09 08 32](https://user-images.githubusercontent.com/39196837/77041115-f77d2580-69c1-11ea-9be3-93ba01188c9b.png)

</details>

<details><summary>Screenshot of the Beta version:</summary>

![Screenshot 2020-03-19 09 09 25](https://user-images.githubusercontent.com/39196837/77041156-095ec880-69c2-11ea-8893-82f94ab1981d.png)

</details>

### Customer ID 
Support Case #2604754

**Comment by Stillness-2** [comment]
@sophisticated-zero Did user try add beta browser for filtering manually, in AdGuard Settings?
