### ISSUE TITLE
HTTPS Everywhere support.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#690]
Request HTTPS Everywhere support like this:
https://chrome.google.com/webstore/detail/https-everywhere/gcbommkclmclpchllfjekcdonpmejbdp?hl=zh-TW

https://github.com/AdguardTeam/AdguardForAndroid/issues/3381#issuecomment-602220270

**Comment by sfionov** [comment]
https://github.com/AdguardTeam/CoreLibs/issues/1284
