### ISSUE TITLE
The advanced configurations for "Use AG as HTTP proxy".

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#691]
1. Usually we can set login name and password for a proxy server.
No login name and password required for "Use AG as HTTP proxy" now?
This is a feature request.
May you add the optional login configuration?
ex:
- anonymous login
- login name and password required

2. Access logging and online access monitoring for recording the clients' Internet access activities.

3. Allow or ban user clients.

Thanks.

**Comment by zzebrum** [comment]
close as dup of https://github.com/AdguardTeam/CoreLibs/issues/1210

**Comment by lancelot-moon** [comment]
@zzebrum 
Is that for outbound proxy or local proxy?
Mine is for local proxy.
That only contains my point 1, not my point 2 and 3.
