### ISSUE TITLE
[German] Missing warning when enabling "Drittanbieter-Autorisierungsheader blockieren"

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#694]
Not sure if it's a localization issue or generally missing in AdGuard for Mac but there's no warning when enabling this feature like on Windows:
https://github.com/AdguardTeam/AdguardFilters/issues/52135#issuecomment-610873737

Also match the description because it's very inaccurate on Mac.

**Comment by zzebrum** [comment]
@iDjay such warning red messages were not in the design AG for Mac, but we could definitely change the description, yeah.

**Comment by iDjay** [comment]
*push*

**Comment by IaroslavKhvorostenko** [comment]
Hello. 
Thank you for taking the time to share your idea. We genuinely appreciate feedback from our community, and every suggestion is carefully reviewed. However, after consideration, we have decided not to proceed with this idea as it doesn't align with our current product vision.
