### ISSUE TITLE
Apple News ads

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#696]
### Steps to reproduce
1. Try to browse Apple News app
2. Ads!

### Expected behavior
AdGuard should block ads in Apple News

### Actual behavior
AdGuard does not block ads in Apple News

<details><summary>Screenshot:</summary>

<img width="1770" alt="applenews" src="https://user-images.githubusercontent.com/33634917/79754626-80b8ac80-8320-11ea-9bc1-c1df83c42f09.png">

</details>

### Customer ID & logs
2646039

### Your environment
* Environment name and version: (e.g. Chrome 59): AdGuard 2.3.2.710, macOS 10.15.4
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) None

**Comment by planet0** [comment]
@akmLaVx Have you tried adding the News app into the list of filtered Applications?

**Comment by akmLaVx** [comment]
Fixed by adding ||advp.apple.com^$ to User filter.
