### ISSUE TITLE
Integrate AdGuard VPN to AdGuard for Mac/Win for system wild usage

### ISSUE THREAD

**Issue by Jason4V** [AdguardTeam/AdguardForMac#697]
As mention above, will you have any plan or roadmap for Integrating AdGuard VPN to AdGuard for Mac/Win for system wild usage? Because AG VPN is great chrome extension!   @zzebrum @ameshkov 

Thanks!
- from royal paid pro user

**Comment by zzebrum** [comment]
@Jason4V first step - standalone applications for Mac and Windows. But it is too early to talk about specific dates.

**Comment by Jason4V** [comment]
@zzebrum Thanks! Looking fwd to it!
