### ISSUE TITLE
Ads not blocked in Skype desktop application

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdguardForMac#699]
### Steps to reproduce

1. Launch Skype
2. Observe annoying ads at the bottom of the contacts list

### Expected behavior

Adguard should block these ads

### Actual behavior

The ads appear

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

Unable to locate

### Your environment

* Skype version 8.59.0.77
* macOS Catalina 10.15.4
* Adguard version 2.4.7.777 nightly (CL-1.5.249)

**Comment by zzebrum** [comment]
@sysfu is the app added to automatically filter applications list in AdGuard settings?

**Comment by sysfu** [comment]
The application was not added automatically. I have added Skype to the list and I don't see any ads so far.
