### ISSUE TITLE
[Feature request] - add fanboy-ultimate filter

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#70]
The customer wants to have a subscription for 

https://www.fanboy.co.nz/r/fanboy-ultimate.txt

Can we add it to the list?

<details>
There is NO WAY for me to add a custom filter address, so there's NO WAY for it to be updated.

I can enter the RULES for the filter I want, but they are NOT going to update without an address to update from.

If I'm missing something then tell me HOW to achieve my goal, and stop sending ambiguous replies with no instructions.

HOW DO I ADD THIS FILTER ADDRESS TO MY USER FILTER?

https://www.fanboy.co.nz/r/fanboy-ultimate.txt

And I'll say it AGAIN - that filter SHOULD be included in Adguard!
You already have several of fanboy's filters included, but not the BEST one that does the job of several others.
</details>

GNC-702-51188

**Comment by ameshkov** [comment]
This filter is literally the same as these three filters:
EasyList + EasyPrivacy +  Fanboys Annoyances
