### ISSUE TITLE
Intercom live chat support widget blocked by Adguard

### ISSUE THREAD

**Issue by sysfu** [AdguardTeam/AdguardForMac#703]
### Steps to reproduce

1. Visit web site using Intercom live chat support
2. Observe that it's being blocked by Adguard.
3. Disable Adguard for website using Adguard assistant
4. Observe Intercom live chat support widget appear

### Expected behavior

Adguard should not block a legit support service on the website

### Actual behavior

Adguard blocks it

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: Adguard version 2.4.71.791 nightly (CL-1.5.269) Safari Version 13.1 (15609.1.20.111.8) macOS Catalina 10.15.4
* Any specific potentially conflicting software installed:

**Comment by adgkart** [comment]
Hi!

To solve this issue, can I ask you to try incognito mode in your browser? Also could you please tell me what filters do you use? Possibly deactivating one of them will indicate the cause of the problem.

Thx

**Comment by sysfu** [comment]
Incognito mode does not resolve. 

Filters in use

- Base
- Tracking protection
- Social Media
- Annoyances
- unblock search ads and self-promo
- Experimental

See if you can duplicate the issue on these two web sites:

https://www.sendwyre.com/
https://www.jollyhq.com/

I will try to gather the filtering logs and post in another comment.

**Comment by vozersky** [comment]
Hi. You are using Annoyances filter which blocks irritating elements on web pages including cookie notices, third-party widgets and in-page pop-ups. There is a rule for blocking intercom widget in it. You can find and disable that rule if you want, just find the Annoyances filter on the Filters tab of the settings and type "Intercom" in the search field.
