### ISSUE TITLE
AdGuars stops working after a few hours of work

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#707]
### Steps to reproduce
1. Start the app
2. Within a few hours, AdGuard will stop filtering anything
3. Restarting the app seems to help

### Expected behavior
App shouldn't shut itself down after a few hours of work.

### Actual behavior
AdGuard shuts down for little, if any, reason.

### Customer ID & Debug Logs
2699519

### Your environment
* Environment name and version: (e.g. Chrome 59): AdGuard 2.4.8.975n, macOS 10.14.6, French locale
* Any specific potentially conflicting software installed: None reported

**Comment by zzebrum** [comment]
close as dup of #540 
waiting for new log files from the user.
