### ISSUE TITLE
Jitsi Meet crashes soon after starting call

### ISSUE THREAD

**Issue by vit9696** [AdguardTeam/AdguardForMac#709]
### Steps to reproduce

1. Create a new room at https://meet.jit.si.
2. Wait for a short while.

### Expected behavior
1. Should work properly and let people communicate.

### Actual behavior
1. The thing will crash shortly signalising about something going wrong.

<details><summary>Screenshot:</summary>

<img width="1185" alt="Снимок экрана 2020-06-08 в 14 40 01" src="https://user-images.githubusercontent.com/4348897/84026433-fee71600-a995-11ea-9214-37cc8e4c0bce.png">

</details>

### Your environment
* macOS 10.15.5 with builtin Safari and Chromium from [here](https://github.com/macchrome/macstable/releases/download/v83.0.4103.97-r756066-Ungoogled-macOS/Chromium.app.ungoogled-83.0.4103.97.zip).

**Comment by zzebrum** [comment]
@vit9696 hello!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject

**Comment by vit9696** [comment]
@zzebrum could try to find some time to do that (it is uneasy due to other connections and the need to review the logs for sensitive data prior to sending), cannot you reproduce the issue on your end?

**Comment by vit9696** [comment]
I explored in more details on what exactly happens, and it seems that the actual issue is caused by adding meet.jit.si to TLS exceptions. I did that some time ago to be able to use Jitsi with Adguard.

When I remove the website from the exception list the stops reloading but I get no sound at all and screen sharing button also disappears (see the images below). I mailed you the logs with this case, if you need another case with meet.jit.si crashing, I could make that too, but I guess addressing the primary issue is more important.

<img width="339" alt="Снимок экрана 2020-06-10 в 10 00 08" src="https://user-images.githubusercontent.com/4348897/84237188-92892580-ab01-11ea-8d26-5aa825d9b9c8.png"> <img width="302" alt="Снимок экрана 2020-06-10 в 10 00 19" src="https://user-images.githubusercontent.com/4348897/84237183-90bf6200-ab01-11ea-8cd6-5f042b65b655.png">

**Comment by zzebrum** [comment]
@vit9696 most probably `block WebRTC` is the trick, try to disable it in Stealth mode settings.

**Comment by vit9696** [comment]
Yes, that seems to do the trick. Thanks!
