### ISSUE TITLE
Safari hangs with random pages after updating to macOS v.10.15.5

### ISSUE THREAD

**Issue by facilisdes** [AdguardTeam/AdguardForMac#710]
### Steps to reproduce
Unfortunately I can't see any pattern here. Some sites that worked yesterday are hanging today, and some that were hanging yesterday works fine today.

### Expected behavior
Every website work normally.

### Actual behavior
Random websites, when opened in Safari, load partially and then stuck being unresponsive. I can scroll page but there's no content beside that was in initial viewport. Such page would load until tab crashes. Issue resolves when i quit AdGuard app and reload page, but this only fixes problem for some time. After awhile issue repeats and then solution is to open AdGuard app again. Temporal solution which work for some sites and doesn't work for others is to empty browser caches.

### Customer ID 
2726348

### Your environment
OS: macOS 10.15.5
AdGuard version: 2.4.8.797 
Related browser: Safari 13.1.1
I don't use any antivirus, traffic counter or cleaner. I use Little Snitch as a firewall but disabling or reenabling it doesn't seem to affect the issue.

**Comment by zzebrum** [comment]
@facilisdes any new?

**Comment by facilisdes** [comment]
@zzebrum sorry for the wait, email support advised me to update to nightly build and also I fully reset filters and settings and after that issue seemed to disappear. However yesterday I found a single page with the same problem. 
So a couple of minutes ago I collected logs and sent it as you requested.
