### ISSUE TITLE
ads-blocker.com

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#711]
@adguard-bot commented on [Fri May 29 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412)

### Issue URL (Ads)
 [https://ads-blocker.com/testing/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fads-blocker.com%2Ftesting%2F)
### Comment
Username: @shenlihartono
> Adguard works in my Android app, the ads are blocked all of them
> 
> but on IOS & MAC OS, it cannot seem to block any ads at all
> 
> When I use third party app (ublock origin) it can block ads
> 
> please try it with this site: https://ads-blocker.com/testing/

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/Fhjwv06.png)
</details>

### System configuration

Information | value
--- | ---
Platform: | Mac
AdGuard version: | 2.4.8.797 release
Browser: | Chrome
Stealth mode options: | Hide your search queries, Send Do-Not-Track header, Remove X-Client-Data header from HTTP requests, Strip URLs from tracking parameters, Block third-party Authorization header, Self-destructing first-party cookies (), Self-destructing third-party cookies (), Disable cache for third-party requests, Block Push API, Block Location API, Block Flash, Block Java, Hide your Referrer from third-parties (), Hide your User-Agent (), Hide your IP address ()
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion
Other extensions used: | uBlock Origin

---

@Alex-302 commented on [Wed Jun 03 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-638176269)

@shenlihartono Hi. Do you have antivirus or another network filtering app?

---

@shenlihartono commented on [Sun Jun 07 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-640221637)

@Alex-302 Hi Alex

I use Mac os I dont have any antivirus, and I also do not use network filtering app

---

@Alex-302 commented on [Tue Jun 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-641116973)

@shenlihartono Weird. Do you see ads on this site only, or at all?

---

@Eugene-Savenko commented on [Tue Jun 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-641122149)

@shenlihartono Hi! There's a widget in the menu bar that shows the network speed. Could you disable the app that controls it and check if the issue persists, please? Also, do you notice any change if you go to AdGuard > gear > Quit and re-start the app?

![image](https://user-images.githubusercontent.com/15856304/84124813-6360ae80-aa44-11ea-9b17-e29dfe24b1d2.png)

---

@shenlihartono commented on [Tue Jun 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-641404613)

@Alex-302 as far as I remember, all this time is that this specific ads keep showing up (on various website site, that _very same_ advertisement) but when I used other plugins/extension on my chrome the ads does not show up.

@Eugene-Savenko still not working, I have tried to close it (the bandwidth+ monitor) and I have also restarted Adguard, still the same.
Here pleasee take a look at video of screenshot I have posted on youtube:
https://www.youtube.com/watch?v=K0vCoohH0qo

---

@Eugene-Savenko commented on [Wed Jun 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-641855829)

@shenlihartono  I think we'll need you to collect debug logs then... Please do the following:

1. Go to AdGuard > gear > Advanced > Logging level > Debug
2. Reproduce the issue
3. Head over to AdGuard > gear > Advanced > Export logs and system info
4. Switch back to the Default logging level
5. Send the logs to support@adguard.com and mention this thread so that we know they're from you :)

Hope you don't mind if we continue working with your case via email.

---

@akmLaVx commented on [Fri Jun 12 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-643406999)

2682037

User has sent the logs

---

@Alex-302 commented on [Sun Jun 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/56412#issuecomment-643770810)

@akmLaVx I see no web requests in the log. 
In any case this is not related to filters. Moved to Mac repository.

**Comment by zzebrum** [comment]
still waiting for additional data from the user

**Comment by shenlihartono** [comment]
Hi, is this issue still investigated?

Do you need more additional data?
Please check the attachment with this email.

I tried again, enabling the debug log and exported it.
I try access this website:
https://www.gsmarena.com/xiaomi_redmi_note_8-9814.php
<https://www.gsmarena.com/xiaomi_redmi_note_8-9814.php>and the ads still
show up

Thank you.

Regards,
Shenli

**Comment by zzebrum** [comment]
@shenlihartono Could you specify what certificate does it show when you click on the lock item in the address bar?

https://uploads.adguard.com/Monosnap_2020-07-07_16-05-40.png

**Comment by zzebrum** [comment]
@shenlihartono any news? 
please, respond right on Github page, not from the email so we can see all the attachments.

**Comment by shenlihartono** [comment]
@zzebrum this is the certificate shown when i click on the lock 

<img width="495" alt="Screen Shot 2020-07-31 at 22 44 10" src="https://user-images.githubusercontent.com/19544482/89052223-986fea00-d37f-11ea-86b8-d8f698549ba6.png">

**Comment by shenlihartono** [comment]
Sorry please close this issue, as I'm not following it anymore. Thank you for your time.
