### ISSUE TITLE
Feature Request: Provide Users With "Set Up Default Settings" when starting AdGuard

### ISSUE THREAD

**Issue by Tryapitsyn** [AdguardTeam/AdguardForMac#715]
Every time my mac (pro 2015) is restarted AdGuard suggests to reset its settings, relaunch it from the very beginning. Every time I just click on "ok, next" or something. It is irritatating

**Comment by adgkart** [comment]
Hi! Cloud you please try to quit the app and remove plist-file?

`sudo rm /Users/user/Library/Preferences/com.adguard.mac.adguard.plist`

**Comment by Tryapitsyn** [comment]
@adgkart Thank you! It looks like a solution and AdGuard starts well)) But it wasn't clear unless I opened this issue, I think it could still irritate a lot of users
