### ISSUE TITLE
hepsiburada.com - HTTPS filtering issue

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#716]
@adguard-bot commented on [Wed Jul 08 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837)

### Issue URL (Annoyance)
 [https://www.hepsiburada.com/thule-ca-tmpa115-15-eva-siyah-apple-macbook-cantasi-p-BS50510](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.hepsiburada.com%2Fthule-ca-tmpa115-15-eva-siyah-apple-macbook-cantasi-p-BS50510)
### Comment
Username: @june8-o
> 
> --
> Aşağıdaki bilgiler otomatik olarak oluşturuldu. Silmeyin.
> 
> Referrer:
> https://forum.donanimhaber.com
> 
> Custom userscripts:
> https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
> 

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/hA6EkaN.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.4.8.797 release
Browser: | Safari
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Adblock Warning Removal List, <br/>EasyList Cookie List<br/><br/><b>Other:</b><br/> Filter unblocking search ads and self-promotion<br/><br/><b>Language-specific:</b><br/> AdGuard Russian, <br/>AdGuard German, <br/>AdGuard Dutch, <br/>AdGuard Turkish
Custom filter subscriptions: | 

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656120855)

I can't reproduce it.
On my end, this cookie notice is already hidden by this rule:
`##.cookie-info:not(body):not(html)`

@AdguardTeam/filters-maintainers Could you please check it?

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656125560)

It exists but does not work for me.

https://www.hepsiburada.com

<img width="1034" alt="Ekran Resmi 2020-07-09 16 22 43" src="https://user-images.githubusercontent.com/25007792/87045443-92fc0580-c200-11ea-80e2-662c0947ab9e.png">

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656131489)

Could you please click right mouse button on this element then choose "Inspect" from menu and make a screenshot (something like on a screenshot below)?

<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/29142494/87046134-0e59b900-c1f9-11ea-831c-a0fef32e8ef3.png)

</details>

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656136608)

There's no "Inspect" in my menu.

<img width="541" alt="Ekran Resmi 2020-07-09 16 42 44" src="https://user-images.githubusercontent.com/25007792/87047676-7b724c00-c203-11ea-8066-4d6071a87c99.png">

When I try to block:

<img width="530" alt="Ekran Resmi 2020-07-09 16 43 42" src="https://user-images.githubusercontent.com/25007792/87047768-95ac2a00-c203-11ea-9947-38d2698d85e8.png">

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656138078)

Does it work if you add this rule to user filter?
`hepsiburada.com##div.cookie-info`

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656140616)

Unfortunately no.

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656145021)

Could you please check these rules:
```
hepsiburada.com##body div.cookie-info
hepsiburada.com#?#div.cookie-info
```

By the way, do you have any other rule in user filter for this website?

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656147616)

Both didn't work. I have no other rule for this website. 

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656147890)

I have tested both with Safari and Firefox.

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656159767)

Could you please check this rule:
`hepsiburada.com##body`
After adding this rule website should be blank, it's for test purpose, just to check if cosmetic filters work correctly.

If it will not work, please check if you see AdGuard certificate on this website.
I'm not sure how to do this in Safari, because I don't MacOS, but in Firefox please click on padlock in address bar and then on arrow, like on a screenshots below.
<details><summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/29142494/87051084-672c5000-c1ff-11ea-8bdc-7dc34a8e5b5e.png)

![image](https://user-images.githubusercontent.com/29142494/87051779-53351e00-c200-11ea-939f-e53dac51e90d.png)

</details>

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656164240)

The page is not blank. 
Screenshots from Firefox:

<img width="311" alt="1" src="https://user-images.githubusercontent.com/25007792/87053127-41f10f00-c20a-11ea-9159-ea7f5131da90.png">
<img width="314" alt="2" src="https://user-images.githubusercontent.com/25007792/87053140-474e5980-c20a-11ea-9e4b-b6dd696e32b6.png">
<img width="732" alt="3" src="https://user-images.githubusercontent.com/25007792/87053150-4ae1e080-c20a-11ea-821e-44f636a28677.png">

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656165691)

This is from Safari:

<img width="589" alt="Ekran Resmi 2020-07-09 17 35 08" src="https://user-images.githubusercontent.com/25007792/87053440-9e542e80-c20a-11ea-869b-2be03413fba5.png">

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656177550)

Ok, thank you for your answer.
It seems that AdGuard certificate is not applied on this website and that's why cosmetic filters don't work.
You can try to reinstall AdGuard certificate (if I'm not wrong, there should be an option to reinstall AdGuard certificate in AdGuard settings).

---

@june8-o commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656179816)

I couldn't find that option.

---

@AdamWr commented on [Thu Jul 09 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656184675)

Unfortunately I don't know where this option is in AdGuard for Mac, because I don't have MacOS.
@AdguardTeam/filters-maintainers Could you please help?

---

@Alex-302 commented on [Fri Jul 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656679421)

There are no that option.
Please check if HTTPS filtering is enabled in `Preferences => Network` tab - `Filter HTTPS protocol`
Also you can try to reinstall AdGuatd. It will automatically install certificate.

---

@june8-o commented on [Fri Jul 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656681823)

It is enabled. And that site is not in excluded ones. I reinstalled AdGuard but nothing changed.

<img width="612" alt="Ekran Resmi 2020-07-10 16 36 12" src="https://user-images.githubusercontent.com/25007792/87160375-8a243600-c2cb-11ea-9828-f017ae5e22eb.png">

---

@june8-o commented on [Fri Jul 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/58837#issuecomment-656705076)

Also, hepsiburada.com is not the only site which has not Adguard certificate.  

https://www.n11.com

<img width="1026" alt="Ekran Resmi 2020-07-10 17 25 50" src="https://user-images.githubusercontent.com/25007792/87165255-919b0d80-c2d2-11ea-96fd-b5f729499767.png">

**Comment by june8-o** [comment]
I have 4 AdGuard Personal CA.cer files on my system. One of them seems to be old. May it be the problem?

<img width="377" alt="Ekran Resmi 2020-07-11 13 00 28" src="https://user-images.githubusercontent.com/25007792/87221753-25261a00-c377-11ea-95b3-2c0b8840833b.png">
<img width="377" alt="Ekran Resmi 2020-07-11 13 00 46" src="https://user-images.githubusercontent.com/25007792/87221756-29eace00-c377-11ea-8d7c-1f7df7d41377.png">
<img width="377" alt="Ekran Resmi 2020-07-11 13 01 03" src="https://user-images.githubusercontent.com/25007792/87221757-2b1bfb00-c377-11ea-96d2-f20837011687.png">
<img width="377" alt="Ekran Resmi 2020-07-11 13 01 19" src="https://user-images.githubusercontent.com/25007792/87221759-2c4d2800-c377-11ea-960d-191c49aa6bd8.png">

**Comment by june8-o** [comment]
And those sites with Guest user. Both have AdGuard certificates.

<img width="1376" alt="Ekran Resmi 2020-07-11 13 14 03" src="https://user-images.githubusercontent.com/25007792/87222249-fb6ef200-c37a-11ea-8da1-ecb5d90e5611.png">
<img width="1376" alt="Ekran Resmi 2020-07-11 13 14 24" src="https://user-images.githubusercontent.com/25007792/87222252-01fd6980-c37b-11ea-8a5d-c5cfa10dad77.png">

**Comment by june8-o** [comment]
I found the reason of the certificate problem. I deselected the following option. AdGuard started to filter also the EV certificated sites. It seems that those sites were EV certificated.

<img width="612" alt="Ekran Resmi 2020-07-11 13 45 53" src="https://user-images.githubusercontent.com/25007792/87222573-56094d80-c37d-11ea-8a2f-7db3d1c7d416.png">
