### ISSUE TITLE
Compatibility issues on BigSur Beta 3

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#718]
After updating your system to the latest beta version of Big Sur OS. Users cannot run the AdGuard application.
- Some AdGuard services were not started correctly. AdGuard won't work correctly.

They have tried to prevent the following actions:
- Reset settings
- Reboot MAC
- Reinstallation of the application, including advanced one

<details><summary>Screenshot:</summary>

</details>

#### HelpDeski ID: 2815644/2824147/2823634/2816271
Archives with the log files are added to NCLoud.

### Your environment

* AdGuard: 2.5.0.838 nightly
* MAC OS: 10.16 (Build 20A4300b)

**Comment by abhilash0505** [comment]
On my Mac, SIP was disabled (automatically) post Beta 3 upgrade. I went to recovery mode and ran `csrutil disable` and AdGuard is working fine after enabling in System preferences.

**Comment by Sam5883** [comment]
i'm having the same problem, on big sur public beta (or beta 4, its the same), version 2.5.0.838 nightly. i know macos is still beta so i'll just wait adguard team to solve all issues instead of doing workarounds.

**Comment by Chinaski1** [comment]
One more user faced a similar issue: 2826002
Logs are added to NCloud

> Some AdGuard services were not started correctly. AdGuard won't work correctly.

**Comment by Chinaski1** [comment]
- HelpDesk ID: 2839007
- AdGuard version: 2.5.0.838 nightly
- OS version: 10.16 (Build 20A5343j)
- Logs are added to NCloud
