### ISSUE TITLE
Stuck at 2FA page

### ISSUE THREAD

**Issue by shenlihartono** [AdguardTeam/AdguardForMac#719]
### Steps to reproduce

1. login in web like usual at https://auth.adguard.com/login.html
2. stuck at https://auth.adguard.com/login/mfa.html page (after input the correct password)
3. tried to reset password, received email  
4. reset the password, and still stuck at the 2FA page 

### Expected behavior
I will be able to login and shown the home page.

### Actual behavior
even though I already input the correct code shown by my authenticator, I still cannot get past the mfa page. 
I never changed my authenticator in my phone so it's still the same since the first time I set up the authenticator / 2FA in my iphone 

<details><summary>Screenshot:</summary>

<img width="542" alt="Screen Shot 2020-07-31 at 22 59 14" src="https://user-images.githubusercontent.com/19544482/89054789-97d95280-d383-11ea-9b92-9524eb885759.png">

</details>

### Customer ID 

sorry i cannot get / know my Customer ID

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

Mac OS Catalina latest version 
Just switch to new machine, so not much installed on the system

**Comment by adgkart** [comment]
Could you please send you login to `a.kartavtsev@adguard.com`?
