### ISSUE TITLE
LinkedIn - Can't Send Message (Spyware Filter)

### ISSUE THREAD

**Issue by war59312** [AdguardTeam/AdguardForMac#72]
Hi,

Looks like the Spyware Filter is breaking the ability to send a Message on Linked In:

> Uncaught TypeError: Cannot read property 'action' of undefined
> Uncaught TypeError: Cannot read property 'rethrown' of null

That is what Chrome logs when I click the Blue "Send Message" button. And no msg is sent.

If I turn off the Spyware Filter it works fine as expected.

OS: OS X El Capitan 10.11.3
Browser: Version 49.0.2623.75 (64-bit)

Thanks,

Will

**Comment by ameshkov** [comment]
@Alex-302 please add this rule to the English filter:
```
@@||linkedin.com/inbox/compose/dialog$document
```

AG messes with this linkedin ajax request.

**Comment by Alex-302** [comment]
@Stillness-2 
added to the English filter
```
@@||linkedin.com/inbox/compose/dialog$document
```

**Comment by war59312** [comment]
Thanks for fixing. :D
