### ISSUE TITLE
AMAZON Help-Chat blocked.......

### ISSUE THREAD

**Issue by BlackSand1974** [AdguardTeam/AdguardForMac#720]
Hello AdGuard team!
On the German AMAZON page, the chat with the support is completely blocked, although the blocking has been deactivated on this page!
Only the main deactivation of AdGuard leads to the success that the chat window is displayed.

**Comment by adgkart** [comment]
Could you please make some additional steps for us?

1. Check if the issue exists in Incognito mode
2. Check if there are no rules in User Rules
3. Send us detailed information about your setup:
- macOS version
- Browser version
- AdGuard for Mac version
- What AdGuard settings are enabled/disabled
- What AdGuard filters are enabled/disabled
- Screenshots of the chat with AdGuard on/off

**Comment by BlackSand1974** [comment]
Hello!

The problem was incognito mode!
Here are some more details:
- macOS 10.15.6
- Safari 13.1.2
- AdGuard 2.4.8.797

Now I have uninstalled the program and installed it again, leaving it with the "basic settings".
The AMAZON Chat now works!

Sorry for the inconvenience!

wolfgang

> Am 05.08.2020 um 15:58 schrieb adgkart <notifications@github.com>:
> 
> Could you please make some additional steps for us?
> 
> Check if the issue exists in Incognito mode
> Check if there are no rules in User Rules
> Send us detailed information about your setup:
> macOS version
> Browser version
> AdGuard for Mac version
> What AdGuard settings are enabled/disabled
> What AdGuard filters are enabled/disabled
> Screenshots of the chat with AdGuard on/off
>
