### ISSUE TITLE
The protection is automatically deactivated when the system goes into sleep mode

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#722]
### Steps to reproduce

1. Turned on Computer, found Adguard had turned itself off
2. Turned Adguard back on
3. Enabled Logging level > Debug
4. Browsed several websites and then closed the laptop lid
5. Opened laptop to again find Adguard had turned itself off

#### HelpDesk ID: 2836462
- Time in Logs: 12:37
- Logs are added to NCloud.

### Your environment

- OS: Version 10.16 (Build 20A5343i)
- Application version: 2.5.0.838 nightly

**Comment by zzebrum** [comment]
10.15 is affected too
