### ISSUE TITLE
com.adguard.mac.adguard.network-extension High CPU Usage after screensaver on Big Sur Beta 20A5343j

### ISSUE THREAD

**Issue by ddriese** [AdguardTeam/AdguardForMac#723]
### Steps to reproduce
1.  Have AdGuard for Mac running.
2.  Have Safari open.
3.  Wait for screensaver to activate.
4.  Dismiss screensaver and check Activity Monitor.

### Expected behavior
Processes should have expected CPU usage.

### Actual behavior
On Big Sur version 20A5343j, using the Nightly Build of AdGuard for Mac.  If Safari is open, the following processes will consume ~40% CPU usage each after the screensaver has been activated and dismissed:

- com.adguard.mac.adguard.network-extension
- Safari Web Content

Force quitting either process will make the other process go back to expected usage.  Neither actually quits Safari or AdGuard for Mac.  The issue happens every time that the screensaver is triggered and subsequently dismissed (unless AdGuard for Mac is not running).

<details><summary>Screenshot:</summary>

<img width="514" alt="Screen Shot 2020-08-12 at 2 09 36 AM" src="https://user-images.githubusercontent.com/7278291/89985609-f7b3e100-dc40-11ea-89d9-2b52a27c5974.png">

</details>

### Customer ID 
I followed the instructions and did not receive a Customer ID after submitting.

### Your environment
* Environment name and version: macOS Big Sur Beta 20A5343j - Safari Version 14.0 (16610.1.23.1.3) - Adguard 2.5.0.838 nightly (CL-1.7.2)
* Any specific potentially conflicting software installed: n/a

**Comment by ddriese** [comment]
So I'm not sure this is dependent upon the screensaver activating at all.  I think the process will overload after some time no matter what.  It may have some relation to viewing live video streams (i.e. Twitch).

**Comment by ddriese** [comment]
Not sure what changed but the issue hasn't occurred in a few days.  I think it may have been caused by a YouTube video in a background tab stuck in a buffering status.

**Comment by zzebrum** [comment]
@ddriese please, reopen the issue if it will be reproducible with the next AdGuard versions.
