### ISSUE TITLE
Cannot ssh to MacOS (Big Sur public beta 1) after installing Adguard nightly

### ISSUE THREAD

**Issue by tarobun** [AdguardTeam/AdguardForMac#724]
### Steps to reproduce

1. Start Adguard
2. Attempt to connect to MacOS from external source
3.
4.

### Expected behavior
ssh connection works

### Actual behavior
Cannot connect from externally.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
Adguard version: 2.5.0.838 nightly

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/CoreLibs #1329](https://github.com/AdguardTeam/CoreLibs/issues/1329) via [**ZenHub**](https://www.zenhub.com/)
