### ISSUE TITLE
AdGuard doesn't block any ads in Big Sur.

### ISSUE THREAD

**Issue by owenzhao** [AdguardTeam/AdguardForMac#726]
### Steps to reproduce

1.
2.
3.
4.

### Expected behavior

Block ads.

### Actual behavior

No ads blocked.

<details><summary>Screenshot:</summary>

<img width="390" alt="summary" src="https://user-images.githubusercontent.com/2182896/90704133-45c08880-e2c2-11ea-9f12-3cb7be0fd148.png">

</details>

### Customer ID 

I sent an email but no auto reply came back.

### Your environment

* Environment name and version: (e.g. Chrome 59): 

Safari 14.0 (16610.1.25.1.3)
macOS Big Sur 11.0 Beta (20A5354i)
AdGuard 2.5.0.838 nightly (CL-1.7.2)

* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

[https://www.macrumors.com](https://www.macrumors.com)

<img width="1436" alt="ads" src="https://user-images.githubusercontent.com/2182896/90704662-b1efbc00-e2c3-11ea-8502-456cf4019eb7.png">

**Comment by zzebrum** [comment]
@owenzhao is the `Network extension` option enabled at `AdGuard settings - Network - Select mode`?
https://uploads.adguard.com/Monosnap_2020-08-20_10-44-14.png

**Comment by owenzhao** [comment]
> @owenzhao is the `Network extension` option enabled at `AdGuard settings - Network - Select mode`?
> https://uploads.adguard.com/Monosnap_2020-08-20_10-44-14.png

Yes. Unlike your picture, the top option is the only option that could be selected in my system.

<img width="662" alt="sc" src="https://user-images.githubusercontent.com/2182896/90753549-56e1b780-e30b-11ea-9819-da5243866706.png">

**Comment by Sam5883** [comment]
i'm having the exact same issue, adguard for mac does not block any single ad on safari, but it actually works on firefox. AdGuard version 2.5.0.838 nightly

**Comment by owenzhao** [comment]
> i'm having the exact same issue, adguard for mac does not block any single ad on safari, but it actually works on firefox. AdGuard version 2.5.0.838 nightly

In my system, Firefox AdGuard doesn't filter ads too.

<img width="682" alt="截屏2020-08-21 上午6 38 01" src="https://user-images.githubusercontent.com/2182896/90832715-fa1ce600-e378-11ea-9e99-b46e49309c17.png">

However, there was also an AdGuard extension for Firefox on Firefox's extension site. Maybe you had installed that before.

For me, AdGuard for Mac is mainly for Safari, as Firefox and Chrome could install ad-block extensions.

**Comment by owenzhao** [comment]
I found the reason. I was using a proxy by ClashXR. It provided proxies for http, https and socks5. AdGuard didn't work when the proxy was enabled. When I stopped the proxies. AdGuard worked again.

However, in macOS 10.15.6 AdGuard worked with ClashXR perfectly.

<img width="780" alt="截屏2020-08-21 上午7 48 04" src="https://user-images.githubusercontent.com/2182896/90836697-a7e0c280-e382-11ea-9300-24b2c4c0e24a.png">

**Comment by owenzhao** [comment]
I found a work around by adding ClashXR to filtered apps. 

<img width="660" alt="add to filter apps" src="https://user-images.githubusercontent.com/2182896/90837487-c1830980-e384-11ea-8f82-0e7319c9569e.png">

However, the result was a little different than the normal mode. As you can see in the picture. The ads were blocked but the space were still hold. I think the reason was that the certificate was not replaced to AdGuard's in the work around. The certificate was still the site's own.

<img width="2647" alt="proxy" src="https://user-images.githubusercontent.com/2182896/90837612-1c1c6580-e385-11ea-8daf-45b15d05edfc.png">

**Comment by zzebrum** [comment]
@owenzhao I've posted your comment above [here](https://github.com/AdguardTeam/CoreLibs/issues/1322#issuecomment-679020432) so devs will take a look into it. 

@Sam5883 either your problem is #727 or it something else. Please, reproduce the issue, collect log files and send it to me.
Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject
