### ISSUE TITLE
AdGuard doesn't work with Youtube in Safari macOS Big Sur (infinity circle loader)

### ISSUE THREAD

**Issue by warb2n** [AdguardTeam/AdguardForMac#727]
### Actual behavior
AdGuard doesn't work with Youtube in Safari macOS Big Sur

<details><summary>AdGuard preferences:</summary>

![Screen Shot 2020-08-20 at 13 22 01](https://user-images.githubusercontent.com/6230166/90758826-479d4280-e2e8-11ea-9e91-9a683265f58c.png)
![Screen Shot 2020-08-20 at 13 22 08](https://user-images.githubusercontent.com/6230166/90758832-49670600-e2e8-11ea-851a-37de2caad6f6.png)
![Screen Shot 2020-08-20 at 13 22 10](https://user-images.githubusercontent.com/6230166/90758835-49ff9c80-e2e8-11ea-9fc7-9d16c48d1413.png)
![Screen Shot 2020-08-20 at 13 22 32](https://user-images.githubusercontent.com/6230166/90758836-4b30c980-e2e8-11ea-88e6-1a1447520e1b.png)

</details>

### Customer ID 
[adguard_logs_20200820102535.zip](https://github.com/AdguardTeam/AdguardForMac/files/5102312/adguard_logs_20200820102535.zip)

### Your environment

• macOS Big Sur _11.0 Beta (20A5354i)_
• AdGuard _2.5.0.838 nightly (CL-1.7.2)_
• Google Chrome Version _84.0.4147.135_ ✓ — Works
<details><summary>Safari 14.0 (16610.1.25.1.3) — ads are blocked but video is not playing (infinity circle loader)</summary>

![Screen Shot 2020-08-20 at 13 18 11](https://user-images.githubusercontent.com/6230166/90758380-9b5b5c00-e2e7-11ea-8fe3-131de9f72c74.png)

**Comment by zer212112** [comment]
i hawe same isue
safari work after adguard is disable

microsoft edge and others browsers is work

mac os 11.0 dev beta 5

**Comment by akmLaVx** [comment]
The same issue has been reported by user 2849086. The logs are available in the ticket.

**Comment by lucky13820** [comment]
Yes, having the same issue. Running 2.5.0.844 nightly and macOS Big Sur 11.0 Beta (20A5354i). Not just YouTube doesn't work, Twitch also doesn't work. And some sites like greehouse.io and lever.co are also not working properly.

**Comment by sfionov** [comment]
It is Apple bug - Safari can't work properly with network extension filtering.

AdGuard 2.5.0.849 nightly is out with workaround for this issue.
YouTube should work in Safari now, but only if Safari is HTTPS filtered. If HTTPS filtered is off or Safari is not filtered, workaround will not be activated, and YouTube won't work.

**Comment by sfionov** [comment]
Reported to Apple
Feedback ID: FB8486799
Forum topic: https://developer.apple.com/forums/thread/657762

**Comment by lucky13820** [comment]
Thanks for the fix! It worked, hopefully Apple can fix the bug.

**Comment by ddriese** [comment]
This issue is still present for me.  It doesn't happen 100% of the time anymore but it still happens regularly and often in the middle of a YouTube video (where I assume it is trying to block an ad).  The issue was fixed about two updates ago but one of the last two updates broke it again.

**Comment by bermudalocket** [comment]
YouTube videos do not load even with HTTPS filtering enabled. I'm on `Application version 2.5.0.900 nightly (CL-1.7.119)`.

**Comment by lucky13820** [comment]
I'm just using Adguard for Safari at his point. AdGuard is not stable right now. Sometimes it works, sometimes it doesn't.

**Comment by srujan89** [comment]
On Mac OS Big Sur, most YouTube videos (> 95%) dont play on safari if AdGuard is enabled. Disabling AdGuard and reloading the page is the only way to play the. This issue has existed since the initial nighties with compatibility for Big Sur units the latest 'stable' release.

**Comment by ddriese** [comment]
@sfionov

**Comment by sfionov** [comment]
@ddriese @srujan89 @bermudalocket 

Hello! Apple still didn't fixed a bug (you may see a lot of 0.0.0.0 connections in network tab of Safari developer console), so we still need a workaround, but we may improve it for your cases. Does adding googlevideo.com to "network.extension.exclude.domains" advanced setting helps?

If not, we may need your debug log.
Here’s what we need you to do:
1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`devteam@adguard.com`** and mention this issue number in the subject.

**Comment by srujan89** [comment]
Adding googlevideo.com to "network.extension.exclude.domains" does indeed help, thanks! A good temporary work around until the issue is fixed permanently.

**Comment by bermudalocket** [comment]
Sorry for the late response. Yes, adding `googlevideo.com` to the exclusions works. Thanks!

**Comment by iDjay** [comment]
also happening with 10.15.7, network extension setting...

**Comment by sfionov** [comment]
@iDjay
Since Apple made incompatible changes to API in BigSur, next version of AdGuard will only support "network extension" filtering method on macOS 11.0.1 and higher. Please consider updating your OS or moving back to Kernel Extension

**Comment by iDjay** [comment]
@sfionov I'll Switch to AdGuard VPN as soon as it's possible + AdGuard for Safari.
