### ISSUE TITLE
Spelling issue 

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#73]
![image](https://cloud.githubusercontent.com/assets/15856304/13666149/bec6b03e-e6b8-11e5-93fd-6d937c0f5a5d.png)

![image](https://cloud.githubusercontent.com/assets/15856304/13666162/c7b27e30-e6b8-11e5-9800-b43f7e2acedc.png)

**Comment by Stillness-2** [comment]
commit 25066
