### ISSUE TITLE
Add Upstream Proxy for AdGuard

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdguardForMac#731]
Since macOS 11 cannot use Legacy Kext mode without disabling SIP, this prevents me from using other NE software and AdGuard at the same time.

If AdGuard can forward all traffic to the HTTP / SOCKS5 proxy in NE mode, I can shut down the other NE software used for network proxy purposes and let AdGuard take over all network traffic.

**Comment by ameshkov** [comment]
@vozersky we should implement this in v2.5 at least via advanced settings (ideally, via network settings)
