### ISSUE TITLE
Update the color of the tray icon to match macOS 11 Light Mode.

### ISSUE THREAD

**Issue by ZeroClover** [AdguardTeam/AdguardForMac#732]
![image](https://user-images.githubusercontent.com/13190004/91852807-eab06d80-ec93-11ea-834d-e662339a2222.png)

As you can see, the tray icon in macOS 11 Light Mode should be white, while the AdGuard Nightly version is still using a black tray icon, which looks a bit out of place.

**Comment by Stillness-2** [comment]
@ZeroClover Check last nightly version please.

**Comment by ZeroClover** [comment]
![image](https://user-images.githubusercontent.com/13190004/93219817-57e8f600-f79e-11ea-81ae-93a26cecf374.png)

Looks great! Thanks for the work.

**Comment by zzebrum** [comment]
Let it be open until the beta version will be released.
