### ISSUE TITLE
Cannot use kexts on the latest macOS system

### ISSUE THREAD

**Issue by du5** [AdguardTeam/AdguardForMac#733]
#### Problem Description

Cannot use kexts on the latest macOS system
 
https://developer.apple.com/support/kernel-extensions/

![image](https://user-images.githubusercontent.com/54979375/91875343-eee98480-ecad-11ea-83ae-b164ff5f2e46.png)
![image](https://user-images.githubusercontent.com/54979375/91875374-fad54680-ecad-11ea-9ee0-399a000816c5.png)

**Comment by zzebrum** [comment]
@du5 that is correct behavior, kext will be deprecated in the Big Sur release version.

**Comment by du5** [comment]
@zzebrum How do I filter ads when I use a third-party VPN?

**Comment by sfionov** [comment]
@du5 If your third-party VPN doesn't work with AdGuard, let us know in [this thread](https://github.com/AdguardTeam/AdguardForMac/issues/692). AdGuard network extension can work together with packet tunnel network extensions, which most of third-party VPNs are.

**Comment by du5** [comment]
@sfionov I use [Surge](https://nssurge.com) to handle my agent

He can also load third-party modules to process web page data

It would be great if Adguard could release official modules

https://manual.nssurge.com/others/module.html

**Comment by zzebrum** [comment]
@du5 temporary solution is to add Surge app to the list of filtered apps in AdGuard settings under the Network tab.

**Comment by du5** [comment]
@zzebrum This will conflict with [Enhanced Mode](https://manual.nssurge.com/others/enhanced-mode.html)

**Comment by zzebrum** [comment]
@du5 you should wait for the next nightly where [this new feature](https://github.com/AdguardTeam/AdguardForMac/issues/731) will be implemented

**Comment by du5** [comment]
thanks
