### ISSUE TITLE
(Big Sur) Incorrect filtering: QQ Music

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#736]
App: https://apps.apple.com/cn/app/qq-yin-le/id595615424?l=en

### Steps to reproduce
1. Enable protection
2. App will refuse to load

App is already excluded from filtering.

### Actual behavior
AdGuard somehow blocks the app.

### Customer ID & logs
2190401

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Big Sur (10.16 build 20A5354i), AdGuard 2.5.0.849n

**Comment by Chinaski1** [comment]
I was able to reproduce the issue on BigSur 11.0 Beta (20A5364e) / AdGuard Nightly (2.5.0.864 nightly (CL-1.7.85))

When the app is launched filtering log is blank.

**Comment by ngorskikh** [comment]
This seems to be a bug in Big Sur, since it works on Catalina, and reproduces with a simple standalone transparent proxy network extension on Big Sur. https://developer.apple.com/forums/thread/660163
