### ISSUE TITLE
Fetching new mail is not possible.

### ISSUE THREAD

**Issue by HelgeBecker** [AdguardTeam/AdguardForMac#737]
### Steps to reproduce

1. Install version 2.5.0.864 nightly (CL-1.7.85)
2. Try to get new mails using Apples Mail client

### Expected behavior

Getting new mails should work

### Actual behavior

Mail fails to get Mails. Happens with those providers: Microsoft Exchange, Google, Apple (iCloud) and other ones offering regular POP3/IMAP services.

Tried to switch of every aspect of Adguard in security, stealth mode and so on. No effect.

<details><summary>Screenshot:</summary>

![Screenshot 2020-09-07 at 13 11 29](https://user-images.githubusercontent.com/26220174/92381818-d7762580-f10b-11ea-96ec-ea642d057163.png)
![Screenshot 2020-09-07 at 13 11 37](https://user-images.githubusercontent.com/26220174/92381826-d8a75280-f10b-11ea-8d93-1efcab96ef1e.png)
</details>

### Customer ID
Unknown. There were never any replys to the bug reports

### Your environment

* Environment name and version: macOS 11.0 20A5354i
* Any specific potentially conflicting software installed: Mail Version 14.0 (3654.0.3) (

**Comment by Chinaski1** [comment]
Hello again.

I would also like to ask you to check the new [Nightly](agrd.io/mac_nightly) build as you did in the previous task.

**Comment by hometechnology** [comment]
I have the same problem with all my standard imap accounts and my icloud mail. I'm on the latest dev beta of macOS Big Sur and the latest nightly build of AdGuard (V2.5.0.864 nightly (CL-1.7.85))

**Comment by lolka4toli** [comment]
A few more examples: #2893853, #305536 and #1462834 client ids. Logs are in NCloud.

**Comment by ISKOTB** [comment]
I just checked for an update and it downloaded/installed "Application version 2.5.0.876 nightly (CL-1.7.95)"
I still have connection issues with, the default MAC mail for personal emails, outlook 16.40 on exchange mail, and some sites

**Comment by Chinaski1** [comment]
@ISKOTB @hometechnology 
Hello!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Menu -> Gear -> Advanced -> Logging level -> Debug;
- Reproduce the issue (and remember the exact time when it happened);
- Menu -> Advanced -> Export Logs and System Info...;
- Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by Eugene-Savenko** [comment]
Another complaint: 615391 (no logs yet).

**Comment by ISKOTB** [comment]
I am now on Application version 2.5.0.879 nightly (CL-1.7.98) same issues AG said no solutions yet!?


-----Original Message-----

**Comment by sfionov** [comment]
It is difficult to do workaround for Apple's bug.
But one idea helps, and we are in progress on implementing it.

**Comment by akmLaVx** [comment]
@ISKOTB has sent a new batch of logs, available in ticket 615391.

macOS default mail app is now able to connect to their email accounts, but MS Outlook is still broken.

**Comment by akmLaVx** [comment]
The issue seems to have come back.
Helpdesk ID: 2942978
Attempted to send/receive messages via Apple Email (SMTP). Fails while protection is enabled.

**Comment by monkeyhangeruk** [comment]
> Attempted to send/receive messages via Apple Email (SMTP). Fails while protection is enabled.

I reported this to support and the problem is **specifically** sending.

With protection enabled Apple Mail cannot connect the the iCloud SMPT server.

It can connect to the iCloud IMAP server.

GMail and an old POP accounts are all working as expected - SMTP and IMAP.

It is only the Apple SMTP that has issues.

**Comment by ameshkov** [comment]
So I guess we need to add port 587 to the default list of exclusions

**Comment by ISKOTB** [comment]
NOT the mac mail, MS Oulook connected to an exchange server "corp email server" If I disable AG it works with no issue. I am on version Application version 2.5.0.902 nightly (CL-1.7.119)


-----Original Message-----

**Comment by ameshkov** [comment]
1. Dock icon -> Settings icon -> Advanced -> Advanced settings...
2. Find `network.extension.exclude.ports` -> add port 587 there

**Comment by monkeyhangeruk** [comment]
That worked - thank you! 👍

**Comment by ISKOTB** [comment]
This did NOT solver my Microsoft Outlook connected to Microsoft Exchange Server issue 
Thank You 


-----Original Message-----

**Comment by ameshkov** [comment]
@ISKOTB 
Could you please try adding ports from this doc?
https://support.prolateral.com/index.php?/Knowledgebase/Article/View/179

If any of them helps, please let us knw

**Comment by zzebrum** [comment]
@ISKOTB any updates?

**Comment by akmLaVx** [comment]
@zzebrum The issue seems to be back, this time affecting both Apple Mail and Microsoft Outlook working over SMTP.

We've collected some fresh log entries - please check helpdesk ticket 3040603.

**Comment by akmLaVx** [comment]
Additional logs available under helpdesk id 3040176.
@AdguardTeam/qa-team, please take a look.

**Comment by Chinaski1** [comment]
@akmLaVx 

Related to this issue is open in the [Corelibs](https://github.com/AdguardTeam/CoreLibs/issues/1389) repository.
I will complement this task with the provided information from the ticket - 3040176.
