### ISSUE TITLE
AdGuard not able to start services on Big Sur Beta

### ISSUE THREAD

**Issue by ravdeepaurora** [AdguardTeam/AdguardForMac#738]
<img width="345" alt="Screenshot 2020-09-12 at 12 46 39 PM" src="https://user-images.githubusercontent.com/16647334/92990006-1504f500-f4f6-11ea-9fcd-c74509d1e692.png">
Adguard installs correctly on the machine with no errors but and initially it shows protected. But after 10 seconds the switch is disabled. I am not able to enable it again. I did perform the usual troubleshooting steps but no luck.

Kindly look into this.

Below is a snippet from the logs

2020/09/07 22:23:26:653  (AANProxyServerHandler) Reload filtering configuration started.
2020/09/07 22:23:26:653  (AAService) Trying to restart network filtering...
2020/09/07 22:23:27:394  (AAService) Not all other cervices started.
2020/09/07 22:23:29:129  (AANProxyServerHandler) Reload filtering configuration started.
2020/09/07 22:23:29:129  (AAService) Trying to restart network filtering...
2020/09/07 22:23:29:830  (AAService) Not all other cervices started.
2020/09/07 22:23:31:638  (AANProxyServerHandler) Reload filtering configuration started.
2020/09/07 22:23:31:638  (AAService) Trying to restart network filtering...
2020/09/07 22:23:32:388  (AAService) Not all other cervices started.
2020/09/07 22:23:41:598  (AANProxyServerHandler) Reload filtering configuration started.
2020/09/07 22:23:41:598  (AAService) Trying to restart network filtering...
2020/09/07 22:23:42:329  (AAService) Not all other cervices started.
2020/09/07 22:23:49:124  (AAPrefBrowsers) Getting extension state result error: nil
2020/09/07 22:23:59:880  (AAPrefBrowsers) Getting extension state result error: nil
2020/09/07 22:26:02:361  (AAAppDelegate) App should terminate request.
2020/09/07 22:26:04:022  (AASNetwork[0x6000015ab560] callUnloadKext:) Error unloading kext. Se

**Comment by Stillness-2** [comment]
@ravdeepaurora AdGuard release version does not support Big Sur at this moment

**Comment by zzebrum** [comment]
@ravdeepaurora please, try the latest [nightly version](https://agrd.io/mac_nightly).

**Comment by zzebrum** [comment]
dup of #692
