### ISSUE TITLE
[Big Sur Nightly] AdGuard blocks Facebook images from loading

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#740]
### Steps to reproduce
1. Install AdGuard Nightly, open Facebook
2. Some images will not load when protection is enabled

### Actual behavior
Some images are blocked from loading.

### Customer ID & Logs
2908351

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Big Sur (build 20A5364e), AdGuard 2.5.0.876n
* Any specific potentially conflicting software installed: None

**Comment by Chinaski1** [comment]
Has the user tried to disable stealth-mode, AdBlocking, and extension modules before reproducing the issue?

**Comment by zzebrum** [comment]
@akmLaVx So far the suggestion is to update to the next nightly which will be released today. There was a bug in the corelibs.

**Comment by zzebrum** [comment]
reopen if the issue happens again.

**Comment by akmLaVx** [comment]
The issue seems to have come back.

Fresh logs & screenshots available under task 2908351.

**Comment by Sergey-Lyapin** [comment]
It seems that the issues below is related to this bug:
https://github.com/AdguardTeam/AdguardFilters/issues/65100
https://github.com/AdguardTeam/AdguardFilters/issues/65157
https://github.com/AdguardTeam/AdguardFilters/issues/65238
https://github.com/AdguardTeam/AdguardFilters/issues/65472
https://github.com/AdguardTeam/AdguardFilters/issues/64575#issuecomment-701189443
https://github.com/AdguardTeam/AdguardFilters/issues/65573

**Comment by monkeyhangeruk** [comment]
Also seeing this with the 2.5.1.906 nightly (CL-1.7.131)

Please let me know if there is any more information I can provide.

For now I have to use Chrome or Firefox to browse Facebook showing the image previews.

**Comment by zzebrum** [comment]
@monkeyhangeruk is it ok on the latest 2.5.1.917 nightly?

**Comment by monkeyhangeruk** [comment]
> @monkeyhangeruk is it ok on the latest 2.5.1.917 nightly?

Hi there, yes all is good with the latest release. image and video previews always show in the Facebook feed.

Thank you :)
