### ISSUE TITLE
(Big Sur Nightly) Network extension causes high CPU usage

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#742]
### Steps to reproduce
1. Be on 11.0, install latest nightly
2. Keep your Mac on for prolonged periods of time

### Expected behavior
Everything works as usual

### Actual behavior
Something's wrong with the network extension - the Activity Monitor looks like it's constantly uploading something to the net

<details><summary>Screenshot:</summary>

![Screen Shot 2020-09-16 at 5 53 52 PM](https://user-images.githubusercontent.com/33634917/93844352-8f2b3b80-fca5-11ea-9346-8bf66ca7834e.png)

</details>

### Customer ID & Logs
598030

**Comment by zzebrum** [comment]
@akmLaVx https://uploads.adguard.com/93844352-8f2b3b80-fca5-11ea-9346-8bf66ca7834e.png_1280952_2020-09-29_17-30-17.png

With new implementation on the Big Sur, those are AdGuard processes that interact with each other. All interactions are local.
So, if the system is on for a long time then it is ok.
