### ISSUE TITLE
Blocked threads

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#743]
AdGuard for Mac is showing me one blocked thread in my statistics. Unfortunately I'm not able to see which thread was blocked and most important where and on which page. Please add an option to show which threads are blocked :)

**Comment by zzebrum** [comment]
1. Blocked thread in statistics shows how many pages were blocked with the Phishing and malware protection module. If you access a website which is detected by our bases, you see this page in your browser: https://uploads.adguard.com/Access_denied_2020-09-22_17-46-18.png 
proceed further or not - the decision is yours. 

2. We do store no more than 10k entries in the filtering log and only if it is opened to limit memory usage.

**Comment by iDjay** [comment]
Statistics didn't show anything and also I never saw the blocked page. That's the weird thing about it.

**Comment by zzebrum** [comment]
@iDjay theoretically it may have happened inside some nasty pop-up being blocked. That's why you didn't notice.
