### ISSUE TITLE
AdGuard deactivates Safari 14 and Big Sur 11.0-beta (20A5364e)

### ISSUE THREAD

**Issue by dagensit** [AdguardTeam/AdguardForMac#744]
It's possible to activate AdGuard on MacBook Air 2018 and use it on Safari. Once. When you try the next time AdGuard is turned off and can't be reactivated unless I close and restart AdGuard.

/Peter

### Steps to reproduce

1.
2.
3.
4.

### Actual behavior

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Chinaski1** [comment]
@dagensit 

Hello there!
As I understand that you are using a release version?

You should try to install the Nightly (agrd.io/mac_nightly) version and check is the issue still persists?

**Comment by dagensit** [comment]
Hi Konstantin

The Nightly Build seems to install a VPN-connection of sorts. And when that’s active Internet connection is blocked. Works when I disable the AdGuard VPN but then AdGuard deactivated too.


/ Peter

**Comment by zzebrum** [comment]
@dagensit do you use any other proxy\vpn?

**Comment by dagensit** [comment]
Hi, 

I have several, but none of them Is active.


/Peter

**Comment by zzebrum** [comment]
@dagensit ok, can you do this: 

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject

**Comment by dagensit** [comment]
OK I will, but still don’t understand why you have to add a proxy

**Comment by zzebrum** [comment]
@dagensit short explanation about that is here: https://github.com/AdguardTeam/AdguardForMac/releases/tag/v2.5.0.892

Did you send log files? Can't find it :(

**Comment by Chinaski1** [comment]
@dagensit 

Hello again!

Could you be more specific as to whether you have managed to sort out your question?
Does the AdGuard application currently work correctly?

**Comment by dagensit** [comment]
Hi Konstantin,

The present config seems to work:
macOS 11.0 (20A5384c)
Safari Version 14.0.1 (16610.2.6.1.6)
AdGuard 2.5.0.896 nightly (CL-1.7.116)

But I’m still puzzled by the VPN-thing. There are VPN suppliers who are able to bypass using the solution with time ticking so I wonder why you guys don’t do that?

/Peter

**Comment by Chinaski1** [comment]
@dagensit 

I do not quite understand your question. Could you please describe it in more detail?
