### ISSUE TITLE
(Big Sur Nightly) AdGuard no longer filters Brave Browser

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#746]
### Steps to reproduce
1. Install Brave (tested on Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit))
2. AdGuard won't filter it and would display an "Not Compatible" error in filtered apps screen

### Expected behavior
Should be filtered.

### Actual behavior
Filtering is no longer available.

<details><summary>Screenshot:</summary>

n/a

</details>

### Customer ID 
2910221

### Your environment
* Environment name and version: (e.g. Chrome 59): Brave Version 1.14.81 Chromium: 85.0.4183.102 (Official Build) (64-bit)

**Comment by Chinaski1** [comment]
Reproduced on BigSur 11 Beta (20A5374i)

**Comment by akmLaVx** [comment]
Some users have reported the same issue on Catalina and Mojave running the latest release builds of Brave.
