### ISSUE TITLE
setapp.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForMac#749]
@adguard-bot commented on [Fri Sep 25 2020](https://github.com/AdguardTeam/AdguardFilters/issues/64558)

### Issue URL (Incorrect Blocking)
 [https://setapp.com](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fsetapp.com)
### Comment
> When I try installing any app from Setapp store, it gives me the message indicated on the screenshot. Once I turn Adguard off, I can install the app without any issues.

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/YQUeywA.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/PmbNeP3.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.5.0.889 nightly
Browser: | Safari
Stealth mode options: | Hide your search queries, <br/>Send Do-Not-Track header, <br/>Remove X-Client-Data header from HTTP requests, <br/>Strip URLs from tracking parameters, <br/>Self-destructing first-party cookies (180), <br/>Block Push API, <br/>Block Location API, <br/>Block Flash, <br/>Block Java
Filters: | <b>Ad Blocking:</b><br/> AdGuard Base<br/><br/><b>Privacy:</b><br/> AdGuard Tracking Protection, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/> AdGuard Social Media<br/><br/><b>Annoyances:</b><br/> AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/> Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List

**Comment by zzebrum** [comment]
Can not reproduce on my side. 
Is `setup.app` added to the list of automatically filtered applications in AdGuard?

**Comment by Chinaski1** [comment]
Not reproducing on the latest BigSur and AdGuard 2.5.0.896 beta (CL-1.7.116)

Please, contact support@adguard.com if the issue persists.
