### ISSUE TITLE
Wrong information in Adguard's filtering log

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#75]
The website HTML code was filtered and modified, but I see nothing about it in the filtering log.

More than this, request has type "Other" instead of "HTML"
<img width="842" alt="00001019" src="https://cloud.githubusercontent.com/assets/5947035/13825837/92d18ee2-ebc5-11e5-92ca-c988abe8f9a9.png">

**Comment by Stillness-2** [comment]
Should it be like that?
<img width="994" alt="2016-04-05 17 13 42" src="https://cloud.githubusercontent.com/assets/12689/14284820/3dc4bbc8-fb5a-11e5-9485-22a9313d9761.png">

**Comment by ameshkov** [comment]
Yep, exactly
