### ISSUE TITLE
OSX Catalina 10.15.7 - Legacy System Extension

### ISSUE THREAD

**Issue by hb9tub** [AdguardTeam/AdguardForMac#750]
For your information, 
Since my MBPro got the last OSX update 10.15.7, I get a pop-up alert message when starting the computer :
"Legacy system extensions"
"Existing software on your system loaded a system
extension signed by ADGUARD which will
be incompatible with future version of macOS."

MbPro 2015 + OSX 10.15.7
Safari 14.0

AdGuard 2.4.8.797
AdGuard Extensions : 
Ad Guard Extra 1.0.161
AdGuard Pop-up windows blocker 2.5.27
Web of Trust 1.1.16
AdGuard Assistant for Safari - activated

**Comment by zzebrum** [comment]
@hb9tub yeap, we are aware of the situation and the next version of the AdGuard app will be compatible with Mac OS v11
closed as dup of #713
