### ISSUE TITLE
Please update zh-TW.

### ISSUE THREAD

**Issue by lancelot-moon** [AdguardTeam/AdguardForMac#751]
zh-TW is just fully done on Crowdin.

**Comment by Chinaski1** [comment]
@lancelot-moon 

Hello there!
Thank you, we will definitely add the translation in the nearest updates.

**Comment by Chinaski1** [comment]
@lancelot-moon 
Please, update to the Nightly version and check have there been any changes in translations?

**Comment by Chinaski1** [comment]
Link: agrd.io/mac_nightly

**Comment by lancelot-moon** [comment]
I don’t have Mac. :D
Anyway, thanks.

**Comment by lancelot-moon** [comment]
You just add this string, "License service is not available/", today.
https://crowdin.com/translate/adguard-applications/17866/en-zhtw#3933662

You may need to update locales again when the release version is out.

**Comment by lancelot-moon** [comment]
https://crowdin.com/translate/adguard-applications/18162/en-zhtw#3930220
macOS Big Sur should be v11.0, not v10.16.
Please fix the English phrase first, and then I'll update its translation.

**Comment by Chinaski1** [comment]
Hello again!

Thank you for the information

Corrected
