### ISSUE TITLE
Error ejecting disk while running Adguard

### ISSUE THREAD

**Issue by iclouny** [AdguardTeam/AdguardForMac#753]
Mac os Mojave 10.14.6 (18G6020). Why does Adguard use an exFAT (used in HDD-Caddy) disk while running? Besides, Adguard does not allow you to disconnect this disk. Unmounting the disk is possible only when exiting Adguard. There is no possibility to change access to the disk in Adguard.
![Снимок экрана 2020-10-10 в 08 35 23](https://user-images.githubusercontent.com/59249716/95648031-e1a98c00-0adc-11eb-9eff-03d4c113ca5f.png)

**Comment by zzebrum** [comment]
@iclouny sorry for the late reply. This is very weird 👀 
If I got it right, restarting the AdGuard does not help.

Please, provide us with debug log files:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject

And also you can send the exact dmg you have installed?

**Comment by iclouny** [comment]
Unfortunately, I reinstalled Adguard. I cannot say for sure which version of the program was installed when this error occurred. This error does not appear on the latest version of the program. I'm sorry, but I don't know how I can help now.

**Comment by zzebrum** [comment]
ok, reopen the issue if the problem appears again.
