### ISSUE TITLE
All traffic blocked in html viewers in Mojave by AdGuard 2.5—secure connection cannot be established

### ISSUE THREAD

**Issue by Bipodos** [AdguardTeam/AdguardForMac#754]
Just upgraded to AdGuard 2.5, on Mojave.
I am running still Mojave due to some legacy apps I need in my work. I am also using Sophos AntiVirus. 
All traffic in html viewers (Safari, Firefox) is blocked since upgrade because no viewer can establish a secure connection. Turniung AdGuard off or quitting it immediately gives access to all websites. Restart of AdGuard or of computer does not help. Changing the network mode from kext to proxy does help for a moment — probably for the few seconds AdGuard is inactive when changing modes.

My Mac runs 10.14.6, AdGuard version is 2.5.0.902 release (CL-1.7.119).

**Comment by Bipodos** [comment]
Resetting all settings has helped in 100%, and all is right, but you can have a look into the issue. I buy life subscriptions for all nerw devices, and will one grateful for some attention

**Comment by zzebrum** [comment]
dup of #755
