### ISSUE TITLE
this might be a duplicate - 755

### ISSUE THREAD

**Issue by eldeemo** [AdguardTeam/AdguardForMac#756]
possible duplicate of 755

### Steps to reproduce

1.went to red lobster.com , placed an order got all the way to check out and upon getting to the screen to enter credit card number page would go white. - turned off the nightly Application version 2.5.0.902 nightly (CL-1.7.119) and was able to enter credit card information - however I have the nightly turned back on and GitHub let me log in (ssl) perfectly fine which is only reason I'm entering this as a possible new bug
2.
3.
4.

### Expected behavior

should take me to secure checkout page for redlobster
### Actual behavior

white screen

<details><summary>Screenshot:</summary>

</details>

### Your environment

Mac OS X 10.15.7 (19H2) - safari Version 14.0 (15610.1.28.1.9, 15610)
* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
I was on a vpn (PIAA)

**Comment by Chinaski1** [comment]
@eldeemo 

Hello there!
Unfortunately, I can't get to the payment page even when using VPN(UK).
Please, use [this instruction](https://kb.adguard.com/ru/technical-support/reporting-tool) to find out the reason for the issue.

**Comment by Chinaski1** [comment]
It seems to be a related issue with task number [755](https://github.com/AdguardTeam/AdguardForMac/issues/755).
Could you clarify that after the last Nightly update it does not play anymore?

I am closing this task - if the issue repeats, just contact us!

Thank you for the report!

**Comment by eldeemo** [comment]
I can confirm it’s working
Thank you

Dmitry
