### ISSUE TITLE
Memory leak in AdGuard 2.5 + Big Sur public beta 5

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#757]
### Steps to reproduce
1. No clear reproduction path has been given - customer told us this can start randomly.

### Actual behavior
AdGuard eats up tons and tons of RAM - in this example, the process took 18GB of Mac's RAM.

<details><summary>Screenshot:</summary>

![Screenshot 2020-10-13 at 23 44 05](https://user-images.githubusercontent.com/33634917/96303586-501dab00-1003-11eb-8a01-1e4f83d769be.png)

</details>

### Customer ID & Debug Logs
2237674

### Your environment
* Environment name and version: (e.g. Chrome 59): macOS Big Sur Public Beta 5, AdGuard 2.5.0.900 nightly (CL-1.7.119)
* Any specific potentially conflicting software installed: Little Snitch (unspecified)

**Comment by Chinaski1** [comment]
For several days we tried to reproduce the specified situation - but without results.
The user also does not respond to the mail so I close this task.
If the issue shows itself again the task can be re-opened.
