### ISSUE TITLE
Safari With HTTP Proxy Doesn't Work When AdGuard 2.5.1.904 nightly (CL-1.7.127) Is Enabled.

### ISSUE THREAD

**Issue by owenzhao** [AdguardTeam/AdguardForMac#758]
I was testing the issue https://github.com/AdguardTeam/AdguardForMac/issues/747 in macOS Big Sur Beta 10. After upgrading to 2.5.1.904 nightly (CL-1.7.127). Safari didn't work any more. Other apps like Carbon Copy Cloner wouldn't get its own update as well. However, Firefox still worked.

<img width="532" alt="CCC_sc" src="https://user-images.githubusercontent.com/2182896/96360384-6df82680-114f-11eb-95a2-c5099d02d7d0.png">

For Safari, the error was strange. The error was a Socket error NSPOSIXErrorDomain:41. I supposed that it should use HTTP Proxy instead of Socket Proxy.

<img width="1436" alt="safari_error" src="https://user-images.githubusercontent.com/2182896/96360405-b0b9fe80-114f-11eb-9ec5-93683865066b.png">

### Steps to reproduce

1. upgrade to macOS Big Sur beta 10. 11.0 Beta版(20A5395g)
2. upgrade to AdGuard 2.5.1.904 nightly (CL-1.7.127)
3. Set HTTP/s Proxy and Socks5 Proxy to 10.0.0.114:7890, which was my other computer in LAN.
4. Open a website in Safari, say gmail.com

### Expected behavior

connect to gmail.com
### Actual behavior

Safari didn't work.

<details><summary>Screenshot:</summary>

</details>

### Your environment

Safari 14.0.1 (16610.2.8.1.1)
macOS Big Sur 11.0 Beta版(20A5395g)
AdGuard 2.5.1.904 nightly (CL-1.7.127)

**Comment by sfionov** [comment]
@owenzhao We'll take a look, but looks like side effect of that beta 10 broken previous version of AdGuard. 

Can you please try with only SOCKS proxy enabled, and with only HTTP+HTTPS proxy enabled?

**Comment by owenzhao** [comment]
> @owenzhao We'll take a look, but looks like side effect of that beta 10 broken previous version of AdGuard.
> 
> Can you please try with only SOCKS proxy enabled, and with only HTTP+HTTPS proxy enabled?

### AdGuard disabled, all proxies set.
Safari works.

### AdGuard enabled, all proxies set.
Safari didn't work. 

### AdGuard enabled, HTTP/s proxies set only.
Safari didn't work. 

### AdGuard enabled, Socks5 proxy set only.
Safari didn't work. 

### AdGuard enabled, no proxy set.
Safari worked. 

### AdGuard enabled, all proxies set with local 127.0.0.1:7890.
Safari worked. But AdGuard blocked nothing.

**Comment by jslawler** [comment]
I noticed this issue as well, and was going to raise it with around 50% of apps having no internet connectivity.

It seems that resetting AdGuard's settings via "Menubar icon > Settings > Advanced > Reset Settings" has fixed the issue on my side.
My guess is that the proxy configuration reset within this process did the trick.

**Comment by owenzhao** [comment]
> I noticed this issue as well, and was going to raise it with around 50% of apps having no internet connectivity.
> 
> It seems that resetting AdGuard's settings via "Menubar icon > Settings > Advanced > Reset Settings" has fixed the issue on my side.
> My guess is that the proxy configuration reset within this process did the trick.

Reset Settings didn't work in my case.

**Comment by Chinaski1** [comment]
Hello, dear users!
Could you check version 2.5.1.911 nightly (CL-1.7.134), is the issue still persists?
- MAC Nighty (agrd.io/mac_nightly)

**Comment by owenzhao** [comment]
> Hello, dear users!
> Could you check version 2.5.1.911 nightly (CL-1.7.134), is the issue still persists?
> 
> * MAC Nighty (agrd.io/mac_nightly)

Yes. The issue still exists.

**Comment by sfionov** [comment]
Seems that Apple fixed it in Big Sur 11.0.1 beta

**Comment by owenzhao** [comment]
> Seems that Apple fixed it in Big Sur 11.0.1 beta

I can not confirm this as macOS 11.0.1 beta can't be installed on my removable SSD. I will try to upgrade it to my internal SSD when I have some time.

**Comment by owenzhao** [comment]
> > Seems that Apple fixed it in Big Sur 11.0.1 beta
> 
> I can not confirm this as macOS 11.0.1 beta can't be installed on my removable SSD. I will try to upgrade it to my internal SSD when I have some time.

This issue no longer exists in macOS Big Sur 11.0.1 beta. Also, there are some good news on HTTP/s Proxy. https://github.com/AdguardTeam/AdguardForMac/issues/747
