### ISSUE TITLE
The DeepL app won't connect

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#763]
DeepL won't connect unless you turn off the protection or switch to the Kernel Extension or Proxy mode. 

### Steps to reproduce

1. Install the app: https://appdownload.deepl.com/macos/DeepL.dmg
2. Skip login and try translating

### Expected behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/97104290-6db1db00-16bb-11eb-96f1-a46b0985e89a.png)

</details>

### Actual behavior

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/15856304/97104285-6094ec00-16bb-11eb-85bb-d80699e2ea96.png)

</details>

### Customer ID 
2059922

### Your environment

* Environment name and version: (e.g. Chrome 59): Application version 2.5.1.906 nightly (CL-1.7.131)
* Any specific potentially conflicting software installed: DeepL v. 1.11.0

**Comment by Chinaski1** [comment]
This issue related to our AG-4846 internal task and it will be fixed in the coming updates.
