### ISSUE TITLE
Copywriting Improvement in AdGuard for MacOS/Safari

### ISSUE THREAD

**Issue by rjonesy** [AdguardTeam/AdguardForMac#765]
This toggle is ambiguous in it's current form. Button labels should _never_ have state in them. Button labels should _label the feature_ that is being turned ON or OFF, and leave the state (ON or OFF) to the toggle.

**Current:** See screenshot. Technically it says that AdGuard's `feature to Disable on this Website` = OFF... so _technically_ disabled blocking is disabled; which means blocking is enabled.

**Proposed:** Label the button with the feature name. Such as "blocking" or "filtering" or whatever your company prefers. I personally think that `AdGuard Blocking` nicely encapsulates the fact that AdGuard blocks more than just Ads, and this toggle turns ON or OFF _all blocking by adguard_ on this page.

**Proposal:** `AdGuard Blocking:`

![Screenshot2020 11 02-17 25 01@2x](https://user-images.githubusercontent.com/5297381/97930428-ef93ab00-1d30-11eb-89da-e453c4f93940.png)

**Comment by zzebrum** [comment]
@rjonesy "AdGuard blocking" may mislead the user. They may think that by toggling the switch you actually can turn on\off filtering in general and that is not true :) Anyway, we will think about how we can change the wording here. Thank you!

**Comment by ameshkov** [comment]
"Protection on this website" + color indication may be okay, but it's a little bit too long.

We want to have "on this website" there as previously we had users being confused by the wording there.

**Comment by rjonesy** [comment]
That's a great point. Then to me this is a "state", with a clarifying point. So it's a normal sized label, with a subtitle/footer label under it.

**AdGuard Protection:**
on GitHub.com ⓘ

I see you are attempting to label the domain with the row above, so maybe you can combine the two. 

Here's a few other phrases that might help.

```
Whitelist:
Protection on this site:
Block Ads on GitHub.com:
```

You also have the freedom to change from a toggle. As you have done with settings below this one.

**Comment by ameshkov** [comment]
`Protection on this site` -- this sounds okay and looks short enough.

I guess we'll need to use different colors for Enabled/Disabled state -- make it light-gray when it's disabled.

Combining is also a not bad idea, but it doesn't play well with the websites that have long domain names.

**Comment by rjonesy** [comment]
@ameshkov If you make the font disabled-colored then the **toggle** will look disabled. As in, the user cannot change the toggle. This is similar to the original problem: Labels are for the feature, _never the state_. (Handy general rule.)

After understanding your user's issues a tab more (surely way less than you!), here's what I suggest you kind folks consider. I hope it helps.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/5297381/98003162-062f1600-1db4-11eb-8f11-c756f5240a61.png">

**Comment by ameshkov** [comment]
Hi Ryan, thank you for the mockup!

And "Pause for 30 seconds" is indeed missing from Safari, good catch:)

**Comment by rjonesy** [comment]
@ameshkov It's there! Just not in the best placement for discoverability, as you now agree. 😜

**Comment by ameshkov** [comment]
Oh, my bad:)

Tbh, I think the reason is that it now attracts more attention (this whole "pause buttons" block kinda stands out).
For "pause" buttons, I'd prefer the same layout as we have in the Chrome/FF assistant because I don't think they're needed that often.

I've listed my thoughts in the new issue in the browser assistant repo:
https://github.com/AdguardTeam/BrowserAssistant/issues/19

**Comment by rjonesy** [comment]
I don't think the current Pause button Safari design is too bad – it *looks* global and "last resort" by being at the bottom like that – which is what it is. Taken in full context of a page it's not super attention-attracting, to my eyes.

<img width="1525" alt="image" src="https://user-images.githubusercontent.com/5297381/98171388-475b1f00-1eb5-11eb-9035-7277df36b8b8.png">

That said, I'd 100% be pushing to standardize this design across all browser if I were you – exactly like you are.

I must say, [the Chrome/FF design](https://uploads.adguard.com/up04_Monosnap_k6rgo.png) looks prettier and has better bones, but man-oh-man is it confusing, for example I'm not certain about:
- what does the pause button pause?
- do not filter should be red icon
- how is "block ads on this website" different from "Enabled on this website"?
- why is "open filter log" a hamburger "open menu" icon?
- am I reporting the website for bad bevahior, NSFW content? That's what it seems like to me.
- [your point](https://github.com/AdguardTeam/BrowserAssistant/issues/19) about button label vs button state separation.

I'm a snob, but these issues prevented me from sticking with AdGuard in the past (I abandoned twice but am now back.) It might be worth engaging a UI/UX person to solve this for all your browsers once and for all.

_(Anecdata: I personally use Pause 30 Seconds a few times a day when a site breaks. Not sure I've ever used standard "Pause", and now that I think about it I wouldn't know if it applies within Safari or my whole Mac.)_

_Please LMK if I posted this in the wrong thread._

**Comment by ameshkov** [comment]
> how is "block ads on this website" different from "Enabled on this website"?

Does "Block an element" sound better to you?

> am I reporting the website for bad bevahior, NSFW content? That's what it seems like to me.

Yeah, this is a problem. Maybe something like "Report incorrect blocking" would work better.

> It might be worth engaging a UI/UX person to solve this for all your browsers once and for all

Yeah, that's what I am planning to do. I am just trying to define the scope first.

> now that I think about it I wouldn't know if it applies within Safari or my whole Mac

It applies to this very website only. Unlike the global "pause" that completely disables AdGuard everywhere.

**Comment by rjonesy** [comment]
> Does "Block an element" sound better to you?

Yes. Or something like "Inspect blocking elements".

> Yeah, this is a problem. Maybe something like "Report incorrect blocking" would work better.

Yep. Or like "Report a blocking issue".

> It applies to this very website only. Unlike the global "pause" that completely disables AdGuard everywhere.

That's a big problem then.

Let me take a stab...

**Comment by rjonesy** [comment]
_Crap, this render came out small. But you get the idea._ 

The idea is to clearly group like items, and utilize norms to convey what a button will do.

✓ settings gear location now makes it clear applies to all of AdGuard and that it will open a window
✓ global toggle is now clear it's global
✓ Report an Issue's location makes it clear what it is
✓ Custom Blocking is now grouped accordingly

<img width="427" alt="Group 2" src="https://user-images.githubusercontent.com/5297381/98276481-a70c0580-1f5b-11eb-890e-1585b5cd9d04.png">

**Comment by ameshkov** [comment]
Nice indeed!

I'd only kept HTTPS filtering under the icon, it's not really useful to most of the users. Also, avoiding one more checkbox/control is a good thing in general.
