### ISSUE TITLE
AdGuard preferences automatically resizes, cutting off headings (Big Sur)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForMac#767]
### Steps to reproduce
1. Select AdGuard preferences

### Expected behavior
Headings not cut, as in macOS Mojave.

### Actual behavior
Headings cut off.

<details><summary>Screenshot:</summary>
<img width="562" alt="Screen Shot 2020-11-08 at 06 42 40" src="https://user-images.githubusercontent.com/6005161/98451005-a5298880-218d-11eb-9822-970d8a7c9249.png">
<img width="662" alt="Screen Shot 2020-11-08 at 06 42 53" src="https://user-images.githubusercontent.com/6005161/98451006-a6f34c00-218d-11eb-96b9-58c4dfc9746a.png">
<img width="562" alt="Screen Shot 2020-11-08 at 06 39 37" src="https://user-images.githubusercontent.com/6005161/98451007-a8247900-218d-11eb-96d6-6885759ee0ab.png">
<img width="562" alt="Screen Shot 2020-11-08 at 06 39 42" src="https://user-images.githubusercontent.com/6005161/98451008-ab1f6980-218d-11eb-89fb-933e3b848edb.png">
<img width="1034" alt="Screen Shot 2020-11-08 at 06 41 57" src="https://user-images.githubusercontent.com/6005161/98451010-ac509680-218d-11eb-97cb-27ac697d5f34.png">
<img width="703" alt="Screen Shot 2020-11-08 at 06 42 03" src="https://user-images.githubusercontent.com/6005161/98451012-ae1a5a00-218d-11eb-95a7-a7abc1b492ef.png">
<img width="688" alt="Screen Shot 2020-11-08 at 06 42 44" src="https://user-images.githubusercontent.com/6005161/98451014-afe41d80-218d-11eb-94ac-71d3c7375fa0.png">
<img width="665" alt="Screen Shot 2020-11-08 at 06 42 49" src="https://user-images.githubusercontent.com/6005161/98451016-b1ade100-218d-11eb-8fe2-64d04f562d92.png">

</details>

### Your environment

* Environment name and version: macOS Big Sur 11.0.1 Beta (20B5022a)

**Comment by Chinaski1** [comment]
Hello there!

Indeed, there is such a specific thing on the BigSur OS.
As release BigSur is just around the corner, we are working hard to improve the performance of AdGuard on the new operating system.
I think in the nearest patches we will also enhance the interface and return it to its usual appearance.

**Comment by Chinaski1** [comment]
Fixed in the Nightly (agrd.io/mac_nightly) version.
