### ISSUE TITLE
Discord compatibility issue

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#768]
Hello,

the last stable version of AdGuard for macOS (2.5.0.902 release (CL-1.7.119)) have compatibility issue with Discord. The application can not update during starting:
![2020-11-09_17-44-47](https://user-images.githubusercontent.com/45385632/98556651-562a4300-22b4-11eb-85d3-54f9b2174cdc.png)

Removing Discord from the filtering list does not solve the problem. Only complete disabling of the AdGuard. The [detailed logs](https://github.com/AdguardTeam/AdguardForMac/files/5511275/adguard_logs_20201109024629.zip) is attached. Please, take a look!😟

Thank you.

**Comment by Chinaski1** [comment]
Hello there!

I managed to reproduce your issue.

Thank you for the information, we will fix this issue in the next update.

**Comment by Chinaski1** [comment]
Hello @ammnt 

Today I checked this issue on BigSur 11.2 Beta (20D5029f) and AdGuard 2.5.2.939 nightly (CL-1.7.153)
-  (Download link: agrd.io/mac_nightly)

I was able to update Discord without any problems.
Could you please check so I can close this task?

**Comment by ammnt** [comment]
@Chinaski1, works perfect now! Thank you.
