### ISSUE TITLE
Change the KEXT behavior in case of a change of user

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#769]
AdGuard service stops its work when users change. (Provided you move from an ordinary user to an administrator).

**Comment by Eugene-Savenko** [comment]
The original reporter (2994231) reports that it's been partially fixed. 

> Hi, just for your info, I have been using the new updated version and the issue seemed solved. Surprisingly yesterday it happened again once, after having logged out one user and switched to the other. Just for your reference.
