### ISSUE TITLE
Can't start Adguard after motherboard replacement.

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#77]
TICKET ID AWX-260-45278 

log: https://gist.github.com/vozersky/6342f7867314d70614d7

**Comment by vozersky** [comment]
<script src="https://gist.github.com/vozersky/6342f7867314d70614d7.js"></script>

**Comment by vozersky** [comment]
<script src="https://gist.github.com/vozersky/6342f7867314d70614d7.js"></script>

**Comment by ameshkov** [comment]
@Stillness-2 any idea?

**Comment by Stillness-2** [comment]
May be Adguard can't obtain serial number or system mac address. I will try to check this on next week. 

It would be nice if the user, which created this ticket, will come here. :)

**Comment by Stillness-2** [comment]
Clarence Mei, check this build please:
https://www.dropbox.com/s/ctig2ihmzqq8i94/Adguard.zip?dl=1

And give us Adguard logs after launching.

**Comment by vozersky** [comment]
forwared to the customer

**Comment by Stillness-2** [comment]
commit 25010
