### ISSUE TITLE
Cannot switch to network extension mode after updating to 2.5.1 in Catalina

### ISSUE THREAD

**Issue by ernestyao** [AdguardTeam/AdguardForMac#770]
After updating to 2.5.1 this morning, the option for Network Extension mode is greyed out. Is that an issue?

OS: 10.15.7 19H15
Adguard 2.5.1.916
Also using Surge 4 (it's used with prior adguard versions too)

![截屏2020-11-10 11 34 28](https://user-images.githubusercontent.com/3162603/98648981-f2fee600-2371-11eb-95fb-ae461a6223fa.png)

**Comment by sfionov** [comment]
Since Apple made incompatible changes to API in Big Sur, next version of AdGuard only supports "network extension" filtering method on macOS 11.0.1 and higher.

**Comment by ernestyao** [comment]
@sfionov  Yeah. I know that. So I plan to switch "network extension" filtering method before the Big Sur updating. I see the new method in v2.5.0. But in v2.5.1 it's greyed out. Do I have to update to Big Sur first?

**Comment by iDjay** [comment]
I guess they disabled it in Catalina because it was causing issues.

**Comment by sfionov** [comment]
@ernestyao Yes, we dropped support for Catalina in 2.5.1 because its Network Extension API is causing issues on both Catalina and Big Sur. New API variant, that have most of issues fixed by Apple, is Big Sur-only.

**Comment by ernestyao** [comment]
@sfionov  Thank you. Get it. Let us wait several hours for Big Sur then.
