### ISSUE TITLE
DNS native encryption compatibility issue 

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#772]
Hello,

I installed Big Sur 11.0.1 today and was extremely disappointed that the connection does not work while using AdGuard for macOS 2.5.1 and the native DNS encryption function in the same time:
![image](https://user-images.githubusercontent.com/45385632/99024295-5312a980-2577-11eb-9e8c-1dd6b0f51f5a.png)

The [detailed logs](https://github.com/AdguardTeam/AdguardForMac/files/5534525/adguard_logs_20201113031033.zip) is attached. Please, confirm it and try to fix it ASAP😫

Thank you.

**Comment by zznosar** [comment]
Yep. I have this Issue too.

I added the AdGuard DNS Mobile Config:

https://adguard.com/en/blog/encrypted-dns-ios-14.html

And it started crawling to the point that it's not connecting at all. Hopefully they can fix this ASAP. Many people are looking forward to use it.

**Comment by ameshkov** [comment]
This is an Apple bug and I have no idea whether they're going to fix it or not.

They are considering AdGuard a VPN connection (despite it being a transparent proxy) and disable DNS encryption.
Just in case, I've filed a question to them: https://developer.apple.com/forums/thread/666527

Meanwhile, I guess the only viable way would be to wait for us to add DNS encryption functionality to AdGuard for Mac (we're planning to do this in the next major update).

**Comment by ameshkov** [comment]
Please note, that this feature works weirdly on MacOS.

It only handles DNS queries from apps that use the new Network framework (like Safari).
All other apps just use the regular DNS server.

**Comment by ameshkov** [comment]
Oh, it's worse than that, Transparent Proxy is broken when DNS settings are enabled.

This is definitely an Apple bug, we'll report it to them asap.

**Comment by zznosar** [comment]
@ameshkov thanks for looking into it.

**Comment by ammnt** [comment]
@ameshkov, yes! Thank you so much for this! So you think this is original Apple bug, right? I ask you because your thread is closed now on the developers forum. No any ways to use DNS native encryption with AdGuard now?🤭Even in HTTP proxy mode? Thank you.

**Comment by ameshkov** [comment]
This is a bug, for sure.

> No any ways to use DNS native encryption with AdGuard now?

Nope.

**Comment by ngorskikh** [comment]
@ammnt As a temporary workaraound, see if the following helps:
1. Exit AdGuard
2. Open Terminal and execute: 
```
defaults write com.adguard.mac.adguard FilteringProcessesV2 -array-add "<dict><key>bundleId</key><string>com.apple.mDNSResponder</string><key>enabled</key><true/><key>filteringBundleIds</key><array><string>com.apple.mDNSResponder</string></array><key>filteringProcessNames</key><array><string>mDNSResponder</string></array><key>localizedName</key><string>mDNSResponder</string></dict>"
```
3. Open AdGuard again

**Comment by ammnt** [comment]
@ngorskikh, this works for me perfect! Thank you so much!😘

**Comment by zznosar** [comment]
Yep. This worked for me too. 👍 Thank you so much!

**Comment by ammnt** [comment]
@ngorskikh & @ameshkov, I just updated the app to 2.5.2 version. Can I remove this daemon from the app filtering list or not yet?🤔Thanks😘

**Comment by ameshkov** [comment]
Well, this bug needs to be fixed by Apple, not us.

@ngorskikh is the Apple Feedback issue still open?

**Comment by ngorskikh** [comment]
@ameshkov 

>Thanks for your feedback.  We believe this report is resolved.
>Please test with the latest macOS 11.3 (Big Sur) beta release [...]

I've checked on `11.3 Beta (20E5186d)` and it seems to work. Keep in mind that this `native encrypted DNS` still only works with NetworkFramework-using apps such as Safari.

**Comment by Macqael** [comment]
> @ameshkov
> 
> > Thanks for your feedback.  We believe this report is resolved.
> > Please test with the latest macOS 11.3 (Big Sur) beta release [...]
> 
> I've checked on `11.3 Beta (20E5186d)` and it seems to work. Keep in mind that this `native encrypted DNS` still only works with NetworkFramework-using apps such as Safari. I think we should check if the issue is solved for more people before closing the feedback, though :)

yes I think it's better to wait the stable update to close this issue.

**Comment by ammnt** [comment]
Works fine after 11.3 release and without the tweak from @ngorskikh🥳

**Comment by BirdInFire** [comment]
@ameshkov time to close this one ?
