### ISSUE TITLE
Can't run Flutter Project, when launch Adguard

### ISSUE THREAD

**Issue by hhgz9527** [AdguardTeam/AdguardForMac#773]
How to change config to handle this case.

Thanks.

Other: https://github.com/flutter/flutter/issues/40515#issuecomment-714499891

**Comment by ameshkov** [comment]
@Stillness-2 

1. Quick solution: figure out what domains it connects to and add them to default HTTPS exclusions list. @hhgz9527 this may be useful to you as well, HTTPS exclusions are configured in settings -> network.
2. We should also figure out why in the world this is getting filtered, we don't touch non-browser apps.

**Comment by andreiborisov** [comment]
It's Google Analytics. Using `flutter config --no-analytics` resolves the issue.

**Comment by ameshkov** [comment]
Well, that's fun. I am not even sure what to do with this now:)

**Comment by andreiborisov** [comment]
> Well, that's fun. I am not even sure what to do with this now:)

I don't think you need to do anything with this, Flutter shouldn't crash if some endpoint isn't available, being analytics or not.

**Comment by ksilz** [comment]
I use Flutter on Big Sur, too. For me it's not the Google Analytics call that fails. It's **other** network calls that my Flutter makes, too. I'd be happy to exclude Flutter from AdGuard filtering, but AdGuard won't let me pick it:

![Cannot select flutter](https://user-images.githubusercontent.com/1061209/102752867-24e86c80-4362-11eb-9dbb-1ecd77925964.png)

It is an executable:

```
~/Applications/flutter/bin % ls -hal
total 32
drwxr-xr-x@  8 karsten  staff   256B Dec 20 16:41 .
drwxr-xr-x@ 25 karsten  staff   800B Dec 20 16:42 ..
drwxr-xr-x  23 karsten  staff   736B Dec 21 07:33 cache
-rwxr-xr-x@  1 karsten  staff   2.0K Dec 10 22:53 dart
-rw-r--r--@  1 karsten  staff   1.4K Dec 10 22:53 dart.bat
-rwxr-xr-x@  1 karsten  staff   2.0K Dec 10 22:53 flutter
-rw-r--r--   1 karsten  staff   2.5K Dec 20 16:41 flutter.bat
drwxr-xr-x@ 19 karsten  staff   608B Dec 20 16:41 internal
```

How can I add Flutter in _Preferences_ - _Network_ - _Applications_?

**Comment by ameshkov** [comment]
@ksilz it seems that Flutter is broken by any Network Extension (at least it's broken by a sample Network Extension with no functionality), even if it does nothing with Flutter's network connection.

We'll report this to Apple soon: https://github.com/AdguardTeam/CoreLibs/issues/1392

Meanwhile, the temporary solution would be to use the "automatic proxy" mode or to switch back to KEXT:
https://kb.adguard.com/en/macos/solving-problems/big-sur-issues#automatic-proxy

**Comment by ksilz** [comment]
I wanted to use "automatic proxy" mode, but my _Network_ preferences don't have "Select Mode..." button:

<img width="648" alt="image" src="https://user-images.githubusercontent.com/1061209/102795460-bf699f80-43a4-11eb-9e0d-2d9192dd7fff.png">

**Comment by ameshkov** [comment]
![image](https://user-images.githubusercontent.com/5947035/102798932-d5865880-43c2-11eb-9e65-914fff2801e0.png)

**Comment by ksilz** [comment]
@ameshkov Thank you! It was staring me right in the face. 🤦🏻

**Comment by erperejildo** [comment]
I faced this problem when I installed AdGuard but after removing it completely still having the same situation

**Comment by erperejildo** [comment]
> It's Google Analytics. Using `flutter config --no-analytics` resolves the issue.

![Uploading Screenshot 2021-03-14 at 15.52.58.png…]()
