### ISSUE TITLE
macos big sur cann't work

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#774]
os_version: MacOS Big Sur 11.0.1
adguard_version: 2.5.1.918 release (CL-1.7.143)
![image](https://user-images.githubusercontent.com/3109626/99087534-d7ac0900-2605-11eb-94b4-4b1509049ce9.jpeg)

**Comment by Chinaski1** [comment]
Hello there!

Looks like you faced an issue with the Network Extension. 
Could you clarify which operating system are you used before the update?
Is it Mojave?

For first you can try to remove the application and install it again (agrd.io/mac).
In the final stage of configuring the application, AdGuard will request confirmation to create the Network extension. You need to open System Preseverans > Security & Privacy > Click on the lock > Enter Password > then allow AdGuard to create a VPN.

**Comment by spacexnasa** [comment]
yes,i remove it ,i will try again

**Comment by spacexnasa** [comment]
![image](https://user-images.githubusercontent.com/3109626/99094627-0aa6ca80-260f-11eb-953f-29972c43b34c.jpeg)
can not find anything

**Comment by spacexnasa** [comment]
reinstall the newest version  and can work,but still have the other problems
