### ISSUE TITLE
on macos big sur can not work properly

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#775]
os_version:macos big sur 11.0.1
adguard version:2.5.1.918 release (CL-1.7.143)

network extension mode  with ClashX  ( like Surge Mac software)

![image](https://user-images.githubusercontent.com/3109626/99137936-fc38cd00-2667-11eb-9c40-0cfed102c1d0.jpeg)

can not filter anything, someone else met this problem ?

**Comment by Chinaski1** [comment]
Hello there!

Any remote (non-local) proxy will work normally in Big Sur alongside AdGuard and doesn't require any additional actions from you. But with a local proxy (localhost), you have to remove it from System settings and configure it in AdGuard.

To configure an upstream proxy in AdGuard for Mac in Big Sur, you need to go to AdGuard menu -> Advanced -> Advanced Settings.... Click on the Value area of the ```upstream.proxy``` setting to configure a proxy.

More details here: https://kb.adguard.com/en/macos/solving-problems/big-sur-issues#local-proxies

**Comment by Chinaski1** [comment]
In general, I can inform you that this is not an application bug.
In the future, we will add common instructions to our knowledge base regarding proxy configurations.

**Comment by spacexnasa** [comment]
ok.thanks.man,i just do like this ,use upstream.proxy
