### ISSUE TITLE
Tencent QQ app cannot work with adguard app in Bigsur 

### ISSUE THREAD

**Issue by byl0561** [AdguardTeam/AdguardForMac#777]
adguard version: 2.1.5.918 release for Mac
macOS version: 11.0.1
all settings: default, uptodate

while enable
network -> automatically filter application traffic -> network expansion

Tencent QQ Application cannot login

while disable, Tencent QQ seems OK

**Comment by Chinaski1** [comment]
Hello there!

Can you provide a link to the specified app? I try to reproduce the issue.

Also, please send a screenshot with the automatic filter [application traffic settings](https://uploads.adguard.com/Chinaskiq8zud.png).

**Comment by ccnana** [comment]
@Chinaski1 

the app app link: https://im.qq.com/macqq/

and it's not added to the list of automatically filtered apps。

**Comment by Chinaski1** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by byl0561** [comment]
done

Konstantin <notifications@github.com> 于2020年11月16日周一 下午9:23写道：

**Comment by Chinaski1** [comment]
Hello again!

We received your e-mail.
Thank you for the information provided.

**Comment by sfionov** [comment]
@byl0561 Hello! Do you use Little Snitch?

**Comment by ccnana** [comment]
@sfionov Yes, i use Little Snitch, too。

**Comment by byl0561** [comment]
> @byl0561 Hello! Do you use Little Snitch?

No, I use Norton Security

**Comment by Chinaski1** [comment]
@byl0561  @ccnana 

Hello there!

Can you check if the issue still reproduces itself after the latest BigSur updates?
Also, better to check on the Nightly version of the AdGuard app (agrd.io/mac_nightly)

As a temporary solution, you can enable AdGuard in [auto-proxy mode](https://uploads.adguard.com/Chinaski93pe3.png).
- AdGuard -> Settings -> Network

**Comment by Chinaski1** [comment]
Good news everyone.

Looks like the recently released update of macOS solves this issue.

- In order to download the current beta version you need to join the Apple Beta Software Program: https://beta.apple.com/
