### ISSUE TITLE
Add support for complex language codes

### ISSUE THREAD

**Issue by confessor-adguard** [AdguardTeam/AdguardForMac#78]
Details in: https://github.com/AdguardTeam/AdguardForWindows/issues/808

**Comment by Stillness-2** [comment]
We support complex language codes

**Comment by ameshkov** [comment]
Are you sure? What for filters translation? AG Assistant translation?

**Comment by Stillness-2** [comment]
If the corresponding localization will exist in filter metadata on the backend server, and in AG Assistant sources, for example `zh-hans`, all must work.
