### ISSUE TITLE
Error establishing connection to website 

### ISSUE THREAD

**Issue by tompalmer** [AdguardTeam/AdguardForMac#780]
On most of websites (that use HTTPS) we get the error "Error establishing connection to website " (tried on safari and chrome). 

It started happening with the release of adguard before big sur. The bug disappears if the application is disabled, but not if you disable adguard via the browser

Also, the application says that the trial period will expire in X days, even if I am lifetime user. 

Considering an app reset if it's just me

**Comment by Chinaski1** [comment]
Hello there!

1. Regarding "Error establishing connection to website":
- Open AdGuard settings -> Network -> AdGuard root certificate -> Save cert to any convenient folder.
- Double click on AdGuard Personal CA -> Keychain will be open -> Open Trust tab > Change to [Always trust](https://uploads.adguard.com/Chinaskienupr.png)
2. To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

- Menu -> Gear -> Advanced -> Logging level -> Debug;
- Reproduce the issue (and remember the exact time when it happened);
- Menu -> Advanced -> Export Logs and System Info...;
- Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by tompalmer** [comment]
Ok I did what was asked, so far no improvement

**Comment by phillies262834** [comment]
I also have this problem, tried the fix, and still doesn't work.

**Comment by Chinaski1** [comment]
After you have sent the logs, please try to uninstall the application using [these instructions](https://kb.adguard.com/en/macos/installation).

Then install the Nightly version of AdGuard(agrd.io/mac_nightly)

Let us know how it goes!

**Comment by tompalmer** [comment]
An application reset did it for me, I had exported my user list so no hassle
