### ISSUE TITLE
Twitter for Mac doesn't work with Adguard

### ISSUE THREAD

**Issue by Sam5883** [AdguardTeam/AdguardForMac#782]
### Steps to reproduce

1. Enable Adguard for Mac with auto proxy mode
2. Open twitter 

### Expected behavior

Twitter should load all tweets and timeline
### Actual behavior

twitter cant load tweets, and if adguard is toggled of, twitter works again

<details><summary>Screenshot:</summary>

![Captura de Tela 2020-11-18 às 14 58 40](https://user-images.githubusercontent.com/65408779/99568785-93768b00-29ae-11eb-813c-4301b1e2e3b4.png)

</details>

### Your environment

* Environment name and version: Adguard 2.5.1 release, macos big sur 11.0.1, twitter for mac 8.4.3.11
* Any specific potentially conflicting software installed: none.

**Comment by Chinaski1** [comment]
Hello Sam!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.
