### ISSUE TITLE
Initial setup screens text clipping

### ISSUE THREAD

**Issue by kour1er** [AdguardTeam/AdguardForMac#785]
On the public build ( 2.5.1.918 release (CL-1.7.143)) and nightly, on the initial setup screens, there are a few instances where the instructional text is clipped i.e. the bottom part of the g character for example. I attach three annotated screenshots pointing them out. (this is obviously very low priority but thought you would like to know)

<img width="718" alt="screen1" src="https://user-images.githubusercontent.com/34779600/99690929-8fb33900-2a80-11eb-91dd-3466fb5d01c5.png">
<img width="720" alt="screen2" src="https://user-images.githubusercontent.com/34779600/99690934-90e46600-2a80-11eb-9f82-662a5f9798fb.png">
<img width="711" alt="screen3" src="https://user-images.githubusercontent.com/34779600/99690937-90e46600-2a80-11eb-8884-bd5715225e7b.png">

**Comment by Chinaski1** [comment]
Fixed in 2.5.2.937 nightly (CL-1.7.153)
Download link: agrd.io/mac_nightly
