### ISSUE TITLE
AdGuard breaks WebSockets in Safari on BigSur

### ISSUE THREAD

**Issue by kaznovac** [AdguardTeam/AdguardForMac#786]
my main issue is with websockets on slack.com and github.com (actions log)
adding those domains to whitelist does not mitigate the issue

### Steps to reproduce

1. enable the AdGuard
2. try this websocket example https://javascript.info/websocket#a-simple-example
3. disable the AdGuard
4. verify that example works

### Expected behavior

WebSockets in example should work (and on other sites)

### Actual behavior

WebSockets do not work, and this message is in WebConsole
`WebSocket network error: OSStatus Error -9810: Internal error `

### Customer ID 

3033797

### Your environment

* Application version 2.5.1.918 release (CL-1.7.143) with extensions disabled
* Environment name and version: macos: 11.0.1, safari: 14.0.1, intel macbook pro 2016
* Any specific potentially conflicting software installed: Little Snitch 5.0.2 (doesn't seem related)

**Comment by sfionov** [comment]
Reported incompatibility with LittleSwitch to Apple:
FB8918126
https://developer.apple.com/forums/thread/667962

**Comment by sfionov** [comment]
Seems that Websockets are working in Safari with AdGuard+LittleSnitch in Big Sur 11.2 Beta 2 🤔
