### ISSUE TITLE
Network Extension interferes with the web version of Whatsapp

### ISSUE THREAD

**Issue by Eugene-Savenko** [AdguardTeam/AdguardForMac#788]
Whatsapp is not working after update to Safari 14.01 and Mac OS 11.0.1

### Steps to reproduce

- Upgrade to Big Sur and Safari 14.0.1
- Install Adguard 2.5.1.918 or 2.5.1.928 nightly
- Run web.whatsapp.com

### Expected behavior

Whatsapp will run

### Actual behavior

<img width="844" alt="GraphiqueCollé-1" src="https://user-images.githubusercontent.com/15856304/99941448-b4582b00-2d76-11eb-87dc-f43e300e0488.png">

### Customer ID 
397794 (w/ debug logs!), 2269561

### Your environment

* Environment name and version: Mac OS 11.0.1, Safari 14.0.1, AdGuard 2.5.1.928 nightly
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): none

**Comment by sfionov** [comment]
Reported incompatibility with LittleSwitch to Apple:
FB8918126
https://developer.apple.com/forums/thread/667962
