### ISSUE TITLE
Safari assistant: open tab instead of new window

### ISSUE THREAD

**Issue by ghost** [AdguardTeam/AdguardForMac#791]
I'm using the safari assistant to report issues on web pages.
Currently, clicking on report opens a new window of safari, which is kind of annoying because sometimes you have to switch between both windows to add the additional information currently.
I would actually prefer that clicking on "report" opens a new tab instead of a new window, so you can easily switch between both tabs for taking screenshots etc.

**Comment by rakleed** [comment]
@Chinaski1 is there any news on this feature request? It seems to be easy to implement it. And the fact that every time a problem is reported on the site opens a new Safari window, it is very annoying.

**Comment by Stillness-2** [comment]
In my opinion, opening a new window is more convenient than opening a new tab. With `command + ~` it is easy to switch between windows in which you are doing something, for example, between the window with the problem page and the window with the report. Also, after sending the report, you can use `command + W` to close the window with the report. 

To use keyboard shortcuts is very comfortable any way... :)

**Comment by ameshkov** [comment]
I tend to agree with @Stillness-2 here, we opted to use a new window because it's easier to switch between the website you're sending the report about and the report itself. This would be pretty problematic to do when there're many tabs opened.

**Comment by rakleed** [comment]
@ameshkov @Chinaski1 in your Windows app you open in the same window in a new tab and there is no problem with that. It's just more convenient for me to switch between tabs, since my browser is always open in full screen, and I often mainly use the mouse for navigation. Therefore, please, do the same behavior as on Windows or add the ability for the user to choose what is more convenient for him.

**Comment by rakleed** [comment]
@ameshkov @Chinaski1 the current implementation is inconsistent. Especially inconvenient when switching from Windows to macOS or vice versa. Please implement support for both options with a choice in the settings.
