### ISSUE TITLE
No host being sent to upstream.proxy

### ISSUE THREAD

**Issue by Fndroid** [AdguardTeam/AdguardForMac#794]
### Steps to reproduce

1. set ``upstream.proxy`` to a socks5 server
2. do some network fetching

### Expected behavior

dst.addr as a domain should be read from socks5 packet

### Actual behavior

dst.add is now an IP address even if I do a domain fetch

<details><summary>Screenshot:</summary>

</details>

### Your environment

* macOS big sur 11.0.1
* adguard for mac 2.5.1.928 release (CL-1.7.150)

**Comment by sfionov** [comment]
Since DNS name is already resolved by browser before it intercepted by AdGuard, it is complicated and requires workaround (fake DNS server).

However, I created feature request in our filtering engine, you may track this issue there:

https://github.com/AdguardTeam/CoreLibs/issues/1386

**Comment by Fndroid** [comment]
But I can find domains in the logs printer. Why's that?

**Comment by sfionov** [comment]
AdGuard detects domain name in first packets of connection but this happens after connection is already established

**Comment by Fndroid** [comment]
Thank you for your patience and responses.
