### ISSUE TITLE
macOS Big Sur Safari Adguard Advanced Blocker - Gmail won't load

### ISSUE THREAD

**Issue by th1818** [AdguardTeam/AdguardForMac#796]
### Steps to reproduce

1. Install Adguard Safari extension via the App Store on Mac (I am using Big Sur)
2. Turn on all Adguard extensions in Safari preference
3. Log onto Gmail, and let it run for a while
4. Eventually, Safari will display a message saying that the Gmail page is using significant memory and is automatically refreshed
5. The page will show "Loading Gmail" and then stuck
6. If I disable Adguard in the preference, or go to "Activity Monitor" and force kill the Adguard Advanced Blocker process, and then refresh the page in Safari, Gmail will load successfully

Note: according to the Activity Monitor, the Safari and Adguard processes are *not* actually using a lot of memory (only a few hundred MB from what I can see at the time of the issue).

### Expected behavior

Gmail should load and run correctly.

### Actual behavior

Got a "Loading Gmail" message (Gmail appears to be stuck loading until I kill the Adguard Advance Blocker process).

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):

MacBook Pro M1 16GB RAM
Big Sur 11.0.1
Latest version of Adguard from the App Store

* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

No

**Comment by th1818** [comment]
I switched to another adblocker Safari extension after submitting this issue 7 hours ago. Gmail has not run into any issue, and it definitely feels much faster (e.g. changing category, composing new mails, reading new mails, moving mails, etc.). Therefore, I believe that Adguard may not have been optimised for the latest version of Safari (e.g. memory leak). 

Note #1: Adguard works perfectly fine so far on MS Edge on the same MacBook (M1). 
Note #2: I had the same issue with Safari+Adguard on my old MacBook (Intel) running Big Sur.

**Comment by zzebrum** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #464](https://github.com/AdguardTeam/AdGuardForSafari/issues/464) via [**ZenHub**](https://www.zenhub.com/)
