### ISSUE TITLE
AdGuard prevent iCloud Music Library Syncing (Error -9810)

### ISSUE THREAD

**Issue by dongjunz** [AdguardTeam/AdguardForMac#797]
### Steps to reproduce

1. If AdGuard is turned ON, Apple Music would not sync.
2. Turn off Sync Library, then turn on again – prompt Error -9810.
3. Quit AdGuard, Apple Music can sync.
4. Same issue on Apple Support: https://discussions.apple.com/thread/252065190

### Actual behavior

As described above: Stuck on "Updating Library" or similar sentences. Nothing updating.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/44934672/101207200-20fbe100-3625-11eb-9780-2922fd64781c.png)
<img width="491" alt="CleanShot 2020-12-04 at 12 39 12@2x" src="https://user-images.githubusercontent.com/44934672/101212834-3e817880-362e-11eb-9324-f978582f0fbc.png">
<img width="202" alt="CleanShot 2020-12-04 at 12 39 23@2x" src="https://user-images.githubusercontent.com/44934672/101212838-3f1a0f00-362e-11eb-8188-75dd5b3f45cd.png">

</details>

### Customer ID 

2720242

### Your environment

* Environment name and version: (e.g. Chrome 59): Music v1.1.2.28, Big Sur 11.1 beta 2
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): No other apps.

**Comment by sfionov** [comment]
@dongjunz Do you have any services in "Network preferences" other than AdGuard and Ethernet/Wi-Fi/Bluetooth?

**Comment by dongjunz** [comment]
I do have TripMode installed, but the app is not running. Thanks

**Comment by dongjunz** [comment]
I removed TripMode and it also solved the problem. I'm not sure which app is causing the problem, but quitting either app, Apple Music works fine.

**Comment by sfionov** [comment]
It looks like the same bug we reported to Apple. Their new firewall API conflicts with their new socket filtering API.

Hope they'll fix it in the next macOS release. At the moment, we recommend to use Automatic proxy mode in AdGuard if you have firewall installed.

**Comment by XxUnkn0wnxX** [comment]
i am getting this issue with little snitch installed I belive 

if I use proxy mode no issues, this so frustrating...

**Comment by Eugene-Savenko** [comment]
Logs here: 3017724.

**Comment by BaksiLi** [comment]
Same issue with not only Apple Music but also **Adobe Creative Cloud**.

With AdGuard switched on, Creative Cloud won‘t sync and load app information. It can be solved by switching it off.

**Comment by Chinaski1** [comment]
@XxUnkn0wnxX @BaksiLi @dongjunz 

Hello there!

Just recently, Apple released the Big Sur 11.2 Beta 2 update. Can you please check if the issue still persists on the new OS version?

**Comment by Serenity23** [comment]
I can confirm that upgrading to 11.2 Beta 2 has fixed the issue. I was previously getting the same error (on 11.1), and after updating to Beta 2 and with AdGuard enabled, I was able to sync my iCloud Music Library without any issue.

**Comment by HitCache** [comment]
I have the exact same issue, I don't have TripMode or anything like that. Installed AdGuard and Apple Music stopped working (couldn't load next track) but once I disable AdGuard everything works fine.

Big Sur 11.2.3

**Comment by Chinaski1** [comment]
Looks weird. @HitCache 
Maybe you using a VPN or third-party antivirus?

**Comment by HitCache** [comment]
> Looks weird. @HitCache
> Maybe you using a VPN or third-party antivirus?

Sorry for the delay in my reply, confirming no VPN or antivirus is in the way.

**Comment by Chinaski1** [comment]
@HitCache it the issue still reproduced on the 11.4 version of macOS?

**Comment by HitCache** [comment]
> @HitCache it the issue still reproduced on the 11.4 version of macOS?

Surprisingly no! Thanks for the ping about this.

Out of curiosity is there a related existing issue link or do you have any insight on what changed that it works fine now on 11.4? I don't want to burden you though if you don't have time :)
