### ISSUE TITLE
Textexpander should sync when Adguard is enabled (macOS 11)

### ISSUE THREAD

**Issue by whkoh** [AdguardTeam/AdguardForMac#798]
### Steps to reproduce
1. Check that Agduard is enabled. 
1. Check that TextExpander app is signed in.
1. Attempt to sync TextExpander snippets.

### Expected behavior
Textexpander should be able to sync even when Adguard is enabled.

### Actual behavior
See first screenshot.
1. TextExpander fails to sync.

#### Tested against by Adguard disabled. See second screenshot.
1. Disable Adguard.
1. Quit TextExpander.
1. Re-open TextExpander. 
1. Attempt to sync TextExpander snippets. 
1. TextExpander sync is successful.

<details><summary>Screenshot:</summary>

![Adguard issue](https://user-images.githubusercontent.com/222353/101270232-1a4ea480-37b2-11eb-80ec-b5845022e02f.png)

</details>

### Customer ID 
1763131

### Your environment

* Environment name and version: (e.g. Chrome 59): macOS 11, TextExpander 6.5.6, Adguard Application version 2.5.1.928 release (CL-1.7.150)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): No

**Comment by whkoh** [comment]
I do not use Little Snitch.

**Comment by Chinaski1** [comment]
Hello there!

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by whkoh** [comment]
Thanks, I sent the logs to apple@adguard.com

**Comment by Chinaski1** [comment]
@whkoh 

We received your logs, tnx for the info provided!

**Comment by Chinaski1** [comment]
Could you clarify if Textexpander is on the [filtered list](https://uploads.adguard.com/Chinaskifrzn9.png) AdGuard -> Settings -> Network?

**Comment by whkoh** [comment]
Hi, it's on the filtered list as I added it manually so as to uncheck it.

[image: image.png]

**Comment by Chinaski1** [comment]
@whkoh 

Hello there!
Just recently, Apple released the Big Sur 11.2 Beta 2 update. Can you please check if the issue still persists on the new OS version?

**Comment by whkoh** [comment]
Sorry, I can't run betas on this device.

**Comment by Chinaski1** [comment]
@whkoh 
Hello!
Version 11.2 was released today, could you check if the issue persists after the update?

**Comment by TravelByRocket** [comment]
I've been having the issues described above but today (after 11.2 install) it looks like it's working!

**Comment by whkoh** [comment]
Verified fixed after upgrading to macOS version 11.2. Closing. Thanks so much for the assistance!
