### ISSUE TITLE
adguard macos big sure proxy mode 

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#799]
newest version adguard
big sure intel

![image](https://user-images.githubusercontent.com/3109626/101274916-dd4bd780-37dc-11eb-9d2e-faeccab8d0c2.jpeg)

![image](https://user-images.githubusercontent.com/3109626/101274940-fbb1d300-37dc-11eb-8b4b-fbc2a3435c9f.jpeg)

**Comment by Chinaski1** [comment]
Hello there, @spacexnasa

As I understand when you try to open a page in Safari you get this [notification](https://uploads.adguard.com/Chinaskici7nr.png)? 
Looks like that the AdGuard certificate is on the "untrusted" list.
You should open KeyChain Access and add AdGuard CA to the list of [trusted certificates](https://uploads.adguard.com/Chinaskidavwe.png) 

Please, let us know the result.

**Comment by spacexnasa** [comment]
> Hello there, @spacexnasa
> 
> 
> 
> As I understand when you try to open a page in Safari you get this [notification](https://uploads.adguard.com/Chinaskici7nr.png)? 
> 
> Looks like that the AdGuard certificate is on the "untrusted" list.
> 
> You should open KeyChain Access and add AdGuard CA to the list of [trusted certificates](https://uploads.adguard.com/Chinaskidavwe.png) 
> 
> 
> 
> Please, let us know the result.

has been added,i will add again

**Comment by spacexnasa** [comment]
1 
i had deletel the old ca,but this can not be  delete

![image](https://user-images.githubusercontent.com/3109626/101435598-95958f00-3947-11eb-86f7-d068b4173d12.jpeg)

2 

![image](https://user-images.githubusercontent.com/3109626/101435678-b8c03e80-3947-11eb-93ea-a755533c17f5.jpeg)

![image](https://user-images.githubusercontent.com/3109626/101435780-e1e0cf00-3947-11eb-90de-cfb22eb61b91.jpeg)

sometime i can not visitit website  , i must disable adguard,and then can visite the website

**Comment by spacexnasa** [comment]
and i use my local dns server via (dnscrypt-proxy),use clash (https://github.com/Dreamacro/clash) use proxy port 1080

**Comment by spacexnasa** [comment]
![image](https://user-images.githubusercontent.com/3109626/101436867-f756f880-3949-11eb-9cc8-0b387e278881.jpeg)


checked again,tursted

**Comment by Chinaski1** [comment]
@spacexnasa 

Can you be more specific about what your issue is at the moment?
Does AdGuard for MAC work when Clash is not active?

**Comment by Chinaski1** [comment]
@spacexnasa 
Any news?

**Comment by spacexnasa** [comment]
> @spacexnasa
> Any news?

sorry for late reply, the proble still exist,i have no idea to resolve

**Comment by Chinaski1** [comment]
In order to further diagnose and resolve this issue, I need to connect to your computer. This would allow us to witness the problem directly and, potentially, fix it as soon as possible. If you're okay with that, please download and install [AnyDesk](anydesk.com) on your computer.

Once you run AnyDesk, you will receive a 9-digit ID in the "Your Desk" session on the top left area of the screen. Please send it to me (k.gretskyi@adguard.com) - I will need it to be able to connect to your computer.
Please specify your timezone and preferable date and time for us to schedule a session with you. 

Looking forward to hearing back from you!

**Comment by spacexnasa** [comment]
> In order to further diagnose and resolve this issue, I need to connect to your computer. This would allow us to witness the problem directly and, potentially, fix it as soon as possible. If you're okay with that, please download and install [AnyDesk](anydesk.com) on your computer.
> 
> 
> 
> Once you run AnyDesk, you will receive a 9-digit ID in the "Your Desk" session on the top left area of the screen. Please send it to me (k.gretskyi@adguard.com) - I will need it to be able to connect to your computer.
> 
> Please specify your timezone and preferable date and time for us to schedule a session with you. 
> 
> 
> 
> Looking forward to hearing back from you!

thanks,tomorrow will be ok  2020-12-23

**Comment by Chinaski1** [comment]
Hello again! @spacexnasa 
I'm ready to connect to your MAC.
Just email me and we will arrange a time for a remote connection session.

**Comment by Chinaski1** [comment]
I close this task because it's directly related to this one https://github.com/AdguardTeam/AdguardForMac/issues/807
Please include all necessary information in it.
