### ISSUE TITLE
Adgard on Big Sur + Safari caused load issues with GitHub Codespaces (works fine in Google Chrome)

### ISSUE THREAD

**Issue by williamli** [AdguardTeam/AdguardForMac#802]
The following can be reproduced across both Intel and Apple M1 Macs.

Works fine on Chrome with Adguard on:
<img width="1677" alt="Screen Shot 2020-12-10 at 19 56 02" src="https://user-images.githubusercontent.com/179761/101773737-262ac580-3b28-11eb-92c7-6bf127c46df9.png">

Breaks Codespaces on Safari with Adguard on:
<img width="1680" alt="Screen Shot 2020-12-10 at 19 56 16" src="https://user-images.githubusercontent.com/179761/101773791-380c6880-3b28-11eb-86a0-0581997dc564.png">

Breaks Codespaces on Safari with Adguard disabled for the website using Assistant plugin, or with all filters disabled, or with site added to every possible whitelist:
<img width="1680" alt="Screen Shot 2020-12-10 at 19 56 23" src="https://user-images.githubusercontent.com/179761/101773853-4e1a2900-3b28-11eb-8e80-caaabfe89985.png">

Codespaces work fine on Safari with Adguard disabled completely:
<img width="1673" alt="Screen Shot 2020-12-10 at 19 56 48" src="https://user-images.githubusercontent.com/179761/101773947-6c802480-3b28-11eb-9d7b-9ef47a51f985.png">

Error message:
> Failed to connect to the remote extension host server (Error: The event "start.block: TimeToFirstConnection-end" already marked in this group.)

Debug logs, logs record ended right after the tests above is done:
adguard_logs_20201210115703.zip (hidden from public access by AdGuard)

PS: Codespaces works fine on Safari on iPad with Adguard enabled

**Comment by williamli** [comment]
@sfionov yes i use Little Snitch, but i have tried with it disabled.

**Comment by Chinaski1** [comment]
A simple deactivation will not be enough.
You need to open the Network settings and check for [any active connections](https://uploads.adguard.com/Chinaski4poad.png) from Little Snitch. 
Other than that, I can tell you that we have already reported this bug to Apple. Presumably, it will be fixed in the next updates of BigSur OS.

**Comment by Chinaski1** [comment]
Hello there @williamli !

Just recently, Apple released the Big Sur 11.2 Beta 2 update. Can you please check if the issue still persists on the new OS version?

In order to download the current beta version, you need to join the Apple Beta Software Program: https://beta.apple.com/

**Comment by Chinaski1** [comment]
I close this task because it is supposedly solved in the BigSur 11.2 release.
Reopen it if the issue still persists.
