### ISSUE TITLE
Whitelist rules do not fully apply

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#803]
### Steps to reproduce
1. Add something to whitelist
2. Site would not open when protection is enabled
3. Disable protection
4. Issues would disappear

### Expected behavior
Whitelisting a website shouldn't block it completely

### Actual behavior
Whitelisting a website breaks it

### Customer ID & debug logs 
3059635

### Your environment
* Environment name and version: (e.g. Chrome 59): AdGuard 2.5.1.928 release, macOS 11 Big Sur

**Comment by Chinaski1** [comment]
A user reported that the problem had been solved.
