### ISSUE TITLE
Skype for Business and Adobe Creative Cloud are blocked when "Automatic filter applications" is ticked

### ISSUE THREAD

**Issue by Alex-302** [AdguardTeam/AdguardForMac#804]
@keewawa commented on [Thu Dec 10 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715)

As the title described, I cannot log on  either Skype for Business or Adobe Creative Cloud when "Automatic filter applications" is enabled. Once this setting is unticked, no issue with the apps.

---

@Alex-302 commented on [Mon Dec 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715#issuecomment-744432340)

Hi. Which AdGuard?

---

@keewawa commented on [Mon Dec 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715#issuecomment-744437075)

Sorry, it is Application version 2.5.1.928 release (CL-1.7.150) on Mac. Actually only started behaving like this after updating to Big Sur

---

@Alex-302 commented on [Mon Dec 14 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715#issuecomment-744728408)

Please open AdGuard's filtering log and restart Skype. And make screenshot. Is Skype  added to filtered apps?

---

@keewawa commented on [Tue Dec 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715#issuecomment-744753489)

Nothing was captured in the log windows (see below). The issue is so reproducible that once "Automatic filter applications" is disabled in Settings Skype for Business can connect. So can Adobe Creative Cloud. By the way, there is no issue with ordinary Skype.

<img width="1098" alt="Screenshot 2020-12-14 at 4 29 42 PM" src="https://user-images.githubusercontent.com/4408568/102143545-b703e880-3e29-11eb-845f-0e2f7350e525.png">

---

@Alex-302 commented on [Tue Dec 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715#issuecomment-745387087)

Weird. Please check when all filters, AdGuard extensions and stealth mode are disabled, but protection is enabled.
Which DNS is used?

---

@keewawa commented on [Tue Dec 15 2020](https://github.com/AdguardTeam/AdguardFilters/issues/69715#issuecomment-745395755)

Disabling all filters, extensions and stealth mode doesn't help. However, if the Filtering Mode under "Automatically filter applications" is changed to "Automatic Proxy" from "Network Extension", then everything works again. As said before, this issue only started after updating to Big Sur, perhaps it has something to do with its Network Extension. 

I didn't set any DNS particularly on the machine

**Comment by Chinaski1** [comment]
Hello there!

Couldn't you ask users if they use third-party antivirus, VPN services, or Little Snitch?
You need to open the Network settings and check for  [any active](https://uploads.adguard.com/Chinaski4poad.png) services from Little Snitch.
As a temporary solution you can leave AdGuard in autoproxy mode.

**Comment by Alex-302** [comment]
@keewawa

**Comment by keewawa** [comment]
I don't use any services mentioned above.
Yes, Auto proxy is a temporary solution

Thx

<img width="177" alt="Screenshot 2020-12-16 at 8 52 49 AM" src="https://user-images.githubusercontent.com/4408568/102364603-40c3cb00-3f7c-11eb-9b5f-1e4cf1085e10.png">

**Comment by Chinaski1** [comment]
@keewawa 
These applications are not filtered by default.
Did you add them manually?

**Comment by keewawa** [comment]
I think I fixed this:

The previous thread reminded me of one thing: I have a company VPN app installed, which does not explicitly create a connection in the above list. There was an update lately but I only installed it this morning. After that, the issue seems to have gone. Now, both Skype for Business and Adobe CC can connect even with "Network extension" 

Thanks for your help. You can close this discussion.

**Comment by sfionov** [comment]
@keewawa Is this VPN app publicly available? We may try to find out what we can do to improve compatibility between this app and AdGuard.

**Comment by keewawa** [comment]
It's Cisco AnyConnect
