### ISSUE TITLE
Switching profile causes the app crash

### ISSUE THREAD

**Issue by lolka4toli** [AdguardTeam/AdguardForMac#805]
### Steps to reproduce
1. Run the main Mac profile 
2. Run AdGuard
3. Switch to another user
4. Get back to the main profile

### Expected behavior
AdGuard should work as always

### Actual behavior
The app crash

### Customer ID 

2438458

### Your environment
* Environment name and version: Safari v14, Catalina 10.15.7 (Build 19H15)

**Comment by Chinaski1** [comment]
Tried to reproduce the issue on Catalina+KEXT but after changing profiles AdGuard continues to work.
Looks like this issue related to [this task](https://github.com/AdguardTeam/AdguardForMac/issues/769).
We will review the logs and let you know the results.
