### ISSUE TITLE
Feature Request: DNS Protection Module for Mac

### ISSUE THREAD

**Issue by TheHadouJHyrule** [AdguardTeam/AdguardForMac#806]
Could you please bring the DNS Protection module featured in AdGuard for androidOS, iOS, and iPadOS? I want to use DNS-over-QUIC on my Mac without having to buy the iPadOS Pro version for my M1 Mac.

**Comment by Rakleed** [comment]
Duplicate of https://github.com/AdguardTeam/AdguardForMac/issues/685

**Comment by TheHadouJHyrule** [comment]
> Duplicate of #685

Got it! I’ll close this case, and refer to that one instead.
