### ISSUE TITLE
adguard+clashx+dnscrypt-proxy--- some website can not visit

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#807]
macos big sur 11.1 intel
adguard 2.5.1.928 release (CL-1.7.150)

test env:
        
        clashx mix port(http+socks5):3129
        dnscrypt-proxy and listen : 5454
      adguard use clashx upstream porxy port : 3129 socks5

![image](https://user-images.githubusercontent.com/3109626/103003672-284f4400-456c-11eb-8e7a-0c6b704c2313.jpeg)

most of the website can visit,and adguard can work also.but some of them can not visit
example 

https://tech.sina.com.cn
https://www.linuxidc.com

the error message is: 

safari

![image](https://user-images.githubusercontent.com/3109626/103006218-1de17a00-456d-11eb-93a8-2a3a69792fb5.jpeg)

firefox

![image](https://user-images.githubusercontent.com/3109626/103006415-2b96ff80-456d-11eb-8760-b3f4bd888d01.jpeg)

https can not visit

![image](https://user-images.githubusercontent.com/3109626/103007025-a6f8b100-456d-11eb-8f22-50dae7297d1f.jpeg)

so i opened the adguard debug log

2020/12/23 21:28:51:292  AGProxySession	[id=1000109-h1] New remote connection to tech.sina.com.cn:443
2020/12/23 21:28:51:292  AGFDVSocketFactory	connect: Started resolving host: tech.sina.com.cn
2020/12/23 21:28:51:292  ANPacProxyServer	Resolved process id: 700
2020/12/23 21:28:51:294  AGProxySession	[id=1000110] Set operating mode to DETECTION
2020/12/23 21:28:51:294  AGProxySession	[id=1000110] Detected protocol is HTTP/1
2020/12/23 21:28:51:294  AGProxySession	[id=1000110] Set operating mode to HTTP1_PROXY
2020/12/23 21:28:51:295  AGProxySession	[id=1000110-h1-1] Parsed received request: CONNECT www.sina.com.cn:443 HTTP/1.1
Host: www.sina.com.cn
User-Agent: com.apple.WebKit.Networking/16610.3.7.1.9 CFNetwork/1209.1 Darwin (unknown version)
Connection: keep-alive
Proxy-Connection: keep-alive

2020/12/23 21:28:51:295  AGProxySession	[id=1000110-h1] New remote connection to www.sina.com.cn:443
2020/12/23 21:28:51:295  AGFDVSocketFactory	connect: Started resolving host: www.sina.com.cn
2020/12/23 21:28:51:296  ANPacProxyServer	Resolved process id: 700
2020/12/23 21:28:51:298  AGProxySession	[id=1000111] Set operating mode to DETECTION
2020/12/23 21:28:51:298  AGProxySession	[id=1000111] Detected protocol is HTTP/1
2020/12/23 21:28:51:298  AGProxySession	[id=1000111] Set operating mode to HTTP1_PROXY
2020/12/23 21:28:51:298  AGProxySession	[id=1000111-h1-1] Parsed received request: CONNECT i.sso.sina.com.cn:443 HTTP/1.1
Host: i.sso.sina.com.cn
User-Agent: com.apple.WebKit.Networking/16610.3.7.1.9 CFNetwork/1209.1 Darwin (unknown version)
Connection: keep-alive
Proxy-Connection: keep-alive

2020/12/23 21:28:51:298  AGProxySession	[id=1000111-h1] New remote connection to i.sso.sina.com.cn:443
2020/12/23 21:28:51:298  AGFDVSocketFactory	connect: Started resolving host: i.sso.sina.com.cn
2020/12/23 21:28:53:443  AGProxySession	[id=1000107-h1-1] sendErrorResponse(endpoint=[::1]:61911; statusCode=502; errorDetails=Error connecting to news.sina.com.cn:443. DNS error: 4(non-recoverable failure in name resolution))
2020/12/23 21:28:53:443  AGProxySession	[id=1000107-h1] httpOutput(endpoint=[::1]:61911; length=111)
2020/12/23 21:28:53:443  AGProxySession	[id=1000107-h1] httpOutput(endpoint=[::1]:61911; length=167246)
2020/12/23 21:28:53:443  AGProxySession	[id=1000107-h1-1] client HTTP stream 1 is fully processed, closing
2020/12/23 21:28:53:445  AGProxySession	[id=1000107-h1] Error on socket 0x700010360d51: 54(Connection reset by peer)
2020/12/23 21:28:53:445  AGProxySession	[id=1000107-h1] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:53:445  AGProxySession	[id=1000107-h1] Destroying session
2020/12/23 21:28:53:451  ANPacProxyServer	Resolved process id: 700
2020/12/23 21:28:53:453  AGProxySession	[id=1000112] Set operating mode to DETECTION
2020/12/23 21:28:53:453  AGProxySession	[id=1000112] Detected protocol is HTTP/1
2020/12/23 21:28:53:453  AGProxySession	[id=1000112] Set operating mode to HTTP1_PROXY
2020/12/23 21:28:53:453  AGProxySession	[id=1000112-h1-1] Parsed received request: CONNECT news.sina.com.cn:443 HTTP/1.1
Host: news.sina.com.cn
User-Agent: com.apple.WebKit.Networking/16610.3.7.1.9 CFNetwork/1209.1 Darwin (unknown version)
Connection: keep-alive
Proxy-Connection: keep-alive

2020/12/23 21:28:53:453  AGProxySession	[id=1000112-h1] New remote connection to news.sina.com.cn:443
2020/12/23 21:28:53:453  AGFDVSocketFactory	connect: Started resolving host: news.sina.com.cn
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet dd=0 pd=1 m_state=7 len=39
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::processOutgoingDataExchange pd=1 m_state=7 len=39 written=39
2020/12/23 21:28:53:921  AGProxySession	[id=1000106-h2-ssl] HTTP/2 session was terminated by peer, last stream=0, error=0
2020/12/23 21:28:53:921  AGProxySession	[id=1000106-h2-ssl] httpOutput(endpoint=64.233.180.101:443; length=17)
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet dd=1 pd=1 m_state=7 len=17
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet preprocessOutputData
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet dd=0 pd=1 m_state=7 len=24
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::processOutgoingDataExchange pd=1 m_state=7 len=24 written=24
2020/12/23 21:28:53:921  AGProxySession	[id=1000106-h2-ssl] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet dd=0 pd=1 m_state=7 len=0
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet dd=0 pd=0 m_state=7 len=0
2020/12/23 21:28:53:921  SSLFilter	[id=1000106] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:53:922  AGProxySession	[id=1000106-h2-ssl] Destroying session
2020/12/23 21:28:53:922  AGProxySession	[id=1000106-h2-ssl] httpOutput(endpoint=[::1]:61908; length=17)
2020/12/23 21:28:55:297  AGProxySession	[id=1000108-h1-1] sendErrorResponse(endpoint=[::1]:61915; statusCode=502; errorDetails=Error connecting to tech.sina.com.cn:443. DNS error: 4(non-recoverable failure in name resolution))
2020/12/23 21:28:55:297  AGProxySession	[id=1000108-h1] httpOutput(endpoint=[::1]:61915; length=111)
2020/12/23 21:28:55:297  AGProxySession	[id=1000108-h1] httpOutput(endpoint=[::1]:61915; length=167246)
2020/12/23 21:28:55:297  AGProxySession	[id=1000108-h1-1] client HTTP stream 1 is fully processed, closing
2020/12/23 21:28:55:299  AGProxySession	[id=1000108-h1] Error on socket 0x700010b63d51: 54(Connection reset by peer)
2020/12/23 21:28:55:299  AGProxySession	[id=1000108-h1] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:55:299  AGProxySession	[id=1000108-h1] Destroying session
2020/12/23 21:28:55:302  AGProxySession	[id=1000109-h1-1] sendErrorResponse(endpoint=[::1]:61916; statusCode=502; errorDetails=Error connecting to tech.sina.com.cn:443. DNS error: 4(non-recoverable failure in name resolution))
2020/12/23 21:28:55:302  AGProxySession	[id=1000109-h1] httpOutput(endpoint=[::1]:61916; length=111)
2020/12/23 21:28:55:302  AGProxySession	[id=1000109-h1] httpOutput(endpoint=[::1]:61916; length=167246)
2020/12/23 21:28:55:302  AGProxySession	[id=1000109-h1-1] client HTTP stream 1 is fully processed, closing
2020/12/23 21:28:55:303  AGProxySession	[id=1000109-h1] Error on socket 0x700011366d51: 54(Connection reset by peer)
2020/12/23 21:28:55:303  AGProxySession	[id=1000109-h1] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:55:303  AGProxySession	[id=1000109-h1] Destroying session
2020/12/23 21:28:55:304  AGProxySession	[id=1000110-h1-1] sendErrorResponse(endpoint=[::1]:61917; statusCode=502; errorDetails=Error connecting to www.sina.com.cn:443. DNS error: 4(non-recoverable failure in name resolution))
2020/12/23 21:28:55:304  AGProxySession	[id=1000110-h1] httpOutput(endpoint=[::1]:61917; length=111)
2020/12/23 21:28:55:304  AGProxySession	[id=1000110-h1] httpOutput(endpoint=[::1]:61917; length=167243)
2020/12/23 21:28:55:304  AGProxySession	[id=1000110-h1-1] client HTTP stream 1 is fully processed, closing
2020/12/23 21:28:55:305  AGProxySession	[id=1000110-h1] Error on socket 0x700011b69d51: 54(Connection reset by peer)
2020/12/23 21:28:55:305  AGProxySession	[id=1000110-h1] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:55:305  AGProxySession	[id=1000110-h1] Destroying session
2020/12/23 21:28:55:307  AGProxySession	[id=1000111-h1-1] sendErrorResponse(endpoint=[::1]:61919; statusCode=502; errorDetails=Error connecting to i.sso.sina.com.cn:443. DNS error: 4(non-recoverable failure in name resolution))
2020/12/23 21:28:55:307  AGProxySession	[id=1000111-h1] httpOutput(endpoint=[::1]:61919; length=111)
2020/12/23 21:28:55:307  AGProxySession	[id=1000111-h1] httpOutput(endpoint=[::1]:61919; length=167249)
2020/12/23 21:28:55:307  AGProxySession	[id=1000111-h1-1] client HTTP stream 1 is fully processed, closing
2020/12/23 21:28:55:308  AGProxySession	[id=1000111-h1] Error on socket 0x700018b10d51: 54(Connection reset by peer)
2020/12/23 21:28:55:308  AGProxySession	[id=1000111-h1] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:55:308  AGProxySession	[id=1000111-h1] Destroying session
2020/12/23 21:28:56:226  SSLFilter	[id=1000004] SSLFilter::tcp_packet dd=0 pd=0 m_state=7 len=273
2020/12/23 21:28:56:226  SSLFilter	[id=1000004] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:56:226  SSLFilter	[id=1000004] SSLFilter::processIncomingDataExchange pd=0 m_state=7 len=273 written=273
2020/12/23 21:28:56:226  SSLFilter	[id=1000004] SSLFilter::tcp_packet dd=1 pd=0 m_state=7 len=244
2020/12/23 21:28:56:226  SSLFilter	[id=1000004] SSLFilter::tcp_packet preprocessOutputData
2020/12/23 21:28:56:234  SSLFilter	[id=1000002] SSLFilter::tcp_packet dd=0 pd=0 m_state=7 len=273
2020/12/23 21:28:56:234  SSLFilter	[id=1000002] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:56:234  SSLFilter	[id=1000002] SSLFilter::processIncomingDataExchange pd=0 m_state=7 len=273 written=273
2020/12/23 21:28:56:234  SSLFilter	[id=1000002] SSLFilter::tcp_packet dd=1 pd=0 m_state=7 len=244
2020/12/23 21:28:56:234  SSLFilter	[id=1000002] SSLFilter::tcp_packet preprocessOutputData
2020/12/23 21:28:56:258  SSLFilter	[id=1000051] SSLFilter::tcp_packet dd=0 pd=0 m_state=7 len=273
2020/12/23 21:28:56:258  SSLFilter	[id=1000051] SSLFilter::tcp_packet processDataExchange
2020/12/23 21:28:56:258  SSLFilter	[id=1000051] SSLFilter::processIncomingDataExchange pd=0 m_state=7 len=273 written=273
2020/12/23 21:28:56:258  SSLFilter	[id=1000051] SSLFilter::tcp_packet dd=1 pd=0 m_state=7 len=244
2020/12/23 21:28:56:258  SSLFilter	[id=1000051] SSLFilter::tcp_packet preprocessOutputData
2020/12/23 21:28:57:464  AGProxySession	[id=1000112-h1-1] sendErrorResponse(endpoint=[::1]:61929; statusCode=502; errorDetails=Error connecting to news.sina.com.cn:443. DNS error: 4(non-recoverable failure in name resolution))
2020/12/23 21:28:57:465  AGProxySession	[id=1000112-h1] httpOutput(endpoint=[::1]:61929; length=111)
2020/12/23 21:28:57:465  AGProxySession	[id=1000112-h1] httpOutput(endpoint=[::1]:61929; length=167246)
2020/12/23 21:28:57:465  AGProxySession	[id=1000112-h1-1] client HTTP stream 1 is fully processed, closing
2020/12/23 21:28:57:467  AGProxySession	[id=1000112-h1] Error on socket 0x70000eb57d51: 54(Connection reset by peer)
2020/12/23 21:28:57:467  AGProxySession	[id=1000112-h1] Shutting down, graceful: 0, reason: Got EOF from client
2020/12/23 21:28:57:467  AGProxySession	[id=1000112-h1] Destroying session
2020/12/23 21:28:57:472  ANPacProxyServer	Resolved process id: 700
2020/12/23 21:28:57:474  AGProxySession	[id=1000113] Set operating mode to DETECTION
2020/12/23 21:28:57:474  AGProxySession	[id=1000113] Detected protocol is HTTP/1
2020/12/23 21:28:57:474  AGProxySession	[id=1000113] Set operating mode to HTTP1_PROXY
2020/12/23 21:28:57:474  AGProxySession	[id=1000113-h1-1] Parsed received request: CONNECT news.sina.com.cn:443 HTTP/1.1
Host: news.sina.com.cn
User-Agent: com.apple.WebKit.Networking/16610.3.7.1.9 CFNetwork/1209.1 Darwin (unknown version)
Connection: keep-alive
Proxy-Connection: keep-alive
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

dig tech.sina.com.cn

; <<>> DiG 9.16.10 <<>> tech.sina.com.cn
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1915
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 10, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tech.sina.com.cn.              IN      A

;; ANSWER SECTION:
tech.sina.com.cn.       1       IN      CNAME   spool.grid.sinaedge.com.
spool.grid.sinaedge.com. 1      IN      CNAME   ww1.sinaimg.cn.w.alikunlun.com.
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.227
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.228
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.229
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.230
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.231
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.225
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.226
ww1.sinaimg.cn.w.alikunlun.com. 1 IN    A       47.246.25.232

;; Query time: 2 msec
;; SERVER: 198.18.0.2#53(198.18.0.2)
;; WHEN: Wed Dec 23 22:28:24 CST 2020
;; MSG SIZE  rcvd: 522

and i think the problem is  two CNAMEs ,maybe not catch by adguard

if i set the Cloaking rules   in dnscrypt-proxy 

tech.sina.com.cn      47.246.23.230
tech.sina.com.cn      47.246.23.231
tech.sina.com.cn      47.246.23.232
tech.sina.com.cn      47.246.23.233
tech.sina.com.cn      47.246.23.234
tech.sina.com.cn      47.246.23.227
tech.sina.com.cn      47.246.23.228
tech.sina.com.cn      47.246.23.229
tech.sina.com.cn       47.246.25.227
tech.sina.com.cn       47.246.25.228
tech.sina.com.cn       47.246.25.229
tech.sina.com.cn       47.246.25.230
tech.sina.com.cn       47.246.25.231
tech.sina.com.cn       47.246.25.225
tech.sina.com.cn       47.246.25.226
tech.sina.com.cn       47.246.25.232

dig @8.8.8.8 tech.sina.com.cn
dig @1.1.1.1 tech.sina.com.cn
dig @223.5.5.5 tech.sina.com.cn

then the website can visit ( clahx open + adguard open )

the normal log is this:

2020/12/23 21:28:30:031  AGFDVSocketFactory	onHostResolved: Host 'www.google.com' was resolved successfully: 216.58.195.68:443
2020/12/23 21:28:30:031  AGFDVSocketFactory	connectImpl: Connecting to host: 216.58.195.68:443
2020/12/23 21:28:30:041  AGFDVSocketFactory	onConnectEvent: Got result for 216.58.195.68:443: 128
2020/12/23 21:28:30:041  AGProxySession	[id=1000093-h1] httpOutput(endpoint=[::1]:61860; length=58)
2020/12/23 21:28:30:041  AGProxySession	[id=1000093-h1] Set operating mode to DETECTION
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] SSLFilter::tcp_packet dd=0 pd=1 m_state=0 len=517
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] SSLFilter::tcp_packet processNewConnectionData
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] ClientHello has GREASE
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] ClientHello has SCT
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] ClientHello has GREASE
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] SSLFilter::indicateSSLHandshakeRequest dataPartAvailable, type=101
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] SSLFilter::indicateSSLHandshakeRequest dataPartAvailable returned DPCR_FILTER
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] SSLFilter::processNewConnectionData SSL version TLSv1.3
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] SSLFilter::processNewConnectionData hostname=www.google.com
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] TLSv1.3 Ciphers: TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
2020/12/23 21:28:30:042  SSLFilter	[id=1000093] Ciphers: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-AES256-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:ECDHE-ECDSA-DES-CBC3-SHA:ECDHE-RSA-DES-CBC3-SHA:DES-CBC3-SHA:TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
2020/12/23 21:28:30:656  SSLFilter	[id=1000093] SSLFilter::tcp_packet dd=0 pd=0 m_state=2 len=2030
2020/12/23 21:28:30:656  SSLFilter	[id=1000093] SSLFilter::tcp_packet processClientHandshakeData
2020/12/23 21:28:30:656  SSLFilter	[id=1000093] SSLFilter::tcp_packet dd=0 pd=0 m_state=2 len=603
2020/12/23 21:28:30:656  SSLFilter	[id=1000093] SSLFilter::tcp_packet processClientHandshakeData
2020/12/23 21:28:30:656  PF	id=1000093 SSLFilter::indicateServerCertificate dataPartAvailable, type=104
2020/12/23 21:28:30:656  PF	id=1000093 SSLFilter::indicateServerCertificate dataPartAvailable returned DPCR_FILTER
2020/12/23 21:28:30:657  PF	SSLDataProvider::doAsyncVerifyCertificate(): www.google.com

can resolve the website ip

dig www.google.com

; <<>> DiG 9.16.10 <<>> www.google.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45796
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; MBZ: 0x0001, udp: 1220
;; QUESTION SECTION:
;www.google.com.                        IN      A

;; ANSWER SECTION:
www.google.com.         1       IN      A       216.58.195.68

;; Query time: 1 msec
;; SERVER: 198.18.0.2#53(198.18.0.2)
;; WHEN: Wed Dec 23 22:37:33 CST 2020
;; MSG SIZE  rcvd: 73

########################################################################################

**Comment by sfionov** [comment]
@spacexnasa Which DNS server do AdGuard use? You may try searching "Using DNS servers:" in AdGuard's log.

**Comment by sfionov** [comment]
Also, there's another option: since BigSur 11.1, AdGuard can filter locahost in network extension mode. So you can try using clash as system proxy and AdGuard in NetworkExtension mode - in this case AdGuard and applications (that support proxy) will not resolve anything - only clash will do it.

**Comment by spacexnasa** [comment]
> @spacexnasa Which DNS server do AdGuard use? You may try searching "Using DNS servers:" in AdGuard's log.

OK，i use clashx dns tun mode,upstream dnscrypt2 that listen 5454

**Comment by spacexnasa** [comment]
2020/12/23 09:14:45:266  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:16:10:271  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:17:21:266  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:17:58:238  AGDnsSettings   Using DNS servers: 8.8.8.8
2020/12/23 09:18:02:595  AGDnsSettings   Using DNS servers: 8.8.8.8
2020/12/23 09:18:02:663  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:21:40:290  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:21:44:831  AGDnsSettings   Using DNS servers: 8.8.8.8
2020/12/23 09:21:50:132  AGDnsSettings   Using DNS servers: 8.8.8.8
2020/12/23 09:21:50:201  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:23:06:094  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:30:05:638  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:30:57:928  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:31:59:587  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:32:21:131  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:34:13:692  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:36:29:597  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:36:59:057  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:37:26:966  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 09:37:36:462  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:42:16:432  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 09:47:38:865  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 11:35:24:600  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 11:35:25:677  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 12:30:07:056  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 12:36:17:302  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 12:58:11:541  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 12:59:31:933  AGDnsSettings   Using DNS servers: 127.0.0.1:0
2020/12/23 12:59:44:130  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 13:00:52:885  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 13:24:58:464  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 13:25:09:446  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 15:17:50:158  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 15:21:48:938  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 15:27:11:606  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 15:27:30:816  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 15:32:33:112  AGDnsSettings   Using DNS servers: 192.168.180.1:0, 114.114.114.114:0
2020/12/23 15:32:52:572  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 20:07:10:599  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 20:07:16:621  AGDnsSettings   Using DNS servers: 8.8.8.8
2020/12/23 20:07:59:052  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/23 20:10:01:586  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/24 08:36:56:733  AGDnsSettings   Using DNS servers: 198.18.0.2:0
2020/12/24 09:34:20:996  AGDnsSettings   Using DNS servers: 198.18.0.2:0



clashx config 


tun:
  enable: true
  macOS-auto-route: true
  macOS-auto-detect-interface: true
  device-url: dev://utun
  dns-listen: '0.0.0.0:53'
  stack: system #gvisor
  dns-hijack:
    - tcp://127.0.0.1:5454
    #- 8.8.8.8
    #- 1.1.1.1
use-hosts: true
dns:
  enable: true # true
  listen: '0.0.0.0:53'  # 修改  0.0.0.0:5454
  ipv6: false
  enhanced-mode: redir-host #fake-ip #redir-host
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  default-nameserver:  # only ip address 
    - 8.8.8.8
    - 1.1.1.1
  nameserver:
    - 127.0.0.1:5454
    #- 8.8.8.8
    #- 1.1.1.1
  fallback:
    - tls://dns.google
    - https://1.1.1.1/dns-query
    #- 8.8.8.8
    #- 1.1.1.1


dnscrypt-proxy 


server_names = ['google','cloudflare']
listen_addresses = ['127.0.0.1:5454']

adguard network mode 

![image](https://user-images.githubusercontent.com/3109626/103053298-9fb8be00-45d4-11eb-8633-8442799327a0.jpeg)

**Comment by spacexnasa** [comment]
> Also, there's another option: since BigSur 11.1, AdGuard can filter locahost in network extension mode. So you can try using clash as system proxy and AdGuard in NetworkExtension mode - in this case AdGuard and applications (that support proxy) will not resolve anything - only clash will do it.

in this mode,adguard can not filter anything,i  has been tried

**Comment by sfionov** [comment]
Did you try this mode on big sur 11.1? There was a bug on 11.0 that was fixed in 11.1 - now localhost can be filtered.

**Comment by spacexnasa** [comment]
> Did you try this mode on big sur 11.1? There was a bug on 11.0 that was fixed in 11.1 - now localhost can be filtered.

your mean i can choose this mode,right ? 

![image](https://user-images.githubusercontent.com/3109626/103060079-e8c33f00-45e1-11eb-8a9d-58992ee73c83.jpeg)

**Comment by spacexnasa** [comment]
> Did you try this mode on big sur 11.1? There was a bug on 11.0 that was fixed in 11.1 - now localhost can be filtered.

i tired about 2 hours ago,cann't not work,and try again laster,can worked,i will need test more,because i have a openvpn ,hope they can all work, thank you very much  @sfionov

**Comment by Chinaski1** [comment]
@spacexnasa 
Any news?

**Comment by spacexnasa** [comment]
> @spacexnasa 
> 
> Any news?

i tested one more week,everything worked fine  with networking mode,no need socks5  proxy.   thanks everyone.
