### ISSUE TITLE
Unable to download file while the application is running

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#810]
### Steps to reproduce

1. Enable last versions of AdGuard for Mac and Safari
2. Go to https://disk.yandex.ru/download?src=Yandex.Sidebar#pc
3. Press yellow button "Скачать"
4. 🤨

### Expected behavior
Yandex.Disk.dmg must be downloaded☝️

### Actual behavior
The abracadabra empty file actually downloaded🤯 

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/45385632/103201356-c80c2980-4900-11eb-8e20-03dbb285631c.png)

</details>

### Logs
The [detailed logs](https://github.com/AdguardTeam/AdguardForMac/files/5746452/adguard_logs_20201228083242.zip) is attached.

### Your environment

* Safari 14.0.2
* macOS 11.1 (20C69)
* AdGuard for Mac 2.5.1.928 (CL-1.7.150)

**Comment by ammnt** [comment]
Damn, it looks like it's a problem with Corelibs. The same problem on Windows 10 and Chrome 87🥺

**Comment by Chinaski1** [comment]
Hello there!

Looks like one of the stealth-mode settings breaks the download.
Try removing the hide-referrer setting first, if that does not help, disable stealth-mode completely and check is the issue still persists?

**Comment by ammnt** [comment]
> Hello there!
> 
> Looks like one of the stealth-mode settings breaks the download.
> Try removing the hide-referrer setting first, if that does not help, disable stealth-mode completely and check is the issue still persists?

Yep. Looks good now😅Thanks a lot!
