### ISSUE TITLE
AdGuard nightly 2.5.2.939 and Big Sur 10.11.1

### ISSUE THREAD

**Issue by evasilis** [AdguardTeam/AdguardForMac#811]
Once nightly 2.5.2.939 is installed and set up onto big sur 10.11.1, it fails with error: 

![Screen Shot 2021-01-06 at 18 35 04](https://user-images.githubusercontent.com/74712901/103795679-f3082300-504e-11eb-9a5f-8d6652950378.png)

This also happens on every boot/reboot. However, turning adguard on, quitting it and launching it again results in the app working normally with no apparent issues. No clash with little snitch 5.0.4.

From console:

Jan  6 18:22:38 doudou Adguard[725]: BUG in libdispatch client: vnode, monitored resource vanished before the source cancel handler was invoked { 0x600002d25680[source], ident: 4 / 0x4, handler: 0x10a674f33 }
Jan  6 18:25:51 doudou Adguard[467]: BUG in libdispatch client: vnode, monitored resource vanished before the source cancel handler was invoked { 0x6000012dfd80[source], ident: 5 / 0x5, handler: 0x10a40cf33 }
Jan  6 18:26:12 doudou com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.adguard.mac.adguard.3098169.3098175(501)> [549]
Jan  6 18:35:36 doudou com.apple.xpc.launchd[1]: Coalition Cache Hit: app<application.com.adguard.mac.adguard.3098169.3098175(501)> [565]

**Comment by evasilis** [comment]
The above does not happen if adguard assistant is set on legacy

![Screen Shot 2021-01-08 at 11 52 52](https://user-images.githubusercontent.com/74712901/104001255-11356680-51a8-11eb-8356-c5d8cbb54eab.png)

**Comment by Chinaski1** [comment]
For first, you should try to reset AdGuard settings:

* Click on the AdGuard icon in the menu bar;
* Click on the gear;
* Go to Advanced;
* Click on Reset settings...

If it doesn't help, we need to get the app logs:

- Menu -> Gear -> Advanced -> Logging level -> Debug;
- Reproduce the issue (and remember the exact time when it happened);
- Menu -> Advanced -> Export Logs and System Info...;
- Send the archive to apple@adguard.com and mention this issue number in the subject.

**Comment by evasilis** [comment]
Thanks and done!
