### ISSUE TITLE
Preference UI looks wrong

### ISSUE THREAD

**Issue by GeQi** [AdguardTeam/AdguardForMac#814]
### Steps to reproduce

1. Open preference plane
2.
3.
4.

### Actual behavior

Everything looks cramped and unnatural.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/4011632/104972703-c1c51680-59af-11eb-96d6-14cd9fc431d6.png)
</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Chinaski1** [comment]
Hello there!

After the release of BigSur, there were indeed some moments in the UI that looked not so good. We have already improved this situation in the Nightly version.
You can see for yourself by clicking on the download link: agrd.io/mac_nightly
