### ISSUE TITLE
Multiple functions of Safari Assistant widget don't work

### ISSUE THREAD

**Issue by y4rr** [AdguardTeam/AdguardForMac#815]
Hi friends. The following functionality of the widget in Safari doesn't work for me:
1. Disable/enable filtering for website
2. Pause filtering
3. Block an element
4. Reset all custom rules.

My widget looks like this, it doesn't change dependent on the current website (apart from the website name):
<img width="263" alt="Untitled" src="https://user-images.githubusercontent.com/45952955/105216960-4ce70d80-5b64-11eb-88f4-6c79f10f2969.png">

I suspect these problems are caused by the widget being unable to communicate with the main app at all.

And, ultimately, the root cause of this is probably another Apple "security" sh*t stuff, related to app groups, because I have this in my syslog:
```
20:55:31.369811+0300	default	com.apple.securityd	SecWarning	trustd	trustd	Entitlement com.apple.application-identifier=TC3Q7MAJXF.com.adguard.mac.adguard is ignored because of invalid application signature or incorrect provisioning profile
20:55:31.369860+0300	default	com.apple.securityd	SecWarning	trustd	trustd	Entitlement com.apple.security.application-groups=(
    "TC3Q7MAJXF.com.adguard.mac"
) is ignored because of invalid application signature or incorrect provisioning profile
```

Apart from that, there isn't anything else in the syslog that may be relevant. 

How is this signing error is possible is not clear to me, because I have used TinkerTool to check AdGuard's app bundle for signing errors, and it shows that there is none:
<img width="773" alt="Untitled 2" src="https://user-images.githubusercontent.com/45952955/105216942-49ec1d00-5b64-11eb-9196-2b184aa31db3.png">

Adguard for Mac 2.5.1.928 beta
OS X 10.15.7 19H114
Safari Version 14.0.2 (15610.3.7.1.10, 15610)

**Comment by Chinaski1** [comment]
Hello @y4rr!

Indeed the AdGuard assistant in safari had several vulnerabilities. We fixed them in one of the Nightly updates.
Could you please install it and check if the situation persists?
Download link: agrd.io/mac_nightly

**Comment by y4rr** [comment]
> Hello @y4rr!
> 
> Indeed the AdGuard assistant in safari had several vulnerabilities. We fixed them in one of the Nightly updates.
> Could you please install it and check if the situation persists?
> Download link: agrd.io/mac_nightly

Thank you, I think this nightly build has resolved the isssues.
