### ISSUE TITLE
can not open any website after using upstream  proxy with Surge 4

### ISSUE THREAD

**Issue by foisonocean** [AdguardTeam/AdguardForMac#816]
I have read this [article](https://kb.adguard.com/en/macos/solving-problems/big-sur-issues), but it doesn't help.

### Steps to reproduce

1. turn off adguard
1. open Advanced Settings
1. set `upstream.proxy` to `socks5://127.0.0.1:6153` and `upstream.proxy.sock5udp` to `true`,  then click "Apply" button
1. turn off System Proxy and turn off Enhanced Mode in Surge
1. turn on adguard

### Expected behavior
everything should works as expect.

### Actual behavior
I can not open any website in Safari. Some CLI tool like `curl` works, but it seems the upstream proxy is not applied to `curl`.

### Customer ID 
ticket number is 3155696

### Your environment

* Environment name and version: macOS: 11.1 (20C69) Adguard: version 2.5.1.928
* Any specific potentially conflicting software installed: Surge: Version 4.0.4 (1227)

**Comment by sfionov** [comment]
On macOS 11.1 AdGuard can filter localhost, so you can use "System proxy" mode in Surge instead of using upstream.proxy in AdGuard. It is better because Surge will receive domains instead of IPs. AdGuard may only pass IPs to upstream.proxy - if your provider blocks some sites by DNS, this may be a problem.

**Comment by foisonocean** [comment]
@sfionov I  just tried using "System Proxy", and found another issue. As you may know, Surge is a rule-based proxy, which means you can configure which domains should use a proxy and which domains should connect directly. After using "System Proxy", I found for those domains which should be connected directly, it works properly, but for those domains which need a proxy, I can not open those sites.

**Comment by ZeroClover** [comment]
AdGuard and Surge do not conflict under macOS 11. AdGuard uses NE to create a Personal VPN, while Surge enhanced mode creates a TUN device and add more specific routes to the routing table to route all traffic. Both can be used simultaneously.

**Comment by Chinaski1** [comment]
I can also confirm that I haven't encountered any compatibility issues between Surge and AdGuard on version 11.1.
I checked different combinations with System Proxy and Enhanced mode enabled/disabled.

**Comment by foisonocean** [comment]
But somehow I couldn't make AdGuard work with Surge System Proxy mode.
Any suggestions for figuring out why AdGuard does not work?

**Comment by Chinaski1** [comment]
Perhaps the logs can help make sense of the situationю.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

**Comment by Chinaski1** [comment]
As the issue does not reproduce and the user does not respond I will close this task.

**Comment by hronro** [comment]
Finally turned out only if I use a "Snell" (v2) type proxy in Surge will conflict with AdGuard.
If the proxy type in Surge is "Trojan" or "Shadowsocks", Surge and AdGuard works together pretty well.

Not sure this is a bug of Surge or AdGuard.

**Comment by A1saka** [comment]
@hronro Hi, how can you let AdGuard work with Surge System Proxy mode, I just use Enhanced Mode in Surge with Adguard together. Any settings suggestions in Adguard ?

**Comment by ZeroClover** [comment]
@A1saka This should be a new issue after macOS 11.3, before 11.3 Surge System Proxy mode and AdGuard NE mode worked together.

**Comment by A1saka** [comment]
> @A1saka This should be a new issue after macOS 11.3, before 11.3 Surge System Proxy mode and AdGuard NE mode worked together.

bad Tim Cook  :(

**Comment by Chinaski1** [comment]
Good news everyone!

We found a temporary solution to the issue.

Available in the Nightly version of AdGuard for macOS: agrd.io/mac_nightly
