### ISSUE TITLE
After updating MacOS

### ISSUE THREAD

**Issue by essamamdani** [AdguardTeam/AdguardForMac#817]
### Steps to reproduce

1. Click Adguard application
2. It doesn't response back. Find in Screenshot

### Actual behavior

<details><summary>Screenshot:</summary><img width="276" alt="Screenshot 2021-01-26 at 6 58 51 PM" src="https://user-images.githubusercontent.com/413629/105854424-b3f33f00-6008-11eb-9b8c-42609713c526.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Chinaski1** [comment]
Hello there @essamamdani!

Please try to reset AdGuard settings:

* Click on the AdGuard icon in the menu bar;
* Click on the gear;
* Go to Advanced;
* Click on Reset settings...

If this has no effect, you need to reinstall the application.
- [How to uninstall](https://kb.adguard.com/en/macos/installation#uninstall)
- Download link: agrd.io/mac

Let me know should you have any additional questions.

**Comment by essamamdani** [comment]
@Chinaski1 I can't access the application its not responding when i ran this application.

I uninstalled it two times and fresh download from the link. It still the same response.

Thanks

**Comment by Chinaski1** [comment]
I think the best option would be to do a short remote connection session.
Please, contact me at k.gretskyi@adguard.com for details.
