### ISSUE TITLE
Memory Leaks with High CPU Usage 

### ISSUE THREAD

**Issue by owenzhao** [AdguardTeam/AdguardForMac#818]
### Steps to reproduce

This probably related to "G Hub" app, which is the recommended software for Logitech mice and keyboards.

1. Open G Hub
2. Quit AdGuard 
3. Reopen AdGuard

This issue may happen immediately or after a while. If the issue won't happen. Sleep your Mac and wake it up and see.

### Expected behavior
Both G Hub and AdGuard should work normally.

### Actual behavior
G Hub and AdGuard uses a lot of CPU, about 50%-60% each. Besides, the memory usage of AdGuard increases some MBs every seconds.

Quit either of the apps will stop the high CPU usage. A workaround is to add "Logitech G Hub" app to the filter app list and explicitly ask AdGuard not to filter it.

I didn't let G Hub to send feedbacks, so the only network related to internet should be autoupdate on itself or the firmware of the mouse.

<details><summary>Screenshot:</summary>

<img width="326" alt="cpu_usage_01" src="https://user-images.githubusercontent.com/2182896/105938450-91a60380-6092-11eb-9d87-c9fad568564f.png">
<img width="326" alt="cpu_usage_02" src="https://user-images.githubusercontent.com/2182896/105938454-94a0f400-6092-11eb-9749-77789fbdc76c.png">
<img width="1347" alt="memery_leak_01" src="https://user-images.githubusercontent.com/2182896/105938504-98cd1180-6092-11eb-8d02-e343b70f7213.png">
<img width="321" alt="memory_leak_02" src="https://user-images.githubusercontent.com/2182896/105938591-9e2a5c00-6092-11eb-9958-f8b3cceaf08a.png">

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

macOS 11.1 (20C69)
AdGuard 2.5.1.928 release (CL-1.7.150)
G Hub 2020.12.9532
Logitech G304 Wireless mouse
Proxy Software: ClashX

**Comment by Chinaski1** [comment]
Hello!

Unfortunately, we are unable to catch the issue on our side.
So I would like to ask you to help us in this situation.
Here's what we need you to do:

1. Next time you notice high CPU usage. Open **Terminal** and type: `sudo /System/Applications/Utilities/Activity\ Monitor.app/Contents/MacOS/Activity\ Monitor`
2. This command will open the Activity Monitor. Search for `com.adguard.mac.adguard.network-extension`. Pay attention to the PID of the process.
3. Choose `com.adguard.mac.adguard.network-extension` the tap on **Sample** -> **Save**
4. After that type that command in the terminal: `kill -6 PID` for example `kill -6 1123`
5. You will receive a [notification](https://uploads.adguard.com/Chinaskiblrfp.png) that there has been a failure in the AdGuard application.
6. Enter your email address and attach a link to this GitHub task in the description.

**Comment by Chinaski1** [comment]
One more user faced a similar issue: 2237558

**Comment by owenzhao** [comment]
> Hello!
> 
> Unfortunately, we are unable to catch the issue on our side.
> So I would like to ask you to help us in this situation.
> Here's what we need you to do:
> 
> 1. Next time you notice high CPU usage. Open **Terminal** and type: `sudo /System/Applications/Utilities/Activity\ Monitor.app/Contents/MacOS/Activity\ Monitor`
> 2. This command will open the Activity Monitor. Search for `com.adguard.mac.adguard.network-extension`. Pay attention to the PID of the process.
> 3. Choose `com.adguard.mac.adguard.network-extension` the tap on **Sample** -> **Save**
> 4. After that type that command in the terminal: `kill -6 PID` for example `kill -6 1123`
> 5. You will receive a [notification](https://uploads.adguard.com/Chinaskiblrfp.png) that there has been a failure in the AdGuard application.
> 6. Enter your email address and attach a link to this GitHub task in the description.

Email sent!

**Comment by owenzhao** [comment]
Just installed the latest `2.5.2.949 release (CL-1.7.189)`. The memory leaks still exists, but quietly. I have to quit and restart AdGuard everyday to free memory.

**Comment by Chinaski1** [comment]
@owenzhao 

Unfortunately, I can't find your crash report sent a few days earlier.
I would like to ask you to send an email to support@adguard.com 

AdGuard -> Gear -> Support -> specify your email and don't forget to enable "Attach a diagnostic report to this massage".

This way we can get the information we need to find your report.

**Comment by owenzhao** [comment]
> @owenzhao
> 
> Unfortunately, I can't find your crash report sent a few days earlier.
> I would like to ask you to send an email to [support@adguard.com](mailto:support@adguard.com)
> 
> AdGuard -> Gear -> Support -> specify your email and don't forget to enable "Attach a diagnostic report to this massage".
> 
> This way we can get the information we need to find your report.

I have to say if you didn't get my mail you shouldn't tell me after 18 days. Maybe 3 days was enough.

I used the method that AdGuard app provide to sent the email. And you didn't get the email. So I think I will be stupid to sent it by it again. 

I think the method inside AdGuard lacks the most important ability, the response. If the mail is successfully delivered. AdGuard should give me an ID of the issue ticked. So I could mentioned it here. And you will be easier to search.

This time I will send the email by Gmail directly.

**Comment by owenzhao** [comment]
Sent.

<img width="592" alt="adguard_issue" src="https://user-images.githubusercontent.com/2182896/108994450-c5e30300-76d6-11eb-9845-19db43c2b026.png">

**Comment by Chinaski1** [comment]
Thank you for sending the second email, we were able to find your crash report with it.

**Comment by owenzhao** [comment]
Here are two new screenshots for the latest stable AdGuard. One is at 9:59 a.m yesterday, AdGuard was just launched. The other was at 8:02 a.m today. So in less than 24 hours, AdGuard's memory usage was increased from 55.2MB to 3.27GB.

However, the system in total is sooth, only the memory is leaking.

<img width="1322" alt="截屏2021-02-24 上午9 59 21" src="https://user-images.githubusercontent.com/2182896/109083244-7df8c600-7740-11eb-8527-7e0588cd9c55.png">

<img width="1481" alt="截屏2021-02-25 上午8 02 19" src="https://user-images.githubusercontent.com/2182896/109083252-8224e380-7740-11eb-99e0-68099b14554b.png">

macOS Big Sur 11.2.1 (20D74)
AdGuard 2.5.2.949 release (CL-1.7.189)

**Comment by owenzhao** [comment]
> Thank you for sending the second email, we were able to find your crash report with it.

I got an auto reply from AdGuard with a ticked id after sending the feedback email by Gmail. However, when sending feedback with AdGuard app, no auto reply was got from AdGuard. I did a search with Gmail and found that in old times, sending feedbacks using AdGuard app should also got auto replies every time. But it doesn't work any more now. Maybe you should check on it too.

**Comment by Chinaski1** [comment]
@owenzhao 

Unfortunately, the crash report you sent earlier does not contain the information needed to find the issue.
Next time you notice that the CPU load has increased, just kill the process `com.adguard.mac.adguard.network-extension`
After that, a window asking you to send a crash report will pop up automatically.
Specify your email and let us know that you sent the report in this task.
No further information is needed.


1. Next time you notice high CPU usage. Open **Terminal** and type: `sudo /System/Applications/Utilities/Activity\ Monitor.app/Contents/MacOS/Activity\ Monitor`
2. This command will open the Activity Monitor. Search for `com.adguard.mac.adguard.network-extension`. Pay attention to the PID of the process.
3. Choose `com.adguard.mac.adguard.network-extension` the tap on **Sample** -> **Save**
4. After that type that command in the terminal: `kill -6 PID` for example `kill -6 1123`
5. You will receive a [notification](https://uploads.adguard.com/Chinaskiblrfp.png) that there has been a failure in the AdGuard application.
6. Enter your email address and attach a link to this GitHub task in the description.

Thanks in advance.

**Comment by owenzhao** [comment]
> @owenzhao
> 
> Unfortunately, the crash report you sent earlier does not contain the information needed to find the issue.
> Next time you notice that the CPU load has increased, just kill the process `com.adguard.mac.adguard.network-extension`
> After that, a window asking you to send a crash report will pop up automatically.
> Specify your email and let us know that you sent the report in this task.
> No further information is needed.
> 
> 1. Next time you notice high CPU usage. Open **Terminal** and type: `sudo /System/Applications/Utilities/Activity\ Monitor.app/Contents/MacOS/Activity\ Monitor`
> 2. This command will open the Activity Monitor. Search for `com.adguard.mac.adguard.network-extension`. Pay attention to the PID of the process.
> 3. Choose `com.adguard.mac.adguard.network-extension` the tap on **Sample** -> **Save**
> 4. After that type that command in the terminal: `kill -6 PID` for example `kill -6 1123`
> 5. You will receive a [notification](https://uploads.adguard.com/Chinaskiblrfp.png) that there has been a failure in the AdGuard application.
> 6. Enter your email address and attach a link to this GitHub task in the description.
> 
> Thanks in advance.

Just sent the crash report by AdGuard. I wanted to save the crash report but there was no way to export it. Also sent the Sample by Gmail.

<img width="1161" alt="截屏2021-03-02 下午7 37 26" src="https://user-images.githubusercontent.com/2182896/109643306-01764500-7b8f-11eb-83b5-b340864ce2b9.png">

**Comment by akmLaVx** [comment]
Received logs from @owenzhao. Helpdesk ID 2291816

**Comment by sfionov** [comment]
@owenzhao

Can you please try this and say if it helps?

1) Go to AdGuard icon -> Settings icon -> Advanced -> Advanced settings
2) Add 127.0.0.1 to network.extension.route.exclude setting

**Comment by owenzhao** [comment]
> @owenzhao
> 
> Can you please try this and say if it helps?
> 
> 1. Go to AdGuard icon -> Settings icon -> Advanced -> Advanced settings
> 2. Add 127.0.0.1 to network.extension.route.exclude setting

Set and see.

<img width="912" alt="截屏2021-03-04 下午10 18 23" src="https://user-images.githubusercontent.com/2182896/109977255-99af2e00-7d37-11eb-8ab8-f586da52a0bb.png">

**Comment by owenzhao** [comment]
Unfortunately, the issue still happened when after "127.0.0.1 to network.extension.route.exclude setting".

By the way, when the issue happened. You can click the "G Hub"'s icon on the system menu bar, the app would be launched. When it started, there was an animation for starting up, the animation wouldn't stop until the mouse was connected. The magic was, when the device was connected, the high CPU usage would stop and everything would be back to normal.

My theory is that somehow AdGuard blocked certain network activities that "G Hub" uses. But it may not the local connection. Maybe it is the autoupdating progress or others. 

In my own test, if I have disabled all settings in "G Hub" settings that related to networks, like "sharing data with Logitech", "Send back bug report automatically", "update checking", "ARX Control". Then restart both AdGuard and "G Hub", the high CPU usage issue won't happen. However, within 24 hours, the memory usage of AdGuard will increase to over 3 GB. I don't know why the memory leaking still exists. But I am sure it still because of something between "G Hub" and AdGuard. As if I quit "G Hub" and use the settings saving on the mouse, there will be no memory leaking of AdGuard.

**Comment by sfionov** [comment]
@owenzhao Thank you for testing. Can you please try, next time it happens, open Console app, set filter to "network-extension", start logging, and see in the log any connections from lghub? AdGuard's network extension receives info about connection and rejects to intercept them if they are not in filtered list - what may be simpler? But there may be leak in Apple's code handling non-intercepted connections.

If such connections are there, you may discover more ips and domains to exclude in advanced settings.

**Comment by owenzhao** [comment]
Upgraded to AdGuard 2.5.3.955 release (CL-1.7.200) after my testing yesterday.

<img width="732" alt="截屏2021-03-06 上午10 28 45" src="https://user-images.githubusercontent.com/2182896/110226976-78fcf900-7f2e-11eb-996b-7552239cf101.png">

It was something that was not logged fixed this issue.

In [another thread](https://github.com/AdguardTeam/AdguardForMac/issues/842), @sfionov told me that 

> We slightly changed exclusions scheme in CL1.7.200 to not to filter localhost by default, but supporting ShadowSocks*/ClashX proxies.

> Now localhost is excluded by default. However, system proxies' host:port will be filtered. But if 127.0.0.1 is in network.extension.route.exclude, it will be forced to exclude, and that's your case.

So I will close this comment with my theory. 

<img width="1913" alt="截屏2021-03-06 上午9 29 22" src="https://user-images.githubusercontent.com/2182896/110226832-3f77be00-7f2d-11eb-9508-6873b5efeef7.png">

### Above was the Console log that both Logitech G Hub app and AdGuard took high CPU usage.

<img width="1913" alt="截屏2021-03-06 上午9 36 15" src="https://user-images.githubusercontent.com/2182896/110226834-48688f80-7f2d-11eb-9a57-8c15d6eadbbe.png">

### Above was the Console log that after the high CPU usage.

## My thoery
As we could see from both of the logs, there were many AdGuard blocking events. Each of them was started from "Flow ID is connecting" and shown in the next 5 lines. 

#### The differences
1. With high CPU usage, the port of localhost was fixed with 9010. I didn't know if it must be 9010, but it was fixed. While, with low CPU usage, the port was self-increased each time. There was a 20346 port, but it was from Xcode and we should ignore it.
2. With high CPU usage, the blockings on the log screenshot were bursted all in one second. While with low CPU usage, the blockings appeared every second. That explained why the memory was still leaking even without high CPU usage.

So the issue was AdGuard blocked what it shouldn't and G Hub was always trying to get another connection after each blocking. When a Mac was waken from sleep, the connections G Hub created were in a burst, that caused the high CPU usage and the memory leaking. When G Hub was brought to front the connections it created were more smooth, so high CPU usage was gone but the memory was still leaking.

However, if the theory was true. Why the method that @sfionov provided, "add 127.0.0.1 to network.extension.route.exclude", didn't work? It must be a bug of AdGuard 2.5.949. As according to the issue [Setting "network.extension.route.exclude" to "127.0.0.1" Stops AdGuard from Blocking Ads in Safari](https://github.com/AdguardTeam/AdguardForMac/issues/842), if the setting took effect, Ads blocking should be stopped in my Mac.

## Conclusion
The unmetioned slight change fixed this issue. Now AdGuard no longer tries to block the connection with 127.0.0.1 with G Hub.
