### ISSUE TITLE
Fix settings UI

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#819]
Sorry guys but the settings UI is a completely mess. It's confusing and looks squeezed. Every page has a different UI/window size you should work on an uniform solution.

<img width="1034" alt="Bildschirmfoto 2021-02-01 um 11 09 05" src="https://user-images.githubusercontent.com/4127356/106444507-26877300-647e-11eb-8996-151e847e9d91.png">
<img width="562" alt="Bildschirmfoto 2021-02-01 um 11 09 20" src="https://user-images.githubusercontent.com/4127356/106444517-29826380-647e-11eb-872a-f27ece969ea0.png">
<img width="686" alt="Bildschirmfoto 2021-02-01 um 11 06 22" src="https://user-images.githubusercontent.com/4127356/106444499-238c8280-647e-11eb-8ed8-ce597015c1c4.png">

At the moment I'm looking for an option to set the filter update rate, but I can't find it and I'm not sure if AdGuard for Mac has one.

**Comment by Chinaski1** [comment]
Hello there!

I'm glad to inform you that we have already fixed this problem in the Nightly version. It will be added to the release soon.
You can update to the Nightly version by following this link: agrd.io/mac_nightly
