### ISSUE TITLE
Adguard won't start on a 64-bit system

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#82]
I have a 64bit system and its still not working.

state:
<details>
Application version: 1.2.0
Applicaton shared support folder:/Library/Application Support/com.adguard.Adguard
Applicaton support folder:/Users/Jan/Library/Application Support/com.adguard.Adguard
Filtration Enabled
Filtration mode: direct
Blocked: 5
Application lifetime: 2015-12-15 06:10:29 +0000
Platform: Mac OS X
OS: 1010
Locale: en

Antibanner filter: Enabled
Antiphishing filter: Enabled
Parental control: Disabled
Privacy protection: Enabled
HTTPS: Enabled
Assistant: Enabled
Web of trust: Enabled
Popup blocker: Enabled

Filters subscriptions:
ID=0 Name="User filter" Version=1.0.0.0
ID=2 Name="English filter" Version=1.0.80.74
ID=3 Name="Spyware filter" Version=1.0.5.20
ID=5 Name="Experimental filter" Version=1.0.24.68
ID Name="Filter for useful ads" Version=1.0.0.84
ID Name="Safari Filter" Version=1.0.0.50
ID 7 Name="Adblock Warning Removal List" Version=1.0.55.35
ID!1 Name="Anti-Adblock Killer | Reek" Version=1.0.1.59

SSL exception domains:
plimus.com
payproglobal.com
avangate.com
paypal.com
halifax-online.co.uk
identity.virginmedia.com
signin.ebay.com
signin.ebay.co.uk
icbc.com.cn
hsbc.co.uk
hsbc.com
secure.hsbcnet.com
bv-activebanking.de
hsbc.ca
hsbc.com.au
chase.com
secure.bnpparibas.net
bnpparibasfortis.be
webbanking.bgl.lu
secure.bnl.it
barclays.co.uk
bankofamerica.com
deutsche-bank.de
deutsche-bank.es
deutsche-bank.it
deutsche-bank.pt
db-pbc.pl
db.com
qweb.quercia.com
citibank.com
wellsfargo.com
societegenerale.fr
societegenerale.com
sgeb.bg
rbsinternational.com
sberbank.ru
alfabank.ru
zakupki.gov.ru
194.105.148.87
aus.mozilla.org
aus1.mozilla.org
aus2.mozilla.org
aus3.mozilla.org
aus4.mozilla.org
aus5.mozilla.org
aus6.mozilla.org
addons.mozilla.org
versioncheck.addons.mozilla.org
dl.dropboxusercontent.com
lastpass.com
mozilla.org
mozilla.net
webmoney.ru
wmtransfer.com
adtidy.org
chrome.adtidy.org
eff.org
8pecxstudios.com
rbsdigital.com
commonbank.com.ua
sparkasse-fuerth.de
ing-diba.de
apple.com

</details>

PKM-945-20460

**Comment by evgeniy-ADG** [comment]
Waiting for customer's response

**Comment by evgeniy-ADG** [comment]
> reference #PKM-945-20460 I can not find the adguard.db file in that location ~/Library/Application Support/com.adguard.Adguard/adguard.db I only see 2 folders, kext and NfApiConfiguration I have uninstalled and reinstalled, but no use.

**Comment by ameshkov** [comment]
@Stillness-2 any idea?

**Comment by DenLeo** [comment]
В свойствах файла не отображается возможность запустить в 32-битном режиме

**Comment by Stillness-2** [comment]
@DenLeo Пожалуйста подробней напишите. Пока что я не понимаю о чем Вы. :)

**Comment by DenLeo** [comment]
Образ Adguard-1.2.2.beta.dmg не запускается (причина image not recognized). Думал, что можно в 32-битном режиме попробовать запустить (через свойства dmg-файла)

**Comment by Stillness-2** [comment]
@DenLeo какая версия OS X? 
От куда загружали образ, с какого сайта?

**Comment by DenLeo** [comment]
1. OS X EI Capitan  10.11.5
2. https://github.com/AdguardTeam/AdguardForMac/releases/download/v1.2.2-beta/Adguard-1.2.2.beta.dmg

**Comment by DenLeo** [comment]
Опа, у меня все заработало. Видимо недокачался образ. Все нормально!

**Comment by Stillness-2** [comment]
@DenLeo  Окей :)
