### ISSUE TITLE
AdGuard not working on macOs Big Sur 11.2 

### ISSUE THREAD

**Issue by jDomenech** [AdguardTeam/AdguardForMac#823]
### Steps to reproduce

macOs BigSur 11.2
AdGuard 2.5.1.928 

When starting adGuard after some seconds this pop-up appears:

<img width="420" alt="Captura de pantalla 2021-02-04 a las 10 03 58" src="https://user-images.githubusercontent.com/1789594/106870162-16b39d00-66d1-11eb-9c95-1462432dbc3d.png">

**Comment by Chinaski1** [comment]
Hello there!
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.

Then you should try resetting the AdGuard settings:

* Click on the AdGuard icon in the menu bar;
* Click on the gear;
* Go to Advanced;
* Click on Reset settings.

- If a reset doesn't help, reinstall the app completely using [these instructions](https://kb.adguard.com/en/macos/installation#uninstall-advanced).

**Comment by Chinaski1** [comment]
Resolved in personal conversation.
