### ISSUE TITLE
"Keep AdGuard running in the background" = "No" choice not consistently followed

### ISSUE THREAD

**Issue by djbeatroot** [AdguardTeam/AdguardForMac#824]
### Steps to reproduce

1.  Click the close/red X icon on the AdGuard window title bar.
2.  A dialog box appears with a "Keep AdGuard running in the background?" question.
3.  Select the "Remember my choice" checkbox.
4.  Click the "No" button.

### Expected behavior

AdGuard should follow the "Remember my choice" = "No" selection every time the window is closed.
There should also be a way to view and change that selection in the settings window.
### Actual behavior

AdGuard honors the "Remember my choice" = "No" selection only the first time the window is closed.  In subsequent sessions, AdGuard stays running after the window is closed.  There is no visible way to view or change this selection.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)
macOS Big Sur 11.2
Safari 14.0.3

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdGuardForSafari #526](https://github.com/AdguardTeam/AdGuardForSafari/issues/526) via [**ZenHub**](https://www.zenhub.com/)
