### ISSUE TITLE
blocking third-party authorization header breaks aws console

### ISSUE THREAD

**Issue by kaznovac** [AdguardTeam/AdguardForMac#829]
this is not a bug report, it's an unexpected behaviour (took me some network digging to see what's wrong) that has a workaround (maybe the whitelist should be distributed with application)

### Steps to reproduce
1. turn on the third-party authorization header blocking in stealth mode tracking methods
2. visit some pages in aws console requiring user roles e.g. https://console.aws.amazon.com/codesuite/codestar/projects

### Expected behavior
page opens as expected

### Actual behavior
error message is displayed

### Workaround
whitelist the `console.aws.amazon.com`

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdguardFilters #74518](https://github.com/AdguardTeam/AdguardFilters/issues/74518) via [**ZenHub**](https://www.zenhub.com/)
