### ISSUE TITLE
Adguard cannot detect HTML if there is an xml declaration at the document start

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#83]
Source:
https://github.com/AdguardTeam/AdguardForWindows/issues/1011

Review ID:
CR-AG-745

**Comment by Stillness-2** [comment]
CR-AG-753

**Comment by ameshkov** [comment]
The problem still exists for oper.ru.
CR-AG-759

**Comment by Stillness-2** [comment]
CR-AG-760
