### ISSUE TITLE
Setting "network.extension.route.exclude" to "127.0.0.1" Stops AdGuard from Blocking Ads in Safari

### ISSUE THREAD

**Issue by owenzhao** [AdguardTeam/AdguardForMac#842]
### Steps to reproduce

1. AdGuard icon -> Settings -> Advanced -> Advanced Settings
2. Add 127.0.0.1 to network.extension.route.exclude
3. quit Safari and reopen Safari
4. open a webpage with ads

### Expected behavior

Ads should be filtered.

### Actual behavior

Ads show.

<details><summary>Screenshot:</summary>

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59):
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

AdGuard 2.5.3.955 release (CL-1.7.200)
ClashX 1.40.0 with Trojan Proxy Enabled
http/https/socked5 proxy to: 127.0.0.1:7890 in WiFi Settings.

Safari 14.0.3 (16610.4.3.1.4)
macOS Big Sur 11.2.2 (20D80)
iMac 5K 2014 late

**Comment by sfionov** [comment]
@owenzhao We slightly changed exclusions scheme in CL1.7.200 to not to filter localhost by default, but supporting ShadowSocks*/ClashX proxies.

Now localhost is excluded by default. However, system proxies' host:port will be filtered. But if 127.0.0.1 is in `network.extension.route.exclude`, it will be forced to exclude, and that's your case.

**Comment by owenzhao** [comment]
> @owenzhao We slightly changed exclusions scheme in CL1.7.200 to not to filter localhost by default, but supporting ShadowSocks*/ClashX proxies.
> 
> Now localhost is excluded by default. However, system proxies' host:port will be filtered. But if 127.0.0.1 is in `network.extension.route.exclude`, it will be forced to exclude, and that's your case.

Thank you.

I encountered this issue while I was testing another issue. [Memory Leaks with High CPU Usage](https://github.com/AdguardTeam/AdguardForMac/issues/818)

Now I am probably sure the latter issue was fixed by AdGuard 2.5.3.955. I will be sure tomorrow morning. Then I will write what I have observed in that thread.
