### ISSUE TITLE
Proxifier and Adguard: if together big connection problem

### ISSUE THREAD

**Issue by michael1900** [AdguardTeam/AdguardForMac#843]
Ok i have already tried all here: https://kb.adguard.com/en/macos/solving-problems/big-sur-issues

**Obviously if i simply disable Adguard, Proxifier and web surfing work perfectly again.**

I am on Catalina. Tried both Extension mode and Proxy mode.

This is the important error that i have in Proxifier log when Adguard is enabled:

**127.0.0.1:52278 error : Could not connect through proxy xx.xxx.xxx.77:9999 - Proxy server cannot establish a connection with the target - Connection refused**

In Advanced setting in Adguard:

upstream.proxy                             --->         socks5://localhost:52278
upstream.proxy.socks5udp         --->          true

Adguard is on last nightly version, Proxifier is last Catalina version.

Please help!

**Comment by ameshkov** [comment]
Hmm, could it be that Proxifier tries to proxy AdGuard itself and they somehow go into an infinite loop?

**Comment by michael1900** [comment]
> Hmm, could it be that Proxifier tries to proxy AdGuard itself and they somehow go into an infinite loop?

The only app that i have choosen to proxifier is Safari. AdGuard is out from this, it use direct connection.
So how can i fix this problem?

**Comment by ameshkov** [comment]
Could you please first explain how the problem looks like when AdGuard simply uses the default settings?

I reckon, there is simply no filtering by AG, right?

**Comment by michael1900** [comment]
If i unflag all lists and turn off all privacy/protecion setting nothing changes. Always the same error posted above :(

**Comment by ameshkov** [comment]
@michael1900 even when `Advanced setting` are empty in AdGuard?

**Comment by michael1900** [comment]
> Could you please first explain how the problem looks like when AdGuard simply uses the default settings?

If i unflag all lists and turn off all privacy/protecion setting nothing changes. Always the same error posted above :(

> I reckon, there is simply no filtering by AG, right?

With Proxifier enabled obviously there is no web surfing possible due error above, with Proxifier disabled and all lists disabled, etc, there is no filtering like normal to be i think.

**Comment by michael1900** [comment]
> @michael1900 even when `Advanced setting` are empty in AdGuard?

no changes, always the same error with all AdGuard lists disabled and Advanced setting like default/empty: 

127.0.0.1:52278 error : Could not connect through proxy xx.xxx.xxx.77:9999 - Proxy server cannot establish a connection with the target - Connection refused

**Comment by ameshkov** [comment]
Did you have this issue with the previous AG version or is it new?

As a temp solution, please try the following:
1. Settings - Network - Applications...
2. Uncheck Safari there
3. Add "Proxifier" as a filtered app

**Comment by michael1900** [comment]
> Did you have this issue with the previous AG version or is it new?
> 
> As a temp solution, please try the following:
> 
> 1. Settings - Network - Applications...
> 2. Uncheck Safari there
> 3. Add "Proxifier" as a filtered app

Done. But web surfing doesn't work the same. The error is slighty different:

com.apple.WebKit.Networking - 127.0.0.1:52278 error : Could not connect through proxy 23.105.131.156:9999 - Reading proxy reply on a connection request failed with error 54

Obviously if i disable AdGuard all works.

**Comment by ameshkov** [comment]
Weird stuff. We'll try to repro it on our side and see what's this about: https://www.proxifier.com/

**Comment by michael1900** [comment]
> Weird stuff. We'll try to repro it on our side and see what's this about.
> 
> It's this app, right? https://www.proxifier.com/
> 
> CC @AdguardTeam/qa-team

Yes Sir!  Thanks for help. I need so much of this app and AdGuard too. Hope you can fix this.

**Comment by michael1900** [comment]
I think to have solved it thanks to help from **Vladimir Borisov**, Developer and Staff in Proxifier.

The right configuration is this:

<img width="837" alt="Schermata 2021-03-10 alle 13 59 19" src="https://user-images.githubusercontent.com/1675875/110633675-56c2df80-81a9-11eb-86f9-d0bb32fcac0d.png">

**Comment by michael1900** [comment]
> I think to have solved it thanks to help from **Vladimir Borisov**, Developer and Staff in Proxifier.
> 
> The right configuration is this:
> 
> <img alt="Schermata 2021-03-10 alle 13 59 19" width="837" src="https://user-images.githubusercontent.com/1675875/110633675-56c2df80-81a9-11eb-86f9-d0bb32fcac0d.png">

Localhost need to be place to the top and only now AdGuard can be Proxified **WITHOUT** errors.

Thanks @ameshkov also for help.

**Comment by michael1900** [comment]
Errata corridge: not really solved. 

From Vladimir Borisov: 

_Hello,

Glad to hear that the issue is solved.
But you should know that **because all connections routed over adguard the Proxifier probably will process the connections that was originally created by other browsers and applications but not only Safari**.

Regards,
Vladimir,
Proxifier Support_

This is not good. Is there a solution to this? Now it's working like a VPN, i don't want this.

**Comment by michael1900** [comment]
From Vladimir Borisov :

> Hello,
> 
> Sorry but there is no good solution for this issue.
> By design adguard mix all connections and thus the original application name cannot be recovered.
> In your case you can use only hostname and port in rules.
> 
> Vladimir,
> Proxifier Support
>

**Comment by ameshkov** [comment]
@michael1900 since you just want to use NordVPN in your browser, why don't you use `upstream.proxy` in AdGuard and configure it to use NordVPN proxy directly?

**Comment by michael1900** [comment]
> @michael1900 since you just want to use NordVPN in your browser, why don't you use `upstream.proxy` in AdGuard and configure it to use NordVPN proxy directly?

I prefer to use Proxifier, it's most usable in many ways. Btw thanks for all help ;)

**Comment by Chinaski1** [comment]
Due to traffic filtering methods used in AdGuard and Proxifier, it is impossible to determine application in Proxifier when AdGuard protection is on. However, they may still be used together without application detection, if localhost exclusion rule is on top of rule list.
We're closing this issue because it is not fully resolvable, and Proxifier already have compatibility workaround for this in default rule list.

**Comment by red-crate** [comment]
I am still experiencing this exact same issue with Proxifier 4.14 and AdGuard for Windows 7.22.7.
There seems to be no workaround at all.
