### ISSUE TITLE
Enhance the Safebrowsing

### ISSUE THREAD

**Issue by Macqael** [AdguardTeam/AdguardForMac#845]
Use the same method as Windows for the safebrowsing.

See this doc to understand what i mean by use the same as windows for mac : https://kb.adguard.com/en/general/how-malware-protection-works#desktop

**Comment by sfionov** [comment]
Work is in progress, you may track it here: https://github.com/AdguardTeam/CoreLibs/issues/891

It is expected to be delivered in Q2 2021.

**Comment by Macqael** [comment]
@sfionov Thanks for the answer

**Comment by Chinaski1** [comment]
I will close this task as it is a duplicate.
Thank you for providing the idea :)
