### ISSUE TITLE
Adguard not workin on startup - MacOS 11.2.3 - Macpro 5,1

### ISSUE THREAD

**Issue by evasilis** [AdguardTeam/AdguardForMac#847]
Hi all,

I have been facing this issue for quite sometime now: If adgaurd is set to launch at login, several times it reports that it hasn't started properly and appears turned off. What I need to do is turn it on, quit and launch it again. In this way it works without a hitch. However, if I set adguard not to launch at login and launch it manual my self after booting has finished, everything seems to work fine. I have contacted support, sent them adguard's logs as well as the console related entries but they replied they cannot reproduce the error. It is my suspicion that, if set on automatic launch, adguard, sometimes, launches too early, hence the error.

Has anyone experienced that? Any ideas?

Currently running 2.5.3.955 nightly (CL-1.7.200)

Thanks

**Comment by Chinaski1** [comment]
@evasilis 

Hello there!

Please specify your helpdesk ID so I can find your log files to investigate the issue.

**Comment by Chinaski1** [comment]
Unfortunately, without clarifying this information, I am unable to find your support request.

**Comment by evasilis** [comment]
Hi Konstantin

Unfortunately I cannot find the information you require. I am going to get the error to reproduce and send you a new set of logs and console entries

Thanks for your help!
V

**Comment by evasilis** [comment]
Hi there

I am sending you afresh set of logs after adguard failed to initialise and also the console entries which are:

Apr  1 10:30:22 doudou com.apple.xpc.launchd[1] (com.apple.xpc.launchd.user.domain.501.100006.Aqua): Could not import service from caller: caller = otherbsd.340, service = com.adguard.mac.adguard.loginhelper, error = 119: Service is disabled
Apr  1 10:30:47 doudou AdGuard Assistant[640]: BUG in libdispatch client: vnode, monitored resource vanished before the source cancel handler was invoked { 0x6000005fa600[source], ident: 4 / 0x4, handler: 0x10a86f95d }
Apr  1 10:31:05 doudou Adguard[612]: BUG in libdispatch client: vnode, monitored resource vanished before the source cancel handler was invoked { 0x600000c77e80[source], ident: 6 / 0x6, handler: 0x10e278173 }

Thanks

**Comment by Chinaski1** [comment]
Please send the received log file to devteam@adguard.com

**Comment by Chinaski1** [comment]
I close this task because there was no response from the user.
Reopen it if the issue is still reproduced.

**Comment by evasilis** [comment]
Hi

I forwarded the issue to the dev team as you suggested but I had no reply yet.

**Comment by Chinaski1** [comment]
I can't find it. Please specify the date and time the email was sent.
