### ISSUE TITLE
Support all HTTP methods (specifically REPORT)

### ISSUE THREAD

**Issue by pospischil** [AdguardTeam/AdguardForMac#85]
Adguard blocks all HTTP requests with method REPORT.  

This is a rare, but valid HTTP method used to circumvent GET request query string limits.

**Comment by ameshkov** [comment]
Some info about REPORT method:
https://tools.ietf.org/html/rfc3253#section-3.6
This is WebDAV HTTP method. As all WebDAV methods it is supposed to have a request body.

**Comment by ameshkov** [comment]
@pospischil any idea where we can test it?

**Comment by pospischil** [comment]
Unfortunately we encountered it on an app that requires authentication, but I believe dropbox makes use of the REPORT method as well.

**Comment by pospischil** [comment]
I take that back, they do not unfortunately.  You should be able to submit a REPORT request to any local web server though.

**Comment by ameshkov** [comment]
I see that all webdav methods are processed similarly in Adguard, report just was not listed there.
So I guess it's enough to test any other webdav methods.

Here is a public webdav server:
http://www.ajaxfilebrowser.com/

**Comment by Stillness-2** [comment]
commit 25283
