### ISSUE TITLE
Issues with running kext

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#853]
- OS version: Versions 10.14.6 (Build 18G8022) / 10.15.7 (assemblage 19H524)
- AdGuard Versions: 2.5.3.955 release (CL-1.7.200) / 2.5.3.955 nightly (CL-1.7.200)
- 2021/03/22 19:42:01:929  (AASKextManager[0x600002858420] callLoadKext) Error loading kext
- Application and system log are attached to the task
- CRM ID: 2059922 / 3256502

**Comment by Eugene-Savenko** [comment]
Another one: 1731340

**Comment by Eugene-Savenko** [comment]
The same here: 502239

> 2021/04/11 11:15:27:720  (AASKextManager[0x6000000e3510] callUnloadKext) Error unloading kext.
