### ISSUE TITLE
AdGuard Big Sur VPN + DNS Profile Mode breaks my internet

### ISSUE THREAD

**Issue by dalisoft** [AdguardTeam/AdguardForMac#855]
### Steps to reproduce

1. Download any DNS profile on system and Run it (NextDNS profile in my case)
2. Download AdGuard on Big Sur
3. Run it
4. Try to login my.adguard.com
5. See error

### Expected behavior

When enabled, I see error for page loading

<img width="1680" alt="Снимок экрана 2021-04-11 в 11 35 36" src="https://user-images.githubusercontent.com/3511344/114294767-2927c980-9aba-11eb-9fd0-e38592cb4be0.png">

### Actual behavior

With disabled, I see actual behavior

<img width="1680" alt="Снимок экрана 2021-04-11 в 11 35 12" src="https://user-images.githubusercontent.com/3511344/114294770-2f1daa80-9aba-11eb-8145-1a6c91150442.png">

### Your environment

* Environment name and version: M1 MacBook Pro (Big Sur) latest
* Any specific potentially conflicting software installed: nextdns, macOS firewall

**Comment by Chinaski1** [comment]
Hello there!

I try to reproduce the issue using specified configurations but it does not reproduce on my side.
Please try another DNS server, will the situation repeat itself?

**Comment by dalisoft** [comment]
@Chinaski1 Hi

Thanks for reply and yes, any DNS profile on macOS Big Sur with AdGuard VPN becomes unusable

**Comment by Chinaski1** [comment]
Please specify the version of the Safari browser and the version of AdGuard VPN.

**Comment by dalisoft** [comment]
Sorry, I mean the AdGuard Ad blocked as VPN Profile on Big Sur.
Safari version is 14.0.3 (16610.4.3.1.7)

**Comment by Chinaski1** [comment]
Also not reproduced in this combination.

**Comment by Chinaski1** [comment]
Try to open the Developer Console (Network tab) and send a screenshot of that tab before logging in to your Personal Account.

**Comment by dalisoft** [comment]
I am not sure then, for me it is breaks more pages than expected, the pages like google.com works, but some pages like AdGuard doesn't, it's maybe due of TLS/SSL issue?!

**Comment by dalisoft** [comment]
I'm tried now, but now not connecting at all, so using NextDNS app (VPN mode) + AdGuard (as VPN profile) + LuLu (as VPN profile).
Now works good, but issue can't reproduce as before, now connection fails

**Comment by Chinaski1** [comment]
Maybe you blocked access to a resource using the Lulu VPN.
I've tried the combination you mentioned, but I haven't encountered any issues.

**Comment by dalisoft** [comment]
Can you please generate config for your device and install https://apple.nextdns.io?

**Comment by dalisoft** [comment]
I sure LuLu doesn't blocks because I use LuLu for just monitoring

**Comment by dalisoft** [comment]
If there any solutions like NextDNS from AdGuard (within app) could be great and I'd use from AdGuard, currently no idea how to bypass this bug 😔

**Comment by dalisoft** [comment]
I didn't tried as i decided turn off NextDNS on macOS for privacy reasons. But may we close this as for me it's not need anymore.
Of course, on Catalina with older kernel extension (or somewhat) worked better than my current Big Sur as DNS solution
