### ISSUE TITLE
Editing a whitelist causes a crash application 

### ISSUE THREAD

**Issue by Chinaski1** [AdguardTeam/AdguardForMac#860]
### Steps to reproduce

1. Open the AdGuard app
2. Gear -> Preferences -> General
3. Attempting to whitelist a domain causes the application to crash

- AdGuard version:  2.5.4.960 nightly (CL-1.7.211)
- OS version: 11.2.3 (20D91) / Apple M1

**Comment by AdamWr** [comment]
I have the same problem when I want to add a new rule or search a rule in the filter editor (Preferences - Filters).
AdGuard 2.5.4.960 nightly (CL-1.7.211)
