### ISSUE TITLE
Local proxies are not filtered on macOS 11.3

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#862]
Application version 2.5.3.955 release (CL-1.7.200)

this version can not load adguard on brower

**Comment by Chinaski1** [comment]
Hello @spacexnasa 

Please describe your issue in more detail.
Are ads not filtered out in the browser or is the app not running?

**Comment by spacexnasa** [comment]
> Hello @spacexnasa
> 
> Please describe your issue in more detail.
> Are ads not filtered out in the browser or is the app not running?

ads not filter,and the app can running ,i checked the debug log,find nothing

**Comment by Chinaski1** [comment]
Is the issue only reproduced in a particular browser?
You should check the security certificate (Click on Lock -> Certificate) is it AdGuard CA?
Also, open keychain access and try to find AdGuard CA cert.
Its Trust status must be **Always trust**. 

![image](https://user-images.githubusercontent.com/49645813/116551002-1c033b00-a900-11eb-9e62-cd603eea774b.png)

**Comment by spacexnasa** [comment]
> Is the issue only reproduced in a particular browser?
> You should check the security certificate (Click on Lock -> Certificate) is it AdGuard CA?
> Also, open keychain access and try to find AdGuard CA cert.
> Its Trust status must be **Always trust**.
> 
> ![image](https://user-images.githubusercontent.com/49645813/116551002-1c033b00-a900-11eb-9e62-cd603eea774b.png)

ok,thanks for your reply,i will check tomorrow.

**Comment by spacexnasa** [comment]
now ,can only work with  upstream.proxy and change the Filtering mode  Automatic Proxy

**Comment by Jax0rz** [comment]
same here.

**Comment by Jax0rz** [comment]
VPN and proxy mod can't work with macOS 11.3

**Comment by ameshkov** [comment]
What other network filtering apps do you have?

**Comment by cmkw** [comment]
> What other network filtering apps do you have?

clashx won't work with adgaurd in MacOS 11.3

**Comment by Chandler-Lu** [comment]
> Good news everyone!
> 
> We found a temporary solution to the issue.
> 
> Available in the Nightly version of AdGuard for macOS: https://agrd.io/mac_nightly

Thanks for update. It works on macOS 11.3.

**Comment by spacexnasa** [comment]
> > Good news everyone!
> > We found a temporary solution to the issue.
> > Available in the Nightly version of AdGuard for macOS: https://agrd.io/mac_nightly
> 
> Thanks for update. It works on macOS 11.3.

worked,thanks

**Comment by ameshkov** [comment]
@Chinaski1 please don't forget to update the Knowledge base.

**Comment by Chinaski1** [comment]
@ameshkov Already done :)

**Comment by ameshkov** [comment]
@Chinaski1 could you please re-test it on v11.3.1? Is it still an issue?

**Comment by ngorskikh** [comment]
@ameshkov FB9093112 reported on 30.04.2021, no response so far
Forum post: https://developer.apple.com/forums/thread/680190

**Comment by ameshkov** [comment]
@ngorskikh well, Matt seems to be responsive there.

I suppose we should also let him (and other devs that are in FB) know what temporary solution we're using. Maybe they'll advise something, for instance how stable this solution would be.

**Comment by mrouben** [comment]
Hi there, I have purchased AdGuard Pro which seems to have issues with every MacOS update. The nightly version worked great but the trial period expired. My AppleID doesn't work to activate the nightly version. Are these separate products? Is there a way to activate the nightly build/refresh the trial period?

Thanks

**Comment by ameshkov** [comment]
@mrouben so here's the thing, if you purchased AdGuard on our website, then the license is cross-platform.

If you did it on App Store, than it's not, the purchase there is only for iOS version, hence the price which is considerably lower.

**Comment by mrouben** [comment]
> @mrouben so here's the thing, if you purchased AdGuard on our website, then the license is cross-platform.
> 
> If you did it on App Store, than it's not, the purchase there is only for iOS version, hence the price which is considerably lower.

@ameshkov  I see, indeed my app says "for iOS". Is it recommended to get the full version from the AdGuard website instead? 

I am now finding that AdGuard is blocking my access to crave.ca, so I tried adding the rule @@||www.crave.ca^$important,document . This had worked on the Nightly version but doesn't seem to be working now. I turned off AdGuard to confirm that it was the source of blocking Crave and when I turned AdGuard back on it said my rules could not be loaded into Safari and therefore not applied. Is this again an issue with trying to use the iOS version on MacOS?

**Comment by ameshkov** [comment]
@mrouben

Tbh, we haven't tested iOS version on MacOS.

Here's the thing, we have two different products specifically for macOS.

1. AdGuard for Safari -- a free app that blocks ads in Safari using Apple's "Safari Content Blocking API": https://github.com/AdguardTeam/AdGuardForSafari
2. AdGuard for Mac -- premium app that is not limited to Safari (or any browser fwiw) and does it's job on the network level: https://adguard.com/en/adguard-mac/overview.html

If you just need us to handle most of the ads in Safari, probably the first option should be okay and it would definitely be better than trying to run the iOS version on mac.

**Comment by mrouben** [comment]
> @mrouben
> 
> Tbh, we haven't tested iOS version on MacOS.
> 
> Here's the thing, we have two different products specifically for macOS.
> 
> 1. AdGuard for Safari -- a free app that blocks ads in Safari using Apple's "Safari Content Blocking API": https://github.com/AdguardTeam/AdGuardForSafari
> 2. AdGuard for Mac -- premium app that is not limited to Safari (or any browser fwiw) and does it's job on the network level: https://adguard.com/en/adguard-mac/overview.html
> 
> If you just need us to handle most of the ads in Safari, probably the first option should be okay and it would definitely be better than trying to run the iOS version on mac.

Thanks so much @ameshkov , this works! Appreciate it
