### ISSUE TITLE
MacBook hangs on startup because of Adguard

### ISSUE THREAD

**Issue by evgeniy-ADG** [AdguardTeam/AdguardForMac#87]
стал при каждом включении макбоок про подвисать и не могу принудительно закрыть программу. начинает греться комп приходится перезагружать полностью мак вчера переустановил прогу скачал с вашего сайта еще раз установил в итоге такая же проблема повторяется как быть?

**Comment by Stillness-2** [comment]
Попробуйде удалить папку: "/Library/Application Support/com.adguard.Adguard"

1. Закройте Adguard
2. Наберите в терминале `rm /Library/Application\ Support/com.adguard.Adguard`
3. Запустите Adguard

**Comment by Stillness-2** [comment]
Есть какой либо результат то?

**Comment by evgeniy-ADG** [comment]
нет, ждем

**Comment by Stillness-2** [comment]
ну как там?

**Comment by evgeniy-ADG** [comment]
> дравствуйте! все заработало по вашему совету! программа работает. мак не греется, работает тихо. спасибо за оперативность!

**Comment by ameshkov** [comment]
@Stillness-2 а в чем проблема была?

**Comment by Stillness-2** [comment]
@ameshkov Я думаю опять в базе сертов. Я тебе про этот странный баг рассказывал. Типа фикс в 1.2.1-beta есть.
