### ISSUE TITLE
AdGuard Assistent caused Safari to crash

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#873]
I was watching something on YouTube while Safari (14.1.1) randomly crashed on macOS Big Sur 11.4
According to the crash log the following happened:
`Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Enabled App Extensions:
com.adguard.mac.adguard.safari-assistant (TC3Q7MAJXF) (Version: 955 - Display Version: 2.5.3) AdGuard-Assistent
 
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0 (section 0 before update). The number of items contained in an existing section after the update (15) must be equal to the number of items contained in that section before the update (15), plus or minus the number of items inserted or deleted from that section (15 inserted, 8 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out). 15 inserts and 8 deletes came from client insert and delete calls. 0 rows in this section were reloaded. Before update: 3 sections. After: 3 sections.'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff2052d87b __exceptionPreprocess + 242
1   libobjc.A.dylib                     0x00007fff20265d92 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff205569e2 +[NSException raise:format:arguments:] + 88
3   Foundation                          0x00007fff21312512 -[NSAssertionHandler handleFailureInMethod:object:file:lineNumber:description:] + 191
4   UIFoundation                        0x00007fff23acfd96 -[_NSCollectionViewCore _endItemAnimationsWithInvalidationContext:tentativelyForReordering:animator:] + 13875
5   UIFoundation                        0x00007fff23ad6602 -[_NSCollectionViewCore _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:animator:] + 681
6   UIFoundation                        0x00007fff23ad6353 -[_NSCollectionViewCore _performBatchUpdates:completion:invalidationContext:tentativelyForReordering:] + 29
7   AppKit                              0x00007fff23640d5c -[NSCollectionView performBatchUpdates:completionHandler:] + 274
8   Safari                              0x00007fff43dbc98b -[StartPageCollectionViewController startPageCollectionSectionProvider:performBatchUpdates:completionHandler:] + 403
9   Safari                              0x00007fff43ebc978 __118-[StartPageCollectionViewControllerAnimator startPageCollectionSectionProvider:performBatchUpdates:completionHandler:]_block_invoke + 82
10  AppKit                              0x00007fff22ccf264 +[NSAnimationContext runAnimationGroup:] + 55
11  Safari                              0x00007fff43ebc8b0 -[StartPageCollectionViewControllerAnimator startPageCollectionSectionProvider:performBatchUpdates:completionHandler:] + 177
12  Safari                              0x00007fff43e392b2 __63-[StartPageFavoritesSectionProvider _openFolder:withAnimation:]_block_invoke + 242
13  UIFoundation                        0x00007fff23ad61c1 -[_NSCollectionViewCore _updateAnimationDidStop:finished:context:] + 2011
14  UIFoundation                        0x00007fff23ad59d5 __76-[_NSCollectionViewCore _updateWithItems:tentativelyForReordering:animator:]_block_invoke.1068 + 77
15  libdispatch.dylib                   0x00007fff2020f623 _dispatch_call_block_and_release + 12
16  libdispatch.dylib                   0x00007fff20210806 _dispatch_client_callout + 8
17  libdispatch.dylib                   0x00007fff2021cb4f _dispatch_main_queue_callback_4CF + 940
18  CoreFoundation                      0x00007fff204f05e8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
19  CoreFoundation                      0x00007fff204b27d2 __CFRunLoopRun + 2755
20  CoreFoundation                      0x00007fff204b164c CFRunLoopRunSpecific + 563
21  HIToolbox                           0x00007fff286efab3 RunCurrentEventLoopInMode + 292
22  HIToolbox                           0x00007fff286ef815 ReceiveNextEventCommon + 587
23  HIToolbox                           0x00007fff286ef5b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
24  AppKit                              0x00007fff22cb26f2 _DPSNextEvent + 864
25  AppKit                              0x00007fff22cb0ec5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
26  Safari                              0x00007fff43b49d67 -[BrowserApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 231
27  AppKit                              0x00007fff22ca3239 -[NSApplication run] + 586
28  AppKit                              0x00007fff22c7747c NSApplicationMain + 816
29  Safari                              0x00007fff43b33a70 SafariMain + 448
30  libdyld.dylib                       0x00007fff203d5f5d start + 1
31  ???                                 0x0000000000000001 0x0 + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff2038b92e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff203ba5bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff2030f411 abort + 120
3   libc++abi.dylib               	0x00007fff2037def2 abort_message + 241
4   libc++abi.dylib               	0x00007fff2036f5fd demangling_terminate_handler() + 266
5   libobjc.A.dylib               	0x00007fff2026858d _objc_terminate() + 96
6   libc++abi.dylib               	0x00007fff2037d307 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff2037d2a9 std::terminate() + 41
8   libdispatch.dylib             	0x00007fff2021081a _dispatch_client_callout + 28
9   libdispatch.dylib             	0x00007fff2021cb4f _dispatch_main_queue_callback_4CF + 940
10  com.apple.CoreFoundation      	0x00007fff204f05e8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
11  com.apple.CoreFoundation      	0x00007fff204b27d2 __CFRunLoopRun + 2755
12  com.apple.CoreFoundation      	0x00007fff204b164c CFRunLoopRunSpecific + 563
13  com.apple.HIToolbox           	0x00007fff286efab3 RunCurrentEventLoopInMode + 292
14  com.apple.HIToolbox           	0x00007fff286ef815 ReceiveNextEventCommon + 587
15  com.apple.HIToolbox           	0x00007fff286ef5b3 _BlockUntilNextEventMatchingListInModeWithFilter + 70
16  com.apple.AppKit              	0x00007fff22cb26f2 _DPSNextEvent + 864
17  com.apple.AppKit              	0x00007fff22cb0ec5 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
18  com.apple.Safari.framework    	0x00007fff43b49d67 -[BrowserApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 231
19  com.apple.AppKit              	0x00007fff22ca3239 -[NSApplication run] + 586
20  com.apple.AppKit              	0x00007fff22c7747c NSApplicationMain + 816
21  com.apple.Safari.framework    	0x00007fff43b33a70 SafariMain + 448
22  libdyld.dylib                 	0x00007fff203d5f5d start + 1`

let me know if you need the complete log or something else.

**Comment by ameshkov** [comment]
Why do you think it has anything to do with AG?

It just indicates what extensions you have enabled in Safari, the crash itself occurred in Safari.
