### ISSUE TITLE
Network Extension Mode doesn't work in macOS 12 Beta

### ISSUE THREAD

**Issue by airart320** [AdguardTeam/AdguardForMac#876]
Websites are unavailable when using Network Extension Mode, Automatic Proxy works fine.

**Comment by ameshkov** [comment]
And here we go. @ngorskikh it's time to file bug reports to Apple again :)

**Comment by MikeLdeM** [comment]
Adguard (or MacOS for that matter) is indeed borked again. Worked fine initially, but now websites won't load with AdGuard enabled.

**Comment by airart320** [comment]
Turning Private Relay off brings back Network Extension Mode.
https://github.com/AdguardTeam/AdguardForMac/issues/875#issue-913965810

**Comment by mainhathao** [comment]
Having the same issue here. Have to disable Private Relay for now.

**Comment by krishnajhaS** [comment]
I am unable to activate extension mode, even with private relay off, any thoughts? it's an M1 MBP.

**Comment by inazarab** [comment]
I'm having the same problem. I disabled private relay but that didn't work, no change to loading time.

**Comment by ameshkov** [comment]
Hi all, from our experience there's a couple of things that could cause this.

To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Menu -> Advanced -> Logging level -> Debug
2. Reproduce the issue (and remember the exact time when it happened).
3. Menu -> Advanced -> Export Logs and System Info...
4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject

**Comment by mainhathao** [comment]
> I'm having the same problem. I disabled private relay but that didn't work, no change to loading time.

It’s working for me with Private Relay disabled. If somehow it blocks you from accessing sites, all you have to do is reset AdGuard settings, or you can uninstall and reinstall the app, that’d work too. Hope this helps.

**Comment by inazarab** [comment]
> Hi all, from our experience there's a couple of things that could cause this.
> 
> To troubleshoot this issue, we need to get the app logs.
> 
> Here's what we need you to do:
> 
> 1. Menu -> Advanced -> Logging level -> Debug
> 2. Reproduce the issue (and remember the exact time when it happened).
> 3. Menu -> Advanced -> Export Logs and System Info...
> 4. Send the archive to `devteam@adguard.com` and mention this issue number in the subject
> 
> Also, one more question: do you use any other network filtering software? Firewall, VPN, antivirus, something like that? If you do, please let us know which one.

When you say reproduce the issue I'm not sure how to do that. It's a consistent slowdown, everything loads fine, nothing is blocked, but it just loads extremely slowly and it's been a consistent issue, it doesn't come and go.

I'm not using any network filter right now. I occasionally use a VPN but it's usually off but the issue doesn't seem to change whether it's on or off though anyway.

**Comment by inazarab** [comment]
I upgraded to the new macOS beta 5 and the issue seems to be resolved.
