### ISSUE TITLE
Using DNS protection makes it impossible to connect to devices on my network

### ISSUE THREAD

**Issue by y4rr** [AdguardTeam/AdguardForMac#877]
DNS Protection should not resolve requests made to devices on my local network, and forward it to a local DNS server instead. 
Or, maybe you should not delete any servers from /etc/resolv.conf, and should just put "nameserver 127.0.0.1" as the first line.
Please look into this issue. Thanks

**Comment by ngorskikh** [comment]
Hi! 

DNS Protection should detect your search domains and forward them to the system-configured resolver automatically. 
Which domains do you want resolved through your system resolver and how are they configured?
Could you run `scutil --dns` before and after enabling DNS protection and share the results?

Also, please collect the logs:
```
1. Menu -> Gear -> Advanced -> Logging level -> Debug;
2. Reproduce the issue (and remember the exact time when it happened);
3. Menu -> Advanced -> Export Logs and System Info...;
4. Send the archive to **`apple@adguard.com`** and mention this issue number in the subject.
```

**Comment by y4rr** [comment]
Hi @ngorskikh 
Thanks your your reply.

I'm uncomfortable sharing raw logs because they contain too much personal information. I've created the redacted version of logs, where I removed logs that are unrelated to the DNS (for example, filters log), replaced all non-local IP addresses with xx.xx.xx.xx, and stuff like that. 
You can find the logs here: https://gist.github.com/y4rr/7f1e158fccec4006148b09c5db9d1b24

I've reproduced the issue two times, during which I was trying to ping the domain "hostname.dlink", which is a device on my local network, and got the reply that the name was not resolved:
1 - Mon Jun 14 13:27:45 MSK 2021
2 - Mon Jun 14 13:28:07 MSK 2021

Here's the output of `scutil --dns` before turning on the DNS protection:
```
DNS configuration

resolver #1
  nameserver[0] : 192.168.10.1
  nameserver[1] : xx.xx.xx.xx
  flags    : Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 192.168.10.1
  nameserver[1] : xx.xx.xx.xx
  if_index : 6 (en0)
  flags    : Scoped, Request A records
  reach    : 0x00020002 (Reachable,Directly Reachable Address)

resolver #2
  nameserver[0] : xx.xx.xx.xx
  nameserver[1] : 192.168.10.1
  if_index : 7 (en1)
  flags    : Scoped, Request A records
  reach    : 0x00000002 (Reachable)

```

Here's the output of `scutil --dns` after turning on the DNS protection:
```
DNS configuration

resolver #1
  nameserver[0] : 127.0.0.1
  flags    : Request A records, Request AAAA records
  reach    : 0x00030002 (Reachable,Local Address,Directly Reachable Address)

resolver #2
  domain   : local
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300000

resolver #3
  domain   : 254.169.in-addr.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300200

resolver #4
  domain   : 8.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300400

resolver #5
  domain   : 9.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300600

resolver #6
  domain   : a.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 300800

resolver #7
  domain   : b.e.f.ip6.arpa
  options  : mdns
  timeout  : 5
  flags    : Request A records
  reach    : 0x00000000 (Not Reachable)
  order    : 301000

DNS configuration (for scoped queries)

resolver #1
  nameserver[0] : 127.0.0.1
  if_index : 6 (en0)
  flags    : Scoped, Request A records, Request AAAA records
  reach    : 0x00000000 (Not Reachable)

resolver #2
  nameserver[0] : xx.xx.xx.xx
  nameserver[1] : 192.168.10.1
  if_index : 7 (en1)
  flags    : Scoped, Request A records
  reach    : 0x00000002 (Reachable)
```

If you need me to provide more information, I will be happy to, just not the raw logs, I hope that you understand. Thank you.

**Comment by ameshkov** [comment]
@ngorskikh @Stillness-2 first of all, we should expose via Advanced Settings the list of domains that will be forwarded to the system DNS resolver.

Also, what about adding `.dlink` to the default list?

**Comment by Chinaski1** [comment]
@y4rr 

As a temporary solution, you can try opening a `terminal` and type these two commands there:
- `defaults write com.adguard.mac.adguard DnsProxyDomainSuffixes -array search.domain1 search.doamin2`
- `defaults delete com.adguard.mac.adguard DnsProxyDomainSuffixes`

**Comment by y4rr** [comment]
@Chinaski1 
Konstantin, thank you! The workaround you've provided makes everything work.

**Comment by Chinaski1** [comment]
Let's leave the task open for now, as we want to add a solution within the application.

**Comment by ngorskikh** [comment]
As I understand it, search domains detection in DnsLibs works, so this is now a UI issue :)

**Comment by y4rr** [comment]
@Chinaski1 Lol you've fixed it in June, didn't you? It works in the latest build too.

**Comment by y4rr** [comment]
Close
