### ISSUE TITLE
Feature Request: Add a "Disable protection when using battery" option

### ISSUE THREAD

**Issue by akmLaVx** [AdguardTeam/AdguardForMac#878]
#### Problem

Some Macbook users would like to completely disable protection while their Macbook is not plugged in. As of now, they have to manually disable protection and reenable it later.

#### Proposed Solution

Add a relevent option to Settings > General.

#### Alternative Solution

None considered.

**Comment by ameshkov** [comment]
Tbh, I don't think we should implement this.

Mac Monterey supports shortcuts and we'd better provide people with a custom shortcut option (at least for enabling and disabling protection): https://github.com/AdguardTeam/AdguardForMac/issues/879
