### ISSUE TITLE
Add login with Apple to the app

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdguardForMac#880]
### Steps to reproduce

1. Have an account created with login with apple
2. Open adguard for Mac
3. Try to connect.
4. Blocked.

### Expected behavior
Have a way to connect myself with login with apple in the app without having to add a password.

### Actual behavior
Forced to add a password to the account so it delete the protection we have with the initial login with apple.

**Comment by Macqael** [comment]
Any news ?

**Comment by Chinaski1** [comment]
I think in the next release 2.6 this feature will not be included. 
But we will try to implement it by 2.7
