### ISSUE TITLE
Not launching on macos

### ISSUE THREAD

**Issue by Semior001** [AdguardTeam/AdguardForMac#881]
### Steps to reproduce
1. Try to launch AdGuard for macOS

### Expected behavior
AdGuard launching

### Actual behavior
AdGuard not launching

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/3617699/122654578-4b9b2a80-d16e-11eb-9741-5475279bd645.png)

</details>

### Customer ID 

Can't send and show any diagnostic data

### Your environment
* Environment name and version: (e.g. Chrome 59): MacOS Mojave 10.14.6
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners) No antiviruses, firewalls, traffic counters are used nor installed.

### Details
Actually I don't know how, what and why happened, but the adguard stopped launching some time ago.

When I try to launch it via terminal with adguard_service it prints the only log entry: `Sentry Started -- Version: 3.13.1`.

I have no idea how to rollback to previous version or how to make it run. I've tried to reinstall it or find any previous versions without success.

Seems not very informative :(

**Comment by zzebrum** [comment]
@Semior001 please run Console app and search there for AdGuard crashes. Also what happens if you run the app usual way?

**Comment by Semior001** [comment]
> Also what happens if you run the app usual way?

Literally nothing, the Adguard's icon is shown in dock but when clicking it nothing appears on screen.

> @Semior001 please run Console app and search there for AdGuard crashes.
The only crash reports that belong to Adguard are the crash reports during sending the sigkill to it. It seems that the adguard keeps running but not responding to anything.

**Comment by Chinaski1** [comment]
Hello @Semior001 
Try reinstalling the app using the advanced instructions.
You need to uninstall these folders and then reinstall the application:

- `/Library/Application Support/com.adguard.mac.adguard`
- `~/Library/Preferences/com.adguard.mac.adguard.plist`
- `~/Library/Group Containers/TC3Q7MAJXF.com.adguard.com`

**Comment by Semior001** [comment]
It worked after removing the last directory with group containers. Thank you! Still don't understand what happened. 

I suppose it would be better to add this directory for removal to [this](https://kb.adguard.com/en/macos/installation#uninstall) instruction.

**Comment by Chinaski1** [comment]
We add information to our knowledge base shortly, thank you.
