### ISSUE TITLE
Add the ability to upgrade to different release channels (release, beta, nightly)

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForMac#882]
Similar to how AdGuard is able to on Android, allow switching between release channels.
This is possible with other many other apps on macOS, so I presume it would be possible to upgrade to a newer release channel.

**Comment by zzebrum** [comment]
@jslawler hi!

Thank you for your request. Unfortunately, we are not planning to add this feature due to some technical difficulties. But I want to point out that releases in the beta channel are pretty stable on Mac OS.
