### ISSUE TITLE
Poor Network Performances

### ISSUE THREAD

**Issue by kdeldycke** [AdguardTeam/AdguardForMac#883]
I'm using AdGuard on my MacBook Air for a couple of years now and I'm a happy customer.

Since [I installed a 10G network at home](https://kevin.deldycke.com/2020/06/10g-network-at-home/) I realized AdGuard is significantly reducing the available bandwidth.

### Steps to reproduce

1. Get a MacBook Air (Retina, 13-inch, 2018)
2. Get latest macOS (Big Sur 11.4)
3. Get latest AdGuard for Mac (2.5.3.955 release CL-1.7.200)
4. Test bandwidth with AdGuard on and off

### Expected behavior
I shouldn't measure a **reduction of 100x of my bandwidth** when AdGuard is on compared to when it's off.

### Actual behavior
Here are some `iperf` tests on my local network between my MacBook and my NAS

<details><summary>Local bandwidth with AdGuard OFF:</summary>

```shell-session
❯ iperf3 -c 192.168.0.28 -p 5201 -f g
Connecting to host 192.168.0.28, port 5201
[  5] local 192.168.0.26 port 50728 connected to 192.168.0.28 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec   883 MBytes  7.40 Gbits/sec                  
[  5]   1.00-2.00   sec   862 MBytes  7.25 Gbits/sec                  
[  5]   2.00-3.00   sec   827 MBytes  6.93 Gbits/sec                  
[  5]   3.00-4.00   sec   893 MBytes  7.49 Gbits/sec                  
[  5]   4.00-5.00   sec   860 MBytes  7.20 Gbits/sec                  
[  5]   5.00-6.00   sec   919 MBytes  7.71 Gbits/sec                  
[  5]   6.00-7.00   sec   871 MBytes  7.32 Gbits/sec                  
[  5]   7.00-8.00   sec   822 MBytes  6.90 Gbits/sec                  
[  5]   8.00-9.00   sec   838 MBytes  7.02 Gbits/sec                  
[  5]   9.00-10.00  sec   822 MBytes  6.89 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  8.40 GBytes  7.21 Gbits/sec                  sender
[  5]   0.00-10.00  sec  8.40 GBytes  7.21 Gbits/sec                  receiver

iperf Done.
```

</details>

<details><summary>Local bandwidth with AdGuard ON:</summary>

```shell-session
❯ iperf3 -c 192.168.0.28 -p 5201 -f g
Connecting to host 192.168.0.28, port 5201
[  5] local 192.168.0.10 port 50632 connected to 192.168.0.28 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  4.51 MBytes  0.04 Gbits/sec                  
[  5]   1.00-2.00   sec  4.43 MBytes  0.04 Gbits/sec                  
[  5]   2.00-3.02   sec  4.18 MBytes  0.03 Gbits/sec                  
[  5]   3.02-4.00   sec  4.52 MBytes  0.04 Gbits/sec                  
[  5]   4.00-5.00   sec  5.63 MBytes  0.05 Gbits/sec                  
[  5]   5.00-6.00   sec  3.88 MBytes  0.03 Gbits/sec                  
[  5]   6.00-7.01   sec  3.61 MBytes  0.03 Gbits/sec                  
[  5]   7.01-8.02   sec  4.71 MBytes  0.04 Gbits/sec                  
[  5]   8.02-9.00   sec  3.72 MBytes  0.03 Gbits/sec                  
[  5]   9.00-10.00  sec  3.51 MBytes  0.03 Gbits/sec                  
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  42.7 MBytes  0.04 Gbits/sec                  sender
[  5]   0.00-10.02  sec  42.7 MBytes  0.04 Gbits/sec                  receiver

iperf Done.
```

</details>

### Customer ID 

* Ticket number: 520276

### Your environment

* MacBook Air (Retina, 13-inch, 2018)
* macOS (Big Sur 11.4)
* AdGuard for Mac (2.5.3.955 release CL-1.7.200)

**Comment by ameshkov** [comment]
Oh I really envy your network performance.

Moved this task to the CoreLibs repo (the "underlying" engine for all AG products):
https://github.com/AdguardTeam/CoreLibs/issues/1470

**Comment by kdeldycke** [comment]
Thanks @ameshkov for the proper bug triage. I'll follow on to the issue you just created at https://github.com/AdguardTeam/CoreLibs/issues/1470 .

**Comment by kdeldycke** [comment]
FTR, there was an limitation of network performances that was fixed in https://github.com/AdguardTeam/CoreLibs/issues/1561
