### ISSUE TITLE
How does adguard decide whether to use 'local.adguard.com' or 'injections.adguard.org'

### ISSUE THREAD

**Issue by way-huang** [AdguardTeam/AdguardForMac#884]
### Steps to reproduce

On my computer, when system proxy is on, the adguard uses 'injections.adguard.org', and when system proxy is off, it uses 'local.adguard.com'.
On my computer, the ‘injections.adguard.org’ always times out, so it stucks the website.
Is there a way to force the use of 'local.adguard.com'

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/40635359/123926079-1f797800-d9be-11eb-960b-32f0ab7eacf2.png)

![image](https://user-images.githubusercontent.com/40635359/123926151-3029ee00-d9be-11eb-9a0b-280f3e8b89a4.png)

</details>

### Your environment

* Google Chrome | 93.0.4557.4 (Official Build) dev (x86_64)
* Adguard 2.5.4.970 nightly (CL-1.7.231)
* BigSur 11.4
* ClashX
* Surge 4

**Comment by sfionov** [comment]
local.adguard.org is used when adguard is able to intercept connection to current IP address of local.adguard.org.
In this case, there will be no real connection to that server.

In other cases (including using proxy), AdGuard fallbacks to old injections method - filtering existing connection to injections.adguard.org. That means that connection to that server is real, but no queries are actually sent to that server.
There's no special case for proxies now, so proxy is required to be able to connect to "injections.adguard.org". 

We may improve this is the future.

**Comment by Chinaski1** [comment]
I close this task because the user has received an answer to his request.
Re-open it if you still have some questions.

**Comment by TPS** [comment]
Since there're no real connections to `local.adguard.com`, why does it need to have DNS resolution & that to an external address?  What would break if that were to, e.g., `NXDOMAIN`?

I remember vaguely that there's a discussion someplace around this, but I don't find it now.

**Comment by TPS** [comment]
It's still a problem that both AGDNS's & OpenDNS's logs show that they're receiving queries from my devices for `local.adguard.com`, though, IIUC, that's never supposed to leave the devices for resolution.

**Comment by sfionov** [comment]
@TPS local.adguard.org periodically resolved by AdGuard to intercept its IP address if it is already in DNS cache. However, regular queries from apps can be answered locally, thank you for idea. I created feature request for that: https://github.com/AdguardTeam/CoreLibs/issues/1854
