### ISSUE TITLE
Enable/allow delete key to delete filters

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#9]
Currently pressing the Del key doesn't do anything - whereas on the Windows version it'll delete filter(s).

**Comment by BooBerry** [comment]
Any update on this one? It's very trivial but would be very helpful! :)

**Comment by ameshkov** [comment]
> It's very trivial and would likely take several minutes to implement but would be very helpful! :)

Haha, i won't be so sure:)

**Comment by worldsdream** [comment]
I would love to see this.

**Comment by worldsdream** [comment]
Which one is the del key on mac?

**Comment by ameshkov** [comment]
FN+Backspace, yep:)

**Comment by BooBerry** [comment]
Or the DEL key on a PC keyboard when using macOS in a Hackintosh setup. ;)

**Comment by Alex-302** [comment]
> Or the DEL key on a PC keyboard when using macOS in a Hackintosh setup. ;)

Doesn't work on virtual machine:(

**Comment by BooBerry** [comment]
Just tried it in macOS VM in Windows/VMware, and it works fine there too.

**Comment by Alex-302** [comment]
Strange. I'm using MacOS in VMware, del is not working in filter editor.

**Comment by ameshkov** [comment]
Reporting from Mac, FN+Backspace is working, I am happy:)

**Comment by Stillness-2** [comment]
If you wish I can change shortcut on `Backspace` in next release.

**Comment by worldsdream** [comment]
I am used to the CMD+backspace when deleting, can that be added as well?

**Comment by ameshkov** [comment]
@Stillness-2 can you add one more shortcut?

**Comment by Stillness-2** [comment]
commit 90dabbf
