### ISSUE TITLE
Adguard prevents Viscosity OpenVPN connections on OS X 10.11.4

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#90]
TICKET ID KWF-964-64956

Adguard 1.2.0
OS X 10.11.4
Viscosity 1.6.2 

How to reproduce: 
OpenVPN connection attempts with Viscosity 1.6.2, will fail if Adguard is enabled.

Tips:
Disabling Adguard completely allows Viscosity to connect. 
Individually disabling all three protection modules (adblocker, privacy protection, browsing security) while leaving Adguard protection enabled does not resolve Viscosity connection problems.

example of Viscosity OpenVPN log with errors: https://gist.github.com/vozersky/818c408faed4fd648d08c2f133209afe

**Comment by gshumihin** [comment]
Tested with my OpenVPN config, works fine.

**Comment by Stillness-2** [comment]
@gshumihin Did you use https://www.sparklabs.com/viscosity ?

**Comment by sysfu** [comment]
I can offer remote sreenshare access to the affected system if that helps.

**Comment by vozersky** [comment]
@sysfu 
It will be helpful, how can I contact you to discuss convenient time?

**Comment by sysfu** [comment]
You can send me a PM in the adguard forums.

**Comment by vozersky** [comment]
Reproduced it via Teamviewer on user's mac.

@gshumihin  could not reproduce it
@Stillness-2  please assist

Viscosity OpenVPN log:

Apr 25 08:42:01: SIGUSR1[soft,tls-error] received, process restarting
Apr 25 08:42:01: UDPv4 link local: [undef]
Apr 25 08:42:01: UDPv4 link remote: [AF_INET]212.129.34.154:443
Apr 25 08:42:01: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:03: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:07: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:15: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:31: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:38: TLS Error: TLS key negotiation failed to occur within 37 seconds (check your network connectivity)
Apr 25 08:42:38: TLS Error: TLS handshake failed
Apr 25 08:42:38: SIGUSR1[soft,tls-error] received, process restarting
Apr 25 08:42:39: UDPv4 link local: [undef]
Apr 25 08:42:39: UDPv4 link remote: [AF_INET]212.129.34.154:443
Apr 25 08:42:39: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:41: write UDPv4: Operation not permitted (code=1)
Apr 25 08:42:45: write UDPv4: Operation not permitted (code=1)

**Comment by vozersky** [comment]
@sysfu  could you please provide a successful connection log example?

**Comment by sysfu** [comment]
You bet
```
Apr 25 17:56:22: Viscosity Mac 1.6.2 (1342)
Apr 25 17:56:22: Viscosity OpenVPN Engine Started
Apr 25 17:56:22: Running on Mac OS X 10.11.4
Apr 25 17:56:22: ---------
Apr 25 17:56:22: Checking reachability status of connection...
Apr 25 17:56:22: Connection is reachable. Starting connection attempt.
Apr 25 17:56:23: OpenVPN 2.3.10 x86_64-apple-darwin [SSL (OpenSSL)] [LZO] [PKCS11] [MH] [IPv6] built on Mar  2 2016
Apr 25 17:56:23: library versions: OpenSSL 1.0.2g  1 Mar 2016, LZO 2.09
Apr 25 17:56:26: UDPv4 link local: [undef]
Apr 25 17:56:26: UDPv4 link remote: [AF_INET]212.129.34.154:443
Apr 25 17:56:26: WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
Apr 25 17:56:42: [server] Peer Connection Initiated with [AF_INET]212.129.34.154:443
Apr 25 17:56:45: Opened utun device utun0
Apr 25 17:56:45: do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
Apr 25 17:56:45: /sbin/ifconfig utun0 delete
Apr 25 17:56:45: NOTE: Tried to delete pre-existing tun/tap instance -- No Problem if failure
Apr 25 17:56:45: /sbin/ifconfig utun0 10.55.0.12 10.55.0.12 netmask 255.255.0.0 mtu 1500 up
Apr 25 17:56:45: Initialization Sequence Completed
Apr 25 17:56:45: DNS mode set to: Full
```

**Comment by vozersky** [comment]
Screenshots of Seth's currently filtered apps:

![screen shot 2016-04-25 at 6 20 00 pm](https://cloud.githubusercontent.com/assets/17472907/15023790/ab276098-123a-11e6-92f7-6b40dacaf1e1.png)
![screen shot 2016-04-25 at 6 20 13 pm](https://cloud.githubusercontent.com/assets/17472907/15023788/ab24c004-123a-11e6-8523-deb09b1a7d6a.png)
![screen shot 2016-04-25 at 6 20 33 pm](https://cloud.githubusercontent.com/assets/17472907/15023789/ab27b444-123a-11e6-9a48-7224bdbaf784.png)

**Comment by Stillness-2** [comment]
I managed to repeat the mistake on Tunnelblick, so the process goes... :)

**Comment by Stillness-2** [comment]
commit 25671

**Comment by Stillness-2** [comment]
@sysfu Please check this build: https://www.dropbox.com/s/ctig2ihmzqq8i94/Adguard.zip?dl=1
