### ISSUE TITLE
www.latimes.com

### ISSUE THREAD

**Issue by zloyden** [AdguardTeam/AdguardForMac#900]
@adguard-bot commented on [Wed Jul 21 2021](https://github.com/AdguardTeam/AdguardFilters/issues/88764)

### Issue URL (Ads)
 [https://www.latimes.com/environment/story/2021-07-19/caltech-fined-for-damaging-native-american-cultural-site](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.latimes.com%2Fenvironment%2Fstory%2F2021-07-19%2Fcaltech-fined-for-damaging-native-american-cultural-site)
### Comment
Username: @TUO-V
> 我发现当我用【V2rayU】3.2.0版本（一个VPN软件）时，如果我只在【V2rayU】上使用【Pac模式】（部分网站使用代理）则AdGuard可以继续过滤广告，但如果使用【全局模式】（所有网站都使用代理）时AdGuard过滤就会失效

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/KPGGBk1.png)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Mac v2.5.3.955 release
Browser: | Chrome
Stealth mode options: | Hide your search queries, <br>Send Do-Not-Track header, <br>Remove X-Client-Data header from HTTP requests, <br>Strip URLs from tracking parameters, <br>Block third-party Authorization header, <br>Self-destructing first-party cookies (9999), <br>Self-destructing third-party cookies (120), <br>Disable cache for third-party requests, <br>Block WebRTC, <br>Block Push API, <br>Block Location API, <br>Block Java, <br>Hide your Referrer from third-parties (), <br>Hide your User-Agent (), <br>Hide your IP address (209.141.53.254)
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>AdGuard Base, <br/>EasyList, <br/>Peter Lowe's Blocklist<br/><br/><b>Privacy:</b><br/>AdGuard Tracking Protection, <br/>AdGuard URL Tracking, <br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List<br/><br/><b>Social Widgets:</b><br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>AdGuard Annoyances, <br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>Spam404, <br/>NoCoin Filter List<br/><br/><b>Language-specific:</b><br/>AdGuard Chinese, <br/>EasyList China, <br/>CJX's Annoyances List, <br/>xinggsf, <br/>ChinaList+EasyList
Custom filters: | https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/rule.txt,<br>https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/ublock-dynamic-rule.txt
Userscripts: | https://userscripts.adtidy.org/release/popup-blocker/2.5/popupblocker.meta.js,<br>https://userscripts.adtidy.org/release/adguard-extra/1.0/adguard-extra.meta.js
Other extensions used: | 无 non

---

@zloyden commented on [Fri Jul 23 2021](https://github.com/AdguardTeam/AdguardFilters/issues/88764#issuecomment-885438868)

Hi! This is not a filter issue, I will move it to another repository.

**Comment by Chinaski1** [comment]
@TUO-V

As I understand it, we are talking about using V2rayU on BigSur. 
Therefore, due to the specifics of the operating system, there may be some issues with using different modes of VPN/Proxy services.

https://kb.adguard.com/en/macos/solving-problems/big-sur-issues

**Comment by TUO-V** [comment]
Today I found that the problem I mentioned was solved after I updated the operating system to macOS 11.5.

**Comment by Chinaski1** [comment]
Glad to hear it :)
So, I close this task.
