### ISSUE TITLE
AdGuard for Mac won't start due to a network extension error

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdguardForMac#908]
Here's how it looks like:
![image](https://user-images.githubusercontent.com/5947035/128641430-3448cd30-f7a9-41d5-ae74-dc7892c63d6f.png)

What's strange is that the user reports that AG starts correctly when CloudFlare WARP is enabled. Once it's disabled, we're back to square one.

The issue is reproduced with both the stable and the nightly version of AdGuard for Mac.

@sfionov logs are attached to the corresponding JIRA issue, please take a look.

**Comment by ameshkov** [comment]
Relevant bug report:
https://forum.adguard.com/index.php?threads/adguard-wont-work-correctly-when-i-enable-cloudflare-please-help.44253/

**Comment by sfionov** [comment]
Cloudflare WARP alters network configuration when powered off - disables lo0 interface, so localhost can't be accessed anymore in Cloudflare WARP off.

To restore localhost interface user should run `sudo ifconfig lo0 up` in Terminal, or remove WARP and reboot.

I've reported a bug to Cloudflare, report ID is: 193575

**Comment by chumido98** [comment]
@sfionov It's still not work.

**Comment by ameshkov** [comment]
The bug in Cloudflare Warp is rather nasty, you may need to run this command (`sudo ifconfig lo0 up`) every time you disable WARP.

**Comment by ogirginc** [comment]
The issue persists... I can see the issue is closed as won't fix, however has anyone contacted to Cloudflare?

**Comment by ogirginc** [comment]
Hey @sfionov! I'm sorry to bother you, but have you got any response from Cloudflare?

**Comment by sfionov** [comment]
@ogirginc They didn't reply, but latest version of Cloudflare WARP doesn't turn off `lo0` interface on my machine.
