### ISSUE TITLE
Change Safe Browsing logic

### ISSUE THREAD

**Issue by BirdInFire** [AdguardTeam/AdguardForMac#910]
When I had read all the documentation some month ago I have seen that Windows and Mac version of secure browsing doesn't work the same (cache on windows and real time on Mac).

So my request is : 
Does the Mac version do caching of the safe browsing (like windows) if not can you add it ?

Thanks

**Comment by Chinaski1** [comment]
Hello there!

This safe browsing method will most likely be implemented in the next release.

**Comment by Macqael** [comment]
@Chinaski1 Thanks.
