### ISSUE TITLE
DNS is very slow on MacOS 12

### ISSUE THREAD

**Issue by tomiams** [AdguardTeam/AdguardForMac#912]
Environment:
- M1 Macbook
- Latest MacOS 12.0 Beta (This issue was not present on the latest MacOS release)
- Private Relay: on
- Adguard version 2.5.5.999 nightly (CL-1.8.141, DNS-1.6.14)

Steps to reproduce:
- Open safari, visit any website. The DNS resolution takes too long (in seconds)

Steps I've tried but didn't make a difference:
- Changing filtering mode from network extension to automatic proxy
- Changing DNS to 'system default' in Adguard

Is AdGuard currently incompatible with private relay?
Is there a way to get the benefits of Adguard DNS blocking AND private relay?

**Comment by Chinaski1** [comment]
Hello @tomiams 

As far as I understand the issue with the delay occurs only when the Private Relay function is enabled?

**Comment by tomiams** [comment]
I have not tried it with private relay disabled.
May I ask if there is a known conflict between Private Relay and "Network Extension" or "Automatic Proxy" modes or the "DNS protection" feature?

**Comment by tomiams** [comment]
It might not be DNS, I have updated issue #875 with the error and sent the debug logs. This issue can be closed/merged with 875.
