### ISSUE TITLE
Unlimited testing phase 

### ISSUE THREAD

**Issue by Theredmc** [AdguardTeam/AdguardForMac#915]
Hi, so I found out that when you use AppCleaner/Sensei/CleanMyMacX on macOS and remove Adguard completely you should be able to get another 14-days trial.
Using an Activation server for this and an account system should prevent this

### Steps to reproduce

1. Download AppCleaner
2. Remove AdGuard
3. Reinstall AdGuard
4. Use Trial 

### Your environment
macOS 12 Beta 5

**Comment by Chinaski1** [comment]
Hello there!

I tried to reproduce the above situation but after removing AdGuard using AppCleaner and Sensei, I could not reactivate the trial.
Specify, are you using these utilities on a virtual machine?

**Comment by Macqael** [comment]
have tested on a native machine (M1), and it does not work on myself, (have to totally reset my Mac) to do this work, but have you tweaked or modified any parameter of these cleaner ? (to facilitate the reproducing, maybe it clear some folder who isn't checked by default).

**Comment by Theredmc** [comment]
mhhh, I tried it on my Catalina machine and it didnt work there but it works on Monterey.
It could be that parameters are changd or it can be that it deletes folder it normally cant because sip is disabled on my m1 machine for cdock.
