### ISSUE TITLE
How does Encrypted DNS work ?

### ISSUE THREAD

**Issue by Macqael** [AdguardTeam/AdguardForMac#917]
Have questions about DNS Encryption on the software.

I have Two question : 

1. does the dnsencryption is enabled directly with the system network (or does it wait to the user to be connected and adguard ui executed ?) (M1)

2. Like on IOS does it generate an augmentation of the battery draining (I ask to decide if it's better to enable it on native (with profile) or use Adguard in the case of MAC).

Thanks for the answer.

**Comment by Chinaski1** [comment]
Hello @Macqael 

1. DNS launches after AdGuard starts up
2. In theory, the battery consumption should be increased. But this figure is [extremely insignificant](https://uploads.adguard.com/Chinaskijk9fm.png).
