### ISSUE TITLE
Adguard 2.5.3.955 stopped working on MacOS 11.5.2

### ISSUE THREAD

**Issue by hellhovnd** [AdguardTeam/AdguardForMac#919]
### Steps to reproduce
1. Upgrade to MacOS 11.5.2
2. Open Safari 14.1.2
3. Go to any web that displays ads (e.g. Youtube)
4. No ad is filtered (Adguard says no ad was blocked)

### Expected behavior
Adguard should block all ads

### Actual behavior
No ad is filtered

<details><summary>Screenshot:</summary>

![Screen Shot 2021-08-28 at 18 17 08](https://user-images.githubusercontent.com/13751988/131233306-155da159-25c1-4f28-ad84-80b0f890f57a.png) 

</details>

### Customer ID 
532759

### Your environment
* Environment name and version: Safari 14.1.2
* Any specific potentially conflicting software installed: Sophos Home 10.0.4a4

**Comment by Chinaski1** [comment]
Hello there!

Using any network filtering software alongside Sophos is quite problematic.
Therefore, AdGuard doesn't block any ads. And at this stage, it is difficult to say whether this issue is solvable.

**Comment by Chinaski1** [comment]
As a temporary solution you can try to use AdGuard in auto-proxy mode (Settings -> Network -> [Filtering mode](https://uploads.adguard.com/Chinaskia90mk.png))

**Comment by Chinaski1** [comment]
I'm closing this task as the Sophos Home compatibility issue, unfortunately, can't be fixed on the AdGuard side.
