### ISSUE TITLE
Problem with Sublime Text 3 Package Control while running AdGuard for Mac

### ISSUE THREAD

**Issue by SergeyKuzmich** [AdguardTeam/AdguardForMac#92]
Sublime Text 3 throws error (see screenshot) when installing package control with enabled AdGuard for Mac. Error also appears sometimes when starting Sublime Text 3 (I think it shows up when ST3 checks for updates)

<img width="532" alt="screen shot 2016-04-25 at 12 26 00" src="https://cloud.githubusercontent.com/assets/2089534/14779512/18667a7e-0ae1-11e6-8a58-f936755b9876.png">

Is it AdGuard certificates problem?

Thank you.

**Comment by ameshkov** [comment]
This is a Sublime bug, but it could really be triggered by installing local CA certificate:
https://github.com/wbond/package_control/issues/1002
