### ISSUE TITLE
Reinstall is not working

### ISSUE THREAD

**Issue by jxwinks** [AdguardTeam/AdguardForMac#920]
### Steps to reproduce

1. Intall AdguardForMac
2. Uninstall AdguardForMac
3. Reinsall AdguardForMac
2.
3.
4.

### Expected behavior
 Adguard should reinstall

### Actual behavior
claims INIT already exists but directory is NOT to be found

<details><summary>Screenshot:</summary>

</details>Last login: Sun Aug 29 10:11:36 on console

The default interactive shell is now zsh.
To update your account to use zsh, please run `chsh -s /bin/zsh`.
For more details, please visit https://support.apple.com/kb/HT208050.
winkelmans-imac:~ winkelman$ curl -s -S -L https://raw.githubusercontent.com/AdguardTeam/AdGuardHome/master/scripts/install.sh | sh -s -- -v
starting AdGuard Home installation script
channel: release
operating system: darwin
cpu type: amd64
AdGuard Home will be installed into /Applications/AdGuardHome
checking curl
checking unzip
note that AdGuard Home requires root privileges to install using this script
restarting with root privileges
Password:
starting AdGuard Home installation script
channel: release
operating system: darwin
cpu type: amd64
AdGuard Home will be installed into /Applications/AdGuardHome
checking curl
checking unzip
script is executed with root privileges
no need to uninstall
downloading package from https://static.adguard.com/adguardhome/release/AdGuardHome_darwin_amd64.zip -> AdGuardHome_darwin_amd64.zip
unpacking package from AdGuardHome_darwin_amd64.zip into /Applications
Archive:  AdGuardHome_darwin_amd64.zip
   creating: /Applications/AdGuardHome/
  inflating: /Applications/AdGuardHome/AdGuardHome  
  inflating: /Applications/AdGuardHome/LICENSE.txt  
 extracting: /Applications/AdGuardHome/AdGuardHome.sig  
  inflating: /Applications/AdGuardHome/README.md  
  inflating: /Applications/AdGuardHome/CHANGELOG.md  
2021/08/30 16:54:04 [info] Service control action: install
2021/08/30 16:54:04 [fatal] Failed to install AdGuard Home service: Init already exists: /Library/LaunchDaemons/AdGuardHome.plist
cannot install AdGuardHome as a service
winkelmans-imac:~ winkelman$ 

### Your environment

* Environment name and version: (e.g. Chrome 59): Mac Big Sur 11.2.3
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

**Comment by Chinaski1** [comment]
Issue moved to [AdguardTeam/AdGuardHome #3522](https://github.com/AdguardTeam/AdGuardHome/issues/3522) via [**ZenHub**](https://www.zenhub.com/)
