### ISSUE TITLE
DNS фильтрация и WireGuard

### ISSUE THREAD

**Issue by ammnt** [AdguardTeam/AdguardForMac#922]
Привет,

DNS фильтрация не работает при использовании VPN клиента WireGuard. Прежде я решал эту проблему при помощи .mobileconfig и удалив строку с DNS из конфигурации туннеля WireGuard. При использовании клиента AdGuard это решение не работает даже при помощи dnsstramp и предустановленным IP-адресом сервера.

Есть ли возможность решить эту проблему?😒

Спасибо.

**Comment by zzebrum** [comment]
@ammnt правильно ли я понимаю, что в у вас в конфиге WireGuard DNS сервера не заданы?
Какой DNS задан в настройках AdGuard? какая версия ос и соответственно какой режим фильтрации выбран (kernel extension или network extension)?

**Comment by ammnt** [comment]
> @ammnt правильно ли я понимаю, что в у вас в конфиге WireGuard DNS сервера не заданы?

Верно!

> Какой DNS задан в настройках AdGuard?

Попробуйте воспроизвести с этим:
`sdns://AgMAAAAAAAAADTE0Ni4yNTUuNTYuOTgAHWRvaC5hcHBsaWVkLXByaXZhY3kubmV0L3F1ZXJ5Bi9xdWVyeQ`

> какая версия ос и соответственно какой режим фильтрации выбран (kernel extension или network extension)?

macOS 11.5.2, поэтому network extension. Файл туннеля для тестирования могу скинуть в TG.

Спасибо.

**Comment by zzebrum** [comment]
@ammnt можете отправить конфиг на почту apple[at]adguard[dot]com или в TG на саппор-аккаунт @Naylya 

и еще вопрос: каким именно способом вы определяете отсутствие DNS фильтрации?

**Comment by ammnt** [comment]
> @ammnt можете отправить конфиг на почту apple[at]adguard[dot]com или в TG на саппор-аккаунт @Naylya

Отправил на почту только что.

> и еще вопрос: каким именно способом вы определяете отсутствие DNS фильтрации?

Ну не резолвятся домены и трафик ходит только по IP. Сюда можно зайти:
https://1.1.1.1
Вот самый простой и репрезентативный способ😀 Пинг тоже идет... Это я _вам_ дал такой адрес сервера, а так то у меня свой на базе AGH 😁

**Comment by ammnt** [comment]
@zzebrum,

1. C OpenVPN на 443/tcp порту такой проблемы нет - проверил только что;
2. Если нужны логи или дополнительная информация, то напишите;
3. На связи в TG:
https://t.me/ammntishere

**Comment by ameshkov** [comment]
У вас там в AllowedIPs = 0.0.0.0/0 -- то есть в туннель заруливается абсолютно весь трафик.

У меня есть ощущение, что проблема именно в этом. Можете попробовать AllowedIPs чуть поточнее вписать, без приватных подсетей?

```
AllowedIPs = 0.0.0.0/5 8.0.0.0/7 11.0.0.0/8 12.0.0.0/6 16.0.0.0/8 18.0.0.0/7 20.0.0.0/6 24.0.0.0/5 32.0.0.0/3 64.0.0.0/3 96.0.0.0/4 112.0.0.0/5 120.0.0.0/6 124.0.0.0/7 126.0.0.0/8 128.0.0.0/2 192.0.0.0/9 192.128.0.0/11 192.160.0.0/13 192.169.0.0/16 192.170.0.0/15 192.172.0.0/14 192.176.0.0/12 192.192.0.0/10 193.0.0.0/8 194.0.0.0/7 196.0.0.0/6 200.0.0.0/5 208.0.0.0/4 224.0.0.0/3
```

**Comment by ammnt** [comment]
@ameshkov, да надо было исключить частные адреса. Хотя я пробовал это с самого начала... не знаю почему не завелось тогда. Можно закрывать.
