### ISSUE TITLE
when enable dns protection,ping cann't work

### ISSUE THREAD

**Issue by spacexnasa** [AdguardTeam/AdguardForMac#924]
![image](https://user-images.githubusercontent.com/3109626/131933322-c0e4c1f5-1807-42d6-8e22-f63928d1ef11.jpeg)

as this image,when enable  DNS protection,i use ping mail.google.com or the goole.com or the other domains,display this error

ping: cannot resolve mail.google.com: Unknown host

Application version 2.6.0.1011 nightly (CL-1.8.166, DNS-1.6.31)

**Comment by zzebrum** [comment]
@spacexnasa are you on Mac OS v11 Big Sur? What if you select another DNS provider from the list? Did the problem occur after you updated the application to the latest nightly?

**Comment by spacexnasa** [comment]
> @spacexnasa are you on Mac OS v11 Big Sur? What if you select another DNS provider from the list? Did the problem occur after you updated the application to the latest nightly?

hello,thanks for your reply,and i have my own dns server run on my laptop,system is 11.5.2,and adguard is the latest nightly

**Comment by Chinaski1** [comment]
@spacexnasa 

Are you using a DNS profile or are the configurations set in system preferences -> network?

**Comment by spacexnasa** [comment]
> @spacexnasa
> 
> Are you using a DNS profile or are the configurations set in system preferences -> network?

![image](https://user-images.githubusercontent.com/3109626/132268226-3c647666-9c18-4b77-bb90-ea85843f88d1.jpeg)
and the  system preferences -> network
![image](https://user-images.githubusercontent.com/3109626/132268249-4c182f8d-2054-4408-89af-c69879ac4c1d.jpeg)
this is my own dns server,if let the 
![image](https://user-images.githubusercontent.com/3109626/132268304-74e71467-5c14-439e-af76-43905650a375.jpeg)
empty,ping can work,you can test on  your mac

**Comment by Chinaski1** [comment]
I tried to reproduce your issue using my own DNS but encountered no problems.

So to troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by spacexnasa** [comment]
> I tried to reproduce your issue using my own DNS but encountered no problems.
> 
> So to troubleshoot this issue, we need to get the app logs.
> 
> Here's what we need you to do:
> 
> 1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
> 2. Reproduce the issue and remember the exact time it happened;
> 3. Menu --> Advanced --> **Export Logs and System Info...**;
> 4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

ok,wait for moment please

**Comment by Chinaski1** [comment]
@spacexnasa 
Please clarify, did you send the logs to the email?

**Comment by Chinaski1** [comment]
Any news?

**Comment by Chinaski1** [comment]
Closed due not reply.
