### ISSUE TITLE
Mail.app CPU eater on AdGuard DNS

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdguardForMac#928]
## environment

AdGuard 2.6.0.1011 beta (CL-1.8.166, DNS-1.6.31)
DNS -> Provider -> AdGuard DNS

- DNS over QUIC
- DNS over TLS
- DNS over HTTPS
- DNSCript

## Console.app log

Date/Time:        2021-09-07 18:25:16.665 +0900
End time:         2021-09-07 18:26:51.202 +0900
OS Version:       macOS 11.5.2 (Build 20G95)
Architecture:     arm64e
Report Version:   32
Incident Identifier: 75666ABB-1819-4B6A-B68B-BF8150D59AF1
Share With Devs:  Yes

Data Source:      Microstackshots
Shared Cache:     74867C57-7C81-38D6-BB42-68EC05B7B3CB slid base address 0x192338000, slide 0x12338000
Shared Cache:     9A070000-0040-0000-0000-000000000000 slide 0x14000

Command:          Mail
Path:             /System/Applications/Mail.app/Contents/MacOS/Mail
Identifier:       com.apple.mail
Version:          14.0 (3654.120.0.1.13)
Build Version:    92
Project Name:     Mail_App
Source Version:   3654120000001013
Parent:           UNKNOWN [1]
PID:              89353

Event:            cpu usage
Action taken:     none
**CPU:              90 seconds cpu time over 95 seconds (95% cpu average), exceeding limit of 50% cpu over 180 seconds**
CPU limit:        90s
Limit duration:   180s
CPU used:         90s
CPU duration:     95s
Duration:         94.54s
Duration Sampled: 93.72s
Steps:            69

Hardware model:   MacBookAir10,1
Active cpus:      8

Heaviest stack for the target process:
  42  _pthread_wqthread + 276 (libsystem_pthread.dylib + 14492) [0x19261f89c]
  42  _dispatch_workloop_worker_thread + 764 (libdispatch.dylib + 93044) [0x192486b74]
  25  _dispatch_workloop_invoke + 1680 (libdispatch.dylib + 54668) [0x19247d58c]
  22  _dispatch_source_invoke + 1284 (libdispatch.dylib + 105340) [0x192489b7c]
  21  _dispatch_continuation_pop + 448 (libdispatch.dylib + 29592) [0x192477398]
  21  _dispatch_client_callout + 20 (libdispatch.dylib + 16064) [0x192473ec0]
  18  nw_socket_handle_socket_event + 1636 (libnetwork.dylib + 1415716) [0x1963dca24]
  7   _os_log_impl_flatten_and_send + 5824 (libsystem_trace.dylib + 28432) [0x1923bef10]
  6   voucher_activity_trace_v_2 + 1248 (libdispatch.dylib + 175888) [0x19249af10]
  6   firehose_buffer_ring_enqueue + 312 (libdispatch.dylib + 180960) [0x19249c2e0]
  5   firehose_send_push_async + 92 (libdispatch.dylib + 229180) [0x1924a7f3c]
  4   mach_msg_trap + 8 (libsystem_kernel.dylib + 3540) [0x1925e8dd4]

Powerstats for:   Mail [89353]
Shared Cache:     74867C57-7C81-38D6-BB42-68EC05B7B3CB slid base address 0x192338000, slide 0x12338000
App Version:      14.0
Build Version:    3654.120.0.1.13
Path:             /System/Applications/Mail.app/Contents/MacOS/Mail
Architecture:     arm64e
Parent:           UNKNOWN [1]
UID:              503
Sudden Term:      Tracked
Footprint:        83.44 MB -> 80.08 MB (-3440 KB) (max 88.73 MB )
Start time:       2021-09-07 18:25:18.207 +0900
End time:         2021-09-07 18:26:49.667 +0900
Num samples:      42 (61%)
Primary state:    30 samples Non-Frontmost App, Suppressed, User mode, Effective Thread QoS Default, Requested Thread QoS Default, Override Thread QoS Default
User Activity:    0 samples Idle, 42 samples Active
Power Source:     0 samples on Battery, 42 samples on AC
  42  _pthread_wqthread + 276 (libsystem_pthread.dylib + 14492) [0x19261f89c]
    42  _dispatch_workloop_worker_thread + 764 (libdispatch.dylib + 93044) [0x192486b74]
      25  _dispatch_workloop_invoke + 1680 (libdispatch.dylib + 54668) [0x19247d58c]
        22  _dispatch_source_invoke + 1284 (libdispatch.dylib + 105340) [0x192489b7c]
          21  _dispatch_continuation_pop + 448 (libdispatch.dylib + 29592) [0x192477398]
            21  _dispatch_client_callout + 20 (libdispatch.dylib + 16064) [0x192473ec0]
              18  nw_socket_handle_socket_event + 1636 (libnetwork.dylib + 1415716) [0x1963dca24]
                7   _os_log_impl_flatten_and_send + 5824 (libsystem_trace.dylib + 28432) [0x1923bef10]
                  6   voucher_activity_trace_v_2 + 1248 (libdispatch.dylib + 175888) [0x19249af10]
                    6   firehose_buffer_ring_enqueue + 312 (libdispatch.dylib + 180960) [0x19249c2e0]
                      5   firehose_send_push_async + 92 (libdispatch.dylib + 229180) [0x1924a7f3c]
                        4   mach_msg_trap + 8 (libsystem_kernel.dylib + 3540) [0x1925e8dd4]
                          2   <Kernel mode>
                        1   mach_msg_trap + 4 (libsystem_kernel.dylib + 3536) [0x1925e8dd0]
                      1   firehose_send_push_async + 160 (libdispatch.dylib + 229248) [0x1924a7f80]
                        1   mach_msg_destroy + 44 (libsystem_kernel.dylib + 7304) [0x1925e9c88]
                          1   _kernelrpc_mach_port_deallocate_trap + 8 (libsystem_kernel.dylib + 3396) [0x1925e8d44]
                            1   <Kernel mode>
                  1   voucher_activity_trace_v_2 + 340 (libdispatch.dylib + 174980) [0x19249ab84]
                6   _os_log_impl_flatten_and_send + 2212 (libsystem_trace.dylib + 24820) [0x1923be0f4]
                  6   _os_log_fmt_flatten_to_blob + 268 (libsystem_trace.dylib + 30220) [0x1923bf60c]
                    6   _os_log_fmt_flatten_data_into_blob + 104 (libsystem_trace.dylib + 30416) [0x1923bf6d0]
                      3   os_trace_blob_addns + 192 (libsystem_trace.dylib + 31392) [0x1923bfaa0]
                      1   os_trace_blob_addns + 336 (libsystem_trace.dylib + 31536) [0x1923bfb30]
                      1   os_trace_blob_addns + 208 (libsystem_trace.dylib + 31408) [0x1923bfab0]
                      1   os_trace_blob_addns + 44 (libsystem_trace.dylib + 31244) [0x1923bfa0c]
                1   ___chkstk_darwin + 24 (libsystem_pthread.dylib + 9724) [0x19261e5fc]
                1   voucher_get_activity_id + 36 (libdispatch.dylib + 174196) [0x19249a874]
                1   _os_log_impl_flatten_and_send + 5824 (libsystem_trace.dylib + 28432) [0x1923bef10]
                1   _os_log_impl_flatten_and_send + 4812 (libsystem_trace.dylib + 27420) [0x1923beb1c]
                  1   <Kernel mode>
                1   _os_log_impl_flatten_and_send + 2900 (libsystem_trace.dylib + 25508) [0x1923be3a4]
              1   nw_socket_handle_socket_event + 2620 (libnetwork.dylib + 1416700) [0x1963dcdfc]
              1   nw_socket_handle_socket_event + 1696 (libnetwork.dylib + 1415776) [0x1963dca60]
                1   nw_socket_input_finished + 84 (libnetwork.dylib + 1442088) [0x1963e3128]
              1   nw_socket_handle_socket_event + 120 (libnetwork.dylib + 1414200) [0x1963dc438]
          1   _dispatch_continuation_pop + 464 (libdispatch.dylib + 29608) [0x1924773a8]
            1   objc_autoreleasePoolPop + 212 (libobjc.A.dylib + 32268) [0x1924bce0c]
              1   AutoreleasePoolPage::releaseUntil(objc_object**) + 88 (libobjc.A.dylib + 169880) [0x1924de798]
        2   _dispatch_source_invoke + 1284 (libdispatch.dylib + 105340) [0x192489b7c]
        1   _dispatch_source_invoke + 356 (libdispatch.dylib + 104412) [0x1924897dc]
      17  _dispatch_workloop_invoke + 2056 (libdispatch.dylib + 55044) [0x19247d704]
        17  _dispatch_event_loop_drain + 332 (libdispatch.dylib + 153292) [0x1924956cc]
          16  _dispatch_kq_drain + 112 (libdispatch.dylib + 153556) [0x1924957d4]
            15  kevent_id + 8 (libsystem_kernel.dylib + 11024) [0x1925eab10]
              8   <Kernel mode>
            1   kevent_id + 0 (libsystem_kernel.dylib + 11016) [0x1925eab08]
          1   _dispatch_queue_wakeup + 596 (libdispatch.dylib + 58664) [0x19247e528]

  Binary Images:
           0x104b44000 -                ???  com.apple.mail 14.0 (3654.120.0.1.13) <BF153FC2-20E8-35B1-ACA3-2A34BD270A5A>  /System/Applications/Mail.app/Contents/MacOS/Mail
           0x1923b8000 -        0x1923cffff  libsystem_trace.dylib (1277.120.1)    <59FD0CCA-0321-3A28-A2FB-80CCBDDFEC82>  /usr/lib/system/libsystem_trace.dylib
           0x192470000 -        0x1924b4fff  libdispatch.dylib (1271.120.2)        <7FAD1391-1E49-3CF2-9936-E808F815AA8F>  /usr/lib/system/libdispatch.dylib
           0x1924b5000 -        0x1924eefff  libobjc.A.dylib (824)                 <3478ECD1-A8BB-38DC-BC97-966A244DB668>  /usr/lib/libobjc.A.dylib
           0x1925e8000 -        0x19261bfff  libsystem_kernel.dylib (7195.141.2)   <1E1E6F44-01BC-3994-A907-61288C3D7BFD>  /usr/lib/system/libsystem_kernel.dylib
           0x19261c000 -        0x192628fff  libsystem_pthread.dylib (454.120.2)   <85E14929-1F9B-3E79-ABDE-06EB161F9574>  /usr/lib/system/libsystem_pthread.dylib
           0x196283000 -        0x1969cbfff  libnetwork.dylib (2288.140.7)         <A0BB3B06-C5A3-3DB8-AED9-EBB180FDBFC1>  /usr/lib/libnetwork.dylib

## no problem

DNS -> Provider -> AdGuard DNS

- ~~DNS over TLS~~
- ~~DNS over HTTPS~~
- ~~DNSCrypt~~
- Regular

**Comment by Chinaski1** [comment]
Attempts to reproduce the behaviour on AdGuard 2.6.0.1011 beta (CL-1.8.166, DNS-1.6.31) + 12.0 Beta (21A5506j) doesn't take any result, regardless of the server selected and the protocol used.
Perhaps you have noticed at what point the CPU load increases significantly?

Also, I would like to specify maybe you using any software that could potentially cause application compatibility issues.
For example Antivirus, VPN, Little Snitch, etc.

**Comment by Chamiu** [comment]
> Perhaps you have noticed at what point the CPU load increases significantly?

Yes, I use notification of iStatMenu.

- CPU usage : 50%, 30 sec
- "M1 SOC Die Average" : 50℃, 10sec

> Also, I would like to specify maybe you using any software that could potentially cause application compatibility issues.
> For example Antivirus, VPN, Little Snitch, etc.

I use ESET Network Protection Proxy at ESET CyberSecurity Pro 6.10.700.0.

- Web access protection
- Email client protection
- Anti-Phishing protection

conflict AdGuard DNS with ESET Network Protection Proxy ?

**Comment by Chinaski1** [comment]
It looks like one of ESET's modules is in conflict with AdGuard, which is causing these problems.
Please try to disable ESET completely and try to reproduce the issue again.

**Comment by Chamiu** [comment]
> It looks like one of ESET's modules is in conflict with AdGuard, which is causing these problems.
> Please try to disable ESET completely and try to reproduce the issue again.

I try...

- uninstall ESET CyberSecurity Pro6.10.700.0 (Intel with Rosetta 2)
- install Avira Security 1.7.5 (**Wow Universal Binary 2**)
- install AdGuard 2.6.0.1011 beta (CL-1.8.166, DNS-1.6.31)
- DNS -> Provider -> AdGuard DNS -> DNS over QUIC

I watch few days.

**Comment by Chamiu** [comment]
This issue didn't change.
I feel not compatible mail.app(macOS Big Sur.6.0) with AdGuard 2.6.0 beta 2 DNS VPN extension.

PreferencePane -> Network
VPN only AdGuard.

**Comment by Chinaski1** [comment]
Hmm...

Please try to disable AdGuard from autostart (Settings -> General -> Launch AdGuard at login).
Then reboot your Mac and after rebooting run mail.app first and then AdGuard.
Will the issue recur using this scenario?

**Comment by sfionov** [comment]
May be the same issue as https://github.com/AdguardTeam/CoreLibs/issues/1436

If starting Mail.app while AdGuard protection is already running helps, it is.

**Comment by Chamiu** [comment]
Let me know if you have checked the anti-virus software compatible with AdGuard 2.6 beta.
This is because consumer anti-virus software has a network monitoring function.

Incidentally, there were remnants of multiple anti-virus services in /Library/SystemExtensions/ that repeated install and uninstall.

**Comment by Chinaski1** [comment]
@Chamiu 

Please clarify if you tried to start the Mail.app after running protection in AdGuard?

**Comment by Chamiu** [comment]
# AdGuard  2.6.0.1041 log

> @Chamiu
> 
> Please clarify if you tried to start the Mail.app after running protection in AdGuard?

1. install AdGuard  2.6.0.1041 : DNS protect ON, AdGuard DNS, QUIC
2. reboot macOS Big Sur.6.0
   ![Startup Items](https://store3.gofile.io/download/1a8f4189-f6ad-428e-a89c-9a8f4dfdf8a4/Starup%20Items.png)
3. launch Mail.app
4. Launch Safari Technology Preview 133
5. Launch Reeder.app
6. Display sleep
7. Touch ID Button touch to wake
8. Mail.app CPU 98% eat

> It looks like one of ESET's modules is in conflict with AdGuard, which is causing these problems.
> Please try to disable ESET completely and try to reproduce the issue again.

Perhaps, conflict with ESET CyberSecurity Pro 6.11.2.0.  
But security software have protect connections to The Internet.
I can only be surprised by the insistence to give up my safety.
Ask for compatible anti-virus software.

[Mail_2021-10-17-171853_MacBook-Air-Late-2020.cpu_resource.diag.zip](https://github.com/AdguardTeam/AdguardForMac/files/7359629/Mail_2021-10-17-171853_MacBook-Air-Late-2020.cpu_resource.diag.zip)
