### ISSUE TITLE
Test websites accessibilities with both Adguard and IPv6 enabled

### ISSUE THREAD

**Issue by vbagirov** [AdguardTeam/AdguardForMac#93]
For example, http://board.byuu.org/phpbb3/ 

Original forum thread - with IPv6 enabled, website won't load at all:
https://forum.adguard.com/index.php?threads/adguard-for-mac-beta-version-1-2-1.9737/#post-81750

**Comment by BooBerry** [comment]
http://www.rampagedev.com/ - this might be another example, still playing around with it.

**Comment by Stillness-2** [comment]
@BooBerry Check this build please: https://www.dropbox.com/s/ctig2ihmzqq8i94/Adguard.zip?dl=1

**Comment by BooBerry** [comment]
Yup, it working fine now! 👍

**Comment by Stillness-2** [comment]
CR-AG-766
