### ISSUE TITLE
Blocking Google doc edition

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardForMac#94]
When editing a Google document for a few hours, there's always a time where Google Drive is "disconnected".  Re-establishing the connection requires to pause Adguard.

This behaviour has been reproduced multiple times and I can confirm that it is Adguard blocking Google Drive.

Now, the logs of Adguard doesn't show anything blocked (even in debug mode) which is probably another bug. But as soon as I pause Adguard and the connection is repaired for Google Drive, a request is sent to:

http://5.talkgadget.google.com/u/0/talkgadget/_/channel/bind?LOT_OF_DATA

I suspect that Adguard is blocking talkgadget which is sometimes used by GDrive as a beacon.

**Comment by ameshkov** [comment]
@ploum the link seems to be broken, I see an "Unknown SID Error 400" there.

Which exact version of Adguard do you sue?

**Comment by ameshkov** [comment]
Couple more questions:
1. You are talking about google docs web app, right? I mean you edit doc in browser?
2. What happens when you simply refresh that page?

**Comment by ploum** [comment]
I use Adguard 1.2.0 on OSX.

1. Yes, I mean I'm editing a doc in my browser (Safari). It also happens under Chrome but seems less frequent.

2. When I refresh the page, it usually reestablish the connexion but not all the time.


My gut feeling is that Google Drive use a keep-alive mechanism and that, for some reasons, the URL for this mechanism is sometimes blocked by adguard, sometimes not. It feels like GDrive is moving through some random URL and only a fraction of them are blocked by Adguard.

**Comment by ameshkov** [comment]
Does it help to whitelist google docs domain (docs.google.com)?
You can do it through AG settings -> edit whitelist.

Meanwhile I'll try to reproduce this issue on hour side.

**Comment by ploum** [comment]
The bug still happens from time to time.  (but to witness it, you have to edit Google documents for hours).

This time, I saw 3 blocked URL:

http://cello.client-channel.google.com/client-channel/channel/*****
http://0.docs.google.com/document/d/********
http://0.talkgadget.google.com/u/0/talkgadget/_/channel/bind*********

**Comment by ameshkov** [comment]
Hm, I don't see any filter rule blocking these URLs in our filters.

Could you please take a screenshot or copy/paste filtering log next time?

**Comment by Stillness-2** [comment]
Could you please do the following next time?
1. Turn on debug logging level (menu -> Advanced -> Logging Level -> Debug)
2. Edit text in document which is shown as 'disconnected'
3. If connection isn't back on, refresh the page
4. Turn off debug logging level (menu -> Advanced -> Logging Level -> Default)
5. Send request to support team from app (menu -> Support...), this will let us to obtain your log.

**Comment by vozersky** [comment]
resolved
