### ISSUE TITLE
MacMini (m1) WiFi Issues

### ISSUE THREAD

**Issue by mglbc** [AdguardTeam/AdguardForMac#941]
AdGuard is interfering with WiFi on my Mac Mini 2020 (m1) with OS 11.6. With AdGuard my WiFi connection is unstable and connects/disconnects rapidly. I have narrowed this down to AdGuard because when I uninstalled the Mac app, WiFi was stable. This happened after the 11.6 update.

**Comment by Chinaski1** [comment]
Hello!

Please clarify the following information:

- Has the AdGuard DNS module been switched on?
- Do you use third-party software such as anti-virus or VPN?

**Comment by mglbc** [comment]
Hello,
Yes this happens with the DNS module. Actually I tested with other DNS level blocking and it repeats. I think it is a bug unique to the Mac Mini M1. It does not happen with my MacBook Air M1 with AdGuard. 

I am not using antivirus or VPN

Thanks

**Comment by Chinaski1** [comment]
@mglbc 

Should you try rebooting your Mac mini and check if the issue repeats?

If it's still reproduced, try reinstalling the app (link to beta version: agrd.io/mac_beta)

**Comment by mglbc** [comment]
Hello,
I have tried this. It really looks like there is an issue with M1 Mac and DNS-level protection. On my Mini it just kills the WiFi and on my MacBook Pro it crashes AdGuard (with the Beta version).  I have rebooted, I have reinstalled and I still have issues.

Mike

**Comment by Chinaski1** [comment]
To troubleshoot this issue, we need to get the app logs.

Here's what we need you to do:

1. Click **AdGuard icon** in the menu bar --> Gear --> Advanced --> Logging level --> **Debug**;
2. Reproduce the issue and remember the exact time it happened;
3. Menu --> Advanced --> **Export Logs and System Info...**;
4. Send the archive to `apple@adguard.com` and mention this issue number in the subject.

**Comment by Chinaski1** [comment]
Any news?

**Comment by mglbc** [comment]
Hello,
I removed AdGuard to make sure that was causing the Wi-Fi issues. I will reinstall and see if things are stable. 

Thanks

**Comment by Chinaski1** [comment]
I am closing this task due to lack of activity.

Reopen it if the issue recurs.
