### ISSUE TITLE
Mail is very slow to launch

### ISSUE THREAD

**Issue by kklobe** [AdguardTeam/AdguardForMac#942]
### Steps to reproduce

1. Install and enable AdGuard
2. Launch Mail
3. Wait 20-30 seconds for Mail to open
4.

### Expected behavior

Mail should launch faster

### Actual behavior

Mail launches slowly, and often shows a spinning beach ball

<details><summary>Screenshot:</summary>

</details>

### Customer ID 

I did not receive a Customer ID, only a ticket number.

### Your environment

* Environment name and version: (e.g. Chrome 59): MacBook Pro M1, macOS 11.6, AdGuard 2.6.0.1022 nightly (CL-1.8.183, DNS-1.6.36)
* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners): None

**Comment by Chinaski1** [comment]
Hello there!

The issue is not reproducing on our side.

If you are using DNS filtering it makes sense to choose a different server.

**Comment by kklobe** [comment]
I am not able to reproduce this after updating to 2.6.0.1026 nightly, thank you!
