### ISSUE TITLE
AdGuard for Mac warned me about more than 50,000 rules

### ISSUE THREAD

**Issue by HenkPoley** [AdguardTeam/AdguardForMac#948]
Though I'm reading that Safari/Mac has no such limit (in the past). 

Is this new in Big Sur (11.6.1 / Safari 15.0), or a bug?

**Comment by ameshkov** [comment]
Probably should've been opened here: https://github.com/AdguardTeam/AdguardForSafari
AdGuard for Mac is a different type of blocker that does not rely on Safari and has no limitations.

Regarding the question itself, Safari has this limitation on both macOS and iOS. The limit is increased to 150k in the new iOS / macOS versions.

**Comment by HenkPoley** [comment]
Hmm okay. btw, I don't think there's any more recent than Safari 15.0 on Big Sur 11.6; Unless it's only on the Safari Technology Preview. It could of course be that I didn't see the '1' in 150,000 before clicking it away.

**Comment by ameshkov** [comment]
New macOS is Monterey, it hasn't been released yet.
