### ISSUE TITLE
Lists can be scrolled in any direction instead of only vertical

### ISSUE THREAD

**Issue by planet0** [AdguardTeam/AdguardForMac#949]
Trying to scroll through filters (and extensions) is messy and there seems to be a little extra horizontal space to cause horizontal scrolling to occur.

### Steps to reproduce

1. Open Preferences
2. Select Filters or Extensions tab
3. Use MacBook trackpad to scroll in any direction

### Expected behavior
Can only scroll vertically

### Actual behavior
Can be scrolled in any direction

<details><summary>Video 1:</summary>

https://user-images.githubusercontent.com/65204836/135783124-3c05486e-2a1c-4605-a628-53dbc47b205e.mov

</details>

<details><summary>Video 2:</summary>

https://user-images.githubusercontent.com/65204836/135783138-bf6ed38c-6e7e-4cac-b7cb-08a38cde837f.mov

</details>

### Your environment

* AdGuard version: 2.6.0.1032 nightly (CL-1.8.195, DNS-1.6.52)
* macOS version: 11.6 (20G165)

**Comment by Chinaski1** [comment]
Hello there!

We decided to make more flexible customization for filter/extensions settings so this behaviour is expected.
