### ISSUE TITLE
Check hosts file for any modifications

### ISSUE THREAD

**Issue by vozersky** [AdguardTeam/AdguardForMac#95]
based on: 
<img width="609" alt="1" src="https://cloud.githubusercontent.com/assets/17472907/15224800/0dfe9516-1884-11e6-8583-ddf8ba9c893b.png">

**Comment by Stillness-2** [comment]
@ameshkov How does Adguard must react on presence domains in `/etc/hosts`?

**Comment by ameshkov** [comment]
I suppose we should simply remove these lines on the app startup.

**Comment by Stillness-2** [comment]
Hmm
We need admin rights for modification of this file. Do you want to request from user of the administrator privileges?

**Comment by ameshkov** [comment]
Nah, this is too complicated. Let's ignore it then.
