### ISSUE TITLE
Can't subscribe on any Medium page with Adguard

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardForMac#96]
Adguard seems to block the "subscribe" button on every Medium profile.

**Comment by ploum** [comment]
![screen shot 2016-05-13 at 15 55 08](https://cloud.githubusercontent.com/assets/1233155/15250140/928924aa-1923-11e6-8a82-c57fbd66e1e6.png)

**Comment by vozersky** [comment]
@ploum hi! could you please tell me what app version do you use? is it 1.2.0? And also what filters are in your list?

**Comment by ploum** [comment]
1.2.0 with the following filters:

- English filter
- Spyware filter
- Social media filter
- Dutch filter
- Easylist Italy
- List FR
- Adblock polsky reguly  (no idea why, I don't speak Polish!)

**Comment by vozersky** [comment]
@ploum 

You mean this follow button, right? 

![2](https://cloud.githubusercontent.com/assets/17472907/15251310/74509604-1931-11e6-8f09-0770d1ac23cd.png)

Try temporary disabling the English filter, does it help?

**Comment by ploum** [comment]
Yes.

**Comment by vozersky** [comment]
@ploum add   medium.com#@#.js-followState    to the user filter

**Comment by ameshkov** [comment]
@vozersky shouldn't we add it to social filter?

**Comment by vozersky** [comment]
@ploum Thanks for telling us! The rule for Medium.com got to English filter by mistake, we have moved it to appropriate Social media filter (please note that you will have to turn it off or add an exception). 

@ameshkov  oh, yes, it was moved in the same day

**Comment by ploum** [comment]
I would argue that this one should never be blocked when I'm on medium.com because it's not a social media widget but part of the website itself.

**Comment by Alex-302** [comment]
@ameshkov 
>shouldn't we add it to social filter?
this button should to be excluded?

**Comment by ameshkov** [comment]
> I would argue that this one should never be blocked when I'm on medium.com because it's not a social media widget but part of the website itself.

That's what I am talking about, this button should not be blocked on medium.com at all. 

> this button should to be excluded?

Yep, why would we, it is a part of the website.
