### ISSUE TITLE
[German] AdGuard 2.6 typing mistake

### ISSUE THREAD

**Issue by iDjay** [AdguardTeam/AdguardForMac#961]
Sorry guys I had to report it! :D 

It's "andere" not "andre".
<img width="812" alt="Bildschirmfoto 2021-10-15 um 15 39 32" src="https://user-images.githubusercontent.com/83946731/137496733-480aca7f-beb7-44da-a056-147ad83dfc1f.png">

**Comment by Chinaski1** [comment]
Tnx!

We will fix it soon :)

**Comment by Chinaski1** [comment]
Fixed!

Available in the Nightly version: agrd.io/mac_nightly
Will also be included in the next release.
