### ISSUE TITLE
Incompatibility of AdGuard and ESET Cyber Security

### ISSUE THREAD

**Issue by Chamiu** [AdguardTeam/AdguardForMac#966]
I make compatibility list of AdGuard 2.6.0 and the Anti-Virus software.
Please tell me, everyone information.

- compatible (NO problem) : 
- incompatible (HAVE problem)
  - ESET CyberSecurity Pro 6.11.2.0.

or Cyber NO GUARD ?

**Comment by Chinaski1** [comment]
@Chamiu 

In fact, the question of the compatibility of software that uses a network extension is quite sensitive.

AdGuard is compatible with endpoint security (typically used for anti-virus scans of user actions) and content filter (typically used for firewalling), but not compatible with transparent proxy extensions. Some anti-viruses use transparent proxy extensions to filter traffic. So in this case the antivirus and AdGuard cannot work in parallel.

There is a chance that by disabling HTTPS-filtering in your antivirus (thus disabling transparent proxy extensions) you will be able to bring back traffic and ad filtering by Adguard.

**Comment by Chamiu** [comment]
@Chinaski1

> There is a chance that by disabling HTTPS-filtering in your antivirus (thus disabling transparent proxy extensions) you will be able to bring back traffic and ad filtering by Adguard.

Thanks to information.
ESET CyberSecurity Pro 6.11.2 have ESET Network Protection Proxy.
/Library/SystemExtensions/*random number*/com.eset.network.systemextension
I think better strategy that
- ESET Network Protection Proxy : OFF
- AdGuard 2.6.x : ON

Both have their best and a few, so can you wait for verification?

That's a shame that I can't find anything without a proxy feature in consumer Anti-Virus software.
What do the AdGuard team use?
I also wanted to know compatibility information for users other than me.

**Comment by Chamiu** [comment]
The cause is unknown, but there is no problem in the following environment.

- AdGuard 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72) : Apple Silicon ver.
- ESET CyberSecurity Pro 6.11.100.0 : Intel with Rosetta 2
- macOS Monterey.2.1 : Apple Silicon
- MacBook Air Late 2020 (Apple Silicon)

Noticeable environmental changes are as follows.

1. uninstall AdGuard 2.5.3.955 release (CL-1.7.200)
2. install AdGuard 2.7.0.1094 release (CL-1.8.276, DNS-1.6.72)

**Comment by Aydinv13** [comment]
@Chamiu is this compatibility issue still reproducible with the latest version of AdGuard For Mac?

**Comment by Chamiu** [comment]
@Aydinv13

> @Chamiu is this compatibility issue still reproducible with the latest version of AdGuard For Mac?

Compatible my environment.
- AdGuard 2.9.0.1166 beta
- ESET CyberSecurity Pro 6.11.100.0
- macOS Monterey.5.1
- MacBook Air Late 2020
- Apple Silicon

**Comment by Aydinv13** [comment]
@Chamiu I'm closing this issue then, reopen it if the problem occurs again.
