### ISSUE TITLE
Unclear how AdguardForMac is combined with browser extensions

### ISSUE THREAD

**Issue by ploum** [AdguardTeam/AdguardForMac#97]
This is not a technical bug but mostly a documentation/workflow bug.

As an Adguard user, it is unclear how AdguardOSX (and Adguard Windows) are acting when combined with Adguard for Safari or Chrome.
- Should both be installed ?
- What happens if Adguard is not installed in the browser ?
- What happens when both are installed but one is temporary disabled ?

I believe that users should be guided more toward this process to understand what is happening. 

One idea would be to automatically redirect a browser to an explanation page if the browser extension can be installed/removed.

**Comment by ameshkov** [comment]
Chrome extension currently works in the so-called "integration mode" when desktop app is detected:
https://adguard.com/en/adguard-adblock-browser-extension/integration-mode.html#integrationMode

This integration mode is not supported by Safari extension though.

> I believe that users should be guided more toward this process to understand what is happening.

Yes, totally.

> One idea would be to automatically redirect a browser to an explanation page if the browser extension can be installed/removed.

For instance, extension may show an information popup when desktop app is detected for the first time.
