### ISSUE TITLE
Incompatibility with AirDrop on macOS Monterey

### ISSUE THREAD

**Issue by yanxin152133** [AdguardTeam/AdguardForMac#973]
![image](https://user-images.githubusercontent.com/43341537/138836311-776d8c52-650d-4bcf-a681-1124fabdd551.png)
![image](https://user-images.githubusercontent.com/43341537/138836400-ad00f67f-501e-4da1-b8fb-1912d1d172cb.png)
![image](https://user-images.githubusercontent.com/43341537/138836428-41d36f80-cbba-4824-b459-2c4d0184dd9c.png)

With this version set as follows, macOS Monterey 12.0.1 will not be able to use airdrop to transfer files to other devices.If you choose another filter mode, you can use airdrop.
Is there anyone in the same situation as me?

**Comment by danidoedel** [comment]
Ohh glad this is fixed in the latest nightly release. Thanks!

**Comment by back21ness** [comment]
Guys, you really should release some updated build with this issue fixed. I was quite frustrated to come across broken AirDrop on two news Macs. Glad that I was able to quickly locate the problem.

Original post was done one month ago, yet the very same AdGuard version that breaks AirDrop is still being distributed now. This is... sad news really.

**Comment by nicholascarey** [comment]
**F%^&Ing seriously?**  

I spent **two hours** yesterday troubleshooting AirDrop not working between my two Macs and now I find out it was bloody AdGuard! And it's been an known issue for an entire month? On an OS that has been in beta for 5 months?  I didn't even come here for this problem - came for an entirely different one! I just happened to spot this issue and the penny dropped. 

I bought a lifetime license for the Mac App and I'm about ready to move on to a different solution. It seems like this it is barely tested at all and the documentation and support for newer versions is almost non-existent.

**Comment by danidoedel** [comment]
> **F%^&Ing seriously?**  
> 
> 
> 
> I spent **two hours** yesterday (unsuccessfully) troubleshooting AirDrop not working between my two Macs and now I find out it was bloody AdGuard! And it's been an known issue for an entire month? On an OS that has been in beta for 5 months?  I didn't even come here for this problem - I came for an entirely different one! I just happened to spot this issue and the penny dropped. 
> 
> 
> 
> I bought a lifetime license for the Mac App and I'm about ready to move on to a different solution. It seems like it is barely tested at all and the documentation and support for newer versions is almost non-existent.

Testing a whole OS won't be possible though so bugs will always happen. 
But releasing a big fix update would be possible, not sure why they don't do it.

**Comment by nicholascarey** [comment]
Not sure what you mean. Testing common functionality under a new OS or release should be the bare minimum... 

The other issue that brought me here was that AdGuard is apparently incompatible with iCloud Private Relay. Well, good luck finding out that information. One of the banner new features of macOS Monterey and there is **zero** mention of AdGuard being incompatible with it in the release notes, FAQ, or knowledge base, including in the release notes for the {Monterey compatible version}(https://adguard.com/en/blog/adguard-for-mac-2-6.html).  Apart from a couple of [brief](https://forum.adguard.com/index.php?threads/adguard-icloud-private-relay-issue.45056/) [replies](https://forum.adguard.com/index.php?threads/adguard-and-private-relay.45469/#post-216077) on the forums there is no documentation or explanation of this fact, and the direct support contact I had failed to suggest it as the casue of my problems with the app either. I had to figure it out myself.

**Comment by danidoedel** [comment]
> Not sure what you mean. Testing common functionality under a new OS or release should be the bare minimum... 
> 
> 
> 
> The other issue that brought me here was that AdGuard is apparently incompatible with iCloud Private Relay. Well, good luck finding out that information. One of the banner new features of macOS Monterey and there is **zero** mention of AdGuard being incompatible with it in the release notes, FAQ, or knowledge base, including in the release notes for the [Monterey compatible version](https://adguard.com/en/blog/adguard-for-mac-2-6.html).  Apart from a couple of [brief](https://forum.adguard.com/index.php?threads/adguard-icloud-private-relay-issue.45056/) [replies](https://forum.adguard.com/index.php?threads/adguard-and-private-relay.45469/#post-216077) on the forums there is no documentation or explanation of this fact, and the direct support contact I had failed to suggest it as the cause of my problems with the app either. I had to figure it out myself. 

So how do you define common functionality? There's a lot of "common functionality" in macOS. Good luck testing everything. Even Apple fails doing so or why are the macOS releases filled with bugs?

**Comment by nicholascarey** [comment]
As noted [above](https://github.com/AdguardTeam/AdguardForMac/issues/973#issuecomment-952494318) the AdGuard defaults on a clean install of macOS 12 breaks AirDrop. I would say a feature such as AirDrop (even setting aside from the fact it relies on the network connection that AdGuard is filtering) is the very definition of common functionality.

**Comment by Chinaski1** [comment]
We are working hard on the release version. But unfortunately, we encountered a number of problems that made it impossible to produce the release in the shortest possible time.

We apologize for the inconvenience.

**Comment by ruchern-chong** [comment]
> We are working hard on the release version. But unfortunately, we encountered a number of problems that made it impossible to produce the release in the shortest possible time.
> 
> We apologize for the inconvenience.

Why is this so? Can't this be released from a branch and merged back into the main later?

**Comment by ruchern-chong** [comment]
Seemed like this is now added to v2.7.0

**Comment by Chinaski1** [comment]
@ruchern-chong 

Quite right :)

In version 2.7.0 this issue has been fixed!

**Comment by ruchern-chong** [comment]
> @ruchern-chong
> 
> Quite right :)
> 
> In version 2.7.0 this issue has been fixed!

I have just installed this and tested. Confirmed working!
