### ISSUE TITLE
Make Adguard abide the system certificate store or use a custom CA store

### ISSUE THREAD

**Issue by inume** [AdguardTeam/AdguardForMac#980]
I'm not 100% sure if it is a bug or expected behavior.
On Mac OS Monterey with Adguard installed it seems when Adguard is used for proxying traffic that the system CA store is ignored. This either means Adguard uses its own CA store (in that case it would be expected) or it somehow works around the settings in MacOS. I'd consider this a security issue.
In case Adguard uses its own CA store could you document that and maybe somehow make that configurable.
It would be great if it would work with the native (customized) CA store from MacOS :) 

### Steps to reproduce

In Keychain remove trust from all root CAs in the system roots CA store.
Alternatively distrust selected ones, just make sure that you distrust those which are used on a website for a later test.
Run Adguard.
Connect to any website or to a website where you revoked trust for its used root CA.

### Expected behavior
Adguard or the website should throw some certificate error on connecting to a website where trust for the root CA was revoked.

### Actual behavior
Proxied connections to the website are successfully bypassing the system root CA store.

### Your environment
Mac M1 with Monterey
Automatic proxy mode was used (service could not start with Network extension mode)

**Comment by ameshkov** [comment]
Issue moved to [AdguardTeam/CoreLibs #1540](https://github.com/AdguardTeam/CoreLibs/issues/1540) via [**ZenHub**](https://www.zenhub.com/)
