### ISSUE TITLE
AdGuard blocks mp4 upload via icloud.com/iclouddrive

### ISSUE THREAD

**Issue by jslawler** [AdguardTeam/AdguardForMac#981]
When AdGuard for macOS is turned on, mp4 files seem to fail uploading, producing the iCloud Drive error "Try uploading the file again later."

When AdGuard for macOS is turned off, the file successfully uploads.

### Steps to reproduce

1. Enable AdGuard for macOS
2. Login to https://www.icloud.com/iclouddrive/
3. Upload mp4

### Expected behavior
File is uploaded successfully

### Actual behavior
Error message stating "xx.mp4” couldn’t be uploaded."

<details><summary>Screenshot:</summary>

<img width="653" alt="Screen Shot 2021-11-03 at 11 50 48" src="https://user-images.githubusercontent.com/6005161/139999873-bfb5c370-6564-4381-b15d-89f8dfa9c304.png">
</details>

### Customer ID 
549977

### Your environment

* Environment name and version: (e.g. Chrome 59): macOS 12.1, Chrome 96
* Any specific potentially conflicting software installed: AdGuard for macOS Application version 2.6.1.1051 release (CL-1.8.221, DNS-1.6.58)

**Comment by Chinaski1** [comment]
Hello there!

I tried to reproduce the specified issue but don't account for any problems on my side with the same configurations.

At first glance, the issue is related to the DNS settings. Please, try to choose any other DNS server or disable the NextDNS profile.

**Comment by dnovitskyi** [comment]
logs received: z549977

**Comment by Chinaski1** [comment]
@jslawler 

The last evening we released a Nightly version which supposedly solves the issue with uploading files.

Could you install it and check if the issue persists?

Download link: agrd.io/mac_nightly

**Comment by jslawler** [comment]
> @jslawler
> 
> The last evening we released a Nightly version which supposedly solves the issue with uploading files.
> 
> Could you install it and check if the issue persists?
> 
> Download link: agrd.io/mac_nightly

As far as I can tell, the issue doesn't exist anymore after uploading a .dmg, .pkg, and a .zip, all >~100mb. As that occasion is the first time I've had to use iCloud Web since 2016, I doubt I'll be using it extensively anytime soon.

Issue closed as resolved.
