### ISSUE TITLE
Adguard does not work with Bitdefender's system extension (BDLDaemon)

### ISSUE THREAD

**Issue by validatedev** [AdguardTeam/AdguardForMac#982]
### Steps to reproduce

1. Activate both Bitdefender and Adguard with Network Extension mode
2. Go to one of the AdBlock testing websites.
3. See many of the ads are not blocked.

### Expected behavior

All of the ads should be blocked.

### Actual behavior

Many of the ads are not blocked.
All of the ads are blocked either using Automatic Proxy mode or disabling the Bitdefender DCI VPN module (system extension same like the AdGuard's) on the Network section of System Preferences.

<details><summary>Screenshot:</summary>

![image](https://user-images.githubusercontent.com/29679552/140629033-a9d52197-28c9-4974-aa34-06aaa3606140.png)

</details>

### Customer ID 

Cannot see any Customer ID but the associated ticket number for the case is 551191.

### Your environment

* Environment name and version: Microsoft Edge 95.0.1020.44 with macOS Monterey 12.0.1
* Any specific potentially conflicting software installed: Bitdefender, native macOS Firewall is also active.
* Also, `network.extension.monterey.force.split.tunnel=true`

**Comment by validatedev** [comment]
You can see from the screenshot that Adguard's VPN is not active because I'm using Automatic Proxy at the moment. Normally, both of the VPN sections are "Connected".

**Comment by Chinaski1** [comment]
Hello there!

In fact, the question of the compatibility of software that uses a network extension is quite sensitive.

AdGuard is compatible with endpoint security (typically used for anti-virus scans of user actions) and content filter (typically used for firewalling), but not compatible with transparent proxy extensions. Some anti-viruses use transparent proxy extensions to filter traffic. So in this case the antivirus and AdGuard cannot work in parallel.

There is a chance that by disabling HTTPS-filtering in your antivirus (thus disabling transparent proxy extensions) you will be able to bring back traffic and ad filtering by Adguard.

**Comment by validatedev** [comment]
Thanks for the response! I'm happy with Automatic Proxy atm, though. Looks like there's nothing to do on Adguard's side. Closing.
