### ISSUE TITLE
Kernel panic on mac os big sur

### ISSUE THREAD

**Issue by darinav** [AdguardTeam/AdguardForMac#985]
### Steps to reproduce

1. Install AdGuard
2. Wait
3. ???
4. Kernel panic

### Expected behavior

My mac should not shut down

### Actual behavior

It shuts down

<details><summary>Log:</summary>
[panic.txt](https://github.com/AdguardTeam/AdguardForMac/files/7519229/panic.txt)

</details>

### Customer ID 

Only got a ticket number in the mail: 552458

### Your environment

* Environment name and version: (e.g. Chrome 59):

Chrome Version 95.0.4638.69 (Official Build)

* Any specific potentially conflicting software installed: (e.g. antiviruses, firewalls, traffic counters, cleaners)

Carbon black cloud
Umbrella roaming client

**Comment by Chinaski1** [comment]
Hello @darinav 

I would like to clarify some information:
- Kernel Panic occur immediately after starting the application, or after some time?
- Do you use a third-party VPN service or DNS-proxy profile?

**Comment by darinav** [comment]
@Chinaski1 Not immediately, from what I noticed, it happens when I'm doing something in Chrome
Yes, I'm using openVPN, bur no DNS or proxy profiles

**Comment by Chinaski1** [comment]
Hello @darinav 

Sorry for the late reply. Judging by the logs you have dnscrypt-proxy somewhere in the system.
Try to find out what application is using it and disable it.

Alternatively, you can try using AdGuard in PAC mode.
Open AdGuard settngs -> Network tab -> [Select Mode](https://uploads.adguard.com/Chinaskigmk23.png) -> Automatic proxy

**Comment by darinav** [comment]
Unfortunately, I can't disable it, as it's a company policy.
I will give auto mode a try, and will let you know.
Having download issues with adguard lately ;(

**Comment by Chinaski1** [comment]
@darinav

Any news?

**Comment by darinav** [comment]
@Chinaski1 no, I'm afraid IT blocked adGuard installer download, after my mac crashed several times, so I can't test it. But probably you could try reproducing the issue with some dnscrypt-proxy app, if you even want to. I think this ticket can be closed for now, I'll let you know about any updates =)
Thanks!
