### ISSUE TITLE
Memory leak (probably) on adguard_dns process (1.2 GB)

### ISSUE THREAD

**Issue by validatedev** [AdguardTeam/AdguardForMac#986]
### Steps to reproduce

1. Use Adguard a period of time without restarting the computer

### Expected behavior

Memory usage should be lower.

### Actual behavior

Memory usage is so high of adguard_dns. (nearly 1.2 GB)

<details><summary>Screenshot:</summary>
<img width="1059" alt="Screen Shot 2021-11-12 at 06 02 34" src="https://user-images.githubusercontent.com/29679552/141401923-64bf0bcf-262a-4802-96a5-542fc5051485.png">
<img width="671" alt="Screen Shot 2021-11-12 at 06 08 00" src="https://user-images.githubusercontent.com/29679552/141402430-d4b670f9-0066-4b7b-a96d-dbc2d07926df.png">
<img width="671" alt="Screen Shot 2021-11-12 at 06 08 10" src="https://user-images.githubusercontent.com/29679552/141402436-c8ecb40e-db7c-4cfd-90c1-8bfd37f3bd64.png">

</details>

### Customer ID 

Ticket number: 552668

### Your environment

Environment name and version: Microsoft Edge 95.0.1020.44 with macOS Monterey 12.0.1
Any specific potentially conflicting software installed: Bitdefender, native macOS Firewall is also active.
Also, `network.extension.monterey.force.split.tunnel=true`
Application version 2.6.1.1051 release (CL-1.8.221, DNS-1.6.58)

Sample of the process:
[Sample of adguard_dns.txt](https://github.com/AdguardTeam/AdguardForMac/files/7524591/Sample.of.adguard_dns.txt)

**Comment by Chinaski1** [comment]
Hello there!
Sorry for the late reply.

Presumably, this leak should be fixed in the Nightly version.
Could you update and check if the issue is still reproduced?

Download Nightly via [direct link](http://agrd.io/mac_nightyl).

**Comment by validatedev** [comment]
Actually, I did encounter the issue only once, even using the stable. I cannot reproduce the issue anymore. Closing the issue.
