### ISSUE TITLE
AdGuard messes up Microsoft Edge new tab layout

### ISSUE THREAD

**Issue by Slavsquat** [AdguardTeam/AdguardForMac#987]
### Steps to reproduce

1. Make sure you don’t have any plugins altering the new tab interface
2. Open a new tab

### Expected behavior

The new tab interface only has the search bar + links or articles, depending on your settings. Its layout is not altered.

### Actual behavior

The new tab interface has some cookie policy stuff all over the background, and the whole layout is shifted. If AdGuard is disabled through the system menu bar item, everything comes back to normal after a refresh.

<details><summary>Screenshot:
</summary>
![image](https://user-images.githubusercontent.com/72618413/141997340-eca11d35-e678-4bb6-87d5-26985dd90637.png)

</details>

### Your environment

* Environment name and version: (e.g. Chrome 59): Edge 95.0.1020.53 (stable), macOS 12.0.1
* Any specific potentially conflicting software installed: can't think of anything

**Comment by Chinaski1** [comment]
Hello there!

This issue should be fixed in the Nightly version.
Please, install it and let us know how it goes.

Download link: http://agrd.io/mac_nightly

**Comment by Slavsquat** [comment]
Ah, that’s good to hear. Should I uninstall the regular version first? If so, will I lose any settings?

**Comment by Chinaski1** [comment]
There is no need to uninstall the release version.

Just install Nightly (settings will be transferred).

**Comment by Chinaski1** [comment]
Open `Applications` -> Move`AdGuard` to the bin -> Install [release version](http://agrd.io/mac)

**Comment by Slavsquat** [comment]
It worked, and none of my settings or stats were lost. Thank you!
