### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by anderworx** [AdguardTeam/AdguardForMac#99]
Help. This is happening. Consistently hovers between 100% and 120% when running.
<img width="875" alt="screen shot 2016-05-24 at 10 47 13 am" src="https://cloud.githubusercontent.com/assets/19155250/15510548/82aacb7e-219d-11e6-9bb8-0c91ecc157af.png">

**Comment by Stillness-2** [comment]
1.2.0?

**Comment by anderworx** [comment]
Yes. But, I just did a full uninstall, then installed 1.2.1 beta and it seems to be working better. CPU usage is back to normal.

**Comment by Stillness-2** [comment]
If so, then:

1. Close Adguard
2. remove folder  "/Library/Application Support/com.adguard.Adguard" (from terminal.app with admin privileges `sudo rm -R /Library/Application\ Support/com.adguard.Adguard`)
3. Open Adguard

**Comment by Stillness-2** [comment]
O :) It is #52
