### ISSUE TITLE
air

### ISSUE THREAD

**Issue by alwaleed1992** [AdguardTeam/AdguardForMac#991]
Hello, sorry i didn’t know how to use github and i was on hurry.. the problem is i bought a new MBP 14 inch. And Adguard app messes with airdrop. When i remove the app airdrop works perfectly. When i reinstall it it misses with it. Bare in mind i tried erasing all content and settings on laptop and on the Iphone. TWICE AND DIDN’t work. The problem extends to all other devices not just my iphone.So for now I uninstalled and report the issue until it gets fixed. System is OSX Montery 12.0.1

**Comment by Chinaski1** [comment]
@alwaleed1992 

There is a small problem - the task turned out to be empty :)

Could you give us a little more information?

**Comment by alwaleed1992** [comment]
> @alwaleed1992
> 
> There is a small problem - the task turned out to be empty :)
> 
> Could you give us a little more information?

Hello, sorry i didn’t know how to use github and i was on hurry.. the problem is i bought a new MBP 14 inch. And Adguard app messes with airdrop. When i remove the app airdrop works perfectly. When i reinstall it it misses with it. Bare in mind i tried erasing all content and settings on laptop and on the Iphone. TWICE AND DIDN’t work. The problem extends to all other devices not just my iphone.So for now I uninstalled and report the issue until it gets fixed. System is OSX Montery 12.0.1

**Comment by Chinaski1** [comment]
We have already fix this issue in the latest Nightly version of the AdGuard app.

You can download it via [direct link](http://agrd.io/mac_nightly).

**Comment by Chinaski1** [comment]
I close this issue because it has been solved in the Nightly version of AdGuard for macOS.
