### ISSUE TITLE
Add the ability to disable the script link interception in the Advanced settings

### ISSUE THREAD

**Issue by yzy1228682367** [AdguardTeam/AdguardForMac#992]
![CleanShot 2021-11-19 at 16 01 28@2x](https://user-images.githubusercontent.com/50101175/142586936-6d21a3f8-768d-4430-9057-73662217bf03.png)

**Comment by yzy1228682367** [comment]
And I just want it open in tampermokey.

**Comment by Chinaski1** [comment]
Hello there!

What you need to do:

1. Open `Terminal`
2. `defaults write com.adguard.mac.adguard UserscriptSubscriptionLinkEnabled false`
3. Restart AdGuard and Reload the page
4. Enjoy the result :)

Also, you gave us the idea of adding a function to disable the use of the script manager. Thank you :)

**Comment by yzy1228682367** [comment]
Thanks, it is fixed now.
